sourcegraph/cody

lib/shared/src/utils.test.ts
lib/shared/src/utils.ts

ADO repository URLs follow the format:
`https://dev.azure.com/organization/project/_git/repository` and currently the Sourcegraph enterprise instances remove the protocol, i.e. `https://`, and additionally filter out the `/_git` tag inside the URL:
`https://dev.azure.com/organization/project/_git/repository` -> `dev.azure.com/organization/project/repository`
However, the VS Code extension for Cody currently only has logic to handle removing the protocol and does not filter the `/_git` from the URL, making automatic pulling of embeddings from an enterprise instance impossible, as the repository names do not match.
As a result, ADO developers must set the `codebase` setting, manually, on a repository by repository basis while using Cody in VS Code if they want embeddings. 
This PR updates …

Fix: Handle Azure DevOps Codebase URLs Automatically from Git Metadata

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

Fixes an issue where the prompt text was added when not intended.

Fix logging issue

---

vscode/CHANGELOG.md
vscode/package.json

Mainly for pushing out #2444 quickly.
- Just a version inc, CI will check

VS Code: Release 1.0.3

---

renovate.json

Basically copying @olafurpg here: https://github.com/sourcegraph/bfg-private/pull/44 in an attempt to reduce noise from Renovate. I think this will make it so that PRs are only created if we manually trigger it.
Guess we land it and see if it works? Only a dev tool with no customer impact though.

Only open renovate PRs manually

---

vscode/CHANGELOG.md
vscode/src/completions/get-inline-completions-tests/no-request-when-accepting.test.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/inline-completion-item-provider.ts

This is a small optimization that should cut down a bit on unnecessary LLM request:
In VS Code, if you accept a completion, this changes the document and thus issue a new completion request. Makes sense! The thing is: we always complete full lines so the chance that you do want a follow-up completion is _very_ slim. In some cases the ending `)` or `;` helps to guard against this but not in all cases. 
This PR adds a special logic now to detect this case and not issue a completion (so accepting a completion via `tab` won't issue a new request but any further keystroke (like `enter`) will).
- Added tests
- 
https://github.com/sourcegraph/cody/assets/458591/83d9c044-a886-4e72-90bf-d2c1486f260e

Autocomplete: Do not trigger a completion if a single-line completion was accepted

---

agent/src/index.test.ts
agent/src/vscode-shim.ts
cli/src/client/context.ts
lib/shared/src/chat/client.ts
lib/shared/src/chat/transcript/transcript.test.ts
lib/shared/src/chat/useClient.ts
lib/shared/src/codebase-context/index.ts
lib/shared/src/configuration.ts
lib/shared/src/test/mocks.ts
slack/src/services/codebase-context.ts
vscode/CHANGELOG.md
vscode/package.json
vscode/src/chat/ContextProvider.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/protocol.ts
vscode/src/completions/get-inline-completions-tests/analytics.test.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/logger.test.ts
vscode/src/completions/logger.ts
vscode/src/completions/providers/create-provider.test.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/extension.common.ts
vscode/src/external-services.ts
vscode/src/jsonrpc/agent-protocol.ts
vscode/src/services/OpenTelemetryService.node.ts
vscode/src/services/sentry/sentry.ts
vscode/webviews/App.tsx

This refactors the `Config` object to no longer expose a `serverEndpoint`. The `serverEndpoint` should be retrieved only from local storage as part of the authenticated user. When going through this legacy code part, the server endpoint would always be set to the dotcom instance URL instead.
This caused some parts to behave like you were on dotcom even when inside an enterprise version.
- I tested it by evaluating analytics logs and switching accounts
- Video is large so uploading it on Google Drive instead: https://drive.google.com/file/d/1dpn-C1IczJ9CQ0zX6evMyzKpHpq8lIvS/view?usp=sharing

Remove serverEndpoint from config object

---

.github/workflows/stale.yml

This PR adds the stale action to automatically detect and close stale issues and PRs. 
I configured it so that issues will be marked as stale after 60 days of no activity and will be closed within 5 days unless manually interfered.
I’m personally up for even more aggressive timeouts, e.g. 30 days are enough, just because of how fast we move here but I’m happy to settle on something larger.
We see if issues close huh

RFC: Detect and close stale issues and PRs

---

vscode/CHANGELOG.md
vscode/package.json

Preparing a release PR to ship #2456
- Just a version increase in prep for the release

VS Code: Release 1.0.4

---

lib/shared/src/sourcegraph-api/completions/nodeClient.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

- Close the upstream in the typewriter to avoid raising an error and potentially crashing the agent.
- Trigger error once per completion request to avoid uncaught errors like `ECONNRESET` being bubbled upstream after the request is aborted.
- [Slack thread.](https://sourcegraph.slack.com/archives/C059N5FRYG3/p1703180240925439)
1. Start a new chat in VS Code.
2. Cancel token sampling in the middle of response streaming.
3. Observe no uncaught errors in the Cody output channels.

VS Code: call the error callback only once per request

---

lib/ui/package.json
lib/ui/src/chat/components/EnhancedContext.tsx
pnpm-lock.yaml
vscode/src/chat/chat-view/ChatPanelProvider.ts
vscode/src/chat/chat-view/CodebaseStatusProvider.ts
vscode/src/chat/chat-view/SidebarChatProvider.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/chat-helpers.test.ts
vscode/src/chat/chat-view/chat-helpers.ts
vscode/src/chat/protocol.ts
vscode/src/services/utils/workspace-action.ts
vscode/webviews/Components/FileLink.tsx

Previously, we used the relative file name to indicate the source file of all context snippets. This causes problems, because:
* The user may have more than one workspace folder open, in which case we don't know how to resolve a relative file name, because we lose track of which workspace folder it came from
* Context from remote sources (e.g., remote embeddings) isn't attached to a local file, and we may need to treat these differently when trying to open the file
Add a URI field to keep better track of the true location of a context item. Adds creator functions for 2 URI schemes: `cody-file-relative://` and `cody-embeddings://`.
Also add an `openUri` function that handles opening these URIs and is more forgiving for `file://` URIs (will attempt to match a relative file URI with an open …

Pass URIs for some context snippets

---

vscode/src/completions/providers/unstable-openai.ts

Closes #2524
Regression introduced by accident [here](https://github.com/sourcegraph/cody/pull/2426/files#diff-9ed150d2122201c9bf34be216ad0ceb4d367cbc653ff240cc8408d29bf19c131R131) where a different parameter for completion request is used.
Tested manually

OpenAI provider requires use of topP parameter

---

lib/shared/src/sourcegraph-api/completions/nodeClient.ts

- Removes redundant `abortSignal` from the completions `stream` function. It's not exposed to the outside world, so it cannot affect the execution flow of the request. @abeatrix, let me know if I misunderstood the code here.
1. CI
2. Tested manually that the "stop generating" chat feature works as expected.

VS Code: remove redundant abort controller

---

lib/shared/src/sourcegraph-api/environments.ts
lib/ui/src/Chat.tsx
lib/ui/src/chat/ErrorItem.tsx
lib/ui/src/chat/Transcript.tsx
lib/ui/src/chat/TranscriptItem.tsx
vscode/src/chat/protocol.ts
vscode/src/chat/utils.test.ts
vscode/src/chat/utils.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/test/e2e/chat.test.ts
vscode/webviews/App.tsx
web/src/App.tsx
web/src/Chat.tsx

- Fixes the issue caused by the fact that `userInfo` [was not available](https://github.com/sourcegraph/cody/pull/2057/files#diff-3ef5ec11a5cb8846141e4fc4e08c5502837d912d07e00fadfbfa25187bdc0d84R20) in the critical place required for a telemetry event creation. This PR makes `userInfo` a required prop in the React component tree for all the intermediate components to avoid such an issue in the future. It sets the `userInfo` value to `{ isDotComUser: true, isCodyProUser: false }` for the components reused in the web version. @chenkc805, let me know if other default values make more sense.
- Closes https://github.com/sourcegraph/cody/issues/2468
- [Slack thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1703205833741309)
- Hit the rate limit events as a DotCom user and ensure the …

VS Code: require `userInfo` prop

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/commands/CommandsController.ts

Close https://github.com/sourcegraph/cody/issues/2536
1. Removed the 'addEnhancedContext' parameter from the addCommand() method in CommandsController. 
2. All commands should be run without enhancedContext unless it's specified in the cody.json to include `codybase` as context
We previously added extra context to custom command which caused confusion to LLM and affected command quality. 
1. Highlight some code in a file
2. Run `/smell` command
4. Check and make sure only 1 file (current file) is used as context.
Before:
On top of the current file, it would add other unrelated files as enhanced context
After:
It should only use the correct file as context and nothing else

fix: remove enhanced context from commands

---

vscode/webviews/Chat.tsx

- Removes redundant logic from the abort streaming click handler. @abeatrix, let me know if I misunderstood the code here.
1. CI
2. Tested manually that the "stop generating" chat feature works as expected.

VS Code: remove redundant cancellation logic from the click handler

---

vscode/src/completions/get-inline-completions.ts
vscode/src/completions/request-manager.test.ts
vscode/src/completions/request-manager.ts

- Bypass request manager cache on manual completion triggers.
- We already have the last candidate cache disabled for this case. The request manager cache was implemented after that we never got to skipping it too. 
- Use the keyboard shortcut to trigger a completion generation multiple times at the same cursor position.
- Every time, a new request should be issued according to Cody's output channel.

Autocomplete: skip request manager cache on manual completion trigger

---

lib/shared/src/chat/prompts/index.ts
lib/shared/src/chat/transcript/messages.ts
vscode/CHANGELOG.md
vscode/src/commands/CommandRunner.ts
vscode/src/main.ts

- Removes `inline` from `CodyPromptMode`
- Logs non-edit commands only in CommandRunner Close https://github.com/sourcegraph/cody/issues/2545
https://github.com/sourcegraph/cody/assets/68532117/6a9a5fdb-b3ff-4fcd-bfdb-ced9dde3fc10
1. Run the `doc` command, only `CodyVSCodeExtension:command:doc:executed` should be logged without `CodyVSCodeExtension:command:edit:executed`
Log for example:
```
█ logEvent (telemetry disabled): CodyVSCodeExtension:command:doc:executed VSCode {"properties":{"source":"doc"},"opts":{"hasV2Event":true}}
█ telemetry-v2: recordEvent (no-op): cody.command.doc/executed: {"parameters":{"version":0,"privateMetadata":{"source":"doc"}},"timestamp":"2024-01-03T15:57:44.677Z"}
█ logEvent (telemetry disabled): CodyVSCodeExtension:recipe:fixup:executed VSCode …
```

refactor: remove command inline mode

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

Before, if both embeddings search methods fail then we display an error in chat. Now, we just log the error and fall back to local keyword search. This avoids a situation we've seen at customer sites where they hit the embeddings rate limit, then their users run into a bunch of errors in chats. 
I don't think this is actually a change in behavior, because the local embeddings client swallows errors and returns "no results", which caused us to fall back to keyword search (accidentally?) It really just clarifies the logic.
Updated embeddings search methods to throw errors (just for testing), and checked we still produce codebase context.

Chat: fallback to local keyword search when embeddings fail

---

lib/shared/src/chat/ignore-helper.ts
vscode/CHANGELOG.md
vscode/src/services/context-filter.ts

- Renames the ignore filename for Cody from `.cody/.ignore` to `.cody/ignore` for simplicity. 
- Updates references across the codebase.
- build from this branch and create a `.cody/ignore` file in the root of the workspace
- add a directory e.g. `vscode/**` to the file then save
- open a file from that directory and then highlight some code
- ask cody to explain selected code
- cody should tell you there is no selected code to explain, and if you check the context files, you will see there is no files from the ignored directory was shared with cody

refactor: rename .cody/.ignore to .cody/ignore

---

lib/ui/src/Chat.tsx

Close https://github.com/sourcegraph/cody/issues/2383
The previous check for Ctrl or AltGraph being pressed was too broad and prevented some default browser shortcuts from working properly, and created blockers for users on different keyboard layouts
This fixes it by checking specifically for Ctrl keys combo only.
Alt + C is still prevented. 
1. Try using alt + key combos when focusing in input box - this should now work
2. Try pressing alt + c when focusing in input box - this should open the command menu

fix: only prevent default on Ctrl key combo

---

lib/ui/src/chat/ErrorItem.module.css
lib/ui/src/chat/ErrorItem.tsx
lib/ui/src/chat/TranscriptItem.tsx
vscode/CHANGELOG.md

This PR addresses the issue mentioned in https://github.com/sourcegraph/cody/issues/2539, where long response from chat gpt 4.0 will resulted in error, and the error message will replace the response text from Cody.
- Display error message in additional to the text that cody has already responded 
- Add new styles for .request-error and .request-error-title classes.
- Update ErrorItem.tsx to use new CSS classes for request error display.
1. Switch chat to use chat gpt 4.0
2. Open a large file and select the whole file
3. Run the /test command
4. If the response is longer than the answer limit, it should display an error message after the text that Cody has already responsed
- before: the text will be replaced with the error message …

fix: show error after Cody response in chat UI

---

agent/package.json
agent/recordings/FullConfig_234680970/recording.har
agent/src/cli/jsonrpc.ts
pnpm-lock.yaml

@olafurpg I still see quite a lot of changes here, I think some of it is because of ordering. I noticed we're setting [disableSortingHarEntries](https://netflix.github.io/pollyjs/#/configuration?id=disablesortingharentries) although after reading the docs it's not clear to me why _not_ sorting would improve diffs - seems like the opposite should be true? 🤔
There are a still a lot of "junk" headers in the HAR file that don't necessarily change on each run, but might be worth removing just to make the file smaller (for example `x-frame-options`). Let me know if you think they should be stripped.
(I haven't looked at the format yet, will do that separately, easy stuff first 🙂)
- Re-record Polly recordings before this change and note large diff that contains many timestamps and cookies that …

Clean up Polly recordings to reduce diffs when re-recording

---

agent/recordings/FullConfig_234680970/recording.har
agent/src/index.test.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/prompt.ts
vscode/test/integration/chat.test.ts

CLOSE https://github.com/sourcegraph/cody/issues/2360
Address issue described in https://github.com/sourcegraph/cody/pull/2575#issuecomment-1878567430
run the agent test

fix: append file to command request only

---

vscode/test/fixtures/mock-server.ts

This PR adds the install and auth events to the loggedEvents variable in e2e tests. Previously these events were omitted to avoid bottlenecking developers when creating new tests. However, since most tests are not doing a holistic validation of all events, it makes sense to add these events back so they can be verified within each test as needed.
By including these events in loggedEvents, individual tests can now assert that the expected install/auth events are fired without having to repeat setup logic. This will make it easier to validate these important events are logged correctly from various entry points.
All tests passed via `pnpm test:e2e`

Add install/auth events to `loggedEvents` in e2e tests

---

vscode/CHANGELOG.md
vscode/src/editor/utils/editor-context.test.ts
vscode/src/editor/utils/editor-context.ts

Fixes https://github.com/sourcegraph/cody/issues/2401 by removing `bin/` from the ignore list and instead just penalizing it unless you have typed `bin` in the query specifically.
https://github.com/sourcegraph/cody/assets/1078012/2ad0ef3b-b2f9-45bd-bfc0-54fd77811511
- Run `pnpm test:unit` and ensure the new tests pass
- Open a project with a file in a folder named `bin` and ensure the file shows up in search results, near the bottom unless you've explicitly typed "bin"

Remove "bin/" from search ignore and just rank low unless typed

---

vscode/src/services/context-filter.ts

Fixes https://github.com/sourcegraph/cody/issues/2586
- Open a folder that is not a Git repo / codebase
- Set `"cody.internal.unstable": true` to enable ignore functionality
- Create a `.cody/ignore` file containing "*.ignore"
- Create files "foo.not" and "foo.ignore"
- Type "@foo" in chat and ensure the `.ignore` file is not shown

Don't skip setting ignore files when not in a codebase

---

vscode/src/completions/get-inline-completions-tests/last-candidate.test.ts
vscode/src/completions/reuse-last-candidate.ts

- It was a tricky one to pinpoint because of the time-sensitive nature of the bug. It happens when a user initializes a completion generation by placing a cursor on the new line and then almost instantly tabs 2+ times. For example: 
```ts
function test() {
█
}
```
The initial completion generation request comes back in the background with the insert-text: `\t\tconst x = 1`, but a user already added three tabs manually:
```ts
function test() {
█
}
```
We reuse (`reuseLastCandidate`) the initial completion that was generated in the background because only whitespace on the current line was changed, and the previous logic returned the final insert text as the following: `lastTriggerCurrentLinePrefixInDocument.slice(currentLinePrefix.length) + item.insertText` which didn't account for leading …

Autocomplete: adjust leading whitespace in the last candidate text on indentation

---

.gitattributes

I haven't manually tested this change works as expected. I only manually validated the glob pattern is correct
```
❯ ls agent/recordings/*/*.har
agent/recordings/FullConfig_234680970/recording.har
```
This SO answer mentions how to do this https://stackoverflow.com/questions/4515679/git-workflow-can-i-prevent-a-certain-file-from-being-merged-to-another-branch-b

Specify git merge strategy for HTTP recording file

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

refactor: rename chat question events
- Rename chat events 
- from `chat-question:recipe-used` to `chat-question:executed`
- from `cody.recipe.chat-question.recipe-used` to `cody.chat-question.executed`
- Avoid logging the chat events when the question is triggered by a command to prevent duplicate events.
Ask Cody a question and check the log:
```
█ logEvent (telemetry disabled): CodyVSCodeExtension:chat-question:executed VSCode {"properties":{"requestID":"9da457b4-ff82-4304-b3c1-042e4920ac1e","chatModel":"anthropic/claude-2.0","promptText":"hello","contextSummary":{}},"opts":{"hasV2Event":true}}
█ telemetry-v2: recordEvent (no-op): cody.chat-question/executed: {"parameters":{"version":0,"metadata":[]},"timestamp":"2024-01-08T17:46:25.454Z"}
```

refactor: rename chat question events

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

CLOSE https://github.com/sourcegraph/cody/issues/2615
fix: add config to control context fetching strategy
This adds the exisiting 'cody.useContext' config to SimpleChatPanelProvider that allows selecting between 'embeddings', 'keyword', and 'none' strategies for context fetching.
- 'embeddings' will use embeddings-based indexing if available, falling back to keyword search (symf). 
- 'keyword' will only use keyword search-based (symf) context fetching.
- 'none' will limit context to the user's current open file.
The default is now 'embeddings' 
1. Start build from this branch
2. Set `cody.useContext` to `search` to confirm context from embeddings are not added, and context from symf are added (if any)
3. Set `cody.useContext` to `embeddings` to confirm context from embeddings are added …

fix: respect cody.useContext for context fetching

---

vscode/src/completions/first-completion-decoration-handler.ts
vscode/src/completions/format-completion.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/is-completion-visible.ts
vscode/src/completions/suggested-autocomplete-items-cache.ts

- Closes https://github.com/sourcegraph/cody/issues/2570 by moving the telemetry helper call to the early return, where we check for the number of visible completions.
- Simplifies the completions processing logic in `provideInlineCompletionItems()`. We return early if no visible completions are generated, so we can simplify the following logic knowing the completions are available and visible.
- Moves the conversion 
- Extracts the `AutocompleteItem` class and `suggestedCompletionItemIDs` cache into a separate file. Update the interfaces of these entities for better readability.
- Extracts the `isCompletionVisible` function and related helpers into a separate file.
- Extracts `FirstCompletionDecorationHandler` into a separate file.
CI

Autocomplete: split up completion item provider

---

vscode/src/completions/artificial-delay.test.ts
vscode/src/completions/artificial-delay.ts

Tweaks the user based delay system to be less aggressive by:
- Reducing the increments from 200ms to 50ms chunks
- Reducing the maximum delay from 2sec to 1.4sec
c.f. https://sourcegraph.slack.com/archives/C05AGQYD528/p1700829801359009?thread_ts=1700673177.479549&cid=C05AGQYD528
See unit test updates

Autocomplete: Tweak user-delay maximum timer and decrease steps

---

vscode/CHANGELOG.md
vscode/src/edit/execute.ts
vscode/src/edit/manager.ts
vscode/src/edit/prompt/context.ts
vscode/src/edit/prompt/index.ts
vscode/src/non-stop/FixupController.ts
vscode/src/non-stop/FixupTask.ts
vscode/src/non-stop/FixupTypingUI.ts
vscode/src/non-stop/roles.ts

This PR adds the edit functionality for:
- User provided file context, e.g. `@fileName`
- User provided symbol context. e.g. `@#symbolName`
Attempted to get this to closely match the chat fuzzy matching:
- Helpful messages for certain suffixes/no matches
- Icons for different symbols
- Same syntax - `@fileName` and `@#symbolName`
Demo:
https://github.com/sourcegraph/cody/assets/9516420/f37d11f1-2375-41d1-b074-02676390b428
1. Create an edit using `@fileName`
2. Create an edit using `@symbolName`
3. Create an edit using multiple `@fileName` and `@symbolName`
4. Create an edit after removing `@fileName` context, check it doesn't still use it
5. Retry an edit that used `@fileName` or `@symbolName` context, check that the context is still used

Edit: Support user provided files ("@name") and symbols ("@#name")

---

lib/shared/package.json
lib/shared/src/sourcegraph-api/errors.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
pnpm-lock.yaml
vscode/src/completions/client.test.ts
vscode/src/completions/client.ts
vscode/src/fetch.ts

- This PR applies part of the changes from @sqs's Ollama PR: https://github.com/sourcegraph/cody/pull/905, which is not specific to Ollama support.
- Differentiate between HTTP responses on the web and in node.js on the type level. 
- This allows dropping redundant type casting in the autocomplete HTTP client code.
- CI
- Manually tested autocomplete locally.

Autocomplete: use `NodeResponse` in the autocomplete client

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

CLOES https://github.com/sourcegraph/cody/issues/2610
Fix issues where starting edit commands from chat would create two edits
Edit commands are already redirected to the executeEdit function in findCommand, so we should exist early in the command execution flow in chat for edit commands. 
This avoids duplicate handling of edit commands.
- No changelog required as the bug does not exist in released version
- Start the doc command from chat input box
- only one edit should be executed
https://github.com/sourcegraph/cody/assets/68532117/7736cdc4-b65c-4d72-a351-de0c350e5c2b

fix: duplicate edit handling in chat

---

vscode/src/commands/utils/menu.ts
vscode/src/non-stop/FixupController.ts
vscode/src/non-stop/FixupTypingUI.ts

Updates the Edit quick pick title to better reflect functionality and scope:
Changes:
- Update placeholder text
- Add title that shows relative path and range selected
- Remove back button from edit QP when triggered directly. Back button still shows when edit input triggered from command palette
Check QP title and placeholder
Check QP title and placeholder matches original when retrying

Edit: Reflect functionality and scope in quick pick

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/CHANGELOG.md
vscode/src/completions/providers/create-provider.ts

For https://docs.google.com/document/d/1P-Hb8BTbz-vMNFXw3gbAvphArsNvS1_8u4ID-phn8gI/edit, we are considereing moving all traffic to the 16b model. When we first run an experiment for this, the single-line CAR was better with the faster model. Part of this might be due to latency (which will improve with the ST deployment) but parts of this might also just no longer be relevant since we have made so many changes.
This PR adds a new client side feature flag that we can run in the short term to gather data on 16b exclusive setups. It will only have an affect if the user is already inside the `CodyAutocompleteStarCoderHybrid` experiment, which is currently our main StarCoder enablement flag.
- Be inside `CodyAutocompleteStarCoderHybrid`
- Be inside `CodyAutocompleteStarCoder16B`
- Observe …

Autocomplete: Add a new 16b exclusive experiment and document existing flags

---

agent/package.json
agent/src/index.test.ts

See thread in https://sourcegraph.slack.com/archives/C05AGQYD528/p1704748857378909
This makes it so that the unit tests for agent only runs the esbuild portion of the script and not the full build of the workspace root (which can fail for any TS issue in the codebase and leads to confusion)
It does seem like the stdio inheriting does not work because of how vitests isolates different test workers (i.e if the test is run in isolation, the stdio won't be cleared? maybe another test file uses `console.clear`?) In any case it doesn't appear trivial to fix the reporting, so leaving this as-is (Plus I added a comment in the code that is displayed on error on how to get more logs).
- Have a change that does not typecheck, e.g.
```
diff --git a/vscode/src/configuration.ts …
```

Do not require a root build for agent unit tests

---

lib/shared/src/chat/ignore-helper.test.ts
lib/shared/src/chat/ignore-helper.ts
vscode/CHANGELOG.md

CLOSE https://github.com/sourcegraph/cody/issues/2585
Add a check to ignore all non-file URIs in the IgnoreHelper class. 
This prevents Cody from using files that cannot be uploaded remotely or defined in ignore files as context, e.g. unsaved files or vs code user configuration files.
This also fixed an issue where opening a non-file URIs would cause autocomplete to stop working
1. Open vs code config as tab as described by @philipp-spiess in https://sourcegraph.slack.com/archives/C05AGQYD528/p1704815009033359
2. Switch back to a codebase file to make sure autocomplete is still working (unless the file is ignored)
https://github.com/sourcegraph/cody/assets/68532117/fca1e0e1-205e-4d72-8278-f5101609a1bf

fix: ignore all non-file uris by default

---

agent/README.md
agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/rateLimitedClient_2043004676/recording.har.yaml
agent/src/AgentWorkspaceConfiguration.ts
agent/src/__tests__/example-ts/src/animal.ts
agent/src/agent.ts
agent/src/cli/base64.ts
agent/src/cli/jsonrpc.ts
agent/src/index.test.ts
agent/src/vscode-shim.ts
lib/shared/src/chat/typewriter.ts
lib/shared/src/sourcegraph-api/telemetry/GraphQLTelemetryExporter.ts
vscode/src/chat/chat-view/prompt.ts
vscode/src/configuration-keys.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/extension.node.ts
vscode/src/local-context/download-symf.ts
vscode/src/rg.ts
vscode/src/search/SearchViewProvider.ts
vscode/src/services/SecretStorageProvider.ts
vscode/src/testutils/mocks.ts
vscode/test/e2e/install-deps.ts

Fixes https://github.com/sourcegraph/jetbrains/issues/256
Previously, symf was disabled in the agent because the download+unzip logic was failing in Node.js. This PR fixes that problem (along with
several other small issues), and adds a test case to stress the code
path where the user submits a chat message with enhanced context enabled. This test case is disabled for now because symf sends an LLM request that we can't record/replay (since symf is written in Go). The test can be manually enabled locally to test the functionality. It's still useful to merge this PR because it unblocks testing symf context with JetBrains.
**Important**: this PR changes the default context to be keyword-based instead of embeddings-based. This is aligned with our plans for February GA. It's possible to change …

Agent: add symf support and enabled keyword context by default

---

vscode/webviews/Components/ChatModelDropdownMenu.tsx

This PR fixes #2592
https://github.com/sourcegraph/cody/assets/44617923/2c240188-a33a-4795-bd7b-54205ab82c13

fix: Chat Model DropDown

---

vscode/CHANGELOG.md

Adds a missing changelog entry for https://github.com/sourcegraph/cody/pull/2627
Changelog update. All tests are passing.

add missing changelog entry for pull/2627

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

Fix https://sourcegraph.slack.com/archives/C05AGQYD528/p1704845125801249
Close https://github.com/sourcegraph/cody/issues/2649
Added a check for user's authentication status and model selection in the SimpleChatPanelProvider class that will get called on start up. The auth provider's getAuthStatus() method is used to determine if the user is on dotcom and can upgrade (not pro users). 
If so, the default model is selected instead of the last used model that does not associate with the current logged in account status.
1. log into cody with a pro account
2. select a pro-only chat model from dropdown and ask cody a question
3. log out of the account 
4. log into cody again with a dot com free user
5. open a new chat to confirm the default chat model is selected instead of the chat model that …

fix: model selection on start up

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.test.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/testutils/mocks.ts

If a file is `@`-mentioned that is inaccessible or unreadable, Cody chat would hang indefinitely. Now, it skips the file, shows the user an error message, and proceeds with the chat response.
The most likely causes for a file being inaccessible or unreadable are: the file is binary, or the file was removed after the user selected it.
Fix https://github.com/sourcegraph/cody/issues/2390.
Added test case.

skip (instead of hanging indefinitely on) non-text context files

---

vscode/src/configuration.ts

- The stable release Typescript build fails because we remove experimental settings from the `package.json`. 
- Follow-up: we need to run a dry-run release as a CI check.
`cd vscode && CODY_RELEASE_TYPE=stable pnpm release:dry-run`

Autocomplete: hide ollama settings

---

.github/workflows/ci.yml

- Adds vscode release dry-run command to the CI build check to ensure it always succeeds on main.
CI

DX: add `pnpm -C vscode run release:dry-run` to the CI build check

---

agent/src/agent.ts
agent/src/index.test.ts
agent/src/vscode-shim.ts
vscode/src/jsonrpc/agent-protocol.ts

Fixes https://github.com/sourcegraph/jetbrains/issues/257
Previously, the agent didn't support rendering progress bars on the client. This was problematic because symf symbol uses progress bars to inform the user when symf is indexing, and allows users to cancel indexing. This PR closes this feature gap by adding four new JSON-RPC notification endpoints to the agent protocol to deal with progress bars:
* `progress/start`: server to client.
* `progress/report`: server to client.
* `progress/end`: server to client.
* `progress/end`: client to server. Only valid for cancelable progress bars.
Agent clients must add `progressBars: 'enabled'` to the client capabilities during the `initalize` handshake to receive progress-related notifications.
Additionally, to help clients with testing progress …

Agent: add support for client-side progress bars

---

agent/src/agent.ts
vscode/src/services/LocalStorageProvider.ts

(From https://github.com/sourcegraph/jetbrains/issues/281#issuecomment-1884680142) 
The [telemetry logger](https://sourcegraph.com/github.com/sourcegraph/cody@85355f1ca72073518ab7adeb1dcc14d14fc1449a/-/blob/vscode/src/services/telemetry.ts?L48-49) was not being created with the anonymous user ID provided by the agent client for events that were created using a singleton [globalAnonymousUserID](https://sourcegraph.com/github.com/sourcegraph/cody@nsc/global-anonymous-user-id/-/blob/vscode/src/services/telemetry.ts?L16). The recipe events dont https://sourcegraph.com/github.com/sourcegraph/cody@85355f1ca72073518ab7adeb1dcc14d14fc1449a/-/blob/agent/src/agent.ts?L327, as well as events created on the jetbrains plugin side (e.g. `CodyInstalled`), but `CodyJetBrainsPlugin:Auth:connected` and …

agent: return client-provided anonymous user ID from localStorage

---

vscode/CHANGELOG.md
vscode/CONTRIBUTING.md
vscode/package.json

VS Code: Release 1.1.0 release update
version update

VS Code: Release 1.1.0

---

lib/shared/src/sourcegraph-api/errors.ts
vscode/src/completions/inline-completion-item-provider.test.ts

The problem is that we're displaying 160 chats in the error message:
while on the /cody/manage page, we display 20:
Cody Gateway only knows the LLM limits (which is 160 for Free users), and that's what it returns in the error header, so that's all the client knows as well. We should display the official limit of 20 instead, but we can't know it for now on the client side.
So my quick solution is just to hide this info on the UI.
Relying on the VS Code team to test this

VS Code: Disable displaying feature limits

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/rateLimitedClient_2043004676/recording.har.yaml
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
vscode/CHANGELOG.md
vscode/src/services/AuthProvider.ts
vscode/test/fixtures/mock-server.ts

RE: https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1704927255975299
Fix issues where enterprise users are unable to login due when on an older version of Sourcegraph.
Remove codyProEnabled field from GraphQL API call as it's used for both enterprise and dot com users, which does not exist in older enterprise instances.
updating tests

fix: remove codyProEnabled field from GraphQL API call

---

vscode/webviews/Chat.tsx

Issue: https://github.com/sourcegraph/cody/issues/2669
The current build of Cody has an issue where the cursor is stolen many times because of a rerendering of some sort for auth, this makes cody very hard to use for anything as you can barely type.
Original PR that introduced this https://github.com/sourcegraph/cody/pull/2665
I actually do not know how the PR works so I added a throttle mechanism to stop the rerendering for 5 minutes(300 seconds) so that it doesn't make a super terrible UX. 
My aim is to merge this HACK for now and then do a proper fix later with @abeatrix

Fixing Steal Cursor Issue

---

lib/ui/src/chat/components/EnhancedContext.tsx
vscode/test/e2e/at-file-context-selecting.test.ts

It is confusing if these are not shown because the user thinks that the file they *most* wanted is not included in Cody's context.
Discussion: https://sourcegraph.slack.com/archives/C05AGQYD528/p1704952995626909
- `@`-mention a file and ensure it's mentioned in the EnhancedContext

show context files explicitly included (@-mentioned) by user

---

vscode/CHANGELOG.md
vscode/src/completions/get-inline-completions-tests/dynamic-multiline.test.ts
vscode/src/completions/get-inline-completions-tests/multiline-truncation.test.ts
vscode/src/completions/text-processing/truncate-parsed-completion.test.ts
vscode/src/completions/text-processing/truncate-parsed-completion.ts

- Improves the stability of multiline completion truncation during streaming by gracefully handling missing brackets in incomplete code segments.
- Closes #2387 
Added new unit tests.

Autocomplete: insert missing brackets before completion truncation

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/rateLimitedClient_2043004676/recording.har.yaml
agent/src/index.test.ts
lib/shared/src/sourcegraph-api/completions/nodeClient.ts
vscode/src/testutils/CodyPersister.ts

Previously, running `pnpm update-agent-recordings` more or less always
made the agent tests fail because the LLM response had minor changes.
This PR sets the LLM temperature to zero when we run agent tsets, which
should help make the tests be a bit more stable when updating
recordings. The tests are still non-deterministic with this change based
on local testing.
Green CI

Agent: use `temperature: 0` in HTTP recordings

---

pnpm-lock.yaml
vscode/package.json
vscode/src/local-context/enhanced-context-status.test.ts
vscode/test/e2e/context-settings.test.ts
vscode/webviews/Chat.module.css
vscode/webviews/Components/EnhancedContextSettings.story.tsx
vscode/webviews/Components/EnhancedContextSettings.tsx
vscode/webviews/Popups/Popup.module.css
vscode/webviews/Popups/Popup.tsx

#2628 will use &times; in the enhanced context settings popup for removing a repository, so we need to remove the close button. This removes the close button. Now, the popup is closed by:
- Clicking outside the popup.
- Pressing Escape.
In addition, this takes care that keyboard focus goes to the enable/disable checkbox when the popup opens, and returns to the enhanced context button when the popup closes.
```
pnpm test:e2e -- context-settings.test.ts
```
Manual test:
1. Sign in and start a chat.
2. Open the enhanced context popup.
3. Press Space a few times, this should toggle the checkbox.
4. Press Escape, this should close the popup.
5. Press Space again, this should re-open the popup.
6. Click somewhere else on the chat. This should close the popup.

VSCode: Remove close button from Enhanced Context Settings popup

---

.eslintrc.js
agent/src/AgentWorkspaceDocuments.ts
cli/src/commands/commit/command.test.ts
lib/shared/src/common/markdown/markdown.ts
lib/shared/src/configuration.ts
lib/shared/src/editor/hydrateAfterPostMessage.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/completions/context/retrievers/jaccard-similarity/bestJaccardMatch.ts
vscode/src/completions/get-inline-completions-tests/no-request-when-accepting.test.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/editor/utils/document-sections.ts
vscode/src/extension.common.ts
vscode/src/fetch.ts
vscode/src/jsonrpc/jsonrpc.ts
vscode/src/non-stop/FixupScheduler.ts
vscode/src/repository/builtinGitExtension.d.ts
vscode/src/search/SearchViewProvider.ts
vscode/src/testutils/mocks.ts
vscode/src/utils.ts
vscode/test/integration/helpers.ts
vscode/webviews/Components/EnhancedContextSettings.tsx
vscode/webviews/utils/VSCodeApi.ts

It will still warn on implicit use of any. This is causing a lot of our eslint warnings, and 95%+ of them are intentional, which just makes us ignore eslint warnings.
Before this, there were 153 no-explicit-any warnings. That represented more than 1/3 of our total eslint warning count.
CI

disable eslint no-explicit-any

---

.vscode/tasks.json

This means that VS Code will show you project-wide diagnostics counts in the status bar.
n/a; dev only

run `tsc --watch` for project-wide TypeScript diagnostics

---

vscode/CHANGELOG.md
vscode/src/edit/prompt/index.ts

RE: https://sourcegraph.slack.com/archives/C052G9Y5Y8H/p1705048856973839
Add the missing preamble to edit commands.
1. Run an edit command, e.g. /doc
2. Check output channel to see if the preamble is included in the transcript

fix: missing preamble in edit commands

---

lib/shared/src/chat/context-filter.ts
lib/shared/src/chat/ignore-helper.ts
lib/shared/src/chat/transcript/interaction.ts
vscode/src/chat/ContextProvider.ts
vscode/src/chat/chat-view/CodebaseStatusProvider.ts
vscode/src/repository/repositoryHelpers.ts
vscode/src/services/context-filter.ts

The `isCodyIgnoredFilePath` API for checking ignores is not actually used. Only `isCodyIgnoredFile` is used.
See discussion: https://sourcegraph.slack.com/archives/C05AGQYD528/p1705004134538609?thread_ts=1704886845.816059&cid=C05AGQYD528.
CI and manually ensured that the removed function was not actually being called for local embeddings, remote embeddings, and symf context (using a debugger).

remove unused codebase-specific ignores

---

.gitignore

.iml files are per-dev, and vsix files are being built only for coder-eval.

added IDEA .iml files and vsix to gitignore

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/rateLimitedClient_2043004676/recording.har.yaml
agent/src/AgentGlobalState.ts
agent/src/AgentWebviewPanel.ts
agent/src/agent.ts
agent/src/index.test.ts
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/protocol.ts
vscode/src/jsonrpc/agent-protocol.ts
vscode/src/main.ts

Previously, it was not possible to start a chat session with context from another conversation. The lack of this feature prevented clients like JetBrains from supporting preserving the chat history after restarting the IDE. This PR fixes the problem by adding a new `chat/restore` endpoint that allows the client to pass the transcript of an old conversation.
This PR also makes the logic related to creating new chats more robust. Previously, it relied on racing promises aginst hardcoded timeouts to capture webview instances. Now, the chat-related commands return the webview directly avoiding the need for brittle logic inside the agent.
See newly added tests.

Agent: add new `chat/restore` endpoint

---

vscode/webviews/utils/displayPath.test.ts
vscode/webviews/utils/displayPath.ts

This makes some fixes to https://github.com/sourcegraph/cody/pull/2653 for Windows where the paths were appearing incorrectly (wrong slash direction, or not detected as part of the workspace so showing as absolute paths).
This PR is targetting @sqs rm-filename branch since it's fixed to unmerged changes.
- Run `pnpm test:e2e` on Windows and verify all is green

Fix some issues on Windows with removed context filenames

---

knip.jsonc

After being _very glad_ to see Knip being used in this repository, I saw the configuration and the slightly uncommon blend of the `vscode` and `agent` workspaces (`"../agent/**/*.ts"`), I couldn't resist to check out the repo and come up with some suggestions, as presented in this PR.
Looks like most of the results are (still) correct and there's even more to clean up, yay! I'm happy to leave the actual clean up to developers more familiar with the codebase (I'm also unaware of  potential external factors/consumers).
Feel free to AMA!
Additionally, Knip v4 is around the corner and will give a nice speed bump (on my machine it goes down from 4.7s to 2.8s with the same config).
CI

Improve Knip config

---

.github/workflows/semgrep.yml

Instead of `pull_request` event, I have moved the semgrep SAST scan to `pull_request_target` similar to `pr-auditor` which consumes extra secret to clone and scan using private semgrep rules.
P.S: this Semgrep Scan should [trigger](https://stackoverflow.com/a/77069245) after merged to main
CI 🟢  and external contributors should be able to execute semgrep scan

Fix Semgrep pull request event 

---

.gitattributes
agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/rateLimitedClient_2043004676/recording.har.yaml
agent/src/cli/jsonrpc.ts
package.json
vscode/src/testutils/polly.ts

Previously, the `update-agent-recordings` command did an `rm -rf agent/recordings`. This was problematic because 1) it was slow to update all the recordings to record one new HTTP request and 2) it made the tests fail more regularly because the LLM response is random even with temperature=0. This PR addresses both problems by allowing Polly to manage deletion of unused recordings instead of doing `rm -rf agent/recordings`. This means that updating recordings is very fast because it only sends network requests for missing recordings, and it also makes the tests a lot more stable because we keep old recordings around for much longer.
One risk with this change is that we never update recordings. Polly suports configuring an expiry date for recorings but we can't use that at the moment …

Agent: make `pnpm update-agent-recordings` more stable and run faster

---

vscode/src/local-context/symf.test.ts
vscode/src/local-context/symf.ts
vscode/src/local-context/symfExpandQuery.ts

Previously, I was unable to run the symf tests locally because it reported an issue with `vscode` imports. This error was understandable because the `symf.ts` file imported from the `'vscode'` module. Moving the term expansion function to a separate file fixes the problem. However, I'm not sure how the tests passed in the first place unless something regressed recently.
Green CI

Symf: move term expansion to separate file

---

vscode/src/completions/get-inline-completions-tests/streaming.test.ts

- I've been refactoring the autocomplete streaming logic and bumped into these tests. By accident, I discovered a couple of things:
1. The `expect` check for abort signal being aborted in `onNetworkRequest` callbacks is not applicable anymore. If you `console.log(abortController.signal.aborted)`, it's always `false`, which makes sense logic-wise. We do not cancel the top-level signal; we only cancel individual requests using the forked signal.
2. These `expect` statements are not taken into account (were never taken into account?) by `vitest`. That's why they all pass even though the values do not match with expects.
- In my other branch, I made these expects reachable and spent an hour trying to understand why it does not work as expected. Then, I finally went to debug how it works on …

Autocomplete: clean up streaming unit tests

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/AgentWebviewPanel.ts
agent/src/agent.ts
agent/src/index.test.ts
lib/shared/src/index.ts
lib/ui/src/Chat.tsx
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/chat/protocol.ts
vscode/src/commands/index.ts
vscode/src/commands/prompt/display-text.ts
vscode/src/editor/displayPathEnvInfo.ts
vscode/src/editor/utils/editor-context.ts
vscode/src/jsonrpc/agent-protocol.ts
vscode/src/main.ts
vscode/src/non-stop/FixupTypingUI.ts
vscode/src/testutils/testSetup.ts
vscode/webviews/Components/FileLink.tsx
vscode/webviews/UserContextSelector.tsx
vscode/webviews/utils/displayPathEnvInfo.ts

Previously, agent clients had to use the old recipe-based API to invoke
the test, smell and explain commands. This PR adds new `commands/*`
endpoints to invoke these commands using the exact same code paths as
they're implemented in VS Code.
See three new test cases.

Agent: add support for `commands/{test,smell,explain}`

---

vscode/src/local-context/download-symf.ts

Bump `symf` version to pick up the following improvements:
- Markdown support
- TSX support
- Cody no longer shows an error when there are no symbols extracted and indexed
- Check out branch and make sure Cody fuzzy search still works
- Try searching for contents in markdown and tsx files—these should now work

bump symf version -> 0.0.4

---

agent/src/esbuild.mjs
lib/shared/src/index.ts
lib/ui/src/Chat.tsx
vscode/src/commands/prompt/display-text.test.ts
vscode/src/commands/prompt/display-text.ts
vscode/src/editor/displayPathEnvInfo.ts
vscode/src/editor/utils/editor-context.ts
vscode/src/non-stop/FixupTypingUI.ts
vscode/src/testutils/testSetup.ts
vscode/webviews/Components/FileLink.tsx
vscode/webviews/UserContextSelector.tsx
vscode/webviews/utils/displayPathEnvInfo.ts

Now, `esbuild` builds other projects from their TypeScript sources instead of from their intermediate build products in `dist`.
As a benefit, also makes it so you don't need to run `tsc -b` to produce the latest `dist` dirs during agent development.
The cause was likely that the `dist` dirs were out of date (because `tsc -b` was not running or got confused during a `git checkout`), or different import strategies were causing `@sourcegraph/cody-shared` to be imported multiple times.
Discussion: https://sourcegraph.slack.com/archives/C05AGQYD528/p1705319075562969
Run agent tests as described in the now-deleted `lib/shared/src/index.ts` comment and ensure they pass.

fix cody-shared import from agent issue

---

lib/shared/src/chat/markdown.ts
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/commands/prompt/display-text.test.ts
vscode/src/commands/prompt/display-text.ts
vscode/src/testutils/mocks.ts

This removes a custom command in favor of using the built-in `vscode.open` (although we need to proxy it for reasons described in https://github.com/microsoft/vscode/issues/178868#issuecomment-1494826381).
Open Cody chat. Mention both files and symbols. Ensure that Cody chat properly opens those links in the editor to the side, with the right selection.

remove custom cody.chat.open.file command, proxy standard vscode.open

---

agent/src/index.test.ts
lib/shared/src/common/markdown/markdown.test.ts
package.json
pnpm-lock.yaml
vscode/src/completions/get-inline-completions-tests/languages.test.ts
vscode/src/completions/get-inline-completions-tests/post-processing.test.ts
vscode/src/editor/utils/editor-context.test.ts
vscode/src/editor/utils/editor-context.ts

- Upgrades `vitest` to the latest version.
- Since the last version upgrade in our repo, `vitest` had [the first stable release](https://github.com/vitest-dev/vitest/releases/tag/v1.0.0) with a lot of useful features and performance improvements. I wanted to use a couple of CLI flags locally and noticed they are unavailable because of the outdated version.
- No breaking changes for us. Only snapshot updates were required because they look nicer now. 
CI

DX: upgrade vitest to the latest version

---

agent/src/cli/evaluate-autocomplete/testParse.test.ts

Fixes https://github.com/sourcegraph/cody/issues/2088 Now that this PR here https://github.com/sourcegraph/cody/pull/2690 has been merged, we should no longer have flaky tree-sitter loading.
Green CI, no flaky failures!

Agent: re-enable tree-sitter parsing tests

---

vscode/CHANGELOG.md
vscode/src/completions/providers/create-provider.test.ts
vscode/src/completions/providers/fireworks.ts

Depends on https://github.com/sourcegraph/sourcegraph/pull/59522
This PR adds support for a new model identifier inside the Fireworks setup: `fireworks/starcoder`. Read more about the new flag, here: https://github.com/sourcegraph/sourcegraph/pull/59522
This PR makes it so that if an enterprise instance has `fireworks/starcoder` set as their default code completion model, the client will pick it up and use the Fireworks provider to build the prompt and send it with the `fireworks/starcoder` model identifier.
1. Be on https://github.com/sourcegraph/sourcegraph/pull/59522 on your backend
2. Configure your Cody Gateway license to allow `fireworks/starcoder`: <img width="889" alt="Screenshot 2024-01-12 at 17 50 19" src="https://github.com/sourcegraph/cody/assets/458591/ec1a0637-191b-42a2-a28e- …

Autocomplete: Add support for Starcoder Enterprise virtual model identifier

---

lib/shared/src/index.ts
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/main.ts

Closes [59261](https://github.com/sourcegraph/sourcegraph/issues/59261)
This pull request wires editor process attribution command and response extension message with a guardrails back-end on the enterprise instance (done in https://github.com/sourcegraph/sourcegraph/pull/59513).
Manual check
Found:
(note this is too short of a snippet for attribution search to run at all, but that's not implemented yet)
Not found:

Wire chat guardrails with snippet attribution search on enterprise instance

---

vscode/src/testutils/uri.ts

If the first arg was a `vscode-uri.URI` type, then it lacks a `.uri` property, and this would fail.
CI

fix testing vscode.Uri.joinPath(/* vscode-uri.URI */, ...)

---

vscode/src/chat/chat-view/ChatManager.ts
vscode/src/main.ts

The `cody.action.chat` command has been using `executeCommand` for chat questions that turns the question into Chat before it can be processed by the Simple Chat Panel as a question.
This PR adds a new `executeChat` method in ChatManager to handle chat questions directly to simplify the process.
The `cody.action.chat` is being used by `Ask Cody to Explain` in CodeAction, so you can invoke that to make sure it works to confirm the changes in this PR.
https://github.com/sourcegraph/cody/assets/68532117/548be375-6351-45b3-9e1d-4aa9e69f1cac

refactor: chat action command

---

lib/shared/src/codebase-context/index.ts

This makes the current state match the Feb 15 state more closely, so we can dogfood it better and our non-enterprise users experience the Feb 15 experience (symf + local embeddings, no remote embeddings) sooner. Enterprise users still get remote embeddings when available.
CI

never use remote embeddings for dotcom/PLG users

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/commands/CommandRunner.ts
vscode/src/commands/CommandsController.ts
vscode/src/main.ts

Previously the custom edit commands are filtered from the chat command list because it wasn't supported. Since we have implemented handleCommand in a previous PR, this PR remove the filter added for excluding custom edit commands from chat view
- Add support for custom edit commands in chat
- Display custom edit commands in chat
- Improve command handling by updating the findCommand method to startCommand in the SimpleChatPanelProvider and CommandsController classes.
- Fix a bug where additional instruction followed by command key submitted in menu were removed incorrectly.
- Remove unused variables, e.g. commandRunners map
https://github.com/sourcegraph/cody/assets/68532117/79b87c00-9726-4dfe-9ce4-3da72481a78a

feat: add support for custom edit commands in chat

---

vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/is-completion-visible.ts
vscode/src/completions/suggested-autocomplete-items-cache.ts

UPD: I added back the VS Code specific `insertText` processing, so this PR no longer has any breaking changes. But this logic is not extracted into a separate function and is called separately. If we decide to change this behavior, it will be easy to do in the future.
- This PR proposes to change the behavior of the `autocomplete/execute` requests for the agent based on the [feedback in Slack](https://sourcegraph.slack.com/archives/C05AGQYD528/p1704164215488589). 
- The only functional change: `InlineCompletionItemProvider.provideInlineCompletionItems()` does not execute the VS Code-specific logic anymore, which makes all completions start at the beginning of the line no matter what the current cursor position is. This logic was added to avoid UI jitter in VS Code, but it does not apply …

Autocomplete: do not adjust insert text in a VS Code-specific way for the agent

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/services/AuthProvider.ts
vscode/src/services/TreeViewProvider.test.ts
vscode/src/services/TreeViewProvider.ts
vscode/src/services/treeViewItems.ts
vscode/src/testutils/mocks.ts

Similar to: https://github.com/sourcegraph/sourcegraph/pull/59660
Remove dependency on cody-pro feature flag which was added during Dec GA release. Things are now stable and it is a good time to cleanup.
- Connect to a local sourcegraph instance
- Visit `/site-admin/feature-flags` and remove the cody-pro feature flag.
- Visit `/cody/manage` and make sure you are on a free plan.
- Check in IDE that Upgrade buttons are showing up.

[Cody] remove cody-pro feature flag dependency

---

agent/src/index.test.ts
vscode/src/extension.node.ts

Previously, local embeddings were enabled for agent clients. We had disabled local embeddings in the tests through an environment variable because they were causing stability issues, but clients like the JetBrains plugin were not setting this environment variable. This PR fixes the problem so that local embeddings are always disabled for all agent clients.
Our tests are already running in this environment.

Agent: always disable local embeddings

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/rateLimitedClient_2043004676/recording.har.yaml
agent/scripts/export-cody-http-recording-tokens.sh
agent/src/index.test.ts
vscode/src/jsonrpc/jsonrpc.ts

Previously, we only had tests for Cody Pro accounts (one without rate
limits and one with rate limits). This PR adds one more testing
account for demo.sourcegraph.com, which is an Enterprise instance. The extension has several code paths related to enterprise accounts that we have not been able to cover before. This PR only adds a basic test,
but we can add more detailed tests later.
See new tests.

Agent: add tests case for Cody Enterprise

---

vscode/src/testutils/mocks.test.ts
vscode/src/testutils/mocks.ts

Previously, local embeddings were enabled for agent clients. We had disabled local embeddings in the tests through an environment variable because they were causing stability issues, but clients like the JetBrains plugin were not setting this environment variable. This PR fixes the problem so that local embeddings are always disabled for all agent clients.
See new tests

Agent: support `new vscode.Selection(number,number,number,number)`

---

.github/workflows/ci.yml

PR to update/remove GoogleAuth step to unblock external contributors.
[Slack thread](https://sourcegraph.slack.com/archives/C04MYFW01NV/p1705336704859289) for more information on this request.
test that CI is working as expected and events are still able to get logged from e2e tests

update google auth workflow step to unblock external contributors

---

agent/src/index.test.ts
lib/ui/src/Chat.module.css
lib/ui/src/Chat.tsx
lib/ui/src/chat/BlinkingCursor.tsx
lib/ui/src/chat/Transcript.tsx
lib/ui/src/chat/TranscriptItem.tsx
pnpm-lock.yaml
vscode/CHANGELOG.md
vscode/package.json
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/chat/chat-view/SimpleChatModel.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/prompt.ts
vscode/test/e2e/at-file-context-selecting.test.ts
vscode/webviews/Chat.tsx

From the `vscode/CHANGELOG.md`:
- New chats are now the default when the user submits a new quesetion. Previously, follow-up questions were the default, but this frequently led to exceeding the LLM context window, which users interpreted as an error state. Follow-up questions are still accessible via ⌘-Enter or Ctrl-Enter.
- We now allocate no more than 60% of the overall LLM context window for enhanced context. This preserves more room for follow-up questions and context.

Make new chats the default and limited context window allocated to enhanced context to preserve context window

---

vscode/src/completions/get-inline-completions-tests/dynamic-multiline.test.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions-tests/hot-streak.test.ts
vscode/src/completions/get-inline-completions-tests/languages.test.ts
vscode/src/completions/get-inline-completions-tests/multiline-truncation.test.ts
vscode/src/completions/get-inline-completions-tests/streaming.test.ts
vscode/src/completions/get-inline-completions-tests/triggers.test.ts
vscode/src/completions/test-helpers.ts

- Addresses @dominiccooney's [suggestion](https://github.com/sourcegraph/cody/pull/2731#issuecomment-1891703877) to improve autocomplete integration tests by adding a delay between streamed chunks.
- Refactors autocomplete partial-response-helpers to async generators.
- Built on top of https://github.com/sourcegraph/cody/pull/2747
CI

Autocomplete: use async generators for autocomplete tests

---

lib/ui/src/Chat.tsx
lib/ui/src/chat/BlinkingCursor.tsx
lib/ui/src/chat/Transcript.tsx
lib/ui/src/chat/TranscriptItem.tsx
lib/ui/src/chat/components/EnhancedContext.tsx
vscode/webviews/App.tsx
vscode/webviews/Chat.tsx
vscode/webviews/Components/EnhancedContextSettings.tsx

We're using React context for enhanced context settings instead of passing it around. This is more succinct and obviously consistent because the context is provided in far fewer places (specifically, one place) than it would be if it were passed around.
Moves the definition of the context into lib/ui so it is accessible from the lib/ui loading indicator, and cleans up passing the value around in some places and using context in others.
CI, this is not a functional change.

Cleanup: Put "is enhanced context enabled" in one place instead of passing it around

---

vscode/test/integration/api.test.ts

This test is failing on `main` on the Windows bots because the way the expected string is built is not correct for Windows (the path will have a drive letter).
This changes it to just compare the string URIs instead.
CI

Fix failing Windows integration test

---

.github/workflows/ci.yml
vscode/playwright.config.ts
vscode/test/e2e/chat-history.test.ts
vscode/test/e2e/helpers.ts

Enables the e2e bots on Windows.
Tested by the bots - the status checks on this PR should have a Windows e2e bot that is green.

Enable e2e tests for Windows on bots

---

vscode/src/completions/providers/anthropic.ts

Follow up to #2783
I tested the gracefull fallback in #2783 on the demo instance (demo.sourcegraph.com) and noticed that the error is a different string. Turns out the string was changed in the past and thus the fallback behavior was not working and the insider build broke completions for these instances 😬. 
So I did a git blame on the `codecompletion.go` file to find all variations of this string. Turns out there is a third one that was available too for some time:
- https://github.com/sourcegraph/sourcegraph/commit/f700d84cab215b84dfbc4ae63d9e6134a856b8be
- https://github.com/sourcegraph/sourcegraph/commit/3b53b4e623e978a559e8ae05d71e8550dded4886#diff-3b488ccb5c3c1aa6d139c640704ba6d118ba6737fda7bc4ac077242a188956baR30
- https://github.com/sourcegraph/sourcegraph/commit/5b95c4b98e2890b9dd …

Fix Anthropic model ID overwrite for old instances

---

.github/workflows/vscode-insiders-release.yml
.github/workflows/vscode-stable-release.yml
vscode/.gitignore
vscode/package.json
vscode/scripts/github-changelog.ts

We already have a pretty stable release pipeline, however one thing that has been very tedious and we often forgot about was to update the GitHub release changelog.
This PR adds a new script that computes the GitHub release body from the `CHANGELOG.md`. 
It also makes it so that we always create a new insider build when we do a stable release (something that also went out of sync before).
- `pnpm -C vscode run github-changelog`
- `cat vscode/GITHUB_CHANGELOG.md`

Automate VS Code release GitHub changelog

---

lib/ui/src/Chat.tsx
vscode/CHANGELOG.md
vscode/test/e2e/at-file-context-selecting.test.ts

We have some code that `return`s if you press certain `Ctrl+` combinations. Since we're using `Ctrl+Enter` for follow-on chat on Windows, we need to not exit out here.
- Run `pnpm test:e2e` to run the updated test, or
- Run the extension on Windows
- Send a chat
- Send a second chat with `<enter>` and ensure it's a new chat (replaces the first message)
- Type a third chat and press `<ctrl+enter>` and ensure it's a follow-on chat (appended after the previous message)

Fix Ctrl+Enter for follow-on chat on Windows

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/AgentGlobalState.ts
agent/src/AgentTabGroups.ts
agent/src/AgentWorkspaceDocuments.ts
agent/src/agent.ts
agent/src/index.test.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/editor/active-editor.ts
vscode/src/jsonrpc/agent-protocol.ts

Followup to https://github.com/sourcegraph/cody/pull/2821
Previously, each agent test performed side effects like opening a document that leaked into the next test case. This caused subtle problems like seemingly non-deterministic behavior based on whether you ran an individual test with `it.only` (or `vitest -t`) or all tests. For example, if one test case customized the LLM model then the next test case would use that custom model when running all test together, but the next test would use the default model when running isolated (via `it.only` or `vitest -t`).
This PR fixes the problem by adding a new `testing/reset` request that does a best-effort to reset the environment of the server process between each test case. The current implementation may not reset everything perfectly but it …

Agent: reset server environment between tests

---

lib/shared/src/embeddings/EmbeddingsDetector.ts

Remote embeddings are no longer used on dotcom, so this skips an unnecessary step. Even if remote embeddings would be found, they would not be used because the embeddings search methods already perform the check that was added here.
CI

skip remote embeddings detection for dotcom

---

lib/shared/src/chat/chat.ts
lib/shared/src/common/abortController.test.ts
lib/shared/src/common/abortController.ts
lib/shared/src/intent-detector/client.ts
lib/shared/src/sourcegraph-api/completions/browserClient.ts
lib/shared/src/sourcegraph-api/completions/client.ts
lib/shared/src/sourcegraph-api/completions/nodeClient.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/edit/provider.ts

Passing an AbortSignal is more standard and interoperable than the previous way of having them return a `() => void` that cancels the operation.
CI

use more standard AbortSignal for aborting stream/chat operations

---

vscode/webviews/Chat.module.css

This avoids the chat box being taller than the webview, which can cause the buttons to be pushed off the bottom of the screen.
Fixes #2824
https://github.com/sourcegraph/cody/assets/1078012/7b048659-45ff-42e0-84f2-f587cdd5c159
Paste large input of press Shift+Enter repeatedly to add more lines to the chat input than fit on the screen.

Restrict chat input to 80% of viewport height

---

lib/shared/src/chat/chat.ts
lib/shared/src/intent-detector/client.ts
lib/shared/src/sourcegraph-api/completions/browserClient.ts
lib/shared/src/sourcegraph-api/completions/client.ts
lib/shared/src/sourcegraph-api/completions/nodeClient.ts
lib/shared/src/sourcegraph-api/completions/types.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/edit/provider.ts
vscode/src/local-context/filename-context-fetcher.ts
vscode/src/local-context/symfExpandQuery.ts

This is more idiomatic JavaScript, is cleaner, and is more interoperable than custom callbacks.
The underlying implementations (`_streamWithCallbacks` methods) still use callbacks. That can be addressed separately. It's a nice win for callers to not need to use callbacks.
CI and e2e tests. Confirmed that completions, chat, and inline edits work manually.

use async generator for completions and chat clients

---

lib/shared/src/index.ts
lib/shared/src/inferenceClient/misc.ts
lib/shared/src/ollama/ollama-client.ts
vscode/src/completions/client.ts
vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/create-provider.test.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/fetch-and-process-completions.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/get-completion-params.ts
vscode/src/completions/providers/ollama-client.ts
vscode/src/completions/providers/unstable-ollama.ts
vscode/src/completions/providers/unstable-openai.ts
vscode/src/external-services.ts

This is in preparation for support for Ollama as a chat backend (not just Ollama completions as was [released in v1.1.0](https://sourcegraph.com/blog/cody-vscode-1.1.0-release)).
No behavioral change; just moving code:
- ollama client
- CodeCompletions{Client,Params} and CompletionResponseGenerator
- STOP_REASON_STREAMING_CHUNK
CI

move ollama client to lib/shared

---

vscode/.storybook/main.ts

They were erroring because `process` was imported along with `@sourcegraph/cody-shared`.
Run `pnpm -C vscode storybook` and try viewing a story.

fix storybooks

---

lib/shared/src/configuration.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/telemetry-v2/TelemetryRecorderProvider.ts
lib/shared/src/telemetry/EventLogger.ts
lib/ui/src/Chat.tsx
vscode/CHANGELOG.md
vscode/package.json
vscode/src/chat/CachedRemoteEmbeddingsClient.ts
vscode/src/chat/ContextProvider.ts
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.test.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/chat-helpers.ts
vscode/src/chat/chat-view/context.ts
vscode/src/chat/chat-view/prompt.test.ts
vscode/src/chat/chat-view/prompt.ts
vscode/src/chat/protocol.ts
vscode/src/commands/CommandsController.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/testutils/mocks.ts
vscode/test/e2e/command.test.ts
vscode/test/e2e/custom-command.test.ts
vscode/test/integration/chat.test.ts
vscode/webviews/App.tsx
vscode/webviews/Chat.tsx

This PR addresses some code quality issues and complexity in the chat implementation.
* https://github.com/sourcegraph/cody/pull/2542 introduced a separate code path for handling command-initiated chats. This introduced a flag that special-cased handling of commands in a number of places—in the view controller (SimpleChatPanelProvider), prompt constructor, and context fetcher. These flags make chat more difficult to reason about, requiring the dev to reason about the conditional flag at multiple places in the lifecycle of a chat request.
Code changes
* Instead of checking a flag to see if the user request was a command in `DefaultPrompter`, introduces a new `CommandPrompter` to customize prompt construction for commands
* Breaks apart `ContextProvider` into separate functions, moved to a …

Refactor chat

---

lib/shared/src/codebase-context/index.ts
lib/shared/src/embeddings/client.ts
lib/shared/src/embeddings/index.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/test/mocks.ts
vscode/src/chat/CachedRemoteEmbeddingsClient.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/context.ts
vscode/src/edit/prompt/context.ts

This fixes an issue with remote embeddings where attempting to run a chat that fetched remote embeddings would completely fail with an error from trying to dereference `.scheme` on an undefined value.
The Sourcegraph GraphQL API returns remote embeddings results with `fileName` fields. We need to resolve this to a `uri` so that we don't pass around a relative fileName that we don't know how to resolve. To resolve it, we assume (as do other context sources) that the context is for the first workspace folder in VS Code. We need to pass this around as `workspaceFolderUri`, which is ugly but is the smallest change that will make this work. The remote embeddings code is going away soon anyway, so IMO this solution suffices.
Using remote embeddings, run a chat that gets context and ensure there …

resolve remote embeddings fileNames to URIs

---

agent/src/agent.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/chat/chat-view/SimpleChatModel.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/protocol.ts
vscode/src/test-support.ts

Implements some follow-up tasks from https://github.com/sourcegraph/cody/pull/2848:
* Move methods around in SimpleChatPanelProvider for greater clarity (not doing in this PR to avoid making the diff larger)
* https://github.com/sourcegraph/cody/pull/2848#discussion_r1461314572
We establish strong naming conventions for methods and document invariants that should hold to prevent future quality regressions that may make the logic more difficult to reason about.
There should be no behavior changes

Further clean up SimpleChatPanelProvider and document invariants

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/rateLimitedClient_2043004676/recording.har.yaml
agent/scripts/reset-recordings-to-main.sh
agent/src/index.test.ts

Previously, the squirrel test didn't assert that the context files were empty. Also, the squirrel test explicitly opened the squirrel.ts file so it wasn't stressing the code path where symf context returns results from unopened files. This PR fixes both problems, we remove the explicit `textDocument/didOpen` notification for squirrel.ts and we add an assertion that squirrel.ts is part of the context files in the transcript.
See updated tests.

Agent: update squirrel test to assert context files

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/main.ts

Close https://github.com/sourcegraph/cody/issues/2885
Fix issue where executing the doc command opens an empty chat panel.
This is because the edit command was sent to chat provider for processing after being routed to fixup controller.
There is a WIP to refactor the relationship between commands and chat to address this issue but for now  we will have to check if the command is a chat command or edit command at the top level.
Run doc command to confirm a new chat window is not opened.

fix: doc command with empty chat

---

lib/shared/src/index.ts
lib/shared/src/sourcegraph-api/errors.ts
lib/ui/src/chat/ErrorItem.tsx
vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/prompt.test.ts
vscode/src/chat/chat-view/prompt.ts

The context warnings in the UI are creating more confusion than they're worth, so we'll move them to the debug output and work on better ways of surfacing these issues as necessary in the transcript view.
- Recreate each warning scenario
- Verify code behaves well

Move context warnings from the UI to the debug log

---

agent/src/cli/jsonrpc.ts
agent/src/index.test.ts

The error message is clearer now if the test fails. I've also added an example on how to reproduce network errors when failing to download, for example, the symf binary.
The error now includes the string of the reply, instead of just saying "value is not truthy"
Green CI

Agent: use more helpful assertion in squirrel test

---

.vscode/settings.json

Takes precedence over user setting and causes annoying behaviour: https://sourcegraph.slack.com/archives/C05AGQYD528/p1706194762920939
(We can still enable these in user settings if people want them)
N/A - Dev setting only

Workspace settings: Disable codeActionsOnSave

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/services/HistoryChat.ts

Cleans up the History quickpick titles, and the editor title buttons (removes the chat reset icon now we have a dedicated button).
Before:
After:
- Loaded chat
- Verified buttons & history view

Clean up chat editor title buttons & history separators

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/main.ts
vscode/test/e2e/auth.test.ts
vscode/webviews/NavBar.tsx

Reported by https://sourcegraph.slack.com/archives/C05AGQYD528/p1706206513677179
Provided by cezary on slack:
- User is signed out of Cody (I just Cmd+Shift+P > Sign out'd)
- I click on the yellow Cody icon in the bottom
- Signup screen appears on the right hand side in a pane
- Clicking sign into enterprise instance seems to have no effect.
After this change: sidebar will be opened with auth view instead of chat panel
https://github.com/sourcegraph/cody/assets/68532117/5a9a8e15-7318-402f-bf66-8e741928f3c8

fix: do not display non-chat view in panel

---

lib/shared/src/guardrails/index.ts
lib/ui/src/chat/CodeBlocks.module.css
lib/ui/src/chat/CodeBlocks.tsx

Closes sourcegraph/sourcegraph#59294
[Figma](https://www.figma.com/file/H0k85e9AGWqSkiaExKVdyL/Guard-Rails-in-Cody-for-VS-Code?type=design&node-id=23-592&mode=design&t=pnlU3Q8qbm7N2Tq8-0)
[Long Loom showing demo local sg start](https://www.loom.com/share/c8cdef930af144e78584cc01e2882a7f?sid=00eac153-c720-4928-bae7-d44ec0567330)
Pass:
Fail:
Unavailable ([caveat](https://github.com/sourcegraph/sourcegraph/issues/59294#issuecomment-1910151871)):
For testing you got to enable `attribution.enabled` in your local site config as well as an experimental setting in VS Code:

VS Code chat UI matches design

---

lib/shared/src/utils.test.ts
lib/shared/src/utils.ts
vscode/CHANGELOG.md

I noticed that the `convertGitCloneURLToCodebaseName` logic doesn't work for repos with dots in the name (my console was littered with errors). We can't fix this in the regex alone (since regexes are greedy and when I allow the repo group to have dots, it will match the `.git` part), so we now have a second regex to replace the `.git` replacement.
- Added a unit test

Fix git clone URL converstion for dots in repo names

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/src/TestClient.ts
agent/src/agent.ts
agent/src/cli/jsonrpc.ts
agent/src/index.test.ts
agent/src/telemetry/index.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/telemetry/GraphQLTelemetryExporter.ts
lib/shared/src/telemetry-v2/TelemetryRecorderProvider.ts
vscode/src/jsonrpc/agent-protocol.ts

Previously, the agent sent log events to sourcegraph.com for enterprise accounts even if any of the following things were true:
- `cody.serverEndpoint` was set to the enterprise URL.
- `cody.telemetry.level` was set to `off`. This setting is, in fact, entirely ignored by the agent.
The root problem was that the v1 event logger was still logging one event to sourcegraph.com without any option to route this request only to the connected instance. This was problematic because some enterprise instances are airgapped and this request ended up timing out.
This PR fixes the problem by adding support to exclusively send logging events to the connected instance. This behavior can only be enabled by setting the environment variable `CODY_LOG_EVENT_MODE` to the value `'connected-instance-only'`. …

Agent: add ability to disable network requests to sourcegraph.com

---

vscode/doc/codyignore.md

Adding temporary docs for cody ignore(Mostly copying the instructions @abeatrix posted already)

Adding cody ignore docs

---

vscode/CHANGELOG.md
vscode/package.json

c.f. [this thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1706522203985629) regarding version number
- Just a version change, CI will test

VS Code: Release 1.2.0

---

vscode/CHANGELOG.md
vscode/src/commands/CommandsController.ts
vscode/src/commands/default/index.ts
vscode/src/commands/default/unit.ts
vscode/src/main.ts
vscode/webviews/Chat.tsx

Cleaned up imports for commands. Removed mention of `/ for command` from the chat input placeholder.

fix: update chat input placeholder

---

vscode/CHANGELOG.md
vscode/src/commands/services/provider.ts

Add the missing /ask command back to command menu.

add /ask to command menu

---

vscode/src/main.ts

Fixes the race condition in the auth token issue highlighted in https://github.com/sourcegraph/cody/issues/2940 thanks to Kevin and Kalan for raising this.
The original bug came in this cool cleanup PR https://github.com/sourcegraph/cody/pull/2782 on this [commit](https://github.com/sourcegraph/cody/commit/058b8ad9542ce15fc3f95bc87f3c0d440699b708) CC @olafurpg 
In the latest version of Cody if you install it in VS code then it will ask you to reload and then you can't login(Coz it can't read auth token)
NOTE: 
1. This bug very likely has nothing to Tabnine, it was just a coincidence
2. The actual error of token not found is [here](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/services/SecretStorageProvider.ts?L15)
- Run the debugger
- Logout of Cody
- Log in to …

Adding temp fix for the race condition involved in reading auth token

---

lib/shared/src/commands/types.ts
vscode/src/commands/CommandsController.ts
vscode/src/commands/default/doc.ts
vscode/src/commands/default/explain.ts
vscode/src/commands/default/index.ts
vscode/src/commands/default/smell.ts
vscode/src/commands/default/test.ts
vscode/src/commands/default/unit.ts
vscode/src/commands/menus/index.ts
vscode/src/commands/menus/items/options.ts
vscode/src/commands/types.ts
vscode/test/e2e/command.test.ts

Follow up on https://github.com/sourcegraph/cody/pull/2939
This enables /ask and /edit from menu to work again.
Also added e2e test to cover submitting question via /ask in command menu.
Start an ask/ edit command from the command menu to confirm it works. 
https://github.com/sourcegraph/cody/assets/68532117/c3ca3077-fdf5-46ea-a5b6-0cded45c0c2a
"Create Custom Command" option should only show up in custom command menu

fix: handle ask and edit commands from menu

---

vscode/src/commands/default/explain.ts
vscode/src/commands/default/smell.ts
vscode/src/commands/default/test.ts
vscode/test/e2e/command.test.ts
vscode/test/e2e/unit-test-command.test.ts

current not logging the default chat commands after the command refactoring.
This adds the logging back for them
execute a command and chat the output channel to make sure the commands are logged correctly.

add log default chat commands

---

vscode/CHANGELOG.md
vscode/package.json

Context: https://sourcegraph.slack.com/archives/C05AGQYD528/p1706583104496449?thread_ts=1706568527.428369&cid=C05AGQYD528 & https://sourcegraph.slack.com/archives/C05AGQYD528/p1706561150132109
Patch release for 1.2.1 to include a temporary fix for the auth token issue and clarification on removing slash commands.
Version bump for the 1.2.1 patch release.

VS Code: Release 1.2.1

---

vscode/src/completions/get-current-doc-context.test.ts
vscode/src/completions/get-current-doc-context.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions-tests/hot-streak.test.ts
vscode/src/completions/providers/fetch-and-process-completions.ts
vscode/src/completions/providers/hot-streak.ts
vscode/src/completions/text-processing/parse-completion.ts
vscode/src/completions/text-processing/utils.ts

- As a follow-up to https://github.com/sourcegraph/cody/pull/2881, I started adding more tests. I bumped into the issue that I had created with the last-minute fix in the PR where I removed the `actualPosition` from `docContext` and switched to computing it manually on the spot. The math was incorrect in some cases: we need to know the length of the string at the target line number to calculate the correct position. This PR reverts back to having this field to avoid the complexity of handling edge cases where the injected completion overwrites `currentLineSuffix`.
- It also adds a helper function `acceptFirstCompletionAndPressEnter`, to the return value of `getInlineCompletionsWithInlinedChunks`, making hot-streak tests even more compact and easier to read. 
CI

Autocomplete: fix actual position calculation for hot-streak completions

---

vscode/test/e2e/command.test.ts
vscode/test/e2e/custom-command.test.ts

- remove `.only` from the custom command e2e test...
- update the flanky e2e test for command which was failing
All the e2e tests should be running and passing on the CI.

update e2e tests

---

vscode/src/edit/prompt/context.ts
vscode/src/edit/prompt/index.ts
vscode/src/edit/provider.ts

Remove codebase context as:
- We now support user provided context, which will generally be much more accurate for the user
- This context is very rarely useful and adds latency to every request. Related code is unlikely to be useful for edits. It's possible we could use codebase context for code related to the instructions, but this is unlikely to work well given most instructions are short. We should revisit a mechanism to manually trigger codebase context.
1. Run edits
2. Check they output as normally

Edit: Remove usage of codebase context

---

vscode/CHANGELOG.md
vscode/package.json

This commit updates the package.json for the VS Code extension by removing the condition that required the resourceScheme to be file for the cody.menu.commands to be visible in the editor title. This change allows the command to be visible regardless of the resource scheme, as long as cody.activated is true, config.cody.editorTitleCommandIcon is set, and the editor is not in readonly mode. This enhances the command's visibility and usability in various contexts within VS Code, and shows up in the chat panels.
cody icon doesn't show up in chat panel

add: display cody icon in chat panel title

---

lib/shared/src/index.ts
lib/shared/src/inferenceClient/misc.ts
lib/shared/src/ollama/ollama-client.ts
lib/shared/src/sourcegraph-api/completions/types.ts
vscode/src/completions/client.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/providers/fetch-and-process-completions.ts

- Adds `STOP_REASON_REQUEST_ABORTED` and `STOP_REASON_REQUEST_FINISHED` to completion responses to enable better observability locally and improve our analytics events analysis capabilities.
- Adds early exit for aborted requests to ollama HTTP client.
CI

Autocomplete: add more stop-reason values to autocomplete responses

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/completion-provider-config.ts
vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/completions/get-inline-completions-tests/dynamic-multiline.test.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions-tests/hot-streak.test.ts
vscode/src/completions/get-inline-completions-tests/multiline-truncation.test.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/testutils/mocks.ts

- Adds `cody-autocomplete-single-multiline-request` feature flag to reduce the number of requests for multiline completions from three to one.
- Adds `CompletionProviderConfig` singleton that prefetches completion provider feature flags and stores the latest configuration object to reduce the "prop-drilling" of completion provider options.
CI

Autocomplete: add `single-multiline-request` feature flag

---

vscode/CHANGELOG.md
vscode/doc/ollama.md
vscode/package.json
vscode/src/completions/providers/fetch-and-process-completions.ts
vscode/src/completions/providers/ollama-models.ts
vscode/src/completions/providers/unstable-ollama.ts

- Adds autocomplete support for local inference with [deepseek-coder:6.7b-base-q4_K_M](https://ollama.ai/library/deepseek-coder:6.7b-base-q4_K_M) powered by ollama.
- Adds a bit of abstraction to simplify further addition of new ollama models.
- Sets `deepseek-coder:6.7` as a default model for the ollama provider.
- Should be tested with the follow-up perf improvements https://github.com/sourcegraph/cody/pull/2967
1. Install and run [Ollama](https://ollama.ai/)
2. Download one of the support local models:
- `ollama pull deepseek-coder:6.7b-base-q4_K_M` for [deepseek-coder](https://ollama.ai/library/deepseek-coder)
- `ollama pull codellama:7b-code` for [codellama](https://ollama.ai/library/codellama)
3. Update Cody's VS Code settings to use the `unstable-ollama` autocomplete provider.
4. …

Autocomplete: add `deepseek-coder:6.7b` support

---

lib/shared/src/sourcegraph-api/graphql/client.ts
vscode/test/e2e/context-settings.test.ts
vscode/test/e2e/helpers.ts
vscode/test/fixtures/mock-server.ts
vscode/test/integration/main.ts

Most interesting thing here: Adds the ability to mock GraphQL responses at a fine granularity, instead of having everyone dump them into the mock server.
```
cd vscode
pnpm test:e2e -- context-settings.test.ts
```

VSCode UI: Add an e2e smoke test for the multi-repo picker

---

vscode/test/e2e/custom-command.test.ts
vscode/test/e2e/helpers.ts

This commit updates the custom command e2e tests. It adds a new test to cover custom commands that are using `openTabs` as context. 
These tests ensure custom commands are executed correctly, added the context accordingly, and provide the expected results.
The newly added e2e test case should pass with all the existing ones.

add e2e test for custom command openTabs context

---

vscode/CHANGELOG.md
vscode/src/completions/get-inline-completions-tests/post-processing.test.ts
vscode/src/completions/text-processing/process-inline-completions.ts

Closes #2912
If the completion is very obviously a prompt continuation, we should not show it. I noticed this too a bunch of time with `// Path: ...` style completions in StarCoder.
- Added unit tests

Autocomplete: Remove obvious prompt-continuations

---

vscode/CHANGELOG.md
vscode/src/chat/protocol.ts
vscode/src/search/SearchViewProvider.ts
vscode/webviews/SearchPanel.tsx

It was not initializing its environment with the VS Code workspace root folders to generate accurate workspace-relative paths. I forgot to add that to the search webview entrypoint (only added it to the chat webview entrypoint).
Confirmed working:
Run a natural language search and confirm you see results instead of the webview disappearing.

fix issue where natural language search panel disappears instead of showing results

---

agent/src/AgentWorkspaceDocuments.ts
agent/src/bfg/BfgRetriever.test.ts
vscode/src/jsonrpc/TextDocumentWithUri.test.ts
vscode/src/jsonrpc/TextDocumentWithUri.ts

Previously, the agent threw an error for `textDocument/*` notificattions when the URI included an exclamation mark. The error was thrown to preserve an important variant that we can always parse and render a URI back into the original string
```ts
vscode.Uri.parse(uri).toString() === uri
```
This variant was getting violated when the JB plugin sent document URIs that included an exclamation mark in them, for example:
```
file:///Users/com.jetbrains/ideaIC-2022.1-sources.jar!/com/intellij/RequiresBackgroundThread.java
```
The `!` got encoded as `%21`. This PR "fixes" the problem by mutating the `uri: string` property to get the `Uri.toString()` formatted URI. t's not a super satisfying solution, it would be more desirable if we can get `vscode.Uri.parse(..).toString()` to be a safe …

Agent: handle document URIs with exclamation marks

---

vscode/src/services/StatusBar.ts
vscode/test/e2e/cody-ignore.test.ts

Update status bar background color on ignored files (behind unstable flag)
- Added functionality to the status bar in StatusBar.ts to display whether the current file is ignored by Cody or not by switching the background color of the status bar item.
This feature allows users and devs to easily identify if the current file is being ignored by Cody directly from the editor.
This feature is behind the unstable feature flag. When unstable flag is not enabled, the background will not be updated based on ignore file.
Note: I found it hard to tell if cody ignore is active or not during development and testing. We can remove it when this is out of unstable state. 
1. Go to a Cody ignored file
2. Check if the status bar item update accordingly
As discussed with Tim, we willl update the background …

display .cody/ignore status in status bar

---

vscode/src/completions/context/retrievers/bfg/bfg-retriever.ts
vscode/src/jsonrpc/bfg-protocol.ts

- I started testing BFG locally and bumped into a runtime error. The context mixer [logic](https://github.com/sourcegraph/cody/blob/7106a4fc2c8d088961f66de2336217a87805136f/vscode/src/completions/context/context-mixer.ts#L110) expects context snippets to have the `uri` field. This field [was added](https://github.com/sourcegraph/cody/pull/2749) relatively recently, but neither the BFG implementation nor the client retriever was updated accordingly. 
- This PR fixes the issue on the client side and adds additional types that would prevent the problem from happening. AFAIU, this solution is similar to the approach `LocalEmbeddingsController` uses, where local embeddings snippet types returned by Cody engine [are defined separately](https://github.com/sourcegraph/cody/blob/main/vscode/src/jso …

Autocomplete: update BFG snippets structure to match the format expected on the client

---

vscode/scripts/github-changelog.ts

We aligned on using dashes for the release posts and change the `since v{version}` code to be correct (well, more correct, it doesn't support major version bumps but these don't happen often anyways (and would need quite a bit of code to work as we would need to know the last minor version that we released on the prev. major).
```
pnpm -C vscode run github-changelog && cat vscode/GITHUB_CHANGELOG.md
> cody-ai@1.2.2 github-changelog /Users/philipp/dev/cody/vscode
> ts-node-transpile-only ./scripts/github-changelog.ts
✨ See the [What’s new in v1.2](https://about.sourcegraph.com/blog/cody-vscode-1-2-0-release) blog post for what’s new in this release since v1.1 ✨
- Fixed an issue where the natural language search panel would disappear instead of showing results by @sqs in …
```

Cosmetic changelog script improvements

---

vscode/package.json

These shortcuts were accidentally not enabled everywhere as part of https://github.com/sourcegraph/cody/pull/2865
We can enable these shortcuts fully now, even when the command hint setting is off
1. Check the `unstable` flag is off
2. Check shortcuts show normally

Edit: Fix chat/edit shortcuts

---

vscode/src/main.ts
vscode/src/services/SidebarCommands.ts
vscode/src/services/treeViewItems.ts

Fixes #2365
@chenkc805 The only difference from your link is that instead of `CodyVSCodeExtension:sidebar:preReleaseNotes:clicked` I called the event `CodyVSCodeExtension:sidebar:releaseNotes:clicked` (since it will be the same for both stable and insider releases)
https://github.com/sourcegraph/cody/assets/458591/3e67daef-236c-49ce-96cb-36c2330b7cb4

Add analytics to settings & support items

---

vscode/src/services/AuthProviderSimplified.ts

Part of the accounts migration from sourcegraph.com to accounts.sourcegraph.com (SAMS). Using this new auth url that enables us to redirect to SAMS and back to dotcom. 
I wasn't able to test the GitLab login properly as my account is too new, could someone help with this? 
For more context, see [Joe's explanation](https://sourcegraph.slack.com/archives/C05AGQYD528/p1706593310231579?thread_ts=1706585008.158329&cid=C05AGQYD528)
Pull the branch, **make sure you are logged out of sourcegraph.com AND accounts.sourcegraph.com**. Head to the editor, log out of Cody, confirm that each login has the right url and try logging in.
See each scenario below:
GitHub
https://github.com/sourcegraph/cody/assets/51868853/6390ac11-d228-4c2c-8960-edc85d7ef558
GitLab …

cody: change auth endpoint to handle SAMS redirect

---

vscode/test/e2e/command-edit.test.ts

Adding a new e2e test for `/edit` command, specifically for testing the code lenses to view diff, accept, retry, and undo edit instructions provided by Cody. 
Code Lenses should appear after submitting or retrying an edit instruction, and allow quick access to view the diff, accept the change, retry the instruction, or undo the edit.
The new test cover the following features used by /edit
A separate test should be created for testing other options on the Edit Menu.
CI should be green with the newly added test

add e2e test for /edit

---

lib/ui/src/chat/TranscriptItem.tsx
lib/ui/src/chat/components/EnhancedContext.tsx
vscode/CHANGELOG.md
vscode/test/e2e/core-commands.test.ts

Do not display sparkle emoji in Context list if no enhanced context was used, aka messages from the core commands.
`/smell`
`/explain`
updated e2e tests to reflect this change.

fix: remove sparkle from context list without enhanced context

---

vscode/src/non-stop/codelenses.ts

context: https://sourcegraph.slack.com/archives/C05AGQYD528/p1706865888514999
the retry button doesn't work on untitled file it seems, and since we have disabled the "edit" button for the core commands in chat, will remove the retry code lens from the /test command as well until it is fixed.
the current e2e test for the /test command should still pass as it only looks for "undo" and "Accept" in the test 😎

remove retry lens from /test

---

vscode/src/commands/GhostHintDecorator.ts

Non-file selections:
- E.g. the "Cody by Sourcegraph" output log. --> Edit isn't possible here
- Multiple selections -> Edit is technically possible on the first selection, but this is confusing if a user has multiple selections, so we just hide the text for now.
- Idea for the future: Trigger the same edits for each selection ?
1. Make selections in above condiitons
2. Check no command hints are shown

Edit: Add command hint filters against non-file selections and multiple selections

---

lib/shared/src/cody-ignore/ignore-helper.test.ts
lib/shared/src/cody-ignore/ignore-helper.ts

The `ignore` library doesn't appear to handle comments itself. When the ignore file contained comments on a line like:
```
.foo # comment
```
This would not match `.foo` files. We now strip comments from the end of lines before processing.
- `run pnpm test:unit ignore` and ensure the new test that contains comments passes

Fix ignore patterns that have trailing comments

---

lib/shared/src/commands/types.ts
vscode/package.json
vscode/src/commands/execute/index.ts
vscode/src/commands/execute/terminal.ts
vscode/src/main.ts

Every time I encounter an error in the terminal, I need to copy and paste the error message into the chat and ask Cody to explain or debug it for me. I just discovered that there is an API to add a contribution point to the right-click menu in the VS Code terminal. I am proposing adding an option to 'Ask Cody' directly from the terminal output window.
This PR adds a new "Ask Cody" option to the terminal right-click menu that allows users to `Ask Cody` to explain the selection from their terminal output:
- The terminal output will be sent to chat view with a predefined prompt that they can easily edit with the edit button.
- Register a new command called `cody.command.explain-output` and bind it to the terminal view context menu.
Select text in your terminal and right click to `Ask Cody`: …

feat: ask Cody about terminal output

---

vscode/test/fixtures/multi-root.code-workspace
vscode/test/fixtures/workspace2/README.md
vscode/test/integration/main.ts
vscode/test/integration/multi-root/index.ts
vscode/test/integration/multi-root/workspace.test.ts
vscode/test/integration/runner.ts
vscode/test/integration/single-root/api.test.ts
vscode/test/integration/single-root/chat.test.ts
vscode/test/integration/single-root/commands.test.ts
vscode/test/integration/single-root/index.ts
vscode/test/integration/single-root/workspace.test.ts
vscode/test/integration/tsconfig.json

This moves the existing integration tests into a `single-root` folder and adds a `multi-root` folder. Because we can't change between single/multi-root while tests are running (it causes an extension host restart), these are separate invocations (`vscode/test/integration/main.ts` was updated to have a set of test folders / workspaces).
This is work towards https://github.com/sourcegraph/cody/issues/3003, which is to have integration tests that open a multi-root workspace and ensure ignores are handled correctly for each (I have some basic tests for this but they're failing and need some debugging).
- Check bot results
- Ensure results include both:
- the original single-root integration tests (including the new "Single-root Workspace was correctly loaded" test) …

Add support for integration tests using a multi-root workspace

---

vscode/CHANGELOG.md
vscode/src/commands/utils/get-commands.test.ts
vscode/src/commands/utils/get-commands.ts
vscode/test/e2e/custom-command.test.ts
vscode/test/e2e/helpers.ts

context: https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1706656724966049
fix: handle commands missing prompts when building map
Issue: Currently, an invalid entry in the cody.json will cause custom commands not showing up in the command menu.
Fix: Updated the get-commands utility to skip adding commands to the map if they don't contain a prompt property. It updates the command type and adds null checking before accessing the prompt property.
This prevents crashes when building the custom command map if a command is missing the expected prompt field.
Updated both the unit test and e2e test to ensure an invalid custom command entry would not break the custom command at build time.
Create a custom command entry without adding a prompt in your cody.json.
Before: all your custom command …

fix: handle missing prompts in custom commands

---

vscode/src/services/StatusBar.ts

fix: check scheme before ignoring file in status bar
The status bar logic was ignoring files without checking the URI scheme first. This fixes it to only ignore files with the 'file' scheme, preventing incorrect ignoring of other URI types.
Note: this is only available behind the unstable feature flag.
in your editor, create an untitled file
before: the cody icon will light up as we mark all the non-files as ignored
after: cody status bar does not light up

fix: ignore non file in status bar

---

agent/src/vscode-shim.test.ts
agent/src/vscode-shim.ts
vscode/src/repository/repositoryHelpers.ts
vscode/src/services/cody-ignore.ts
vscode/src/test-support.ts
vscode/src/testutils/mocks.ts
vscode/src/testutils/uri.ts
vscode/test/fixtures/multi-root.code-workspace
vscode/test/fixtures/workspace/.cody/ignore
vscode/test/fixtures/workspace/ignoreTests/ignoreTest.ws1
vscode/test/fixtures/workspace/ignoreTests/ignoreTest.ws2
vscode/test/fixtures/workspace2/.cody/ignore
vscode/test/fixtures/workspace2/ignoreTests/ignoreTest.ws1
vscode/test/fixtures/workspace2/ignoreTests/ignoreTest.ws2
vscode/test/integration/multi-root/ignore.test.ts

This adds some integration tests that in an active multi-root workspace in VS Code, the ignore files are set up and applied correctly.
Also includes some tweaks to the shim `findFiles()` to support `RelativePattern` which fixes an issue where we could add ignore rules from the "wrong" workspace folders (not in a breaking way, but it was confusing to debug and slower because we ran a search across all workspace folders for each workspace folder).
Fixes https://github.com/sourcegraph/cody/issues/3003
- Check bot results for the new tests, or:
- Open the `multi-root.code-workspace` workspace from `fixtures` and verify that the `.ws1` is ignored only in workspace1 and that `.ws2` file is ignored only in workspace2.

Add integration tests for Ignores in multi-root VS Code workspaces

---

agent/src/vscode-shim.ts

When we receive the initialization message from the client, only add the workspace folders if they don't already exist. Previously, when the agent service lived past the client lifespan, a subsequent client could add a duplicate workspace folder. (Currently, I think we only hit this in the dev environment if the agent is run separately.)

Don't add duplicate workspace folders

---

vscode/src/editor/utils/editor-context.ts

exclude build/ and .class files from user context files

---

agent/package.json

Makes `pnpm test:unit` work with bash on macOS
Test-only

fix build in bash

---

vscode/src/services/AuthProviderSimplified.ts

This is a follow-up improvement to https://github.com/sourcegraph/cody/pull/2957. TIL we can configure auth provider in Sourcegraph to have a static `pc` to reference to. This is strictly better than relying on the brittle sha256 of current provider config.
Manually tested
and

cody: update auth endpoint for SAMS redirect

---

vscode/src/completions/get-inline-completions-tests/multiline-truncation.test.ts
vscode/src/completions/text-processing/utils.ts

- If the last completion line starts the next-non-empty-suffix line, we didn't truncate it, which caused completions to be suggested with redundant closing brackets:
- This PR fixes the issues and adds a unit test to cover this case.
- [Slack report](https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1705662932035059)
CI

Autocomplete: truncate the last completion line if it matches suffix

---

agent/src/index.test.ts
vscode/src/commands/execute/ask.ts
vscode/test/e2e/cody-ignore.test.ts

This commit adds a check for the chat and commands config features before executing the chat command. If either feature is disabled by the site admin, an error message is shown and the command is not executed. This gates usage of the chat and commands behind the config features.
Also updated behavior where running a command in an ignored file will returns an error.
connect to an instance that has chat or command disabled, and check if the error message shows up correctly.

Add config feature gating for chat and commands

---

vscode/CHANGELOG.md
vscode/src/services/StatusBar.ts

c.f.: https://sourcegraph.slack.com/archives/C05AGQYD528/p1707217245795609?thread_ts=1707216986.020879&cid=C05AGQYD528
Needs a quick change from to `window.showQuickPick` to `window.createQuickPick`.
https://github.com/sourcegraph/cody/assets/458591/b8d5ec4e-5c2e-49c5-92f8-c80ba9f70acb

Autocomplete: Add button to quickly expose Autocomplete options to status bar items

---

vscode/test/e2e/core-commands.test.ts

wait for the input box to show up before `.fill`
bot should be green

fix flanky e2e test

---

agent/recordings/defaultClient_631904893/recording.har.yaml
vscode/src/edit/input/get-input.ts
vscode/src/edit/input/quick-pick.ts
vscode/src/edit/manager.ts
vscode/src/edit/utils/edit-selection.ts

This PR:
- Always expands the Edit selection to include all non-whitespace characters from the selected lines.
This is a change that will help ensure users don't accidentally miss characters from their selection. Edit will only act on the selected range, so this reduces the likelihood of bad output.
There is some use case for inner-line ranges, but it's unlikely to be of a benefit for the user. The value of doing this outweighs that feature.
1. Create a selection that doesn't contains all chars from a full line
2. Trigger an edit
3. Check that the edit acts on the full line

Edit: Always expand range to include all non-whitespace chars

---

vscode/src/edit/input/get-input.ts
vscode/src/edit/manager.ts
vscode/src/edit/utils/edit-models.ts
vscode/src/main.ts

CLOSE https://github.com/sourcegraph/jetbrains/issues/511
CONTEXT: https://sourcegraph.slack.com/archives/C05B7C6FBPX/p1707210738623389
Sync the edit models used by the edit manager with the latest authentication status rather than just initializing them once on startup. This allows edit models to be refreshed when auth config changes.
- Syncing the edit models in the edit manager when the auth status changes rather than just on init
- Getting the edit models based on the auth status rather than directly from the auth provider
- All current tests should continue passing.
- Edit should work.
Confirmed this change work with https://github.com/sourcegraph/cody/pull/3055:

fix: sync edit models on AuthStatus change

---

vscode/src/edit/manager.ts

Removed in: https://github.com/sourcegraph/cody/pull/3058
We still need to do this on init, as `syncAuthStatus` is only called if the auth status is actually changed. This change handles the case where the user is already authenticated and e.g. just reloads the editor.
1. Ensure authenticated
2. Reload the VS Code window
3. Try to trigger an edit

Edit: Always set `models` on initialization

---

vscode/src/edit/input/get-input.ts
vscode/src/edit/input/get-items/range.ts
vscode/src/edit/manager.ts
vscode/src/edit/utils/edit-intent.ts
vscode/src/edit/utils/edit-selection.ts
vscode/test/e2e/core-commands.test.ts

We would not expand the `doc` intent if we first through we could override it to be `add`.
This just improves our `smartSelection` to always expand in this case
Before:
https://github.com/sourcegraph/cody/assets/9516420/26685fae-6afc-4fe8-8f51-29af0e478a19
After:
https://github.com/sourcegraph/cody/assets/9516420/a0917adb-f540-4cd1-93d9-67d122fe7432
1. Start a doc command by right clicking on an empty line inside a function
2. Check the range expands as much as it can

Edit: Always expand `doc` command

---

vscode/src/commands/GhostHintDecorator.ts
vscode/src/main.ts

Only show command hints if the user is authenticated
1. Confirm you can see the ghost text when auth
2. Confirm you can see the ghost text when unauth
3. Confirm you can never see the ghost text when the setting is disabled

Edit: Disable command hints for unauthenticated users

---

vscode/src/completions/providers/fireworks.ts
vscode/src/completions/utils.test.ts
vscode/src/completions/utils.ts

- The `generatorWithTimeout` did not finish the inner generator if the consumer stopped earlier. It caused the `onComplete` completion event never to be logged to the Cody output channel. This PR fixes it by introducing the `finally` clause that finishes the inner generator instance.
- I did not experience this issue until I turned off hot-streak completions locally.
Added unit test

Autocomplete: always log `onComplete` debug event

---

vscode/CHANGELOG.md
vscode/src/completions/format-completion.ts

- Closes https://github.com/sourcegraph/cody/issues/3050
- Seems like a bug in the `executeFormatRangeProvider` command. It does not produce consistent results and does not honor `rangeToFormat`. This PR falls back to the `executeFormatDocumentProvider` command we use for the edit command.
1. Start a new if statement: `if (` without closing bracket
2. Wait for a suggestion to pop up
3. Accept a suggestion
4. The first line often should not be removed

Autocomplete: use `executeFormatDocumentProvider` for completion formatting

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/src/index.test.ts

When triggering the "Document code" command in JetBrains with an Enterprise account, we hit on the following error
```
InternalError: Cannot read properties of undefined (reading 'model')
TypeError: Cannot read properties of undefined (reading 'model')
at getModel (/Users/olafurpg/dev/sourcegraph/cody/vscode/src/models/index.ts:24:26)
at Object.get (/Users/olafurpg/dev/sourcegraph/cody/vscode/src/models/index.ts:47:13)
at EditManager.executeEdit (/Users/olafurpg/dev/sourcegraph/cody/vscode/src/edit/manager.ts:102:47)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5): {
"error": {},
"stack": "\nTypeError: Cannot read properties of undefined (reading 'model')\n    at getModel (/Users/olafurpg/dev/sourcegraph/cody/vscode/src/models/index.ts:24:26)\n    at …
```

Add test case to reproduce crash that only happens with Enterprise accounts

---

vscode/src/notifications/cody-pro-expiration.ts

update end date in the notifications. We will need to cut a patch to get this updated in the client before end of week
N/A

PLG: update end date

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/fireworks.ts

c.f. https://sourcegraph.slack.com/archives/C05AGQYD528/p1707411649398769?thread_ts=1706882079.259169&cid=C05AGQYD528
- Enable the feature flag
- Observe the right model is used (`█ CodyCompletionProvider:initialized: fireworks/llama-code-13b`)

Autocomplete: Add Llama Code 13b feature flag

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/CHANGELOG.md
vscode/src/completions/completion-provider-config.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/request-manager.test.ts
vscode/src/completions/request-manager.ts

A few small tweaks from my learnings of looking at some traces:
1. Fixes a bug where the debounce time was increased for non-local models
2. Sets the same debounce time for single-line and multi-line
3. Remove some config evaluations off the critical path. Those are heavily cached but it would still cause the very first completion to be slower
4. Add a new `eager cancellation` experiment that will cancel requests as soon as a new request is created and reduces the debounce time significantly to try and counter the latency regression
- For the new experiment, I added a abort handler in the fireworks client and ensured it was heavily hit
- For the rest, just made sure completions still work. The changes are trivial.

Autocomplete: Various latency related tweaks and new eager cancellation experiment

---

vscode/src/edit/manager.ts

If the task is not created for whatever reason we shouldn't log the edit
1. Try to create an edit
2. Exit the input, without submitting
3. Check no telemetry is sent

Edit: Improve telemetry for cancelled edits

---

.github/workflows/semgrep.yml

Semgrep doesn't efficiently handles automatic checkout to branch/commit. It causes few noise during scan. This PR attempts to clean check out the branch and facilitate the scan
Context: [Slack discussion](https://sourcegraph.slack.com/archives/C05AGQYD528/p1707498575029809)
Semgrep Github Action should be 🟢

Update Semgrep Checkout step with ref & repo

---

.github/workflows/semgrep.yml

Moved semgrep rules out of source directory to prevent dangling changes during semgrep scan.
- CI is 🟢

Move semgrep rules directory

---

vscode/src/chat/chat-view/prompt.test.ts
vscode/src/prompt-builder/index.ts

There was a bug in the logic of `tryAddContext` that could effectively expand the overall char limit we imposed on the prompt by the number of bytes we allocated to enhanced context (60%). This contributed to https://github.com/sourcegraph/cody/issues/3104.
This change properly enforces the overall prompt limit.
See added unit test

properly enforce prompt context limit

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/commands/GhostHintDecorator.ts
vscode/src/services/StatusBar.ts

This PR:
- Adds default enablement for the `cody.commandHints.enabled` setting via a feature flag
- We still respect the default setting value, so users can easily override this if they want
**When `cody.commandHints.enabled` setting is not set:**
1. Set `cody-command-hints` flag to 100%. Check command hints are enabled. Check value is correctly shown in "Cody Settings" menu. 
2. Set `cody-command-hints` flag to 0%. Reload and check command hints are NOT enabled. Check value is correctly shown in "Cody Settings" menu. 
**When `cody.commandHints.enabled` setting is already set to `true`:**
1. Set `cody-command-hints` flag to 0%. Reload and check command hints are STILL enabled. Check value is correctly shown in "Cody Settings" menu. 
**When `cody.commandHints.enabled` setting is already …

Edit: Add feature flag / AB test logic for command hints

---

vscode/src/edit/manager.ts

Small change to stop hiding the ghost text when the input opens. This makes the UI less flicker-y.
1. With command hints enabled, open edit input from selection.
2. Check command hints still show

Edit: Stop clearing ghost text when input opens

---

vscode/webviews/App.tsx

Closes sourcegraph/sourcegraph#59720
This pull requests removes the requirement for experimental config to enable guardrails.
The feature is just hidden behind [a sourcegraph instance config](https://sourcegraph.com/github.com/sourcegraph/cody@30620eb96a4e112611abe1d864b72a3a4c6ad1c3/-/blob/lib/shared/src/sourcegraph-api/graphql/client.ts?L86:5-86:16).
- Manual check - works with site config changes

Guardrails is enabled just via instance configuration

---

lib/ui/src/chat/CodeBlocks.tsx

This updates the labelling of Guardrails to match the product name, and makes some small improvement to the tooltips including show the underlying error message in the error state:
- Hardcoded guardrails to always be running
- Verified displayed as expected

Rename "Guard Rails" to "Guardrails" and update tooltips

---

vscode/src/completions/logger.ts

Add a span event when a completion was already logged as suggested. Mainly to ensure we have attributes attached.
Noticed a few spans with source `null` in Honeycomb. 
- Ensured that this is the codepath taken via adding debugger breakpoints.

Autocomplete: Log if a completion was suggested again

---

lib/ui/src/Chat.tsx
vscode/test/e2e/chat-atFile.test.ts
vscode/test/e2e/helpers.ts

The extractMentionQuery function has been updated to handle cases where the user types the file without tabbing the selection. If a context selection is available and the current chat context query matches the input query, the first context selection should be automatically selected.
Green bots = 🆗 
1. at-mention a file without using tab or enter, just type out the whole file path, and end it with space
2. it should stlil include the file on submit

Chat: improve handling of at mentions

---

vscode/webviews/Components/EnhancedContextSettings.module.css
vscode/webviews/Components/EnhancedContextSettings.tsx

We've had feedback from users who miss the text input placeholder text and go looking in Enhanced Context for how to add a particular file or function (probably also a learned behaviour from other apps and systems that have an explicit button to add files/symbols).
Long term we should move to a UI that has an explicit button. Short term, we can add a hint to let people know how to do that: this PR adds that hint.
| - | - |
| ![CleanShot 2024-02-12 at 11 48 02@2x](https://github.com/sourcegraph/cody/assets/153/c8d7eb8f-f1f5-4780-a43d-df02973b7b06) | ![CleanShot 2024-02-12 at 11 45 16@2x](https://github.com/sourcegraph/cody/assets/153/935a61fe-0abf-45df-ab29-0c3856b6b15c) |
I've made no distinction between Cody Free+Pro and Cody Enterprise.
For Enterprise, given they can …

Add a hint about how to include specific files or functions

---

vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/logger.test.ts
vscode/src/completions/logger.ts

Thinking about #3136 again, I don't think it's helpful to sample these traces even. It's not bad per-se, but it's easier to aggregate if we don't have to filter based on a root span attribute everywhere.
E.g. I want to see the "median" completion time so I get the median timings of specific spans but if I have to exclude some values in the root span, this is getting more complex then necessary. Let's keep it simple and don't even sample these (which also saves some bandwidth)
- Added a debugger breakpoint to see if the sampled attribute is set

Autocomplete: Only sample requests that are also suggested

---

lib/shared/src/sourcegraph-api/graphql/client.ts

Solves the issue https://github.com/sourcegraph/sourcegraph/issues/60050
Basically we already wanted to make sure that GQL and fetch errors aren't something that hammer the logs console so this PR adds an extra case of checking that the error message doesn't have the string that gets repeatedly printed in this users console. 
I didn't thoroughly test this PR in the sense that going back to v5.2.0 and then testing. I did go to that version but doing the setup on my local instance caused other issues for me so I left it. My understanding is that this issue is just about seeing something non necessary in the logs so its not really an actually problematic issue.

Fixing logs on the failed GQL queries for refreshConfigFeatures

---

agent/src/index.ts

Previously, the agent process would kill itself if the Node.js process encountered an uncaught exception because this is the default behavior for Node.js. This was problematic because most uncaught exceptions are innocent, they're typically non-critical code that runs in some un-awaited promise where we forget to wrap the code in try/catch.
This PR adds an uncaught error handler that logs the error (and stack trace) to stderr instead. For clients like JetBrains, we automatically redirect stderr to `idea.log` making it easy to troubleshoot the problem.
This change should be a big stability boost since tiny programming mistakes no longer take down the entire agent process. I am embarrassed we didn't do this sooner, but better late than never.
* Manually add `setTimeout(() => {throw new …

Agent: don't kill entire process on uncaught exceptions

---

vscode/package.json
vscode/src/scm/CommitMessageProvider.ts
vscode/src/services/StatusBar.ts
vscode/test/e2e/commit-message.test.ts

This PR:
- Fixes an issue where VS Code would provide `changes` as an empty array for unstaged files
- Adds a e2e test to cover this
- Adds an item to the Cody feature menu to enable/disable the setting
1. Trigger the Cody commit message with no staged files
2. Check it works!
Other:
1. Check that disabling/enabling the feature from the menu works

Commit Messages: Fix bug with unstaged files and add feature toggle to menu

---

vscode/package.json
vscode/src/commands/GhostHintDecorator.ts

1. Defaults the setting to on, as visible to the user. See comment below as to why that is important
2. Adds default text to the setting description, so users can easily search VS Code settings to disable this if they want to.
**When `cody.commandHints.enabled` setting is not set:**
1. Set `cody-command-hints` flag to 100%. Check command hints are enabled. Check value is correctly shown in "Cody Settings" menu. 
2. Set `cody-command-hints` flag to 0%. Reload and check command hints are NOT enabled. Check value is correctly shown in "Cody Settings" menu. 
**When `cody.commandHints.enabled` setting is already set to `true`:**
1. Set `cody-command-hints` flag to 0%. Reload and check command hints are STILL enabled. Check value is correctly shown in "Cody Settings" menu. 
**When …

Command Hints: Update setting enablement

---

lib/shared/src/chat/markdown.ts
vscode/CHANGELOG.md
vscode/test/e2e/commit-message.test.ts

CLOSE https://github.com/sourcegraph/cody/issues/3085
The regex for allowed URIs in chat messages was updated to allow additional custom URI schemes like 'command:cody.*'. This allows linking directly to Cody guides and other custom VS Code commands from within the chat.
Previously only the `_cody.vscode.open` command is allowed in the chat view, which blocked the `Cody Commands` and `Getting Started Guide` commands from working in the chat view.
This PR adds the `command:cody.` prefix to fix the aforementioned issue.
Click on the `Cody Commands` and `Getting Started Guide` links in a new chat to make sure they work:
https://github.com/sourcegraph/cody/assets/68532117/bf12648f-1f05-48da-bdeb-8a52dfb57eca

Chat: fix welcome messages in chat view

---

vscode/src/chat/protocol.ts
vscode/src/services/AuthMenus.ts
vscode/src/services/AuthProvider.ts
vscode/src/services/LocalStorageProvider.ts

This commit adds validation for sourcegraph tokens in the AuthMenus and AuthProvider files. The showInstanceURLInputBox function in AuthMenus now checks if the user is entering a token as a URL and displays an error message if so. 
Similarly, the formatURL function in AuthProvider now throws an error if the URI is a sourcegraph token, and return `null`.
Additionally, the LocalStorageProvider file now ignores and clears the last used endpoint if the provided endpoint is a sourcegraph token.
Update placeholder value for URL to always starts with `https://` to make it clear that the field is for URL input:
https://github.com/sourcegraph/cody/assets/68532117/9d44427a-3b8b-4c35-812d-aa5b22120d6d

Auth: Add input validation for instance URL

---

.github/workflows/agent-bindings.yml
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/Date.kt
agent/protocol.md
agent/src/cli/scip-codegen/BaseCodegen.ts
agent/src/cli/scip-codegen/KotlinCodegen.ts
agent/src/cli/scip-codegen/MarkdownCodegen.ts
agent/src/cli/scip-codegen/command.ts
agent/src/cli/scip-codegen/resetOutputPath.ts

Previously, we didn't have any clearly written high-level overview of the Cody Agent protocol. As we are increasingly relying on this protocol for different use-cases (JetBrains plugin, ML evaluations, testing), it's worth investing time into documenting the protocol.
Green CI

Agent: add protocol documentation

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/index.test.ts
vscode/CHANGELOG.md
vscode/src/chat/chat-view/chat-helpers.ts
vscode/src/commands/context/current-file.ts
vscode/src/commands/context/directory.ts
vscode/test/e2e/chat-input.test.ts
vscode/test/e2e/command-core.test.ts
vscode/test/e2e/command-custom.test.ts
vscode/webviews/Components/FileLink.tsx

CLOSE: https://github.com/sourcegraph/cody/issues/3110
Updated code to display document range correctly in chat view.
This commit updates the code to correctly handle the selection range. 
- In chat-helpers.ts, the code now opens the text document before setting the selection range. 
- In FileLink.tsx, the code now adjusts the line numbers in the selection range to account for the difference between the range starting at 0 and the editor line numbers starting at 1.
- Updated e2e tests to display the correct line numbers
All changes are covered by the updated e2e tests.
1-15 is used and shows up as 1-15
clicking on 1-15 highlights 1-15 in the document
1-15 is used but showing up as 1-13
clicking one 1-13 link highlights 1-14 in the document

Chat: Display file range correctly

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/CHANGELOG.md
vscode/src/completions/completion-provider-config.ts
vscode/src/completions/get-inline-completions-tests/common.test.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions-tests/languages.test.ts
vscode/src/completions/get-inline-completions-tests/multiline-truncation.test.ts
vscode/src/completions/get-inline-completions-tests/post-processing.test.ts
vscode/src/completions/get-inline-completions-tests/triggers.test.ts
vscode/src/completions/get-inline-completions-tests/windows.test.ts
vscode/src/completions/get-inline-completions.ts

- By default, we now trigger one multiline completion request instead of three. As expected, the latency is better (with multiline wins of up to 150ms).
CI

Autocomplete: ship single-multiline requests

---

vscode/src/commands/services/custom-commands.ts
vscode/test/e2e/command-custom.test.ts

CONTEXT: https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1707992847314209
**NOTE:** No Changelog entry needed as this is a recent change that's not included in stable yet.
Previously, userConfigFile was initialized using this.configFileName but did not get updated when this.configFileName changed at runtime (init()). Now it is set dynamically based on the runtime config.
workspaceConfigFile was already using this.configFileName dynamically. Make userConfigFile consistent by also setting it dynamically based on runtime config.
This allows custom commands to be configured separately for the agent and editor.
We use separate config files (.cody/commands.json and .vscode/cody.json) for the Cody agent and VS Code for configuration Custom Commands right now, with a plan to migrate the one …

Custom Command:  set userConfigFile on runtime

---

vscode/CHANGELOG.md
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/services/StatusBar.ts

This fixes cases like https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1707987812090509 where a loading lease that is never returned would be stuck forever.
- Remove the call of `stopLoading()` in the completions code
- Trigger a completion and wait 30sec.
- The loading indicator now stops

Require a timeout when getting a loading lease

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/index.test.ts
vscode/src/chat/chat-view/context.ts
vscode/src/commands/services/runner.ts

Just a small follow-up from https://github.com/sourcegraph/cody/pull/3089
As discovered by Olaf in the aforementioned PR, the context we used for the custom command tests were not always in the same order when running on CI (especially on Windows), causing the tests to fail with a `recordings not found` error. As a workaround, we added a condition to sort all chat context for agent tests, which might affect the purpose of other tests that utilize enhanced context as those are ranked priorly. 
This PR is to remove the workaround that would affect all the tests that use chat context and add the workaround to context from custom commands context runtime instead. 
All the current tests should be green.

Agent: sort custom command context only

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/index.test.ts
vscode/src/chat/chat-view/agentContextSorting.ts
vscode/src/chat/chat-view/prompt.ts
vscode/src/commands/services/runner.ts

Previously, I was failing to run the agent tests locally in replay mode from the latest `main` even if the tests were passing in CI. The root cause was that we are not sorting context items that we feed to the prompt. The CI tests seem to be flaky, because some open PRs are reproducing the failure even if those PRs have unrelated changes.
This PR fixes the problem by adding an additional sorting step for context items so that the tests pass reliably in replay mode.
Green CI

Agent: make tests more stable

---

vscode/test/integration/main.ts

This ensures the exit codes from multiple test runs are combined correctly.
Although in my testing, failed tests always result un `runTests()` throwing, so the behaviour I saw locally was that if the single-root tests failed, the multi-root tests would never run. This fixes that - both suites will always run now, and whether they fail by `runTests()` throwing, or returning non-zero, we will always get a correct non-zero exit code.
- green CI, both multi-root and single-root tests shown in logs; and
- verify locally that `pnpm test:integration` runs both suites of tests even if there's a forced failure in the single-root tests

Ensure multi-root integration tests run if single-root tests have failures

---

vscode/test/e2e/chat-history.test.ts

Attempt to fix the flanky chat history e2e test that was failing in our Windows CI.
Green bots

Test: update chat history e2e test

---

lib/shared/src/chat/markdown.ts
lib/shared/src/common/markdown/markdown.ts
lib/ui/src/chat/CodeBlocks.tsx

CLOSE: https://github.com/sourcegraph/cody/issues/2563 https://github.com/sourcegraph/security-issues/issues/369
https://github.com/sourcegraph/cody/assets/68532117/4a43239a-e9c7-474d-b6ca-e23750b7af3a
This commit introduces a new feature to the markdown rendering functionality. It adds support for wrapping links with the Cody command in the rendered markdown. This allows for opening links using the editor protocol in VS Code.
It should follow the protocol described in https://code.visualstudio.com/updates/v1_84#_confirmation-for-opening-protocol-links
1. In your cody chatbox, type `repeat after me <a href='https://example.com'>Example</a>`
2. You should see a confirmation dialog regarding the link you're trying to open handles by the editor
3. Confirm all the links in the welcome message …

Security: add handlers for links in chat view

---

.vscode/launch.json
vscode/src/services/sentry/sentry.ts

It seems like some change has (unexpectedly?) removed Sentry from being enabled (at least I could not find `ENABLE_SENTRY` ever being set for production). This PR brings Sentry back plus enables all default integrations when run inside VS Code (so this will add the default `onUncaughtException` handlers etc.
If this is too noisy we can turn it off easily.
- Enable `ENABLE_SENTRY` in local development
- Put a `throw new Error()` somewhere
- Notice that it is being reported by Sentry

Reenable Sentry and enable default integrations

---

lib/ui/src/chat/components/EnhancedContext.tsx
vscode/test/e2e/command-core.test.ts

The chat "context used" list was hiding snippets used in context, because there was logic that would filter out snippets from the same file.
Before:
After:
- Compare context menu with this change and without this change.

chat: do not hide snippets from the same file in context list

---

agent/src/vscode-shim.ts

Previously, we never respected the `dispose()` callback for code lens providers due to a bug in the implementation. I haven't confirmed 100%, but this bug could have caused code lenses to accumulate for agent clients. This PR fixes the bug where we handle the `dispose()` callback, but I don't have time right now to add test cases or validate it fixes the accumulation issue.
Manually verify that code lenses no longer accumulate. Ideally, we should have a test case to reproduce this as well.

Agent: correctly dispose code lens providers

---

lib/shared/src/configuration.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
lib/shared/src/inferenceClient/misc.ts
vscode/package.json
vscode/src/completions/completion-provider-config.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/providers/create-provider.test.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/provider.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/testutils/mocks.ts

Removes feature flags and Fireworks models that are no longer deployed and not used. Ships fast path though (only for dotcom and it's already rolled out to 100% anyways).
- it builds

Autocomplete: Remove unused feature flags and models

---

vscode/CHANGELOG.md
vscode/src/completions/providers/experimental-ollama.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/text-processing/utils.ts

This PR removes the same line suffix information in the ollama prompts. This is going to make it possible to have insertion in the middle of text in the current line.
The issue without that is that we currently do not have a way for yielded completion results to know wether they contain the same line suffix or not. We treat all completions as though they _do_ (so a completion of `console.log(|)` will always include the closing `)`) and if there's no overlap with the current suffix we filter them out. This logic is because in the past, models weren't good enough to deal the same line suffix.
The quick fix is to make sure we also omit the same line suffix info for Ollama prompts and have the model generate the suffix again so we can properly diff it.

Autocomplete: Remove same line suffix information from ollama prompts

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/IconsParams.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ProtocolCommand.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/TitleParams.kt
agent/src/agent.ts
agent/src/index.test.ts
vscode/src/jsonrpc/agent-protocol.ts
vscode/src/non-stop/codelenses/items.ts

**Problem:**
- VS Code allows rendering icons (via an icon font) in code lens, e.g. `$(cody-logo) Accept`
- We cannot assume consumers of Agent will be able to render these icons in the same way
- (Other problem): We include VS Code specific shortcuts in the text of the agent lens
**Solution:**
- Extract icon syntax from title string
- Return `icons[]` with the icon value and the original position in the string
- Consumers of the agent can decide if and how they will render these icons.
**Example:**
VS Code codelens title:
`$(cody-logo) Accept`
Agent output:
```
{
"isResolved": true,
"range": {
"start": {
"line": 4,
"character": 0
},
"end": {
"line": 4,
"character": 0
}
},
"command": {
"title": {
"text": " Accept",
"icons": [
{
"value": "$(cody-logo)",
"position": 0
}
]
},
"command": …
```

Agent CodeLenses: Allow consumers to control how they render `title` icons and omit shortcut labels

---

vscode/src/commands/menus/index.ts
vscode/test/e2e/command-custom.test.ts

Default Commands Menu
Custom Commands Menu
PR to add custom commands back to the main menu as discussed with @toolmantim 
Open the main command menu to check if custom commands are included.

Commands: Include Custom Commands in main menu

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/context.ts

The fused context feature was running for a while inside the `internalUnstable` config and I think it's time to ship this. To avoid breaking things, I'd like to do this with a feature flag (so we can easily killswitch this feature). 
- I added a breakpoint in the debugger to ensure this evaluates to the right value
- You can try it locally by enabling the `cody-chat-fused-context` feature flag on your SG instance and disable `cody.internal.unstable`

Chat: Add flag to enable fused context

---

vscode/src/non-stop/FixupController.ts

We currently attempt to compute the applicable diff even in cases where we don't need it, such as `insert` mode for Edit.
This PR just skips that step.
1. Create an edit, check works as expected
2. Create an insert mode edit, like `Document Code`. Check works as expected

Edit: Skip applicable diff logic when only inserting code

---

lib/ui/src/chat/TranscriptItem.module.css
vscode/CHANGELOG.md
vscode/src/services/AuthProviderSimplified.ts

Once https://github.com/sourcegraph/sourcegraph/pull/60681 is merged,
- Run dev instance from Cursor
- Auth via GitHub

support auth from cursor

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/editor/utils/editor-context.test.ts
vscode/src/editor/utils/editor-context.ts
vscode/src/editor/utils/index.ts

Issue: Currently, we are only showing large file warning for @-mentioned file selections, but not for the files from open tabs we list at @-mentioned start-up selection. 
This PR aims to fix the above issue:
- Updated `getOpenTabsContextFile` to add the `filterLargeFiles` process for locating large files.
- Refactored `getFileContextFiles` function to use a separate `filterLargeFiles` function for better reusability and readability.
1. Open a large file (e.g. [SimpleChatPanelProvider.ts](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/chat/chat-view/SimpleChatPanelProvider.ts)) in your editor
2. open Cody Chat. 
3. In the chatbox, type `@`
4. You should see the large file warning showing up for the opened tabs

Chat: add file size warning to @-tabs

---

vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/commands/CommandsController.ts
vscode/src/commands/index.ts
vscode/src/commands/services/custom-commands.ts
vscode/src/commands/services/provider.ts
vscode/src/services/HistoryChat.ts
vscode/src/services/tree-views/TreeItemProvider.ts
vscode/src/services/tree-views/TreeViewProvider.test.ts
vscode/src/services/tree-views/TreeViewProvider.ts
vscode/src/services/tree-views/chat-history.ts
vscode/src/services/tree-views/commands.ts
vscode/src/services/tree-views/treeViewItems.ts
vscode/test/e2e/command-custom.test.ts

PR add custom commands to sidebar as discussed with @toolmantim
- move the TreeViewProvider registration process for commands to the command provider as that's the service that manages the commands
- reorganize tree-views items into its own folder
- refactor TreeViewProvider to make sure methods are not one-type-specificed
e2e test for custom commands has been updated accordingly.
1. Check the sidebar to see if your custom commands are showing up there
2. Clicking on the custom command in sidebar should work as expected
https://github.com/sourcegraph/cody/assets/68532117/0bc58b64-ba2a-4d7e-add1-3def062ed366

Custom Commands: display commands in sidebar

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/index.test.ts
lib/shared/src/chat/input/at-mentioned.ts
lib/shared/src/chat/input/user-context.test.ts
lib/shared/src/chat/input/user-context.ts
lib/ui/src/Chat.tsx
lib/ui/src/chat/TranscriptItem.tsx
lib/ui/src/chat/components/ChatActions.tsx
lib/ui/src/chat/components/EnhancedContext.tsx
vscode/src/commands/execute/explain.ts
vscode/src/commands/execute/smell.ts
vscode/src/commands/utils/display-text.ts
vscode/test/e2e/command-core.test.ts

enable edits on commands. Replace `the selected code` in the prompt for the explain and smell commands with @-mentioned file with selection range.
1. Run the Explain and Smell commands
2. You should see the @-mentioned file in the prompt
3. You should be able to edit the prompt
https://github.com/sourcegraph/cody/assets/68532117/41754c4a-0e2c-40ed-98ac-91e9285deb8e

Chat: enable editing chat command prompts

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/prompt.ts
vscode/src/edit/prompt/index.ts
vscode/src/prompt-builder/index.test.ts
vscode/src/prompt-builder/index.ts

FIX: https://github.com/sourcegraph/cody/issues/3126
Update to remove consecutive assistant messages after a human message cannot be added due to context limit reach.
Currently, we would stop adding old transcript messages when the limit has been reached, which was causing `found consecutive messages with the same speaker 'assistant'` error because we are not removing the (assistant) response that is associated with the (human) message we are skipping (as we loop through them from back to front).
~~This PR updates to removing the last assistant message responding to the current human message when the limit has been reached, instead of keeping assistant response without adding human message. This prevents the error when adding the preamble ending in 'assistant'.~~
Changes included:
- …

Chat: add transcript messages in pairs

---

lib/shared/src/configuration.ts
vscode/src/chat/ContextProvider.ts
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/context.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/extension.common.ts
vscode/src/extension.node.ts
vscode/src/external-services.ts
vscode/src/graph/bfg/download-bfg.ts
vscode/src/jsonrpc/context-ranking-protocol.ts
vscode/src/jsonrpc/jsonrpc.ts
vscode/src/local-context/cody-engine.ts
vscode/src/local-context/context-ranking.ts
vscode/src/local-context/local-embeddings.ts
vscode/src/main.ts
vscode/src/testutils/mocks.ts

Adding a context ranking module for chat command, which ranks the context from different sources such as embeddings, symf and editor. This feature currently is behind the flag `cody.experimental.chatContextRanker`. We plan to launch the changes first for the internal users.
**Note**: This updates bfg version and the related BFG release associated with this change is: https://github.com/sourcegraph/bfg/releases/tag/v5.3.1781.
Project Plan and offline analysis: https://docs.google.com/document/d/1rg9P-xqAwn_HfgKlzpHqX6v8Mf9cN-9r-S4kjr88jP8/edit?pli=1
Similar to local embeddings, additional indexes are created with [base path here](https://github.com/sourcegraph/cody/blob/hitesh/context-ranking-support/vscode/src/local-context/context-ranking.ts#L36). More specifically, When a user click the …

context-ranking support

---

lib/shared/src/index.ts
lib/ui/src/Chat.tsx
vscode/webviews/UserContextSelector.story.tsx
vscode/webviews/UserContextSelector.tsx

The props `contextQuery` and `formInput` were the same, except the latter had `@` prepended.
CI

UserContextSelector: remove duplicative prop formInput

---

vscode/webviews/App.tsx
vscode/webviews/Notices/OnboardingAutocompleteNotice.tsx
vscode/webviews/Notices/index.tsx

The `vscodeAPI` should be passed down from App to avoid global state, which makes the App story in the storybook work again.
CI

fix App story

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/context.ts
vscode/src/local-context/download-symf.ts
vscode/src/local-context/symf.ts
vscode/src/search/SearchViewProvider.ts

Local indexes are rebuilt automatically on a daily cadence when they are stale. Staleness is determined by checking whether files have changed across Git commits and in the set of working file updates not yet committed. If the indexed directories is not in a Git repository, then reindex every day.

Update symf index when stale

---

vscode/CONTRIBUTING.md

This PR adds documentation for the `CODY_RELEASE_TYPE` environment variable to the `CONTRIBUTING.md` file.
The `CODY_RELEASE_TYPE` environment variable is required to build the extension locally successfully. It specifies the type of release, which can be either `stable` or `insiders`.
By adding this documentation, we can ensure that contributors are aware of the requirements for building the extension locally and can avoid errors during the build process. 
The error that appears due to not setting the environment variable is:
> Invalid release type undefined. Valid values are: ["stable","insiders"]. Specify a a release type in the CODY_RELEASE_TYPE env var.
> ELIFECYCLE  Command failed with exit code 1.
Docs only change

Add documentation for CODY_RELEASE_TYPE environment variable

---

vscode/package.json
vscode/src/completions/providers/ollama-models.ts

- Adds [StarCoder2](https://ollama.com/library/starcoder2) support for autocomplete via Ollama.
- Install the pre-release Ollama version https://github.com/ollama/ollama/releases/tag/v0.1.28
- `ollama pull starcoder2:7b` or `ollama pull starcoder2:15b`
- Update user settings:
```json
{
"cody.autocomplete.experimental.ollamaOptions": {
"url": "http://localhost:11434",
"model": "starcoder2:7b"
},
"cody.autocomplete.advanced.provider": "experimental-ollama",
}
```

Autocomplete: add `StarCoder2` ollama support

---

vscode/test/e2e/chat-history.test.ts
vscode/test/e2e/command-custom.test.ts
vscode/test/e2e/context-settings.test.ts

Playwright provides `page.waitForTimeout`, so we should use it instead of our own `sleep` for consistency.
CI

use `page.waitForTimeout` instead of custom `sleep`

---

vscode/playwright.config.ts

These make it so that test failures will be returned faster, and so that flaky/slow UI behavior must be explicitly accounted for in tests (such as by including `{ timeout: X }` in a `.toBeVisible()` call).
CI

stricter timeouts for vscode e2e tests

---

vscode/src/local-context/download-symf.ts
vscode/src/local-context/symf.test.ts

Previously, it was possible to have 2 parallel symf downloads if `getSymfPath` was called twice before the first download completed. Sometimes, these appeared to interfere with one another.
See added unit test.

ensure symf is only downloaded once

---

vscode/src/commands/utils/display-text.test.ts
vscode/src/commands/utils/display-text.ts

Given a chat message like `Explain @my/file.go :)`, all but the last non-alphanum char was dropped, so the resulting message as seen in the transcript would be `Explain @my/file.go)`. The handling of trailing non-alphanum was to not get tripped up by question marks, but it incorrectly assumed there would only be a single such character. This approach can be fixed more robustly by using a rich editor (https://github.com/sourcegraph/cody/pull/3287), but this is a quick fix for now.
CI

preserve trailing non-alphanum chars in chat message

---

vscode/src/services/LocalStorageProvider.test.ts
vscode/src/services/LocalStorageProvider.ts

The migrations in https://github.com/sourcegraph/cody/pull/2473, https://github.com/sourcegraph/cody/pull/2695, and https://github.com/sourcegraph/cody/pull/2665 have been in the code for one major release and more than a month. We can remove them to simplify the code now.
CI

remove code for old chat history migrations

---

vscode/CHANGELOG.md
vscode/src/edit/prompt/context.ts
vscode/src/prompt-builder/utils.ts

@philipp-spiess noticed that Edit was not including context, which it should have been doing.
Recent work around commands + context improvements introduced a couple of bugs that weren't obvious:
- `contextMessages` are defaulted to `[]` from the Edit input, we had a bad check for these
- `range` is an optional value for `ContextItem`, but we rely on it to generate unique IDs for content within a file. This adds an extra ID mechanism to uniquely hash the `content` of the item alongside the file URI (if available)
1. Create an edit,
2. Check preceding code and following code are included as context

Edit: Fix missing context for instruction-based inputs

---

lib/shared/src/common/range.test.ts
lib/shared/src/common/range.ts
vscode/src/common/range.ts

We should fix the source of any bugs like this, but it's also helpful to handle them gracefully.
CI

handle incorrectly serialized vscode.Range values in toRangeData

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/configuration.ts
vscode/src/testutils/mocks.ts

Follow up on https://github.com/sourcegraph/cody/pull/3256
Context: https://sourcegraph.slack.com/archives/C05AGQYD528/p1708722669252619
This PR updates to enable `cody.debug.enable` by default that allows basic debug logging, which would be helpful with the `Export Logs` feature introduced in https://github.com/sourcegraph/cody/pull/3256
No feature change. Green CI.

Debug: enable debug logging by default

---

vscode/src/commands/services/provider.ts

FIX bug where command sidebar disappears on configuration change ([slack](https://sourcegraph.slack.com/archives/C05AGQYD528/p1709745282681469))
Root cause: Introduced in https://github.com/sourcegraph/cody/pull/3245 by me 😅 , the tree view provider for commands is refreshed without tree items provided on configuration change, causing the sidebar view to be empty
Proposed fix: Since commands are not configurable, there is no need to refresh the sidebar on configuration change. This PR removes the aforementioned code. 
Note: Changelog entry is not required as the change has not been released
2. Update any of your Cody extension settings
3. Confirm the command sidebar is not empty
4. Update any of your Custom Command
5. Confirm the change is reflected in the …

Command: do not refresh sidebar on config change

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
vscode/CHANGELOG.md
vscode/package.json

VS Code: Release 1.8.0 - Stable Release.
Blog post: https://github.com/sourcegraph/about/pull/6791
Version bump

VS Code: Release 1.8.0

---

agent/src/TestClient.ts
agent/src/agent.ts
agent/src/index.test.ts
lib/shared/src/chat/chat.ts
lib/shared/src/chat/transcript/index.ts
lib/shared/src/chat/transcript/interaction.ts
lib/shared/src/chat/transcript/messages.ts
lib/shared/src/index.ts
vscode/src/chat/chat-view/ChatHistoryManager.ts
vscode/src/chat/chat-view/SimpleChatModel.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/prompt.test.ts
vscode/src/chat/chat-view/prompt.ts
vscode/src/edit/prompt/index.ts
vscode/src/prompt-builder/index.test.ts
vscode/src/prompt-builder/index.ts
vscode/src/services/HistoryChat.ts
vscode/src/test-support.ts
vscode/test/integration/helpers.ts
vscode/webviews/App.tsx
vscode/webviews/UserContextSelector.tsx

I am working on #3287, which benefits from having less different data structures that store messages. In working on that PR, I found the following refactors were helpful:
- Remove `MessageWithContext` ([Slack thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1709675835965529))
- Remove `newContextUsed` and `usedContextFiles` fields (that duplicate `ChatMessage#contextFiles`)
- Other code cleanups as a result of these
CI

clean up MessageWithContext, TranscriptJSON, InteractionJSON code

---

vscode/CHANGELOG.md
vscode/src/commands/context/shell.ts
vscode/test/e2e/command-custom.test.ts
vscode/test/e2e/common.ts
vscode/test/e2e/helpers.ts
vscode/test/e2e/utils/buildCustomCommands.ts
vscode/test/e2e/utils/commands.json
vscode/test/e2e/utils/gitWorkspace.ts
vscode/tsconfig.json

FIX https://github.com/sourcegraph/cody/issues/3328
This PR fixes an issue where Cody is unable to use output from a shell command as context for Custom Command.
Root cause: we would run the command from the workspace root using the path of the URI, which doesn't return the path with the correct format on Windows (forward slashes vs backward slashes). 
Proposed fix: Replacing path with fsPath which returns the path with the correct format base on platform works.
Added a new e2e test to ensure shell context can be used across platforms.
1. Start Cody from this branch on Windows
2. Runs a custom command that uses command output as context
3. You should see that Cody is able to get the output from the command instead of showing the `Command Failed: Make sure the command works locally` error

Custom Command: Fix shell command as context on Windows

---

vscode/CHANGELOG.md
vscode/test/e2e/command-menu.test.ts
vscode/test/e2e/update-notice.test.ts
vscode/webviews/Chat.tsx
vscode/webviews/chat/Transcript.tsx

CLOSE https://github.com/sourcegraph/cody/issues/2461
This PR removes the welcome message after the first question has been submitted.
1. Open a new chat to confirm welcome message is displayed
2. Submit a question / execute a command
3. the welcome message should disappear

Chat: Shows welcome message on empty chat only

---

agent/recordings/rateLimitedClient_2043004676/recording.har.yaml
vscode/src/services/AuthProvider.ts

CONTEXT: https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1709840673141329
- Check if the user has an active PRO subscription using getCurrentUserCodySubscription()
- Consider users with a non-PENDING PRO plan as valid pro users
- Set userCanUpgrade based on the active pro user status
This change corrects the detection of pro users by checking their actual subscription status instead of relying on the codyProEnabled flag. It ensures that only users with an active PRO plan are considered valid pro users as we have already implemented in https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/notifications/cody-pro-expiration.ts?L115-117, but the edit code lens that relies on the AuthStatus was not updated correctly in …

Auth: Fix pro status logic

---

biome.json

1. Fixes issue in VS Code where the diagnostics panel would show a Biome parse error in `node_modules/`
2. Fixes issue where `pnpm run biome` would show file-too-large errors for binary files in `vscode/.vscode-test/`
CI

biome ignore node_modules and .vscode-test

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ContextItem.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ContextItemSource.kt
lib/shared/src/codebase-context/messages.ts
lib/shared/src/index.ts
vscode/src/chat/chat-view/context.test.ts
vscode/src/chat/chat-view/context.ts
vscode/src/commands/context/current-file.ts
vscode/src/commands/context/directory.ts
vscode/src/commands/context/file-path.ts
vscode/src/commands/context/selection.ts
vscode/src/commands/context/shell.ts
vscode/src/commands/utils/create-context-file.ts
vscode/src/context/remote-search.ts
vscode/src/edit/prompt/context.ts
vscode/src/editor/utils/editor-context.test.ts
vscode/src/editor/utils/editor-context.ts
vscode/src/prompt-builder/index.ts
vscode/src/prompt-builder/utils.ts
vscode/webviews/UserContextSelector.tsx

Mostly just adds docs. Makes `ContextItemSource` an enum because each item had relevant documentation.
Also now uses `isTooLarge?: boolean` instead of `title === 'large-file'` to indicate the file is too large.
CI

document and reorganize ContextItem source, title, etc.

---

vscode/CHANGELOG.md
vscode/src/completions/providers/ollama-models.ts

- Specify ollama stop sequences per model.
- Removes filename comment from the request to stabilize StarCoder2 output.
- This improves the StarCoder2 output, but it's still unstable and often outputs comments and numbers instead of code.
Set StarCoder2 as the autocomplete model.
```
"cody.autocomplete.experimental.ollamaOptions": {
"url": "http://localhost:11434",
"model": "starcoder2:7b"
},
```
Generate completions.

Autocomplete: ollama per model stop sequences

---

vscode/CHANGELOG.md
vscode/webviews/chat/TextArea.tsx

This PR makes it so that when we paste code into the chat box, it will wrap it in triple backticks.
This improves a few things:
- If someone pasts html/tsx, the code will now no longer be hidden once the request is sent (since it would be escaped otherwise)
- Any pasted code will now be showing with the right indentation after submitting the search query
- LLMs like Opus will not be confused by missing code block delimiters causing the response to also skip code block delimiters.
https://github.com/sourcegraph/cody/assets/458591/6dfe67f4-fe0d-4269-a85c-fecdf8da85a0

Chat: Wrap pasted code blocks in backticks

---

vscode/test/e2e/chat-input.test.ts
vscode/webviews/Chat.tsx
vscode/webviews/Components/ChatModelDropdownMenu.tsx
vscode/webviews/chat/Transcript.tsx

In https://github.com/sourcegraph/cody/pull/3341 the behavior changed so that the welcome message goes away when you chat. (Which I love!) But there's a minor bug in that the model selector remains enabled after the 1st message is sent now (because the existing logic assumed that the welcome message was always the 1st message and so checked for `>1` messages to disable the model selector).
Also adds an e2e test for the model selector.
e2e test covers the following test plan: Open new chat. Ensure model selector is enabled. Send a message. Ensure the model selector becomes immediately disabled.

disable model selector after 1st chat message is sent

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/main.ts
vscode/src/services/StatusBar.ts
vscode/src/services/utils/export-logs.ts

Part of Better debugging facilities for enterprise issues
New commands to make debugging Cody easier:
- `cody.debug.outputChannel`
- open the Cody output channel
- `cody.debug.enable.all`
- enable both `cody.debug.enable` and `cody.debug.verbose` and open output channel with one click
New sidebar menu item to open output channel
New button in the Cody Setting menu to enable debug mode and open output channel on click
All debug commands are also grouped together and are available through the command palette
https://github.com/sourcegraph/cody/assets/68532117/3ec5a97b-8d09-4b72-92a5-d08f17bad72a

Debug: Enable debug mode from setting menu

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
vscode/CHANGELOG.md
vscode/package.json

VS Code: Release 1.8.2 - Stable
Version bump

VS Code: Release 1.8.2

---

vscode/src/commands/utils/display-text.ts

If chat history lacks `displayText` (which should never happen, only if you have a local dev extension that writes chat history without that field, as I did), then Cody initialization will crash and Cody is completely unusable. This is because Cody attempts to synthesize the `displayText` but assumes that the value contains classes (including a `vscode.Uri` value on which it calls `toJSON()`), but actually the value was just serialized from JSON and does not have any nested class instances.
This would cause the following error message at initialization:
```
TypeError: file.toJSON is not a function
at replaceFileNameWithMarkdownLink (/home/sqs/.vscode/extensions/sourcegraph.cody-ai-1.8.2/dist/extension.node.js:124096:12)
```
(But again, nobody should experience this. Still, this fix is …

do not crash initialization if chat history somehow lacks `displayText`

---

agent/src/cli/evaluate-autocomplete/AutocompleteMatcher.ts
agent/src/cli/evaluate-autocomplete/Queries.ts
agent/src/cli/evaluate-autocomplete/strategy-bfg.ts
agent/src/cli/evaluate-autocomplete/testParse.test.ts
pnpm-lock.yaml
vscode/package.json
vscode/scripts/download-wasm-modules.ts
vscode/src/completions/get-inline-completions-tests/multiline-truncation.test.ts
vscode/src/completions/get-inline-completions-tests/post-processing.test.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/text-processing/parse-completion.ts
vscode/src/completions/text-processing/truncate-parsed-completion.ts
vscode/src/tree-sitter/grammars.ts
vscode/src/tree-sitter/parse-tree-cache.ts
vscode/src/tree-sitter/parser.ts
vscode/src/tree-sitter/queries/go.ts
vscode/src/tree-sitter/queries/javascript.ts
vscode/src/tree-sitter/queries/python.ts
vscode/src/tree-sitter/query-sdk.test.ts
vscode/src/tree-sitter/query-sdk.ts
vscode/src/tree-sitter/query-tests/annotate-and-match-snapshot.ts
vscode/src/tree-sitter/query-tests/documentable-nodes.test.ts
vscode/src/tree-sitter/query-tests/intents.test.ts
vscode/src/tree-sitter/query-tests/node-at-cursor-and-parents.test.ts
vscode/src/tree-sitter/query-tests/singleline-triggers.test.ts
vscode/src/tree-sitter/query-tests/test-data/intents.snap.ts
vscode/src/tree-sitter/query-tests/test-data/parents.snap.ts
vscode/src/tree-sitter/test-helpers.ts

- Upgrade tree-sitter from `0.20.8` to `0.21.0` and update the code based on breaking changes.
- Migrate from custom S3-hosted grammars to the latest grammars from `npm` via [tree-sitter-wasms](https://github.com/Gregoor/tree-sitter-wasms). This expands the tree-sitter language support and improves grammars error tolerance.
- Follow-up issue https://github.com/sourcegraph/cody/issues/3374
- Add timeout to the tree-sitter parse method to avoid freezing users' editor instances in case of unexpected errors.
- Refactor how tree-sitter edits are calculated to paste completions into the existing document. This fixes the issue described in [the Slack thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1709892644622649?thread_ts=1709891165.036869&cid=C05AGQYD528).
- Updated the …

Autocomplete: upgrade tree-sitter and expand language support

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ChatMessage.kt
agent/src/index.test.ts
lib/shared/src/chat/transcript/display-text.test.ts
lib/shared/src/chat/transcript/display-text.ts
lib/shared/src/chat/transcript/messages.ts
lib/shared/src/chat/viewHelpers.test.ts
lib/shared/src/chat/viewHelpers.ts
lib/shared/src/index.ts
lib/shared/src/prompt/prompt-mixin.ts
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/chat/chat-view/SimpleChatModel.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/chat-helpers.ts
vscode/src/commands/utils/test-commands.ts
vscode/src/prompt-builder/index.ts
vscode/src/services/HistoryChat.ts
vscode/test/integration/single-root/chat.test.ts
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/TranscriptItem.tsx
vscode/webviews/chat/fixtures.ts

Previously, `ChatMessage.displayText?: string` was set in multiple places, and the logic for getting the title of a chat was defined in 2 different places (and uses the `displayText`). Now, we never persist `displayText` and instead compute it at display time, which is possible because it uses only data that is available in the `ChatMessage` value.
Also simplify and test reformatBotMessageForChat.
This is a refactor to clear the way for #3287.
CI. Also manually test that chat titles are set based on the last human message in a new chat, and that editing a chat title in the sidebar updates the title in the sidebar and the tab title bars.

compute ChatMessage.displayText on-demand instead of persisting

---

lib/shared/src/common/markdown/markdown.ts

This is an equivalent implementation of `escapeHTML` that just uses regexps and not the DOM, so it's usable in non-DOM contexts.
These replacements are sufficient and match the OWASP recommendation for characters to encode: https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#output-encoding-for-html-contexts.
CI

escapeHTML that does not use the DOM

---

agent/recordings/defaultClient_631904893/recording.har.yaml
lib/shared/src/common/range.test.ts
lib/shared/src/common/range.ts
lib/shared/src/index.ts
vscode/src/commands/execute/explain.ts
vscode/src/commands/execute/smell.ts
vscode/src/completions/tracer/traceView.ts
vscode/src/edit/input/get-input.ts
vscode/src/edit/input/utils.ts
vscode/test/e2e/command-custom.test.ts
vscode/webviews/Components/FileLink.tsx
vscode/webviews/UserContextSelector.tsx

Several places had slightly different logic for rendering ranges and line ranges. Now, anywhere that a range string (such as `1:2-3:4`) or line range string (such as `1-2`) is presented, it uses `displayRange` or `displayLineRange`, respectively.
Refactor related to https://github.com/sourcegraph/cody/pull/3287.
CI

standardize on display{Line,}Range funcs

---

lib/shared/src/sourcegraph-api/graphql/client.ts

Updates the condition for including `X-Sourcegraph-Actor-Anonymous-UID` to always do it, instead of only doing it on unauthenticated users.
n/a

sourcegraph-api: always include anonymous UID

---

.gitignore

This file is created when you regenerate the Kotlin agent bindings and should not be committed to Git.
CI

ignore index.scip

---

.github/workflows/agent-bindings.yml
.github/workflows/ci.yml
.github/workflows/scip-typescript.yml
.github/workflows/vscode-insiders-release.yml
.github/workflows/vscode-stable-release.yml

This PRs pins the 3rd party GitHub actions to their release commit. This prevents potential supply chain attacks. See https://github.com/sourcegraph/security-issues/issues/377 for more information.
See if CI still runs as expected.

Harden the GH actions by pinning the release

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

We got an error report but no match in Sentry. Turns out we handle all chat errors but don't forward them to Sentry.
CI

Chat: Log errors to Sentry

---

vscode/playwright.config.ts

I don't love it, but this seems to make Windows e2e tests pass more reliably.
On this branch, test-e2e on Windows passed 4/4 times (https://github.com/sourcegraph/cody/actions/runs/8259801441/job/22596572234?pr=3390), compared to a pass rate of about 50% looking at `main` (https://github.com/sourcegraph/cody/commits/main/).
CI

more generous retries and timeouts for windows e2e tests to de-flake

---

lib/shared/src/chat/transcript/display-text.ts

Similar to https://github.com/sourcegraph/cody/pull/3367, this prevents Cody from crashing on initialization if the chat history contains `vscode.Range` JSON-serialized values (which are JSON-serialized as `[start, end]`). This is an easy and subtle bug to introduce, and it's valuable to protect against complete crashing on initialization.
The stack trace of the crash that this prevents is:
```
TypeError: Cannot read properties of undefined (reading 'line')
at createDisplayTextWithFileLinks (/home/sqs/.vscode/extensions/sourcegraph.cody-ai-1.8.2/dist/extension.node.js:124081:56)
at getDisplayText (/home/sqs/.vscode/extensions/sourcegraph.cody-ai-1.8.2/dist/extension.node.js:124292:12)
at prepareChatMessage (/home/sqs/.vscode/extensions/sourcegraph.cody-ai-1.8.2/dist/extension.node.js:12427 …
```

prevent Cody from crashing on init with mis-serialized chat history

---

vscode/webviews/vite.config.ts

These were not being used anyway because VS Code does not support external sourcemaps (https://github.com/microsoft/vscode/issues/115440#issuecomment-778473764).
Using `sourcemap: 'inline'` makes it work, but this increases the size of `dist/webviews/index.js` from 1.5MB to 9MB, which may hurt perf.
CI

disable unused vscode webview sourcemaps

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
vscode/CHANGELOG.md
vscode/package.json

The actual release will be from the `vscode-v1.8.3` tag, and #3394 will be backported.
The purpose of this release is to backport:
- Fix crash upon initialization in the stable build if a prerelease version of the VS Code extension was used for chat after 2024-03-08. [pull/3394](https://github.com/sourcegraph/cody/pull/3394).
CI

VS Code release 1.8.3

---

vscode/src/completions/detect-multiline.ts
vscode/src/completions/get-inline-completions-tests/languages.test.ts
vscode/src/tree-sitter/language.ts

- Adds `kotlin` support for multiline completions.
- Closes https://github.com/sourcegraph/cody/issues/3303
- CI
- Added unit test

Autocomplete: add `kotlin` multiline support

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/src/index.test.ts
lib/shared/src/prompt/templates.ts
vscode/src/prompt-builder/utils.ts

Previously, there were several very similar (but slightly different) templates for introducing code snippets as context.
- "Use the following text from FILE ..."
- Sometimes backticks around file paths and repo names, sometimes not.
- Markdown files are cited differently from non-Markdown files.
There were also several unused functions here.
This improves the response quality regarding https://github.com/sourcegraph/cody/issues/3331 (for the `how does authentication work in sourcegraph/cody?` question at least).
CI

standardize on a single prompt format for codebase context

---

lib/shared/src/telemetry/index.ts
vscode/src/chat/chat-view/SidebarViewController.ts
vscode/src/commands/GhostHintDecorator.ts
vscode/src/edit/provider.ts
vscode/src/non-stop/FixupController.ts
vscode/src/services/AuthProvider.ts
vscode/src/services/utils/codeblock-action-tracker.ts

- Bans `hasV2Event` from telemetry properties
- Fixes type errors created from this
Build passes, type only change as this is an unused telemetry property

Telemetry: Fix `hasV2Event` often being included as an event property

---

vscode/webviews/promptEditor/plugins/atMentions/OptionsList.module.css
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.tsx

Previously, this warning was shown on the same line. See the screenshots below. (Note that these are on different color themes, but you get the idea.)
CI

show "File too large" @-mention item warning on 2nd line in menu

---

.vscode/settings.json

This makes it so you can set it to disabled by default in your VS Code user settings so it doesn't show an annoying notification in repositories that don't use Biome.
CI

explicitly enable biome in VS Code workspace settings

---

lib/shared/src/chat/transcript/display-text.ts
lib/shared/src/index.ts
vscode/test/e2e/chat-atFile.test.ts
vscode/test/e2e/chat-edits.test.ts
vscode/test/e2e/command-core.test.ts
vscode/test/e2e/command-custom.test.ts
vscode/webviews/Components/FileLink.module.css
vscode/webviews/Components/FileLink.tsx
vscode/webviews/chat/CodeBlocks.tsx
vscode/webviews/chat/TranscriptItem.tsx
vscode/webviews/chat/actions/TranscriptAction.module.css
vscode/webviews/promptEditor/nodes/ContextItemMentionNode.ts

Now, links in human messages open in the web browser when clicked, instead of showing a VS Code "do you trust this domain?" dialog.
CI; e2e tests handle these cases

remove needless command:_cody.vscode.open wrapping for https? URLs

---

vscode/test/e2e/cody-ignore.test.ts

Not sure why this helps, but it certainly seems to.
CI

make cody ignore e2e test less flaky on Windows

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/main.ts
vscode/src/notifications/setup-notification.ts
vscode/src/services/StatusBar.ts
vscode/test/e2e/auth.test.ts

Updates the Cody status bar button to have the text "Sign in to Cody" when not logged in.
[PRD](https://docs.google.com/document/d/1vYkk-LY65k2x0J1AOldbUyxfK_JQCFc3eCUbULZXx70/edit)
[Asana task](https://app.asana.com/0/1206519077296236/1206519077296305)
Before:
https://github.com/sourcegraph/cody/assets/153/a413dfd0-4ad2-4eec-9549-99a17551511e
After:
https://github.com/sourcegraph/cody/assets/153/8d2214f8-1582-4801-b73a-25b4c4cc6451
Events added:
- `CodyVSCodeExtension:signInNotification:shown`
- `CodyVSCodeExtension:signInNotification:signIn:clicked`
- `CodyVSCodeExtension:signInNotification:doNotShow:clicked`
- `CodyVSCodeExtension:statusBarIcon:clicked, { loggedIn: boolean }`
- CI
- Test logged out & logging in
- Test logged in

Update the logged out status bar item with more obvious CTA

---

agent/src/cli/evaluate-autocomplete/AutocompleteMatcher.ts
agent/src/cli/evaluate-autocomplete/Queries.ts
agent/src/cli/evaluate-autocomplete/testParse.ts
agent/src/cli/evaluate-autocomplete/triggerAutocomplete.ts
vscode/src/completions/get-current-doc-context.test.ts
vscode/src/completions/text-processing/parse-completion.ts
vscode/src/tree-sitter/parse-tree-cache.ts
vscode/src/tree-sitter/parser.ts
vscode/src/tree-sitter/query-sdk.ts
vscode/src/tree-sitter/query-tests/annotate-and-match-snapshot.ts
vscode/src/tree-sitter/test-helpers.ts

- Exposes `parser.observableParse()` method that wraps `parser.parse()` call in OpenTelemtry spans. 
- We still use the regular parse to update parse trees incrementally on every document change. 
CI

Autocomplete: wrap some `parser.parse()` calls in OpenTelemetry spans

---

.github/workflows/e2e-flakiness-detector.yml

Every day at 1400 UTC, this action runs the e2e tests many times (10 times per test case) to detect intermittent flakiness proactively instead of having it be occasionally detected in unrelated PRs. This information will help us fix flaky e2e tests.
CI

add e2e-flakiness-detector GitHub action

---

vscode/playwright.config.ts

This will mean more annoying e2e failures due to flakiness in our PRs, which is bad. But it, along with https://github.com/sourcegraph/cody/pull/3446, will mean that we (if we are good people :) will notice the flakiness better and will fix it, thereby making it so we don't need to wait for multiple retries of some flaky tests on each build, thereby saving us time overall.
We should make this `retries: 0` soon once we reduce the flakes (which #3446 will help us identify).
CI

only allow 1 retry for flaky e2e tests

---

vscode/test/e2e/chat-atFile.test.ts

This e2e test no longer makes sense now that we changed the behavior so that pressing <kbd>Space</kbd> actually does accept the first suggestion. We could add a test for pressing something else like <kbd>,</kbd>, but that seems of marginal importance and we might even want <kbd>,</kbd> and other punctuation to select the suggestion in the future. The reason this test was passing is due to flakiness, a race condition where zero context items were shown because the response had not loaded yet, not because the behavior was as expected.
CI

remove `typing @-mention text does not automatically accept it` e2e test

---

.github/workflows/e2e-flakiness-detector.yml
vscode/test/fixtures/mock-server.ts

The GitHub action appears to fail because of tons of log lines from the thing that logs our telemetry from e2e runs. Example: https://github.com/sourcegraph/cody/actions/runs/8321504214/job/22767854935
CI

fix log spam in e2e flakiness detector

---

vscode/CHANGELOG.md
vscode/src/completions/providers/ollama-models.ts

- Add a missing stop sequence for StarCoder2 served via Ollama. Reference: https://arxiv.org/html/2402.19173v1
Tested locally

Autocomplete: starcoder2 ollama stop sequences

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/CHANGELOG.md
vscode/package.json
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions-tests/models.test.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/get-completion-params.ts

- Preparing for the StarCoder2 A/B test.
- Adds `starcoder2-hybrid` model to the Fireworks provider, which uses `starcoder2-7b` and `starcoder2-15b`.
- Cody-Gateway support https://github.com/sourcegraph/sourcegraph/pull/61207
- Tested locally by mocking the return value of the feature flag provider and asserting that the right requests were made by investigating the output console.

Autocomplete: add StarCoder2 hybrid feature flag

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/context/chatContext.ts
vscode/src/editor/utils/editor-context.test.ts
vscode/src/editor/utils/editor-context.ts
vscode/src/editor/utils/findWorkspaceFiles.ts
vscode/src/editor/utils/index.ts
vscode/test/e2e/chat-atFile.test.ts

1. Finding the list of files now respects the `files.exclude`,
`search.exclude`, and gitignore/ignore files. This makes it much faster
(~1200ms -> 100ms on sourcegraph/sourcegraph on my machine) and eliminates
irrelevant files (such as tons of `bazel-bin/` and `*.js` files).
2. Removes the cancellation on `throttledFindFiles`. This actually made it
slower because each time `throttledFindFiles.cancel()` was called, it would
invalidate the cached result, which means the next call would invoke the
expensive find-files operation even if it had been less than 10000ms since
the previous successful call. We do not need cancellation for this
operation because each call uses the same arguments, so earlier calls are
not wasted and just mean the result will be returned slightly sooner.
Note: the e2e …

speed up & respect ignores in finding workspace files for file @-mentions

---

vscode/test/e2e/README.md
vscode/test/e2e/auth.test.ts
vscode/test/e2e/chat-atFile.test.ts
vscode/test/e2e/chat-history.test.ts
vscode/test/e2e/chat-input.test.ts
vscode/test/e2e/code-actions.test.ts
vscode/test/e2e/cody-ignore.test.ts
vscode/test/e2e/command-core.test.ts
vscode/test/e2e/command-custom.test.ts
vscode/test/e2e/command-edit.test.ts
vscode/test/e2e/command-menu.test.ts
vscode/test/e2e/fixup-decorator.test.ts
vscode/test/e2e/helpers.ts

In our e2e tests, there were many patterns like (where `x` is some Playwright locator, ie a selector query resolved by polling):
```
await x.hover()
await x.click()
```
The intent of this pattern is (except in rare cases where hovering is actually needed) to give extra time for `x` to become visible. But this is unnecessary because Playwright's `.click()` already auto-waits for the locator to become [actionable (see Playwright's definition)](https://playwright.dev/docs/actionability). The effect of these 2 lines is just to double the timeout (from 3s to 6s), which is not usually necessary. If a longer timeout is indeed needed, you can use `.click({timeout: N})`, and if a longer timeout than 3s is ever needed by default, we can update `playwright.config.ts` (but I don't think that's …

remove needless hovers and visibility checks from e2e

---

lib/shared/src/index.ts
lib/shared/src/mentions/query.test.ts
lib/shared/src/mentions/query.ts
vscode/src/chat/context/chatContext.ts
vscode/src/edit/input/constants.ts
vscode/src/edit/input/get-input.ts
vscode/src/edit/input/get-matching-context.ts
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.tsx
vscode/webviews/promptEditor/plugins/atMentions/atMentions.test.tsx
vscode/webviews/promptEditor/plugins/atMentions/atMentions.tsx
vscode/webviews/promptEditor/plugins/atMentions/fixtures.ts

The following 3 places now use the same implementation of parsing `@`-mention queries:
- edit quickpick
- webview editor
- SimpleChatViewProvider backend for webview editor
No change in behavior.
CI. Also, run edit, and try typing `@`, `@#`, and both of those with text following to ensure the behavior is unchanged.

factor out @-mention query scanning and parsing

---

vscode/src/chat/chat-view/context.ts

Rename span not to use embeddings in the name (it uses remote keyword search). 
- this should only change Trace span names
- `pnpm test` passes
- old name is [not used anywhere else](https://sourcegraph.sourcegraph.com/search?q=context:global+chat.context.embeddings.remote&patternType=keyword&sm=0)

Rename span to indicate it doesn't use embeddings

---

.github/workflows/e2e-flakiness-detector.yml
vscode/playwright.config.ts
vscode/test/e2e/chat-atFile.test.ts
vscode/test/e2e/chat-history.test.ts
vscode/test/e2e/cody-ignore.test.ts
vscode/test/e2e/command-core.test.ts
vscode/test/e2e/command-custom.test.ts
vscode/test/e2e/helpers.ts

- Remove `page.waitForTimeout` calls when they are unnecessary (before another `expect` call that waits for 3000ms). Keep `page.waitForTimeout` calls that perform an action immediately after because those delays are needed.
- Improve the @-mention test to check that the correct results are in the mention list for easier debuggability, and slow down keypresses to avoid flakiness that seems only to occur if multiple keyboard events are sent without intervening delay.
- Increase timeout in the Document Command e2e test because formatting sometimes is slow.
- Increase timeout for the e2e flakiness detector because it was timing out (exceeding 15 min).
CI

misc e2e test improvements

---

.github/workflows/ci.yml

Cuts the time for e2e tests on Ubuntu (the only one that blocks merging) from ~7-8min to ~2-3min.
CI

shard e2e tests so they complete faster

---

lib/shared/src/chat/fast-path-client.ts
vscode/CHANGELOG.md

Review this with whitespace changes removed. I need to validate this still works for rate limiting issues.
- Send a message and abort before the message starts streaming the first chars

Fix chat abort before first streaming chunk is coming in

---

lib/shared/src/chat/transcript/display-text.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
lib/shared/src/index.ts
lib/shared/src/mentions/query.test.ts
lib/shared/src/mentions/query.ts
lib/shared/src/mentions/urlContextItems.ts
vscode/CHANGELOG.md
vscode/src/chat/context/chatContext.ts
vscode/src/editor/utils/editor-context.ts
vscode/test/e2e/chat-atFile.test.ts
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.tsx

This is an experimental (off-by-default) feature that lets you, in chat, @-mention web pages by URL to include their text contents as context for the LLM. For example, you can type `what are the books listed at @https://slack.org/reading` into chat, select the context item in the menu, and then press Enter, and Cody will read the contents of that web page.
Requires the experimental and undocumented `"cody.experimental.urlContext": true` VS Code setting (or the `cody-url-context` feature flag, which I enabled for all sourcegraph org members on dotcom).
This is just something we can experiment with internally for now.
[Loom video (below)](https://www.loom.com/share/309d6829b98a46678e28b910af21fd21)
https://github.com/sourcegraph/cody/assets/1976/51995c63-e246-4e55-860b-03a9431caa1e
CI

support @-mentioning URLs to use web page contents as context

---

vscode/src/completions/text-processing/parse-completion.ts
vscode/src/tree-sitter/parse-tree-cache.ts
vscode/src/tree-sitter/parser.ts

- Wrap `parser.parse()` in a try-catch statement, report errors to Sentry and fail gracefully.
CI

Autocomplete: use `parser.safeParse()`

---

lib/shared/src/sourcegraph-api/completions/nodeClient.ts
vscode/CHANGELOG.md

We have observed cases where the response of the SSE endpoint did not contain any SSE events (and was thus malformed). This PR makes it so that in this case we still yield an error and log the actual body in verbose mode.
- Apply a change to the sg server like this
```diff
diff --git a/internal/completions/httpapi/handler.go b/internal/completions/httpapi/handler.go
index 50fb45bcd77..afc1080a63a 100644
--- a/internal/completions/httpapi/handler.go
+++ b/internal/completions/httpapi/handler.go
@@ -204,6 +204,8 @@ func newSwitchingResponseHandler(logger log.Logger, db database.DB, feature type
nonStreamer := newNonStreamingResponseHandler(logger, db, feature)
streamer := newStreamingResponseHandler(logger, db, feature)
return func(ctx context.Context, requestParams …
```

Error when receing an SSE response that does not contain any SSE event

---

lib/shared/src/chat/markdown.ts

Partial fix for https://github.com/sourcegraph/cody/issues/3483. Makes it so that the Markdown is rendered literally with newlines as typed, instead of all being jammed on 1 line. (It does not render the user's code in backticks as code.)
Here is how it looks (not ideal because of the lack of rendering, but better than seen in #3483 since the newlines are preserved):
Type a message with triple-backtick then newline then multiple lines of code. Confirm that the newlines are preserved when the message is displayed in the transcript.

do not strip intentional newlines in chat transcript items

---

vscode/webviews/Components/FileLink.tsx

Small UI change.
Update the tooltip for file links included via remote search to explicitly mention "search (remote)" for unified context to improve clarity and make it easier to identify the search, as currently, we are showing it as `via Search` which overlaps with the search results from `symf`. 
|  symf context | unified context   |
|---|---|
| ![image](https://github.com/sourcegraph/cody/assets/68532117/d8e64b98-9368-48fa-bbf5-b99f66c039cf)  |  ![image](https://github.com/sourcegraph/cody/assets/68532117/927873c9-49a3-49f5-9954-59625cf9be2b)  |

Chat: clarify tooltip for remote search context

---

agent/src/agent.ts
lib/shared/src/commands/types.ts
vscode/src/commands/execute/doc.ts
vscode/src/commands/execute/edit.ts

#3445 on stevey/extension-client-api-rebased landed without 3 code review feedback commits that went to stevey/extension-client-api. This cherry picks these back to main.
CI

Cherry-pick code review feedback missing from #3445

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/commands/GhostHintDecorator.ts

This is now set to 100%. Will also remove the `cody-command-hints` feature from dotcom
Check that the ghost text appears by default, when it has not already been set in settings

Edit: Remove ghost hint feature flag

---

vscode/test/e2e/chat-edits.test.ts
vscode/test/e2e/cody-ignore.test.ts
vscode/test/e2e/command-custom.test.ts

Attempt to fix the flaky e2e tests.
Notice we were expecting the new command to show up on the sidebar and in the menu, so we originally were expecting 2 elements with the new command name:
```
await expect(page.getByText(commandName)).toHaveCount(2)
```
However, in the screenshot captured from the recordings shown below, the same command name will also appear in the background in the editor and on hover, leading the test to fail. To fix this, i've updated the test to expect any number greater than 1, and then click on the actual element to make sure they show up in the expected places.
In some failed recordings, I noticed the `await expect(editButtons).toHaveCount(3)` would fail because the third message wasn't submitted because the second message was still in process. To fix this, i've …

Test: fix flaky e2e tests related to count

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
vscode/CHANGELOG.md
vscode/CONTRIBUTING.md
vscode/package.json

VS Code: Release 1.10.0 - Stable Release.
Blog post: 
- PR: https://github.com/sourcegraph/about/pull/6821
- Preview: https://deploy-preview-6821--sourcegraph.netlify.app/blog/cody-vscode-1-10-0-release
Version bump

VS Code: Release 1.10.0

---

vscode/webviews/promptEditor/nodes/ContextItemMentionNode.module.css

Updates the color for the at-mention input tokens to make it more obvious to user. Right now it's hard to tell between a token and regular input.
Co-author with @toolmantim

Chat: update at-mention input token color

---

vscode/src/edit/manager.ts
vscode/test/e2e/code-actions.test.ts

Currently we log "fix" as an `edit:executed` event:
I think it's better to separate this out in our telemetry, so we have better insight into command usage. We already do this for `doc` and `test`:
1. Run a code action fix
2. Check that `fix:executed` is sent instead of `edit:executed`

Edit: Log telemetry events for `fix` separately

---

vscode/src/chat/context/constants.ts
vscode/src/edit/input/get-input.ts
vscode/src/edit/input/get-items/model.ts
vscode/src/edit/input/get-items/range.ts
vscode/src/edit/input/get-matching-context.ts
vscode/src/edit/input/utils.ts
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.tsx

Follow up on my command in https://github.com/sourcegraph/cody/pull/3494
Updated to share the duplicated at-mention labels and logic to fetch for at-mention context items between edit and chat.
This also adds the missing support for URL as context item to Edit:
Green CI

update: share at mention logics between edit and chat

---

vscode/test/e2e/chat-atFile.test.ts
vscode/test/e2e/update-notice.test.ts
vscode/webviews/promptEditor/plugins/atMentions/atMentions.tsx
vscode/webviews/promptEditor/plugins/atMentions/chatContextClient.tsx

Follow-up on https://github.com/sourcegraph/cody/pull/3489
Backgroud: While debugging the cancellation token issue yesterday ([slack](https://sourcegraph.slack.com/archives/C05AGQYD528/p1710984547497189?thread_ts=1710973220.764839&cid=C05AGQYD528)), I noticed the `handleGetUserContextFilesCandidates`function was unexpectedly getting called with an empty query when the chat view is first mounted, or when the input box is re-focused after closing the @ mention box.
This pull request addresses an issue in the `atMentions` plugin where empty and null query states were not handled correctly. The changes ensure that the plugin distinguishes between a valid empty query used for retrieving open tabs context and a null query indicating a non-mention scenario that we can skip.
- Improved handling …

Chat: skip invalid at-mention request

---

vscode/src/non-stop/codelenses/items.ts

We do not compute a diff for insertions, as we're only inserting new code.
We can likely rework this as part of https://github.com/sourcegraph/cody/issues/3510, to decorate the text as a diff _insertion_.
For now, we're just omitting the CTA for insertions
1. Do an insertion (e.g. document code), check "Show diff" doesn't appear
2. Do an edit, check "Show diff" appears and functions correctly
closes https://github.com/sourcegraph/cody/issues/3509

Edit: Remove show diff CTA for insertions

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/create-provider.ts

Adds an A/B test for Claude 3 Haiku for Autocomplete in our holdout group.
manually overwrite the feature flags on the client and observe the right request being made

Autocomplete: Add Claude 3 Haiku A/B test

---

vscode/CHANGELOG.md
vscode/webviews/promptEditor/nodes/ContextItemMentionNode.ts
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.module.css
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.tsx

CLOSE https://github.com/sourcegraph/cody/issues/3522
A new check has been added to the contextItemMentionNodeDisplayText function. If the contextItem is of type 'file' and has the isTooLarge flag set to true, the context item cannot be added as an @-mention token.
In the Item component, a new warning prop has been added to conditionally apply the .disabled class to the option item. This is used to visually indicate that a large file is disabled and cannot be selected from the context list:
Try to @ a large file
You should not be able to add the file

Chat: Disable adding large-file via @-mention

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/Constants.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ContextItem.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ContextItemSource.kt
lib/shared/src/codebase-context/messages.ts
lib/shared/src/mentions/urlContextItems.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/prompt.test.ts
vscode/src/chat/chat-view/prompt.ts
vscode/src/prompt-builder/index.ts
vscode/test/e2e/chat-atFile.test.ts
vscode/test/e2e/cody-ignore.test.ts
vscode/test/e2e/command-core.test.ts
vscode/test/e2e/command-custom.test.ts
vscode/test/e2e/local-embeddings.test.ts
vscode/webviews/Components/FileLink.module.css
vscode/webviews/Components/FileLink.tsx
vscode/webviews/chat/components/EnhancedContext.tsx

Update context list to match [figma design ](https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=1826-40270&mode=design&t=uR9EdiEEMOLHwOsN-0)
Expected behavior:
- @-mentioned items that are excluded should show up in the UI
- excluded enhanced context will not show up in UI
- no sparkle icon next to context for non-enhanced context items
Ex
- context mixed with enhanced context items will display sparkle next to Context:

Chat: display excluded @-files in UI

---

vscode/test/e2e/chat-atFile.test.ts
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.module.css
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.tsx

https://github.com/sourcegraph/cody/issues/3530
A user on Discord has reported that Cody is incorrectly showing an error message "No symbols found (try installing language extensions and opening a file)":
This error message/tooltip is incorrect as the result is expected to be empty when the query is empty, and not required to have a file opened for symbol search, this PR reverts the tooltip back to `'Search for a symbol to include...'` to display on start-up screen.
- Type `@#` in the input, you should see `'Search for a symbol to include...'`
- `No symbols found` is displayed when no result is returned after typing more than 1 character

Chat: fix at symbol title

---

vscode/CHANGELOG.md
vscode/src/completions/get-inline-completions-tests/models.test.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/unstable-openai.ts

Adding `\n\n` as a stop sequence for singleline completions. I suspect this is one of the reasons for [higher-than-expected upstream char counts](https://redash.sgdev.org/queries/485/source#1003) in the StarCoder2 experiment.
CI

Autocomplete: add singleline stop sequences

---

vscode/src/completions/logger.ts
vscode/src/services/sentry/sentry.ts

This is an attempt to reduce the load of Sentry issues. There are two general patterns I've observed:
- The filter we have for our #1 error is not working (the one that is defined in the project settings) so we're adding it in code instead.
- The other top 3 errors all happen _in other extensions_. You can see this by looking at the stack trace. None of this have the Cody extension in its trace. I believe we can gate against this by investigating the trace.
See https://sourcegraph.sentry.io/issues/?groupStatsPeriod=auto&project=4505743319564288&query=&referrer=issue-list&sort=freq&statsPeriod=30d for more details.
- Stepped through the debugger and looked at traces in Sentry to derive this setup

Sentry: More aggressive filtering on errors

---

vscode/webviews/promptEditor/nodes/ContextItemMentionNode.module.css

Address issue from https://github.com/sourcegraph/cody/pull/3501#issuecomment-2018037797
Remove `.context-item-mention-node::before` that sets background color with opacity, set `background-color` to `rgba(200, 200, 200, 0.2);` to add blurred background instead.

Chat: update @-input token background

---

vscode/CHANGELOG.md
vscode/test/e2e/chat-input.test.ts
vscode/webviews/Chat.tsx

CLOSE https://github.com/sourcegraph/cody/issues/3520
This commit addresses an issue where the Chat component was not properly handling empty input values in the PromptEditor. The changes made in this commit are:
In the onEditorChange callback function, the condition for setting the isEmptyEditorValue state has been updated to check if the trimmed text property of the SerializedPromptEditorValue object is an empty string or not. This ensures that the isEmptyEditorValue state accurately reflects whether the editor has any non-whitespace content or not.
In the onAbortMessageInProgress callback function, a new check has been added to throw an error if the trimmed text property of the SerializedPromptEditorValue object is an empty string. This prevents the user from submitting an empty chat …

Chat: Handle empty chat message input

---

agent/src/index.test.ts
package.json
pnpm-lock.yaml

This updates most medium and all high & critical risk rated vulnerabilities in dependencies. These were reported by Dependabot.
CI tests

chore: Bump dependencies

---

vscode/webviews/promptEditor/plugins/atMentions/OptionsList.tsx

Address comment in https://github.com/sourcegraph/cody/pull/3531#pullrequestreview-1959266608
> I wouldn't show the "(language extensions may be loading)" above two characters
Type the query with more than 2 chars and check if the "(language extensions may be loading)" warning text shows up. It shouldn't

Chat: hide language extensions warning for @-symbol query with 3chars+

---

vscode/webviews/App.tsx
vscode/webviews/Chat.story.tsx
vscode/webviews/Chat.tsx
vscode/webviews/Components/EnhancedContextSettings.tsx

Follow-up on https://github.com/sourcegraph/cody/pull/3547/files#r1540281243
> @toolmantim We want it to appear on the first chat that's created for first time users, not every time a chat is created.
Update to display enhanced context settings on their first chat (when chat history is empty).
Clear your chat history, you can see the enhanced context settings opened by default when you open a new chat:
New chat created with chat history in sidebar will not have enhanced context opened:

Chat: show enhanced context settings on first chat

---

vscode/CHANGELOG.md
vscode/src/commands/context/shell.ts

If a custom command has problems running a context command, this adds the error output to the error notification, allowing you to more quickly debug the issue and try again.
| - | - |
| ![CleanShot 2024-03-27 at 11 40 25@2x](https://github.com/sourcegraph/cody/assets/153/1282b53f-7138-4729-9546-59544e235ed3) | ![CleanShot 2024-03-27 at 11 39 37@2x](https://github.com/sourcegraph/cody/assets/153/e4ab6559-6b14-4d3f-8a00-27007227fb7b) |
```json
{
"broken-command": {
"description": "Totes broken",
"prompt": "This aint gonna work",
"context": {
"command": "command that doesnt work"
}
}
}
```
- Manually tested

Custom Commands: Show context command errors in the notification message for easier debugging

---

vscode/webviews/promptEditor/BaseEditor.module.css

Updates the placeholder styles so it doesn't go over the enhanced context button. Future improvement (which I couldn't get to work) would be to set a `title` so that it shows the full label on hover.
| Before | After|
| - | - |
| ![CleanShot 2024-03-27 at 14 07 19@2x](https://github.com/sourcegraph/cody/assets/153/48656f0e-ce4f-419d-adc0-95a84accf44a) | ![CleanShot 2024-03-27 at 14 06 38@2x](https://github.com/sourcegraph/cody/assets/153/d745a9f6-30ea-4271-8541-bf08c8e370e0) |
- Opened chat
- Resized chat
- Verified ellipsis

Chat: Fix message input placeholder overflow

---

vscode/package.json

Fixes the following problem when running `pnpm -C vscode storybook`:
```
error: unknown option '--no-release-notes'
```
A dependency bump upgraded the storybook package to a version that removed this command-line argument.
CI

rm now-invalid storybook option

---

lib/shared/src/experimentation/FeatureFlagProvider.ts

JetBrains folks: Is the cody-pro-jetbrains flag still used by the jb client? If not we can probably clean it up in the cody repo and the dotcom backend :)
CI

Remove Cody Pro JetBrains flag

---

vscode/webviews/Components/EnhancedContextSettings.tsx

RE: https://sourcegraph.slack.com/archives/C05AGQYD528/p1711540311641009
Reported by @philipp-spiess 
> The updated disable-enhanced-context button doesn’t seem to work on main :grimacing: It’s still pulling in lots of context  for me
This PR updates the PR so that the button and the checkbox use the same function for toggling the setting instead of having separate functions for the same thing.
1. Submit a question with the enhanced context button showing as disabled (no background color, with a slash in the middle):
2. Confirm enhanced context is not added to your question
3. Submit a question with the enhanced context button showing as enabled (with background color):
4. Confirm enhanced context is added to your question
5. Both icons status should match

Enhanced Context: fix input button toggler

---

vscode/webviews/Components/FileLink.tsx
vscode/webviews/chat/actions/TranscriptAction.tsx
vscode/webviews/chat/components/EnhancedContext.tsx

Adds logging for when users click on context items
Ask a question and click on context items:
```
█ logEvent (telemetry disabled): CodyVSCodeExtension:chat:context:opened  {
"details": "VSCode",
"properties": {
"lineCount": 558,
"fileCount": 16,
"excludedAtContext": 0
}
}
█ logEvent (telemetry disabled): CodyVSCodeExtension:chat:context:fileLink:clicked  {
"details": "VSCode",
"properties": {
"source": "embeddings"
}
}
```

Log context clicks

---

vscode/CHANGELOG.md
vscode/package.json

We can fully move over to Opt/Alt+K now. And we have the ghost text set to 100% for hints.
Didn't find any other references to this shortcut
1. Try shortcut
2. Check it doesn't trigger edits

Edit: Remove old shortcut

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ModelUsage.kt
agent/src/agent.ts
agent/src/index.test.ts
vscode/src/jsonrpc/agent-protocol.ts

`id` param is redundant for `chat/models` request and it complicates logic in the jetbrains client. This PR remove that param from the request.
JetBrains part: https://github.com/sourcegraph/jetbrains/pull/1207

Make `chat/models` request `chatID`-agnostic

---

vscode/CONTRIBUTING.md

CONTEXT: https://sourcegraph.slack.com/archives/C05AGQYD528/p1711639269181349
This PR adds documentation on how to create patch releases for the VS Code extension. 
Having a dedicated section on patching will make it easy for maintainers to ship critical bug fixes without bundling major features.
The new "Patch Release" section explains:
- Starting a new branch from the last stable tag
- Cherry-picking fixes from main
- Bumping version and tagging
- Pushing tag to trigger release
- Syncing main with new patch version
Doc update

Doc: patch release instructions

---

README.md

docs: Remove Inline chat section from README
The Inline chat section and its associated image have been removed from the README file as they are no longer supported.
Docs update

Docs: remove Inline chat section from README

---

vscode/test/e2e/command-custom.test.ts

Small improvement for the custom command e2e tests
Recording shows that the custom command e2e test often fails because the unexpected file wasn't closed. This PR attempts to fix the test by closing the old file before it continues to the next step.
Green CI

E2E Test: fix flaky custom command test

---

vscode/webviews/Components/EnhancedContextSettings.tsx

Previously, it would forcibly close the popover if the component re-rendered (for some reason) on a non-first chat. I have not seen this bug actually occur in real usage.
CI

fix always opening EnhancedContextSettings on first chat

---

vscode/webviews/App.story.tsx
vscode/webviews/Chat.story.tsx
vscode/webviews/ChatErrorNotice.story.tsx
vscode/webviews/Components/ChatModelDropdownMenu.story.tsx
vscode/webviews/Components/EnhancedContextSettings.story.tsx
vscode/webviews/OnboardingExperiment.story.tsx
vscode/webviews/chat/Transcript.story.tsx
vscode/webviews/chat/components/ChatActions.story.tsx
vscode/webviews/promptEditor/BaseEditor.story.tsx
vscode/webviews/promptEditor/PromptEditor.story.tsx
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.story.tsx
vscode/webviews/storybook/VSCodeStoryDecorator.module.css
vscode/webviews/storybook/VSCodeStoryDecorator.tsx
vscode/webviews/storybook/vscode-dark-theme.css

Now, the VS Code storybooks use the actual VS Code dark theme CSS variables from https://vscode.dev instead of using a manually maintained list.
Only storybook code is affected.
CI

clean up VS Code storybooks, make them use the default VS Code dark theme colors

---

vscode/webviews/Chat.module.css
vscode/webviews/Chat.tsx
vscode/webviews/chat/ErrorItem.tsx
vscode/webviews/chat/Transcript.story.tsx
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/TranscriptItem.tsx
vscode/webviews/chat/components/EnhancedContext.tsx
vscode/webviews/chat/components/FeedbackButtons.module.css
vscode/webviews/chat/components/FeedbackButtons.tsx

- remove indirection for FileLinkComponent
- remove indirection for ChatModelDropdownMenu
- remove indirection for EditButton
- extract FeedbackButtons and remove indirection
- rm needless ChatButtonComponent (it just wrapped VSCodeButton)
CI

remove indirection in vscode webview React components

---

vscode/webviews/App.tsx
vscode/webviews/Chat.tsx
vscode/webviews/Components/EnhancedContextSettings.story.tsx
vscode/webviews/Components/EnhancedContextSettings.tsx
vscode/webviews/Notices/index.tsx
vscode/webviews/Popups/Popup.tsx

Previously, before the ext host sends the user's chat history, we considered `isNewInstall` to be true. Now, we consider it to be undefined (indeterminate/unknown). Fixes the issue reported by @abeatrix in https://github.com/sourcegraph/cody/pull/3628#issuecomment-2027947292 where the enhanced context settings popup always opened on all chats.
Also renames the prop to be consistent (`isNewInstall`).
Run locally, and ensure that the popup does not display on a non-new install. Flip the value in App.tsx manually and ensure it does show up.

isNewInstall defaults to unknown (undefined) not true

---

vscode/webviews/storybook/VSCodeStoryDecorator.tsx

This makes transcripts tint human vs. assistant messages in the storybook.
CI

display storybooks with vscode-dark theme style variation

---

vscode/test/e2e/chat-atFile.test.ts
vscode/test/e2e/chat-edits.test.ts
vscode/test/e2e/cody-ignore.test.ts
vscode/test/e2e/command-core.test.ts
vscode/test/e2e/command-custom.test.ts
vscode/test/e2e/common.ts
vscode/test/e2e/local-embeddings.test.ts

This will make it easier to change the way that context is displayed in the chat UI (as in #3639).
CI

factor out chat context e2e helpers

---

.github/workflows/semgrep.yml

This PR attempts to improve semgrep scans, (tested this config on `sourcegraph/sourcegraph`)
- Moved checkout script github action to v4 for semgrep
- Moved to v3 for uploading sarif file action script
- optimized few semgrep params to match `sourcegraph/sourcegraph` config to scan only changed files
reference: https://github.com/sourcegraph/security/issues/1286
- CI 🟢

Semgrep: improved Semgrep scan params, upgraded GH action version

---

lib/shared/src/mentions/query.ts
vscode/test/e2e/chat-atFile.test.ts
vscode/test/e2e/chat-edits.test.ts
vscode/webviews/promptEditor/nodes/ContextItemMentionNode.ts
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.tsx
vscode/webviews/promptEditor/plugins/atMentions/atMentions.tsx
vscode/webviews/promptEditor/plugins/atMentions/chatContextClient.tsx

CLOSE: https://github.com/sourcegraph/cody/issues/3589#issuecomment-2026647366
Currently, if you add the range after inputting the file name, the title will show up as `No files found`:
Until you have finished the @-range:
This means you will have to type the whole file path before you can add the file range. Which means if you pressed space or tab on a selection you won't be able to make any changes and have to restart. 
This PR updates:
1. Menu displays correctly while entering the line range.
2. Autocomplete on select, and then select again to turn the selection into token (for files only. Symbol and uri is not affected).
- This allows users to edit the file path, e.g. adding range, before it becomes a token
https://github.com/sourcegraph/cody/assets/68532117/9b91c43f-13ef-40b1-898c-cc0 …

Chat: improve @mentions on input

---

vscode/webviews/App.tsx
vscode/webviews/Chat.tsx
vscode/webviews/Components/EnhancedContextSettings.tsx

FIX & CLOSE https://github.com/sourcegraph/cody/issues/3646
Issue: the Enhanced Context settings would remain open for all new users (user without chat history) 
Root cause: Cause by the useEffect logic where we will open the Enhanced Settings for new users on every `isOpen` value change.
Proposed fix in this PR:
- Makes sure the value for userHistory is loaded before we render the Chat component
- Start the `isOpen` value in the Chat component with the `isNewInstall` value so that we won't need to use `useEffect` to handle this logic
(also looking into why this wasn’t caught by our e2e tests, will update it in a follow-up PR)
Green CI. 
For Manual testing:
1. Clear your chat history
2. Open a new chat to verify the enhanced context settings is opened by default
3. Verify you can close …

Chat: Fix enhance context settings bug

---

ARCHITECTURE.md
vscode/CONTRIBUTING.md

The idea here is to capture architecture advice to help engineers writing and reviewing code. Obviously not comprehensive yet. Ideally the tools and abstractions encode these principles and we can simply rely on the doc for background detail. A complement to the RFC process, the aim is to summarize practical principles in a convenient place accessible to all contributors.
This is a docs-only change.

Add a document for capturing architecture guidance

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/main.ts
vscode/webviews/utils/reportIssue.ts

New "Report Issue" command to allow users to file Github issues with the editor through the built-in `Issue Reporter`.
This commit adds a new command to the *VS Code Issue Reporter* and the *Cody support sidebar* to allow users to easily report issues to us with pre-filled system info. 
- The "Report Issue" command opens the *VS Code Issue Reporter* with `Cody version`, `VS Code Version` and `Host` pre-filled.
Summary of Changes:
- Updated our bug link for filing GitHub issue with relevant labels, project, and template for bug reports.
- Added a new command `cody.debug.reportIssue` under `contributes.commands` to register the "Report Issue" command.
- Added a new menu item under `view/item/context` to display the "Report Issue" command in the Cody support sidebar.
- Updated …

feat: "Report Issue" command for filing bug reports inside VS Code

---

lib/shared/src/models/index.test.ts
lib/shared/src/models/index.ts
vscode/src/main.ts
vscode/src/models/utils.ts

Context:
Fix issues where `syncModelProviders` is not run during the extension activation event.
Currently, we only run `syncModelProviders()` on authStatus change, which means this will not run if the listeners are mounted after the authStatus has been created at activation time. 
- This PR updates to run `syncModelProviders()` after adding  `syncModelProviders()` to the authStatus listener.
- Also updated to only default to .com models if endpoint is dotcom to prevent enterprise using .com models
- If there is a chatModel override in the auth status config, use that to set a single model provider. This allows BYOK customers to configure their own model.
- Fallback to using the default model on the server if no model providers are set.
- Updated to use the default chat model token limit …

Chat: sync models at activation

---

vscode/webviews/storybook/vscode-dark-theme.css

Pulls in 2 new VS Code CSS variables.
Only affects storybooks.
CI

fix vscode theme CSS import regexp

---

vscode/webviews/Chat.tsx
vscode/webviews/promptEditor/PromptEditor.module.css
vscode/webviews/promptEditor/PromptEditor.tsx

Lexical editor autogrows on its own. This container was needed for a plain textarea to autogrow.
No behavior/UI change.
CI

rm needless PromptEditor container

---

vscode/src/commands/GhostHintDecorator.ts
vscode/src/commands/HoverCommandsProvider.ts

This PR enables the hover commands feature based on a feature flag evaluation. 
The main changes are:
- Get the ghost hint enablement config in HoverCommandsProvider to check if EditOrChat or Document are enabled
- Set the isInTreatment flag in HoverCommandsProvider based on:
- The hover commands feature flag
- EditOrChat and Document being disabled in the ghost hint config (control by config settings and feature flag)
This allows us to run an A/B test on the hover commands by enabling it for some users if they have the feature flag and EditOrChat/Document disabled.
The ghost hint config is used to disable EditOrChat and Document as those features conflict with the hover commands. So we want to enable hover commands only if those are off.
This unblocks us from running the planned hover …

Hover Commands: enable and disable ghost text and hover on feature flags

---

vscode/src/commands/GhostHintDecorator.ts

We don't need the enrolment event here, especially now that https://github.com/sourcegraph/cody/pull/3662 is in
Check no telemetry events fired

Edit: Remove enrollment events for document ghost text

---

vscode/src/commands/HoverCommandsProvider.ts
vscode/src/commands/menus/index.ts
vscode/src/commands/services/provider.ts
vscode/src/edit/input/get-input.ts

Changes:
- add telemetry for disabling hover commands
- Log event on edit menu open
- Add event source for general command menu events
These changes aim to provide better visibility and tracking of the hover commands feature's usage, particularly when it is disabled for users in the treatment group. 
Telemetry change

Telemetry: update menu clicks

---

lib/shared/src/configuration.ts
vscode/CHANGELOG.md
vscode/package.json
vscode/src/chat/ContextProvider.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/services/StatusBar.ts
vscode/src/testutils/mocks.ts
vscode/test/e2e/command-custom.test.ts
vscode/test/e2e/command-edit.test.ts
vscode/test/e2e/fixup-decorator.test.ts
vscode/test/e2e/helpers.ts
vscode/test/fixtures/multi-root.code-workspace

Updated the settings menu with the following changes:
1. Show `Commands on Hover` & `Command Hints` in settings menu based on the feature flag for the Hover Commands A/B Test value
2. The toggle for enabling/disabling the Cody icon in the editor title menu has been removed.
Reason: This option can be easily configuration through the title bar by right-clicking on it
All the relevant settings have also been removed
User without the feature flag for `Hover Commands A/B test` should **not** see the setting option for `Commands on Hover`
User with the feature flag for `Hover Commands A/B test` should **not** see the setting option for `Command Hints`

Menu: hide disabled feature flag item

---

vscode/src/commands/HoverCommandsProvider.ts

This commit resolves an issue where the telemetry logging for hover commands was displaying "[object Object],[object Object],[object Object]" instead of the actual command titles.
1. Telemetry Logging Fix:
The previous implementation was logging the entire command objects as strings, resulting in the "[object Object]" output.
To fix this, the commit changes the way command titles are extracted and logged.
Instead of joining the command objects directly, the map function is used to extract the title property from each command object.
The resulting array of command titles is then joined with ', ' as the separator and logged.
2. Rendering Optimization:
As a side effect of the telemetry logging fix, the rendering of hover commands has also been optimized.
The createHoverCommandTitle function …

Command: Fix log format

---

vscode/test/e2e/command-custom.test.ts
vscode/test/e2e/helpers.ts
vscode/test/e2e/local-embeddings.test.ts

This commit update the `openFile` helper function in the VSCode extension E2E tests to fix the incorrect logic and make it more robust and cross-platform compatible. 
This is to fix the local-embeddings e2e test that has been flaky on Windows because the `openFile` helper function which only works on Windows
Update to use the correct shortkey for opening a file from the file picker:
- Currently using `Control+P+Shift` which is to open the command palette
- Control shouldn't work on Mac as well, so the tests were actually not opening the file before this change
- Updated to use `MetaKey+P` correctly. 
- Add check to ensure the extension was loaded before we try opening a file to prevent other windows from stealing focus
- Add checks to make sure the file is opened before we move onto the …

E2E: Fix helper function for file opening

---

vscode/test/e2e/chat-input.test.ts

See code comment.
Example of CI failure: https://github.com/sourcegraph/cody/actions/runs/8566106885/job/23475259217?pr=3418#step:10:98
CI

fix 'chat input focus' e2e test on VS Code 1.88.0+

---

.github/workflows/agent-release.yml
agent/README.md
agent/package.json
agent/src/index.ts

Cody Agent releases are available:
- as self-contained executables for various platforms at [Cody Agent releases](https://github.com/sourcegraph/cody/releases) on GitHub
- from the `@sourcegraph/cody-agent` npm package (`npx @sourcegraph/cody-agent help`)
To build and publish a release using GitHub Actions, bump the version number in the agent's [package.json](package.json) and then push to the `agent-vN.N.N` tag (where `N.N.N` is that version number).
NOTE: The macOS binaries are NOT code-signed. They will not work without code-signing.
Merge and attempt to push to the `agent-v*` tag.

build and release cody-agent in CI

---

agent/package.json
agent/src/cli/root.ts
agent/tsconfig.json
cli/README.md
cli/package.json
cli/src/agentClient.ts
cli/src/chat.ts
cli/src/command.ts
cli/tsconfig.json
pnpm-lock.yaml
pnpm-workspace.yaml
vitest.workspace.js

The experimental Cody CLI spawns the agent and uses it to support CLI invocations like:
```
cody-agent experimental-cli chat -m 'what color is the sky?'
cody-agent experimental-cli chat --context-repo github.com/sourcegraph/{sourcegraph,cody} -m 'how is authentication handled in sourcegraph/cody?'
```
Unlike the previous CLI (which was removed), this CLI requires almost *no changes* to code outside the new `cli/` directory, which is a nice win for the agent architecture and means that this experimental CLI does not necessitate bad code abstractions.
Depends on https://github.com/sourcegraph/cody/pull/3671 to publish `cody-agent` binaries and packages, so that it's easy to run the CLI without building it locally from source.
n/a

experimental Cody CLI

---

.github/workflows/agent-release.yml
agent/package.json

Testing https://github.com/sourcegraph/cody/pull/3671 (will push this to tag `agent-v0.0.4`).
Also fixes the npm auth.
CI

bump agent version to test release CI

---

vscode/playwright.config.ts

I am seeing some e2e tests (`create a new user command via the custom commands menu` most often) take slightly more than 20 seconds to complete sometimes, which leads to them timing out. As long as we keep the expect timeout reasonably low and don't have a lot of `await page.waitForTimeout(...)` calls, it is not necessarily bad to have long e2e tests, and the alternative is that people will slice one logical test into two, which is bad in general.
CI

longer e2e test timeout

---

vscode/webviews/Components/ChatModelDropdownMenu.tsx

`selectedIndex` is not how you are supposed to set the initial value (although there is no documentation about this, only https://github.com/microsoft/vscode-webview-ui-toolkit/issues/433). Instead, use `value` just as you would for an HTML select element. This fixes an issue where in some cases (seen only in our storybooks), the dropdown would show the first item as selected, not the `selectedIndex`th item.
CI

more idiomatic use of VSCodeDropdown

---

vscode/playwright.config.ts

I see a lot of people retrying them. We should fix them to be less flaky, but this will save us time in the meantime.
CI

more retries for windows e2e tests

---

vscode/src/common/persistence-tracker/index.test.ts
vscode/src/common/persistence-tracker/index.ts
vscode/src/common/persistence-tracker/types.ts
vscode/src/completions/logger.ts
vscode/src/non-stop/FixupController.ts

This PR updates the persistence tracker to log `persistence:present` events with a difference of `100` when an insertion is completely removed.
This should make our analytics more accurate
1. Make a completion or "insert" edit
2. Delete the inserted text
3. Check the correct telemetry event is logged after 30 secs
Confirmed:
```
logEvent (telemetry disabled): CodyVSCodeExtension:completion:persistence:present  {
"details": "VSCode",
"properties": {
"id": "b0e0030a-4a6f-482d-bd20-7ec3f595f046",
"difference": 100
},
"opts": {
"agent": true,
"hasV2Event": true
}
}
```

Persistence Tracker: Treat removed events as `difference: 100`

---

vscode/src/services/SidebarCommands.ts
vscode/src/services/tree-views/commands.ts
vscode/test/e2e/command-custom.test.ts

Fix issue introduced by https://github.com/sourcegraph/cody/pull/3708 (my bad)
Right now custom commands on Sidebar are not working.
In SidebarCommands.ts, a new condition is added to the cody.sidebar.commands command handler. If the command is cody.action.command, it logs the sidebar click event with the label 'custom', and then executes the command with the feature name and a source parameter set to 'sidebar'.
In commands.ts, the getCommandTreeItems function is updated to pass the command key as the first argument to the cody.sidebar.commands command, instead of the hardcoded 'custom' string.
These changes allow for custom commands to be executed from the sidebar, with the ability to pass additional arguments and track the source of the command execution. The custom commands can be …

Sidebar: fix custom commands on click

---

vscode/package.json
vscode/src/chat/chat-view/ChatManager.ts
vscode/test/e2e/chat-atFile.test.ts

Pull Request Description:
This commit introduces telemetry events to track when the "Cody Chat: Add context" command is used. It also adds a e2e test to cover the feature. The main changes are listed below.
Add Telemetry Events:
- In ChatManager.ts, two new telemetry events are logged when the "Add context" command is triggered:
- CodyVSCodeExtension:addChatContext:clicked
- cody.addChatContext (recorded using telemetryRecorder)
Improve "Add context" Command:
- In package.json, the "Cody Chat: Add context" command is moved from the "Cody" category to the "Chat" group for better organization and discoverability.
New E2e Tests:
- In chat-atFile.test.ts, a new test case is added to verify the behavior of the "Cody Chat: Add context" command. The test checks if the selected code is correctly …

E2E Test: Add e2e test for the "Cody Chat: Add context" command

---

agent/src/agent.ts

I'm not sure why tsc is failing only for me locally, but that is legitimate error.
@valerybugakov looked at it also and confirmed.
```
agent/src/agent.ts:442:35 - error TS18047: 'polly.persister' is possibly 'null'.
442                 const persister = polly.persister._cache as Map<string, Promise<Har>>
~~~~~~~~~~~~~~~
agent/src/agent.ts:442:35 - error TS2352: Conversion of type 'Map<string, Har>' to type 'Map<string, Promise<Har>>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
Type 'Har' is missing the following properties from type 'Promise<Har>': then, catch, finally, [Symbol.toStringTag]
442                 const persister = polly.persister._cache as Map<string, Promise<Har>> …
```

Fix compilation error

---

vscode/CHANGELOG.md
vscode/src/completions/providers/ollama-models.ts

Autocomplete: Add Codegemma prompt to Ollama provider

---

lib/shared/src/models/dotcom.ts
vscode/webviews/App.tsx
vscode/webviews/Chat.story.tsx
vscode/webviews/Chat.tsx
vscode/webviews/chat/Transcript.story.tsx
vscode/webviews/chat/Transcript.test.tsx
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/models/chatModelContext.tsx
vscode/webviews/storybook/VSCodeStoryDecorator.tsx

This makes it so more of the exthost<->webview RPC code lives in App.tsx, which is fitting. It also simplifies the props we need to pass down.
We did the same thing for enhanced context a couple months ago.
CI

pass chatModels and onCurrentChatModelChange through React context

---

vscode/doc/ollama.md
vscode/src/completions/providers/ollama-models.ts

- Add the current file name at the beginning of the prompt.
- Explicitly set `repeat_penalty=1.0` for the best performance.
1. Install Ollama https://ollama.com/
2. `ollama pull codegemma:2b` or `ollama pull codegemma:7b`
3. Update user settings:
```
{
"cody.autocomplete.experimental.ollamaOptions": {
"url": "http://localhost:11434",
"model": "codegemma:2b"
},
"cody.autocomplete.advanced.provider": "experimental-ollama",
}
```
4. Confirm Cody uses Ollama by looking at the Cody output channel or the autocomplete trace view (in the command palette).

Autocomplete: add file name and repeat_penalty for CodeGemma.

---

lib/shared/src/index.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
pnpm-lock.yaml
vscode/package.json
vscode/src/context/context-filters-provider.ts
vscode/src/context/context-filters.provider.test.ts

- Closes subtasks from https://github.com/sourcegraph/cody/issues/3641
- Add node RE2 package; the RFC specifies RE2
- Fetch the enterprise rules with GraphQL
- Provide a stub implementation for Sourcegraph endpoints which don't support this feature, with a liberal allow policy
- Write a function which takes (repo, relative path) -> do/don't ignore
- Builds on top of backend changes https://github.com/sourcegraph/sourcegraph/pull/61101
- Mirrors backend logic from https://github.com/sourcegraph/sourcegraph/pull/61641
CI and new unit tests

VS Code: add remote context filters provider

---

agent/package.json
agent/src/certs.ts
agent/src/index.ts
pnpm-lock.yaml

Adds support for looking up local certs for windows & linux, just like macOS certs are added to the global agent.
CI passes

Agent add support for Windows and Linux self signed certs. 

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatModel.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

This pull request introduces a new method to the SimpleChatModel class that allows it to dynamically update the underlying model ID and the associated maximum character limit.
The key changes are:
- The maxChars property in SimpleChatModel has been changed from readonly to a regular property, enabling it to be updated.
- A new updateModel method has been added to SimpleChatModel, which allows updating the modelID and recalculating the maxChars based on the new model ID.
- In the SimpleChatPanelProvider, the handleSetChatModel method has been updated to use the new updateModel method, instead of directly modifying the modelID property.
Before this change, the handleSetChatModel method in SimpleChatPanelProvider only updated the modelID property of the SimpleChatModel instance, but did not …

Chat: update token limit on model changes

---

vscode/CHANGELOG.md
vscode/package.json

Adds a "Pop out" CTA to the Chat title bar:
https://github.com/sourcegraph/cody/assets/9516420/cc8d9103-a1d7-422c-b3f0-e308f9556d1a
1. Open chats
2. Make them pop out
3. Check the icon disappears when the chat is popped out

Chat: Add Pop out CTA

---

vscode/webviews/Components/ChatModelIcon.tsx
vscode/webviews/icons/CodyLogo.tsx

fix: use Cody logo for custom chat models
This pull request addresses an issue where custom chat models were not getting an associated icon in the UI. To resolve this, the changes include:
- Added a new `CodyLogoBW` component in vscode/webviews/icons/CodyLogo.tsx that renders a black and white version of the Cody logo.
- Updated the chatModelIconComponent function in vscode/webviews/Components/ChatModelIcon.tsx to use the new CodyLogoBW component when the model is not on our supported list. Previously, the function would return null in this case, resulting in no icon being displayed.
By using the Cody logo as a fallback for custom chat models, this change ensures that all models have a consistent visual representation in the application.
1. Build Cody from this branch
1. In your user …

Chat: default Cody as model icon

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

This PR fixes the issue where an exisiting chat panel will stay hidden when the user tries to send the editor selection to the chat panel as @-mentions token (@-selection) . See video below for example
Expected behavior:
The existing chat panel should be revealed on click
Hidden chat panel will stay hidden on @-selection 
https://github.com/sourcegraph/cody/assets/68532117/69c8beab-42b9-41a0-89e6-14fabf687ac4
Current active chat panel will show up if hidden:
https://github.com/sourcegraph/cody/assets/68532117/0fd048f1-a009-4931-82a3-478a154c44e3

Chat: reveal hidden chat panel on @-selection

---

lib/shared/src/configuration.ts
lib/shared/src/index.ts
lib/shared/src/llm-providers/google/chat-client.ts
lib/shared/src/llm-providers/google/index.ts
lib/shared/src/llm-providers/google/utils.test.ts
lib/shared/src/llm-providers/google/utils.ts
lib/shared/src/llm-providers/groq/chat-client.ts
lib/shared/src/llm-providers/groq/index.ts
lib/shared/src/llm-providers/index.ts
lib/shared/src/llm-providers/ollama/chat-client.ts
lib/shared/src/llm-providers/ollama/completions-client.ts
lib/shared/src/llm-providers/ollama/index.ts
lib/shared/src/llm-providers/ollama/utils.ts
lib/shared/src/llm-providers/types.ts
lib/shared/src/llm-providers/utils.ts
lib/shared/src/models/index.ts
lib/shared/src/models/types.ts
lib/shared/src/models/utils.ts
lib/shared/src/sourcegraph-api/completions/nodeClient.ts
vscode/src/models/utils.ts

CONTEXT: https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1712770567742159
Add internal dev support for Groq models when an API key and config are provided.
This PR adds a new chat client specifically for Groq models provided via the `cody.dev.models"` config option introduced in https://github.com/sourcegraph/cody/pull/3758
I also moved the existing third-party clients (ollama and Google) into a new `llm-providers` directory to centralize them.
1. Create an API KEY in https://console.groq.com/keys
1. Build Cody from this branch
1. In your user settings JSON file, add the following settings and fill in the apiKey field:
```json
{
"cody.dev.models": [
{
"provider": "groq",
"model": "llama2-70b-4096",
"tokens": 4096,
"apiKey": "$YOUR_GROQ_API_KEY"
},
{
"provider": "groq",
"model": …
```

Chat: add chat client for Groq

---

vscode/CHANGELOG.md
vscode/src/edit/input/get-input.ts
vscode/src/editor/utils/editor-context.test.ts
vscode/src/editor/utils/editor-context.ts

The changes in this pull request address an issue where the total size of selected context items could exceed the character budget for the active model when importing through @-mentions.
The Edit Command Menu has been updated to:
1. Track the total size of the selected context items and compare it against the maximum character limit for the active model.
2. Display a "Large File Warning" label in the quick pick items if the size of a selected context item would cause the total to exceed the character budget.
3. Automatically remove any selected context items that are no longer included in the current user input.
Additionally, the `filterLargeFiles` function in `editor-context.ts` has been updated to store the file size in the `ContextItemFile` object, which is used in the `getInput` …

Edit: display warning for large @-mentions

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/CodyAgentClient.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/CodyAgentServer.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/Constants.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/RemoteRepoFetchState.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/RemoteRepo_DidChangeParams.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/RemoteRepo_HasParams.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/RemoteRepo_HasResult.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/RemoteRepo_ListParams.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/RemoteRepo_ListResult.kt
agent/protocol.md
agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/src/agent.ts
agent/src/index.test.ts
vscode/src/context/enterprise-context-factory.ts
vscode/src/context/remote-repo-searcher.ts
vscode/src/context/repo-fetcher.ts
vscode/src/context/workspace-repo-mapper.ts
vscode/src/extension-client.ts
vscode/src/jsonrpc/agent-protocol.ts
vscode/src/main.ts

This adds Agent endpoints for:
- Testing whether a remote has a specific repository.
- Retrieving repository names from a remote matching a fuzzysort.
- Retrieving all repository names from a remote, with pagination.
Closes sourcegraph/jetbrains#605.
Manually tested with sourcegraph/jetbrains#1308
Added agent tests, run with `pnpm test`

Agent protocol and implementation for searching, listing, testing remote repository names

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/CodyAgentServer.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/EditTask_AcceptParams.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/EditTask_CancelParams.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/EditTask_UndoParams.kt
agent/src/agent.ts
agent/src/index.test.ts
vscode/src/jsonrpc/agent-protocol.ts

Fixes API for calling `editTask/undo`, `editTask/accept` and `editTask/cancel`
Manual tests with the JB plugin

Fix undo/accept/cancel command calls

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/main.ts
vscode/src/services/tree-views/TreeViewProvider.ts
vscode/src/services/tree-views/support-items.ts
vscode/src/services/tree-views/treeViewItems.ts
vscode/src/services/utils/issue-reporter.ts

CLOSE https://github.com/sourcegraph/cody/issues/3658
This pull request introduces a new command `cody.copy.version` that allows users to copy the current version of the Cody extension to their clipboard. This can be helpful when reporting issues or seeking support, as providing the extension version is often necessary for troubleshooting purposes.
Update package.json:
- Add a new command entry for cody.copy.version under the "Cody Debug" category with an appropriate icon and title.
- Add a new keybinding for the cody.copy.version command in the "cody.support.tree.view" context.
Modify main.ts:
- Import the version constant from the ./version module.
- Register the cody.copy.version command, which uses vscode.env.clipboard.writeText to copy the extension version to the clipboard.
Update …

Sidebar: add copy extension version command

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

CLOSE https://github.com/sourcegraph/cody/issues/3688
The code change in this commit adds the `sessionID` property to the sharedProperties object that is logged with the `CodyVSCodeExtension:chat-question:submitted` and `CodyVSCodeExtension:chat-question:executed` telemetry event.
The `sessionID` property is obtained from the chatModel instance, which likely represents the current chat session. By including the sessionID in the telemetry data, it becomes easier to correlate and analyze chat-related events within the same session.
Submit a message and verify in Output channel that sessionID is included as event properties.
`CodyVSCodeExtension:chat-question:submitted`:
```json
█ logEvent (telemetry disabled): CodyVSCodeExtension:chat-question:submitted  {
"details": "VSCode",
"properties": …
```

Telemetry: add sessionID to properties for Chat events

---

vscode/test/e2e/command-custom.test.ts

CONTEXT: https://sourcegraph.slack.com/archives/C05AGQYD528/p1713194760682759
Attempt to fix the flaky custom-commands e2e test. This commit adds a new interaction step to the command-custom.test.ts file in the vscode/test/e2e directory. The added line of code clicks on the index.html file in the sidebar explorer before proceeding with the existing test steps.
In current recordings for the failed test, we can see the test failed because it was clicking on the mini-map for the index.html instead of .vscody/cody.json:
By explicitly clicking on the index.html file, the test ensures that the file explorer is focused on the correct file or directory before interacting with the .vscode folder and cody.json file, so that the file will always opened in the same tab as index.html.
The e2e test for …

E2E: add click interaction for index.html in command-custom test

---

vscode/CHANGELOG.md
vscode/src/commands/services/custom-commands.ts
vscode/src/commands/services/provider.ts
vscode/test/e2e/command-custom.test.ts

CLOSE https://github.com/sourcegraph/cody/issues/3805
This pull request addresses an issue where newly added custom commands were not working when clicked in the sidebar tree view. 
The root cause of the problem was that the commands map was not being refreshed when new commands were added or existing ones were modified.
To fix this issue, the following changes were made:
vscode/src/commands/services/custom-commands.ts:
- Added a new getter method commands that returns the customCommandsMap.
- This getter provides a convenient way to access the up-to-date custom commands map from outside the CustomCommandsManager class.
vscode/src/commands/services/provider.ts:
- Replaced the getCustomCommands method to use the new commands getter from CustomCommandsManager.
- Added an event listener to …

Custom Command: Fix new custom command not working on sidebar click

---

.github/workflows/lints.yml
lints/git-diff-ts-ranges.ts
lints/safe-prompts.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

As the title suggest, we only want to emit linter errors when new call sites were added. The previous rule would fire too often.
- Add a change to the bottom of `vscode/src/chat/chat-view/SimpleChatPanelProvider.ts` that adds an `unsafe_` API call
- Run `pnpm ts-node lints/safe-prompts.ts `pnpm ts-node lints/git-diff-ts-ranges.ts`
- Observe that only an error for this change is emitted.

PromptString linter: Only error when the reported violation is within one of the changed range

---

vscode/CHANGELOG.md
vscode/webviews/chat/cells/messageCell/MessageCell.module.css
vscode/webviews/chat/cells/messageCell/MessageCell.tsx

CLOSE https://github.com/sourcegraph/cody/issues/3815
This commit adds a new CSS class `.human-content` that applies `white-space: pre-wrap` styling specifically to human messages in the chat transcript. 
It also updates the `MessageCell` component to conditionally apply this new class to message cells if `message.speaker === 'human'`.
This enables messages submitted by users to render with correct spacing as a temporary workaround until the new design has been fully implemented.

Chat: render spacings for human messages

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

We want to be able to filter TTFT by model ID
- I tested that you can still send chat messages but the `console.log` trace exporter won't log subtraces yet. However the change is trivial

Log chat properties with first-token span

---

vscode/webviews/Components/ChatModelIcon.tsx
vscode/webviews/chat/cells/messageCell/SpeakerIcon.tsx

Adds a hover tooltip to the LLM model avatars in the chat transcript, so you can see what the icon means. Ideally we include the model name in the cell text, not just the provider avatar, but this is a small improvement in the meantime.
- Tested in webview

Add a hover title to the LLM chat avatars

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
vscode/CHANGELOG.md
vscode/src/chat/chat-view/SidebarViewController.ts
vscode/src/main.ts
vscode/src/services/AuthProvider.ts

Closes https://github.com/sourcegraph/cody-issues/issues/19
This PR adds a new analytics event that is fired the first time a user authenticates. We use local storage to make sure this is only fired ones. 
For existing users, we will check if the extension is ever authenticated when it first starts up. If someone has Cody installed and was authenticated in the past, they would be suspect to getting a first-ever event logged. However I think this is fine, we don't know wether they were authenticated before. 
- When loading up an instance where you're not authenticated at
```
█ logEvent (telemetry disabled): CodyVSCodeExtension:auth:simplifiedSignInGitHubClick 
█ telemetry-v2: recordEvent: cody.auth.login/firstEver      <<<<<<<<<<<<<<<<<<<<<<<
█ Cody:publishConfig: configForWebview 
█ …
```

Log first ever authentication event

---

vscode/webviews/chat/cells/contextCell/ContextCell.module.css
vscode/webviews/chat/cells/contextCell/ContextCell.tsx
vscode/webviews/promptEditor/nodes/ContextItemMentionNode.module.css
vscode/webviews/promptEditor/nodes/ContextItemMentionNode.ts

Some VS Code color themes made the context links and at-mentions in chat unreadable. This was because the styling assumed that the text link foreground had contrast with the list active selection background, which is an incorrect assumption in general. Now the styles are formally shared between these 2 components and use CSS theme variables that can be assumed to have appropriate contrast.
Fix https://github.com/sourcegraph/cody/issues/3816
TBH this regressed the consistency between the at-mentions in the editor and the list somewhat, but they weren't consistent before and we'll need to clean up the button styles or something else. This is unobjectionable and fixes the obvious bug, so I think it's worth merging for the release.
CI. Also view chat and switch themes.

improve contrast of context links and at-mention colors in various VS Code themes

---

vscode/CHANGELOG.md
vscode/src/editor/utils/editor-context.test.ts
vscode/src/editor/utils/editor-context.ts
vscode/test/e2e/chat-atFile.test.ts
vscode/test/e2e/chat-edits.test.ts

When @-mentioning a file without specifying the range, the file will be displayed without line numbers, and without the number, the Chat UI will not be able to display the correct number for total lines read:
"5 lines from 2 files" is not correct here, because the line count from the ignore file is not included here:
This PR fixed the aforementioned issue with the following changes:
- Destructure commonly used properties like `content` and `size` upfront
- Remove separate `content` and `size` assignments in favor of single conditional block
- Introduce `getRangeByContentLineCount` to infer range based on content lines
Updated all unit tests and e2e tests.

Chat: display line range for @-mentions

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
lib/shared/src/models/dotcom.ts
vscode/CHANGELOG.md
vscode/package.json

VS Code: Release 1.14.0 - Stable Release.
Blog post: https://github.com/sourcegraph/about/pull/6882

VS Code: Release 1.14.0

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/EditCommands_CodeParams.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ParamsParams.kt
agent/src/agent.ts
vscode/src/jsonrpc/agent-protocol.ts

The introduction of PromptString did not catch this case where an Agent command was converted into the arguments for Edit. I added a cast to `ExecuteEditArguments` now so that the next time this will yell.
`command.executeCommand()` being untyped is not great 😞 
- CI; Will ask @sourcegraph/jetbrains-plugin folks

Convert editCommands/code to a proper PromptString

---

vscode/CHANGELOG.md
vscode/test/e2e/chat-input.test.ts
vscode/test/fixtures/mock-server.ts
vscode/webviews/chat/ChatMessageContent.module.css
vscode/webviews/chat/cells/Cell.module.css
vscode/webviews/chat/cells/messageCell/MessageCell.module.css
vscode/webviews/chat/cells/messageCell/MessageCell.tsx

CLOSE https://github.com/sourcegraph/cody/issues/3863
This PR improves text wrapping and scrolling behavior in the chat views:
- Enables text wrapping in chat message content by adding 'text-wrap: wrap' CSS rule. This allows long messages to wrap instead of overflowing.
- Adds 'overflow: scroll' to `<pre>` tags in message content to enable scrolling for code blocks. Previously code blocks could overflow container. 
- Sets 'overflow: auto' on chat cell content containers. This enables scrolling when content overflows cell.
- Moves 'white-space: pre-wrap' to human message containers for nicer text wrapping of human messages.
These changes improve the readability and scrolling behavior of long chat messages and code blocks. Text will wrap instead of overflowing, and scrolling will be enabled …

Fix: text-wrapping and code scrolling in chat views

---

lib/shared/src/cody-ignore/context-filters-provider.test.ts
lib/shared/src/cody-ignore/context-filters-provider.ts
lib/shared/src/index.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
vscode/src/main.ts

- Part of https://github.com/sourcegraph/cody/pull/3771
- Rebased on top of https://github.com/sourcegraph/cody/pull/3856
- Updates the Cody Ignore context filter GraphQL query to be compatible with the latest backend changes https://github.com/sourcegraph/sourcegraph/pull/61101.
- Initializes `contextFiltersProvider` on the extension activation
- Re-initializes `contextFiltersProvider` on configuration change
- Uses the "includes everything" policy for Sourcegraph instances without specified context filters or for instances where this API is not yet supported.
CI and unit tests.

VS Code: context filters graphql API update

---

vscode/package.json

Some of the Fireworks models required for this are no longer deployed:

Remove startcoder2-hybrid from settings

---

agent/src/AgentWorkspaceConfiguration.ts
lib/shared/src/configuration.ts
lib/shared/src/sourcegraph-api/completions/client.ts
lib/shared/src/sourcegraph-api/completions/nodeClient.ts
vscode/CHANGELOG.md
vscode/CONTRIBUTING.md
vscode/package.json
vscode/src/chat/ContextProvider.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/protocol.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/external-services.ts
vscode/src/local-context/symf.test.ts
vscode/src/log.ts
vscode/src/main.ts
vscode/src/services/StatusBar.ts
vscode/src/services/utils/export-logs.ts
vscode/src/testutils/mocks.ts
vscode/test/fixtures/.vscode/settings.json
vscode/webviews/App.story.tsx
vscode/webviews/App.tsx

We changed the default to `true` a while back but it's still possible to have manual overwrites. Let's remove the flag.
- CI

Remove debug.enable flag

---

.vscode/settings.json
agent/package.json
agent/src/cli/root.ts
agent/src/cli/server.ts
lib/shared/src/logger.ts
pnpm-lock.yaml
vscode/src/jsonrpc/jsonrpc.ts

Previously, it was only possible to do RPC with the Cody Agent via stdin/stdout, which required the client to run on the same computer as the Cody Agent. This PR adds a new `server` subcommand that starts a server that allows clients to connect with the Cody Agent via web sockets from another computer.
One example use-case for this feature is to implement a browser client to interact with Cody Chat. By using websockets, the browser client can interact with Cody without installing any custom dependencies. To improve the ergonomics of interacting with Cody, we can extend our current Kotlin bindings generation tool to generate bindings for other languages like TypeScript and Go.
Below is a demo of a SvelteKit static page that establishes a websocket connection to expose a basic chat …

Agent: add `server` subcommand to expose agent protocol via websockets

---

package.json
pnpm-lock.yaml
vscode/scripts/github-changelog.ts
vscode/src/context/context-filters-provider.ts

The vitest VS Code extension was no longer working because of an outdated vitest version. Upgrading it seemed to work without any issues.
Unfortunately I can't say this about upgrading biome so I've reverted to only vite, vitest, and some type helpers...
- CI passes
- Vitest vscode works again:

Upgrade vitest, vite, and some types

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/rateLimitedClient_2043004676/recording.har.yaml
agent/src/index.test.ts
lib/shared/src/models/dotcom.ts
vscode/test/fixtures/mock-server.ts

The order we list our models in dotcom.ts is the order it is shown in. I imagine in future we likely want to order these such that LLMs we want to guide users to use are higher up. For now I just moved the default LLM to the top.
Alternatively we should consider making the selected LLM at the top of the dropdown list?
Test Plan: CI
Fixes https://github.com/sourcegraph/cody/issues/3820

models: show default LLM first in dropdown

---

vscode/CHANGELOG.md
vscode/src/edit/manager.ts
vscode/src/edit/provider.ts
vscode/src/non-stop/FixupController.ts

https://github.com/sourcegraph/cody/assets/9516420/3707835b-90e5-47be-9053-f3650cd038df
Bug: Edits were not correctly re-spinning, as the LLM request wasn't being restarted
Solution:
- When a respin is required:
- Access the `EditProvider` for the task
- Abort any existing request
- Re-trigger `startEdit` using the same task parameters
1. Make an edit
2. Immediately make changes within the range of that edit, that would likely conflict with the LLM's response
3. Expect that the Edit respins and resolves the issue

Edit: Fix respins not restarting a edit

---

lib/shared/src/editor/index.ts
lib/shared/src/test/mocks.ts
vscode/src/chat/chat-view/context.ts
vscode/src/editor/utils/editor-context.ts
vscode/src/editor/vscode-editor.ts

`Editor.getTextEditorContentForFile` now returns `Promise<string>` not `Promise<string | undefined>`. The only case where the impl returned an `undefined` content value was if the URI argument was undefined, which was impossible per the type signature anyway and does not make sense.
Now, reading a file either returns a string or throws an exception, which makes sense. It does not make sense for it to ever return `undefined`.
CI

remove misleading `| undefined` return for editor file content

---

lib/shared/src/index.ts
vscode/src/editor/utils/editor-context.test.ts
vscode/src/editor/utils/editor-context.ts
vscode/test/e2e/chat-atFile.test.ts
vscode/test/e2e/chat-edits.test.ts
vscode/test/e2e/command-core.test.ts
vscode/test/e2e/command-custom.test.ts
vscode/test/e2e/common.ts
vscode/test/e2e/local-embeddings.test.ts
vscode/webviews/chat/cells/contextCell/ContextCell.tsx

Previously the chat context cell would display `Context: 93 lines from 7 files`. The number of lines is not necessary, and now it just shows the file count, as in `Context: 7 files`.
The total line count is an unnecessary detail even for today's context sources. It is not clear what users should do with that information. As context sources start to get less about "chunks of files", it becomes even less relevant.
CI

do not show the context file line count in chat context

---

lib/shared/src/cody-ignore/context-filters-provider.ts

- Follow up on the comment https://github.com/sourcegraph/cody/pull/3771#discussion_r1568301215
- Logs non-file URIs via `logDebug`
- Part of https://github.com/sourcegraph/cody/issues/3641
CI

VS Code: add non-file URI logs

---

lib/shared/src/token/counter.ts
vscode/src/chat/utils.ts

CONTEXT: https://sourcegraph.slack.com/archives/C05AGQYD528/p1713491201142189
Follow-up on https://github.com/sourcegraph/cody/pull/3742
In https://github.com/sourcegraph/cody/pull/3742 we have replaced the old token-counting logic with js-tiktoken using `'cl100k_base'` encoding. This PR contains some minor clean-up works as a follow-up to that. 
- The `tokenize` method (which was a typo) has been renamed to `tokenizer`.
- References to `tokenize` have been updated to use the `tokenizer` instance property instead.
- Removed unused `countBytesInChatMessages` and `getContextWindowLimitInBytes` utility functions
Just removed unused functions and fixed a typo. Everything should work as before with green CI.

Chat: minor clean up

---

lib/shared/src/cody-ignore/context-filters-provider.test.ts
lib/shared/src/cody-ignore/context-filters-provider.ts
lib/shared/src/prompt/prompt-string.test.ts
lib/shared/src/prompt/prompt-string.ts

`ContextFiltersProvider.prototype.isUriAllowed()` returning a Promise makes an argument for inverting the logic. Consider this code:
```ts
if (!contextFiltersProvider.isUriAllowed(foo)) {
return null
}
```
Which is what most of the call sites of this function will look like. The fact that Promise is a truthy value will make it very easy for us to forget to await the result. In the past we had lint rules which notified us about issues like this but since the move to biome we don’t have access to type-aware linter rules. To avoid issues, I suggest we invert the logic here instead:
```ts
if (contextFiltersProvider.isUriBlocked(foo)) { // <- Will always be true since a Promise instance is truthy. 
return null
}
```
- Updated unit tests

Invert ContextFiltersProvider.prototype.isUriAllowed logic

---

.vscode/launch.json
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/Constants.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ContextProvider.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/EmbeddingsProvider.kt
lib/shared/src/codebase-context/context-status.ts
lib/shared/src/configuration.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/extension.common.ts
vscode/src/extension.node.ts
vscode/src/external-services.ts
vscode/src/local-context/enhanced-context-status.test.ts
vscode/src/local-context/local-embeddings.ts
vscode/src/testutils/mocks.ts
vscode/test/e2e/local-embeddings.test.ts
vscode/webviews/Components/EnhancedContextSettings.story.tsx
vscode/webviews/Components/EnhancedContextSettings.tsx

Add's support for Sourcegraph Embeddings API, changing:
- model identifier and vector dimension (passed to BFG aka Cody Engine)
- storage location for indices (to allow switching from OpenAI to Sourcegraph API without data loss / conflicts)
- test used to communicate how we process user code
[Loom](https://www.loom.com/share/38a46f95a2414726816de62740c90760)
Potentially TODO (separate PR):
- can we "assume consent" and re-embed automatically if user has used OpenAI (without accepting again)?
- build BFG from main (`cd $BFG_REPO && cd crated/bfg && cargo build --release`)
- configure your VSCode to use locally-built BFG (add `  "cody.experimental.cody-engine.path": "$BFG_REPO/target/release/bfg"` to settings.json)
- enable the Feature …

Add support for using Sourcegraph Embeddings API

---

vscode/src/completions/context/context-mixer.test.ts
vscode/src/completions/context/context-mixer.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/inline-completion-item-provider.ts

Part of https://github.com/sourcegraph/cody/issues/3642
Part of https://github.com/sourcegraph/cody/issues/3604
This PR implements context filter honoring for Autocomplete. There are two types of sources we filter:
- The current file context (appended as prefix/suffix) to the prompt: In files that are ignored, autocomplete will now no-op. **Question:** should this print a log somewhere that a user can see it so it's clear why Autocomplete does not work? I am worried that anything we add might be annoying, though.
- Retrieved file context: we now filter all retrieved context before ranking. We can move some of the checks closer into the retrievers but since all of the retrievers are local and fast, this is not a high prioroity
- Added tests

Autocomplete: Implement context filter

---

vscode/src/search/SearchViewProvider.ts

It should show the basename of the dir. Fixes a bug where it is blank and just says "Updating Cody search index for" in VS Code workspaces with a single root. The problem is that `displayPath` truncates the workspace root folder prefix.
CI

fix "Updating Cody search index for" message

---

vscode/webviews/promptEditor/plugins/atMentions/atMentions.tsx

- Fixes a React warning (in the devtools console) `Warning: Do not call Hooks inside useEffect(...), useMemo(...), or other built-in Hooks.` because `useCurrentModel()` was being called within a `useMemo()` hook. This can cause unexpected behavior in React. It is also desirable for the `isTooLarge` property of each option to be recomputed when the model changes because different models have different context window sizes.
- Avoids registering another editor mutation listener each time the component is rendered by wrapping the registration in a `useEffect` hook. I don't *know* if this causes any problems, but it could make things slow or result in weird behavior.
CI, and try adding mentions in the storybook

fix nested react hook usage and only have 1 editor mutation listener

---

lib/shared/src/chat/transcript/display-text.ts
lib/shared/src/codebase-context/messages.ts
lib/shared/src/index.ts
lib/shared/src/mentions/api.ts
lib/shared/src/mentions/providers/urlMentions.ts
lib/shared/src/mentions/query.test.ts
lib/shared/src/mentions/query.ts
lib/shared/src/mentions/urlContextItems.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/context/chatContext.ts
vscode/src/edit/input/get-input.ts
vscode/src/edit/prompt/context.ts
vscode/src/editor/utils/editor-context.test.ts
vscode/src/editor/utils/editor-context.ts
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.tsx
vscode/webviews/promptEditor/plugins/atMentions/fixtures.ts

A ContextMentionProvider can provide context items that the user can `@`-mention in chat. It exposes an API with:
- triggerPrefixes: eg `npm:` to show a list of possible npm packages to mention when the user types `@npm:`
- queryContextItems: return a list of possible npm packages when the user types in `@npm:left-p` into the chat
- resolveContextItem (optional): enrich the context item with more content, used right before the context is sent to the LLM and only run on items that the user explicitly mentioned (so it can be slower)
The experimental URL mention feature was also ported to use this new API. It was designed to support more mentionable context sources, such as https://github.com/sourcegraph/cody/pull/3866 (@-mentionable packages like `@npm:left-pad`).
**Status: experimental.** …

introduce ContextMentionProvider API for mentionable context sources

---

vscode/src/testutils/uri.ts

The [VS Code URI class](https://sourcegraph.com/github.com/microsoft/vscode/-/blob/src/vs/base/common/uri.ts) has public properties not getters for `scheme`, `authority`, `path`, `query`, and `fragment`. This means that those properties are serialized as JSON object fields when the URI instance is passed via MessagePort. This change makes our shim behave similarly so that it can be transferred via MessagePort (such as to agent in a web worker).
CI

make our shim URI more like VS Code's URI

---

lib/shared/src/cody-ignore/context-filters-provider.test.ts
lib/shared/src/cody-ignore/context-filters-provider.ts
vscode/src/extension.node.ts
vscode/src/main.ts
vscode/src/repository/git-extension-api.ts
vscode/src/repository/repo-name-getter.node.test.ts
vscode/src/repository/repo-name-getter.node.ts
vscode/src/repository/repo-name-resolver.test.ts
vscode/src/repository/repo-name-resolver.ts

- Uses all remote URLs available to resolve repo names for Cody Ignore checks
- Built on top of https://github.com/sourcegraph/cody/pull/3870
- Part of https://github.com/sourcegraph/cody/issues/3641
CI and updated unit tests.

Cody Ignore: support multiple remote URLs

---

lib/shared/src/cody-ignore/context-filters-provider.test.ts
vscode/src/repository/repo-name-resolver.test.ts
vscode/src/repository/repo-name-resolver.ts

This PR fixes a few things regarding the repo name resolver:
- It will now fall back to the previous URL parsing if the repo is not known in the Sourcegraph instance (for backward compat): https://github.com/sourcegraph/cody/pull/3870/files#diff-282c58c06ab5f90a1cda9f3adae0bd0541bf9a3c4f681d0399037a568cc8c605L61-R64
- I remove the nullability since we moved this to an array (an empty array is the same as null now)
- Fixed some type issues that creeped into `main`
- Fixed an issue where the upstream request was not sent that I discovered when adding unit tests 😬 
Added a unit test

Fix repo name resolver

---

agent/scripts/test-agent-binary.ts
agent/src/TestClient.ts
agent/src/agent.ts
agent/src/cli/jsonrpc.ts
agent/src/cli/server.ts
agent/src/index.test.ts
cli/src/agentClient.ts
package.json
pnpm-lock.yaml
vscode/src/graph/bfg/spawn-bfg.ts
vscode/src/jsonrpc/jsonrpc.ts

The [vscode-jsonrpc](https://www.npmjs.com/package/vscode-jsonrpc) library is from the VS Code team and is used by many VS Code extensions and language servers to implement the JSON-RPC 2.0 protocol. It is well tested, heavily used, actively maintained, and supports both Node and Web platforms.
Using this library means we can remove our own implementation of the protocol, which is (a) less code to maintain, (b) does not support the browser, and (c) is not spec-compliant (for example, it supports string values as request parameters, which are disallowed by the [JSON-RPC 2.0 spec](https://www.jsonrpc.org/specification#request_object)).
1. CI
2. Manually ran BFG (cody-engine) tests and confirm that `embeddings/set-token` works in the output channel
3. Manually tested with the CLI
4. Test …

use vscode-jsonrpc library for JSON-RPC implementation

---

vscode/CHANGELOG.md
vscode/doc/ollama.md
vscode/src/configuration.ts
vscode/src/services/StatusBar.ts
vscode/src/testutils/mocks.ts
vscode/webviews/Components/ChatModelDropdownMenu.module.css
vscode/webviews/Components/ChatModelDropdownMenu.tsx

CONTEXT: https://sourcegraph.slack.com/archives/C05AGQYD528/p1713891011703859
This pull request updates the Cody extension for VS Code to enable the experimental Ollama Chat feature by default. 
- Configuration Update: In the configuration.ts file, the experimentalOllamaChat setting is changed from false to true by default. This setting controls whether the Ollama Chat feature is enabled or not.
- Status Bar Update: In the StatusBar.ts file, a new feature toggle is added for the "Ollama Chat" feature. This toggle appears in the Cody extension's status bar and allows users to enable or disable the Ollama Chat feature from the UI.
- Dropdown menu Update: Display Ollama models in the dropdown menu with `experimental` badge.
With these changes, users will now have the …

Enable Ollama Chat by default

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/Ignore_TestParams.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/Ignore_TestResult.kt

Follow up to 3a50f57ca0a249c05851cc19ec891f49885dff86, add the generated stubs for the renamed `ignore/test` method. Forgot to add these.
`./agent/scripts/generate-agent-kotlin-bindings.sh` produces an empty diff.

Add missing generated Kotlin stubs for `ignore/test`

---

vscode/.storybook/main.ts
vscode/.storybook/re2-wasm-shim.js

Fixes issue when loading all storybooks:
```
abort(sync fetching of the wasm failed: you can preload it to Module['wasmBinary'] manually, or emcc.py will do that for you when generating HTML (but not JS)) at Error
```
There's almost certainly a better way to do this, but this unblocks storybooks for now.
CI

shim re2-wasm to fix storybook

---

.github/workflows/ci.yml
agent/src/cli/evaluate-autocomplete/AutocompleteMatcher.test.ts
agent/src/index.test.ts
agent/src/isNode16.ts
package.json

My recommendation is that we should stop testing and supporting Node 16, and instead bump this to Node 18.
We had been supporting Node 16 because the July 2023 VS Code release shipped with a version of Electron that used Node 16. That is now well in the past, and:
- VS Code's Aug 2023 release shipped with Node 18 (up from Node 16): https://code.visualstudio.com/updates/v1_82#_engineering
- Node 16 was end-of-life'd on 2023-09-11: https://nodejs.org/en/blog/announcements/nodejs16-eol
- For JetBrains, we use the agent binary that bundles Node (20), so we don't depend on Node 16 even if that's what is installed on the system.
An alternative is to start testing Node 16, 18, AND 20 (ie add tests for Node 18 since it's the version in use by VS Code). This would be safer in case any customers …

test and support node 18 (no longer node 16)

---

lib/shared/src/cody-ignore/context-filters-provider.test.ts
lib/shared/src/cody-ignore/context-filters-provider.ts

Remote context has http/s URIs, and we were conservatively blocking these because they don't pass the *file* filter. But remote context is filtered by the getCodyContext backend.
For now, unblocking all context items with http/s URIs.
Added a unit test; CI
Fixes #3928

Cody Ignore: Do not block context with http/s URIs

---

lib/shared/src/cody-ignore/context-filters-provider.test.ts

These are only needed in RegExp literals.
CI

remove needless escapes of `/` in regexp patterns

---

lib/shared/package.json
lib/shared/src/cody-ignore/context-filters-provider.test.ts
lib/shared/src/cody-ignore/context-filters-provider.ts
pnpm-lock.yaml
vscode/.storybook/main.ts
vscode/.storybook/re2-wasm-shim.js
vscode/package.json
vscode/scripts/download-wasm-modules.ts

[RE2JS](https://github.com/le0pard/re2js) is a pure JavaScript implementation of RE2. This is more portable than [re2-wasm](https://github.com/google/re2-wasm), which [does not support usage in the browser](https://github.com/google/re2-wasm/issues/15), which breaks storybooks (although there is an easy hack workarond) and prevents Cody Web from reusing this code. It is possible to make re2-wasm usable in the browser, but it would require forking the upstream, which does not seem worth the effort unless we find the performance of RE2JS to be unacceptable.
RE2JS does not support the `u` flag for RE2, which [enables various Unicode-related features](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode), so I added a test to confirm that this is its …

use pure-JS RE2 impl instead of re2-wasm

---

.github/workflows/agent-bindings.yml
.github/workflows/scip-typescript.yml
.tool-versions
package.json
pnpm-lock.yaml

upgrade to pnpm 9.0.5

---

vscode/src/local-context/local-embeddings.ts

Trace embedding search errors - currently, we only capture the number of results.
- local testing

Trace local embedding search error

---

.vscode/settings.json
lib/shared/src/codebase-context/messages.ts
lib/shared/src/index.ts
lib/shared/src/mentions/api.ts
lib/shared/src/mentions/providers/packageMentions.ts
lib/shared/src/mentions/providers/urlMentions.ts
lib/shared/src/mentions/query.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/context/chatContext.ts
vscode/src/chat/context/constants.ts
vscode/src/edit/input/get-input.ts
vscode/src/edit/input/utils.ts
vscode/src/edit/prompt/context.ts
vscode/src/editor/utils/editor-context.test.ts
vscode/src/editor/utils/editor-context.ts
vscode/webviews/promptEditor/nodes/ContextItemMentionNode.ts
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.tsx

Demo: https://www.loom.com/share/342e1903f93e4ff28f582c5d310ef5ff?sid=f8b66a30-b230-4403-8869-cb3e748cdbb5
We have 370K+ packages from various ecosystems (npm, go, rust, ruby, python, java) already indexed on [sourcegraph.com](http://sourcegraph.com/). It is already enterprise-ready as well.
This new feature will allow users to include specific packages into the context using the syntax `@<ecosystem>:<package_name>`, for example: `@npm:tailwindcss`.
Cody will make a Remote Search for the tailwind package repo against the user's query and include the related code snippets in the context.
TODO

Implement @-mention package context

---

lib/shared/src/prompt/prompt-string.test.ts
lib/shared/src/prompt/prompt-string.ts

Add logging around blocked references and simplify the message since it might leak to the user while we find all cases where context is pulled in from.
- CI

PromptString: Log blocked references

---

lib/shared/src/cody-ignore/context-filters-provider.test.ts
lib/shared/src/cody-ignore/context-filters-provider.ts
lib/shared/src/prompt/prompt-string.test.ts
lib/shared/src/prompt/prompt-string.ts
vscode/src/completions/context/context-mixer.test.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/supercompletions/recent-edits/recent-edits-retriever.test.ts

- Changes the return type for blocked references to a string giving a reason. We type it so that the string is always non-empty so we can still keep using `if(..)` checks easily.
- Add an API to expose the current filters as a debug object that can be used in our last-line-of-defence logging

ContextFilters: Return block reason and expose current state for logging purposes

---

vscode/test/e2e/chat-input.test.ts
vscode/test/e2e/helpers.ts
vscode/webviews/Components/ChatModelDropdownMenu.tsx

Suggested by @toolmantim 
Remove the `capitalize` function call when rendering the title for chat model options and the selected model in the dropdown menu. This change  allows the original casing of the model titles to be displayed as-is.
- Remove the `capitalize` function call when rendering `option.title` in the dropdown menu options.
- Remove the `capitalize` function call when rendering `currentModel.title` in the selected value of the dropdown.
Verify third-party modes (e.g. ollama) from the dropdown list are not capitalized

Chat: remove capitalization from model names

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
lib/shared/src/index.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/completions/nodeClient.ts
vscode/src/extension.node.ts
vscode/src/fetch.node.ts
vscode/src/local-context/local-embeddings.ts
vscode/src/local-context/symf.test.ts
vscode/src/models/utils.ts
vscode/src/prompt-builder/index.ts
vscode/src/repository/repo-name-getter.node.ts
vscode/webviews/promptEditor/plugins/atMentions/atMentions.tsx

We noticed that the `ContextFilterProvider` was bundled twice in the VS Code production builds. To fix this, we now move all `@sourcegraph/cody-shared` requires to use the main bundle instead of requiring files directly.
Add a console log to the context provider and see that it's only bundled once:
```
α cody/vscode 🐙(ps/remove-double-bundling-of-some-lib-shared-files)✗
cat dist/extension.node.js | grep "THIS SHOULD ONLY EVER BE LOGGED ONCE"
console.log("THIS SHOULD ONLY EVER BE LOGGED ONCE");
```

Remove double-bundling of some lib/shared files

---

lib/shared/src/cody-ignore/ignore-helper.ts
vscode/webviews/promptEditor/nodes/ContextItemMentionNode.ts
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.tsx

This PR introduces three changes:
1. **Decode URI components for display in URL context mentions**
- URLs mentioned using the '@' syntax were displaying encoded characters like '%3D' instead of '='.
- This commit fixes the issue by decoding the URI components when displaying file paths and directories for URL context mention items in `ContextItemMentionNode.ts` and `OptionsList.tsx`.
- This ensures that users see properly decoded URLs when using the '@' mention feature to reference URLs in their prompts.
2. **Skip ignoring HTTP URIs**
- The `IgnoreHelper` class now checks if the URI scheme is 'http' and returns false (i.e., does not ignore the URI) in that case.
- This change allows the code to process HTTP URIs, which were previously being ignored along with other non-file URIs.
- The …

fix: Handle HTTP URIs and decode URI components in URL context mentions

---

vscode/src/local-context/local-embeddings.ts

Record the embedding provider on search spans so we can correlate errors/latency with a specific provider being used.
- tracing only

Record embedding provider on embedding span

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/agent.ts
agent/src/index.test.ts
lib/shared/src/cody-ignore/context-filters-provider.ts

- Context filters should fire the changed event *after* parsing the filters, so clients which query the filters can see updated values.
- Remove the hook for applying overrides for dotcom users at the agent level; the overrides need to be at the extension level. For now we simply won't integrate file-based Cody Ignore here.
- Remove the VITEST guard. The purpose of this hook is largely for testing IntelliJ, which is not VITEST.
- For now, disables Agent file-based Cody Ignore tests. File-based Cody Ignore should be integrated at the extension level, not the Agent "container" level. Then these tests can come back.
Part of #3641 
Manually tested with a sourcegraph/jetbrains#1396
CI

Cody Ignore: Tidy up context filter overrides

---

lib/shared/src/mentions/api.ts
lib/shared/src/mentions/providers/sourcegraphSearch.ts

Note: this logic is currently hidden behind the noodle feature flag. Additionally instead of implementing client logic in our graphql backend, it keeps all related logic inside one file to contain the blast radius. Please give feedback if this is a reasonable idea, or if I should just implement things inside of client.ts. Because I didn't do the latter I had to copy paste some utility types/functions.
When typing the prefix "@src:" we will provide a context item which says it will search against your sourcegraph endpoint. This is presented as a URL to the search. When clicking resolving the item it will convert each search result chunk into a context item.
This is currently not working due to some recent restrictions introduced on context sources. Note that the URL mention provider also …

noodle: introduce sourcegraph literal search mentions provider

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
lib/shared/src/index.ts
lib/shared/src/models/dotcom.ts
lib/shared/src/models/index.test.ts
lib/shared/src/token/constants.ts
lib/shared/src/token/counter.test.ts
vscode/CHANGELOG.md
vscode/src/editor/utils/editor-context.test.ts
vscode/src/models/utils.ts
vscode/webviews/App.story.tsx
vscode/webviews/Components/ChatModelDropdownMenu.story.tsx
vscode/webviews/storybook/VSCodeStoryDecorator.tsx

CLOSE https://github.com/sourcegraph/cody-issues/issues/27
> @chillatom And for the removal that limits to Dotcom users, we could release that to stable in the next release (5/1)
As we have rolled out the expanded context window to 100% of our DotCom users, and implement a more stable tokenizer on both client and cody gateway https://github.com/sourcegraph/sourcegraph/issues/62057 , we are now expected to roll out the expanded windows to PLG users without the feature flag.
This PR aims to remove the feature flag we used for A/B testing the expanded context window for DotCom users using Claude 3 Opus and Sonnet models. Changes include:
- Update token consts:
- EXPERIMENTAL_CHAT_INPUT_TOKEN_BUDGET to CLAUDE3_CHAT_INPUT_TOKEN_BUDGET
- EXPERIMENTAL_USER_CONTEXT_TOKEN_BUDGET to …

Cody PLG: increase token budget for Claude 3 models w/o feature flag

---

.github/workflows/agent-bindings.yml
.github/workflows/scip-typescript.yml
.tool-versions
package.json
pnpm-lock.yaml

This reverts commit b1c91e37916dab9f5bf6d8807520cba8b2627e84.
Breaks JetBrains extension CI because the jetbrains repo requires both cody and sourcegraph/sourcegraph, and the latter can't upgrade to pnpm 9 because it is not yet supported by https://github.com/aspect-build/rules_js.
CI

Revert "upgrade to pnpm 9.0.5 (#3904)"

---

vscode/CHANGELOG.md
vscode/src/commands/menus/command-builder.ts
vscode/src/commands/menus/items/menu.ts
vscode/test/e2e/command-custom.test.ts

This pull request updates the context options available when creating custom commands using the quick pick menu and fixes an issue with the "selection" option. 
- Fix "selection" Option Behavior: Previously, when creating a custom command, the "selection" option was not being toggled correctly. If an option was selected in the quick pick menu, it would not set the "selection" property to false but rather leave it as undefined. This pull request addresses this issue by explicitly setting `newPrompt.context.selection` to false when initializing the context object.
- Add 'currentFile' Option: A new option 'currentFile' has been added to the context options. This option allows users to include the full content of the currently open file in the active editor when creating …

Custom Command: update context options

---

lib/shared/src/mentions/providers/sourcegraphSearch.ts

This is so when you click through it uses the same interpretation of the query string we use against the backend.
Additionally instead of using the title of the item, we extract out the query from the URI. This is a small change which makes this more useful as a generic extractor of search results from URLs.
Test Plan: tested manually to ensure context was still returned. Then clicked through on the @ mentioned link. Right now there is another bug which double quotes the URL when clicking through so not fully functional.

noodle: include patternType in search URL

---

lib/shared/src/mentions/providers/sourcegraphSearch.ts

This is inline with the examples Quinn was using.
Test Plan: tested mentioning search results with both `@?` and `@src:` as a trigger prefix.

noodle: sourcegraph search also uses ? as a trigger prefix

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/chat-helpers.test.ts
vscode/src/chat/chat-view/chat-helpers.ts
vscode/src/services/HistoryChat.ts

Small fix: Add title trimming and handle empty text
This commit updates the getChatPanelTitle function to use the trimmed title when generating the chat panel title to address an issue where chat title is set to "New Chat" when the last chat question starts with a new line:
Changes:
- Added a new test case to ensure that the getChatPanelTitle function trims the title and handles empty text.
Updated the getChatPanelTitle function to use the trimmed title when generating the chat panel title.
- start debug mode from this branch
- start a new chat
- send a question to cody and start the question with a new line
The chat title is set to "New Chat"
The chat title used the trimmed value:

Chat: Fix chat title that starts with new line

---

vscode/src/commands/execute/usage-examples.ts
vscode/webviews/Components/FileLink.tsx

CONTEXT: https://sourcegraph.slack.com/archives/C05AGQYD528/p1714489870131939
RE: https://github.com/sourcegraph/cody/pull/3939
This pull request addresses an issue where the context items for usage examples have the `source` property set to `ContextItemSource.Search`, which is reserved for results returned by `symf`. However, `symf` has a different interface than results returned from `Remote Search`, which is associated with `ContextItemSource.Unified`. As a result, the results returned from `symf` are displayed as `undefined` in the UI.
Changes:
- Fixes the issue of `symf` results displaying as `undefined` in the UI for usage examples
- Unifies the source for usage examples to `ContextItemSource.Unified`, ensuring correct display
- Updates the `source` property of `ContextItem` for …

fix: update ContextItemSource for usage examples

---

vscode/webviews/chat/Transcript.test.tsx

Fixes the `Warning: <VSCodeButton /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.` message.
CI

fix 'incorrect casing' warning in tests for Transcript

---

vscode/webviews/promptEditor/nodes/ContextItemMentionNode.ts

For `ContextItem`s with a `title`, the title is used as the text label for the @-mention in the editor. Previously, the URI was used. This change results in a nicer display of context items that have titles.
CI

use title (if present) as label for @-mentions

---

vscode/src/non-stop/FixupController.ts
vscode/src/services/AuthProvider.ts
vscode/src/services/SidebarCommands.ts
vscode/src/services/tree-views/support-items.ts
vscode/src/services/utils/enrollment-event.ts
vscode/src/tutorial/commands.ts
vscode/src/tutorial/content.ts
vscode/src/tutorial/index.ts

This PR:
- Improves unhappy path handling for the tutorial
- Fixes an issue where "Reset Tutorial" did not reset
- Skips formatting for Edits
- Continues tutorial even if an edit hits an error state
- Adds logic to open the tutorial automatically on the users first auth
- Gated behind a feature flag, so we can incrementally enable this for new users
- Adds telemetry
- For A/B test: enrollment events
- For tutorial progress
- On tutorial start
- On tutorial finish
- On each step finished (autocomplete, edit, fix, chat)   
Demo:
https://github.com/sourcegraph/cody/assets/9516420/fa8444d6-0a1b-40bb-9ef2-71b1db8cfaaf
**Enrolled**:
1. Force user into A/B test
2. Repeat demo from above video, on a clean instance of VS Code
3. Check correct telemetry is sent, and tutorial functions as expected. …

Interactive Tutorial: Add telemetry and improve unhappy paths

---

vscode/CHANGELOG.md
vscode/package.json

VS Code: Release 1.16.0 - Stable Release.
Blog post: https://github.com/sourcegraph/about/pull/6901

VS Code: Release 1.16.0

---

.github/workflows/ci.yml

Cheapen our GitHub actions by only running on macOS for commits to main.
No changes to branch protection rules necessary; these do not depend on macos.
CI

Cheapen CI workflow by running macOS for main commits only

---

biome.json

We found that it causes biome to crash causing issues in the VS Code extension (and likely some files won't be linted the way we expected it to because of the crash): 
```
pnpm biome
> @sourcegraph/cody@ biome /Users/philipp/dev/cody
> biome check --apply --error-on-warnings .
Biome encountered an unexpected error
This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:
Source Location: crates/biome_js_semantic/src/semantic_model/scope.rs:115:33
Thread Name: biome::worker_9
Message: no entry found for key
Biome encountered an unexpected error
This is a bug in Biome, not an error in your code, and we would appreciate it if you could …
```

Disable noRedeclare to prevent Biome crash

---

agent/src/vscode-shim.test.ts
vscode/src/testutils/mocks.ts
vscode/src/tutorial/index.ts

Fixes CODY-1326
closes https://linear.app/sourcegraph/issue/CODY-1326/noisy-ci-warning-cody-nodejswalkthroughscody-tutorialpy
VS Code will create a directory on `writeFile` if it doesn't already exist.
This updates the Agent to match that behavior
Tests pass without any errors logged in CI

Agent: Create dir if not exists when writeFile is called

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/fireworks.ts

1. This PR adds the fine-tuning code completions model for internal users. The offline evaluation is done on HumanEval dataset and the results are linked in the [RFC](https://docs.google.com/document/d/1myMceHu7x8gh0B9eb_kRE719AGqVHfZ3py9k_3luym8/edit#heading=h.trqab8y0kufp)
2. This PR particularly adds a fine-tuned version of the Mixtral model hosted by the fireworks.
3. Cody Gateway PR: https://github.com/sourcegraph/sourcegraph/pull/62300 
Manual testing
1. Added my username in the feature flag: `cody-autocomplete-finetuned-model `
2. Used debug console and cody autotrace view to check the context and completions.

adding finetuned model for code completions

---

lib/shared/src/sourcegraph-api/graphql/client.ts
vscode/CHANGELOG.md

This unbreaks 5.2.3 treating all files as ignored.
Tested manually: Log in to 5.2.3 and chat with an @-file mention. You should not get a Cody Ignore error message.

Cody Ignore: Treat unterminated JSON responses as an outdated API error message

---

lib/shared/package.json
lib/shared/src/context/openctx/api.ts
lib/shared/src/index.ts
lib/shared/src/mentions/api.ts
lib/shared/src/mentions/providers/openctxMentions.ts
pnpm-lock.yaml
vscode/src/context/openctx.ts
vscode/src/main.ts

Allows any [OpenCtx](https://openctx.org) provider to be used as a `ContextMentionProvider` to provide @-mentionable context.
For example, the [Google Docs OpenCtx provider](https://sourcegraph.com/github.com/sourcegraph/openctx@8b11111e9fccb207828b9b8ec5217a44acaa108d/-/blob/provider/google-docs/index.ts) makes it possible to @-mention Google Docs.
This lets us add more context providers without committing them to the `cody` repo. We can even add them by external HTTP URLs if there is some service that implements the HTTP OpenCtx API.
CI

add OpenCtx context mention provider

---

vscode/CHANGELOG.md
vscode/webviews/Components/modelSelectField/ModelSelectField.module.css

This was impeding readability on many color themes (esp. Monokai Pro).
Before:
After:
Test on various themes.

remove drop shadow on model selector experimental label

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
agent/recordings/graph-context-claude-3-haiku-20240307_3262616872/recording.har.yaml
agent/recordings/graph-context-claude-instant-1-2_1248528072/recording.har.yaml
agent/recordings/graph-context-starcoder-16b_352709139/recording.har.yaml
agent/recordings/graph-context-starcoder-7b_2337326201/recording.har.yaml
agent/recordings/rateLimitedClient_2043004676/recording.har.yaml
lib/shared/src/sourcegraph-api/graphql/client.ts
vscode/CHANGELOG.md
vscode/package.json

VS Code: Release 1.16.1 - Stable Release.
Patch release with fixes for the request error for Enterprise users:
Request Failed: The prompt contains a reference to a file that is not allowed by your current Cody policy.
Instance older than 5.3.3 (test instance was on v5.3.2)
DotCom:

VS Code: Release 1.16.1

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/index.test.ts
vscode/src/edit/provider.ts

We are running into issues where streamed insertions are not reliably applied to a document in JetBrains ([issue](https://github.com/sourcegraph/jetbrains/issues/1449)). This PR temporarily disables this so we can unblock progress on JetBrains whilst we figure out why this is happening
This PR:
- Disables streaming insertions into the document when running an inline edit with the `add` intent
1. Check the `add` variant of inline edit (create an edit with no selection)
2. Check edits are not streamed when running via agent

Edit: Disable streaming for 'Add' insertions in Agent

---

agent/recordings/graph-context-starcoder-16b_352709139/recording.har.yaml
agent/src/__tests__/graph-test/src/All.ts
agent/src/__tests__/graph-test/src/members-indirection.ts
agent/src/__tests__/graph-test/src/members.ts
agent/src/graph-context.test.ts
vscode/src/completions/context/retrievers/tsc/relevantTypeIdentifiers.ts

Previously, the `tsc-mixed` context didn't boost the type of the *expression* (aka. qualifier) in property accesses. For example, the property access
```ts
this.helper().CURSOR
```
has the *expression* `this.helper()`, which might have the type `interface Helper { ... }` with relevant members for autocomplete. This PR fixes the problem by effectively doing "Go to type definition" on the expression and including that definition in the context.
Fixes CODY-1331
Green CI. See newly added tests.

TSC Graph Context: handle property access

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ContextItem.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ContextItemSource.kt
vscode/package.json
vscode/src/main.ts

Closes CODY-1341
Add a command to overwrite context filters. I've for now gated it to only show up when verbose debugging is enabled however that doesn't seem to be working well 🤔 
```
{ "include": [], "exclude": [{ "repoNamePattern": "^github\\.com/sourcegraph/sourcegraph" }] }
```
https://github.com/sourcegraph/cody/assets/458591/4fda5932-a708-457f-9a55-072cd42d9b08

Add command to debug context filters

---

.github/workflows/vscode-insiders-release.yml

The `vscode-insiders-release` GitHub workflow runs E2E tests which require google-auth to send pubsub messages to our testing topic. Here we are introducing Google Authentication within the github Workflow.
Resolving:
- https://github.com/sourcegraph/cody-issues/issues/93
Test via CI and verify auth errors are gone

Add Google Authentication for `vscode-insiders-release.yml`

---

pnpm-lock.yaml
vscode/package.json
vscode/webviews/Chat.tsx
vscode/webviews/Notices/Notice.tsx
vscode/webviews/Popups/Popup.tsx
vscode/webviews/Troubleshooting/ConnectionIssuesPage.tsx
vscode/webviews/chat/ChatMessageContent.tsx
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/actions/TranscriptAction.tsx
vscode/webviews/chat/cells/Cell.tsx
vscode/webviews/chat/cells/contextCell/ContextCell.tsx
vscode/webviews/chat/cells/messageCell/MessageCell.tsx
vscode/webviews/chat/components/FeedbackButtons.tsx
vscode/webviews/components/EnhancedContextSettings.tsx
vscode/webviews/components/FileLink.tsx
vscode/webviews/components/UserAvatar.tsx
vscode/webviews/components/modelSelectField/ModelSelectField.tsx
vscode/webviews/components/platform/Button.tsx
vscode/webviews/components/platform/Popover.tsx
vscode/webviews/components/platform/SelectList.tsx
vscode/webviews/promptEditor/BaseEditor.tsx
vscode/webviews/promptEditor/PromptEditor.tsx
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.tsx
vscode/webviews/promptEditor/plugins/atMentions/atMentions.tsx
vscode/webviews/storybook/VSCodeStoryDecorator.tsx

`clsx` seems to be used in more projects now (https://npmtrends.com/classnames-vs-clsx), so standardizing on it makes it easier to copy-paste code (eg from shadcn). Also, it's shorter.
No change to any behavior.
```
fastmod -F -e ts,tsx "import classNames from 'classnames'" "import { clsx } from 'clsx'" vscode/
fastmod -F -e ts,tsx 'classNames(' 'clsx(' vscode/
```
CI

use clsx instead of classnames

---

.github/workflows/ci.yml

This test is flaky and fails often. We should fix it, but in the meantime, it slows us down on every push and PR waiting for it to finish before we can rerun other actions.
CI

only run windows e2e on main

---

.github/workflows/ci.yml

Reverts sourcegraph/cody#4052
This change was incorrect and affected unit tests not e2e tests.
CI

Revert "only run windows e2e on main"

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ProtocolTextDocument.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ProtocolTextDocumentContentChangeEvent.kt
agent/src/AgentWorkspaceDocuments.ts
agent/src/TestClient.ts
agent/src/agent.ts
agent/src/applyContentChanges.test.ts
agent/src/applyContentChanges.ts
agent/src/calculateContentChanges.test.ts
agent/src/calculateContentChanges.ts
vscode/src/jsonrpc/TextDocumentWithUri.ts
vscode/src/jsonrpc/agent-protocol.ts

Fixes CODY-1388
Fixes CODY-1292
Previously, the agent had two important limitations:
- Clients couldn't synchronize document content incrementally. This hurt performance because clients had to copy the full text contents of files on every minor change.
- The VS Code event `vscode.workspace.onDidChangeTextDocument` never populated the `contentChanges` property. We use this property in several places in the extension, including to track persistence and to support parallel inline edit.
This PR fixes both of those limitations.
See added unit tests.

Agent: add incremental document syncing and fire content changes

---

vscode/src/prompt-builder/index.ts

Closes CODY-1390
Special-case remote context here. We can usually rely on the remote context to honor any context filters but in case of client side overwrites, we want a file that is ignored on a client to always be treated as ignored.
Note that we currently do not enhanced context items that are not included at all (since those also contains items that are already part of the transcript etc), so the outcome of this PR is to simply filter these results from being part of the prompt. [Started a thread about that](https://sourcegraph.com/github.com/sourcegraph/cody@6bd1abc392814b7e973ecd23d3c278bc80005873/-/blob/vscode/src/chat/chat-view/prompt.ts?L73).

Hide ignored files that come back from the remote-search endpoint

---

vscode/CHANGELOG.md
vscode/webviews/components/platform/Popover.tsx

Attempt to fix issue reported by 2 people where the Cody webview was blank in VS Code and the following error appeared in the devtools console:
```
Uncaught DOMException: Failed to execute 'hidePopover' on 'HTMLElement': Invalid on popover elements that aren't already showing. This might have been the result of the "beforetoggle" event handler changing the state of this popover.
```
CI

swallow hidePopover exception

---

.github/workflows/vscode-insiders-release.yml
.github/workflows/vscode-stable-release.yml

This also removes the need to gcloud-auth them. Fixes failing vscode-insiders-release at https://github.com/sourcegraph/cody/actions/runs/8974364456/job/24646590518.
CI

do not log e2e telemetry in release actions

---

vscode/CHANGELOG.md
vscode/package.json

Update CHANGELOG and version number to reflect the patch release started in https://github.com/sourcegraph/cody/actions/runs/8976036958/job/24651990534 
diff: https://github.com/sourcegraph/cody/compare/vscode-v1.16.1...bee/v1.16.2?expand=1
Patch release pipeline has been started in https://github.com/sourcegraph/cody/actions/runs/8976036958/job/24651990534

VS Code: Release 1.16.2

---

lib/shared/src/llm-providers/ollama/completions-client.ts
vscode/CHANGELOG.md

- Closes https://github.com/sourcegraph/cody/issues/4008
- In the Ollama autocomplete client, ignore cut-in-the-middle response chunks and continue streaming.

Ollama: handle incomplete response chunks

---

lib/shared/src/cody-ignore/context-filters-provider.ts

Sample repo-name-resolver spans to analyze real-world performance during internal Cody Ignore testing.
Thanks @philipp-spiess for the tip!
N/a

Cody Ignore: sample repo-name-resolver spans

---

vscode/src/repository/repo-metadata-from-git-api.ts

1. Follow up on https://github.com/sourcegraph/cody/pull/3882 PR - Git repo logging for public repos
2. If the user asks a question in chat without opening a file in editor, we cache `undefined` value for the visibility. This PR changes this behaviour by only caching the values which are not `undefined`.  
1. Start the debugger from this branch.
2. Click on the new chat and ask a question without opening any file: The `gitMetadata` should be empty.
3. Open any file and click on the new chat and ask a question. The telemetry response should have an additional field gitMetadata, reflecting the git url and commit of the repo. If the repo is private, the field will be empty

git repo name logs for public repos

---

vscode/src/services/AuthProvider.ts
vscode/src/tutorial/commands.ts
vscode/src/tutorial/content.ts
vscode/src/tutorial/helpers.ts
vscode/src/tutorial/index.ts
vscode/src/tutorial/providers.ts

This PR:
- Fixes an issue where a user could become enrolled in the A/B test even if they were not a new user, by clicking "Tutorial" from the sidebar.
- Adds a "Start an Edit" command link, that will automatically trigger the edit command prompt when clicked. This is to see if we can convert a greater number of users to finish this step, as "Start a Chat" has a higher progression rate.
- Adds telemetry so that we can observe if users are triggering the chat/edit commands via a shortcut, or via the clickable link
- Improves the "Edit' tutorial command by ensuring we always get the right range to trigger the edit. We will automatically select the intended line if they did not already
https://github.com/sourcegraph/cody/assets/9516420/1b92799c-49b2-45a7-a65b-49d1ab493de3
1. Run the tutorial …

Interactive Tutorial: Add telemetry, improve command, and adjust flag logic

---

vscode/src/prompt-builder/index.test.ts

RE: https://github.com/sourcegraph/cody/pull/3929
Add new unit tests to cover the expected behavior for the `tryAddContext` method in the PromptBuilder class.
Also add unit tests for `tryAddToPrefix`.
Additional unit tests. No features were updated. The unit test CI should be still green.

Add more unit tests for PromptBuilder

---

vscode/src/editor/utils/editor-context.ts
vscode/src/prompt-builder/unique-context.ts

Small change to remove the `createContextFileRange` function, and use the centralized `toRangeData` utility function from the @sourcegraph/cody-shared module to convert the selectionRange to the required ContextItem['range'] format.
no feature change. CI should stays green

update: use toRangeData utility for range conversion

---

vscode/src/search/SearchViewProvider.ts

RE: https://sourcegraph.slack.com/archives/C05AGQYD528/p1715122290764839?thread_ts=1715122026.830309&cid=C05AGQYD528
- replace the input box for search query with quickPick 
- as input box does not allow us to add buttons
- add buttons to refresh index to the quick pick menu
1. Click on Search Code (Beta) on your sidebar
2. Verify the refresh buttons are showing up on the upper right of the menu
3. Search for something to ensure the search feature still works
No buttons on the upper right

Search: Add refresh buttons to Search Code menu

---

vscode/src/chat/chat-view/SimpleChatModel.ts
vscode/src/chat/chat-view/prompt.ts
vscode/src/prompt-builder/unique-context.ts

Follow-up https://github.com/sourcegraph/cody/pull/3929
This commit addresses an issue where the range property of a ContextItem object might not be an instance of the RangeData class. The changes ensure that the range property is always an instance of RangeData before performing any operations on it.
Currently, some contexts are not using the correct RangeData format, which would cause the checks to fail in `vscode/src/prompt-builder/unique-context.ts` with the error `Cannot read properties of undefined (reading: 'line').`:
To reproduce, try to build Cody from main with indexed search and local embeddings enabled, and then ask Cody a question: `tell me about SecretStorage?`
1. Build Cody from this branch and start debug mode
2. Open the code repository and make sure enhanced context is …

fix: ensure range is RangeData instance

---

vscode/src/chat/chat-view/prompt.ts
vscode/src/prompt-builder/index.test.ts
vscode/src/prompt-builder/index.ts

FOLLOW-UP https://github.com/sourcegraph/cody/pull/3929
Main change is to add `used` and `ignored` context lists for UI display.
Currently, context items from older chat messages are showing up in the last submitted message in the UI after https://github.com/sourcegraph/cody/pull/3929. 
Ideally, it should only display context items added for the lastest message only.
Summary: 
The DefaultPrompter now maintains separate lists for used and ignored context items. These lists are intended for UI display purposes and do not affect the actual prompt construction. The used list contains valid context items added from the last human message, while the ignored list contains user-specified context items that were too large to include.
I've also updated the unit test to reflect this change.
No agent …

Chat: exclude history items from UI

---

vscode/test/e2e/chat-atFile.test.ts
vscode/test/e2e/cody-ignore.test.ts
vscode/test/e2e/common.ts
vscode/webviews/components/shadcn/ui/command.tsx
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.module.css
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.tsx
vscode/webviews/promptEditor/plugins/atMentions/atMentions.module.css

No (or very minor) change in UI, no change in behavior. Just uses `cmdk` instead of our own custom menu list for @-mentions.
CI

use cmdk for existing @-mention UI

---

lib/shared/src/configuration.ts
vscode/package.json
vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/completions/create-multi-model-inline-completion-provider.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/main.ts

The goal of this PR is to add a custom command in cody (purely for the internal testing and comparing the completion output from different LLM models), which when triggered will print the completions from multiple providers. This would be very useful to compare completions output from different models.
The way I currently tried to implement the same is:
1. Initialize multiple completions providers at the initialization. The list of providers is picked from the VSCode settings by providing the following config:
```
"cody.autocomplete.experimental.multiModelCompletions": [
{"provider": "fireworks", "model": "starcoder-hybrid"},
{"provider": "fireworks", "model": "fireworks-completions-fine-tuned", "enableExperimentalFireworksOverrides": true},
{"provider": "anthropic", "model": …
```

add experimental vscode command to get completions from multiple models

---

vscode/src/services/tree-views/TreeViewProvider.ts

Issue:
- We call `refresh` in the constructor of `TreeViewProvider`
- This is an async method that will possibly check for the existence of a feature flag too
- This constructor is called before we finish authenticating, so we have a race condition where we check for a feature flag before the user is authenticated
Fix:
- We already call `refresh` when we have a valid change that should trigger a refresh:
- Auth change
- Reset called
- Auth change is triggered when the editor is loaded too, so we can be confident that this will be executed
The easiest way to recreate this is to check the interactive tutorial works:
1. Ensure you are in the interactive tutorial group
2. Reset VS Code insiders to start a fresh editor:
(macos)
```
rm -rf $HOME/.vscode-insiders
rm -rf …
```

TreeViewProvider: Do not refresh on init

---

vscode/CHANGELOG.md
vscode/package.json

Update CHANGELOG and version number to reflect the patch release started in https://github.com/sourcegraph/cody/actions/runs/9003635159
diff: https://github.com/sourcegraph/cody/compare/vscode-v1.16.2...vscode-v1.16.3
Patch release pipeline has been started in https://github.com/sourcegraph/cody/actions/runs/9003635159

VS Code: Release 1.16.3

---

.github/workflows/ci.yml

- Consolidates macOS e2e test runner now that we are programmatically determining the matrix and can do that
- Runs macOS e2e tests on the normal (non-large) macOS runner, which takes longer but is fine since these no longer block
- Runs Ubuntu e2e tests un-sharded on main, which is fine because these don't block (if this becomes annoying, we can easily return to sharding these on main)
(Trying again on #4052)
CI

only run ubuntu e2e tests on PR push, run all on main

---

vscode/CHANGELOG.md
vscode/package.json

Update CHANGELOG and version number to reflect the VS Code: Release 1.16.4 #4098 
- PR: https://github.com/sourcegraph/cody/pull/4098
- DIFF: https://github.com/sourcegraph/cody/compare/vscode-v1.16.3...v1.16.4?expand=1
Pipeline for 1.16.4 release has been started: https://github.com/sourcegraph/cody/actions/runs/9006884383
See details in PR: https://github.com/sourcegraph/cody/pull/4098

VS Code: Release 1.16.4

---

vscode/webviews/components/UserAvatar.module.css

Fix a minor css issue where the height of the user avatar is stretched by adjusting the container height to fit-content. 
Not sure if this is the best solution so any feedback is welcome :D 
Run the explain command and check the user avatar size to verify the user avatar is displaying correctly.

Chat UI: Adjust user avatar height to fit content

---

lib/shared/src/llm-providers/ollama/completions-client.ts

- Closes https://github.com/sourcegraph/cody/issues/4008
- Buffer incomplete chunks in the Ollama HTTP client.

Ollama: buffer incomplete response chunks

---

vscode/src/completions/logger.ts

This PR fixes completion events that were not getting logged on v2 telemetry because they contained the illegal character "`:`" within `action`. It also updates the helper function `writeCompletionEvent` thats being used to log completion events to accept subfeature as a parameter.
CI & Locally

[Bug Fix] Naming of v2 telemetry events and update `writeCompletionEvent` helper function [Easy Review]

---

vscode/walkthroughs/edit.md
vscode/walkthroughs/fix.md

- Crtl -> Ctrl
- Remove the "for macOS" and "for Windows & Linux" since those are self-explanatory IMO.
- Fix "keyboard short"
CI

fix typos and simplify keyboard shortcut mention

---

vscode/src/services/AuthProvider.ts

OK, I think this is finally the issue with the tutorial race condition:
1. We call `handleFirstEverAuthentication`, which kick starts the tutorial logic (which eventually evals a feature flag)
2. We call `this.storeAuthInfo`
This logic meant the feature flag call could have happened before the auth info was stored, so it would incorrectly get the feature flag for the user, and then we would cache this value.
Verified by manually modifying the code to force `storeAuthInfo` to always happen after a delay
Verified that switching this logic works without the delay

Tutorial: Handle auth __after__ we sync

---

vscode/package.json
vscode/src/repository/git-extension-api.ts

- Removes the init delay making the git API instantly available in Cody.
- To ensure that the `vscode.git` extension is activated before your extension, add `extensionDependencies` ([docs](https://code.visualstudio.com/api/references/extension-manifest)) into the `package.json` of your extension:
- It's [safe](https://github.com/microsoft/vscode/blob/main/extensions/git/README.md#git-integration-for-visual-studio-code) to do because the Git extension is bundled with Visual Studio Code. It can be disabled but not uninstalled.

Cody Ignore: activate the `vscode.git` before Cody extension via `ensionDependencies`

---

vscode/CHANGELOG.md
vscode/src/non-stop/FixupController.ts

fixes CODY-1449
closes https://github.com/sourcegraph/cody/pull/4111
closes https://github.com/sourcegraph/cody/issues/3952
Accidental regression from https://github.com/sourcegraph/cody/pull/3734
Wasn't caught due to the fact that VS Code has really poor type enforcement around `executeCommand` :(
1. Make Edits with only the default TypeScript language formatter selected
2. Check indentation is correct

Edit: Fix incorrect formatting with certain formatters

---

vscode/CHANGELOG.md
vscode/src/non-stop/FixupController.ts

If an Edit takes longer than 1000ms to format, it's likely that something has gone wrong.
This is a poor UX so we will stop formatting automatically when this happens.
1. Tested by lowering the formatter timer to a small value (10ms)
2. Running edits
3. Checking that the formatting step is skipped

Edit: Add maximum timeout to formatter logic

---

vscode/CHANGELOG.md
vscode/package.json

Build: https://github.com/sourcegraph/cody/actions/runs/9017560728
Diff: https://github.com/sourcegraph/cody/compare/vscode-v1.16.5...vscode-v1.16.6
Tested through PRs: https://github.com/sourcegraph/cody/pull/4113 and https://github.com/sourcegraph/cody/pull/4111

VS Code: Release 1.16.6

---

vscode/CHANGELOG.md
vscode/package.json

Do not merge to main until 1.16.7 is published
Update CHANGELOG and version number to reflect the VS Code: Release 1.16.7 https://github.com/sourcegraph/cody/pull/4121
- PR with detail: https://github.com/sourcegraph/cody/pull/4121
- DIFF: https://github.com/sourcegraph/cody/compare/vscode-v1.16.6...vscode-patch-v1.16.7
Pipeline for 1.16.4 release has been started: https://github.com/sourcegraph/cody/actions/runs/9006884383
See details in PR: https://github.com/sourcegraph/cody/pull/4121

VS Code: Release 1.16.7

---

vscode/src/commands/menus/command-builder.ts
vscode/src/edit/input/get-input.ts
vscode/src/edit/input/quick-pick.ts
vscode/src/search/SearchViewProvider.ts

If the user has (for example) an Cmd+K edit quickpick open, then switches to their web browser to copy some information to paste into the edit quickpick input, then VS Code will close the quickpick. Many users set `"workbench.quickOpen.closeOnFocusLost": false,` in their VS Code settings to prevent this globally because it's annoying, so only users without that setting will experience this annoyance. All of the Cody quickpicks should remain when the user switches away because they are invoked through explicit user action and may have valuable unsaved input provided by the user.
Reported by @martinamps
Run Cmd+K. Cmd+Tab to another application. Ensure VS Code does not hide the edit quickpick.

keep quickpicks (esp for edit) open if focus is lost

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

RE: https://sourcegraph.slack.com/archives/C05AGQYD528/p1715096388594779
Currently, we are logging the postContextStatusToWebView event on empty status.
This PR updates to log non-empty status to reduce the noises in our debug logs.
1. Check your debug log to confirm if Cody is still logging empty status `[]`

Skip logging empty context status

---

vscode/CHANGELOG.md
vscode/webviews/promptEditor/PromptEditor.module.css

Previously, when the user had entered a very long message in chat (with many lines, specifically more than 80% of the viewport height), it was not possible to scroll the chat message editor up/down with the mouse or trackpad. This was a bug. (Arrow keys would still scroll it by moving the text insertion point.)
Now, it is possible to scroll with the mouse or trackpad.
Reported by @martinamps
Type a very long (tall) message into chat, like "a" (hit shift+enter many times) "a". Ensure that the chat message editor allows scrolling up/down with the mouse or trackpad.

allow scrolling with mouse of chat message editor

---

vscode/test/e2e/local-embeddings.test.ts
vscode/webviews/components/EnhancedContextSettings.tsx

If you open a subdir of a Git repository as the VS Code workspace root folder, then Cody will show `Folder is not a Git repository` as the embeddings status in the enhanced context popover. This is true, but it can be confusing. The ideal behavior is to make embeddings "just work" in this case, but in the meantime, this message is slightly clearer and should indicate to users that embeddings would work if they open up the Git repository root dir in the editor.
Reported by @martinamps
CI

slightly clearer message in context popover for git repo subdirs

---

vscode/webviews/components/modelSelectField/ModelSelectField.tsx

- make needs-cody-pro models clickable so the user can upgrade: Fixes an issue with the new model selector where needs-cody-pro models were disabled and therefore not clickable.
- fix bug where model selector would not work on first click: Similar to https://github.com/sourcegraph/cody/pull/4121 (HT @abeatrix).
1. Sign in with a Cody Free (not Pro) user
2. In the chat model selector, select a Cody Pro-only model. The web browser should open to the upgrade page and the model should not be selected in the chat view.
3. Sign in with a Cody Pro user.
4. Select a different model. Ensure that the selected model is used (with `cody.debug.verbose` `true` in user settings).

fix needs-cody-pro model selector bugs

---

vscode/src/local-context/download-symf.ts
vscode/src/local-context/symf.ts

We want to upgrade symf to a [new version](https://github.com/sourcegraph/symf-private/pull/13) which improves reranking. 
Ran this locally and logged the expanded and original user queries, these matched the inputs to Cody and search using symf worked as expected.

Use new version of symf with expanded query param

---

vscode/src/context/repo-picker.ts

c.f. https://github.com/sourcegraph/cody/pull/4059#issuecomment-2103878481
Let the user know why we show a warning somtimes.
- Set an overwrite policy (e.g. `{ "include": [], "exclude": [{ "repoNamePattern": "cody" }] }`) and connect to an enterprise instance (e.g. s2)
- Pick models for chat and observe the window

Explain the warning icon in repo picker

---

.github/workflows/scip-typescript.yml

Fixes GRAPH-578
- Existing scip-typescript workflows should now work

Use SRC_ACCESS_TOKEN in scip-typescript uploads

---

.github/workflows/scip-typescript.yml

We're not using k8s.sgdev.org any more
n/a

chore: Stop uploading indexes to k8s.sgdev.org

---

vscode/src/fetch.node.test.ts
vscode/src/fetch.node.ts

This was initially added in #3769 but we had to revert it. Bringing the test back so we have this behavior documented
- test green

Add back socket reuse test

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
agent/recordings/rateLimitedClient_2043004676/recording.har.yaml
vscode/src/completions/logger.test.ts
vscode/src/completions/logger.ts
vscode/src/main.ts
vscode/src/services/UpstreamHealthProvider.ts

Part-of CODY-1495
This PR adds a new service that continuously pings the upstream Sourcegraph instances `/healthz` endpoint with a `HEAD` request to estimate the RTT to the SG instance.
For now, pings are logged in debug mode and attached to autocomplete events (since we want to use it to investigate autocomplete latencies). Later we might extend this into a Cody Help command (cc @RXminuS)
We also want to upload this data to Prometheus as a follow-up.
- Enable verbose debug mode
- Open the extension spot the new `UpstreamHealth` message. It will update after 10 minutes (or you can overwrite the timeout in `UpstreamHealthProvider`)
- Cause an autocomplete to appear and check the suggested event for a new `medianUpstreamLatency` field.

Measure upstream health and attach median to autocomplete events

---

vscode/package.json
vscode/src/completions/create-multi-model-inline-completion-provider.ts

- The `when` configuration field is not applicable to commands:
- To verify disable autocomplete and observe that all autocomplete commands are still visible in the command list.
- The related JSON schema in VS Code sources confirms this: https://github.com/microsoft/vscode/blob/29aeab1cbb350107a7bd5962b5e7efe745e0a3ec/src/vs/workbench/services/actions/common/menusExtensionPoint.ts#L729-L773. The `when` field is missing. Only `enablement` is specified.
- The VS Code document is misleading: https://code.visualstudio.com/api/extension-guides/command#controlling-when-a-command-shows-up-in-the-command-palette
- This PR changes all `when` fields to `enablement` to hide Cody commands under certain conditions.
- **Design input required**: we use `"cody.activated && editorTextFocus"` in multiple …

VS Code: use `enablement` for Cody commands

---

lib/shared/src/mentions/providers/githubMentions.ts
vscode/src/chat/context/constants.ts
vscode/webviews/promptEditor/nodes/ContextItemMentionNode.ts
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.tsx

For the at-mention GitHub context, this PR adds the functionality which shows the latest PRs and issues in the options list when no issue/PR number has been typed yet. 
If the user types `@gh:issue:` cody will show the list of the latest issues assigned to the user. 
If the user types `@gh:pr:` cody will show the list of the latest PRs for the opened repo. 
Demo: https://www.loom.com/share/36c483d356464580b655c6f228c02fc9
- Open cody 
- Type `@gh:pr:`, and it should show you the list of the latest PRs from the repo.
- Type `@gh:issue:`, and it should show you the list of assigned issues.

Show latest pr & issues automatically in options list

---

vscode/CHANGELOG.md
vscode/scripts/github-changelog.ts

I noticed the 1.16.7 release failed due to a malformed link. This PR fixes the link but also makes it so the script handles malformed links gracefully.
See: https://github.com/sourcegraph/cody/actions/workflows/vscode-stable-release.yml
- `cd vscode`
- `pnpm run github-changelog`
- `cat GITHUB_CHANGELOG.md`

Fix release changelog script

---

lib/shared/src/models/dotcom.ts
vscode/CHANGELOG.md

FOLLOW UP ON https://github.com/sourcegraph/sourcegraph/pull/62640
Do not merge this until https://github.com/sourcegraph/sourcegraph/pull/62640 is deployed
Check if the new gpt 4o shows up on the model list.
Can confirm gpt-4o model ID works when connect directly to the open AI endpoint in dev mode:

Cody PLG: Add GPT-4o to model list

---

lib/shared/src/codebase-context/messages.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/prompt-builder/index.test.ts
vscode/webviews/promptEditor/nodes/ContextItemMentionNode.ts
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.story.tsx
vscode/webviews/promptEditor/plugins/atMentions/OptionsList.tsx
vscode/webviews/promptEditor/plugins/atMentions/atMentions.tsx
vscode/webviews/promptEditor/plugins/atMentions/util.ts

There is no change to behavior; this is just a refactor to extract code, add some notes, and make other minor code style changes.
CI

extract ContextItem#isTooLarge calculation and add deprecation note

---

vscode/src/completions/inline-completion-item-provider.ts
vscode/src/services/StatusBar.ts

Issue: https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1715609038152519
The rate limit error does not clear automatically when the rate limit resets, at least for 1 hour or until the user manually selects the error, even after there is a successful completion. 
This PR will clear the error at whichever is the earliest between rate limit reset time or 1 hour from error creation. 
Manually tested locally.
- build extension
- set cody override limit to 1 at dotcom
- try code completion
- Cody status icon will turn yellow and show the rate limit error resetting at the same time. (because of override)
- wait from a minute, the error will automatically go away.

Clear rate limit error after reset timeout

---

lib/shared/src/cody-ignore/context-filters-provider.test.ts
lib/shared/src/cody-ignore/context-filters-provider.ts
lib/shared/src/sourcegraph-api/graphql/client.ts

sourcegraph.com can set Cody Ignore policy, however it is unlikely to. There's a window from startup until the ignore policy is fetched where we conservatively default to ignoring files. For users on slow connections, that could be a long time.
This changes the rules so that for dotcom accounts, we will liberally assume all files are allowed until the policy is fetched. This ensures dotcom users should not see Cody Ignore notices.
`pnpm test:unit`
Manual test:
1. Run the JetBrains plugin, sign in to dotcom, open a file. Close that IDE.
2. Run in VSCode with agent:debug configuration.
3. Run JetBrains in IntelliJ with `CODY_AGENT_DEBUG_PORT=3113;CODY_AGENT_DEBUG_REMOTE=true;CODY_JETBRAINS_FEATURES=cody.feature.inline-edits=true`
4. As quickly as possible, cmd-shift-H to run "Document" …

Cody Ignore: Default to allowing files for dotcom until the policy is fetched

---

vscode/package.json

- Having `"extensionDependencies": ["vscode.git"]` disables Cody in restricted workspaces. Reverting to the manual Git extension initialization we already have in place.
CI

VS Code: remove extension dependencies

---

vscode/src/graph/bfg/download-bfg.ts

Bump BFG version to include https://github.com/sourcegraph/bfg-private/pull/184
- Embedding indexing succeeds for https://github.com/huggingface/transformers repo (that fails on main)

Bump BFG version

---

vscode/src/completions/context/retrievers/section-history/nextTick.ts
vscode/src/completions/context/retrievers/section-history/section-history-retriever.test.ts
vscode/src/completions/context/retrievers/tsc/SymbolFormatter.test.ts
vscode/src/completions/context/retrievers/tsc/SymbolFormatter.ts
vscode/src/completions/context/retrievers/tsc/relevantTypeIdentifiers.ts
vscode/src/completions/context/retrievers/tsc/tsc-retriever.test.ts
vscode/src/completions/context/retrievers/tsc/tsc-retriever.ts

Fixes CODY-1434
Previously, the `tsc-mixed` context retriever made  the UI freeze because it was doing super inefficient things with context expansion. This PR fixes the problem so that the performance is back to normal.
Green CI.
I tested this change manually in large projects and confirmed that the latency overhead for tsc context-retriever is no longer huge. For example, it's 33ms here on line 1300 in the largest file in svelte/language-tools repo

TSC Graph Context: fix performance

---

vscode/CHANGELOG.md
vscode/package.json

VS Code: Release 1.18.0 - Stable Release.
Blog post: https://github.com/sourcegraph/about/pull/6940

VS Code: Release 1.18.0

---

vscode/CHANGELOG.md
vscode/webviews/promptEditor/plugins/atMentions/atMentions.tsx

This behavior existed to preserve parity with the pre-Lexical-editor behavior, but I think we should remove it because it will interfere with more complex @-mentions where the "query" does need to include spaces. (For example, think about @-mentioning a title of a doc with spaces in it.)
CI

space key no longer triggers commit of selected mention item

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/SerializedChatMessage.kt
agent/src/index.test.ts
lib/shared/src/chat/transcript/index.ts
lib/shared/src/chat/transcript/messages.ts
vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatModel.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/services/LocalStorageProvider.test.ts
vscode/src/services/LocalStorageProvider.ts
vscode/test/e2e/chat-input.test.ts
vscode/webviews/chat/Transcript.story.tsx
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/messageCell/MessageCell.tsx
vscode/webviews/chat/cells/messageCell/SpeakerIcon.tsx
vscode/webviews/chat/fixtures.ts
vscode/webviews/chat/models/chatModelContext.tsx
vscode/webviews/components/modelSelectField/ModelSelectField.tsx

Previously, you could only change the chat model before you started a chat. Now, you can change it at any point.
- Changing a chat model does not re-send previous messages.
- If you change the chat model and then edit a message, it gets sent to the new model (not the original model of the message).
1. Send a first chat message using any model.
2. Change the model using the model selector.
3. Send a 2nd chat message. Confirm it shows as being from the model you just chose.
4. Change the model to yet another model. Edit the 2nd chat message and send it. Ensure that the response now shows as being from the new model.
5. Close the chat and reopen it. Ensure that the models are still correct (by their icons).

support changing chat model after chat session has begun

---

agent/src/TestClient.ts
vscode/src/completions/logger.ts
vscode/src/services/UpstreamHealthProvider.ts

Closes CODY-1605
This PR changes the way we track upstream latency (= RTT to the Sourcegraph instance). Instead of measuring every 10 minutes and then exporting the median to the completion metadata, I thought that it might be simpler to include the last measurement with the completion data (and then we can run an aggregation on that). While coding, completion suggestions should happen more frequent then every 10 minutes so this will give us a higher resolution while we avoid to maintain a list.
Additionally, I've added a second parameter to measure the latency to Gateway. This is only turned on for Free/Pro users right now (to avoid outgoing traffic in air-gapped instances). 
Furthermore I added tracing to the upstream pings. With our current rate limit, one two two traces every ~10 …

Simplify upstream latency collector and measure gateway latency

---

lib/shared/package.json
lib/shared/src/context/openctx/api.ts
lib/shared/src/index.ts
lib/shared/src/mentions/providers/openctxMentions.ts
package.json
pnpm-lock.yaml
vscode/package.json
vscode/src/context/openctx.ts
vscode/src/main.ts

Previously, Cody would try to communicate with the OpenCtx VS Code extension in the extension host process. This required both the Cody and OpenCtx VS Code extensions to both be installed and activated, which was tricky and made it hard to develop on both simultaneously.
Now, Cody uses [@openctx/vscode-lib](https://www.npmjs.com/package/@openctx/vscode-lib), which means it does not need to rely on the OpenCtx VS Code extension being installed and activated.
To avoid affecting users who are not participating in this experiment, you must set `cody.experimental.openctx` to true in your VS Code user settings to use OpenCtx in Cody.
To try it out end-to-end, add the following to your VS Code user settings:
```
{
"openctx.enable": true,
"openctx.debug": true,
"openctx.providers": { …
```

use simpler way of loading OpenCtx (for mentions/context)

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

This fixes a bug where no LLM avatar was shown until the message was complete.
Type a chat message and hit send. Ensure that the LLM avatar shows up even while the message is being received.

show LLM avatar in chat transcript while message is loading

---

vscode/webviews/mentions/mentionMenu/MentionMenu.tsx
vscode/webviews/mentions/mentionMenu/useMentionMenuData.ts
vscode/webviews/promptEditor/plugins/atMentions/atMentions.tsx

This reduces undesirable invocations of querying context items. No behavior change.
CI

if no @-mention query, don't try to run query

---

vscode/src/prompt-builder/unique-context.test.ts
vscode/src/prompt-builder/unique-context.ts
vscode/test/e2e/command-core.test.ts

REPLACE https://github.com/sourcegraph/cody/pull/4225
The changes in this commit ensure that user-added context items always have the highest priority when deduplicating context items. This means that if a user-added item is present, it will be included in the unique context items, even if there are other duplicate items.
The test cases have been updated to reflect this behavior, and the `isUniqueContextItem` function has been modified to skip non-duplicated user-added items.
1. Start Debug mode from this branch
2. Run the Explain command
3. You should see that the selection file is included on top of the full file as context

Chat: prioritize user-added context items

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ProtocolTextDocument.kt
agent/src/AgentWorkspaceDocuments.ts
vscode/src/jsonrpc/TextDocumentWithUri.ts
vscode/src/jsonrpc/agent-protocol.ts

Add support for visible ranges for the client IDEs.
See also: https://github.com/sourcegraph/jetbrains/pull/1551
I'm not able to find scenario in which visible range wins over smart selection (see [selection.ts:43](https://github.com/sourcegraph/cody/blob/main/vscode/src/commands/context/selection.ts#L43)) but I verified in the debugger that it works as expected, and it might fix some corner case issues we observed with not perfect document context.

Add support for providing visible range by clients

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/context/chatContext.ts

> We've noticed a few events getting rejected like:
> `cody.at-mention.https://openctx.org/npm/@openctx/provider-sourcegraph-search/executed` due to the feature name length being greater than 60 characters!
This PR logs `cody.at-mention.openctx:executed` for all OpenCtx providers and passes the provider id in the metadata.
unit tests present

Replace provider id with OpenCtx for at-mention event names

---

vscode/README.md
vscode/package.json

Updates VS Code extension meta description and README:
- Meta description was >300 chars, so it was getting cut off in the marketplace. New description is 297 chars.
- README and meta description are both also updated for new messaging that refers to code search rather than general code understanding (see "Cody Messaging" in Notion for details)
Copy changes only.

Update description and messaging

---

lib/shared/src/sourcegraph-api/graphql/client.ts
vscode/webviews/Troubleshooting/ConnectionIssuesPage.tsx

Solves https://github.com/sourcegraph/cody/issues/4232
Thanks to Kalan and Bee we finally solved this issue which is the final issue that I found in the proxy settings.
https://www.loom.com/share/4865ebf0edd34bdcaf0084aeb31ea4f7 
When you log in again without the proxy and you have a cached result then Cody will log out coz the Graphql requests have a timeout on them. Previously the timeout was so long that the cody would be stuck in loading for many many minutes. 
Tested locally

Fix: Graphql Fetching blockage when Cody tries to load a cached proxy that can only be loaded behind a proxy

---

vscode/test/e2e/chat-atFile.test.ts
vscode/test/e2e/common.ts
vscode/test/e2e/context-settings.test.ts
vscode/test/e2e/local-embeddings.test.ts
vscode/webviews/App.tsx
vscode/webviews/Chat.story.tsx
vscode/webviews/Chat.tsx
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx
vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx
web/src/App.tsx

This helped with discoverability but I'm removing this for the prerelease build because it seems like we'll change this UI a lot before the next release and it was causing flakiness. If we don't make progress on that new UI as hoped, then we probably need to add it back to avoid losing a lot of users who don't know how to set up context.
Added https://linear.app/sourcegraph/issue/CODY-1781/check-whether-we-need-to-go-back-to-showing-enhanced-context-popover to track this to make sure we don't miss it for the release.
CI

do not open enhanced context popover by default on new installs

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ContextItem.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/MentionParams.kt
lib/shared/src/codebase-context/messages.ts
vscode/src/chat/context/chatContext.ts
vscode/src/editor/utils/editor-context.ts

This is to make it clearer in ContextItemOpenCtx which fields are for before and after resolving a context item.
Additionally we remove the unused description field.
Test Plan: CI

openctx: store mention specific fields separately

---

vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.test.tsx
vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx

<kbd>Alt/Opt+Enter</kbd> should submit the chat message without enhanced context. There was a bug in the new chat UI where it submitted the message with enhanced context.
CI

fix alt/opt+enter (should submit w/o enhanced context)

---

vscode/CHANGELOG.md
vscode/package.json

RE: https://linear.app/sourcegraph/issue/CODY-1686/enable-code-chat-with-alt-l-shortcut-before-cody-launch 
CONTEXT: https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1716395608291109
> want: if i have a selection and a start a new chat, bring that selection into the chat
Assign new chat keybinding to the "New Chat with Selection" command.
1. Build cody from this branch
2. Select some code in your editor
3. Press `ALT+L` to start new chat with @selection

Keybind: Alt + L for starting new chat with @-selection

---

vscode/src/non-stop/FixupController.ts

This fix must be paired with a [sourcegraph/jetbrains PR](https://github.com/sourcegraph/jetbrains/pull/1603) that moves the logic to the client.
Everyone has try to break it -- specifically:
- the Accept lens group (with Edit/Retry, Undo, Show Diff) should _always_ be shown after requesting a Document Code
- It should auto-accept your current edit if you start another one somewhere else in the document.
This is already covered by the test plan, so it just needs to be re-run with this specific feature in mind.

Move auto-accept logic from Agent to client for now, workaround for Issue 315 for GA

---

vscode/test/e2e/chat-input.test.ts

The `isMacOS` check is no longer needed in the `chat-input.test.ts` file for testing the Alt+L keybind, as the command directly uses the 'Alt+L' key combination on all platforms. This is because the command is registered under ['alt+l' in the package.json](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/package.json?L617-621)?
This fixes the issue where e2e tests are failing on Mac in main CI.
Green CI.
Run the e2e test locally from this branch: `pnpm test:e2e chat-input` to verify:

E2E: remove isMacOS check for Alt+L keybind test

---

vscode/src/edit/provider.ts

CONTEXT: https://sourcegraph.slack.com/archives/C05AGQYD528/p1716415682614109
CLOSE: https://github.com/sourcegraph/jetbrains/issues/1597
I suspect the issue is caused by injecting the `responsePrefix` repeatedly on every new stream response during the `typewriter.update()` step, a change we made when we first refactored fixup away from the old MessageProvider in https://github.com/sourcegraph/cody/pull/2549. 
I believe this can be safely removed because when we first received a response from the LLM,  the 
multiplexer would publish the `responsePrefix`, which will then notify the topic subscribers which then run the [typewriter.update() ](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/edit/provider.ts?L80) step. This is why injecting the `responsePrefix` seems …

Edit: do not inject responsePrefix on typewriter.update()

---

vscode/CHANGELOG.md
vscode/src/edit/provider.ts

RE: https://github.com/sourcegraph/cody/issues/3963
This PR fixes an issue with test command inserting test file name at the top of the unit test
> The inclusion of a file path at the top is a bug.
I suspect the issue was introduced in [#3759](https://sourcegraph.com/github.com/sourcegraph/cody/-/commit/db6d4eb84bd32b6141bb93e732d14c40a5775613?visible=3) where we updated to only subscribe to the multiplexer for file creation if we couldn't locate the test file internally. This becomes an issue when we ask for the LLM to always return the test file name in the [PROMPT_TOPICS.FILENAME](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/edit/prompt/models/generic.ts?L88) in our prompt.
- Fixes an issue where the test file name was incorrectly inserted when using the unit …

Test Command: Fix issue with inserting test file name with unit test

---

vscode/webviews/chat/Transcript.module.css
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/messageCell/BaseMessageCell.tsx
vscode/webviews/chat/cells/messageCell/assistant/AssistantMessageCell.tsx
vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx

Instead of ensuring the assistant message is visible, make it so it's impossible for it to NOT be visible ever by adding a margin at the bottom of the last human message that will be filled in visually by the subsequent assistant message.
HT @erikars and @Kynlos for reporting this issue
CI

fix jumpy scroll when submitting followup

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/EditCommands_CodeParams.kt
agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/edit_1541920145/recording.har.yaml
agent/src/edit.test.ts
agent/src/explainPollyError.ts
agent/src/index.test.ts
lib/shared/src/models/index.ts
vscode/src/jsonrpc/agent-protocol.ts

This is the first step to address JetBrains performance problems for
inline edit. While removing the test from index.test.ts, I skipped a
flaky custom command test that keeps failing on unrelated changes (due
to sensitive prompt).
Green CI. There is no functional difference here. Only refactoring tests.

Move inline edit tests to separate file

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/fireworks.ts

1. This PR adds the fine-tuning model setup, trained on context aware FIM examples on top of bigcode/the-stack. More details about the training dataset/ modeling/ offline evaluation etc can be found in [this RFC](https://docs.google.com/document/d/1myMceHu7x8gh0B9eb_kRE719AGqVHfZ3py9k_3luym8/edit#bookmark=id.nkenlaow7lyh).
2. We wanted to iterate faster on the modeling changes, i.e. don't want to replace the model string in the client every time we change a model in the backend - So, this PR adds [four variant feature flags and control feature flag](https://github.com/sourcegraph/cody/compare/hitesh/finetuned-fim-model-integration?expand=1#diff-b990afc7444ecfe27e4f42d0b9af949030d8aca26e21a4f090a7c0a0fe19b0ceR24) and the variant based feature-flag names will be send to cody-gateway as is, …

adding FIM finetuned model hosted on fireworks

---

vscode/CHANGELOG.md
vscode/package.json

Patch release follow-up based on https://github.com/sourcegraph/cody/blob/main/vscode/CONTRIBUTING.md
- version/CHANGELOG only

VS Code: Release 1.18.2

---

.vscode/launch.json
.vscode/tasks.json

Added a launch config for spawning the Agent on port 3113, so JetBrains can attach.
This is not code, but rather dev infrastructure, so it's tested manually by launching the configuration.

added a much-needed run config for spawning the Agent

---

lib/shared/src/index.ts
lib/shared/src/local-context/index.ts
vscode/src/chat/chat-view/context.ts
vscode/src/context/remote-search.ts

`RemoteSearch` implemented `IRemoteSearch` to allow remote searches in Edit/
Fix. We no longer pull in this remote context, so we can simplify and remove
the extra logic.
This PR also fixes a tiny issue where we awaited the remote search promise
after it's already resolved.
Covered by existing tests. Manually tested VSCode extension.

Remove unused RemoteSearch methods

---

agent/src/AgentWorkspaceDocuments.ts
agent/src/agent.ts

In a client:
1.  open sourcegraph/cody , execute.ts  file
2.  Select whole ExecuteEditArguments interface block
3.  Click Document Code
4.  Undo edit (from inlay lens)
5.  Click Document Code again -> comments will appear in wrong

Improve incremental document update

---

agent/src/AgentTextEditor.ts
agent/src/AgentWorkspaceDocuments.test.ts
agent/src/AgentWorkspaceDocuments.ts
agent/src/TestClient.ts

The PR https://github.com/sourcegraph/cody/pull/4277 was a lesson that we have very brittle code around dealing with document synchronization. This PR is an attempt to improve code health by
- Adding tests!
- Being more rigorous with null handling
- Making the code a bit easier to follow (hopefully)
See new test suite.

Agent: make AgentWorkspaceDocuments more robust

---

vscode/src/services/open-telemetry/CodyTraceExport.ts
vscode/src/services/open-telemetry/OpenTelemetryService.node.ts

I remember we had some issues in the past where trace uploading to the SG instance didn't work because auth was missing. This change includes the access token. I tried it on S2 and while I didn't see any issues, logs also did not progress into GCP suggesting we also need to change the Cloud otel config first.
Traces are disabled by default unless you're on PLG (where the FF is enabled for some % of users) or you manually enable it so this won't break any setups.
- CI
- Connected to S2 and enable traces via `"cody.experimental.tracing": true`. Observe that nothing throws but traces still won't be showing up in GCP traces yet

Include access token when exporting traces for enterprise

---

agent/src/panicWhenClientIsOutOfSync.test.ts
agent/src/panicWhenClientIsOutOfSync.ts

The agent is panicking on mismatches for visibility ranges, which is probably catching legitimate bugs but they're getting in the way of debugger higher-priority bugs related to content/selection. For now, we can live with minor de-sync between client/server on visibility ranges.
Manually ran JB and confirmed it no longer panicks on visibility range (it still panicks on selection)

Agent: disable panic check for visibility ranges

---

agent/src/panicWhenClientIsOutOfSync.ts
agent/src/renderUnifiedDiff.test.ts
agent/src/renderUnifiedDiff.ts

Previously, we would panic the agent process if the "source of truth"
document didn't match 100% between the client/server. Now, we soften the
assertion to only compare "source of truth" properties that are defined
by the client. This gives the client freedom to leave out some
properties (like content).
The motivation for this change is that the JB client can't always give a
100% correct answer in some scenarios. For example, on caret changes, we
only know the "logical position" (line/character), we don't know the
offset, or even the document contents. Just as we are calling
`Document.getText()`, the caret may already become outdated by mutation
on another thread.## Test plan
Manually tested with JB.

Agent: soften panic assertions

---

agent/src/AgentWorkspaceDocuments.ts

Just run any client with with `cody-agent.panic-when-out-of-sync` - it should not fail immediately.

Reseting document content properties is happening too late in the code

---

vscode/CHANGELOG.md
vscode/webviews/chat/ChatMessageContent.module.css

The introduction of Tailwind's reset meant that list elements were not showing any bullet or number. This un-resets the CSS within Markdown-rendered content.
CI

fix styling for bullet lists

---

agent/src/panicWhenClientIsOutOfSync.ts

Typescript !== TypeSafe. In this case messages coming over the JsonRPC are null instead of undefined.
And `typeof null` is obviously...`object`!
We should (and will) be resolving this on a more robust higher level but for now having the most resillient null/undefined, even if not the prettiest, is solves the issue.
- unit tests still pass.
- Checked that manually setting to null does not break

Makes "undefined" check more resillient

---

agent/src/AgentWorkspaceDocuments.ts
agent/src/agent.ts
agent/src/cli/evaluate-autocomplete/triggerAutocomplete.ts
lib/shared/src/models/types.ts
vscode/src/chat/chat-view/SidebarViewController.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/protocol.ts
vscode/src/jsonrpc/TextDocumentWithUri.ts
vscode/src/jsonrpc/agent-protocol.ts
vscode/src/jsonrpc/bfg-protocol.ts
vscode/src/jsonrpc/context-ranking-protocol.ts
vscode/src/jsonrpc/embeddings-protocol.ts
vscode/src/jsonrpc/protocol.test.ts

To prevent bugs when communicating with peers implemented in different programming languages cross-process RPC protocols must not differentiate between `undefined`, ECMAScript property presence (`hasOwnProperty`), and `null`. Anywhere that a value can be `undefined`, our code needs to handle `null` values or no such property existing, and all must be handled in the same way (and vice versa).
If a property's TypeScript type includes any of `null`, `undefined`, or `?` (optional field), then it must use *all* of them in its TypeScript type. All of those possible TypeScript types must be handled.
This makes it impossible to accidentally only check `if (message.foo === undefined) { ...` in cases where `message` came from a peer that may have sent `message.foo === null`.
Also adds tests that …

Agent: handle `null` values where we previously only handled `undefined`

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/EditCommands_CodeParams.kt
agent/src/agent.ts
vscode/src/commands/execute/doc.ts
vscode/src/commands/execute/test-edit.ts
vscode/src/edit/prompt/models/generic.ts
vscode/src/jsonrpc/agent-protocol.ts

This change adds a new `mode` parameter to the `editCommands/code` request in the agent protocol. The `mode` parameter can be either `'edit'` or `'insert'`, and it allows the client to specify whether the edit command should perform an edit or an insertion operation.
The corresponding changes have been made in the Kotlin binding and the TypeScript agent implementation to support this new parameter.
2: add checks for empty selection in doc and test commands
This change adds checks for empty selections in the `executeDocCommand` and `executeTestEditCommand` functions. If the selected text is empty (AFTER we have expanded the range and not before), the functions will throw an error to prevent the commands from executing on an empty selection.
The changes also include some minor logging …

Agent: add `mode` parameter to editCommands/code

---

vscode/.storybook/main.ts
vscode/webviews/Chat.module.css
vscode/webviews/chat/Transcript.module.css
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/messageCell/BaseMessageCell.module.css
vscode/webviews/chat/fixtures.ts
vscode/webviews/promptEditor/BaseEditor.tsx
vscode/webviews/promptEditor/PromptEditor.tsx
vscode/webviews/promptEditor/plugins/keyboardEvent.tsx
vscode/webviews/storybook/VSCodeStoryDecorator.module.css

- remove needless onKeyDown Lexical event listener
- avoid white flash when changing stories in dark theme
- remove erroneous VSCodeCell decorator style
- add new chat fixture to test scrolling in storybook
- clean up Transcript and Chat styling and containers
CI

misc improvements to chat storybooks and removing unused chat-related code/styles

---

vscode/test/e2e/chat-input.test.ts

The Lexical editor has its own e2e tests for these keyboard shortcuts, and we have a unit test to ensure that empty messages can't be submitted.
CI

rm unnecessary e2e test

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/context.ts

This change includes the user's current editor selection as context for all new chat messages by default. The selection context is added to the user context items when creating a new chat message.
To support this, the `getContextFileFromSelection` function is now imported and used in `SimpleChatPanelProvider.ts`. If the chat message source is 'chat', the current selection context is retrieved and added to the `userContextFiles` array before resolving the context items.
The selection context retrieval logic is also removed from `getPriorityContext` in `context.ts` since it is now handled in `SimpleChatPanelProvider.ts`.
1. Build Cody from this branch
3. Highlight some code in your editor
2. Start a new chat and ask Cody about the code you highlighted
3. Submit the question with `Opt + …

Chat: Include editor selection in chat context by default

---

vscode/webviews/chat/cells/messageCell/human/editor/toolbar/SubmitButton.module.css
vscode/webviews/components/modelSelectField/ModelSelectField.module.css
vscode/webviews/components/shadcn/ui/button.tsx
vscode/webviews/components/shadcn/ui/toolbar.module.css
vscode/webviews/components/shadcn/ui/toolbar.tsx

In many light themes for VS Code, the chat input toolbar had very low or no contrast.
HT @eseliger @toolmantim
Before:
After:
CI

fix chat input colors on light themes

---

lib/shared/src/mentions/api.ts

We want these to feel native.
Also the heading of the @-mention menu when you've selected a provider now just contains the provider name itself, instead of `Search using PROVIDER provider`, which could be ungrammatical or clunky. We should have a way in the OpenCtx `meta` result to specify the right label here, but for now, this suffices.
CI

remove "(by OpenCtx)" in @-mention menu

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/CodyAgentServer.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/MemoryUsage.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/Testing_MemoryUsageResult.kt
agent/src/AgentWorkspaceDocuments.ts
agent/src/TestClient.ts
agent/src/agent.ts
agent/src/memory.test.ts
agent/src/panicWhenClientIsOutOfSync.test.ts
agent/src/vscode-shim.ts
vscode/src/jsonrpc/agent-protocol.ts
vscode/src/main.ts
vscode/src/tree-sitter/parse-tree-cache.ts

Fixes https://github.com/sourcegraph/jetbrains/issues/1587
Previously, the agent was firing the
`vscode.window.onDidChangeVisibleTextEditors` event on every `textDocument/didChange` event, including when we only updated the selection (no content changes). In VSC, this event only fires when you open a new file, change the actived file tab, or close a file. Now, the agent mirrors the VSC behavior by firing the event less frequently. This change doesn't actually fix the memory leak, it just makes it very difficult to reproduce because you need to open/close files thousands of times. Previously, it was easy to reproduce, you could just drag-select text with the mouse and fire thousands of events.
See new `memory.test.ts` file. This test suite can be skipped by default in CI because it's going …

Agent: close P0 memory leak on `textDocument/didChange`

---

agent/src/agent.ts

##
Instead of crashing the process we send debug message to client where we can display it in a nice way.
N/A, it's part of testing infrastructure

Agent: send notification about document sync issue to client instead of panicking

---

vscode/CHANGELOG.md
vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.story.tsx
vscode/webviews/promptEditor/PromptEditor.module.css
vscode/webviews/promptEditor/PromptEditor.story.tsx

Fixes https://linear.app/sourcegraph/issue/CODY-1881/cody-for-vs-code-long-user-messages-cant-be-scrolled-using-a-mouse
HT @taras.yemets
CI, and try new storybook

fix bug preventing vertically scrolling of long messages in the input

---

vscode/CHANGELOG.md
vscode/webviews/promptEditor/BaseEditor.tsx
vscode/webviews/promptEditor/plugins/noRichTextShortcuts.tsx

Fixes https://linear.app/sourcegraph/issue/CODY-1892/fix-copy-and-paste-of-mentions-in-lexical-editor
Fixes https://linear.app/sourcegraph/issue/CODY-61/bug-copy-and-paste-removes-file-tokenization
Fixes https://linear.app/sourcegraph/issue/CODY-1779/-mentions-not-copyingpasting-properly
https://github.com/sourcegraph/cody/assets/1976/6b7aa431-c7f7-4970-9ca0-244b978a0d57
CI, and see video

support pasting @-mentions in chat input

---

agent/src/__snapshots__/document-code.test.ts.snap
agent/src/__tests__/document-code/src/TestClass.ts
agent/src/__tests__/document-code/src/TestLogger.ts
agent/src/__tests__/document-code/src/example.test.ts
agent/src/__tests__/document-code/src/sum.ts
agent/src/document-code.test.ts

Previously, the document code tests ran in the monolithic `example-ts` workspace. This was problematic because when you added a new "Document Code" test to example-ts, then it would invalidate the HTTP recordings for unrelated tests in the `index.test.ts` file, because they use enhanced symf context that would pull in the newly added files. Now, we run the test with an isolated `document-code` workspace so that we can add tests without introducing big unrelated diffs in `index.test.ts`.
Green CI

Document Code: move tests to separate workspace

---

agent/recordings/document-code_965949506/recording.har.yaml
agent/src/__snapshots__/document-code.test.ts.snap
agent/src/__tests__/document-code/src/Hello.kt
agent/src/agent.ts
agent/src/document-code.test.ts
vscode/CHANGELOG.md
vscode/src/commands/execute/doc.ts
vscode/src/edit/utils/edit-selection.ts

Fixes an issue where the "Document Code" command would incorrectly insert documentation at the cursor position: This occurred when the cursor was in the middle of some code, but we did not have a tree-sitter `documentableNode` or a folding range to expand to.
We now always fallback to the **line selection** and adjust the `insertionPoint` to be at the start of this line.
1. Place the cursor in the middle of some text (e.g. in a Markdown file)
2. Run "Document Code"
3. Expect that the inserted documentation is inserted in the line above the cursor

Document Code: Always expand to the start of a line as a fallback

---

agent/README.md

I spent a while debugging this error. Hitesh had also had the same problem. Hopefully, this will save time for the next person who hits on the problem (adding a dependency on `vitest` from the main bundle).
N/a

Agent: document pitfall in the agent readme

---

agent/src/vscode-shim.ts
vscode/src/testutils/mocks.ts

These classes are missing in the VS Code shim. They will be needed in order to support Code Actions (for Fix command). Adding this as a separate low-risk PR.
Green CI.

Agent: implement more parts of the VS Code shim

---

vscode/src/testutils/CodyPersister.ts
vscode/src/testutils/polly.ts

The `recordingDirectory` setting was actually being ignored because our custom persister has the id `cody-fs` when the settings only allow the ID `cody`.
Green CI

Polly: fix bug where `'fs'` persister didn't pick up config

---

vscode/src/graph/bfg/download-bfg.ts

Updates version of BFG to include https://github.com/sourcegraph/bfg-private/pull/187.
Closes AI-60.
- e2e tests

Update BFG version

---

vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx

CLOSE https://github.com/sourcegraph/cody/issues/4321
Remove isFirstMessage check for adding user Context from selection via  `Add selection to Cody Chat`. 
Currently `isFirstMessage` blocks users from adding selection to Cody chat if the message is not the first message.
1. Start Cody in debug mode from this branch
2. Start new chat and send Cody a question
3. Select some code in your editor
4. Right click in your selected code and select `Add selection to Cody Chat`
5. Verify the selected code is added as @-mention context in your chat window
Before this change, users are not able to `Add selection to Cody Chat` in non-new chat

fix: remove isFirstMessage check for adding userContextFromSelection

---

vscode/src/context/openctx/remoteRepositorySearch.ts

This updates the Sourcegraph Repositories search provider to use the updated OpenCtx protocol. Resolves the bug which causes the provider to be hidden on pre-release. 
tested manually

Fix Sourcegraph Repositories Search Context Provider for enterprise

---

lib/shared/src/telemetry-v2/singleton.ts
vscode/webviews/App.tsx
vscode/webviews/AppWrapper.tsx
vscode/webviews/Chat.story.tsx
vscode/webviews/Chat.tsx
vscode/webviews/OnboardingExperiment.story.tsx
vscode/webviews/OnboardingExperiment.tsx
vscode/webviews/Troubleshooting/ConnectionIssuesPage.tsx
vscode/webviews/chat/Transcript.test.tsx
vscode/webviews/chat/cells/messageCell/assistant/ContextFocusActions.tsx
vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.test.tsx
vscode/webviews/storybook/VSCodeStoryDecorator.tsx
vscode/webviews/utils/telemetry.ts
web/src/App.tsx

Instead of requiring this `telemetryRecorder` to be passed down via props, which is messy, it's now stored in React context.
CI

fix "Try again with different context:" failure due to telemetryRecorder misuse

---

agent/src/cli/jsonrpc.ts
agent/src/index.test.ts
vscode/src/jsonrpc/CodyJsonRpcErrorCode.ts
vscode/src/jsonrpc/jsonrpc.ts

The PR #3807 introduced a regression in how we deal with rate limits. Before that PR, we returned a dedicated JSON-RPC error code on rate limit errors, and this code was no longer returning after the PR. This PR recovers the original logic and integrates it with the new vscode-jsonrpc bindings.
Not tested yet.

Agent: return more details in JSON-RPC error responses

---

vscode/CHANGELOG.md
vscode/src/tree-sitter/queries.ts
vscode/src/tree-sitter/queries/java.ts
vscode/src/tree-sitter/query-tests/documentable-nodes.test.ts
vscode/src/tree-sitter/query-tests/test-data/documentable-node.java
vscode/src/tree-sitter/query-tests/test-data/documentable-node.snap.java

This PR adds tree-sitter support for `getDocumentableNode` in Java.
1. Open Java code
2. Move cursor to a position on a documentable node, e.g. a method name
3. Document code, expect documentation is generated correctly (above the method)
4. Move cursor to a position within a documentable node, e.g. within a method
5. Document code, expect documentation is generated correctly (above the method)

Document code: Add tree-sitter query for Java

---

vscode/src/tree-sitter/queries/java.ts
vscode/src/tree-sitter/query-tests/test-data/documentable-node.snap.java

Excludes local variables from the `getDocumentableNode` query in Java. This means we'll generally expand to the nearest function/method/class declaration/interface declaration
Unit tests

Document Code: Exclude local variables from getDocumentableNode in Java

---

vscode/src/tree-sitter/queries.ts
vscode/src/tree-sitter/queries/kotlin.ts
vscode/src/tree-sitter/query-tests/documentable-nodes.test.ts
vscode/src/tree-sitter/query-tests/test-data/documentable-node.kt
vscode/src/tree-sitter/query-tests/test-data/documentable-node.snap.kt

Description
This PR adds tree-sitter support for getDocumentableNode in Kotlin.
Copied from https://github.com/sourcegraph/cody/pull/4353
- Open Kotlin code
- Move cursor to a position on a documentable node, e.g. a method name
- Document code, expect documentation is generated correctly (above the method)
- Move cursor to a position within a documentable node, e.g. within a method
- Document code, expect documentation is generated correctly (above the method)

Document code: Add tree-sitter query for Kotlin

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/src/index.test.ts
lib/shared/src/index.ts
lib/shared/src/models/dotcom.ts
lib/shared/src/models/types.ts
vscode/CHANGELOG.md
vscode/src/edit/prompt/index.ts
vscode/src/edit/utils/edit-models.ts
vscode/src/non-stop/FixupController.ts
vscode/src/non-stop/FixupTask.ts

Fixes an issue where an enterprise instance would have `chatModel` set to something non-claude specific.
We would still override the model, which resulted in weird bugs
Also improves the type safety again, as this seemed to have regressed
1. Connect to an enterprise instance with the `chatModel` set to an OpenAI model
2. Run an edit command
3. Check that it works as expected

Edit: Fix incorrect prompt used for enterprise chat models

---

lib/shared/src/mentions/api.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
vscode/src/context/openctx.ts
vscode/src/context/openctx/remoteFileSearch.ts
vscode/src/context/openctx/remoteRepositorySearch.ts
vscode/webviews/mentions/mentionMenu/MentionMenu.tsx
vscode/webviews/mentions/mentionMenu/MentionMenuItem.tsx
vscode/webviews/promptEditor/nodes/ContextItemMentionNode.ts

Similar to the Sourcegraph Repositories context provider, this PR adds a Sourcegraph Files provider. Which only loads under the `config.experimental.noodle` config flag right now.
But this is not as clean as the previous provider. Searching for files on Sourcegraph without first selecting a repo is not a great experience because a global file search based on file path won't get the desired results. Imagine searching for client.js, there will be 100s of those. 
The OpenCtx protocol does not provide a way to do a two-step selection for multiple items and we do not modify the protocol to introduce the complexity. 
So, in this PR, we are doing a HACK to pull this off. Given this is an internal Cody provider, this should be fine. 
Here is what it does:
1. The provider separates the repoName …

Add Sourcegraph File Context for Enterprise

---

vscode/src/tree-sitter/queries.ts
vscode/src/tree-sitter/queries/rust.ts
vscode/src/tree-sitter/query-tests/documentable-nodes.test.ts
vscode/src/tree-sitter/query-tests/test-data/documentable-node.rs
vscode/src/tree-sitter/query-tests/test-data/documentable-node.snap.rs

Copied from https://github.com/sourcegraph/cody/pull/4355
This PR adds tree-sitter support for getDocumentableNode in Rust.
- Open Rust code
- Move cursor to a position on a documentable node, e.g. a method name
- Document code, expect documentation is generated correctly (above the method)
- Move cursor to a position within a documentable node, e.g. within a method
- Document code, expect documentation is generated correctly (above the method)

Document code: Add tree-sitter query for Rust

---

vscode/src/tree-sitter/queries.ts
vscode/src/tree-sitter/queries/php.ts
vscode/src/tree-sitter/query-sdk.test.ts
vscode/src/tree-sitter/query-tests/documentable-nodes.test.ts
vscode/src/tree-sitter/query-tests/test-data/documentable-node.php
vscode/src/tree-sitter/query-tests/test-data/documentable-node.snap.php

Copied from https://github.com/sourcegraph/cody/pull/4355
This PR adds tree-sitter support for getDocumentableNode in PHP.
- Open PHP code
- Move cursor to a position on a documentable node, e.g. a method name
- Document code, expect documentation is generated correctly (above the method)
- Move cursor to a position within a documentable node, e.g. within a method
- Document code, expect documentation is generated correctly (above the method)

Document code: Add tree-sitter query for PHP

---

lib/shared/src/mentions/query.test.ts
lib/shared/src/mentions/query.ts
vscode/src/edit/input/get-input.ts
vscode/webviews/promptEditor/plugins/atMentions/atMentions.tsx

- Fixes a regression introduced in https://github.com/sourcegraph/cody/pull/4307, which does not allow the use of @-mentions in the Edit code quick-pick menu.
- This PR changes the @-mentions regex to allow spaces in the chat input and disallow them in the quick-pick menu.
Updated unit tests and verified locally.

Edit: fix @-mentions in the quick-pick menu

---

pnpm-lock.yaml
vscode/package.json
vscode/webviews/chat/Transcript.test.tsx
vscode/webviews/promptEditor/PromptEditor.tsx

The current check wasn't exhaustive enough to detect "there is no input". It only checked that no nodes were created ever. But focusing it adds a paragraphNode that is then empty.
I found this pretty good answer on stackoverflow: https://stackoverflow.com/a/75498145 and there's a nice utility method in the @lexical/text package that can check for empty text content, _after_ trimming.
Test plan:
Can no longer submit empty inputs.

vscode: Fixup empty input detection

---

vscode/webviews/mentions/mentionMenu/MentionMenu.tsx

The command menu had an empty section at the end, because the emptyelement doesn't render when any providers are still shown. We thus created an empty CommandGroup.
This restructures it a bit to 
- always render the empty element and the loading element, as they won't show when there's any content
- to only render the second command group when there's actually gonna be entries in it
See the empty section at the end here:
Test plan:
No more empty section at the end.

vscode: Fixup empty section in command menu

---

vscode/test/e2e/common.ts
vscode/webviews/chat/Transcript.test.tsx
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/contextCell/ContextCell.story.tsx
vscode/webviews/chat/cells/contextCell/ContextCell.tsx

In preparation for more context sources, we're renaming them to items. This PR also does a little cleanup of the variable names within the ContextCell component.
Closes CODY-1891
https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/d7743f63-6b06-4ef6-a365-dd73d5a4e56c/d8227344-1a42-44be-8059-380d19eb4240
Test plan:
Screenshot.

vscode: Rename context files to context items

---

vscode/webviews/chat/components/WelcomeMessage.tsx

This reads nicer IMO, it properly indicates which two buttons you're supposed to press.
Before: 
After: 
Test plan: Visual inspection.

vscode: Make keybinding for new chat separate keycaps

---

vscode/package.json
vscode/src/context/openctx.ts
vscode/src/context/openctx/web.ts
vscode/webviews/mentions/mentionMenu/MentionMenuItem.tsx

As the OpenCtx Web provider was enabled by default on the pre-release, we can not just ship it that way and it doesn't belong to the vscode package and all the SOC2 compliance stuff....
This PR imports the Web provider from OpenCtx (as it is) and use it as internal providers similar to Remote Repo & File search providers. 
~This PR also removed the pre-openctx era providers namely github, sg search, URL fetcher. Still keeping the packages one as it has not been migrated to openctx yet and is used by "usage example" command.~
This PR also removes the default value of `openctx.providers` to include the web provider from npm package, because now it is included as an internal provider. 
Closes CODY-1945
Tested manually.

Import OpenCtx Web provider and remove the old ones

---

vscode/.storybook/preview.tsx
vscode/webviews/storybook/VSCodeStoryDecorator.tsx

- Set VS Code theme classes on `body` in Storybook

Storybook: set vscode theme classes on `body`

---

agent/src/__snapshots__/document-code.test.ts.snap
vscode/src/non-stop/FixupController.ts

CLOSE: https://github.com/sourcegraph/jetbrains/issues/1696
This PR fixes the indentation misalignment for text insertions.
Current Process:
1. Get the index of the first non-whitespace character on the line where the insertion point is
2. Split the text into lines and prepend each line with spaces to match the indentation level of the line where the insertion point is
3. Keep the leading whitespace <-`ROOT-CAUSE`
4. Remove trailing whitespace on the last line <- `ROOT-CAUSE`
5.  Insert the updated text at the specified insertionPoint
Since we are already inserting at the "correct" insertion point, the indentation prepended for the first line should be ignored. Or else, we will be inserting the indentation again at the insertion point, causing the issue described in …

Edit: Fix indentation handling for text insertions

---

vscode/src/prompt-builder/utils.ts

By default the context from the openctx providers are appended with the line "Codebase context from file" which is the default template. Adding a check for the openctx providers and only adding the content from the openctx providers.
Manually checked
1. Added a debugger point in the local code to ensure openctx line does not have the default line.

removing the default "codebase context from file <file_path>" line for openctx providers

---

agent/src/index.test.ts

Had to update the snapshot. Didn't re-record
Green CI.

Agent: get tests green again

---

vscode/webviews/mentions/mentionMenu/useMentionMenuData.ts

This PR makes it so that all of
- github
- " GitHub"
- issues
- githubissues
- "GitHub Issues"
match `GitHub Issues`.
Previously, any excessive spaces in the query would cause all providers to not match, and you always had to put in the space. Without requiring all the spaces (but still okay to put them in) it should feel a bit more like a fuzzy finder.
Test plan:
Tim!

vscode: Relax provider search matching

---

vscode/webviews/mentions/mentionMenu/MentionMenu.tsx
vscode/webviews/promptEditor/plugins/atMentions/atMentions.tsx

- Keep the editor query prefix on the @-mention provider selection
1. Open a new chat with OpenCtx enabled.
2. Type a few words and then attempt to select an OpenCtx provider.
3. In the main branch, the chat input will be cleared upon provider selection. In this branch, it should only remove the text after @.

Chat: keep the editor query prefix on the @-mention provider selection

---

vscode/webviews/chat/cells/contextCell/ContextCell.tsx

When we switched the wording from files to items, this number made even less sense than before.
I think this was always a bit confusing as there are often more list items than there are files (because we include multiple chunks) but with the term items this just fell apart completely.
So now we no longer count the unique number of file URIs, but instead just the number of rendered items. For telemetry, I kept it the same for now, as I am scared of skewing any metrics.
Test plan:
Verified locally that the number is now matching the number of list items.

vscode: Fix item count

---

.vscode/settings.json
pnpm-lock.yaml
vscode/package.json
vscode/src/context/openctx/remoteRepositorySearch.ts
vscode/test/e2e/chat-atFile.test.ts
vscode/webviews/mentions/mentionMenu/MentionMenuItem.tsx
vscode/webviews/promptEditor/nodes/ContextItemMentionNode.module.css
vscode/webviews/promptEditor/nodes/ContextItemMentionNode.test.ts
vscode/webviews/promptEditor/nodes/ContextItemMentionNode.ts

This PR:
1. Adds icons to all the mention chips enabled by default namely Files, Symbols, Remote Repositories & Web URL. 
2. Renames Sourcegraph Repositories to Remote Repositories.
3. Updates the label for Symbol mention chips to only show symbol name and not the whole file path as well. 
4. Updates the level for File mention chips to only show file base path.
This PR doesn't update icons for all the other experimental openctx providers yet which are not enabled by default. For all the other providers there is a default DocumentIcon set. 
Closes CODY-1946
Manually tested

Add Icons to Mention chips and update chip labels

---

.github/PULL_REQUEST_TEMPLATE.md

Spotted a broken link. Ideally this shouldn't be pointing at the legacy docs, but that's still better that a 404. I'll update this once I've ported this stuff to Notion. 
n/a, just updating PR template.

chore(dev): fix broken link in PR template

---

vscode/webviews/promptEditor/nodes/ContextItemMentionNode.test.ts

Was about to post a comment over https://github.com/sourcegraph/cody/pull/4393 but it got merged just as I was about to press enter. It's really nothing, but I'm still pushing it as this kind of stuff tend to make the reader scratch their head for a minute when stumbling across it. And I couldn't _unsee_ it 🤣 
PS: _damn those Windows matrix tests are flaky_. 
CI

chore(vscode): simplify test assertion

---

vscode/src/tree-sitter/queries.ts
vscode/src/tree-sitter/queries/c.ts
vscode/src/tree-sitter/query-tests/documentable-nodes.test.ts
vscode/src/tree-sitter/query-tests/test-data/documentable-node.c
vscode/src/tree-sitter/query-tests/test-data/documentable-node.snap.c

Copied from https://github.com/sourcegraph/cody/pull/4355
Part of the effort to add basic tree-sitter support for [the most popular languages.](https://sourcegraph.looker.com/explore/sourcegraph/v2_events?qid=BiIyYwVvQumJeHStxbsOVZ&origin_space=562&toggle=vis)
This PR adds tree-sitter support for getDocumentableNode in C.
- Open C code in the editor
- Move cursor to a position on a documentable node, e.g. a method name
- Document code, expect documentation is generated correctly (above the method)
- Move cursor to a position within a documentable node, e.g. within a method
- …

Document code: Add tree-sitter query for C

---

vscode/webviews/promptEditor/nodes/ContextItemMentionNode.test.ts

The true and false branch are the same value.
Follow up from https://github.com/sourcegraph/cody/pull/4393 and https://github.com/sourcegraph/cody/pull/4394
Test Plan: CI

remove unneccessary windows check in ContextItemMentionNode test

---

vscode/package.json

This command only works when directly clicked on a chat item in the history. So we use the same enablement condition as when it is shown there.
Test Plan: tested renaming chat still works and that it doesn't appear in command pallette

vscode: do not show "Rename Chat" in command pallette

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

Being ruthless with this feature. We will be moving chat history to the backend, synchronizing it, etc. Being able to rename chats will add complexity. We can always add it back once we do all that.
Test Plan: CI. Ran manually and the edit title button was gone.
More context at https://sourcegraph.slack.com/archives/C0748TDGT29/p1717162754194119?thread_ts=1717160259.281599&cid=C0748TDGT29

vscode: remove Rename Chat functionality

---

vscode/src/tree-sitter/queries/cpp.ts
vscode/src/tree-sitter/query-tests/test-data/documentable-node.cpp
vscode/src/tree-sitter/query-tests/test-data/documentable-node.snap.cpp

- Add support for template declarations and struct specializations
- Refine class and struct definitions to better capture symbol and range information
- Remove unused variable and union declaration rules
Updated test to cover template declaration.
Confirm https://github.com/sourcegraph/jetbrains/issues/1728 is fixed:
- Open https://github.com/fmtlib/fmt/blob/master/test/format-test.cc#L2410
- Put cursor somewhere inside template <> struct formatter<convertible_to_cstring> template method.
- Run Document Code
https://github.com/sourcegraph/cody/assets/68532117/296d3188-9f43-4b59-8c3a-c4e11a292c19

Document Code: improve tree-sitter query for c++

---

vscode/CHANGELOG.md
vscode/package.json

VS Code: Release 1.20.0 - Stable Release.
Blog Post: 
- PR: https://github.com/sourcegraph/about/pull/6976
- Preview: https://deploy-preview-6976--sourcegraph.netlify.app/blog/cody-vscode-1-20-0-release

VS Code: Release 1.20.0

---

vscode/CHANGELOG.md
vscode/src/chat/clientStateBroadcaster.ts

By default, the input box for new messages contains @-mention chips for the repos opened in the workspace.
But it doesn't care if the repo is excluded based on Context Filters. 
This PR takes care of that. 
Loom: https://www.loom.com/share/3c7ff06d5b3d4128a1946bd492b4c486?sid=a53e2142-4ec6-4ea1-bdb4-28f5e59fe510

Exclude repos based on Context filters from default mention items

---

agent/src/TestWorkspace.ts

Previously, the CI could fail in the `afterAll` hook for agent integration tests because `fs.rm` would crash on Windows. An example error message:
```
FAIL  |agent| src/document-code.test.ts > Document Code
Error: EBUSY: resource busy or locked, rmdir 'C:\Users\RUNNER~1\AppData\Local\Temp\cody-vscode-shim-testqDezWe\src'
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { errno: -4082, code: 'EBUSY', syscall: 'rmdir', path: 'C:\Users\RUNNER~1\AppData\Local\Temp\cody-vscode-shim-testqDezWe\src' }
```
In this PR, we change the `fs.rm` logic to
- Retry deleting files.
- Log the error if it still fails to delete. This is not a fatal error for the tests.
Green CI, no flaky failures related to `fs.rm`

CI: make tests more stable on Windows

---

vscode/CHANGELOG.md
vscode/test/e2e/chat-messages.test.ts
vscode/test/e2e/common.ts
vscode/webviews/chat/ChatMessageContent.module.css
vscode/webviews/chat/ChatMessageContent.tsx
vscode/webviews/chat/fixtures.ts

These buttons were sometimes not showing on new messages due to the `useEffect` hook not having the right deps.
Fixes that issue and adds an e2e test to ensure the buttons show up and that the copy button copies the right text.
Fixes https://linear.app/sourcegraph/issue/CODY-2014/missing-copyinsert-buttons-on-code-snippets
CI + e2e

fix copy/insert/save code buttons in chat

---

vscode/webviews/chat/ChatMessageContent.tsx
vscode/webviews/chat/cells/messageCell/assistant/AssistantMessageCell.tsx

This avoids many unnecessary guardrails requests while the message is still in progress.
CI, and set logpoint to ensure that the `isMessageLoading` check ensures it's only run at the end of the message being received.

only run guardrails when message is finished loading

---

agent/recordings/document-code_965949506/recording.har.yaml
agent/recordings/edit_1541920145/recording.har.yaml
agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/src/__snapshots__/document-code.test.ts.snap
agent/src/edit.test.ts
agent/src/index.test.ts
vscode/src/edit/prompt/context.ts
vscode/src/edit/prompt/index.ts
vscode/src/edit/prompt/utils.ts
vscode/src/prompt-builder/index.test.ts
vscode/src/prompt-builder/index.ts

- https://github.com/sourcegraph/cody/pull/3307 removed `extractContextItemsFromContextMessages` and replaced it with `isContextItem(value) ? value : value.file` which removes context items content from the final prompt. 
1. Updated and added unit tests
2. Tested locally by triggering the `doc` command on the function in the middle of the file. You should observe document prefix and suffix being added to the prompt in the Cody output channel.

Edit: preserve intent context

---

agent/recordings/document-code_965949506/recording.har.yaml
agent/recordings/edit_1541920145/recording.har.yaml
agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/src/__snapshots__/document-code.test.ts.snap
agent/src/__tests__/document-code/src/TestClass.ts
agent/src/document-code.test.ts
agent/src/edit.test.ts
agent/src/index.test.ts
agent/src/offsets.test.ts
agent/src/offsets.ts
vscode/src/edit/prompt/context.ts
vscode/src/edit/prompt/index.ts
vscode/src/edit/prompt/utils.ts

I [noticed](https://github.com/sourcegraph/cody/pull/4432) that the edit prompt does not contain document suffixes in the agent tests. This is caused by `DocumentOffsets` not handling out-of-bound line numbers like VS Code does. If the line number is out of bound, it results in NaN offset, which causes `document.getText(range)` to return an empty string. This PR fixes it.
- Added unit test
- Updated the doc command unit tests to include long prefix and suffix, which should be present in Polly recordings.

Agent: fix out of bounds document offsets

---

vscode/CHANGELOG.md

- Changelog update for https://github.com/sourcegraph/cody/pull/4432 and https://github.com/sourcegraph/cody/pull/4435
n/a

VS Code: changelog update
