cli/README.md

add installation instructions from the published npm package

---

vscode/CONTRIBUTING.md

improve stable/insiders instructions for publishing and usage

---

vscode/src/chat/ChatViewProvider.ts

remove outdated comment

---

lib/shared/src/test/mocks.ts
vscode/test/completions/completions-dataset.ts
vscode/test/completions/run-code-completions-on-dataset.ts

add MockCompletionsClient, improve run-code-completions-on-dataset

---

vscode/webviews/Login.tsx

"Sign in" is two words

---

vscode/CHANGELOG.md
vscode/package.json

Release v0.6.1

---

vscode/src/chat/ChatViewProvider.ts
vscode/src/chat/protocol.ts
vscode/webviews/Chat.tsx

Noticed this when trying to handle some merge conflicts. 
Types only change. Couldn't find any usage of the token event

Cody: Type webview events

---

lib/shared/src/chat/recipes/fixup.ts
lib/shared/src/chat/recipes/inline-chat.ts
lib/shared/src/chat/recipes/inline-touch.ts
lib/shared/src/chat/recipes/my-prompt.ts
lib/shared/src/chat/recipes/non-stop.ts
lib/shared/src/editor/index.ts
vscode/src/chat/ChatViewProvider.ts
vscode/src/editor/vscode-editor.ts
vscode/src/main.ts
vscode/src/my-cody/MyPromptController.ts
vscode/src/non-stop/FixupController.ts
vscode/src/services/InlineController.ts

make ActiveTextEditorViewControllers optional and improve usage of types

---

vscode/CHANGELOG.md

note in changelog that triggerMoreEagerly defaults to true

---

vscode/src/configuration.ts
vscode/src/main.ts

remove config migration from `completions` to `autocomplete` after ~35 days

---

agent/src/agent.ts
agent/src/index.test.ts
agent/src/protocol.ts
lib/shared/src/chat/client.ts
web/src/App.tsx

We need to be able to verify whether or not the instance has Cody enabled.
Verified locally + all tests pass locally and on CI.

agent: get cody enabled status/version

---

doc/dev/library-development.md

See https://sourcegraph.slack.com/archives/C07KZF47K/p1690414516471369?thread_ts=1689235088.716529&cid=C07KZF47K for additional context.
n/a

fix steps for using cody as a library

---

vscode/CHANGELOG.md
vscode/package.json

release v0.6.3

---

.eslintrc.js
vscode/src/local-context/local-keyword-context-fetcher.ts

- rm duplicate files entry in eslint config
- unexport locals
n/a

minor cleanups

---

vscode/src/completions/providers/unstable-codegen.ts

I've already fixed these in the Hugging Face provider but seems like I also overlooked this in the codegen provider as well. 
👀

Autocomplete: Fix Codegen provider

---

vscode/package.json

remove deprecated VS Code settings that have since been migrated

---

lib/shared/src/chat/recipes/inline-touch.ts
vscode/src/chat/ContextProvider.ts
vscode/src/my-cody/MyToolsProvider.ts
vscode/src/services/InlineController.ts
vscode/test/integration/task-controller.test.ts

Related issues: https://github.com/sourcegraph/cody/issues/332 https://github.com/sourcegraph/cody/issues/360
Not 100% sure these are the fixes, but they are good improvements anyway.
n/a

various possible fixes for `Cannot read properties of null` errors

---

vscode/doc/releases.md

document how to get the Cody insiders release

---

vscode/CONTRIBUTING.md

simpler "fresh user install" steps in docs

---

vscode/src/completions/providers/anthropic.ts
vscode/src/completions/utils.ts
vscode/src/editor/vscode-editor.ts
vscode/src/main.ts

narrow types and imports

---

pnpm-lock.yaml
web/package.json
web/vite.config.ts

remove needless alias for `path` to `path-browserify` in `web`

---

vscode/src/non-stop/FixupScheduler.ts

The browserify packages for `timers` do not implement `refresh`, so this adds a simple implementation of it.
n/a

make FixupScheduler compatible with DOM setTimeout and Node.js setTimeout

---

.github/workflows/ci.yml
vscode/test/integration/api.test.ts

run e2e tests on windows

---

vscode/test/integration/task-controller.test.ts

hack around flaky Fixup Task Controller integration test w/delay

---

vscode/CONTRIBUTING.md

Autocomplete: Add some info on how to access logs

---

vscode/src/completions/index.ts

Two quick fixes for regressions I introduced in #412
- Loading indicator felt flaky so this this PR makes sure we start the indicator a bit earlier and terminate in any case.
- The opt-out for a deletion case was wrong, causing it to skip the condition if the last action was a deletion and there was no cache response. This was not intended to be changed for now. The correct behavior should still be: If there is a deletion, ONLY continue if twe have an exact cache response. Otherwise return no completions. 
- tested locally,

Autocomplete: Fix loading indicator and deletion opt-out

---

vscode/src/log.ts

debug log prefix for readability in output channel

---

completions-review-tool/server.js
completions-review-tool/src/entry.server.tsx
vscode/src/services/telemetry.ts

fix eslint auto-fixable issues

---

vscode/src/completions/testHelpers.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.test.ts

Will be used in multiple files.
n/a

extract completion tag function test helper

---

vscode/src/completions/cache.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/provider.ts
vscode/src/completions/providers/unstable-codegen.ts
vscode/src/completions/providers/unstable-fireworks.ts
vscode/src/completions/providers/unstable-huggingface.ts
vscode/src/completions/request-manager.test.ts
vscode/src/completions/request-manager.ts
vscode/src/completions/shared-post-process.ts
vscode/src/completions/types.ts

mv vscode/src/completions/{index => types}.ts

---

vscode/src/completions/testHelpers.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.test.ts

add documentAndPosition test helper

---

vscode/src/completions/tracer/index.ts
vscode/src/completions/tracer/traceView.ts

support null completion tracer context

---

vscode/src/completions/providers/unstable-fireworks.ts

Autocomplete: Properly handle Fireworks errors

---

vscode/src/completions/providers/unstable-fireworks.ts

We have changed the model name

Autocomplete: Fix Fireworks

---

vscode/CHANGELOG.md
vscode/package.json

VS Code: Release 0.6.4

---

.vscode/settings.json

ignore completion-review-tool data files in search

---

vscode/src/completions/getInlineCompletions.ts
vscode/src/completions/tracer/index.ts
vscode/src/completions/tracer/traceView.ts

- show autocomplete result source and logId in trace view
- show triggerKind in autocomplete trace view
n/a

autocomplete trace view improvements

---

vscode/src/custom-prompts/CommandsController.ts

I was trying to troubleshoot a "too many file watchers" problem and came across some un-disposed file watcher event listeners in CommandsController. This commit fixes that. (It is not the source of the problem I was investigating, but it's a worthwhile fix anyway for future-proofing.)
n/a

dispose of file watcher listeners in CommandsController

---

vscode/src/completions/getInlineCompletions.test.ts

add test case for filtering when there are multiple last-candidate items

---

vscode/src/completions/providers/anthropic.ts
vscode/src/services/test.py

While looking into https://github.com/sourcegraph/cody/discussions/358#discussioncomment-6658645 I noticed some really bad completions. The completions was regularly containing invalid code.
After fixing this line in the prompt, the quality seems to have improved a bit 😬

Autocomplete: Improve Python and Ruby quality

---

vscode/CHANGELOG.md

Adds the changelog entries that were forgotten in #605 and #603
- N/A

VS Cody: Add #605 and #603 to the changelog

---

lib/shared/src/chat/recipes/agent-recipes.ts
lib/shared/src/chat/recipes/browser-recipes.ts
lib/shared/src/chat/recipes/code-question.ts
lib/shared/src/chat/recipes/recipe.ts

Similar to the chat question recipe, but tries to coerce Cody to respond with only code.
Seems to work? What do we do for test plans here?

Add recipe that asks Cody to respond with only code

---

lib/shared/tsconfig.json

rm needlessly included file

---

cli/src/client/completions.ts

rm unused streamCompletions

---

lib/ui/package.json

Release cody-shared v0.0.7 ([version list on npm](https://www.npmjs.com/package/@sourcegraph/cody-ui?activeTab=versions)).
N/A

Release cody-ui v0.0.7

---

README.md
vscode/README.md

This PR includes updates to the repo README as well as the README that feeds the VS Code marketplace page.
Markdown updates only.

Update VSC marketplace + README

---

vscode/README.md

Clarifies some wording around free and Enterprise usage.
- N/A

VS Code marketplace readme clarifications

---

vscode/CHANGELOG.md

changelog: add experimental /symf

---

e2e/src/test-cases/index.ts
e2e/src/test-cases/numpy.ts
e2e/src/test-cases/pytorch.ts

added more e2e test cases

---

vscode/src/custom-prompts/utils/menu.ts

Feedback from @sqs: `Submit Refactor Request only makes sense to us because we know about nonstop`
Let's just keep this as `Refactor` for simplicity
Checked locally

Reword catch-all refactor command

---

agent/src/agent.ts
agent/src/protocol.ts
lib/shared/src/chat/recipes/chat-question.ts
lib/shared/src/chat/recipes/code-question.ts
lib/shared/src/chat/recipes/context-search.ts
lib/shared/src/chat/recipes/custom-prompt.ts
lib/shared/src/chat/recipes/explain-code-detailed.ts
lib/shared/src/chat/recipes/explain-code-high-level.ts
lib/shared/src/chat/recipes/find-code-smells.ts
lib/shared/src/chat/recipes/fixup.ts
lib/shared/src/chat/recipes/generate-docstring.ts
lib/shared/src/chat/recipes/generate-pr-description.ts
lib/shared/src/chat/recipes/generate-release-notes.ts
lib/shared/src/chat/recipes/generate-test.ts
lib/shared/src/chat/recipes/git-log.ts
lib/shared/src/chat/recipes/improve-variable-names.ts
lib/shared/src/chat/recipes/inline-chat.ts
lib/shared/src/chat/recipes/inline-touch.ts
lib/shared/src/chat/recipes/next-questions.ts
lib/shared/src/chat/recipes/recipe.ts
lib/shared/src/chat/recipes/translate.ts
vscode/src/chat/local-code-search.ts

Added titles to recipes. This was the last requirement, everything else was in place.
Tested with the JetBrains client in https://github.com/sourcegraph/sourcegraph/pull/56196

Agent: Make recipes work through agent

---

agent/src/agent.ts

remove debug statement testing agent logging.
run JetBrains extension verify no logging of the event.

Agent: remove debugging log

---

lib/shared/src/chat/recipes/fixup.ts
vscode/src/chat/MessageProvider.ts
vscode/src/custom-prompts/CommandsController.ts
vscode/src/custom-prompts/PromptsProvider.ts
vscode/src/custom-prompts/utils/menu.ts
vscode/src/main.ts
vscode/src/non-stop/FixupTypingUI.ts
vscode/src/services/InlineController.ts
vscode/test/e2e/fixup-decorator.test.ts
vscode/test/e2e/inline-assist.test.ts
vscode/test/e2e/task-controller.test.ts
vscode/walkthroughs/inline-assist.md

This reverts commit cbb0d407c0d32e446cb777520e62e60b3390cdcd.
N/A

Revert "rename /fix command to /edit (#835)"

---

agent/src/jsonrpc.ts

Previously, you had to start a separate process and communicate with stdout/stdin to the use agent. This PR adds a new in-memory API that allows you to use the agent without starting a separate process.
n/a

Agent: add an in-process client

---

lib/shared/src/chat/recipes/inline-chat.ts
lib/shared/src/chat/recipes/recipe.ts
vscode/src/chat/MessageProvider.ts
vscode/src/inline-chat/InlineController.ts

experimental: support setting `fast` model for inline chat

---

vscode/README.md

Adds 2 new gifs to the VS Code README.
README updates only.

Update Cody VS Code README gifs

---

cli/package.json
cli/src/commands/complete/command.ts
cli/src/commands/complete/index.ts
cli/src/program.ts
cli/tsconfig.json
pnpm-lock.yaml
pnpm-workspace.yaml

Experimental `cody complete` subcommand.
n/a; experimental feature only

experimental `cody complete` subcommand

---

vscode/CHANGELOG.md
vscode/package.json

VS Code: Release 0.10.0

---

vscode/test/completions/completions-dataset.ts

Add new tests to the ompletion testing library

add twoNums.ts to completions test

---

vscode/CONTRIBUTING.md

Autocomplete: Document test suite setup

---

vscode/CHANGELOG.md

Forgot to add a changelog entry for https://github.com/sourcegraph/cody/pull/974 😅 
changelog update

changelog update for pull/974

---

vscode/README.md

I opened this small PR to fix a couple small issues on the VS Code marketplace page for Cody:
- 2 of the images were up against one another - I removed one.
- There was some duplicate copy in 2 parts of the page (under "Chat" and "Code graph"), so I updated one section.
README only.

Update VS Code README.md

---

lib/shared/src/sourcegraph-api/completions/browserClient.ts
lib/shared/src/sourcegraph-api/completions/nodeClient.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
vscode/src/fetch.ts

Agent: specify User-Agent in more requests

---

lib/ui/src/chat/Transcript.tsx

also handle edge case where human message not found
Addresses comment: https://github.com/sourcegraph/cody/pull/1005#discussion_r1322223545
Tested locally

transcript: ensure react key uniqueness

---

vscode/package.json
vscode/src/services/AuthMenus.ts

- Follow-up for https://github.com/sourcegraph/cody/pull/1032 based on @toolmantim's comments.

VS Code: sign out cleanup

---

vscode/src/completions/providers/unstable-fireworks.ts

Follow up from https://github.com/sourcegraph/cody/pull/1018#issuecomment-1718477783
👀

Autocomplete: Include \n\r\n as stop sequence for multi-line requests

---

vscode/src/completions/providers/anthropic.ts

noticed this issue while looking at the case issue
This PR fix replacement logic we use for the infill prompt, previously (my bad) we remove the tail from the prefix to reserve the spacing, but this could remove the same code from the earlier part of the prefix.
Example: 
We removed the `//` from earlier part of the code, so it looks incorrect in the request we send to cody, causing cody sometimes reply with unhelpful suggestion
this change makes sure only the last match is removed
now it can generate correct suggestions

fix replace prefix logic for infill prompt

---

agent/README.md

Previously, the agent README was a bit difficult to read and it was
missing useful tips/instructions on how to debug the agent. This PR
fixes the problem by organizing "useful commands" as a table and
adding a new section on "debugging the agent".
n/a

Agent: update contributing docs

---

vscode/CHANGELOG.md
vscode/src/completions/get-inline-completions-tests/post-processing.test.ts
vscode/src/completions/text-processing/process-inline-completions.ts

Autocomplete: Filter out single character completions

---

vscode/package.json

Missing a `config.`
Tested locally

Fix completion trigger enablement

---

vscode/src/services/AuthProviderSimplified.ts
vscode/src/services/OnboardingExperiment.test.ts
vscode/src/services/OnboardingExperiment.ts

Also update a comment based on feedback the language was non-inclusive.
```
pnpm -C vscode test:unit
```

Clean up: Remove lint suppressions from OnboardingExperiment.

---

vscode/src/testutils/mocks.ts

- Implements partial mock for `vscode.workspace.fs`. It's not used anywhere yet.
- Side-effect of working on https://github.com/sourcegraph/cody/pull/1122
CI

VS Code: implement partial `vscode.workspace.fs` mock

---

vscode/CHANGELOG.md
vscode/package.json

Contains bc02e84c8aaa29b89f960f67964075302b568e63 and 6c4e19f4ddecb249c09ab741074c1cbee90a754d
Change log and version change only

VS Code: Release 0.12.1

---

vscode/src/completions/logger.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/unstable-fireworks.ts
vscode/src/completions/providers/unstable-openai.ts
vscode/src/completions/request-manager.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.ts

- Simplifies existing code without any functional changes.
CI

Autocomplete: refactor prep for adding analytics tree-sitter events

---

vscode/CHANGELOG.md

- Adds a changelog item for https://github.com/sourcegraph/cody/pull/1144
N/a

Autocomplete: add changelog item

---

vscode/src/completions/get-inline-completions-tests/last-candidate.test.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/logger.ts
vscode/src/completions/request-manager.ts
vscode/src/completions/reuse-last-candidate.ts
vscode/src/completions/text-processing/process-inline-completions.ts

Closes #1206
https://github.com/sourcegraph/cody/assets/458591/7ef383f2-4ad2-4faf-844e-893c39fed79c

Autocomplete: Accept completions that are forward typed to the end

---

vscode/src/completions/tree-sitter/queries/annotate-and-match-snapshot.ts

- Remove the cursor line from the code sample before parsing them with tree-sitter. This ensures that no unexpected comment nodes are present in the AST. 
CI

Autocomplete: remove cursor line from code samples before running snapshot tests

---

vscode/src/custom-prompts/CommandRunner.ts

update /doc to use current line if no folding range is detected
NOTE: All changes are only added for the /doc command. 
Updated the behavior for the latest /doc command change:
- Check if editor is available before accessing it
- If no selection, try to get folding range for current line 
- If no folding range, use current line range instead
- Update getDocCommandRange to:
- Accept languageId parameter
- __scroll to selection in editor__
- Move to the start of selection line - 5 for visibility
- run /doc in a single line without selection
currently /doc command fails without notification
use current line range
https://github.com/sourcegraph/cody/assets/68532117/78998624-29e1-43a8-af37-da72218204a2

update: /doc use current line when no folding range detected

---

.github/workflows/ci.yml
lib/shared/src/chat/prompts/vscode-context.ts
lib/ui/src/chat/Transcript.tsx
vscode/src/completions/text-processing/utils.ts

Closes #1191
- New tests pass 🤞

Add back support and CI tests for Node 16

---

lib/ui/src/chat/Transcript.tsx

Fix Transcript order

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/main.ts

Merge back the latest changelog to main
just a changelog change

VS Code: Release 0.12.3

---

vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/inline-completion-item-provider.ts

To avoid showing the notice to existing users (who have probably already accepted completions), disable it if there is chat history. In future (when the completion flag has been set for existing users), this extra check could be removed.
Tested with new test via `pnpm test:unit`

Don't show completion notice for existing installs

---

vscode/CHANGELOG.md
vscode/package.json

Just a change log and version change

VS Code: Release 0.14.0

---

agent/src/agent.ts
agent/src/protocol.ts

I still have some more local testing to do, but just wanted to get your initial thoughts on this

agent: start unifying event logging between clients

---

vscode/test/benchmark/env.ts
vscode/test/benchmark/vscode/env.ts

Improves DX. Removed these accidentally when making some changes
Local dev-only command. Checked error appears in console

Benchmark: Add error messages for env

---

lib/shared/src/telemetry/index.ts
vscode/src/completions/logger.test.ts
vscode/src/completions/logger.ts

c.f. https://sourcegraph.slack.com/archives/C05AGQYD528/p1697138659101549
```
█ logEvent (telemetry disabled): CodyVSCodeExtension:completion:accepted {"multiline":false,"triggerKind":"Manual","providerIdentifier":"fireworks","providerModel":"starcoder-hybrid","languageId":"typescript","type":"inline","multilineMode":null,"id":"2d649567-8a1f-45cf-b21a-42cf76f16937","contextSummary":{"local":1,"duration":22.82337498664856},"source":"Network","lineCount":1,"charCount":3,"items":[{"lineCount":1,"charCount":3,"stopReason":"stop"},{"lineCount":1,"charCount":43,"stopReason":"stop"}],"otherCompletionProviderEnabled":false,"otherCompletionProviders":[],"acceptedItem":{"lineCount":1,"charCount":3,"stopReason":"stop"}}
█ logEvent (telemetry disabled): CodyVSCodeExtension:completion:accepted …
```

Autocomplete: Update other providers list

---

vscode/CHANGELOG.md
vscode/package.json

:shipit: 
Just a version change

VS Code: Release 0.14.1

---

agent/src/agent.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/utils.test.ts
vscode/src/jsonrpc/agent-protocol.ts

Fixes https://github.com/sourcegraph/sourcegraph/issues/56929. 
PR to jetbrains: https://github.com/sourcegraph/jetbrains/pull/42
1. Unit tests, CI
2. Manual testing:
1. Checkout these changes 
2. Checkout the corresponding changes in jetbrains repo
3. `runIde` with the local clone of Cody
4. set git remote to `ssh://git@gitlab-my-company.net:20022/path/repo.git`
5. verify that context selection contains `gitlab-my-company.net/path/repo`

Agent: add new `git/codebaseName` request

---

agent/src/editor.ts
lib/ui/src/Chat.tsx
vscode/src/completions/tree-sitter/grammars.ts
vscode/src/fetch.ts
vscode/src/non-stop/FixupController.ts
vscode/src/services/InlineController.ts

Fixes the eslint errors caused by the automatic config upgrade.
CI

DX: fix eslint errors caused by the config upgrade

---

agent/src/agent.ts
vscode/src/jsonrpc/agent-protocol.ts

I was sure I added these changes in the first place to: https://github.com/sourcegraph/cody/pull/1425.
Anyway, I must have missed it somehow. Here they come. 
PR to jetbrains: https://github.com/sourcegraph/jetbrains/pull/42
-  [x] Unit tests, CI
1. Checkout these changes
2. Checkout the corresponding changes in jetbrains repo
3. runIde with the local clone of Cody
4. set git remote to ssh://git@gitlab-my-company.net:20022/path/repo.git
5. verify that context selection contains gitlab-my-company.net/path/repo

Agent: fix `git/codebaseName` request

---

lib/shared/src/prompt/prompt-mixin.ts
vscode/CHANGELOG.md
vscode/package.json

Patch release for p1 bugs
- https://github.com/sourcegraph/cody/pull/1477
- https://github.com/sourcegraph/cody/pull/1440
- Update default prompt mixin
version bump

Cody Patch Release v0.14.2

---

lib/shared/src/telemetry-v2/index.ts
vscode/src/chat/ChatViewProvider.ts
vscode/src/chat/protocol.ts
vscode/src/main.ts
vscode/test/e2e/inline-assist.test.ts
vscode/test/e2e/task-controller.test.ts
vscode/webviews/utils/telemetry.ts

run extension in debug mode
check test eventlogs on dotcom for event emission
check bigquery for event reception

Add secondary telemetry to ChatViewProvider and main

---

.gitignore
vscode/src/graph/bfg/download-bfg.ts

Follow-up to #1511
Manually tested it locally on Windows.

BFG: fix download URL for x64 CPU architecture

---

vscode/CHANGELOG.md

Updating changelog with recently merged PRs.
n/a

VS Code: changelog updates

---

vscode/CHANGELOG.md

Changelog for fix heading styles and inline code colors (#1528)

---

.gitignore

It's painful to have to keep deleting these for a clean git
e2e tests go brrrr

chore: gitignore playwright failure recordings

---

vscode/CHANGELOG.md

For https://github.com/sourcegraph/cody/pull/1376
N/A - Changelog change

chore: Add missing changelog entry

---

vscode/src/completions/create-inline-completion-item-provider.ts

Make manual context option take priority over flags

---

vscode/CHANGELOG.md
vscode/package.json

Version bump and changelog update
New Chat view available behind feature flag

Cody Release v0.14.3

---

vscode/package.json

Version bump.
Include a fix for a disruptive UI bug.

VS Code: Release 0.14.4

---

.github/ISSUE_TEMPLATE/prd-issue.md

Issue template to create user stories based on PRDs 
n/a

Add PRD issue template

---

vscode/src/completions/get-inline-completions-tests/multiline-truncation.test.ts
vscode/src/completions/tree-sitter/queries.ts
vscode/src/completions/tree-sitter/queries/go.ts
vscode/src/completions/tree-sitter/queries/javascript.ts
vscode/src/completions/tree-sitter/queries/python.ts
vscode/src/completions/tree-sitter/query-sdk.test.ts
vscode/src/completions/tree-sitter/query-tests/blocks.test.ts
vscode/src/completions/tree-sitter/query-tests/test-data/blocks.py
vscode/src/completions/tree-sitter/query-tests/test-data/blocks.snap.py

- Adds tree-sitter-powered multiline truncation for Python
- Closes https://github.com/sourcegraph/cody/issues/1635
- Prep for https://github.com/sourcegraph/cody/issues/1453
Added unit tests

Autocomplete: support python multiline truncation

---

agent/src/vscode-shim.ts

Slack thread: https://sourcegraph.slack.com/archives/C059N5FRYG3/p1699032616817709
- `runIde` with a local clone of this revision 
- verify autocomplete works

Agent: Fix autocomplete (FixupController)

---

lib/shared/src/utils.test.ts
lib/shared/src/utils.ts

This PR closes #1572
- Added a test case

Fix Github SSH URL parsing

---

lib/shared/src/configuration.ts
vscode/package.json
vscode/src/completions/providers/createProvider.test.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/services/StatusBar.ts

Minor config change affecting experimental feature

Add a feature toggle for the new search panel

---

vscode/src/completions/tree-sitter/queries/javascript.ts
vscode/src/completions/tree-sitter/queries/python.ts
vscode/src/completions/tree-sitter/query-sdk.ts
vscode/src/completions/tree-sitter/query-tests/intents.test.ts
vscode/src/completions/tree-sitter/query-tests/test-data/intents.py
vscode/src/completions/tree-sitter/query-tests/test-data/intents.snap.py

- Adds Python completion intents powered by tree-sitter
- Closes #1453 
Added Python snapshot tests.

Autocomplete: support python completion intents

---

.github/ISSUE_TEMPLATE/prd-issues.yml

remove blank items so they don't count as being tracked
n/a

remove blank tasklist entries

---

vscode/src/chat/chat-view/ChatPanelsManager.ts

This PR closes #1699 
https://github.com/sourcegraph/cody/assets/44617923/7f358472-955f-408e-9097-49616d477b5b

Chat Panel: Fix chat history view

---

.github/ISSUE_TEMPLATE/prd-issues.yml

fix grammar in prd-issues.yml

---

.github/ISSUE_TEMPLATE/prd-issues.yml

changing to the prefix from `PRD-Issue:` to `PRD:`, I think "Issue" is a bit repetitive as it's already implied in the ticket creation. 
Also removing some fluff in the example to shorten how the examples are rendered in the form preview
n/a

shorten prd example and remove unnecessary prefix

---

vscode/CHANGELOG.md

Adds a missing changelog for https://github.com/sourcegraph/cody/pull/1722
N/A - Docs only change

Docs: Add missing changelog for response time improvements

---

lib/ui/src/chat/TranscriptItem.tsx
vscode/CHANGELOG.md
vscode/package.json

Cody Release v0.16.0

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feedback.yml
.github/ISSUE_TEMPLATE/prd_issue.yml

add additional templates so we can capture feedback from slack and users
n/a

add feedback and bug templates

---

e2e/src/test-cases/embeddings.ts
e2e/src/test-cases/index.ts

Part of [#58403](https://github.com/sourcegraph/sourcegraph/issues/58403)
* Introduce LLM judge test cases that are sensitive to having an embeddings-based semantic-similarity search in Cody's context.
* Run: first with `embeddings` context and then with `keyword` context. Expecting different results of LLM judge.
- When using embeddings both answers are matching expectation (as opposed to none without embeddings).
- When using embeddings 50% of expected facts are missing (as opposed to 100% missing without embeddings).
Test with embeddings context (embeddings for all the repositories under test up-to-date on sourcegraph.com/search):
```
Test 1/2: Embeddings context > Explain repo-updater (github.com/sourcegraph/sourcegraph)
Incorrect or partial answers (LLM judge): 0/1 (0%)
Missing …
```

Embeddings - explain a service in a codebase - 2 tests

---

lib/shared/src/experimentation/FeatureFlagProvider.ts

- Closes https://github.com/sourcegraph/cody/issues/1783
CI

Autocomplete: drop the `syntactic triggers` feature flag

---

vscode/src/completions/artificial-delay.ts

Just some tweaks based on analytics.
- 👀

Autocomplete: Update low performing subset

---

vscode/src/completions/providers/createProvider.ts
vscode/src/completions/providers/fireworks.ts

Autocomplete: Remove extended token window feature flag

---

.gitattributes

Automatically merge CHANGELOG entries on conflict

---

vscode/webviews/Notices/Notice.module.css

Close https://github.com/sourcegraph/cody/issues/1811
UI change, visual testing is required.

[#1811]Added margin for release popup notification

---

vscode/src/services/treeViewItems.ts

Comment from @toolmantim: https://github.com/sourcegraph/cody/pull/1901
Check the copy looks correct :)

Edit: Update sidebar copy

---

vscode/CHANGELOG.md

Always forget 🤦 
N/A - Docs change

Docs: Update changelog for #1883

---

agent/src/vscode-shim.ts

Tested over the week while working on various PRs as part of https://github.com/sourcegraph/jetbrains/pull/140

Agent: flip cody.telemetry.level to 'agent'

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/prompt.ts

When enhanced context is off, no files should be fetched implicitly, including current editor context. Fixes item 1 in #2020.
Test the following queries:

Roll current editor context into enhanced context

---

agent/src/cli/evaluate-autocomplete/testParse.test.ts
lib/shared/src/chat/recipes/inline-touch.ts
lib/shared/src/chat/recipes/recipe.ts
lib/shared/src/editor/index.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/chat/chat-view/LegacyRecipeAdapter.ts
vscode/src/chat/chat-view/SimpleChatModel.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/SimpleChatRecipeAdapter.ts
vscode/src/chat/chat-view/prompt.ts
vscode/test/e2e/history-new-ui.test.ts
vscode/test/fixtures/mock-server.ts

https://github.com/sourcegraph/cody/assets/1646931/eeb77823-6654-4687-a06a-81ef7b5c7169
Test out the commands that output into chat:

make commands work with SimpleChatPanelProvider

---

lib/shared/src/chat/preamble.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/SimpleChatRecipeAdapter.ts
vscode/src/chat/chat-view/prompt.ts

Incorporate Cody preamble into simple chat provider

---

vscode/src/chat/protocol.ts

Link to new Cody feedback URL

---

vscode/test/e2e/history-new-ui.test.ts

Simplifies the new-history-ui e2e test which still occasionally flakes
- N/A

chore: Simplify new-history-ui e2e test to deflake

---

vscode/test/e2e/at-file-context-selecting.test.ts
vscode/test/e2e/history-new-ui.test.ts

Simplifies the @-selection test to make it faster as it's slowing down our e2e tests on macOS
- N/A

chore: Speed up at-file-selection e2e test

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

Fixes https://github.com/sourcegraph/cody/issues/2139

chat: always include selection in enhanced context

---

vscode/CHANGELOG.md
vscode/webviews/ChatCommands.module.css

| - | - |
| <img width="526" alt="Screenshot 2023-12-07 at 3 53 36 pm" src="https://github.com/sourcegraph/cody/assets/153/c7928f43-79a9-4510-9566-96a2797ad586"> | <img width="526" alt="Screenshot 2023-12-07 at 3 51 16 pm" src="https://github.com/sourcegraph/cody/assets/153/c2591452-77b2-4cc3-b822-06b5ebf8c57d"> |
- Started a chat
- Typed /
- Inspected styles

Chat: Improve slash command heading padding

---

vscode/CHANGELOG.md

Add missing changelogs

---

vscode/CHANGELOG.md
vscode/package.json

Patchin' around
Just a version increment.

VS Code: Release 0.18.1

---

lib/ui/src/Chat.tsx

Minor change to the intro text for Cody to clarify that Cody is focused on coding questions, not general world knowledge. 
Copy change only. Tested locally.

Update intro chat message to be clear about coding questions

---

vscode/src/local-context/symf.ts

Fix https://github.com/sourcegraph/cody/issues/1877
See https://github.com/sourcegraph/cody/issues/1877
Note: to reproduce the issue, you may need to quit VS Code from the macOS Activity Monitor.

send sigkill to symf when extension exits

---

vscode/CHANGELOG.md
vscode/package.json

VS Code: Release 0.18.2

---

vscode/CHANGELOG.md
vscode/package.json

Updating the version to prepare a release

VS Code: Release 0.18.4

---

lib/shared/src/experimentation/FeatureFlagProvider.ts

It helps [PLG: Add "Upgrade to Cody Pro" and "Current Usage" settings buttons#149](https://github.com/sourcegraph/jetbrains/issues/149)
* Check if `cody-pro-jetbrains` feature flag is available via `featureFlags/getFeatureFlag` endpoint

Add cody-pro-jetbrains feature flag

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/SimpleChatRecipeAdapter.ts

closes https://github.com/sourcegraph/cody/issues/2300
Re-add `/test` command
Run slash command
Check test is there
Check it works

Commands: Include /test

---

vscode/CHANGELOG.md
vscode/package.json

Bug fix time!!
Waiting for #2305
Just a version increment and change log update.

VS Code: Release 0.18.5

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

This PR closes #2301.
https://github.com/sourcegraph/cody/assets/44617923/7b62a24f-4da6-4dad-ab7e-4433444bc553

Chat: Fix reset recipe

---

.github/workflows/pr-auditor.yml

Update workflow to use new token
Tested in infrastructure repo

update pr-auditor token

---

vscode/CHANGELOG.md

Just adding these for completeness / I didn't want to wait for a re-build on the original PRs :P 
N/A - Docs change

Edit: Update the changelog with a bunch of missed fixes from the last release

---

agent/src/vscode-shim.test.ts

Green CI, including Windows check

Agent: skip file system tests on Windows for now

---

vscode/README.md

Need to remove mention of Free/Pro until GA.
Passing CI

Remove mention of Free/Pro from marketplace

---

vscode/CHANGELOG.md
vscode/package.json

VS Code: Release 0.18.6

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/services/treeViewItems.ts

c.f. https://sourcegraph.slack.com/archives/C05AGQYD528/p1702500830637489?thread_ts=1702483933.499279&cid=C05AGQYD528
After:

Fix code smell icon

---

README.md
doc/dev/index.md

docs: update dev docs to include `pnpm build`

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

set context window limit by model

---

vscode/README.md

Updates to go live for GA. Adds new gif for Custom Commands, info about NLS (with gif), and Cody Free/Cody Pro usage info. 
Passing CI.

[ONLY MERGE FOR 1.0 RELEASE] Update Marketplace README with new gifs, free/pro info, and NLS

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

Lowers limit, verified locally

set more conservative limit for gpt-3.5-turbo to stay under window limit

---

lib/ui/src/chat/ErrorItem.tsx

Small update to the "Start New Chat" button label.
- Viewed context button

Update "Start New Chat" button label casing

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

As the title suggests.
- `sg start` with the openai config from dev-private
- chat with cody

Chat: Honor enterprise token limits

---

vscode/CHANGELOG.md
vscode/package.json

A few token limit related bug fixes.
trivial; just a version change; ci will test

VS Code: Release 1.0.1

---

agent/src/vscode-shim.ts

A fix for https://github.com/sourcegraph/jetbrains/issues/203.
**Note:** we need to update `codyCommit` 
- `runIde` 
- verify no error mentioned by the issue appear in the log

Add missing handlers to vscode-shim

---

vscode/CONTRIBUTING.md

Found a minor issue while setting up debugging on Vscode.
N/A

Fix Debug Instructions

---

vscode/CHANGELOG.md
vscode/package.json

Some bug fixes.
Just a version change, CI will validate.

VS Code: Release 1.0.2

---

README.md

replace link to google form with pricing page

---

vscode/CHANGELOG.md
vscode/package.json

Patch release 1.0.5
version bump

Cody VS Code: Release 1.0.5

---

vscode/CHANGELOG.md

I accidentally added this to the previous released version not unreleased
Not a code change, just fixing changelog

Fix changelog entry

---

vscode/src/completions/get-inline-completions-tests/dynamic-multiline.test.ts

- Closes #1920 by adding unit tests for dynamic multiline completions.
CI + new unit tests

Autocomplete: add unit tests for dynamic multiline completions

---

vscode/webviews/Components/EnhancedContextSettings.tsx

CLOSE https://github.com/sourcegraph/cody/issues/2609
Added functionality to log events when a user interacts with the Enhanced Context toggle within the EnhancedContextSettings component. This is achieved by utilizing the `getVSCodeAPI` method to post messages to the VSCode API, providing insights into the usage of the toggle feature.
- Click on the Enhanced Context toggler
- Check the output channel to see if the click event was logged:
```
█ logEvent (telemetry disabled): CodyVSCodeExtension:useEnhancedContextToggler:clicked VSCode {"properties":{"useEnhancedContext":false}}
█ logEvent (telemetry disabled): CodyVSCodeExtension:useEnhancedContextToggler:clicked VSCode {"properties":{"useEnhancedContext":true}}
```

add: log enhanced context toggle clicks

---

lib/shared/src/chat/recipes/chat-question.ts
vscode/src/chat/chat-view/prompt.ts

remove accidentally committed log

---

lib/shared/src/chat/transcript/transcript.test.ts
lib/shared/src/prompt/templates.ts
vscode/src/chat/chat-view/chat-helpers.ts

fix grammar ("Use { => the} following") in prompt template

---

vscode/CONTRIBUTING.md

More context in [this](https://sourcegraph.slack.com/archives/C05AGQYD528/p1704888961864529) Slack thread. 
N/A: docs update only

docs: fix package extension command

---

vscode/package.json

VS Code: Release 1.1.1 release update
version update

VS Code: Release 1.1.1

---

vscode/doc/ollama.md

- Fixing the doc to be consistent with our default Ollama settings. Thanks @arafatkatze, for catching this!
n/a

Autocomplete: fix ollama doc

---

vscode/src/main.ts

The onDidChangeWindowState was introduced previously to check if the user has left the window to upgrade their account to Cody Pro in their browser when the VS Code window refocuses. 
In v1.1.0, we've updated to use `reloadAuthStatus()` to update the auth status, that caused logging this reload event as login event.  This PR replaced that with `syncAuthStatus(authStatus)` to update the `authStatus.userCanUpgrade` only on windowState change.
This will update the auth status with a userCanUpgrade flag to indicate if the user is eligible to upgrade.
- Check the log to see if login events are being logged on window state change.
- Login event should only be logged once after sign in

update cody pro status when window refocuses

---

vscode/scripts/download-wasm-modules.ts

See discussion: https://sourcegraph.slack.com/archives/C05AGQYD528/p1704969591506399.
CI

fix CI flakes in AutocompleteMatcher.test.ts

---

vscode/src/main.ts
vscode/src/services/AuthMenus.ts
vscode/src/services/InlineAssist.ts
vscode/test/e2e/auth.test.ts
vscode/test/e2e/common.ts
vscode/webviews/OnboardingExperiment.tsx

fix capitalization

---

vscode/src/non-stop/FixupTypingUI.ts
vscode/test/e2e/at-file-context-selecting.test.ts
vscode/webviews/UserContextSelector.tsx

Fixes typo to use correct ellipsis 
Copy change, check UI is correct

Chat/Edit: Fix symbol hint label typo

---

vscode/CHANGELOG.md
vscode/package.json

Fixed the prompt used by the edit command.
version update

VS Code: Release 1.1.3

---

vscode/src/commands/prompt/templates.ts
vscode/src/editor-context/VSCodeEditorContext.ts
vscode/src/editor-context/helpers.ts

rm unused code

---

package.json

show eslint warnings

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/agent.ts
agent/src/index.test.ts
vscode/src/chat/protocol.ts
vscode/src/jsonrpc/agent-protocol.ts

Add tests for:
- select chat model
- reset chat
- edit chat
Callout: introduces a `chat/editMessage` message type, which closely mirrors `chat/submitMessage`
Only adding tests

Add more agent tests

---

vscode/src/local-context/symf.ts

Also removes now-obsolete code to remove an old index root path that has not been used in a while.
CI

symf: clean up node:fs usage in SymfRunner

---

vscode/src/non-stop/codelenses.ts

Part of https://github.com/sourcegraph/cody/issues/2009
Keyboard functionality will be added in a follow up PR
1. Create an edit
2. Observe the code lens on complete

Edit: Update code lens to be more descriptive

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/rateLimitedClient_2043004676/recording.har.yaml
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
lib/ui/src/Chat.tsx
lib/ui/src/chat/TranscriptItem.tsx
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/protocol.ts
vscode/src/commands/CommandRunner.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/edit/manager.ts
vscode/src/main.ts
vscode/src/services/StatusBar.ts
vscode/webviews/App.tsx
vscode/webviews/Chat.module.css
vscode/webviews/Chat.tsx

Main Issue https://github.com/sourcegraph/sourcegraph/issues/58631
Related SourceGraph PR: https://github.com/sourcegraph/sourcegraph/pull/59229
To understand just watch 
1. [Video Description of this PR
](https://www.loom.com/share/ec5fc79db52d401491dfa2674ecf7125?sid=b5de0bc2-fdd2-4a6a-b346-289cd263f011)
2. [How to connect Cody to SG Instance
](https://www.loom.com/share/ec5fc79db52d401491dfa2674ecf7125?highlightComment=27977469&t=230)
1. New UI For Chat
2. New UI for Commands
3. New UI for Autocomplete
Already described in the video

Making the Cody UI configurable by Site Admin

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

Remove the console log I added accidentally in my last commit.
Nothing has changed. All current tests should be passing as expected.

remove redundant console.log

---

.config/viteShared.ts
agent/vitest.config.ts

fix complaint about needing esModuleInterop

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/src/index.test.ts

Updated recordings based on new test user
ci

Agent: Enterprise tests now run using new codytesting user

---

vscode/test/e2e/install-deps.ts

bump vscode test version

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

Address clean-up requests from https://github.com/sourcegraph/cody/pull/2849
Only changes comments

minor cleanup

---

vscode/CHANGELOG.md
vscode/webviews/Components/EnhancedContextSettings.tsx

Clarify how Enhanced Context works, in that it _automatically_ searches for additional code from your _codebase_, and links to https://sourcegraph.com/docs/cody/clients/install-vscode#enhanced-context-selector
| - | - |
| ![CleanShot 2024-01-23 at 15 59 02@2x](https://github.com/sourcegraph/cody/assets/153/e5ca97d3-5759-4ec4-9451-043a6a50bcd7) | ![CleanShot 2024-01-24 at 11 21 07@2x](https://github.com/sourcegraph/cody/assets/153/b6404b9d-a358-4ec8-a4a8-d5bf07167d4a) |
- Clicked the popover
- Verified words

Update the Enhanced Context popover copy and link to docs

---

vscode/CHANGELOG.md

Clarify custom command codebase property removal changelog

---

vscode/src/non-stop/FixupController.ts

see diff
N/A - Removing logging code only

Edit: Remove debug logs

---

.github/ISSUE_TEMPLATE/feedback.yml

make the feedback template less wordy
N/A

cody: change feedback template

---

vscode/src/completions/context/context-mixer.test.ts
vscode/src/completions/context/context-mixer.ts
vscode/src/completions/context/retrievers/jaccard-similarity/jaccard-similarity-retriever.ts
vscode/src/completions/context/retrievers/new-jaccard-similarity/jaccard-similarity-retriever.ts
vscode/src/completions/get-inline-completions.ts

This is the Autocomplete step of my context hardening for Cody Ignore https://github.com/sourcegraph/sourcegraph/issues/59683 
[Document](https://docs.google.com/document/d/1LUNSOuwwhgycfCvqoI3AETS-sDIjCpZknFv2ueQ8Ctw/edit) 
Snippet
Try it in the debugger UI. USe this file for instructions of Cody Ignore https://sourcegraph.com/github.com/sourcegraph/cody@adding-autocomplete-ignore/-/blob/vscode/doc/codyignore.md?L16

Finishing autocomplete Cody Ignore

---

vscode/src/services/AuthProvider.ts

Remove dangling closing bracket

---

TESTING.md

Adds a new TESTING.md file to enable our third party QA testers to walk through VS Code features and functionality. 
**Please note! This flow reflects our [QA plans for the December launch](https://docs.google.com/document/d/15wnVMbZAlU8DOXJKSWlPREaYz0Cuf-8pltips-BetsY/edit) and is certainly out of date.** 
My ask:
- P0: Could feature owners please review and update these flows as necessary? 
- @valerybugakov and @philipp-spiess for autocompletions
- @umpox and @abeatrix for commands
- @toolmantim and @dominiccooney for chat and enhanced context
- P1: As these features continue to evolve, please keep this file up-to-date as you merge PRs. This is what the JB team has been doing, and it's _so_ helpful in terms of alignment and testing. Thank you! cc @kalanchan @beyang to help remind the …

Add QA testing flows 

---

TESTING.md

Update Edit testing instructions to include new features and visual changes
N/A - Docs only

Edit: Update testing instructions

---

TESTING.md

Update testing instructions for core commands and custom commands.
Check the diff

Commands: Update testing instructions

---

vscode/CHANGELOG.md

Add missing changelog entry for https://github.com/sourcegraph/cody/pull/3008
Changelog entry update

add: missing changelog entry

---

TESTING.md

This is a doc-only change. Perform the changed parts of the test plan.

Add VSCode testing instructions for consumer, multi-repo context

---

vscode/src/local-context/download-symf.ts

bump symf version

---

vscode/src/editor/utils/editor-context.ts

Addressing this review comment here  https://github.com/sourcegraph/cody/pull/3093/files#r1484122261
Green CI

Remove "bin/" from search ignore, part 2

---

vscode/src/graph/bfg/download-bfg.ts

BFG version bump.
Tested locally with BFG context enabled.

Autocomplete: bump BFG version

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
vscode/CHANGELOG.md
vscode/package.json

VS Code: Release 1.4.1 - patch release
version bump

VS Code: Release 1.4.1

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
vscode/CHANGELOG.md
vscode/package.json

VS Code: Release 1.4.2 - patch release

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
vscode/CHANGELOG.md
vscode/package.json

VS Code: release v1.4.3 - patch release.
n/a

VS Code: release v1.4.3

---

TESTING.md
vscode/test/e2e/commit-message.test.ts

Fix failing e2e test on windows.
Also updated TESTING.md with the latest command change.
green bots

Test: fix flanky e2e test

---

vscode/test/e2e/command-custom.test.ts
vscode/webviews/App.tsx

Fix the e2e test that's failing on Windows.
Green bots 🙏

Test: fix failed e2e tests

---

vscode/src/commands/services/runner.ts

CONTEXT: https://sourcegraph.slack.com/archives/C05AGQYD528/p1707959968144029
Issue: Currently, we only log custom commands that are chat commands.
This PR updates to send telemetry events for all types of custom commands at execution time.
- Standardize telemetry metadata for custom commands
- Set source to 'custom-commands' when executing custom command
Example log from a custom chat command:
```
█ logEvent (telemetry disabled): CodyVSCodeExtension:command:custom:executed VSCode {"properties":{"mode":"ask","useCodebaseContex":false,"useShellCommand":true,"requestID":"5c269833-d2b4-4ccc-aab9-ce1a4b3414cf","traceId":"bd736337072d4dd44f527deab68537fd"}}
█ telemetry-v2: recordEvent: cody.command.custom/executed: {"parameters":{"version":0,"interactionID":"5c269833-d2b4-4ccc-aab9-ce1a4b3414cf …
```

Telemetry: update logs for custom commands

---

vscode/src/non-stop/codelenses/items.ts

Missed this from https://github.com/sourcegraph/cody/commit/235c64b42c67dc195043f77e5a760ad60d8f4d05

Cody: Fix edit shortcut label style

---

vscode/src/commands/GhostHintDecorator.ts

Sends an event when the ghost text becomes visible.
Fires no more than once every 30 seconds to reduce telemetry spam
1. Make a selection, check that the event is fired
2. Make another selection immediately after, check no event
3. Make a selection after 30 seconds of waiting, check event is fired again

Ghost text: Fire throttled display event

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
vscode/CHANGELOG.md
vscode/package.json

VS Code: Release 1.6.0 - stable release.
Version bump

VS Code: Release 1.6.0

---

vscode/README.md

Updates the README for the latest pricing information
README change only, no testing.

Update VSC README about pricing

---

vscode/doc/ollama.md

Some clarifications from #3074
Just docs change, trivial

Update Ollama docs

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/graph/bfg/spawn-bfg.ts
vscode/src/local-context/local-embeddings.ts
vscode/src/log.ts
vscode/src/services/telemetry-v2.ts
vscode/src/services/telemetry.ts

log chat and fireworks requests

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/agent.ts
agent/src/index.test.ts
vscode/src/jsonrpc/agent-protocol.ts

It fixes https://github.com/sourcegraph/jetbrains/issues/620
Restore chat from history with null model 
(There is automated test in index.test.ts)

`chat/restore`: set default llm for null `modelID` param

---

vscode/package.json

- Document the existing setting to be visible in the extension settings for the insiders build.
n/a

Autocomplete: expose the smart throttle setting

---

vscode/src/completions/get-inline-completions.ts
vscode/src/completions/request-manager.test.ts

- Reduce the adaptive timeout to match latency improvements.
n/a

Autocomplete: reduce the adaptive timeout

---

vscode/test/e2e/chat-input.test.ts

de-flake and reenable `chat input focus` test

---

vscode/test/e2e/context-settings.test.ts

improve context selector a11y e2e test

---

vscode/webviews/App.story.tsx
vscode/webviews/Chat.story.tsx
vscode/webviews/chat/Transcript.story.module.css
vscode/webviews/chat/Transcript.story.tsx
vscode/webviews/chat/components/ChatActions.story.tsx
vscode/webviews/chat/fixtures.ts
vscode/webviews/storybook/VSCodeStoryDecorator.module.css
vscode/webviews/storybook/VSCodeStoryDecorator.tsx

Reduce duplication in the styling of the background (via decorators) and reuse `FIXTURE_TRANSCRIPT`.
CI

clean up vscode storybooks

---

vscode/webviews/index.html

Update the CSP to include data URIs. Fixes an issue with new vite versions. ([Part of Vite 5 breaking changes](https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md#breaking-changes))

Fix sign in icons

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
vscode/CHANGELOG.md
vscode/package.json

VS Code: Release 1.8.1

---

lib/shared/src/chat/fast-path-client.ts
vscode/CHANGELOG.md

Closes #3332 
🤦 
https://github.com/sourcegraph/cody/assets/458591/f6fe0e90-5ce1-4d03-b2c1-7577ecaba031

Chat: Fixes an issue where the abort error was not properly handled in the Claude 3 providers

---

vscode/CHANGELOG.md

- Changelog update for https://github.com/sourcegraph/cody/pull/3392
n/a

Autocomplete: changelog update

---

lib/shared/src/models/dotcom.ts
vscode/CHANGELOG.md
vscode/src/edit/prompt/index.ts

Add Claude 3 to model dropdown

---

lib/shared/src/codebase-context/messages.ts

use interface extends for consistency

---

vscode/CHANGELOG.md

- Changelog updates for merged PRs.
n/a

VS Code: changelog update

---

vscode/src/completions/get-inline-completions-tests/models.test.ts
vscode/src/completions/providers/fireworks.ts

- Do not mutate the StarCoder2 stop sequences array so it doesn't grow in time.
Added unit test

Autocomplete: do not mutate stop sequences array

---

vscode/src/chat/chat-view/context.ts

Add number of results from local embedding search to the trace.

Add # of results from local embedding search to the trace

---

lib/shared/src/models/dotcom.ts
vscode/CHANGELOG.md
vscode/src/edit/prompt/index.ts
vscode/src/models/utilts.ts

Requires https://github.com/sourcegraph/sourcegraph/pull/61272/files
Trivial, just changes the model identifier.

Upgrade GPT 4 Turbo on PLG

---

vscode/test/e2e/chat-atFile.test.ts

remove @-mention URL e2e test (experimental feature)

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/editor/utils/editor-context.ts
vscode/src/editor/utils/findWorkspaceFiles.ts

(CROSSES FINGERS...) Deflakes the @-mention file e2e tests on Windows.
CI

do not cancel throttled findWorkspaceFiles call

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feedback.yml
.github/ISSUE_TEMPLATE/tracking.yml

add tracking issue template and add screenshot suggestion to bug & feedback
N/A

add tracking issue template

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
vscode/CHANGELOG.md
vscode/package.json

- VS Code: release v1.6.1 - patch release.
- Cherry-picked PRs on top of https://github.com/sourcegraph/cody/commit/fbe16e0da400f6fed411530a0aba6bc79562cc11
- https://github.com/sourcegraph/cody/pull/3502
- https://github.com/sourcegraph/cody/pull/3538
- https://github.com/sourcegraph/cody/pull/3549
n/a

VS Code: release v1.10.1

---

agent/recordings/defaultClient_631904893/recording.har.yaml
recordings/symf_3564355686/recording.har.yaml
vscode/src/local-context/symf.test.ts
vscode/src/local-context/symfExpandQuery.ts

https://sourcegraph.slack.com/archives/C05SZB829D0/p1711637157633099?thread_ts=1711634989.767619&cid=C05SZB829D0
1. Run query
2. Check preamble is attached

Symf: Add preamble

---

vscode/webviews/chat/CodeBlocks.tsx
vscode/webviews/chat/ErrorItem.tsx
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/TranscriptItem.tsx
vscode/webviews/chat/components/ChatActions.tsx
vscode/webviews/chat/components/EnhancedContext.tsx
vscode/webviews/icons/CodyLogo.tsx
vscode/webviews/icons/SparkleSlash.tsx
vscode/webviews/utils/icons.tsx

I am not aware of any performance issues that specifically caused us to want to use `React.memo`, and it does not guarantee that a component is not re-rendered, so it can't be counted on for correctness.
CI

remove needless React.memo wrapper

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
agent/recordings/rateLimitedClient_2043004676/recording.har.yaml
lib/shared/src/sourcegraph-api/graphql/queries.ts

fix name for CurrentSiteCodyLlmProvider GraphQL query

---

vscode/webviews/Components/FileLink.tsx
vscode/webviews/chat/components/EnhancedContext.tsx

No need for this to be in a separate file. I forgot to move this when I removed other indirection in #3628.
CI

mv FileLinkProps to FileLink

---

vscode/webviews/Chat.module.css
vscode/webviews/chat/TranscriptItem.module.css

rm unused styles in Chat and TranscriptItem

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
vscode/CHANGELOG.md
vscode/package.json

Finishing the last step of https://github.com/sourcegraph/cody/blob/main/vscode/CONTRIBUTING.md#patch-release
Following https://github.com/sourcegraph/cody/blob/main/vscode/CONTRIBUTING.md#patch-release

VS Code: Release 1.10.2

---

vscode/CHANGELOG.md

Add a missing changelog entry for https://github.com/sourcegraph/cody/pull/3585
Changelog updated for https://github.com/sourcegraph/cody/pull/3585

Add missing changelog entry

---

vscode/webviews/utils/reportIssue.ts

Discovered during QA
Fix issue where Issue Reporter not working
Example issues created from this fix:
https://github.com/sourcegraph/cody/issues/3682
https://github.com/sourcegraph/cody/issues/3681

Remove incorrect field for Issue Reporter

---

.github/workflows/agent-release.yml
agent/package.json

fix path names for agent-release action

---

vscode/src/commands/index.ts

Adds the keybinding to the "Document Code" item in the sidebar
Check keybinding shows

Edit: Add keybinding to sidebar for document

---

vscode/webviews/storybook/VSCodeStoryDecorator.tsx

set noop acquireVsCodeApi in storybooks to avoid ugly console errors

---

agent/package.json

Increase memory space available to agent
Manual QA tests on the jetbrains side

Increase agent heap  memory

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/GetFoldingRangeParams.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/GetFoldingRangeResult.kt
agent/src/agent.ts
vscode/src/jsonrpc/agent-protocol.ts

Testing on the Jetbrains plugin side as it only affects it currently.

Fix agent folding ranges API to use getEditSmartSelection

---

lib/shared/src/models/dotcom.ts
vscode/CHANGELOG.md
vscode/src/edit/prompt/index.ts

Enable GPT4 Turbo

---

doc/dev/quality/index.md

CONTEXT: https://sourcegraph.slack.com/archives/C05AGQYD528/p1712952343200429
This commit adds a new section to the QA dev doc, providing a guide on how to test new LLM models from Google Gemini, Groq, or any OpenAI-compatible APIs in Cody.
Doc update

Doc:  update QA dev guide

---

vscode/src/commands/menus/index.ts

Reported by @umpox here: https://github.com/sourcegraph/cody/pull/3734#issuecomment-2059061854
- Open a new cody tab via the cody command pallete.

PromptString: Fix new chat from cody command pallete

---

lints/safe-prompts.ts

Do not error on `ENOENT` in safe prompt CI check
CI

DX: do not error on `ENOENT` in safe prompt CI check

---

TESTING.md
vscode/CHANGELOG.md
vscode/src/code-actions/document.ts
vscode/src/code-actions/edit.ts
vscode/src/code-actions/test.ts
vscode/walkthroughs/edit.md

Change less commonly used code actions from "Ask Cody to Do Thing" to "Cody: Do Thing"
1. Trigger code actions
2. Check naming correct

Code Actions: Improve labels to be more descriptive

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/index.test.ts

N/A, this is just adding tests

Add simple test for editCommands/code

---

agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
vscode/src/services/AuthProvider.ts

Noticed the waterfall when chatting with @taras-yemets 
- Rely on CI. This is 🔥 code so it's tested.

Run currentUser query in parallel

---

vscode/src/completions/logger.ts

Update the list of other code completion providers.
- Trival, CI will validate.

Update other completion providers list

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/index.test.ts

N/A, this PR just reenabled tests for `editCommand/test`

Reenable tests for editCommand/test

---

vscode/test/e2e/chat-atFile.test.ts

Removed in b5eb7d1e853be69354b0618ce4976ac90d73c58e when flakiness was a bigger problem with e2e tests. I do not think this was actually the culprit.
CI

add back URL mention e2e test

---

vscode/src/tree-sitter/parser.ts

This bundles to the same code and is more standard.
CI

import instead of require for web-tree-sitter

---

lib/shared/src/cody-ignore/context-filters-provider.test.ts
lib/shared/src/cody-ignore/context-filters-provider.ts
lib/shared/src/index.ts
lib/shared/src/sourcegraph-api/graphql/client.ts

- Clarify ignore/exclude everything constants and related helper methods
- Built on top of https://github.com/sourcegraph/cody/pull/3856
- Follow-up for review comments in https://github.com/sourcegraph/cody/pull/3869
- Part of https://github.com/sourcegraph/cody/issues/3641
CI

VS Code: clarify ignore/exclude everything constants

---

vscode/src/services/sentry/sentry.ts

See: https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1713516681123579?thread_ts=1710545289.604959&cid=C04MSD3DP5L
- Trivial/CI

Turn on aggressive sampling for Sentry

---

vscode/src/supercompletions/get-supercompletion.ts
vscode/src/supercompletions/recent-edits/recent-edits-retriever.test.ts
vscode/src/supercompletions/recent-edits/recent-edits-retriever.ts

Supercompletions: Implement context filter

---

agent/recordings/enterpriseClient_3965582033/recording.har.yaml
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/test/e2e/chat-atFile.test.ts
vscode/test/e2e/chat-input.test.ts

CLOSE https://github.com/sourcegraph/cody-issues/issues/25
Right now, we are only logging responses that contain code under `cody.chatResponse/hasCode` event.
This PR adds a new event, `Cody.chatResponse/noCode,` to log responses that do not contain code. 
The main changes are:
- Consolidated Telemetry Events: A single event cody.chatResponse is now used. The event name is dynamically set to hasCode or noCode based on the presence of generated code in the response.
- Simplified Code Structure: The code for logging telemetry events has been streamlined. The countGeneratedCode function is now used to determine if the response contains code, and the result is used to set the event name and properties accordingly.
- Improved Readability: The code has been refactored to improve readability by …

Telemetry: chat responses without code

---

vscode/src/repository/repo-name-resolver.test.ts

Cody Ignore: windows unit test debug

---

agent/src/TestClient.ts
vscode/src/edit/provider.ts
vscode/src/non-stop/FixupController.ts
vscode/src/non-stop/FixupDocumentEditObserver.ts
vscode/src/non-stop/FixupTask.ts
vscode/src/non-stop/codelenses/constants.ts
vscode/src/non-stop/codelenses/items.ts
vscode/src/non-stop/codelenses/provider.ts
vscode/src/non-stop/utils.ts

Conversion of enums to integers and then back to enums in the clients is error prone to off-by-one errors (as it was the case).
Manual integration tests of inline Edit commands in Jetbrains.

Fix CodyTaskState serialization/deserialization issues

---

agent/src/graph-context.test.ts

TSC Graph Context: add more non-snapshot assertions

---

vscode/src/main.ts

Handle cody pro status change on window focus
When the user moves back to the VSCode window after upgrading/downgrading their Cody Pro subscription on the web, the extension now detects the change in their Cody Pro status and reloads the authentication status accordingly.
- Refactored Cody Pro status handling: Instead of setting the userCanUpgrade property on the authStatus object, the code now compares the user's current Cody Pro status (isCurrentCodyProUser) with the fetched status from the GraphQL API (res.codyProEnabled).
- Reload authentication status on Cody Pro status change: If the user's Cody Pro status has changed (e.g., they upgraded or downgraded their subscription), the code now calls the reloadAuthStatus method on the authProvider to reload the authentication status and …

Cody PLG: Reload auth on window focus change

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
agent/scripts/export-cody-http-recording-tokens.sh
agent/src/TestClient.ts
agent/src/__tests__/example-ts/src/ChatColumn.tsx
agent/src/__tests__/example-ts/tsconfig.json
agent/src/index.test.ts
agent/src/testing-tokens.ts
lib/shared/src/models/index.ts

Related CODY-1312
The large unrelated diff should not have happened. I'm planning to fix that separately. It looks like the prompts changed but I would have expected the tests to fail if that was the case.
See new test case.

Inline Edit: add minimized test case for bug report

---

vscode/features.json5

As our features continue to expand across different editors and platforms, it's becoming increasingly important to have a centralized system to track and manage these features. The `features.json5` file will serve as a single source of truth for all the features we've built, their status, and the details of their implementation across different editors. 
**Note:** This is the most basic example of what it _could_ look like, the schema of `features.json5` will continue to be evolved, see [RFC 932](https://docs.google.com/document/d/10dCF0iJlBIf6p3qnGqfBltHDDGVnPYmeT03FeNmmVrg/edit#heading=h.8saknylfr2bz) for more preliminary discussions. 
The tooling to support this across different editors will come afterwards, treat this as a manual process maintained by EPD for now. 
N/A

Introduce a feature JSON tracking system

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
agent/recordings/graph-context-claude-3-haiku-20240307_3262616872/recording.har.yaml
agent/recordings/graph-context-claude-instant-1-2_1248528072/recording.har.yaml
agent/recordings/graph-context-starcoder-16b_352709139/recording.har.yaml
agent/recordings/graph-context-starcoder-7b_2337326201/recording.har.yaml
agent/recordings/rateLimitedClient_2043004676/recording.har.yaml
agent/src/graph-context.test.ts
lib/shared/package.json
lib/shared/src/cody-ignore/context-filters-provider.test.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
pnpm-lock.yaml

CONTEXT: https://sourcegraph.slack.com/archives/C05AGQYD528/p1714664110917129
Check for version number before contextFilter request
Internal: Try connecting to sg04 listed in the linked thread and submit a message with enhanced context enabled

Check for version number before contextFilter request

---

agent/src/agent.ts

1. Remove `cursorMove` which I added - I think incorrectly.
2. Remove caching added by @steveyegge which rollbacks state if we receive empty data from client.
@steveyegge, I would rather stumble on the issues you had before that changes (if they are still there, as code is changing constantly) and then fix them properly on the client side. Adding such caching, where we do not fully understand all edge cases when/why it happens, seems a bit dangerous to me as it can break other things in a subtle way.
Of course I'm open for discussion there, I'm not going to merge this untill we all agree on a way forward.
CC @olafurpg 
This is removal of the code which I think is unnecessary (and I'm not sure if it's already doing anything useful).

Remove caching and unnecessery code from didFocus

---

vscode/src/completions/providers/fireworks.ts

Address https://github.com/sourcegraph/cody/pull/4039/files/b07cb606a6c5fc020012f1e0be70a3717dc54e76#diff-4236ad86f26bb203b040a80dd111451001b68dd322aefa602f5b71857c4d5880
Green CI

Followup to bad merge

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

Summary:
The current implementation for the `Add selection to Cody Chat` is incorrect as it only takes the returned URL from the vscode context menu API into account when retrieving the context from the document, causing the command to always return the whole file rather than a specific range of the file. This PR updates to check if the current editor has selection first, before using the URL to get content from the editor file.
The updated implementation now takes into account the active text editor's selection, which allows for more precise context fetching based on the user's focus.
Changes:
Selection Handling: Added logic to fetch the selection from the active text editor. This selection is then used when fetching context from a URI or directly from the cursor when uri is not …

Chat: Fix editor selection retrieval from context menu

---

vscode/CHANGELOG.md

- Adds changelog for #4031, as forgot to add it in the PR

chore: Add changelog for #4031

---

lib/shared/package.json
lib/shared/src/cody-ignore/context-filters-provider.test.ts
pnpm-lock.yaml

- Closes https://github.com/sourcegraph/cody/issues/4104
- Integrated the test dataset implemented in https://github.com/sourcegraph/sourcegraph/pull/61968
Added new unit tests.

Cody Ignore: integrate shared testing dataset

---

vscode/CHANGELOG.md
vscode/package.json

Build: https://github.com/sourcegraph/cody/actions/runs/9015216734
Diff: https://github.com/sourcegraph/cody/compare/vscode-v1.16.4...vscode-v1.16.5
Tested through https://github.com/sourcegraph/cody/pull/4108

VS Code: Release 1.16.5

---

vscode/CHANGELOG.md

- Adds changelog entry for https://github.com/sourcegraph/cody/pull/4110
N/a

Cody Ignore: git extension changelog entry

---

vscode/src/tutorial/content.ts

From my testing a blank line is fine here, and we don't want to show errors to the user from this file (p is not defined).
1. Open tutorial
2. Check step 1 works as expected

Tutorial: Remove partial code from tutorial

---

vscode/src/services/CharactersLogger.ts

- Trivial change, CI will test

Remove insertion logger from v1 telemetry

---

doc/dev/quality/index.md
lib/shared/src/llm-providers/google/chat-client.ts
vscode/src/completions/nodeClient.ts

update google gemini support (cody.dev.models experimental model provider)

---

lib/shared/src/llm-providers/google/chat-client.ts

With the VS Code setting `"cody.debug.verbose": true` set, and when using the [experimental Gemini support](https://community.sourcegraph.com/t/gemini-1-5-pro-support-experimental-feature/290/12), the `Cody by Sourcegraph` output channel in VS Code will show the full HTTP response body for Gemini API error responses.
Example output in the output channel:
```
googleChatClient: HTTP 400 Error: Bad  body: "{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"API key not valid. ...
```
CI

log errors from Google Gemini API

---

pnpm-lock.yaml
vscode/package.json
vscode/webviews/components/shadcn/ui/combobox.tsx
vscode/webviews/components/shadcn/ui/dialog.tsx

Switch to lucide icon set (from heroicons)

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/index.test.ts
vscode/src/commands/context/directory.ts
vscode/src/commands/context/git-api.ts
vscode/src/commands/context/workspace.ts

This also fixes the Windows unit tests in CI. According to https://github.com/sourcegraph/cody/actions/workflows/ci.yml?query=branch%3Amain, all `main` CI runs including and after https://github.com/sourcegraph/cody/commit/ce072f784a049e44653151961122807638a53224 have been failing on the Windows unit test step.
Also toSorted is not available in Node 18, so we need to use sort still in one other place.
CI

sort directory context files for determinism

---

vscode/CHANGELOG.md

fix incorrect PR link in changelog entry

---

tsconfig.json

add cli subproject to root tsconfig

---

vscode/webviews/storybook/VSCodeStoryDecorator.module.css

use same fonts in storybooks and web

---

vscode/webviews/components/shadcn/ui/button.tsx
vscode/webviews/components/shadcn/ui/dialog.tsx

remove needless shadcn component animations

---

vscode/webviews/Chat.tsx
vscode/webviews/components/EnhancedContextSettings.story.tsx
vscode/webviews/components/EnhancedContextSettings.tsx

remove unused EnhancedContextSettings prop isNewInstall

---

vscode/CHANGELOG.md

add missing changelog entry for https://github.com/sourcegraph/cody/pull/4229
No test required for changelog update.

Update: add missing changelog entry for pr4229

---

vscode/src/completions/logger.ts

See https://sourcegraph.slack.com/archives/C0LJP8WTB/p1715978143995059
- Trivial, CI will test

Update completion provider extension list

---

agent/src/TestClient.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/CHANGELOG.md
vscode/package.json
vscode/playwright.config.ts
vscode/src/completions/logger.ts
vscode/src/local-context/local-embeddings.ts
vscode/src/main.ts
vscode/src/services/UpstreamHealthProvider.ts

Cherry-picked https://github.com/sourcegraph/cody/pull/4091/ (behind feature flag) and https://github.com/sourcegraph/cody/pull/4193 (fixes to code that is already released).
- e2e tests

[vscode] 1.18.1 patch release

---

web/src/index.css

fix web css to use new vscode themes

---

vscode/src/non-stop/tracked-range.test.ts
vscode/src/non-stop/tracked-range.ts

This PR is part of investigations related to https://github.com/sourcegraph/cody-issues/issues/264.
- CI

Fix the range calculation issues & add more tests on tacked range and changes

---

agent/src/agent.ts

There is no way to fix it in the IDE, but there is no sense to fire empty changes notifications.

Fix contentChanges emptines check

---

agent/src/index.test.ts
agent/src/vscode-shim.ts
lib/shared/src/cody-ignore/context-filters-provider.ts
vscode/package.json
vscode/src/context/repo-picker.ts

- Change `Cody Ignore` to `Cody Context Filters` as per [this Slack thread](https://sourcegraph.slack.com/archives/C06Q9R098N4/p1716523545624419?thread_ts=1716523213.929559&cid=C06Q9R098N4).
Manually tested

Cody Context Filters: update labels

---

lib/shared/src/mentions/query.ts

Allow spaces in @-mentions
Tested manually

OpenCtx: allow spaces in mentions

---

vscode/src/commands/execute/test-chat.ts

- Closes https://github.com/sourcegraph/cody-issues/issues/360
- [Fixed by Cody](https://sourcegraph.slack.com/archives/C067XHJ2Y2F/p1716711927079689)
Tested manually

Test Command: error on empty selection

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/MentionParams.kt
lib/shared/src/codebase-context/messages.ts
package.json
pnpm-lock.yaml
vscode/src/chat/context/chatContext.ts
vscode/webviews/mentions/mentionMenu/MentionMenuItem.tsx

- Use `mention.description` if available
- Based on https://github.com/sourcegraph/openctx/pull/94
Tested locally

OpenCtx: use `mention.description` if available

---

agent/src/generate-unit-test.test.ts
vscode/src/non-stop/FixupController.ts

- CI 
- Generate Unit Tests and review the trace (no `-1` lines should be present)

Fix selection range for empty files

---

package.json

Add commands for local openctx dev

---

vscode/src/context/openctx/remoteRepositorySearch.ts

Update "Repositories" to "Sourcegraph Repositories"

---

lib/shared/src/mentions/api.ts
package.json
pnpm-lock.yaml
vscode/package.json

This PR updates the OpenCtx deps to latest version and resolve the breaking changes made to meta result as part of https://github.com/sourcegraph/openctx/pull/103
Tested manually

Upgrade to Openctx client @ 0.0.15

---

agent/src/agent.ts

Agent: remove redundant logs

---

vscode/src/tree-sitter/queries/java.ts
vscode/src/tree-sitter/query-tests/enclosing-function.test.ts
vscode/src/tree-sitter/query-tests/test-data/enclosing-function.java
vscode/src/tree-sitter/query-tests/test-data/enclosing-function.snap.java

Adds support to expand to the nearest enclosing function in Java
Unit tests

Edit: Add Java support for expanding to the nearest enclosing function

---

doc/dev/quality/index.md
vscode/src/completions/nodeClient.ts
vscode/src/models/sync.ts

allow groq and openaicompatible chat models on Cody Free

---

vscode/src/prompt-builder/utils.ts

Revert "removing the default "codebase context from file <file_path>" line for openctx providers"

---

lib/shared/src/llm-providers/groq/chat-client.ts
lib/shared/src/llm-providers/utils.ts

Use the following VS Code settings:
```
"cody.dev.models": [
{
"provider": "openaicompatible",
"model": "janhq/TinyLlama-1.1B-Chat-v1.0-GGUF",
"tokens": 4096,
"apiEndpoint": "http://localhost:1337/chat/completions"
},
]
```
CI

better logging and experimental support for [Cortex](https://jan.ai/cortex)

---

vscode/test/e2e/helpers.ts

If it failed, it probably wouldn't have triggered all the right event logging calls anyway.
Makes reading e2e test failures faster and less confusing.
CI

only run event logging assertions if test passed

---

vscode/playwright.config.ts

shorter e2e timeouts when running locally

---

vscode/webviews/components/ScrollDown.tsx

https://sourcegraph.slack.com/archives/C05AGQYD528/p1717159744497019?thread_ts=1717081935.865579&cid=C05AGQYD528
CI

fix ScrollDown arrow becoming transparent on hover

---

vscode/CHANGELOG.md

Add forgotten change log entry for #4404

---

vscode/src/release.ts
vscode/webviews/Notices/Notices.story.tsx

This is a better explanation of the changes than the comprehensive release notes.
CI

link "Cody updated to v..." notice to blog post

---

vscode/test/e2e/command-core.test.ts

https://github.com/sourcegraph/cody/pull/4424 will help a lot more here.
CI

make explain e2e test slightly less flaky

---

vscode/webviews/chat/cells/messageCell/human/editor/toolbar/SubmitButton.tsx

Fixes https://github.com/sourcegraph/cody/pull/4436#discussion_r1624487011
- CI

Fix incorrect JSX SVG attrs

---

vscode/CHANGELOG.md
vscode/package.json

VS Code: Release 1.20.2

---

vscode/CHANGELOG.md
vscode/package.json
vscode/webviews/chat/ChatMessageContent.tsx

Incorporate https://github.com/sourcegraph/cody/pull/4469
n/a

VS Code: 1.20.3 release

---

vscode/src/minion/blocks/plan-run-step.ts
vscode/src/minion/prompts.ts

https://github.com/sourcegraph/cody/assets/1646931/99259cc9-869f-4c8a-bbc3-da3638bd4245
Add the ability to automatically update the changelog given the feature description
Feature is experimental, behind an experimental feature flag

minion: auto-update the changelog

---

vscode/src/certs.js

When using VS Code Insiders (recent builds of 1.91), Cody extension activation fails during the `win-ca` cert registration. This workaround makes extension activation continue. Users who need these certs on Windows will not be able to use them (and a full fix is needed), but all other users will be able to use Cody on VS Code Insiders again.
- Workaround for https://github.com/sourcegraph/cody/issues/4491
- Workaround for https://community.sourcegraph.com/t/cody-extension-hangs-on-extension-activation-after-installing-latest-can-t-use-it-help-requested/499/4
- Workaround for https://linear.app/sourcegraph/issue/CODY-2176/bug-codys-chat-not-loading-on-latest-vscode-insiders
Run in VS Code Insiders. Confirm the extension activates successfully and prints the `console.warn` message.

workaround for createSecureContext error blocking ext activation in VS Code Insiders

---

vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

rm unused VS Code context key cody.hasNewChatOpened

---

vscode/package.json
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/main.ts
vscode/src/non-stop/codelenses/items.ts
vscode/src/notifications/setup-notification.ts
vscode/src/services/StatusBar.ts
vscode/webviews/components/MarkdownFromCody.tsx

- remove cody.focus alias (use cody.chat.focus)
- remove other unused VS Code commands
CI

remove unused/duplicate VS Code commands

---

vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx
vscode/webviews/components/modelSelectField/ModelSelectField.tsx

add more telemetry for ModelSelectField and HumanMessageEditor

---

vscode/webviews/minion/MinionApp.tsx

Minion was breaking, because there was nothing setting the clientState context, so the call to `useClientState` was throwing an exception (in this case inside the `PromptEditor`).
This change sets an empty clientState, so we can reuse the PromptEditor component in Minion (note: without the actual client state, which will be empty, but that's fine for now because we don't yet need the functionality from the `MentionsPlugin`).
Experimental feature, tested locally.

fix minion

---

vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.story.tsx

Follow up https://github.com/sourcegraph/cody/pull/4534
Update storybook for the component updated in https://github.com/sourcegraph/cody/pull/4534
Check storybook

cstorybook: human message cell with initial large file

---

lib/shared/src/index.ts
lib/shared/src/mentions/api.ts

It was only used locally.
Test Plan: CI

minor: do not export openCtxMentionProviders

---

vscode/CHANGELOG.md
vscode/package.json
vscode/scripts/version-bump.ts

Cody 1.22.1 Patch Release
This patch release includes the following improvements and bug fixes:
Enhancements
Enterprise: Expanded the context window for Gemini 1.5 models.
Bug Fixes
Fixed an issue with hover tooltips on overflowed paths in the @-mention file picker in Chat.
Fixed a bug where creating a new custom command through the menu without an existing cody.json file did not create a new cody.json file with the command added.
Fixed a bug where Ollama models were not connected to the correct client.

VS Code: Release v1.22.1

---

vscode/src/local-context/symf.ts

In unit tests, the `vscode` environment is not fully mocked, so `vscode.CancellationError` is `undefined`. Just use our `AbortError` instead.
Example: https://github.com/sourcegraph/cody/actions/runs/9526461106/job/26261889928?pr=4407#step:9:1806
CI

fix symf instanceof CancellationError test flake

---

README.md
vscode/README.md

Updates "Cody _knows_" messaging across README files.
Also updates outdated portions of the repo README.
Markdown README updates only.

Update README files for Cody messaing

---

lib/shared/src/sourcegraph-api/errors.ts
vscode/src/completions/inline-completion-item-provider.test.ts

fix typo: "all FEATURE" -> "all of your FEATURE"

---

vscode/src/completions/providers/fireworks.ts

Fixed the language identifier for the language specific fine-tuned model
Local testing

fix lang identifier for language specific mixtral model

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/completions/providers/fireworks.ts

VS Code v1.22.3 patch release. This is a release branch PR. Will create a separate one for the main branch.
Updated changelog and package.json.

Hitesh/patch release 1.22.3

---

agent/src/cli/cody-bench/AutocompleteMatcher.test.ts
agent/src/cli/cody-bench/AutocompleteMatcher.ts
agent/src/cli/cody-bench/EvaluationDocument.ts
agent/src/cli/cody-bench/Queries.ts
agent/src/cli/cody-bench/cody-bench.ts
agent/src/cli/cody-bench/strategy-autocomplete.ts

An incomplete implementation of autocomplete evals. Want to merge this now to unblock another PR for chat evals that depend on the diff here.
N/a

Leaderboard: add autocomplete benchmarks

---

vscode/src/non-stop/FixupController.ts

`event.waitUntil` on `onWillSaveTextDocument` supports taking a `void` promise but it does not seem to reliably wait for it.
`event.waitUntil` also supports taking a promise of `TextEdit[]`. It seems it will guarantee the lines will be deleted before the save with this approach/
1. Create many edits
2. Save them
3. Check there's no race conditions between formatters and our manual line deletion

Edit: Fix race condition on save (intended deletions vs formatter)

---

agent/recordings/customCommandsClient_509552979/recording.har.yaml
agent/recordings/document-code_965949506/recording.har.yaml
agent/recordings/edit_1541920145/recording.har.yaml
agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/fix_3001320056/recording.har.yaml
agent/src/__snapshots__/custom-commands.test.ts.snap
agent/src/__snapshots__/document-code.test.ts.snap
agent/src/edit.test.ts
agent/src/index.test.ts
vscode/src/non-stop/FixupController.ts
vscode/src/non-stop/FixupTask.ts

Uses `document.lineAt` to get the end of a line, rather than `Number.MAX_SAFE_INTEGER`.
1. Create edits in JetBrains
2. Undo them
3. Check the undo functions correctly (only original code is returned)

Edit: Fix JetBrains issue with range expansion

---

web/src/agent/shims/fs.ts
web/vite.config.ts

add copyFileSync web shim to fix perma 'Loading...' in web

---

vscode/CHANGELOG.md
vscode/package.json

VS Code: Release v1.24.0

---

agent/src/agent.ts

When a user is not logged in, set the default chat model to the dotcom default model. This is because unauthed users are expected not to have a default model as the model list is only synced on login.
No feature was changed so CI is expected to be green.

Agent: handle missing chat model for unauthenticated users

---

vscode/test/integration/multi-root/workspace.test.ts

See https://sourcegraph.slack.com/archives/C069SENKKRT/p1719952558669169 for an instance of confusion here.
CI

clearer test that Cody doesn't crash but also doesn't support VS Code multi-root workspaces

---

agent/.gitignore
agent/demo/demo.vhs
agent/scripts/record-cli-demo-video.sh

CLI: add VHS script to record demo video

---

vscode/CHANGELOG.md

Important fix and forgot to changelog

Edit: Add changelog for #4720

---

vscode/e2e/utils/vscody/fixture.ts

Test Plan: pnpm run test:e2e2:run on windows
Fixes https://linear.app/sourcegraph/issue/CODY-2677/e2e2-working-on-windows

e2e2: support windows for extension installation

---

vscode/CHANGELOG.md
vscode/package.json

https://docs.google.com/document/d/1wVyOggD1Kib4upxy8Gfqybvx8yyYi6FYyiOmOYvunSg/edit

VS Code: Release v1.26.0

---

vscode/CHANGELOG.md

Update changelog: Re-enable chat in sidebar by default

---

vscode/CHANGELOG.md

Updates changelog to reflect changes made in 1.26.1
Changelog only

VS Code: Release 1.26.1

---

vscode/src/commands/execute/test-chat-experimental.ts

If a prompt is not generated now, we will always throw an error. Previously those errors would only go to Cody Output and be hard to find for the user. So we wrap the call with a try catch so we can report the errors.
Note: Ideally we should only show the button if we have an active document (the easiest failure case). That is for the future.
Test Plan: manually tested with no active document and with an active document.
Fixes https://linear.app/sourcegraph/issue/CODY-2825/generate-unit-test-experimental-should-show-error-when-failing

report to user when Experimental Generate Unit test fails

---

vscode/CHANGELOG.md

1. Add changelog for https://github.com/sourcegraph/cody/pull/4827
2. Add missing PR links

Chore: Update changelog

---

vscode/CHANGELOG.md
vscode/package.json

Build: https://github.com/sourcegraph/cody/actions/runs/9909134079
Diff: https://github.com/sourcegraph/cody/compare/vscode-v1.26.1...vscode-v1.26.2
Tested through PRs:
- https://github.com/sourcegraph/cody/pull/4834
- https://github.com/sourcegraph/cody/pull/4850
- https://github.com/sourcegraph/cody/pull/4827
- https://github.com/sourcegraph/cody/pull/4852

VS Code: Release 1.26.2

---

lib/shared/src/experimentation/FeatureFlagProvider.ts

Noticed these when updating some feature flags
N/A - Deleting unused code

chore: remove unused feature flags

---

vscode/src/services/CharactersLogger.test.ts
vscode/src/services/CharactersLogger.ts

In the previous version, the chars logger didn't account for multiline deletions. It reported one deleted char even if multiple lines were deleted in one go. This PR fixes it by relying more on VS Code API which has `change.rangeLength` field, which can be used to track multiline deletions. See comments added inline that explain its behavior.
Updated unit tests.

Autocomplete: chars logger account for multiline deletions

---

vscode/src/chat/chat-view/ChatController.ts

Improves readability of the `handleUserSubmission` method.
No functional changes, simple refactor

factor out very long telemetry event

---

vscode/src/completions/providers/google.ts

Minor refactor: This PR  introduces new markers object for the Gemini model's prefix, suffix, and response in the Google autocomplete provider. The `RESPONSE_CODE` constant has been replaced with a `MARKERS` object that defines these new markers. The code that generates the prompt and handles the response has been updated to use these new markers for consistency and clarity.
Just refactoring the hardcoded markers into an object. No feature behaviour was changed.

Autocomplete: minor refactor markers in Gemini model

---

vscode/CHANGELOG.md

Changelog update for https://github.com/sourcegraph/cody/pull/4865
n/a

Autocomplete: changelog

---

agent/src/cli/command-chat.ts

Fixes CODY-2658
Previously, it was only possible to pass the chat message through the explicit `--message` or `-m` option. This PR adds several new ways to pass the chat message:
- Via arguments. Example: `cody chat explain react hooks`.
- Via stdin with `--stdin` option or `-` argument. Example: `git diff | cody chat --stdin --message 'summarize this diff'`
Manually tested these commands
```
echo 'respond only with hello' | cody chat -
echo 'respond only with hello' | cody chat --stdin
git diff | cody chat --stdin --message 'summarize this diff'
git diff | cody chat --message 'summarize this diff' -
cody chat --message 'what files changed' $(git show --name-only) 
```

CLI: add more flexible message construction for `chat` command

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/WebviewMessage.kt
agent/src/TestClient.ts
agent/src/cli/command-bench/strategy-chat.ts
agent/src/cli/command-chat.ts
agent/src/index.test.ts
lib/shared/src/lexicalEditor/editorState.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatsController.ts
vscode/src/chat/protocol.ts
vscode/src/code-actions/explain.ts
vscode/src/commands/execute/ask.ts
vscode/src/commands/execute/explain-history.ts
vscode/src/commands/execute/explain.ts
vscode/src/commands/execute/smell.ts
vscode/src/commands/execute/terminal.ts
vscode/src/commands/execute/test-chat.ts
vscode/src/commands/menus/index.ts
vscode/src/commands/services/runner.ts
vscode/test/integration/single-root/chat.test.ts
vscode/webviews/chat/Transcript.tsx

This reverts commit b05aedd6a3f0660601f3535d8040e93fcc3a6bd0 - will use a better solution.
N/A

Revert "Exclude context chips from the query text (#4920)"

---

lib/shared/src/lexicalEditor/editorState.ts
vscode/CHANGELOG.md
vscode/package.json
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

Patch release with a fix for chat context.
The changelog and the VS Code extension versions are updated.

VS Code: Release v1.26.5

---

.github/PULL_REQUEST_TEMPLATE.md

Prepping our PR templates to implement changelog automation ([notion page](https://www.notion.so/sourcegraph/Writing-a-changelog-entry-dd997f411d524caabf0d8d38a24a878c)) soon
N/A

Update PR template with optional changelog entry

---

vscode/src/completions/inline-completion-item-provider-e2e.test.ts

Previously the tests were not correctly checking that the `read` parameter was set to the correct value.
This PR updates the tests to do that
Tests only - CI should pass

Autocomplete: Improve inline completions tests

---

vscode/CHANGELOG.md
vscode/package.json

VS Code: Release v1.28.0

---

vscode/CONTRIBUTING.md

Based on a recent tip shared in slack.
Test Plan: n/a

vscode: contributing tip around using mitmproxy

---

lib/shared/src/lexicalEditor/editorState.ts

We implemented a pre-order walk using a queue 4 times. This factors out the common logic into a function `forEachPreOrder`. Additionally in two of the cases we did filtering, so we also introduce the helper `filterLexicalNodes`.
Note that we use recursion instead of a queue. We don't have deep trees to recurse. I believe previously we used a queue just because it was more convenient due to the function signature. But now it is easier (and clearer I think) to use recursion.
Test Plan: call sites are covered by tests.

chat: factor out helpers over SerializedLexicalNode 

---

vscode/webviews/icons/LLMProviderIcons.tsx

fix react warning on prop name stop-color (--> stopColor)

---

vscode/webviews/components/modelSelectField/ModelSelectField.module.css
vscode/webviews/components/modelSelectField/ModelSelectField.tsx
vscode/webviews/components/shadcn/ui/badge.story.tsx
vscode/webviews/components/shadcn/ui/badge.tsx
vscode/webviews/tailwind.config.mjs

use shadcn badge component

---

README.md

update readme to mention Claude 3.5 Sonnet

---

vscode/webviews/components/shadcn/ui/tabs.tsx

pass along forwardRef's ref arg

---

vscode/src/chat/chat-view/ChatController.ts

rm accidental console.log

---

lib/prompt-editor/src/index.ts

export some more useful things from @sourcegraph/prompt-editor

---

vscode/webviews/Chat.story.tsx
vscode/webviews/chat/components/WelcomeMessage.tsx

update Chat Help

---

vscode/webviews/chat/components/CustomCommandsList.tsx
vscode/webviews/chat/components/DefaultCommandsList.tsx
vscode/webviews/chat/components/WelcomeMessage.test.tsx
vscode/webviews/chat/components/WelcomeMessage.tsx
vscode/webviews/components/CollapsiblePanel.tsx
vscode/webviews/tabs/CommandsTab.tsx
vscode/webviews/tabs/HistoryTab.tsx

This makes the chat empty state less noisy.
View chat empty state

collapse chat empty state Chat Help and Commands by default

---

.vscode/launch.json
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
vscode/src/chat/context/contextAPIClient.ts

Use https://github.com/sourcegraph/sourcegraph/pull/64172 in Cody
- code behind a feature flag

Fetch ranker relevance scores from GraphQL

---

vscode/src/editor/utils/editor-context.ts

Previously, when using `@-file` mentions for common filenames in the repo, the ordering of the results wasn't personalised meaning the top result could be a random file (for example, a short file path) instead of a file that the user has open in their editor. This PR adds basic customization where we boost candidates that the user has open in their editor.
Open local build of cody in the sourcegraph repo. Open a file named `openai.go` which is not in cody-gateway, open another file named something else. Open chat and type `@openai.go` and confirm that the top result is the `openai.go` that you have open instead of the one in cody-gateway. Confirm that you can optionally type a space character and `cody-gateway` to narrow the filter to boost the cody-gateway result to the top.
Before
After …

Chat: boost `@-file` mentions for open documents

---

agent/scripts/generate-agent-kotlin-bindings.sh

faster kotlin bindings regeneration

---

biome.json
vscode/test/fixtures/mock-server.ts

do not ignore mock-server.ts in biome

---

web/CONTRIBUTING.md

Cody Web: Add contributing.md to cody web package

---

vscode/src/editor/utils/findWorkspaceFiles.ts

findWorkspaceFiles return value is reused and should not be mutated

---

lib/prompt-editor/package.json
lib/shared/package.json

bump lib versions for publishing

---

vscode/src/chat/chat-view/ChatsController.ts
vscode/test/e2e/chat-history.test.ts
vscode/test/e2e/command-core.test.ts
vscode/webviews/App.tsx
vscode/webviews/CodyPanel.tsx
vscode/webviews/tabs/TabsBar.tsx
web/lib/components/CodyWebPanel.tsx
web/lib/components/CodyWebPanelProvider.tsx

In the Cody Web demo (`pnpm -C web dev`), try the New Chat and Clear History actions.

fix web/demo New Chat and Clear History actions

---

vscode/src/testutils/mocks.ts

Check if JetBrains Edit Code works again with this change.

Fix unimplemented range contains check

---

web/lib/agent/shims/child_process.ts

export os.exec in child_process shim to fix web build

---

vscode/CHANGELOG.md
vscode/package.json

VS Code `v1.30.0` release gogog!
[blog post](https://github.com/sourcegraph/about/pull/7125)
N/A

VS Code: Release v1.30.0

---

vscode/webviews/chat/ChatMessageContent.tsx

Add a tooltip with the full file path to the smart apply UI
Helps a lot with debugging, and also a useful feature anyway. TODO: Use better tooltips here
1. Hover a file name in a code block
2. View full file path

Smart Apply: Add title tooltip with full file path

---

vscode/CHANGELOG.md
vscode/package.json

Patch release follow-up based on https://github.com/sourcegraph/cody/blob/main/vscode/CONTRIBUTING.md
version/CHANGELOG only
Autocomplete: Experiment flag for deepseek context increase experiment. [pull/5159](https://github.com/sourcegraph/cody/pull/5159)

bump version and add changelog

---

vscode/CHANGELOG.md
vscode/package.json

https://github.com/sourcegraph/cody/actions/runs/10341068260

VS Code: Release 1.30.3

---

vscode/src/chat/chat-view/ChatController.ts
vscode/src/edit/manager.ts
vscode/src/edit/smart-apply.ts
vscode/src/services/utils/codeblock-action-tracker.ts
vscode/test/e2e/chat-messages.test.ts
vscode/webviews/chat/ChatMessageContent/ChatMessageContent.module.css
vscode/webviews/chat/ChatMessageContent/ChatMessageContent.tsx
vscode/webviews/chat/ChatMessageContent/create-buttons.ts

**Happy path**
**Happy path 2**
**Unhappy path**
**Squashed UI Example**
1. Trigger a chat message on an enterprise Cody setup
2. Check that the smart apply UI appears correctly alongside guardrails
3. Check the applying the smart apply works well

Smart Apply: Update model choice and UI to support enterprise

---

vscode/CHANGELOG.md

These changes are not yet released, and will be in the next release
N/A - Changelog copy change only

chore: Fix incorrect changelog items

---

vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ContextRetriever.ts

This change only affects chat context retrieval when `"cody.internal.serverSideContext": true`
Fixes an issue where @-mentioning files or symbols alone would cause an error, because these @-mentions were not resolved.
Test locally

fix errors in new context retrieval code

---

.github/workflows/ci.yml

Attempt to fix this error on main where the command to set env var on Windows are different on Windows:
Green CI?

Test: fix e2e test run step for Windows

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/SerializedChatTranscript.kt
agent/src/index.test.ts
lib/shared/src/chat/transcript/index.ts
lib/shared/src/chat/transcript/messages.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatModel.ts
vscode/src/services/LocalStorageProvider.test.ts
vscode/src/services/LocalStorageProvider.ts

remove long-deprecated chatModel field and migration code

---

lib/shared/src/index.ts
lib/shared/src/sourcegraph-api/environments.ts
vscode/src/services/AuthMenus.ts
vscode/src/services/AuthProvider.ts

This has not been used for ~9 months.
CI

rm handling of long-removed App URLs

---

agent/src/agent.ts
agent/src/cli/command-bench/command-bench.ts
agent/src/edit.test.ts
lib/shared/src/index.ts
lib/shared/src/llm-providers/clients.ts
lib/shared/src/llm-providers/utils.ts
lib/shared/src/models/index.test.ts
lib/shared/src/models/index.ts
lib/shared/src/models/utils.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatModel.ts
vscode/src/chat/chat-view/prompt.test.ts
vscode/src/commands/scm/source-control.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/edit/input/get-input.ts
vscode/src/edit/manager.ts
vscode/src/edit/prompt/index.ts
vscode/src/edit/prompt/smart-apply.ts
vscode/src/edit/provider.ts
vscode/src/main.ts
vscode/src/models/modelMigrator.ts
vscode/src/models/sync.test.ts
vscode/src/models/sync.ts

Just a code cleanup to make it more consistent. Also will help with https://linear.app/sourcegraph/issue/CODY-3332/full-native-offline-mode-and-instant-config-reactivity-for-cody-in-vs.
CI

make ModelsService a singleton instance, not static

---

vscode/src/chat/chat-view/ChatsController.ts

The current logic to clear chat history using the "clear-all-no-confirm" as the ChatID exists for Cody Web, but the current implementation does not work because right now, we check for `if (chatID)` and exist early if true, which will always be true when the client passes `clear-all-no-confirm` as the chatID here.
The changes fix an issue where the "clear-all-no-confirm" chat ID was being treated as a single chat ID instead of clearing all chat records. The updated implementation correctly handles the "clear-all-no-confirm" case that would clear all chat history without requiring user confirmation.
All CI tests should be green. 
1. In VS Code, go to chat history and click Clear Chat History in the History Tab
2. Verify a window pop-up shows up and asks you for confirmation
3. Start this …

Agent: fix issue with clearing chat history

---

lib/shared/src/models/dotcom.ts

Fixes https://linear.app/sourcegraph/issue/CODY-3378/simplify-chat-model-dropdown
whatever models are configured for them.
CI

recommend only Claude 3.5 Sonnet for now

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/CodyAgentClient.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/SaveDialogOptionsParams.kt
agent/src/vscode-shim.ts
vscode/src/jsonrpc/agent-protocol.ts

- test with https://github.com/sourcegraph/jetbrains/pull/2040

Add SaveDialogOptionsParams

---

lib/shared/src/mentions/api.ts
lib/shared/src/models/dotcom.ts
lib/shared/src/models/index.ts
lib/shared/src/models/tags.ts
vscode/test/e2e/chat-input.test.ts
vscode/webviews/components/modelSelectField/ModelSelectField.tsx

cleaning up models and names

---

vscode/webviews/themes/visual-studio.css

This commit updates the Visual Studio theme for webviews:
- Removes custom scrollbar styles for `.model-selector-popover` elements, aligning with the default Visual Studio experience.
- Defines missing color variables for input validation and active options, enhancing consistency with the Visual Studio theme.
- Commented out variables that are currently not used.
These changes improve the overall visual fidelity and consistency of the webview themes.
Green UI - simple UI change.

Chat: remove unused variables for Visual Studio

---

README.md

docs: update twitter handle label from un-capitalized sourcegraph to capitalized Sourcegraph

---

vscode/src/completions/fast-path-client.ts
vscode/src/completions/providers/fim-prompt-utils.ts
vscode/src/completions/providers/fireworks.ts

1. Cleaned unused fireworks models, earlier introduced for experiments
2. No functional change
CI

remove unused models

---

lib/prompt-editor/src/mentions/mentionMenu/MentionMenu.tsx
lib/shared/src/index.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
pnpm-lock.yaml
vscode/package.json
vscode/src/chat/clientStateBroadcaster.ts
vscode/src/context/openctx/common/get-repository-mentions.ts
vscode/src/context/openctx/remoteDirectorySearch.ts
vscode/src/context/openctx/remoteFileSearch.ts
vscode/src/context/openctx/remoteRepositorySearch.ts
vscode/test/e2e/mention-repository.test.ts
web/CHANGELOG.md
web/lib/components/CodyWebPanel.tsx
web/package.json

Closes CODY-3370
Fixes CODY-3372
This PR brings search mentions results closer to the Sourcegraph search experience (search API feels a bit faster and we also include fuzzy ranking similar to what we do in Sourcegraph search-box UI) 
- Check that all mention flows that require repositories mentions (such as repositories, files and directories) work properly

Improve repository mention search

---

vscode/src/local-context/symf.ts

fix bug where chat hangs if no changes since last symf index

---

vscode/src/context/openctx.test.ts
vscode/src/context/openctx.ts

Just testing current state.
CI

add simple unit test for getOpenCtxProviders

---

web/lib/components/use-cody-agent.ts

Regression since I fixed it here https://github.com/sourcegraph/cody/pull/5293/files
Fixes CODY-3375
Fixes CODY-3376
- Run Cody demo 
- Check that after you type @<search term> the file search is restricted to the initial repo (in demo this repo is cody repository)

Always set initial context when you create new chat for Cody Web

---

web/lib/components/use-cody-agent.ts

I've noticed that Cody Web wrappers over cody agent work with race conditions sometimes, this happens because in dev mode react fires useEffect twice and this breaks code agent internal states and handling order (twice init actions case clears active panel IDs for example)
This PR adds init flags to avoid this problem when you run pnpm dev; it should have no effect on the production build, though. 
- Run Cody Web demo and check that you still can submit the message

Cody Web: Fix Cody Web wrapper in dev mode

---

vscode/src/local-context/local-embeddings.ts

This code was not being used.
CI

rm unused local embeddings onChange

---

vscode/src/completions/nodeClient.ts

Logging and error message changes. Test locally.

on empty chat streaming response, log span and trace id

---

lib/prompt-editor/src/mentions/mentionMenu/MentionMenu.tsx

Updated labels for Cody 
- Open Cody
- Select Remote Directories 
- Check for updated labels.
- Update Remote Directory labels.

Update Remote Directory Labels

---

vscode/CHANGELOG.md
vscode/package.json

VS Code `v1.34.0`! We'll also be changing the blog post to https://sourcegraph.com/changelog?topics=VS+Code
version bump

VS Code: Release v1.34.0

---

agent/src/agent.ts

N/A, rollback of previously commited changes.

Remove workspace check which fails JB tests

---

vscode/CHANGELOG.md
vscode/package.json

VS Code: Release v1.34.1

---

vscode/src/completions/inline-completion-item-provider-e2e.test.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/services/LocalStorageProvider.test.ts

Use the other existing fixture.
CI

rm needless DUMMY_AUTH_STATUS fixture

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ClientCapabilities.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ContextMentionProviderID.kt
lib/shared/src/index.ts
lib/shared/src/mentions/api.test.ts
lib/shared/src/mentions/api.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/context/chatContext.ts
vscode/src/jsonrpc/agent-protocol.ts
web/lib/agent/agent.client.ts

N/A, unittests should pass.
When it will get adopted in JetBrains test plan will be as follow: 
https://github.com/sourcegraph/cody/pull/5384

Add option to disable ctx providers

---

README.md

Manually check newly added links

Clean up README - clean up links, add an up-to-date demo video, and clean up typos

---

vscode/src/completions/get-inline-completions-tests/analytics.test.ts

No functional changes. Fixing incorrect test labels found by @sqs.
Check that the updated test labels make sense.

Autocomplete: fix test labels

---

vscode/CHANGELOG.md
vscode/package.json

VSCode Release 1.34.3
update changelog and version

VS Code: Release 1.34.3

---

vscode/src/local-context/symf.test.ts

skip flaky symf parallel downloads test

---

lib/shared/src/experimentation/FeatureFlagProvider.test.ts
lib/shared/src/misc/observable.ts

make readValuesFrom readonly to avoid misuse

---

agent/src/cli/command-auth/AuthenticatedAccount.ts
agent/src/cli/command-auth/command-accounts.ts
agent/src/cli/command-auth/command-whoami.ts
agent/src/cli/command-bench/strategy-chat-context-types.ts
agent/src/cli/command-bench/strategy-unit-test.ts
agent/src/cli/command-chat.ts
agent/src/cli/command-context/command-context.ts
lib/prompt-editor/src/PromptEditor.tsx
lib/prompt-editor/src/mentions/mentionMenu/useMentionMenuData.ts
lib/prompt-editor/src/plugins/atMentions/atMentions.tsx
lib/shared/src/cody-ignore/context-filters-provider.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/url.ts
vscode/src/chat/chat-view/ChatHistoryManager.ts
vscode/src/chat/chat-view/ChatModel.ts
vscode/src/chat/chat-view/ContextRetriever.ts
vscode/src/chat/chat-view/InitDoer.ts
vscode/src/commands/services/custom-commands.ts
vscode/src/completions/context/retrievers/cached-retriever.ts
vscode/src/completions/context/retrievers/lsp-light/lsp-light-retriever.ts
vscode/src/completions/get-inline-completions-tests/analytics.test.ts
vscode/src/completions/get-inline-completions-tests/post-processing.test.ts
vscode/src/completions/text-processing/utils.ts
vscode/src/configuration-keys.ts
vscode/src/context/remote-search.ts
vscode/src/services/LocalStorageProvider.ts
vscode/src/tree-sitter/query-sdk.ts
vscode/src/tree-sitter/query-tests/annotate-and-match-snapshot.ts
vscode/webviews/chat/Transcript.tsx
vscode/webviews/components/codeSnippet/components/Code.tsx

```
fastmod -e ts,tsx "import \{ (\w+) \} from 'lodash'" "import \$1 from 'lodash/\$1'"
```
CI

use lodash individual imports for better tree-shaking, smaller bundles

---

vscode/src/local-context/local-embeddings.ts

The local embeddings service was not actually being used for enterprise (non-dotcom), but the class was being instantiated and an error message `local embeddings are only available on Sourcegraph.com` would show up in the output channel for enterprise users.
Sign into s2 or another enterprise instance and confirm that there is no such error in the output channel and a breakpoint set in `LocalEmbeddingsController`'s constructor is never hit.

do not even instantiate LocalEmbeddingsController for non-dotcom

---

.vscode/launch.json
agent/src/index.test.ts

remove 2 unintentional or noisy dev console logs

---

vscode/src/commands/scm/source-control.ts

This is a rare edge case, but one that should be handled by the type system.
CI

handle no models available in CodySourceControl

---

vscode/src/main.ts

Fixes an issue where the auth was not yet available during init, so `evaluateFeatureFlag` could not be called in Cody Web (which supplies creds after initialization). Also makes it so that an editor reload is not necessary to pick up an updated value for this feature flag. (I will remove the `evaluateFeatureFlag` method because it is hard to think of a situation where you only want to read a feature flag's value at a given instant and not watch its value.)
n/a

make unified prompts feature flag reactive

---

vscode/webviews/chat/cells/contextCell/ContextCell.tsx

When there are 0 items in the context, instead of saying "0 items", it should say "fetching..."

---

agent/recordings/auth_2503977039/recording.har.yaml
agent/recordings/cody-chat_103640681/recording.har.yaml
agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
agent/src/auth.test.ts
agent/src/cli/__snapshots__/command-chat.test.ts.snap
recordings/rewrite-query_2689977722/recording.har.yaml
vscode/src/testutils/testing-credentials.ts

Rotate s2 token for agent recordings
N/A

Agent: update access token for integration tests

---

vscode/webviews/App.story.tsx
vscode/webviews/AppWrapperForTest.tsx

Fixes 2 issues that caused the App and Chat storybooks to not render.
n/a

fix storybook

---

vscode/src/auth/auth.ts

Update the accounts separator label from "current" to "account history" for cases where the top endpoint is not always the current one in the Quickpick for switching accounts.
I also did some minor code cleanup for readability.
Closes https://linear.app/sourcegraph/issue/CODY-3896/switch-account-quickpick-incorrectly-marks-current
Open the Switch Account QuickPick to confirm the "current" separator has been updated to "account history"

Auth: Update separator label for endpoint history

---

vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/chat-helpers.ts
vscode/src/chat/protocol.ts
vscode/src/services/utils/workspace-action.ts
vscode/webviews/chat/ErrorItem.tsx
vscode/webviews/chat/cells/contextCell/ContextCell.tsx
vscode/webviews/components/modelSelectField/ModelSelectField.tsx

- Telemetry v1 was a noop. Removed calls to it, and changed 1 call to v2 that was only calling v1.
- Other protocol messages were completely unused.
CI

remove unused webview protocol messages

---

lib/prompt-editor/src/useExtensionAPI.tsx
lib/shared/src/misc/rpc/webviewAPI.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/webviews/AppWrapperForTest.tsx
vscode/webviews/CodyPanel.tsx
vscode/webviews/chat/cells/messageCell/assistant/AssistantMessageCell.tsx
vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.story.tsx
vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx
vscode/webviews/components/StateDebugOverlay.tsx
vscode/webviews/components/shadcn/ui/tabs.tsx
web/demo/App.tsx
web/lib/agent/agent.client.ts
web/vite.config.ts

- more minimal UI so you can keep it enabled while devving
- shows in Cody Web demo
n/a

improved StateDebugView

---

vscode/CHANGELOG.md
vscode/package.json

Version Bump
VS Code: Release v1.36.0

VS Code: Release v1.36.0

---

.github/workflows/jetbrains.yml

Adds a workflow that builds JetBrains main with a Cody commit, as an FYI.
Look at output of the JetBrains FYI job.

Add a CI workflow that builds the JetBrains plugin as an FYI

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/CHANGELOG.md
vscode/package.json
vscode/src/repository/remoteRepos.ts

Cherry-pick https://github.com/sourcegraph/cody/pull/5805
cherry-pick and updated changelog and version

Hitesh/vscode 1.36.2 release

---

lib/shared/src/chat/transcript/index.ts
lib/shared/src/editor/editorState.ts
lib/shared/src/index.ts
lib/shared/src/models/model.ts
lib/shared/src/token/counter.ts
vscode/src/chat/agentic/CodyTool.ts
vscode/src/chat/agentic/DeepCody.ts
vscode/src/chat/chat-view/ChatController.test.ts
vscode/src/chat/chat-view/ChatController.ts

No behavior change, just the addition of tests.
n/a

add ChatController tests for sending, followups, editing, and errors

---

vscode/CHANGELOG.md
vscode/package.json

vscode 1.36.3 release
updated chagelog and version

VS Code: Release 1.36.3

---

lib/shared/src/models/sync.ts

In the current implementation of `syncModels`, the waitlist check is not applied to users who have Deep Cody enabled. This is because the Deep Cody logic returns early from the observable pipeline, preventing the execution of the waitlist check for these users.
This PR restructures the logic in `syncModels` to ensure that the waitlist check is applied to all users before handling the Deep Cody-specific logic.
- Modified the `remoteModelsData` observable in `lib/shared/src/models/sync.ts` to perform the waitlist check before the Deep Cody check.
- Ensured that the `data` object is consistently updated with waitlist information for all users.
- Maintained the existing Deep Cody functionality for eligible users.
Sign in as DotCom user:
o1 models showing up with "Join Waitlist" label for …

Chat: fix waitlist check on model sync

---

vscode/CHANGELOG.md
vscode/package.json

VS Code: Release v1.38.0
This is built off commit 3be77a18bc322db15f2e63bd87fd782429621e87 which is tested and has addressed stability issue for the Webview

VS Code: Release v1.38.0

---

README.md
vscode/README.md

Updates the README:
-  "Commands" -> "Prompts"
Updates VSC Marketplace
- 
Marketing copy only.

Update README.md and VSC Marketplace

---

lib/shared/src/chat/chat.ts

Update Deep Cody model to use the latest Claude 3.5 Sonnet model deployed in https://github.com/sourcegraph/sourcegraph/pull/1244
Model string update for a feature behind feature flag.

Deep Cody: update model to Claude 3.5 Sonnet Latest

---

vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/components/WelcomeFooter.module.css
vscode/webviews/chat/components/WelcomeMessage.tsx
vscode/webviews/components/promptsMigration/PromptsMigration.module.css
vscode/webviews/components/promptsMigration/PromptsMigration.tsx

This PR is an amalgamation of small CSS changes and tweaks to the Cody chat panel.
**Before**  | **After**
-- | --
Tested locally, manually.

fix: visual tweaks and polish on Cody chat panel

---

vscode/webviews/components/modelSelectField/ModelSelectField.tsx

Manual testing + CI
Before:
After:

Capitalize provider names in tool tips

---

package.json
pnpm-lock.yaml
vscode/package.json
web/package.json

Incorporates https://github.com/sourcegraph/openctx/pull/210.
CI

bump openctx to incorporate HTTP provider invocation

---

vscode/CHANGELOG.md
vscode/package.json

Release v1.40.0 gogogo!!!
N/A - See https://linear.app/sourcegraph/issue/QA-144/qa-report-oct-30-2024

VS Code: Release v1.40.0

---

vscode/package.json

Updates the marketplace description from saying "Claude 3" to "Claude 3.5 Sonnet"
Only updates text description for the marketplace.

Update marketplace description

---

vscode/src/completions/analytics-logger.ts

Previously, CompletionBookkeepingEvent fields that represent timestamp could be floating numbers (non-integer). That was breaking type deserialization in the JetBrains client (and likely could cause troubles in other clients). The protocol expects integers.
This PR ensures that the timestamps are integers.
Tested manually with https://github.com/sourcegraph/jetbrains/pull/2584.

Ensure CompletionBookkeepingEvent timestamps are not floating point

---

agent/src/AgentWorkspaceConfiguration.test.ts
agent/src/AgentWorkspaceConfiguration.ts

Unit tests added.
Also test plan from this PR: https://github.com/sourcegraph/cody/pull/6058 
should work without any settings on the instance.

Fix configuration inspect method

---

vscode/src/autoedits/adapters/cody-gateway.ts
vscode/src/autoedits/adapters/fireworks.ts
vscode/src/autoedits/autoedits-provider.ts

Removes the hardcoded indentation and handling the same at the model layer correctly. 
Green CI

fix indentation issue

---

vscode/webviews/chat/cells/messageCell/human/editor/toolbar/AddContextButton.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx
vscode/webviews/components/shadcn/ui/toolbar.module.css

Part of https://linear.app/sourcegraph/issue/CODY-4290
Run locally

chat input: '@' -> '@ Context' toolbar button

---

vscode/src/chat/chat-view/prompts-migration.ts

Fixes QA-159
It improves Prompts from Command migration, it adds a bit more complex name transformation in order to avoid prompt name validation failure if the command name has some unsupported symbols (like @ or _ or sequence of "-")
Same change was done in SG admin prompts/commands migration tool https://github.com/sourcegraph/sourcegraph/pull/1664
- Check that you can migrate your local commands via the prompts/commands wizard on the welcome area or prompts tab) even if your commands have unsupported symbols in their name/key field

Fix prompt name generation during prompts/commands migration

---

vscode/CHANGELOG.md

adding PRs associated from v1.38 -> v1.40
n/a

add 1.40 changelog items

---

vscode/src/autoedits/renderer/diff-utils.test.ts
vscode/src/autoedits/renderer/diff-utils.ts

- Follow-up for https://github.com/sourcegraph/cody/pull/6172
- Adds tests to our diff utils logic to ensure it can handle different new line chars.
CI with new unit tests.

chore(audoedit): test diff logic with different new line chars

---

vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-diff-helpers/auotedit-short-term-diff.test.ts
vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-diff-helpers/auotedit-short-term-diff.ts
vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-diff-helpers/helper.test.ts
vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-diff-helpers/helper.ts
vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-diff-helpers/recent-edits-diff-strategy.ts
vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-diff-helpers/unified-diff.ts
vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-diff-helpers/utils.test.ts
vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-diff-helpers/utils.ts
vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-retriever.ts

Adding more granular line level diff strategy for the recent edits calculation
Added CI test cases

adding line level diff strategy for the recent edits diff calculation

---

.github/workflows/backport.yml
vscode/scripts/changelog.sh

update instructions for release captain on how to use this script and tags cody-core for all backport requests
N/A just text

Update changelog.sh instructions and add cody-core to backports

---

vscode/webviews/App.tsx
vscode/webviews/components/hooks.ts

also factor out key suppression into custom hook
test locally

suppress emission of characters on emacs keybindings

---

package.json
pnpm-lock.yaml
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/protocol.ts
vscode/src/services/open-telemetry/CodyTraceExportWeb.ts
vscode/src/services/open-telemetry/trace-sender.ts
vscode/webviews/App.tsx
vscode/webviews/Chat.tsx
vscode/webviews/chat/Transcript.story.tsx
vscode/webviews/chat/Transcript.test.tsx
vscode/webviews/chat/Transcript.tsx
vscode/webviews/utils/spanManager.ts
vscode/webviews/utils/webviewOpenTelemetryService.ts
web/lib/agent/shims/stream.ts
web/lib/agent/shims/zlib.ts
web/vite.config.ts

#6100 was reverted in #6179 based[ on the thread ](https://sourcegraph.slack.com/archives/C05AGQYD528/p1732289326228309)
So now @vovakulikov made a fix in this PR for it. The fix is in[ this commit
](https://github.com/sourcegraph/cody/commit/b361e05f79d5fe0212bd3c2fd3dcf3e5866bf9a8)
NOTE: The commit is not present in this PR because of rebasing I had to do some squash shenanigans but I made a separate branch where you can see the commit which just shows the change from Vova. 
- Go to web directory
- `pnpm dev` 
- go to http://localhost:5777 to test if the page loads properly and everything else

Fixing Integrate OpenTelemetry tracing in Cody Webview PR 6100

---

vscode/webviews/components/Notices.tsx

Follow up on https://github.com/sourcegraph/cody/pull/6245
CLOSE https://linear.app/sourcegraph/issue/CODY-4346/implement-the-eligible-for-teams-upgrade-triggering
CLOSE https://linear.app/sourcegraph/issue/CODY-4345/add-telemetry-to-the-eligible-for-teams-upgrade-cta
This PR introduces session-based dismissal for notices in the Cody extension. The 'DogfoodS2' notice continued to be dismissed only for the current session, allowing them to be shown again if the user logs out and logs back in. The 'TeamsUpgrade' notice is now dismissed forever after the user has clicked on the dismiss button once.
- Adding a `useLocalStorage` hook to manage dismissed notices in local storage
- Introducing a `sessionDismissedNotices` state to track notices dismissed for the current …

feat(webviews): add telemetry events and session-based dismissal for notices

---

.github/workflows/backport.yml

- Testing it live doing the release process. :/
chore/build: The backports workflow matches JetBrains and VSCode branch names.

chore/build: Match JetBrains and VSCode branch names for backports

---

vscode/CHANGELOG.md
vscode/package.json

Emergency patch release v1.48.1 to address telemetry issues
N/A

VS Code: Release 1.48.1

---

vscode/src/chat/agentic/CodyTool.ts
vscode/src/chat/agentic/prompts.ts

Ask Deep Cody to load a .env file.

Improve prompting to prevent loading .env files

---

jetbrains/src/integrationTest/kotlin/com/sourcegraph/cody/edit/DocumentCodeTest.kt
jetbrains/src/integrationTest/kotlin/com/sourcegraph/cody/util/CodyIntegrationTextFixture.kt
jetbrains/src/integrationTest/kotlin/com/sourcegraph/cody/util/TestingCredentials.kt
jetbrains/src/integrationTest/resources/recordings/integration-test_2927926756/recording.har.yaml
jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentServer.kt
jetbrains/src/main/kotlin/com/sourcegraph/cody/listeners/CodyCaretListener.kt
jetbrains/src/main/kotlin/com/sourcegraph/cody/listeners/CodySelectionListener.kt
jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt

Fixes integration tests broken by https://github.com/sourcegraph/cody/pull/6306
Also, I think I might found reason of the test flakiness and fixed it as well.
N/A, this is a fix for the testing infrastructure.

Fix jetbrains integration tests

---

vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx
vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx

Revert "[Backport vscode-v1.52.x] Fix manual intent selection for onebox"

---

vscode/src/autoedits/renderer/renderer-testing.ts

- Switches the `cody.experimental.autoedits.use-mock-responses` logic for response extraction from the template to rely on line numbers instead of document offsets because autoedits are always generated for a number of lines and can never start or end in the middle of a line. This fixes response extraction in some of the cody-chat-eval examples.
- CI
- Manually go over cody-chat-eval examples with `"cody.experimental.autoedits.use-mock-responses": true,` in your VS Code settings and ensure that responses are extracted from templates (no LLM requests should be visible in the Cody Debug output channel).

feat(audoedit): improve inline renderer offline testing logic

---

jetbrains/src/integrationTest/kotlin/com/sourcegraph/cody/util/CodyIntegrationTextFixture.kt
jetbrains/src/integrationTest/resources/recordings/integration-test_2927926756/recording.har.yaml
jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentServer.kt
jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/protocol/NetworkRequest.kt

* PR #6293:
`mkondratek/migrate-api/testing/requestErrors` ➔ `pkukielka/fix-polly-recordings-v5`
* PR #6289:
`pkukielka/fix-polly-recordings-v5` ➔ `main`
- All migrated endpoints have been verified with debugger (and reviewed in the trace log).
- Autocomplete works, chat works.

Migrate `testing/requestErrors`

---

vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx

Was in here for something else, just a quick fix to the copy to not suggest exhaustive results.

fix result count copy

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
lib/shared/src/models/modelsService.ts
lib/shared/src/models/sync.test.ts
lib/shared/src/models/sync.ts

Applying https://github.com/sourcegraph/cody/pull/6353
See https://github.com/sourcegraph/cody/pull/6353

[Backport jb-v7.6.x] show Deep Cody to pro users only

---

vscode/webviews/components/promptFilter/PromptsFilter.tsx
vscode/webviews/prompts/PromptsTab.tsx
web/CHANGELOG.md
web/package.json

@vovakulikov [discovered](https://github.com/sourcegraph/cody/pull/6346#issuecomment-2548014730) that keyboard nav is missing from the prompts library dropdown. This PR fixes it.
https://github.com/user-attachments/assets/703af5e9-99c8-4b52-a9dc-a81677b26a56
Manual testing
feat: add keyboard nav for prompts library

feat: add keyboard nav for prompts library

---

vscode/webviews/chat/cells/messageCell/human/editor/toolbar/SubmitButton.tsx

This PR has these fixes for jetbrains

Fix edit intent setting for jetbrains backport

---

vscode/package.json

VS Code version bump to v1.52.0

---

vscode/src/autoedits/renderer/inline-manager.ts

- Hides inline renderer suggestions on cursor movement
- Part of [CODY-4412: Implement experimental inline renderer](https://linear.app/sourcegraph/issue/CODY-4412/implement-experimental-inline-renderer)
- Closes [CODY-4415: Inline-renderer: suggestion disposal on cursor movement](https://linear.app/sourcegraph/issue/CODY-4415/inline-renderer-suggestion-disposal-on-cursor-movement)
CI and manual testing in the cody-chat-eval repo.

feat(audoedit): dismiss suggestions on selection change

---

vscode/src/chat/chat-view/ChatController.ts
vscode/webviews/App.module.css
vscode/webviews/chat/cells/messageCell/assistant/SearchResults.module.css
vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx

This PR adds responsive layout for Filters Sidebar for Cody both IDE and web.
https://www.loom.com/share/fae20c99158748efb36f56f4857c2593

Filters layout for Cody Web

---

vscode/webviews/components/promptFilter/PromptsFilter.tsx
vscode/webviews/components/promptList/PromptList.tsx
vscode/webviews/components/shadcn/ui/command.tsx

A few small tweaks to the UI for prompt filters.
Manually tested, locally.

fix: Styling updates to prompt list

---

vscode/src/chat/chat-view/ChatController.ts
vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx

This builds on top of https://github.com/sourcegraph/sourcegraph/pull/2375 to boost the current repo for one box search. 
[Video walkthrough](https://share.cleanshot.com/N6q9xW2f)

feat: boost current repo

---

vscode/src/context/openctx/codeSearch.ts
vscode/webviews/App.module.css
vscode/webviews/chat/cells/messageCell/assistant/SearchResults.module.css
vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx
vscode/webviews/components/Notices.tsx
web/CHANGELOG.md
web/package.json

Cody Web 0.20.0 release
- Fixes problem with popover elements after search results fitlers container change
- Updates banner styles for instance level notificationss
- Check Cody Web manually connected to local sg instance

Fixes paper cuts for Cody Web 0.20.0 cut

---

vscode/CHANGELOG.md
vscode/package.json

Created as instructed by the Release Captain Playbook

chore/release: Bump package version and update changelog for 1.52

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/chat/context/chatIntentAPIClient.ts

Replace Intent Detector FF with the one-box feature flag.
- make sure the intent detector is working.

Use omnibox ff for intent detector

---

vscode/CHANGELOG.md
vscode/package.json

chore/release: Bump package version and update changelog for 1.54

---

vscode/CHANGELOG.md

N/A since this is just changing `CHANGELOG.md`

chore/cody: Update CHANGELOG.md

---

.github/workflows/generate-changelog.yml
vscode/CHANGELOG.md

Still not quite ready, but to test it we're running in github actions
Been pairing with @kalanchan on this one 
Run the action

feat: generate changelog action

---

vscode/CHANGELOG.md

Update CHANGELOG.md versioning for 1.56

---

agent/src/NativeWebview.ts

`cody-agent-trace.json` looks like this now:
```
[Trace - 01:03:47 PM] Received notification 'webview/setTitle'
Params: {
"handle": "native-webview-panel-df3675ed-b3d7-4051-94ff-78a569945443",
"title": "Explain what @src/main/ja..."
}
[Trace - 01:03:47 PM] Received notification 'webview/setTitle'
Params: {
"handle": "native-webview-panel-df3675ed-b3d7-4051-94ff-78a569945443",
"title": "Explain what @src/main/ja..."
}
[Trace - 01:03:47 PM] Received notification 'webview/setTitle'
Params: {
"handle": "native-webview-panel-df3675ed-b3d7-4051-94ff-78a569945443",
"title": "Explain what @src/main/ja..."
}
[Trace - 01:03:47 PM] Received notification 'webview/setTitle'
Params: {
"handle": "native-webview-panel-df3675ed-b3d7-4051-94ff-78a569945443",
"title": "Explain what @src/main/ja..."
}
[Trace …
```

Update NativeWebview title only if the title changes

---

lib/shared/src/misc/rpc/webviewAPI.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/webviews/AppWrapperForTest.tsx
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/messageCell/assistant/RepositorySelector.tsx
vscode/webviews/chat/cells/messageCell/assistant/SearchFilters.tsx
vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx
vscode/webviews/chat/cells/messageCell/assistant/SwitchIntent.tsx
vscode/webviews/components/NLSResultSnippet.tsx
vscode/webviews/components/codeSnippet/CodeSnippet.tsx
vscode/webviews/components/codeSnippet/components/RepoLink.tsx
vscode/webviews/components/shadcn/ui/input.tsx
vscode/webviews/components/shadcn/ui/label.tsx

closes: https://linear.app/sourcegraph/issue/SRCH-1419/path-search-results
closes: https://linear.app/sourcegraph/issue/SRCH-1442/add-different-countn-filter-for-other-result-types
closes: https://linear.app/sourcegraph/issue/SRCH-1417/text-results
https://www.loom.com/share/58d63ad0ce2a45649400ed04cc9dfcb3

Result Types & Repo Filter

---

vscode/src/autoedits/analytics-logger/analytics-logger.test.ts
vscode/src/autoedits/analytics-logger/analytics-logger.ts
vscode/src/autoedits/autoedits-provider.ts

Added `discarded` analytics events for the autoedits provider that would allow us to know how often and why autoedit suggestions are not shown to users after they have been fetched from the backend.
CI and updated unit tests.

feat(autoedit): add `discarded` events

---

web/CHANGELOG.md
web/package.json

Updates Cody Web to 0.22.0
- cd web
- pnpm dev
- test cody web demo

Update Cody Web 0.22.0

---

lib/shared/src/misc/rpc/rpc.ts

This fixes some debugging output that would have been useful for debugging initial/default context bugs.
```
cd jetbrains
CODY_LOG_WEBVIEW_RPC_MESSAGES=true ./gradlew :customRunIde &
tail -F build/sourcegraph/cody-agent-log.json | grep RPC
```
Webview <--> extension RPC messages should have data like this:
```
"█ [RPC] W-\u003eX: {\"streamId\":\"2pn4b0arkm5yq6rc9\",\"method\":\"evaluatedFeatureFlag\",\"args\":[\"deep-cody\"]}",
"level": "trace"
```
Instead of opaque messages like this:
```
"█ [RPC] X-\u003eW:: [object Object]"
```

chore/webview: Fix webview-extension RPC logging to contain message payloads

---

web/CHANGELOG.md
web/package.json

Updates Cody Web to 0.23.0
- cd web
- pnpm dev
- test cody web demo

Update Cody Web to 0.23.0

---

vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/messageCell/assistant/RepositorySelector.tsx
vscode/webviews/chat/cells/messageCell/assistant/SearchFilters.module.css
vscode/webviews/chat/cells/messageCell/assistant/SearchFilters.tsx
vscode/webviews/chat/cells/messageCell/assistant/SearchFiltersModal.tsx
vscode/webviews/chat/cells/messageCell/assistant/SearchResults.module.css
vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx
vscode/webviews/chat/cells/messageCell/assistant/SwitchIntent.tsx
vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx
vscode/webviews/components/codeSnippet/CodeSnippet.module.css
vscode/webviews/components/codeSnippet/CodeSnippet.tsx
vscode/webviews/components/codeSnippet/components/CodeExcerpt.module.css
vscode/webviews/components/codeSnippet/components/CodeExcerpt.tsx
vscode/webviews/components/codeSnippet/components/FileMatchChildren.module.css
vscode/webviews/components/codeSnippet/components/RepoLink.tsx

This PR is to implement visual updates across Cody in the editor and on the web. It's a pretty substantial set of changes so needs thorough review and testing.
|--------|-------|
| ![Before](https://github.com/user-attachments/assets/39438b0e-f837-4a4d-ae4f-a4946887d82e) | ![After](https://github.com/user-attachments/assets/aa91c85d-5583-403f-9d36-ac8f4ee34490) |
- Update styling for agentic chat and context fetching UI
Tested locally, visually.

fix: Search results in Cody visual update

---

vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx
vscode/webviews/chat/cells/messageCell/assistant/SwitchIntent.tsx
vscode/webviews/chat/components/QuickStart.tsx
web/package.json

Update Cody Web to 0.24.0. Remove border-muted as it uses wrong var and renders white on web. 
follow web/readme.md to test with sg.

Naman/update cody web 0.24.0

---

.github/workflows/generate-changelog.yml

template string is supposed to be ``
N/A

fix(release): fix generate changelog template string

---

vscode/src/completions/context/retrievers/recent-user-actions/diagnostics-retriever.test.ts
vscode/src/completions/context/retrievers/recent-user-actions/diagnostics-retriever.ts

- By testing locally, I reproduced the runtime error we see in our analytics data. It's coming from the diagnostics retriever where line numbers are not clamped. 
- Closes [CODY-4717: Fix the `illegal line` runtime error](https://linear.app/sourcegraph/issue/CODY-4717/fix-the-illegal-line-runtime-error)
CI + updated unit tests

chore(audo-edit): fix the illegal line runtime error

---

vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/Cell.tsx
vscode/webviews/chat/cells/agenticCell/AgenticContextCell.tsx
vscode/webviews/chat/cells/contextCell/ContextCell.module.css
vscode/webviews/chat/cells/contextCell/ContextCell.tsx
vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx
vscode/webviews/chat/cells/messageCell/assistant/SwitchIntent.tsx
vscode/webviews/components/codeSnippet/CodeSnippet.tsx

Minor css chages. 
- cd web
- pnpm dev

More CSS updates

---

web/package.json

Update Cody Web 0.26.0

---

web/package.json

changes from https://github.com/sourcegraph/cody/pull/6755
Update Cody Web 0.27.0

Update Cody Web 0.27.0

---

agent/protocol.md

N/A, this PR only changes a markdown file.

Fix typo in protocol.md

---

jetbrains/src/integrationTest/resources/recordings/integration-test_2927926756/recording.har.yaml

N/A, internal fix for broken tests

Fix jetbrains recordings

---

vscode/src/autoedits/adapters/cody-gateway.test.ts
vscode/src/autoedits/adapters/cody-gateway.ts
vscode/src/autoedits/adapters/fireworks.test.ts
vscode/src/autoedits/adapters/fireworks.ts
vscode/src/autoedits/adapters/sourcegraph-chat.test.ts
vscode/src/autoedits/adapters/sourcegraph-chat.ts
vscode/src/autoedits/adapters/sourcegraph-completions.test.ts
vscode/src/autoedits/adapters/sourcegraph-completions.ts

Reverts sourcegraph/cody#6853
CI

Revert "fix(auto-edit): fix temperature value to be low for output consistency"

---

agent/README.md
jetbrains/src/integrationTest/resources/recordings/integration-test_2927926756/recording.har.yaml
vscode/CHANGELOG.md
vscode/package.json

Also update the agent test recording docs: `src login` only works if you
have `SRC_ACCESS_TOKEN` set, which `export-cody-http-recording-tokens`
does not do.
Test agent recordings have been updated:
```
pnpm run test agent/src/index.test.ts
```

chore/release: Bump package version and update changelog for 1.66

---

jetbrains/src/main/kotlin/com/sourcegraph/cody/listeners/CodyDocumentListener.kt
jetbrains/src/main/kotlin/com/sourcegraph/cody/telemetry/TelemetryV2.kt
vscode/src/services/utils/codeblock-action-tracker.ts

closes https://linear.app/sourcegraph/issue/CODY-4121
- verified with the debugger that the logger execution happens
- chat Copy and chat Insert verfied
- todo: check the metrics
-

Fix keyDown:paste 

---

.gitignore

ignore aider files

---

vscode/webviews/chat/cells/agenticCell/AgenticContextCell.tsx
vscode/webviews/tabs/HistoryTab.tsx

**Before**
1. Things on the chat page are not aligned (see image)
2. The search bar text font is too big (see gif)
3. The search bar moves while typing (see gif)
**After**
1. Everything is aligned
2. Smaller font
3. Make the search bar not move while typing
CI & local tests
(cherry picked from commit d17c277efe2415d07f533801d29d9fb3274f1b5f)

fix(ui): Fix bugs in the UI (#7001)

---

vscode/src/chat/protocol.ts

Remove intent detection leftovers. 
- no feature changes

Remove intent leftovers

---

vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx
web/package.json

Update Cody Web to 0.31.0
Also hide filters toggle button when filters sidebar is visible. 
- cd web
- pnpm dev
- test cody

Update Cody Web to V0.31.0

---

vscode/CHANGELOG.md
vscode/package.json

Automated release and changelog for VS code Cody 1.68.0 \n ## Test plan \n N/A - changelog update

Changelog for 1.68.0

---

vscode/CHANGELOG.md
vscode/package.json

Automated release and changelog for VS code Cody 1.68.0 \n ## Test plan \n N/A - changelog update
---------
NA

Changelog for 1.68.0 (#7089)

---

vscode/CHANGELOG.md
vscode/package.json

Automated release and changelog for VS code Cody 1.70.0 \n ## Test plan \n N/A - changelog update

Changelog for 1.70.0

---

.github/workflows/release-jetbrains-experimental.yml
.github/workflows/release-jetbrains-prerelease.yml
.github/workflows/release-jetbrains-stable.yml
jetbrains/build.gradle.kts

Tested by enabling search build in tests and running it there:
https://github.com/sourcegraph/cody/actions/runs/13394726131/job/37410747588

Fix code search downlaod

---

jetbrains/build.gradle.kts
jetbrains/gradle/wrapper/gradle-wrapper.properties
jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.kt
jetbrains/src/main/kotlin/com/sourcegraph/cody/ui/web/WebUIProxy.kt
jetbrains/src/test/kotlin/com/sourcegraph/cody/autocomplete/CodyAutocompleteManagerTest.kt
jetbrains/src/test/kotlin/com/sourcegraph/cody/error/CodyErrorSubmitterTest.kt
jetbrains/src/test/kotlin/com/sourcegraph/config/ConfigUtilTest.kt
jetbrains/src/test/kotlin/com/sourcegraph/vcs/RepoUtilTest.kt

Update gradle and deps

---

README.md

Closes [CODY-5117](https://linear.app/sourcegraph/issue/CODY-5117/fix-broken-demos-link-in-cody-github-repository)
Manual testing

Update README.md (Fix a broken link.)

---

vscode/CHANGELOG.md
vscode/package.json

Automated release and changelog for VS code Cody 1.70.2
Replacing 1.70.1 as it failed to be published
N/A - changelog update

Changelog for 1.70.2

---

vscode/CHANGELOG.md
vscode/package.json

Update changelog to 1.70.2

---

vscode/CHANGELOG.md
vscode/package.json

[Backport M70] update changelog

---

doc/dev/PromptAtMentions.md

This PR adds a bit of documentation for future devs working on the prompt library and at mentions.
Manual review

docs: prompt library at mentions

---

vscode/CHANGELOG.md
vscode/webviews/chat/ChatMessageContent/ChatMessageContent.tsx

Improve the UI of the thinking display by:
1. Remove the "quirky" hover state
2. Make the text color easier to read
Before:
https://github.com/user-attachments/assets/43222c49-2c82-415d-99b8-d6ce430de57b
After:
https://github.com/user-attachments/assets/a7a8bd6e-06cd-4f19-ac9e-f620ffbd6ad2
Manually test

Improve the UI of the thinking display

---

jetbrains/src/main/kotlin/com/sourcegraph/cody/error/CodyConsole.kt

Fixes https://github.com/sourcegraph/jetbrains/issues/2679.
Fixes https://github.com/sourcegraph/jetbrains/issues/2885.
Fixes https://github.com/sourcegraph/jetbrains/issues/2893.
I was not able to reproduce.

Fix disposed errors from CodyConsole (closes #2893, closes #2885)

---

README.md

Update the main copy on README

---

vscode/webviews/chat/ChatMessageContent/ChatMessageContent.module.css
vscode/webviews/chat/ChatMessageContent/ChatMessageContent.tsx
vscode/webviews/chat/ChatMessageContent/create-buttons.ts

**WHAT & WHY**
Fix the regression caused by https://github.com/sourcegraph/cody/pull/7217
tested locally

fix(chat): Fix the filename container location in chat

---

lib/prompt-editor/src/mentions/mentionMenu/MentionMenuItem.module.css

Before:
After:
Manually test it

Truncate full file paths from the left, not from the right

---

jetbrains/src/main/kotlin/com/sourcegraph/cody/chat/ChatIconProvider.kt
jetbrains/src/main/kotlin/com/sourcegraph/cody/ui/web/WebviewPanel.kt
jetbrains/src/main/resources/META-INF/plugin.xml

1. Open New Chat
2. Review the icon in the top and in Recent Files

Add icon for Cody chat panel

---

vscode/webviews/chat/ChatMessageContent/create-buttons.ts
vscode/webviews/tailwind.config.mjs

https://github.com/user-attachments/assets/e714c9cb-1a9a-4bcf-863a-31bb49df50b4
Test manually.

Fix papercut: the apply and copy buttons render improperly when the sidebar width is narrow

---

lib/shared/src/models/sync.ts
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx

Follow up on https://github.com/sourcegraph/cody/pull/7279
This commit refines the logic for enabling image uploads and managing vision model support in the Cody application.
Key changes:
- Updated the `isImageUploadEnabled` function in `Toolbar.tsx` to correctly determine when image uploads are allowed. Image upload is now enabled if the user is not on Sourcegraph.com OR is using a BYOK model, AND the selected model has the `Vision` tag.
- Modified the `syncModels` function in `lib/shared/src/models/sync.ts` to conditionally remove the `Vision` tag from models provided by Google when running on Enterprise instances with early access enabled. This is because the gateway does not yet support vision models for Google.
Follow instruction in https://github.com/sourcegraph/cody/pull/7279

fix(dev): Refine image upload logic and vision model support

---

web/lib/components/CodyPromptTemplate.tsx
web/package.json

For bringing the prompt editor fixes in https://github.com/sourcegraph/cody/pull/7289 to the web app
n/a

chore: Bump cody web version in preparation for publishing

---

vscode/src/edit/edit-context-logging.ts
vscode/src/edit/prompt/smart-apply/selection.ts
vscode/src/edit/prompt/smart-apply/selection/base.ts
vscode/src/edit/prompt/smart-apply/selection/custom-model.ts
vscode/src/edit/prompt/smart-apply/selection/default.ts
vscode/src/services/utils/codeblock-action-tracker.ts

Add the feature flags for the smart apply custom model
Unit test

feat(smart-apply): Add feature flag for internal dogfooding

---

agent/recordings/auth_2503977039/recording.har.yaml
agent/recordings/cody-chat_103640681/recording.har.yaml
agent/recordings/customCommandsClient_509552979/recording.har.yaml
agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/document-code_965949506/recording.har.yaml
agent/recordings/edit_1541920145/recording.har.yaml
agent/recordings/fix_3001320056/recording.har.yaml
agent/src/__snapshots__/custom-commands.test.ts.snap
agent/src/__snapshots__/document-code.test.ts.snap
agent/src/__snapshots__/index.test.ts.snap
agent/src/custom-commands.test.ts
agent/src/edit.test.ts
agent/src/index.test.ts
jetbrains/src/integrationTest/resources/recordings/integration-test_2927926756/recording.har.yaml
lib/shared/src/chat/chat.test.ts
lib/shared/src/chat/chat.ts
lib/shared/src/sourcegraph-api/siteVersion.test.ts
lib/shared/src/sourcegraph-api/siteVersion.ts
vscode/test/e2e/command-edit.test.ts

- Fix Claude model versioning to use API version 0 for older models but not 3.5 or newer.
- Fix chat client adding empty assistant message as the last message for all requests which is not longer supported by newer models.
- Add support for the latest Cody API version (8) for chat completions.
- Refactor the chat client to simplify logic and improve readability.
- Verified that chat completions work as expected.
- Verified that Fireworks tracing is enabled for Sourcegraph teammates.
- Verified that Claude models older than 3.5 use API version 0.
- Verified that Claude models 3.5 or newer does not use API version 0.
- Verified that the chat client does not add an empty assistant message as the last message for all requests unless they are using older claude models.

fix(client): API versioning

---

jetbrains/src/main/kotlin/com/sourcegraph/cody/error/SentryService.kt

This PR adds embedded browser version information when logging into Sentry.
1. Try calling Cody related error
2. Open error reporting window by clicking on the icon in the lower right corner 
3. Select  error and click “Report to Sourcegraph”
4. Open Sentry and see if there is a new error in the `cody-jb` project

Logging JCEF version to Sentry

---

agent/package.json

Include `*.node` files in the NPM bundle
Will publish the library after this is merged

Cody CLI: Include Noxide files

---

vscode/src/commands/scm/source-control.ts

Refactor a few lines in vscode/src/commands/scm/source-control.ts

---

vscode/src/chat/chat-view/context.ts
vscode/src/chat/chat-view/handlers/ChatHandler.ts

CLOSE: https://linear.app/sourcegraph/issue/CODY-5163
This commit removes the priority context logic from the chat view. This includes removing the `getPriorityContext` function and its related dependencies. The priority context was used to determine context based on user input, but with the improved context fetching process, this often seen as unhelpful.
Readme context should no longer appended as context automatically.

refactor(chat): Remove priority context logic

---

vscode/src/edit/edit-context-logging.ts
vscode/src/edit/smart-apply-manager.ts

- Fix the structure of the smart apply payload to include additional fields like model, outside the smartApplyContext field enclosed in the privateMetadata.
- Add additional fields like `model` and `totalTimeMs` for the feature.
Check the telemetry event:
For dotcom instance:
```
{
"parameters": {
"version": 0,
"metadata": [
{
"key": "isPublic",
"value": 0
},
{
"key": "isPrefetched",
"value": 0
},
{
"key": "selectionTimeMs",
"value": 0.06316700001480058
},
{
"key": "applyTimeMs",
"value": 1456.3297080000048
},
{
"key": "totalTimeMs",
"value": 1465.289167000039
},
{
"key": "selectionRangeStart",
"value": 0
},
{
"key": "selectionRangeEnd",
"value": 2165
},
{
"key": "recordsPrivateMetadataTranscript",
"value": 1
}
],
"privateMetadata": {
"model": "fireworks::v1::smart-apply-qwen-default", …
```

fix(smart-apply): Fix the payload structure for the smart apply a/b test

---

vscode/src/edit/prompt/smart-apply/apply/smart-apply-custom.test.ts
vscode/src/edit/prompt/smart-apply/apply/smart-apply-custom.ts

Fix the role from assistant to system for smart apply model. 
Added unit test

feat(smart-apply): Fix the smart apply prompt role from system to assistant

---

web/package.json

Update Cody Web version to 0.32.3
- cd web
- pnpm dev
- test cody web demo

Update Cody Web 0.32.3

---

jetbrains/src/integrationTest/resources/recordings/integration-test_2927926756/recording.har.yaml
lib/shared/src/models/sync.test.ts
lib/shared/src/models/sync.ts

1. Fixed a bug where we change the input limits instead of the output limits when the flag is off. 
2. Simplified the code logic for better readability
Added tests in `sync.test.ts`, see [table](https://linear.app/sourcegraph/issue/CODY-5022/increase-context-window-limits#comment-ef682a3d) for more details on the test cases
Tested locally with console logs and the feature flag

fix(models): Update context limit logic

---

vscode/webviews/chat/Transcript.tsx

revert the change accidentally committed in https://github.com/sourcegraph/cody/pull/7491/files#r2008066537
caught by review bot https://github.com/sourcegraph/cody/pull/7491/files#r2008066537

chore(chat): revert

---

vscode/webviews/chat/cells/messageCell/human/editor/toolbar/ModeSelectorButton.test.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/ModeSelectorButton.tsx

AgentAgentAgentAgentAgentAgentAgentAgentAgent

fix(agentic): agentic -> agent dropdown title

---

jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt

Fixes https://linear.app/sourcegraph/issue/QA-554
Test edit, document code, and code completion on:
1. MacOs
2. Windows with project on C: \ drive
3. Windows with project on WSL2

Fix uri conversions on Windows

---

vscode/src/commands/context/git-api.ts
vscode/src/commands/scm/source-control.ts

Closes CODY-5277.
This PR depends on https://github.com/sourcegraph/cody/pull/7386.
Test manually.

Commit message gen: it is now able to handle a case when the user is not in the root directory

---

jetbrains/src/main/kotlin/com/sourcegraph/cody/config/ui/CheckUpdatesTask.kt

This potentially my fix one of the most reported exceptions:
https://sourcegraph.sentry.io/issues/6396868697/
Either way I changed the action to update the Cody plugin automatically, instead of just moving user to the plugins list.
I also investigated if we can reload our plugin without restarts.
Currently it does not work, and it would require some fixes to disposables and services we have, but in principle it should be possible. If someone would be looking at this later, some useful resources:
Docs:
https://plugins.jetbrains.com/docs/intellij/dynamic-plugins.html?from=jetbrains.org#restrictions
Debugging issues:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360008211319-Plugin-not-unload-safe-because-class-loader-cannot-be-unloaded
1. Run IntelliJ, you should see new …

Change update checker action to directly update Cody plugin

---

vscode/src/completions/analytics-logger.ts

PR adds tracking persistence data for longer duration to help predict longer suggestions.
Observe telemetry logs for the longer duration for autocomplete

(auto-edit): Add longer duration for persistence tracking for longer suggestion prediction

---

web/publish.md

Add cody web publishing docs. 
Follow the publishing guide and text.

Add Cody Web Publish Document

---

vscode/CHANGELOG.md
vscode/package.json

Automated release and changelog for Cody VS Code 1.80.0
N/A - changelog update
---------
Co-authored-by: sourcegraph-bot <bot@sourcegraph.com>
Co-authored-by: julialeex <julia.xu@sourcegraph.com>
(cherry picked from commit ef7565da84fbf27e2c1a1bfb1833ef0cd05a8b65)

Changelog for 1.80.0 (#7572)

---

jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/CodySecureStore.kt

1. Run integration tests few time local
2. Open IntelliJ
3. Switch account
No error should be thrown at any of the steps above.

Tests should use its own temp keystore

---

jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentClient.kt
jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/CodySecureStore.kt
jetbrains/src/main/kotlin/com/sourcegraph/cody/config/migration/AccountsMigration.kt
jetbrains/src/main/kotlin/com/sourcegraph/config/ConfigUtil.kt

Fixes https://linear.app/sourcegraph/issue/QA-569
Full QA, but in general that is just a pure revert.

Revert changes to password storage in JetBrains

---

jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentClient.kt
jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/CodySecureStore.kt
jetbrains/src/main/kotlin/com/sourcegraph/cody/config/migration/AccountsMigration.kt
jetbrains/src/main/kotlin/com/sourcegraph/config/ConfigUtil.kt

Fixes https://linear.app/sourcegraph/issue/QA-569
Full QA, but in general that is just a pure revert.

Revert changes to password storage in JetBrains 

---

vscode/src/chat/chat-view/ChatController.test.ts

This is very flaky and failing a lot of the time. Skipping as it's slowing down development for multiple people
Check tests pass

chore(tests): Skip flaky test

---

jetbrains/src/integrationTest/kotlin/com/sourcegraph/cody/AllSuites.kt
jetbrains/src/integrationTest/kotlin/com/sourcegraph/cody/autocomplete/AutocompleteCompletionTest.kt
jetbrains/src/integrationTest/kotlin/com/sourcegraph/cody/autocomplete/AutocompleteEditTest.kt
jetbrains/src/integrationTest/kotlin/com/sourcegraph/cody/autocomplete/BaseAutocompleteTest.kt
jetbrains/src/integrationTest/kotlin/com/sourcegraph/cody/util/BaseIntegrationTextFixture.kt
jetbrains/src/integrationTest/kotlin/com/sourcegraph/cody/util/EditCodeFixture.kt
jetbrains/src/integrationTest/resources/recordings/autocompleteEdit_3787598409/recording.har.yaml
jetbrains/src/integrationTest/resources/recordings/autocomplete_2136217965/recording.har.yaml
jetbrains/src/integrationTest/resources/recordings/documentCode_2994921345/recording.har.yaml
jetbrains/src/integrationTest/resources/testProjects/autocompleteEdit/src/main/js/debug-styles.ts
jetbrains/src/integrationTest/resources/testProjects/autocompleteEdit/src/main/kotlin/ForLoop.kt
jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt
jetbrains/src/main/kotlin/com/sourcegraph/cody/autoedit/AutoeditLineStatusMarkerPopupPanel.kt
jetbrains/src/main/kotlin/com/sourcegraph/cody/autoedit/AutoeditManager.kt

Resolves: https://linear.app/sourcegraph/issue/CODY-5605
* PR #7455:
`main` ← `mkondratek/feat/autoedits-diff-v2`
* **PR #7584 (THIS ONE)**:
`mkondratek/feat/autoedits-diff-v2` ← `mkondratek/chore/autoedit-it`
green ci

[JetBrains] Add integration tests for autoedits

---

vscode/CHANGELOG.md
vscode/package.json

Automated release and changelog for Cody VS Code 1.82.0
N/A - changelog update
---------
Co-authored-by: hitesh-1997 <hitesh.sagtani@sourcegraph.com>
(cherry picked from commit 527b200b6c817aba90398f737ad6fe4ab5eb8975)
Changelog

Changelog for 1.82.0 (#7656)

---

agent/src/enterprise-s2.test.ts
vscode/src/autoedits/analytics-logger/analytics-logger.test.ts
vscode/src/autoedits/autoedits-provider.test.ts
vscode/src/completions/analytics-logger.test.ts
vscode/src/completions/context/context-mixer.test.ts
vscode/src/completions/context/context-mixer.ts
vscode/src/completions/get-inline-completions-tests/analytics.test.ts
vscode/webviews/autoedit-debug/sections/ContextInfoSection.tsx

Fixed JSON-key is preferred by the analytics pipeline. Refactor the code to use array for retriever stats instead of (variable) key-value pairs.
- unit test

feat(auto-edit): add context summary latency to auto-edit dashboard

---

jetbrains/src/main/java/com/sourcegraph/find/FindPopupPanel.java
jetbrains/src/main/java/com/sourcegraph/find/FindService.java
jetbrains/src/main/java/com/sourcegraph/find/browser/JavaToJSBridge.java
jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/CodyAuthService.kt

Possible fix for `IllegalStateException - JS query has been disposed` [exception observed](https://sourcegraph.sentry.io/issues/6372518034/?project=4508886063644672) in Sentry.
Monitor [sentry issue](https://sourcegraph.sentry.io/issues/6372518034/?project=4508886063644672)

[JetBrains] Fix for "IllegalStateException - JS query has been disposed"

---

vscode/src/services/NetworkDiagnostics.ts

Looks like in case of the socket we cannot rely on the automatic cleanup upon the object destruction, because we are reusing the sockets. That is why we need to manually remove listeners when the socket is closed.
1. Play with Cody for a while (1 min of editing a text file is more than enough)
2. Search log for "leak detected" - there should be no leaks or too many listener warnings.

feat(agent): Manually cleanup listeners from the socket

---

vscode/src/services/NetworkDiagnostics.ts

Backport of [7654](https://github.com/sourcegraph/cody/pull/7654) and [7669](https://github.com/sourcegraph/cody/pull/7669) to M84
CC @sourcegraph/release
As in:
https://github.com/sourcegraph/cody/pull/7654
https://github.com/sourcegraph/cody/pull/7669

[Backport M84] Backport #7654 and #7669 to m84

---

web/publish.md

Improve the cody web publish documentation
Updated doc

chore(cody-web): Improve cody web publishing documentation

---

lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/siteVersion.ts

Backport of [7691](https://github.com/sourcegraph/cody/pull/7691) or M84
CC @sourcegraph/release
Green CI

 [Backport M84] Fix flaky tests caused by too often refresh of siteVersion #7691

---

vscode/test/integration/single-root/chat.test.ts

Disables flaky chat test to unblock release
CI

fix(tests): disable flaky chat test

---

vscode/test/integration/single-root/chat.test.ts

Disables flaky chat test to unblock release
CI
(cherry picked from commit 6d50980883965d2898d1d8e34c5c20c7532b33f0)
CI

fix(tests): disable flaky chat test (#7705)

---

jetbrains/src/main/java/com/sourcegraph/find/FindService.java

Fix for `NullPointerException` when calling `FindService.Dispose()`
1. Open a project
2. Right click in the editor -> Sourcegraph -> Find with Sourcegraph ...
3. Close project

[JetBrains] NPE fix for mainPanel

---

web/lib/components/use-cody-agent.ts

CLOSING https://linear.app/sourcegraph/issue/CODY-5685/new-chat-not-working-on-cody-web
Fixes the new chat not working bug on cody web
- cd web && pnpm dev
- Ask a question
- Click on 'New Chat'
Loom: https://www.loom.com/share/bff76cd063b84c6ea0b2a571eb21e682

fix(chat): Fixes the new chat bug on cody web

---

agent/package.json

Automated release PR for version 5.5.18.
CI

Release agent-v5.5.18

---

lib/shared/src/index.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts

Remove unused chat intent queries

---

vscode/src/autoedits/autoedits-config.ts

Add the model trained on long suggestion for hot-streak
CI

feat(auto-edit): Add hot-streak model for long suggestion

---

web/lib/components/use-cody-agent.ts
web/package.json

CLOSING https://linear.app/sourcegraph/issue/CODY-5686/model-selector-is-not-visible-in-cody-web-sidebar-when-you-open-a-file
This PR improves resource management by cleanly disposing of existing agents before creating new ones and fixes potential stale closure issues by using the correct dependency array in useEffect.
Local tests
Loom: https://www.loom.com/share/29d755f5b27248319475fde7d573e832?sid=1a373ae7-cc4c-49c1-a2c9-111a6e34be39

fix(web): Fix agent recreation in Cody Web component to properly respond to config changes

---

web/lib/components/use-cody-agent.ts

rename disposeAndCreateNewAgent to createAndSetNewAgent
Local tests

chore(web): rename disposeAndCreateNewAgent to createAndSetNewAgent

---

vscode/src/commands/scm/prompts.ts

Fix typo in constant: COMMMIT --> COMMIT

---

vscode/src/autoedits/hot-streak/get-chunk.test.ts

Fix typo in a comment: commments --> comments

---

vscode/src/commands/scm/prompts.ts

Fix typo: COMMIT_TEMPLATE_NOT_FOUNT --> COMMIT_TEMPLATE_NOT_FOUND

---

vscode/webviews/chat/ChatMessageContent/ChatMessageContent.module.css

Fixes CODY-5283
This commit refactors the layout of action buttons and the file name display in chat messages to improve the user interface.
Here is a video with the fix in action
https://www.youtube.com/watch?v=GNgvwzYSUFs
- Verify that the action buttons in the chat interface are displayed correctly and do not shrink unexpectedly.
- Verify that the file name in the chat interface is displayed correctly and truncates with an ellipsis when it exceeds the available space.

fix(chat): Improve layout of action buttons when chat window is shrinked

---

lib/shared/src/llm-providers/groq/chat-client.ts
lib/shared/src/llm-providers/utils.test.ts
lib/shared/src/llm-providers/utils.ts
lib/shared/src/models/fixtures.ts

Fixes BUGS-711
This commit introduces several improvements related to BYOK (Bring Your Own Key) model configurations and the Groq API client:
- Adds a comprehensive test suite for `getCompletionsModelConfig` to ensure correct configuration retrieval and handling of various model ID formats, including those with and without provider prefixes.
- Introduces fixture data for BYOK models to facilitate testing and demonstration of the BYOK model configuration logic.
- Updates the `getCompletionsModelConfig` function to correctly handle model IDs with provider prefixes, ensuring that the model name is extracted accurately.
- Corrects a typo in the Groq API client documentation, changing "Gork" to "Groq".
These changes improve the flexibility and reliability of the Cody integration with BYOK …

fix(models): Enhance BYOK model configuration to allow models with / in id

---

vscode/src/autoedits/adapters/sourcegraph-completions.ts
vscode/webviews/autoedit-debug/sections/PromptSection.tsx

- Fix the debug panel prompt tab with hot-streak. Earlier we weren't emitting the responseBody for the partial response.
- Check the prompt panel in the debug mode

fix(auto-edit): Add the prompt in debug panel for hot-streak

---

vscode/scripts/jb-changelogs.sh

A new script, `vscode/scripts/jb-changelogs.sh`, has been introduced and subsequently refactored to automate the generation of changelogs for JetBrains releases. Key improvements include:
- **Automated Changelog Generation**: Automates the creation of JetBrains release changelogs. 
- **Case-Insensitive Matching**: Implements case-insensitive matching for commit types and domains. 
- **Domain Grouping**: Groups changes by domain and capitalizes domain names for improved readability. 
- **Error Handling**: Adds error handling for the `git log` command and displays ungrouped changes.
- **Filtering Logic**: Fixes filtering logic and adds a cleanup step to remove temporary files.
- **Section Processing**: Introduces section processing (Features, Fixes, Changes, Chores, Uncategorized) to handle …

feat(release): Enhance JetBrains changelog generation with improved filtering and formatting

---

AGENT.md

See https://ampcode.com/news/AGENT.md.
n/a

add AGENT.md for use with Amp

---

vscode/src/chat/chat-view/tools/MCPManager.ts

CLOSE https://linear.app/sourcegraph/issue/CODY-5785/mcp-telemetry
This PR adds telemetry events to track the usage of Deep Cody tools and servers within the MCPManager. These events record when tools are executed, enabled/disabled, and when servers are added, removed, enabled, or disabled. The telemetry data includes the model, chat agent, tool name, server name, and arguments (for tool execution). This information will help us understand how Deep Cody is being used and identify areas for improvement.
Perform the events added and verify the event names are showing up in your output channel

feat(chat): Add telemetry for mcp tool and server usage

---

web/lib/components/use-cody-agent.ts

Revert this change due to regression.
Tested locally

Revert: fix(web): Fix agent recreation in Cody Web component to properly respond to config changes (#7787)

---

vscode/CHANGELOG.md
vscode/package.json

Changelog for 1.94.1 

---

vscode/CHANGELOG.md
vscode/package.json

Changelog for 1.94.1

---

vscode/CHANGELOG.md
vscode/package.json

Changelog for 1.94.2

---

lib/shared/src/sourcegraph-api/completions/browserClient.ts

Fixes CODY-5469
This commit introduces support for handling different types of content, including text and tool calls, within browser completions.
- Updating the completion processing logic to handle `delta_thinking`, `deltaText`, and `delta_tool_calls` from the server and construct the `content` array accordingly.
1.  Run a completion in the browser.
2.  Verify that the completion content is displayed correctly, including both text and tool calls.
3.  Ensure that the `delta_thinking` updates are handled correctly.

fix(cody-web): display thinking tags for reasoning models

---

vscode/webviews/chat/Transcript.tsx

CLOSE https://linear.app/sourcegraph/issue/CODY-5201
Make the last human editor sticky to the bottom:
- Implements auto-scrolling in `AssistantMessageCell` to keep the latest content visible during message streaming. The scrolling considers the height of the input box to prevent it from being hidden.
- Adds `data-scrollable="true"` to the transcript container to allow targeting the scrollable element.
- Makes the last human message input box sticky at the bottom of the transcript using `tw-sticky` and `tw-bottom-0` classes.
- Introduces a `setTimeout` to delay focusing the last human message editor after submitting or editing a message. This addresses a potential race condition or rendering issue.
- Ask Cody a question
- Verify the input editor is stick to the bottom for follow-up …

feat(chat): make last editor sticky

---

vscode/src/autoedits/analytics-logger/types.ts
vscode/src/autoedits/autoedits-provider.ts
vscode/src/autoedits/big-diff-modification.test.ts
vscode/src/autoedits/big-diff-modification.ts
vscode/src/autoedits/debug-panel/autoedit-data-sdk.ts
vscode/src/autoedits/renderer/diff-utils.ts

- Add filter on big diff modification
- Added unit test

autoedit: Add filter on the big diff modifications

---

vscode/CHANGELOG.md
vscode/package.json

chore/release: Bump package version and update changelog for M96

---

vscode/CHANGELOG.md
vscode/package.json

N/A - changelog update
(cherry picked from commit 8d69fe3b1fb75d98727f1146ad770b42504ad336)
N/A - Changelog

chore/release: Bump package version and update changelog for M96 (#7973)

---

vscode/webviews/themes/jetbrains.css

Before my fixes with light theme:
After my fixes:
1. Ask cody any question with file context
2. Click on the `Context >` in the reply to see all context files - they should be readable
3. Repeat check from point 2 with various themes

Fix mentions styling in JetBrains

---

jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt

IntelliJ plugins does not directly inherit IntelliJ env settings. In turn, agent process does not inherit them, nor any other processes spawn by it (like MCP servers). That may cause problems e.g. due to insufficient PATH configuration.
Problem can be mitigated by usage of `GeneralCommandLine` which allow us to generate `ProcessBuilder` with default IntelliJ env (by default the same as IntelliJ console).
Try to configure and launch MCP server according to MCP testing guide (internal).

fix(jetbrains): Cody agent should inherit IntelliJ env settings

---

lib/shared/src/sourcegraph-api/completions/parse.test.ts
lib/shared/src/sourcegraph-api/completions/parse.ts

Refactor data.usage logic
Local Tests & Green CI

chore(chat): refactor parse.ts

---

vscode/src/editor/utils/editor-context.test.ts
vscode/src/editor/utils/editor-context.ts

clean up code on large file detection
Green CI

chore(chat): clean up code on large file detection

---

vscode/test/e2e/chat-atFile.test.ts
vscode/test/e2e/chat-messages.test.ts
vscode/test/e2e/common.ts
vscode/webviews/Chat.tsx
vscode/webviews/CodyPanel.tsx
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/components/ScrollbarMarkers.tsx
vscode/webviews/chat/components/WelcomeMessage.tsx
vscode/webviews/components/ScrollDown.story.tsx
vscode/webviews/components/ScrollDown.tsx

Fixes https://linear.app/sourcegraph/issue/CODY-6024/generated-code-blocks-in-intellij-dont-autoscroll-making-it-difficult
Users were experiencing difficulty selecting large chunks of text in chat conversations. When trying to select text that spans multiple screens by clicking and dragging, the selection would not expand when the mouse cursor moved under the input box, which was overlapping the bottom portion of the chat content.
Redesigned the chat layout to separate the input box from the scrollable chat content:
- **Fixed input box** at the bottom of the screen during active conversations
- **Scrollable chat content** area above the input box
- **Smooth fade transition** where content meets the input box
- **Proper welcome message flow** for new conversations
- Split interactions into …

Redesign chat layout for improved text selection experience

---

vscode/src/services/open-telemetry/OpenTelemetryService.node.ts

This is not quite used feature, removing for now.
- N/A

fix: remove OTEL metrics

---

vscode/CHANGELOG.md
vscode/package.json

Changelog for 1.106.2

---

vscode/webviews/chat/Transcript.tsx

https://www.youtube.com/watch?v=V-PnNRUo5Jo
- Use the mention menu and notice that we no longer get a fake scroll down as we type

fix(chat): phantom scrolling when typing in mention menu

---

vscode/e2e/features/auth.test.ts
vscode/test/e2e/auth.test.ts
vscode/test/e2e/chat-atFile.test.ts
vscode/test/e2e/chat-history.test.ts
vscode/test/e2e/chat-input.test.ts
vscode/test/e2e/chat-rateLimit.test.ts
vscode/test/e2e/code-actions.test.ts
vscode/test/e2e/command-core.test.ts
vscode/test/e2e/command-custom.test.ts
vscode/test/e2e/command-edit.test.ts
vscode/test/e2e/command-menu.test.ts
vscode/test/e2e/common.ts

fix(ci): auth e2e tests after PLG shutdown

---

agent/package.json

Automated release PR for version 5.5.23.
CI

Release agent-v5.5.23
