lib/ui/src/chat/Transcript.tsx

To give a typing feel, we reduced streaming intervals between character chunks in [this PR](https://github.com/sourcegraph/sourcegraph/pull/54665)
We should also adjust this scroll threshold, as it is now more likely that a new chunk will come in while a user scrolls, and move them back to the bottom of the threshold.

Cody: Reduce scroll threshold for auto scroll

---

README.md
vscode/README.md
vscode/package.json
vscode/src/log.ts

Also improve wording in a few places.
Removes the old inline chat example because we now prefer using the `+` button.
Removes longer descriptions of some features (which were about their value, not how to use them) in lieu of simple demo videos.

update VS Code readme and marketplace listing to match top-level README

---

vscode/CHANGELOG.md
vscode/package.json

Revived from https://github.com/sourcegraph/sourcegraph/pull/54656.

release vscode 0.4.3

---

vscode/src/chat/ChatViewProvider.ts
vscode/src/services/InlineController.ts

Noticed this doing some final regression testing for the 0.4.3 release. It is possible to end up with a loading state that isn't cleared if a user manually stops the response. Just need to copy where `cody.reply.pending` is set

Cody: Fix inline loading state

---

vscode/package.json

We get an error when publishing when using the display name "Cody".
[Failed build
](https://github.com/sourcegraph/cody/actions/runs/5518311241/jobs/10062085036)
`Error: This extension display name 'Cody' is taken. Please try a different one. For queries contact VSMarketplace@microsoft.com.`
Using "Cody AI" as it's similar to what we had before. We can still omit the "by Sourcegraph" as that information is already shown I think.
Other suggestions welcome!

Cody: Update extension display name

---

vscode/package.json
vscode/src/completions/completion.test.ts
vscode/src/completions/text-processing.ts

Proposal based on feedback: [#1](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1688847762962619) and [#2](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1688885824688359).
We can cut off the completion on the partial suffix match (first N characters) to prevent suggesting code duplicating the completion suffix. We want to rely on a big-enough number of symbols to avoid false positives. We do not want to match the whole string because it leads to suffix duplication. Example:
We can use fancier algorithms like Levenstein distance instead, but it needs to be clarified if it will perform better in the wild. 
Added unit tests.

autocomplete: cut-off completions on partial suffix match

---

lib/shared/src/chat/recipes/helpers.ts
vscode/CHANGELOG.md
vscode/src/services/InlineController.ts

Close https://github.com/sourcegraph/cody/issues/114
This is a quick temporary fix for the issue where fixup replacement contains `</selection>` tag at the end:
This fix is served as a temporary fix as Dom's PR https://github.com/sourcegraph/cody/pull/70 to improve the multiplexer should fix this issue properly. 
Adding this line of code however, could use as a fallback in the future and should not break anything before and after Dom's PR:
Also added error handling to surface error messages during the inline fixup step.
Looks like the issue was a regression from https://github.com/sourcegraph/sourcegraph/pull/54665 as this issue does not exist when switching to the previous version (0.4.2). As the response is now being streamed to Inline Chat, caused the result to be sent to the …

fix: remove fixup ending tag

---

cli/tsconfig.json
slack/tsconfig.json
vscode/tsconfig.json
web/tsconfig.json

These are now `.eslintrc.json` files and do not need TypeScript typechecking.
n/a; build only

remove nonexistent .eslintrc.js entry from tsconfig.json files

---

lib/ui/src/Chat.tsx
vscode/CHANGELOG.md
vscode/src/chat/ChatViewProvider.ts

Closes #[229](https://github.com/sourcegraph/cody/issues/229) - Uses the common terminal hotkey [CMD-K](https://docs.warp.dev/features/keyboard-shortcuts#blocks) to clear & restart the Cody session like it does in terminal.
- Launch Cody from this branch
- Ensure there is chat history or start a new thread
- CMD+K and observe new session start

Hotkey cmd+K clears & restarts session

---

lib/shared/src/chat/bot-response-multiplexer.test.ts
lib/shared/src/chat/bot-response-multiplexer.ts

The LLM interaction pushes text to the bot response multiplexer without waiting for the publishing to complete. If the turn ends before publishing is complete, the half-parsed buffer is echoed as-is. The net effect is that `</selection>` closing tags from fixups are sometimes echoed to the output.
This fixes the problem by chaining a promise for the publications together and waits for them to complete before doing the "turn complete" processing.
`cd client/cody-shared && pnpm test`
Manual test:
This is racy, but you should use Fixup from Inline Instructions, Fixup (Experimental), etc. and check that the word `</selection>` does not appear in the output.

Cody: Bot response multiplexer publishes, then completes turns

---

.github/workflows/cli-release.yml
cli/README.md
cli/package.json

Also set up a GitHub Action to publish this for the tag `cli-v*`.
n/a; CLI is experimental

make the @sourcegraph/cody-cli package publishable

---

.github/workflows/scip-typescript.yml
agent/src/agent.ts

The sourcegraph.com auto-indexing queue has a lot of jobs so it takes a long time for the index to catch up with the latest commit. Having the indexing job in the repo makes sure we always have precise intel for the latest commits.

Add scip-typescript indexing job

---

cli/README.md
cli/package.json
cli/src/client/completions.ts
cli/src/client/index.ts
cli/src/client/interactions.ts
cli/src/commands/commit/command.test.ts
cli/src/commands/commit/command.ts
cli/src/commands/commit/compare.test.sh
cli/src/commands/commit/index.ts
cli/src/commands/repl/index.ts
cli/src/gitHelpers/index.ts
cli/src/gitHelpers/testHelpers.ts
cli/src/log.ts
cli/src/program.ts
cli/vitest.config.ts
lib/shared/src/sourcegraph-api/completions/client.ts
lib/shared/src/sourcegraph-api/completions/nodeClient.ts
tsconfig.json

The new (experimental) `cody commit` command passes the diffs (with added codebase context) from a Git repository to Cody to write a commit message. It optionally invokes `git commit` if `--dry-run` is not set.
(It wrote the 2 commit messages in this PR with only minor modifications.)
```
$ cd cli && pnpm run --silent build && dist/cody commit --dry-run
Add completions client and utilities
This commit adds utilities for interacting with the completions client to generate completions and responses. It includes:
- A `streamCompletions()` function to stream completions from the client.
- A `getCompletion()` function to get a single completion response. 
- A `getCompletionWithContext()` function to generate completions with context from the transcript and codebase.
This allows us to reuse …
```

cli: add commit command to generate a commit message

---

.vscode/cody.json
lib/shared/src/chat/recipes/helpers.ts
lib/shared/src/chat/recipes/my-prompt.ts
vscode/CHANGELOG.md
vscode/resources/bin/cody.json
vscode/src/chat/ChatViewProvider.ts
vscode/src/my-cody/MyPromptController.ts
vscode/src/services/DecorationProvider.ts
vscode/webviews/Recipes.module.css
vscode/webviews/Recipes.tsx

This PR adds new context types to the custom prompts feature.
Users can specify what type of context to include when building their recipe:
```
export interface CodyPromptContext {
codebase: boolean
openTabs?: boolean
currentDir?: boolean
excludeSelection?: boolean
}
```
Add intro to My Prompts and button to create cody.json file in current workspace:

custom prompts: add intro and new context type

---

vscode/CHANGELOG.md
vscode/package.json

Cut release for v0.4.4
The version includes:
- fixes for bugs that caused Inline Fixups [unusable](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1689267101964289)
- new feature: plugin
- new feature: custom recipe (internal testing only atm)

Release v0.4.4

---

vscode/src/chat/ChatViewProvider.ts

In the new logged plugin events, specific data was passed to the `eventProperties` field but not `publicProperties`. This will log to both now

add logging to `publicProperties` in new logged events

---

vscode/src/completions/completion.test.ts
vscode/src/completions/index.ts

Running 5 iterations each of completing a large file in single-line completion mode:
n=1: 1372ms, 1181ms, 1298ms
n=3: 1958ms, 1769ms
(There was no significant perf difference for n=1 vs. n=3 on multi-line mode.)
Run a single-line completion and ensure it works.

improve single-line completion perf by only fetching 1 completion

---

vscode/src/completions/completion.test.ts
vscode/src/completions/providers/anthropic.ts

This seemed to yield better results that did not result in trivial(ly incorrect) completions.
Also, it is not needed to say we are Cody since this is autocomplete not chat, so the identity of the bot is less likely to come up.
n/a

improve Anthropic code completion prompt

---

lib/shared/src/configuration.ts
vscode/CHANGELOG.md
vscode/package.json
vscode/src/completions/completion.test.ts
vscode/src/completions/index.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/main.ts
vscode/src/testutils/cli/run-code-completions-on-dataset.ts

Previously, autocomplete only triggered *after* you typed a non-letter character:
- `if err` would NOT trigger autocomplete
- `if err<SPACE>` WOULD trigger autocomplete
Now, the new experimental `cody.autocomplete.experimental.triggerMoreEagerly` VS Code setting changes the behavior so that autocomplete is triggered in the first case.
See https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1689357531463279 for context.
This has performance and UX consequences, so it's experimental for now.
- The completions sometimes lack a leading space, which results in /sometimes/ (eg) incorrectly completing `<Link` to `<Linkhref="..."`.
Set `cody.autocomplete.experimental.triggerMoreEagerly` to true. Open a code file and type `if err` or `const message` (without a space afterwards). Confirm that a …

experimental more eager autocomplete triggering

---

vscode/package.json
vscode/src/completions/index.ts
vscode/src/completions/logger.ts

Instruments our existing autocomplete logging to better track the new trigger-more-eagerly behavior introduced in #260:
1. Whether user has the `cody.autocomplete.experimental.triggerMoreEagerly` setting enabled.
1. Whether the completion was shown only because of that setting.
Discussion on this feature at https://github.com/sourcegraph/cody/discussions/274.
n/a; for experimental feature only

better logging for trigger-more-eagerly autocomplete

---

vscode/src/completions/completion.test.ts
vscode/src/completions/providers/anthropic.ts

This commit limits code completions to 2 lines when in single line mode, to avoid cluttering the editor with too many lines.
Added unit tests for:
- Completing up to 2 lines
- Completing 1 line if the second line is indented
This fixes a UX issue where inline completions look like a truncated multi-line completion, e.g.:

Cody: Limit completions to 2 lines in single line mode

---

vscode/src/completions/completion.test.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/shared-post-process.ts
vscode/src/completions/text-processing.test.ts
vscode/src/completions/text-processing.ts

Given `const isLocalhost = window.location.host{CURSOR}` and a completion ` === 'localhost'`, the leading whitespace before the `===` should be preserved. This comes up most frequently when using the new experimental `cody.autocomplete.experimental.triggerMoreEagerly` setting introduced in https://github.com/sourcegraph/cody/pull/260, which triggers autocomplete even before the user types space.
Added test case

preserve leading whitespace in completions

---

vscode/src/completions/index.ts

This line was mistakenly added, based on a misunderstanding. The `context.triggerKind` refers to how *inline completions* were triggered, not the *suggest widget* (the dropdown menu). It caused the `Trigger Inline Suggestion` VS Code action to not do anything in Cody. Now, that action works.
As for the other case (`sameLinePrefix.endsWith('.')`), we are already suppressing Cody completions when `context.selectedCompletionInfo` is present (which is when there is a selected item in the suggest widget), which already covers that case more robustly.
Run the VS Code `Trigger Inline Suggestion` action and confirm it works.

allow manual triggering of completions

---

vscode/src/completions/cache.test.ts
vscode/src/completions/cache.ts
vscode/src/completions/text-processing.test.ts
vscode/src/completions/text-processing.ts

For example, a cached completion for `a =` should not be returned for `a = ` (with a trailing
space). We still preserve the trailing-whitespace trimming behavior for entirely empty lines to
avoid rerunning completion when the user is just indenting on a new line.
Fixes the issue reported at https://github.com/sourcegraph/cody/pull/284#pullrequestreview-1534394856.
Follow the steps in the linked comment's video.

separately cache non-empty lines with differing trailing whitespace

---

vscode/package.json

- Do not register walkthrough commands (`cody.walkthrough.*`). These are only used in the walkthrough and do not need to be registered to work there.
- Do not register `cody.test.token`. This is only used for tests. It was mistakenly showing in the command palette and was a no-op there.
- Do not mention the Linux/Windows keybinding for `cody.inline.new` in the title because it differs for macOS. Also give it a macOS keybinding that does not use Ctrl.
Run the extension and confirm the walkthrough buttons work (in the VS Code walkthrough menu > Cody AI and then expanding the sections) and that there are no command registration errors.

declutter and clean up vscode package.json

---

lib/shared/src/configuration.ts
vscode/package.json
vscode/src/completions/index.ts
vscode/src/completions/logger.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/main.ts

Previously, when the suggest widget (which shows a list of function names, variable names, etc., from language symbols) was visible, Cody did not show an inline completion.
With the new experimental `cody.autocomplete.experimental.completeSuggestWidgetSelection` VS Code user setting, now Cody will show an inline completion when the first suggest widget item is selected. Its completion is based only on the characters you have typed, not the selected completion item (but the former is typically a prefix of the former). Taking the actual suggest widget completion item's `text` into account would be a UX improvement.
Related: https://github.com/sourcegraph/cody/issues/303
In a file, type a few characters that would trigger the suggest widget to show. Confirm that Cody *also* shows an inline …

show inline completions even when suggest widget is visible (experimental)

---

vscode/CONTRIBUTING.md

Running the packaged extension locally is important to test certain flows that are not available with the typical local development flow. E.g. onboarding workflows.
This just adds docs that explain how to do that
N/A - Docs change
Tested process myself

VS Code: Add docs for testing packaged extension

---

lib/ui/src/Chat.tsx
vscode/CHANGELOG.md

This PR closes #316. It disables the looping around down button after the last input history.
I tested it manually. 
To test, start the extension and press the Down Button. After it reaches the end, it won't loop around the first history input.

Fix input history down button

---

vscode/src/completions/index.ts
vscode/src/completions/logger.ts
vscode/src/completions/multiline.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/provider.ts
vscode/src/completions/providers/unstable-codegen.ts
vscode/src/completions/providers/unstable-huggingface.ts

Renaming all occurrences of `multilineMode` to a `multiline` boolean flag instead. My idea of having more modes in the future didn't pan out and this was just adding confusion.
The old field name is still kept in analytics for a bit so we can keep comparing data with the past. We can rm that in the future once we have more data with the new format.
Tests are green

Autocomplete: Remove multilineMode in favor of a simple boolean

---

vscode/src/chat/ChatViewProvider.ts
vscode/src/chat/protocol.ts
vscode/webviews/Chat.tsx
vscode/webviews/ConnectApp.tsx

Log app and auth event.
Add `app` to event names when logging in with app's URL
Update to log events. Defer to data team to confirm

update: log app and auth events

---

.vscode/cody.json
lib/shared/src/chat/recipes/my-prompt.ts
lib/shared/src/editor/index.ts
vscode/resources/samples/user-cody.json
vscode/resources/samples/workspace-cody.json
vscode/src/chat/ChatViewProvider.ts
vscode/src/my-cody/CustomRecipesBuilder.ts
vscode/src/my-cody/InputMenu.ts
vscode/src/my-cody/MyPromptController.ts
vscode/src/my-cody/MyToolsProvider.ts
vscode/src/my-cody/helper.ts
vscode/src/my-cody/types.ts
vscode/webviews/Recipes.tsx

1. add `/open` command  - the main purpose is to make it easier for users to build a recipe that involves opening a file
1. improve prompts used in custom recipes sample
1. fix JSON format issue
1. cleared up some helper functions
Example recipe that utilizes the /open command:
```json
{
"title": "Cody Custom Recipes - Workspace",
"description": "This is an example file to showcase how to build custom recipes for Cody by Sourcegraph.",
"recipes": {
"Open User Recipes File": {
"prompt": "/open user",
"note": "Open the existing cody.json file for User recipes in your editor if any"
}
}
}
```
- Enter `/open package.json` in Cody's chatbox with a workspace opened. the package.json file should be opened for you
- Enter `/open user` to open the .vscode/cody.json located in your home directory …

custom recipes: add /open command and improve prompts

---

vscode/package.json

The `INIT_CWD` env var is set to the dir from which `pnpm` is run, not the current package.json dir (https://docs.npmjs.com/cli/v9/commands/npm-run-script#description). This means that `$INIT_CWD/vscode` when run from the `vscode/` dir points to a nonexistent dir.
Run `pnpm -C vscode run dev` and `cd vscode && pnpm run dev` from the repository root and confirm both work.

fix `pnpm run dev` when run from the vscode/ dir

---

agent/vitest.config.ts
lib/shared/vitest.config.ts
vscode/src/chat/utils.test.ts
vscode/src/non-stop/utils.test.ts
vscode/src/services/InlineAssist.test.ts
vscode/vite.config.ts
web/vite.config.ts

All test files explicitly import the `describe`, `test`, `it`, etc., bindings, so this is no longer needed.
Confirm that unit test suite typechecks in CI.

remove unnecessary vite globals

---

vscode/test/completions/tsconfig.json
vscode/test/integration/tsconfig.json
vscode/tsconfig.json

Fixes an issue where `vscode/tsconfig.json` incorrectly included `test/completions` and caused errors when running `tsc -b` from various directories.
CI is sufficient.

fix tsconfig excludes

---

vscode/CHANGELOG.md
vscode/src/completions/completion.test.ts
vscode/src/completions/providers/anthropic.ts

Ensure that single-line mode completions are only ever returning a single line.
Since we no longer have two lines, I thought it's also okay to decrease the response token limit a bit. While there's still some variations, this seems to make it much more common for me when testing to get sub 800ms responses (compared to ~1sec before). I wasn't able to find an instance where 60 tokens weren't enough for single line completions yet.
Updated test suite. Tested the latency locally.

Autocomplete: Only ever complete a single line in single-line mode and reduce the output token limit

---

vscode/webviews/Chat.tsx

issue: `click` event name for copy and insert actions including the context value.
fix: remove text from event value
@akalia25 can you confirm if the changes in this branch work?

fix event name for copy and insert events

---

vscode/src/completions/index.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/provider.ts
vscode/src/completions/providers/unstable-codegen.ts
vscode/src/completions/providers/unstable-huggingface.ts
vscode/src/completions/request-manager.test.ts

- reuse ProviderOptions type
- only vscode.InlineCompletionList not type union
- add eslint disable rules
- refer to document.languageId
n/a

misc vscode refactors

---

vscode/src/chat/ChatViewProvider.ts

Removing usage of `any`
Types only change, should be not change in functionality. `lastChatUsedEmbeddings` should always be `true|false` now but that seems like it was bugged before

Cody: Fix `any` type

---

vscode/src/completions/index.ts
vscode/src/completions/request-manager.ts
vscode/src/main.ts
vscode/test/completions/run-code-completions-on-dataset.ts

Instead of repeating the property names and types in the `interface CodyCompletionItemProviderConfig` and the class members of `CodyCompletionItemProvider`, just use the type.
Tests suffice.

reuse CodyCompletionItemProviderConfig

---

lib/shared/src/common/markdown/markdown.ts
vscode/package.json
vscode/src/completions/context.ts
vscode/src/completions/index.ts
vscode/src/completions/tracer/index.ts
vscode/src/completions/tracer/traceView.ts
vscode/src/main.ts
vscode/test/completions/run-code-completions-on-dataset.ts

Added a `Cody: Open Autocomplete Trace View` command palette action opens a webview with trace info about the most recently triggered completion. This helps understand what params, prefix, suffix, context, etc., was used. It is only shown in the command palette when `cody.debug.enabled` is `true`.
https://github.com/sourcegraph/cody/assets/1976/fa83e9d1-1528-4f42-8f07-ad5f027f87fa
Set `cody.debug.enabled` to `true`, run the new command palette action (`Cody: Open Autocomplete Trace View`), and then trigger completions.

add `Cody: Open Autocomplete Trace View` and associated view

---

vscode/src/completions/language.ts
vscode/src/completions/multiline.ts
vscode/src/completions/providers/unstable-huggingface.ts

This tweaks the existing Hugging Face inference endpoint provider option to better work with the OG StarCoder model. This also now adds context in form of comments in the prefix to the prompt.
Two observations:
- StarCoder only supports 1k token prompt and up to 500 token response. I believe this is slower than WizardCoder
- Lots of model tuning still to be done of course. This is only a very rough first pass to evaluate it against other OS LLMs
- Run it locally using these settings:
```
"cody.autocomplete.advanced.accessToken": "ping me",
"cody.autocomplete.advanced.serverEndpoint": "ping me",
"cody.autocomplete.advanced.provider": "unstable-huggingface"
```

Autocomplete: Update Hugging Face inference endpoint for StarCoder prompt

---

vscode/src/completions/completion.test.ts
vscode/src/completions/text-processing.ts
vscode/src/completions/utils/string-comparator.test.ts
vscode/src/completions/utils/string-comparator.ts

Fixes https://github.com/sourcegraph/cody/issues/264
Prior to this PR, we cut off some trailing parts of completion based on the number of connected characters sequence in the begining of the suffix part (see this PR for more details https://github.com/sourcegraph/cody/pull/108). In this PR, we do simular same logic, but we try to compare strings a bit deeper based on a minimum number of edits operation over strings. If there is more than 30% of differences, we won't cut off the trailing completion. Otherwise, we cut off the completion string. This should handle cases like 
```
// Todo: cancel network request 
const abortController = new AbortController() // ← completion
const networkAbortController = new AbortController()
```
To be clear, even this comparing isn't ideal because there …

[Cody completion]: Improve trailing completion based on suffix string

---

.github/PULL_REQUEST_TEMPLATE.md

I've seen some commit messages from merged PRs (such as https://sourcegraph.com/github.com/sourcegraph/cody/-/commit/323160ccac317c18dc3cc55fa3174a6b4e3a25da?visible=9) that include the entire comment, which adds noise to the `git log`.
n/a

shorten test plan in PR template

---

vscode/package.json

This setting makes it so that autocomplete is triggered when you are still typing a word, without waiting for you to press space, return, `(`, etc.
This has been an experimental setting for 10 days (see internal discussion at https://sourcegraph.slack.com/archives/C05AGQYD528/p1689990943908639).
n/a

default `cody.autocomplete.experimental.triggerMoreEagerly` to true

---

lib/shared/package.json
lib/shared/src/codebase-context/rerank.test.ts
lib/shared/src/codebase-context/rerank.ts
pnpm-lock.yaml

The x2js library is much smaller and does not require non-browser (Node.js) deps. The total number of bytes parsed is small, so performance is not a major consideration. Also adds a test case.
n/a

use simpler XML parsing lib in reranking

---

lib/shared/src/hallucinations-detector/index.ts
vscode/src/chat/ChatViewProvider.ts
vscode/src/external-services.ts
vscode/src/local-context/local-keyword-context-fetcher.ts
vscode/src/main.ts
vscode/src/rg.ts
vscode/test/integration/local-search.test.ts

Instead of falling back to exec'ing `rg` on the `$PATH` if no `ripgrep` binary is found, return null and do not attempt to exec `rg` elsewhere.
Ensure `rg` on your system is not provided. Ensure that chat responses are still shown (with no file path hallucination filtering).

fall back to less context if `rg` is not available

---

vscode/src/editor/vscode-editor.ts

Recipes that provide information about code (such as an explanation) should work on read-only files.
Recipes that modify files in-place should use the VS Code `vscode.workspace.fs.isWritableFileSystem` extension API to see if the document's URI scheme is writable. This commit does NOT update all recipes to check that because that is a fairly rare case and we are evolving the recipes UX right now.
Open a virtual file (such as using the RemoteHub extension). Try running a recipe on it. It should succeed.

support working with recipes, etc., on virtual files

---

vscode/CHANGELOG.md
vscode/src/completions/index.ts

In VS Code, if you run the `Trigger Inline Suggestion` action manually (instead of just typing to trigger completions), 3 suggestions will be fetched instead of 1. This is because the user's intent in this case is more likely to get multiple options, and latency is not as critical.
Run `Trigger Inline Suggestion` and ensure there are 3 suggestions provided. Hover over the gray ghost text to see the button to cycle through the other suggestions.

get 3 completions when manually triggered

---

lib/ui/src/chat/TranscriptItem.module.css

Closes #[55187](https://github.com/sourcegraph/sourcegraph/issues/55187) - adds bottom padding to last assistant row to avoid feedback hover overlap.
Web before
Web after
VS Code before
VS Code after
- Ensure compatibility across Clients

Feedback overlap fix

---

.vscode/launch.json
vscode/src/log.ts
vscode/src/main.ts

This makes it easier to test settings and auth in the extension host without interfering with your main instance of VS Code.
n/a; dev only

helpful VS Code launch profile for running a separate instance

---

lib/shared/src/telemetry/EventLogger.ts
lib/shared/src/telemetry/index.ts
vscode/src/chat/ChatViewProvider.ts
vscode/src/chat/ContextProvider.ts
vscode/src/chat/MessageProvider.ts
vscode/src/chat/protocol.ts
vscode/src/completions/logger.ts
vscode/src/configuration.ts
vscode/src/external-services.ts
vscode/src/local-context/local-keyword-context-fetcher.ts
vscode/src/main.ts
vscode/src/services/AuthProvider.ts
vscode/src/services/EventLogger.ts
vscode/src/services/InlineController.ts
vscode/src/services/LocalStorageProvider.ts
vscode/src/services/telemetry.ts
vscode/test/completions/run-code-completions-on-dataset.ts
vscode/webviews/App.tsx
vscode/webviews/Chat.tsx
vscode/webviews/ConnectApp.tsx
vscode/webviews/Login.story.tsx
vscode/webviews/Login.tsx
vscode/webviews/utils/telemetry.ts

There is no significant change to the telemetry event data that is sent up (except for a few reductions in the event properties when we were sending up complex objects).
- Add a few more tracked events related to the signup flow.
- Introduce a new `TelemetryService` with the same API as `logEvent` but that is not global.
- Use the `TelemetryService` interface in the VS Code webviews as well instead of manually passing events.
- Clean up other code.
- Simplify EventLogger.log to only take public event props. Previously, the event logger took 2 args: event properties and public properties. The former was a superset of the latter and contained private information that could end up in, for example, the audit log. This is not needed for Cody's telemetry. See …

refactor telemetry service for VS Code extension

---

vscode/src/configuration.test.ts
vscode/src/configuration.ts

The default of triggerMoreEagerly was changed in vscode/package.json but not in code. The prior change was sufficient to make the default true, but the code was misleading. (We could improve this by making the TypeScript code in configuration.ts be aware of the JSON Schema of our configuration.)
n/a

fix default of triggerMoreEagerly in code

---

vscode/package.json

These are not documented and are not very useful since VS Code runs a watch task in the background when you open it to edit this project anyway.
n/a

rm unused/unneeded vscode build scripts

---

.github/workflows/vscode-insiders-release.yml
.github/workflows/vscode-stable-release.yml

Previously only the unit tests were being run. (The full test suite was being run in the normal post-push CI, but not for releases specifically. It should be run for releases in case someone wants to tag or trigger an arbitrary commit that's not the HEAD of a pushed branch to be a release commit.)
n/a

run full vscode test suite before release

---

lib/shared/src/configuration.ts
vscode/package.json
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/services/EventLogger.ts

Makes it possible for users to disable Cody's extension telemetry.
Set `cody.telemetry.level` to `off` and run Cody. Ensure `cody.debug.enabled` is `true`. Note in the output channel that there are lines starting `logEvent (telemetry disabled)`, which indicate a noop call to telemetry logging.

add cody.telemetry.level VS Code setting to control telemetry

---

vscode/src/completions/completion.test.ts
vscode/src/completions/language.ts
vscode/src/completions/multiline.ts
vscode/src/completions/shared-post-process.ts
vscode/src/completions/text-processing.ts
vscode/src/completions/utils/text-utils.ts

Fixes bad completion case https://github.com/sourcegraph/cody/discussions/358#discussioncomment-6531096
After hours of catching corner cases, I think we can't rely on regexp-based `shouldIncludeClosingLine` logic here. Counting brackets doesn't provide much value when we don't know about the structure of the expression where we try to insert completions. This PR just tries to handle the simple case with an empty completion line with a closed bracket symbol and cut off this completion. 
@philipp-spiess I don't think I fully understand how this is possible, but unit tests tell me that completion should be cut off, but vscode manual test shows that this problem is still there. Let me know if you have a minute for a quick pair on this.
- Try to force `}` completion (see original GitHub …

Completion: fix bad trailing `}` completion 

---

vscode/src/services/InlineController.ts

This handles issue #169 .
I tested manually with responses in the form of a paragraph.

Add naive html escaping for inline chat.

---

lib/shared/src/chat/recipes/chat-question.ts
lib/shared/src/chat/recipes/helpers.ts
vscode/CHANGELOG.md
vscode/src/chat/ChatViewProvider.ts
vscode/src/chat/protocol.ts
vscode/src/main.ts
vscode/test/integration/helpers.ts
vscode/webviews/App.tsx

Current the `Chat History` command does not show you the Chat History view:
This is because chat history command was using showTab('history') is doing the same thing as the `setWebviewView(view)` but only accepts `chat` as the view, which is confusing and redundant.
TIncluded in this PR:
- removed `showTab` and move to `setWebviewView`
- moved `isTextTooShort` to helper function ([context](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1690215101604749?thread_ts=1690214874.981619&cid=C04MSD3DP5L))
- updated type error for the test token command
locally tested and all the tests are still passing after the change

fix: chat history command and remove setTab

---

vscode/src/chat/ContextProvider.ts
vscode/src/repository/builtinGitExtension.d.ts
vscode/src/repository/repositoryHelpers.ts

This is more portable (to the web) and compatible (to non-web platforms where git is not installed, not in `$PATH`, or not configured, which has been the source of many user bug reports).
Open a workspace with no `cody.codebase` setting and ensure the chat sidebar shows the correct repository at the bottom in the context indicator.

use VS Code git extension to get remote URL instead of exec'ing

---

lib/shared/src/sourcegraph-api/completions/browserClient.ts
lib/shared/src/sourcegraph-api/completions/client.ts
lib/shared/src/sourcegraph-api/completions/nodeClient.ts

They both use the standard `fetch` API, so the impl can be shared.
Nothing was using the browser complete method yet, so this does not change anything today, it only allows future use of this by browser clients.
n/a

reuse SourcegraphCompletionsClient.complete across browser/node

---

.eslintrc.js

Adds about ~500ms to some eslint invocations and is not critical.
n/a

disable slow eslint no-deprecated rule

---

vscode/.vscodeignore
vscode/package.json
vscode/resources/cody-icons.woff

Even though the `.vscodeignore` intended to un-ignore `cody-icons.woff`, it was being ignored during the packaging process and the status bar icon was showing as a character similar to `B`.
Install from `.vsix` and confirm the status bar icon is correct.

fix Cody status bar icon in release builds

---

vscode/CONTRIBUTING.md
vscode/doc/releases.md

use consistent language for insiders (builds vs. releases vs. channel)

---

vscode/package.json

Just learned about this when reviewing @sqs's changes. 🙈

Autocomplete: Use enum for finite config options

---

vscode/src/completions/index.ts

We usually resolve cached results instantly. However, if the inserted completion would
include more than one line, this can create a lot of visible UI churn. To avoid this, we
debounce these results and wait for the user to stop typing for a bit before applying
them.
The duration we wait is longer than the debounce time for new requests because we do not
have network latency for cache completion.
- Observe that a multi-line completion resolved from cache is now delayed a bit and if you keep typing (at least in my natural speed) it doesn't annoy you anymore
https://github.com/sourcegraph/cody/assets/458591/ab00b5d6-ed59-477f-9c8c-1e1aa1229d91

Autocomplete: Delay mutli-line cached completions

---

.vscode/launch.json
vscode/CONTRIBUTING.md
vscode/package.json
vscode/src/dev/helpers.ts
vscode/src/extension.common.ts

Previously, the Cody sidebar *always* opened upon startup during debugging. This was not needed for development on non-sidebar-related features. It is also nice to have a way to open the autocomplete trace view on startup.
n/a

add dev helpers to focus sidebar on startup or open trace view

---

.vscode/launch.json

It is sometimes useful to toggle GitHub Copilot on and off to test that there are no conflicts.
It is not needed to disable sourcegraph.cody-ai as that is done automatically when the extension under development has the same identifier.
n/a

do not disable other autocomplete extensions when debugging

---

vscode/src/completions/index.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/provider.ts
vscode/src/completions/request-manager.ts
vscode/src/completions/tracer/index.ts
vscode/src/completions/tracer/traceView.ts

Records the params, raw results, and post-processed results.
n/a

trace calls to completion providers

---

vscode/src/completions/completion.test.ts

c.f. https://github.com/sourcegraph/cody/pull/393
This changes the completion examples in the docs once again to match the style of tabby: https://sourcegraph.com/github.com/TabbyML/tabby/-/blob/clients/tabby-agent/src/postprocess/testUtils.ts?L22:17-22:23
- Tests pass

Autocomplete: Use tabby style helpers for completion strings in tests

---

lib/shared/src/chat/context.ts
lib/shared/src/editor/index.ts
lib/ui/src/chat/inputContext/ChatInputContext.story.tsx
lib/ui/src/chat/inputContext/ChatInputContext.tsx
vscode/src/chat/ContextProvider.ts
vscode/src/editor/vscode-editor.ts

`ActiveTextEditor.selection` is super confusing because we also have `ActiveTextEditorSelection`. The latter is just for the selection contents, whereas the former is for the selection range.
Rename so people don't have to run into the same pain that I did
Name change only. Quick check that we don't have any usage that isn't picked up by TS

Cody: Rename confusing `selection` to `selectionRange`

---

vscode/package.json

Quick command to run local dev in vscode insiders.
Aside from being a good way of testing new features, it has another benefit that it makes it super easy to open Cody in the same folder as you're currently working. Meaning you can dogfood stuff like `/fix` changes easier.
Checked runs locally

Cody: Add dev:insiders command for VS Code

---

vscode/test/completions/run-code-completions-on-dataset.ts

Small improvement to the `run-code-completions-on-dataset.ts` script. Use the provider name to name the generated completions dataset file.
- Generate test completions
- Dataset file will use the name of the configured provider

Add provider name to generated completions datasets

---

lib/shared/src/configuration.ts
vscode/package.json
vscode/src/completions/completion.test.ts
vscode/src/completions/index.ts
vscode/src/completions/logger.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/main.ts
vscode/test/completions/completions-dataset.ts
vscode/test/completions/run-code-completions-on-dataset.ts

This behavior has been available for 3 weeks and default for 1 week. It has not generated any complaints, and it has coincided with a significant increase in completion acceptance rate and usage. Removing the ability to disable it seems safe and simplifies the code.
n/a

always use triggerMoreEagerly behavior (remove config to disable it)

---

vscode/src/completions/completion.test.ts
vscode/src/completions/context-local.ts
vscode/src/completions/context.ts
vscode/src/completions/history.ts
vscode/src/completions/index.ts
vscode/src/main.ts
vscode/test/completions/run-code-completions-on-dataset.ts
vscode/test/integration/api.test.ts

`class History -> interface DocumentHistory, class VSCodeDocumentHistory`
Just a code refactor.
n/a

extract History to DocumentHistory

---

vscode/src/completions/index.ts

This was only needed for the `cody:`-scheme document used for showing manual completions, which was removed (https://github.com/sourcegraph/cody/pull/326).
n/a

rm unneeded check for cody scheme

---

vscode/src/completions/document.ts
vscode/src/completions/index.ts
vscode/src/completions/multiline.ts

Just a type and naming improvement.
n/a; just a code refactor

extract DocumentContext and rename currentLine{Prefix,Suffix}

---

vscode/src/extension.common.ts
vscode/src/main.ts
vscode/src/services/EventLogger.ts

I noticed this interfering with my own "organic" telemetry and making it harder for me to understand my own usage of Cody. Now, only usage in the main VS Code window (not in a test, and not in a debug extension host instance) counts. This could increase the likelihood of errors in our actual telemetry, but that is mitigated by our heavy use of the Cody insiders build.
n/a

disable telemetry when extension is running in dev or test mode

---

vscode/src/completions/cache.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/provider.ts
vscode/src/completions/providers/unstable-azure-openai.ts
vscode/src/completions/providers/unstable-codegen.ts
vscode/src/completions/providers/unstable-fireworks.ts
vscode/src/completions/providers/unstable-huggingface.ts
vscode/src/completions/request-manager.test.ts
vscode/src/completions/request-manager.ts
vscode/src/completions/shared-post-process.ts
vscode/src/completions/tracer/traceView.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.test.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.ts
vscode/src/main.ts
vscode/test/completions/run-code-completions-on-dataset.ts

No impl changes. This is just so that we can better separate the VS Code-specific stuff from the rest (and helps with future commits).
This is an intermediate commit that will make our history cleaner. I submitted it as a separate PR so that the Git history includes the rename as an atomic operation.
n/a

move provider to vscodeInlineCompletionItemProvider.ts

---

package.json
pnpm-lock.yaml

The completions-review-tool uses remix, which uses deasync, which only has prebuilt binaries for older Node.js versions (https://github.com/abbr/deasync-bin). This means that CI takes 1-2 extra minutes and is flakier due to node-gyp being invoked each time. This commit skips the node-gyp build of deasync. It may break some aspects of the completion-review-tool (although it seems to work fine), but that's an acceptable tradeoff for now because that is a dev-only tool and we can revert this commit if it is needed.
n/a

never build deasync to speed up and de-flake builds

---

package.json
pnpm-lock.yaml

The playwright post-install script downloads and installs many browsers, which takes a long time. It's not needed, sinc we explicitly download and install them in the `vscode/package.json` `test:e2e` build script.
n/a

skip playwright post-install scripts to speed up build 

---

vscode/test/integration/task-controller.test.ts

Example of flake: https://github.com/sourcegraph/cody/actions/runs/5722519632/job/15505777631
n/a

skip flaky `Cody Fixup Task Controller` integration test

---

vscode/package.json

Currently our local development commands fail to load the extension, as it seems `extensionDevelopmentPath` expects an absolute path. (`extensionDevelopmentPath` isn't actually documented 😢 )
This PR updates it to use this (this is how it was before).
`cd vscode`
`pnpm run dev`
Check Cody loads

Cody: Fix dev commands

---

vscode/src/completions/logger.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.test.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.ts

Even when `cody.autocomplete.experimental.completeSuggestWidgetSelection` is false, still try to return a completion even if the suggest widget is showing. This completion will often not be shown to the user (but we now check for that case in telemetry). This removes complexity from the provider code.
Set `editor.inlineSuggest.suppressSuggestions` to true. See that Cody autocomplete shows up when the insertText of the suggest widget selection matches the prefix of the completion (even without enabling the Cody experimental setting).

try to show completion when suggest widget is showing

---

vscode/src/completions/vscodeInlineCompletionItemProvider.ts

Previously, we swallowed any exceptions here and just returned empty. Now we re-throw the error after logging it. This has no change in behavior, since VS Code already catches and logs any exceptions from inline completion item providers, treating them as `[]`. It does make it easier for us to identify bugs.
To confirm that VS Code catches these exceptions and logs them, see the `Extension Host` output channel:
```
2023-07-31 21:25:37.693 [error] [sourcegraph.cody-ai] provider FAILED
2023-07-31 21:25:37.694 [error] Error: asdf
at InlineCompletionItemProvider.provideInlineCompletionItems (/home/sqs/src/github.com/sourcegraph/cody/vscode/src/completions/vscodeInlineCompletionItemProvider.ts:129:19)
...
```
I also triggered it more than 10 times to see if it eventually would terminate a …

do not swallow provideInlineCompletionItems exception

---

vscode/src/completions/vscodeInlineCompletionItemProvider.test.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.ts

This reduces UI jitter in VS Code; when typing or deleting individual characters, VS Code reuses the existing completion while it waits for the new one to come in. This is also accomplished by our existing caching when forward-typing, but this even further reduces it.
Type `const country =` and wait for it to suggest something like `'USA'`. Type the first few letters of the suggestion then delete. With this change, the suggestion still displays. Without this change, it disappears.

return completions from the start of current line to reduce VS Code UI jitter

---

vscode/src/completions/shared-post-process.ts
vscode/src/completions/text-processing.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.test.ts

I noticed some odd duplications in multi-line completion snippets that was caused by a difference only in trailing whitespace. Since my IDE does this on save automatically anyways, I figure it's save to filter the LLM output for this. I noticed this to be an issue in both Anthropic and StarCoder, but Anthropic encounters it more often.
- Added a test case

Autocomplete: Remove trailing whitespace

---

completions-review-tool/data/anthropic-1690966785443.json
completions-review-tool/data/starcoder-16b-fireworks-1690965883693.json
completions-review-tool/data/starcoder-7b-fireworks-1690965610208.json
completions-review-tool/src/components/CompletionsTable.module.css
completions-review-tool/src/routes/_index.tsx
vscode/test/completions/completions-dataset.ts
vscode/test/completions/run-code-completions-on-dataset.ts

StarCoder (the OSS code completion LLM) has recently released a new 7b version of their model. I wanted to post a brief update about that:
- The performance difference between the 15.5b and 7b models aren’t super big
- I think the biggest improvement we can make at this point is for either provider (including Anthropic) to use the streaming APIs and terminate the request if we detect the end since they all might overshoot (and every subsequent unused token just incurs a waiting time). We could do this on the client or on the server but the latter might require us to port more logic to Go.
- The hosted OSS models are actually performing really well in terms of latency. I know this is a limited data and the anthropic request is also routed via the SG server where as the other isn’t, but …

Autocomplete: Add infilling test case and capture new StarCoder 7b results

---

vscode/src/services/StatusBar.ts

The checkboxes now occupy the left column and the text is aligned.
New:
Compare to the current (not left-aligned):
n/a

left-align items in the cody status bar enable menu

---

vscode/package.json

In the VS Code comment UI, ctrl+enter/cmd+enter should submit the comment. Unfortunately, when GitHub Copilot is activated, it does nothing. This is likely a bug in GitHub Copilot's overly greedy keyboard bindings (it should have `&& !commentEditorFocused` in the `when` for `github.copilot.generate`).
To make that keybinding submit the comment in VS Code's comment UI again, work around this by disabling that keybinding when Cody is running (it is not possible to be more selective about when we disable the keybinding). This is reasonable because that is not a frequently used keybinding anymore for Copilot.
Run VS Code with both Cody and GitHub Copilot. Open our inline chat and try pressing ctrl+enter/cmd+enter after you've typed a comment to submit it. It should work.

fix problem with github copilot suppressing ctrl+enter in comment UI

---

vscode/package.json
vscode/src/configuration.test.ts
vscode/src/configuration.ts

I personally found these distracting to have on by default (although I am super happy to see the commands stuff in!!), and I bet users would agree (especially users who haven't started using the features yet). I am sure they help with feature discovery, but let's run with them disabled-by-default for a bit until we can find a better way for discovery and/or until this feature is really lovable.
n/a

disable commands code lens and editor title icon by default

---

vscode/package.json
vscode/src/configuration.ts

I got confused by not seeing it there. :)
n/a

add cody.experimental.nonStop as setting for internal discoverability

---

vscode/webviews/vite.config.ts

With an inline sourcemap, `vscode/dist/webviews/index.js` is 18.8MB. With a separate sourcemap file, it is 1.8MB. The sourcemap file is 13MB, so even including it, there's still a big reduction. And now the sourcemap is only loaded for debugging, not for routine execution, which surely must be a perf improvement.
n/a

use separate vscode webview source map to cut bundle by 17MB

---

vscode/src/chat/ContextProvider.ts

Added `onDidChangeActiveTextEditor` so that context status get published whenever active text editor changes.
[Sourcegraph Issue](https://github.com/sourcegraph/sourcegraph/issues/52542)
https://github.com/GitStartHQ/client-sourcegraph-cody/assets/51731962/180ce3da-34fc-49dc-a4df-8a90de63fe68
Run the vscode extension from `Run and Debug` or `cd vsocde && pnpm run dev `

fix: Context file item UI out of sync with file events (VS Code)

---

vscode/src/completions/providers/unstable-fireworks.ts

Changing the default model used for the fireworks config to use the 7b one.
👀

Autocomplete: Use the 7b version of StarCoder by default

---

vscode/src/repository/repositoryHelpers.ts

fix: handle errors from Git extension APIs
Wrap calls to Git extension APIs in try/catch blocks to avoid crashes if APIs throw errors or are unavailable.
Log warnings if extension is unavailable or inactive instead of throwing errors.
added error handling

fix: handle errors from Git extension APIs

---

vscode/src/custom-prompts/utils/helpers.ts

This fixes an issue where Cody (on Linux at least) would watch the user's home directory and exhaust the system's open files limit. This appears to be due to a bug or limitation in VS Code's `createFileSystemWatcher` API where `RelativePattern` globs are not optimized and instead set up recursive watchers on the first arg given (which, for the user's home dir, causes a very large number to be created).
To reproduce the issue, uncomment this code and then look for the following in the VS Code logs for file watchers (see below for how to enable these):
```
TRACE [File Watcher (parcel)] Request to start watching: /home/sqs
```
(`/home/sqs` is my home directory, and the file watcher then starts to traverse all dirs and set up ~250,000+ inotify watches.)
See …

fix ~/.vscode/cody.json recipes file watch that exhausted system

---

.tool-versions
package.json

Reverts sourcegraph/cody#497
Some weird build issues is happening since this was merged. Here's an example log: https://github.com/sourcegraph/cody/actions/runs/5762909352/job/15623607192
CI is complaining that the pnpm version on CI is not `8.6.11` but the `pnpm/action-setup@v2` [should read the correct version](https://github.com/pnpm/action-setup#version) via `packageManager` from the package.json 🤔 
Let's revert for now and I can take a closer look next week if no-one else has any ideas? 
This is a revert

Revert "chore(deps): update pnpm to v8.6.11"

---

vscode/src/custom-prompts/utils/helpers.ts
vscode/src/services/LocalAppDetector.ts

Noticed the file watchers for the custom commands config file (cody.json) are currently not working as the second param is set to empty when we created the `RelativePattern`.
Based on the [vscode API docs](https://code.visualstudio.com/api/references/vscode-api#workspace.createFileSystemWatcher), the second param should be set to `*` for watching changes in a specific file (when first param is set to file path, TIL!).
I've also updated the file watchers we added to watch `Cody.app` to reflect this:
```
// AFTER
TRACE [File Watcher (node.js)] Started watching: '/Applications/Cody.app'
// BEFORE
TRACE [File Watcher (node.js)] Started watching: '/Applications'
```
https://github.com/microsoft/vscode/blob/a330b89e5d83293bacee75ac910626b64ad8c3fd/src/vscode-dts/vscode.d.ts#L11339-L11343
make …

fix: relative patterns for file watchers

---

vscode/CHANGELOG.md
vscode/src/completions/providers/anthropic.ts

Autocomplete: Include current file name in anthropic prompt

---

vscode/CHANGELOG.md
vscode/src/chat/MessageProvider.ts

RE: https://sourcegraph.slack.com/archives/C05AGQYD528/p1691422532897009
fix: command filter regex
Currently, typing /r or /reset would reset the chat as expected, but if you create a new slash command that starts with `r`, for example, `/release`, it would still perform the reset command because of the current REGEX we are using for the `/reset` command. 
This PR fixes that issue along with the same issue for `/search` and `/fix`
submitting chat with `/read` should not perform `reset` 
submitting chat with `/stop` should not perform `search` 
submitting chat with `/fox` should not perform `fix.` 
submitting chat with `/read` performs `reset` 
submitting chat with `/stop` performs `search` 
submitting chat with `/fox` performs `fix`

fix: command filter regex

---

vscode/src/completions/document.ts
vscode/src/completions/getInlineCompletions.test.ts
vscode/src/completions/getInlineCompletions.ts
vscode/src/completions/request-manager.test.ts
vscode/src/completions/request-manager.ts
vscode/src/completions/reuse-last-candidate.ts
vscode/src/completions/utils/text-utils.test.ts
vscode/src/completions/utils/text-utils.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.test.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.ts

Add the next non-empty line to the "last candidate" logic. This way we can detect wether a multi-line completion was already inserted. If the suffix has changed this dramatically, the last candidate is no longer relevant and we should instead issue a new request.
https://github.com/sourcegraph/cody/assets/458591/329c9bb5-5c4b-4467-95ca-b9a6b4769dd9

Autocomplete: Check next non-empty line for last candidate test and network cache

---

vscode/CHANGELOG.md
vscode/src/chat/MessageProvider.ts

RE: https://sourcegraph.slack.com/archives/C05AGQYD528/p1691104523645779
fix: handle aborted messages correctly
This PR proposed to check `isMessageInProgress` before treating abort errors as real errors. This avoids chat being hung indefinitely on the `socket hang up` error, which is the same error that returns for aborted messages.
Issue: the onCompletionEnd method was being called after aborting completion that produces the `socket hang up` error, but it does not cover cases where `socket hang up` is returned for errors that were not caused by calling `abort`, leaving the chat to be stuck with `stop generating` indefinitely until the user clicks on the `stop generating` button to mark it as completed manually. 
See Demo:
After: the `stop generating` button still works accordingly in …

fix: handle aborted messages correctly

---

vscode/package.json

#53908 introduced a stray system-wide "Reload Window" action. This reverts that change and fixes #601.
| - | - |
| <img width="556" alt="Screenshot 2023-08-08 at 11 52 25 am" src="https://github.com/sourcegraph/cody/assets/153/77c354f3-e0b9-43c2-8b7d-4f7e4ab6934c"> | <img width="556" alt="Screenshot 2023-08-08 at 11 53 09 am" src="https://github.com/sourcegraph/cody/assets/153/d3d5f518-08aa-4d27-a913-d4357e23e37d"> |
- Opened views, checked reload option doesn't exist
- Used the Cody Settings palette to enable/disable features, click "Reload Window" in notification and verified still works

VSCode: Don't add "Reload Window" actions to all views

---

vscode/CHANGELOG.md
vscode/webviews/FileLink.module.css

RE: https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1691431852119019
The file link color was changed from `--vscode-textLink-foreground` to `--vscode-button-secondaryForeground` for the `link-button`
This makes the file links match the styling of the secondary buttons we currently use for the[ file links component](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/webviews/Chat.module.css?L45), providing a more consistent user experience.
Before:
[Shades of Purple](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple)
Material theme palenight HC
Light+ theme
Dark+
After:
[Shades of Purple](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple)
Material theme palenight HC
Light+ theme
Dark +

fix: change file link color to match buttons

---

vscode/package.json
vscode/src/services/StatusBar.ts
vscode/walkthroughs/autocomplete.md

Given the whole extension is in beta we don't need to label these two features as individually in beta.
| - | - |
| <img width="1147" alt="Screenshot 2023-08-08 at 8 03 52 pm" src="https://github.com/sourcegraph/cody/assets/153/ca714706-3b66-4441-847e-fc6ad9bb3159"> | <img width="1147" alt="Screenshot 2023-08-08 at 8 03 06 pm" src="https://github.com/sourcegraph/cody/assets/153/ef8e7c9e-cf53-46a9-b1fb-1303137d9f06"> |
- Opened Cody settings, verified renders

VS Code: Remove beta labels from features

---

lib/ui/src/Chat.tsx
vscode/CHANGELOG.md
vscode/src/custom-prompts/utils/menu.ts
vscode/test/e2e/custom-command.test.ts
vscode/webviews/ChatCommands.tsx

separated from https://github.com/sourcegraph/cody/pull/602
- Add tab-to-complete && enter-to-complete behavior for matching commands in chat box
- Allow selecting a chat command by pressing enter in addition to tab
Hide Suggestions when the `/` command box is activated:
Additional clean up:
- Clear command selection when submitting input if no command selected
- Only show suggestions if no command list is open
- Use chatCommands prop directly instead of filtering to commands with slashCommand
tab to complete:

command: add tab-to-complete

---

vscode/src/completions/providers/unstable-fireworks.ts

- Removes the minimum tokens to sample, the model can now yield nothing if nothing is probably. This feels nicer than always forcing a completion and still seems to always provide tokens when it makes sense
- Increases the context window length to be more equivalent to our Anthropic prompt 
Played with it locally, this is not stable anyways.

Autocomplete: Tweak StarCoder options

---

vscode/src/completions/getInlineCompletions.ts

Models that support infilling do not replace an existing suffix but
instead insert the completion only at the current cursor position. Thus,
we do not need to compare the suffix

Autocomplete: Fix suffix matching logic for FIM models

---

lib/shared/src/configuration.ts
vscode/CHANGELOG.md
vscode/src/chat/ContextProvider.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/services/StatusBar.ts

This adds the existing configuration setting called experimentalEditorTitleCommandIcon that adds cody icon that can be used to toggle showing the chat `command menu` in the editor title bar:
The setting is defaulted to false. When enabled, it will show the icon that can be clicked to open the command menu.
This also updates the status bar service to respect this new setting when determining whether to show the icon as enabled or not.
Related components updated:
- configuration.ts
- StatusBar.ts
- ContextProvider.ts
- configuration.test.ts
Cody icon only shows up in the title bar when the setting is set to true:

add experimentalEditorTitleCommandIcon > statusbar

---

lib/shared/package.json

Release `cody-shared` v0.0.5 ([version list on npm](https://www.npmjs.com/package/@sourcegraph/cody-shared?activeTab=versions)).
N/A

Bump cody-shared package version

---

vscode/src/completions/context/context.ts
vscode/src/completions/getInlineCompletions.ts
vscode/src/completions/logger.ts

- We now add the context summary to the `suggested` and `accepted` events so I we can better understand the correlation of context and when completions are accepted
- The types were also unified so that it's easier to add more fields
- Removes the networkRequestStarted event. We don't really need it and it's high volume. 
- Add the `source` to the `suggested` and `accepted` events so we know how many completions are served from either caching mechanism.
```
█ logEvent (telemetry disabled): CodyVSCodeExtension:completion:suggested {"multiline":true,"providerIdentifier":"anthropic","languageId":"typescript","type":"inline","multilineMode":"block","contextSummary":{"duration":0.21250000596046448},"source":"CacheAfterRequestStart","latency":1098.0695829987526,"displayDuration":531.024041995406 …
```

Autocomplete: Various analytic improvements

---

vscode/src/chat/ChatViewProvider.ts
vscode/src/chat/protocol.ts
vscode/src/services/AuthMenus.ts
vscode/src/services/AuthProvider.ts
vscode/src/services/LocalAppDetector.ts
vscode/webviews/App.story.tsx
vscode/webviews/App.tsx
vscode/webviews/Login.tsx

Refactor vscode input boxes for instance URL and access token.
Refactor the code to make it possible to just show an access token input box.
Do not show Cody app login when running in VS Code Web
Support VS Code Web in login flow: VS Code Web does not support callbacks like vscode:// from our access token creation flow because it is running on the web and does not have a system protocol handler registered. There is a solution to this, but it requires changes on the Sourcegraph.com backend. So, for now, just open up the new access token creation page and ask the user for the token.
Start with a fresh VS Code instance and try signing in via Sourcegraph.com or via a token.

support signing in on VS Code Web

---

vscode/src/services/EventLogger.ts

Prefer the runtime package json over the version that is inlined during build times. This
way we will be able to include pre-release builds that are published with a different version
identifier.
c.f. https://sourcegraph.slack.com/archives/C05AGQYD528/p1691591325810769
We'll test this in the next pre-release build 😬

Prefer runtime package.json for logger version

---

vscode/src/completions/providers/unstable-fireworks.ts

Fireworks renamed the starcoder 7b model.
Tested locally:
- Enable the fireworks provider (refer to https://sourcegraph.slack.com/archives/C05AGQYD528/p1690551781096999 for the API secrets)
- Trigger an autocomplete request
- Verify that a response comes back

Autocomplete: Fix fireworks model name

---

vscode/src/completions/getInlineCompletions.ts
vscode/src/completions/logger.ts
vscode/src/completions/request-manager.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.ts
vscode/src/main.ts

These are a few tweaks that hopefully makes us understand why in some niche situations with low `n`, we see so many accepted events. 
I have not found anything in the logging that would explain it so far so I’m also going to include the log IDs (which are 100% anonymous) so we can cross match exactly what accepted event belongs to what completion.
- We now include the log `id` with all completion events
- The output console was cleaned up. The deleted logger calls were redundant information
- Completion suggestion events now have an additional `accepted` field
- This field will be set in the same run loop as we also log the `completion:accepted` events and the idea here is that might not need two different event types but can instead simplify the logging to only one event per autocomplete …

Autocomplete: More analytics tweaks

---

vscode/src/completions/utils/text-utils.test.ts
vscode/src/completions/utils/text-utils.ts

😱 this is a huge oversight from my side. Thankfully this is only used for a very niche case in the multiline detection logic that isn't used much so there's no big impact.
- Fixed the test case

Autocomplete: Fix previous non-empty line

---

vscode/CHANGELOG.md
vscode/src/completions/getInlineCompletions.test.ts
vscode/src/completions/getInlineCompletions.ts
vscode/src/completions/logger.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.test.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.ts
vscode/test/completions/run-code-completions-on-dataset.ts

This PR fixes an issue that sometimes caused completion suggestion events to not fire correctly. The issue here was that we decided wether or not a completion is visible in the `getInlineCompletions` code that was now change to _still yield completions_.
The yielding is fine, we have relied on these results to be used for the last candidate cache. However, this would also mean that we would store a log id that was _deemed as not visible_ but that never reconsidered this condition. This meant that such a completion could become visible later and we would be able to accept it, even though it was never logged as suggested.
To fix this, we move this logic into the VS Code specific part (which conceptually makes more sense anyways since it's full of VS Code specific logic) and also test the …

Autocomplete: Fix suggestion event over counting

---

vscode/CHANGELOG.md
vscode/package.json

This PR is preparing for a patch release (we need to at least bump the version on `main` so I can cherry-pick this onto a release branch).
I think all of the changes referenced in the change log so far small enough to be part of the patch release but I would like someone else to weigh in here too (cc @toolmantim @dominiccooney @abeatrix @beyang @kalanchan @vovakulikov).
I went over [all individual commits since the 0.6.5 release](https://github.com/sourcegraph/cody/compare/vscode-v0.6.5...main) to make sure we have not forgotten anything and so I think we can cherry-pick everything from `main` for this patch.
**Note:**
@abeatrix wants to get another bug fix in.
This is just a version bump.

VS Code: Release 0.6.6

---

agent/src/agent.ts
agent/src/vscode-shim.ts

Requires https://github.com/sourcegraph/sourcegraph/pull/55775
Handle `onDidChangeConfiguration` so that registered handlers in e.g. `vscode/src/main.ts` are actually invoked. This lets us hard-code the configuration in e.g. `client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java`
n/a

handle configuration updates

---

vscode/package.json
vscode/src/completions/providers/createProvider.ts
vscode/src/configuration.ts
vscode/src/main.ts
vscode/test/completions/run-code-completions-on-dataset.ts

- Show error messages during provider creation in the output channel instead of (a) in a notification (which is annoying and shows up for each keystroke) or (b) in the webview, which is not somewhere the user would necessarily look for autocomplete-related issues.
- Do not default to the Anthropic provider if an invalid provider is specified. If the user is specifying a provider in `cody.autocomplete.advanced.provider`, their intent is likely to use a non-default provider, and falling back to Anthropic would not be desired.
- Remove the duplication in calls to `createCompletionsProvider`.
- Update settings docstrings.
(My initial motivation for this is that I got annoying VS Code notifications while hacking on a new unstable autocomplete provider based on Ollama.)
Set …

overhaul autocomplete provider config

---

vscode/src/completions/providers/unstable-codegen.ts
vscode/src/completions/providers/unstable-fireworks.ts
vscode/src/completions/providers/unstable-huggingface.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.ts

This PR removes the same line suffix from all fill-in-middle providers. There are multiple reasons for this:
- For single line completions, we don't want to match the same line suffix in some cases. consider this file:
```
for (let i = 0; i < array.length; █)
``` 
We actually want this to complete with `i++) {` (notice the added opening brace) and replace the existing `)`.
- Some models like StarCoder doesn't seem to be too happy with same line suffixes resulting in responses that _sometimes have the same line suffix repeated and sometimes not_.
Some recent change to try to deal with this better resulted in a pretty big regression with the FIM models (I think this is what @olafurpg experienced today too, so I think it's better to just remove it all-together.
This _can_ result in …

Autocomplete: Truncate same line suffix from prompt

---

lib/shared/src/chat/recipes/next-questions.ts

When working on a proof of concept for using ML to determine if code context is needed for Cody, @novoselrok and I noticed that my "is context needed" classifier was getting hit with text which included messages about next questions. It turns out that the `NextQuestions` recipe calls the `getContextMessages` function with the full prompt message as the text, including the recipe specific prompt prefix / suffix. @novoselrok and I believed that this was unintentional/likely a bug and that `getContextMessages` was meant to be called with only the text of the user query, `truncatedText`.
This PR changes the call to `getContextMessages` to use `truncatedText` instead of the fully prompt with the recipe specific info. If we misunderstood and the status quo is intended behavior, then please feel …

Potential bug fix in next questions recipe

---

vscode/src/completions/getInlineCompletions.ts

The behavior of only logging when it *was* an abort error was mistaken. It might be useful to only log when it is *not* an abort error, but for now, let's log in all cases.
n/a

always log error from getInlineCompletions

---

agent/package.json
agent/src/agent.ts
agent/src/index.test.ts
agent/src/jsonrpc.ts
agent/src/vscode-shim.ts
agent/tsconfig.json
agent/vitest.config.ts
lib/shared/src/configuration.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/main.ts

Previously, autocomplete via agent wasn't working because of regressions that got introduced in the last PR to fix ESLint errors. We have integration tests that caught this regression but we don't run that test in CI because it currently requires SRC_ACCESS_TOKEN.
This PR fixes the regression above along with other improvements:
- Use latest Node.js for agent binaries because the VSC extension is using APIs that are not present in Node.js v16 (version we previously used for the agent) causing the agent to crash.
- Remove leftover `console.log`
- Fix failing integration test after we added a new agent recipe
- Fail fast when running the extension via the agent and we don't register the completion provider. We currently await on the completion provider, which silently times out if we don't …

Agent: code cleanup and get autocomplete working again

---

vscode/CHANGELOG.md
vscode/src/completions/logger.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.ts
vscode/src/main.ts

Part of #672
Adds tracking for number of inserted characters per completion request.

Autocomplete: Log number of accepted chars per suggestion

---

vscode/CHANGELOG.md

PR to move items from pull/602 to the unreleased section.
I forgot to update the changelog before I merged https://github.com/sourcegraph/cody/pull/602, which was not included in 0.6.6 release.
changelog updated

fix changelog from pull/602

---

agent/src/agent.ts
agent/src/index.test.ts
agent/src/protocol.ts
agent/src/vscode-shim.ts
vscode/src/main.ts

Adds a debug notification to Agent, extensions can list to this notification to receive the debugging information that is generated in Agent during commands like autocomplete. 
Run extension with debug enabled verify debug messages received.
Run extension with debug disabled verify no debug messages received.

Agent: add debug notifications for clients to receive debug messages

---

lib/shared/src/chat/prompts/utils.ts
lib/shared/src/chat/recipes/custom-prompt.ts

This PR updates to correctly replace the `{languageName}` string in prompt text. 
Check the output channel after running the /smell command

fix: replace {languageName} in custom prompt

---

lib/shared/src/sourcegraph-api/graphql/client.ts
vscode/src/configuration.ts

Closes https://github.com/sourcegraph/cody/issues/686
It's currently only the JetBrains plugin that relies on the `isAgentEnabled` flag, and the JetBrains plugin is logging events for itself. To avoid double logging, this PR disables logging in the agent in this case.
I also updated the docs for the flag to convey the sentiment of using the flag, and document the exceptions.
I couldn't get any logs, so couldn't really test this. I've tried to spy on the traffic with [Fiddler Everywhere](https://www.telerik.com/fiddler/fiddler-everywhere), but it couldn't see anything.

Agent: Suppress telemetry if agent is running and update docs

---

lib/shared/src/chat/prompts/templates.ts
lib/shared/src/chat/prompts/vscode-context.ts
lib/shared/src/chat/recipes/custom-prompt.ts
lib/shared/src/prompt/templates.ts
vscode/CHANGELOG.md

Currently, we are using `getContextMessagesFromSelection` to generate context message for the current file, which is incorrect as that includes context from other files as well.
This PR adds `getCurrentFileContextFromEditorSelection` that generates context message for the current file using the current editor selection / visible content to replace `getContextMessagesFromSelection`, which generate context message using embeddings search result returned from the selection.
Run the /explain or /smell command that uses the current file as context. You should only see that it reads 1 file.

custom command: update get context for current file

---

agent/src/AgentWorkspaceDocuments.ts
agent/src/agent.ts
agent/src/editor.ts
agent/src/protocol.ts
agent/src/vscode-shim.ts
vscode/src/testutils/mocks.ts

Previously, `VSCodeEditor` was not working correctly because the agent shim for `vscode` was not implementing the following APIs
- `window.activeTextEditor`
- `workspace.getWorkspaceFolder`
This PR fixes the issue so that `VSCodeEditor` works even when running inside the agent.
@chwarwick tested this change manually and confirmed it works as expected.

Agent: implement more `vscode` APIs

---

agent/src/agent.ts
agent/src/protocol.ts
agent/src/vscode-shim.ts

Add a codebase setting to the ExtensionConfiguration (renamed from ConnectionConfiguration).  This allows the agent's internal version of the vs code extension to operate in the mode where the codebase is manually set instead of inferred from  the git remote of the current file.  
Tested by using the JetBrains extension to set the codebase in the configuration and verified that the contextProvider used the codebase to fetch embeddings for autocomplete context.

Agent: add codebase setting to configuration

---

lib/shared/src/chat/recipes/context-search.ts

Fixed typo in context-search.ts comment
n/a

Fixed typo in context-search.ts

---

vscode/src/chat/ChatViewProvider.ts
vscode/src/main.ts
vscode/src/services/InlineController.ts

RE: https://sourcegraph.slack.com/archives/C05AGQYD528/p1692117220217969?thread_ts=1692054351.708989&cid=C05AGQYD528
Moved tracker for copy and paste event to inline controller
█ logEvent (telemetry disabled): CodyVSCodeExtension:inlineChat:Copy:clicked {"op":"copy","charCount":73,"lineCount":4}
█ logEvent (telemetry disabled): CodyVSCodeExtension:inlineChat:Paste:clicked {"op":"paste","lineCount":4,"charCount":73}
█ logEvent (telemetry disabled): CodyVSCodeExtension:inlineChat:Copy:clicked {"op":"copy","charCount":20,"lineCount":1}
█ logEvent (telemetry disabled): CodyVSCodeExtension:inlineChat:Paste:clicked {"op":"paste","lineCount":1,"charCount":20}
█ logEvent (telemetry disabled): CodyVSCodeExtension:insertButton:clicked {"op":"insert","charCount":228,"lineCount":8}
█ logEvent …

fix duplicate paste events for telemetry log

---

vscode/CHANGELOG.md
vscode/src/custom-prompts/menus/CustomCommandBuilderMenu.ts
vscode/src/custom-prompts/menus/index.ts

This removes the `ignoreFocusOut: true` settings on our command quickpick, removing the need for you use to press `esc` in the input to dismiss it. This makes it feel just as quick and light as the standard `cmd-shift-p` command palette.
The one downside to removing it is if you need to change your code selection mid-quickpick-item-selection, but given the standard command palette has commands that depend on code selection too (e.g. "Transform to Kebab Case") I think we should follow their suit and not introduce the extra bit of friction that requiring `esc` adds.
- Opened command palette
- Clicked outside it and verified it dismisses

Don't require Esc to dismiss Cody menu

---

vscode/CHANGELOG.md
vscode/src/custom-prompts/menus/index.ts

This change makes the VS Code command menu match on the command description, not just the title. 
This enables searching `/`commands in the menu.
Demo:

commands: match commands on description

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/services/AuthMenus.ts
vscode/src/services/StatusBar.ts

There's lots of goodies hidden away in our settings menu that you can only access via the statusbar. This adds a settings icon to the main title bar to help people discover these more easily. You can also now access it via the VS Code command palette.
- Opened Cody
- Clicked the button

Add a settings button to Cody pane header

---

agent/src/index.test.ts
agent/src/protocol.ts
agent/src/vscode-shim.ts

New agent configuration values were added to support additional autocomplete providers, this updates them to be optional and sets the defaults the same as the vs code extension
test add to confirm working agent with minimal configuration.

Agent: make advanced autocomplete configuration optional 

---

vscode/src/completions/providers/unstable-fireworks.ts

This just updates the model name after a conversation with Fireworks. 
- Configure the StarCoder model (c.f. [sourcegraph.slack.com/archives/C05AGQYD528/p1690551781096999](https://sourcegraph.slack.com/archives/C05AGQYD528/p1690551781096999))
- See that completions work again

Autocomplete: Fix starcoder model name again

---

vscode/src/completions/vscodeInlineCompletionItemProvider.ts

This is a leftover from #655 that removed the different branching and makes sure the same line suffix is truncated for FIM models too. 
- Configure the StarCoder model (c.f. [sourcegraph.slack.com/archives/C05AGQYD528/p1690551781096999](https://sourcegraph.slack.com/archives/C05AGQYD528/p1690551781096999))
- Get a completion returned that has a different same line suffix 
- Observe the event will no longer be logged as displayed after the fix

Autocomplete: Remove suffix matching bail for FIM models

---

vscode/CHANGELOG.md
vscode/src/non-stop/FixupCodeLenses.ts
vscode/src/non-stop/FixupController.ts
vscode/src/non-stop/codelenses.ts

RE: https://sourcegraph.slack.com/archives/C03CSAER9LK/p1692000660788579
Add a new Code Lens for discarding Fixup suggestions.
Currently user MUST accept the change and undo the change to get rid the code lens. This button will remove all that on click.
Added Discard lens:

fixup: add code lens to discard fixup suggestion

---

vscode/src/services/AuthMenus.ts

Trim spaces from the instance url and the access token in VSCode, to avoid copy-paste errors in which some whitespace gets accidentally pasted into the input.
- Run tests
- Test auth flow manually

Trim values in vscode auth menu

---

agent/src/jsonrpc.ts

Previously, there was no good way for the NeoVim client to debug the incoming/outgoing messages of the agent. This PR fixes the problem by optionally writing all JSON messages to a trace file through the environment variable `CODY_AGENT_TRACE_FILE`.
Manually tested by @pjlast

Agent: add support to trace JSON messages

---

agent/src/vscode-shim.ts

I got an error previously, complaining about `env.clipboard.readText` miissing.
Added it in this PR.
Tested it with the JetBrains plugin. It builds and works with the new version of the shim, and the warning is gone.

Agent: Add clipboard to VS Code shim

---

agent/package.json

We have two cases of this fixing an error related to `Could not resolve "@sourcegraph/cody-shared"`
n/a

Agent: always build parent directory first

---

vscode/webviews/Chat.module.css

Fixes #614.
Secondary button backgrounds are transparent in many themes. This doesn't work with the kind of overlapping design we have, so on hover I'm flipping to the primary button hover theme.
1. Open Cody chat, `show me hello world in Rust`
2. Hover over the code, confirm the insert, copy buttons appear.
3. Hover over each button, confirm the button is legible and has a background.

Use primary button theme on hover for insert, copy.

---

vscode/src/completions/getInlineCompletions.test.ts
vscode/src/completions/multiline.ts
vscode/src/completions/utils/text-utils.ts

Fixes https://github.com/sourcegraph/cody/discussions/358#discussioncomment-6519606
As it is described in GH discussion, we shouldn't make multiline completion for cases like function or method 
invocation (but we should do this in case of method or function declaration). 
So this PR gates multiline completion behind this regexp check (regexp isn't ideal, but this is what we have to
work with until we get parsers working) You can check this regexp [here](https://regex101.com/r/k85odc/1)
- Check that completion doesn't try to do multiline complete if your cursor is within arguments
position of function or method invocation/call statement

Don't trigger multiline completion in case of function or method invocation

---

vscode/src/chat/MessageProvider.ts

**NOTE: The core functionality of this PR has been replaced by https://github.com/sourcegraph/cody/pull/704**
Solves https://github.com/sourcegraph/cody/issues/699 
Currently the search doesn't scroll down because when the context search result is be sent to transcript `onCompletionEnd` is being called(This is an edge case recipe because it involves no LLM calls or streaming).   
https://github.com/sourcegraph/cody/blob/23ce972044869cbfca2cd31b20dd85293d4b1771/vscode/src/chat/MessageProvider.ts#L387-L388
If you look at `onCompletionEnd` function you can see that it has `isMessageInProgress` is set to false "before" the transcript is sent to the webview. The problem with having the `isMessageInProgress` is that it doesn't push the window down when it gets the result. So I am calling …

Adding support for downward scrolling when a search operation is performed on Cody

---

lib/ui/src/Chat.tsx
vscode/CHANGELOG.md
vscode/test/e2e/custom-command.test.ts
vscode/test/e2e/history.test.ts
vscode/webviews/Chat.module.css
vscode/webviews/Chat.tsx

This revamps the chat input with better styling (high contrast outline support, proper border radius, etc), autoresizing support for long lines and narrow screens, and a command button.
https://github.com/sourcegraph/cody/assets/153/07d8e3c0-d9a4-4591-bf22-87d2cfc55a2b
| - | - |
| <img width="884" alt="Screenshot 2023-08-18 at 12 24 50 am" src="https://github.com/sourcegraph/cody/assets/153/381152a7-8fe5-413d-9f70-ee0f6dcd2957"> | <img width="884" alt="Screenshot 2023-08-18 at 12 23 56 am" src="https://github.com/sourcegraph/cody/assets/153/41598e31-88c6-491b-b039-39724dec57df"> |
| <img width="884" alt="Screenshot 2023-08-18 at 12 25 00 am" src="https://github.com/sourcegraph/cody/assets/153/185de523-49d8-4c43-8f5c-1d7024abf407"> | <img width="884" alt="Screenshot …

Add autoresizing and command button to chat input

---

lib/ui/src/chat/Transcript.module.css
lib/ui/src/chat/Transcript.tsx

Chat scroll pinning was broken for `/search` because that adds messages in quick succession and the React effect was only looking at the change in message author.
The general approach was also iffy because we were basically polling the scroll position on updates, but in practice scrolling works best when it is managed asynchronously by the browser.
This takes a different approach:
- Use CSS scroll anchoring. This takes care of 90% of what we want with pinning the scroll position to the bottom: If you scroll away from the anchor, the scroll position doesn't change, the browser manages all of this for us. We also get better behavior when you resize the panel; the scroll position will stick to the bottom pretty intelligently.
- Because browsers anchor the scroll position to the top until …

Use CSS scroll anchoring for most chat scroll pinning

---

vscode/CHANGELOG.md
vscode/src/completions/getInlineCompletions.test.ts
vscode/src/completions/text-processing.ts

We learned that Anthropic is giving us worse results with trailing whitespace in the prompt.
To fix this, we started to trim the prompt.
However, when the prefix includes a line break, the LLM needs to know that we do not want the
current line to complete and instead start a new one. For this specific case, we're injecting
a line break in the trimmed prefix.
This will only be added if the existing line is otherwise empty and will help especially with
cases like users typing a comment and asking the LLM to provide a suggestion for the next
line of code:
// Write some code
█
- Added a test case

Autocomplete: Include up to a single new line in the Anthropic prompt

---

agent/src/editor.ts

Previously, the agent crashed when executing a recipe when the client hadn't provided any text document selection.
- Start IntelliJ with an open file but no selection
- Send a chat message. Nothing happened, it was stuck in processing mode and the "Stop generating" button is just there.

Agent: recipes/execute - handle empty selection

---

agent/src/agent.ts
agent/src/protocol.ts
lib/shared/src/chat/client.ts
lib/shared/src/sourcegraph-api/graphql/client.ts

Previously, the JetBrains plugin still sent direct network requests to the Sourcegraph instance. This was problematic because it meant that users behind proxies had to configure both proxy settings for the agent and for the Java plugin. This PR adds two endpoints to the Agent protocol allowing the JetBrains plugin to send requests to the Agent instead of sending network requests to Sourcegraph.
Tested alongside JetBrains PR

Agent: add requests for logging events and to find user ID

---

vscode/CHANGELOG.md
vscode/src/completions/vscodeInlineCompletionItemProvider.test.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.ts
vscode/src/main.ts
vscode/src/services/FeatureFlagProvider.ts
vscode/test/completions/run-code-completions-on-dataset.ts

Tweak single-line autocomplete debounce time depending on `'cody-autocomplete-increased-debounce-time-enabled'` feature flag value. 
As we restrict feature flags evaluation only to dotcom users, the actual events data should be checked on dotcom instance `event_logs` table ([docs](https://docs.sourcegraph.com/dev/how-to/use_feature_flags#measure-the-effect-of-a-feature-flag)). 
During the development I tested the functionality in the following way:
- remove (comment out) `isDotCom` condition in `FeatureFlagProvider` methods
- run local Sourcegraph instance (`sg start`)
- log in to the local instance as admin and add `'cody-autocomplete-increased-debounce-time-enabled'` feature flag
- sign it to the local Sourcegraph instance in Cody VSCode extension
- launch the VSCode extension from the …

Add increased autocomplete debounce time feature flag support

---

agent/src/vscode-shim.ts
lib/shared/src/sourcegraph-api/graphql/client.ts

Previously, we used the `isRunningInsideAgent` config to determine whether telemetry should be disable or not. This solution had the problem that we actually want to send telemetry from the agent when the client sends the recently added `graphql/logEvent` request. We just want to disable telemetry for vscode-specific events.
This PR fixes the problem by reverting the previous `isRunningInsideAgent` check and adds a check based on the `cody.telemetry.level` configuration setting. The shim hardcodes the value to `'off'` making telemetry disabled when running inside the agent, while the telmetry level defaults to `'all'` when we manually construct the GraphQL client.
Manually tested the following steps with @chwarwick 
- Added `console.log({event: event.name, telemetry: …

Agent: disable telemetry only via the shim

---

vscode/src/chat/MessageProvider.ts
vscode/src/custom-prompts/CommandsController.ts

Since we are already logging default command being called in MessageProvider, we should only log custom command in the command controller.
check output channel to confirm default commands are not being logged twice.

log custom command only

---

agent/src/agent.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
lib/shared/src/sourcegraph-api/completions/client.test.ts
lib/shared/src/sourcegraph-api/completions/client.ts
lib/shared/src/test/mocks.ts
vscode/CHANGELOG.md
vscode/README.md
vscode/src/completions/getInlineCompletions.test.ts
vscode/src/completions/getInlineCompletions.ts
vscode/src/completions/processInlineCompletions.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/provider.ts
vscode/src/completions/providers/unstable-azure-openai.ts
vscode/src/completions/providers/unstable-codegen.ts
vscode/src/completions/providers/unstable-fireworks.ts
vscode/src/completions/providers/unstable-huggingface.ts
vscode/src/completions/request-manager.test.ts
vscode/src/completions/streaming.ts
vscode/src/completions/text-processing.ts
vscode/src/completions/tracer/traceView.ts
vscode/src/completions/utils.ts
vscode/src/external-services.ts
vscode/src/main.ts
vscode/test/completions/mock-vscode.ts

This adds a backward-compatible support for using the new streaming backend added in https://github.com/sourcegraph/sourcegraph/pull/55967.
It currently only works in Node.js because the node-fetch polyfill we use returns native Node streams and not unified browser streams. However given that browser support is not official right now, I decided that for now (especially until we know this experiment is giving us wins) it's not worth to add a separate implementation.
This all works by the new `stream` bool option on the server. When set and the server has the changes in https://github.com/sourcegraph/sourcegraph/pull/55967, we return an SSE event stream. On the client, we can check the header values for wether we got a streaming response and use that.
Architecture wise this is not super …

Autocomplete: Use streaming to early-terminate Anthropic requests

---

agent/src/agent.ts

GraphQL mutations to record log events were failing from agent because arguments and public arguments are required to be strings. 
./gradlew -PforceAgentBuild=true :runIde
Added logging in agent to ensure log mutation requests were successful.

Agent: Log arguments need to be strings 

---

lib/shared/src/chat/chat.ts
lib/shared/src/chat/typewriter.ts
lib/shared/src/chat/useClient.ts
vscode/src/chat/MessageProvider.ts
vscode/test/integration/chat.test.ts
vscode/test/integration/helpers.ts
vscode/test/integration/recipes.test.ts

The Typewriter was integrated at a convenient point for other agents possibly, but it didn't work well for Cody-VScode. VScode's BotResponseMultiplexer buffers content to parse tags in the output, which chunks the incremental effect a bit. The typewriter also slowed down consumers like inline fixups which just want the complete code and don't care if it appears "typed."
Since then, Cody-VScode has added LLM turns for keyword expansion and context re-ranking. The typewriter effect also applied to these, needlessly slowing them down. For me these turns are about twice as fast now the typewriter is out of their path.
This moves the typewriter up to the MessageProvider, and only applies the typewriter effect to output destined for the chat sidebar. This makes all the code consumers faster …

Move typewriter so it does not throttle keyword expansion, reranker

---

vscode/src/chat/ContextProvider.ts

This should reduce the amount of needless work done when the user (for example) holds down the arrow key in a document to change the cursor position.
Switch files while the sidebar is open and confirm the new filename is shown at the bottom.

throttle updates of context to chat sidebar

---

vscode/src/non-stop/FixupController.ts
vscode/src/non-stop/FixupTypingUI.ts
vscode/src/non-stop/TaskViewProvider.ts
vscode/src/non-stop/codelenses.ts
vscode/src/non-stop/utils.ts
vscode/src/services/CodeLensProvider.ts
vscode/src/services/InlineController.ts
vscode/test/e2e/fixup-decorator.test.ts
vscode/test/e2e/task-controller.test.ts

- Use "Cody is working" label instead of "Asking Cody". "Working" makes sense for inline refactors *and* questions. "Asking" makes less sense for inline refactors.
- Eliminate weird-looking spaces in `' / '`.
n/a

improve 2 Cody text labels

---

vscode/CHANGELOG.md
vscode/webviews/Chat.tsx

Partially implements #633 with new welcome message text:
Reason for the partial implementation is that there's currently no way to embed images or a component in the welcome markdown, so we couldn't include the illustrations as per the Figma.
Closes #633
- Started a new chat, verified welcome text

New welcome chat words

---

vscode/src/completions/getInlineCompletions.ts
vscode/src/completions/logger.ts
vscode/src/completions/utils.ts

Start to log unexpected errors during autocomplete (so everything that is not an abort error or a rate limiting error). To avoid overflowing the events log, errors are logged as cumulative counts grouped by the message with the first event logged immediately and every subsequent requests being debounced by a 5 minute timer.
- Open the VS Code extension in dev mode
- Open the outputs panel for Cody
- Disable your network connection
- Observe the following to only be logged once in the output console
```
█ logEvent (telemetry disabled): CodyVSCodeExtension:completion:error {"message":"request to https://sourcegraph.com/.api/completions/code failed, reason: getaddrinfo ENOTFOUND sourcegraph.com","count":1}
```

Autocomplete: Log errors

---

vscode/CHANGELOG.md
vscode/src/services/InlineController.ts

When the inline chat is disabled, we'd still show the comment thread UI during extension startup before we "fix" it by removing it again. This is causing unnecessary visual churn so we now check the settings right away.
https://github.com/sourcegraph/cody/assets/458591/51f9e2a7-91d1-4fbc-9555-49cb68fd211f

Do not init inline controller on startup when disabled

---

vscode/CHANGELOG.md
vscode/src/completions/request-manager.test.ts
vscode/src/completions/request-manager.ts

Right now, a completion can be resolved while the network request is still being in progress if a previous completion request matches the new editor text. This happens in ~10% of situations and was responsible for a small increase in latency.
I noticed that we did not abort the request if that is the case though and we still used the second response to the seed the cache. I think in this case, this is not necessary since we already have a completion that matches and that we consider a "match" for the given prefix. I think that we should rather preserve the costs and network bandwidth in this case.
To think through this:
- 👉 User starts by typing `console.l` and waits a few MS
- ➡️ We start request 1 with the prefix `console.`
- 👉 User continues to type until it reaches `console.log`
- ➡️ …

Autocomplete: Abort network requests when a completion request is resolved with a previously started request's response

---

.vscode/cody.json

Remove Compare open tabs from workspace command
/compare should be removed from your command menu

remove compare open tabs from workspace command

---

vscode/package.json

Unblocking the VS Code release by removing the web build temporarily 
```
α vscode (ps/rm-web-build)
pnpm run build
> cody-ai@0.8.0 build /Users/philipp/dev/cody/vscode
> tsc --build && pnpm run -s _build:esbuild:desktop && pnpm run -s _build:webviews --mode production
dist/extension.node.js      6.0mb ⚠️
dist/extension.node.js.map  9.6mb
⚡ Done in 144ms
vite v4.4.3 building for production...
✓ 438 modules transformed.
../dist/webviews/index.html                0.78 kB
../dist/webviews/codicon-2d58c995.ttf     70.78 kB
../dist/webviews/index-024934e3.css       57.90 kB
../dist/webviews/index.js              1,759.42 kB │ map: 12,839.48 kB
✓ built in 2.20s
```

Unblock VS Code release by removing the web build

---

vscode/package.json

This builds now for real 😓 
```
α vscode (main)✗
pnpm vsce package --no-dependencies
Executing prepublish script 'npm run vscode:prepublish'...
> cody-ai@0.8.0 vscode:prepublish
> pnpm -s run build
dist/extension.node.js      6.0mb ⚠️
dist/extension.node.js.map  9.6mb
⚡ Done in 149ms
vite v4.4.3 building for production...
✓ 438 modules transformed.
../dist/webviews/index.html                0.78 kB
../dist/webviews/codicon-2d58c995.ttf     70.78 kB
../dist/webviews/index-024934e3.css       57.90 kB
../dist/webviews/index.js              1,759.42 kB │ map: 12,839.48 kB
✓ built in 2.18s
DONE  Packaged: /Users/philipp/dev/cody/vscode/cody-ai-0.8.0.vsix (196 files, 27.05MB)
INFO
The latest version of @vscode/vsce is 2.20.1 and you have 2.19.0.
Update it now: npm install -g @vscode/vsce
```

Unblock the VS Code build #2 - Remove the web build from package.json

---

lib/shared/src/chat/useClient.ts

Pre-req for https://github.com/sourcegraph/sourcegraph/issues/55363. Updates the signature of `CodyClient.initializeNewChat()` to accept an optional arg `newScope` which, if provided, will be used to set the new transcript's scope state. Retains the same defaults if arg is omitted. 
Manual testing with/without arg provided. Ensure unit tests still pass.

lib/shared: add arg to optionally initialize chat with a specific scope

---

lib/shared/package.json

Bumps the version for cody-shared to prepare for publishing.
N/A

lib/shared: bump package version

---

vscode/webviews/Notices/VersionUpdatedNotice.tsx

Adds a 'v' to the start of the version number in the update notice.
| - | - |
| <img width="385" alt="Screenshot 2023-08-22 at 12 28 20 pm" src="https://github.com/sourcegraph/cody/assets/153/605afbb2-171d-438c-92a2-cdde8c700370"> | <img width="385" alt="Screenshot 2023-08-22 at 12 27 59 pm" src="https://github.com/sourcegraph/cody/assets/153/6202ff14-bf50-454a-a1af-9a8cf22b98a7"> |
- Inspected the UI, verified 'v' was added

Add a 'v' to the start of the version number in the update notice

---

.github/workflows/vscode-insiders-release.yml

🤞  (It's just a CI step that runs after the publishing so it shouldn't break anything)

Add notification when nightly build fails

---

vscode/webviews/Chat.tsx

Adds a tooltip to the command and send message buttons:
<p><img src="https://github.com/sourcegraph/cody/assets/153/487c6ba7-8eeb-4ee6-896f-e18dc0973964" width="321"></p>
<p><img src="https://github.com/sourcegraph/cody/assets/153/c49d51bc-f1b1-4bdf-b9e1-8bee64096428" width="321"></p>
Thanks to @philipp-spiess for the feedback!
- Hovered over button
- Witnessed tooltip

Add tooltips to the chat input buttons

---

vscode/CHANGELOG.md
vscode/src/services/InlineController.ts

fix: add null checks before accessing editor properties
The code to track copy action from inline chat was accessing properties on the editor object without first checking if it was null. This adds null checks before accessing the document and uri properties to avoid potential null reference errors.
This should fix an issue that I run into where VS Code is complaining about `Cannot read properties of undefined (reading 'scheme')` when I try to start a new chat session:
I'm not sure what the exact steps to reproduce the issue I run into, but try interacting with Cody without using inline chat, then make changes to your text document and then start a new conversation, you should not see the error message about `Cannot read properties of undefined (reading 'scheme')`:

fix: add null check to inline controller on change

---

agent/src/agent.ts

Sets `useContext` to `'embeddings'` so that chat messages with agent can use embeddings.
Does this make sense?

Enable embeddings in chat in agent

---

vscode/CHANGELOG.md
vscode/src/chat/MessageProvider.ts

CLOSE: https://github.com/sourcegraph/cody/issues/757
Currently the stop-generating button returns an error in UI:
fix: handle message abort errors gracefully
Included in this PR:
- Set isMessageInProgress to false for abort error
- Send transcript after handling abort error to let webview know there is no message in progress so that the `stop-generating` button will be removed from UI
Run a command and then click on the `stop-generating` button, you should not see any error:
We should also look into adding a test for the stop-generating button

fix: handle message abort errors gracefully

---

vscode/CHANGELOG.md
vscode/src/chat/MessageProvider.ts
vscode/src/main.ts

fix: handle /fix command by executing `cody.fixup.new`
This PR includes:
- The `/fix` command now executes the `cody.fixup.new` command during the `chatCommandFilter` instead of executing the fixup recipe that returns an error (see image below). This allows the fixup flow to be handled in the correct way.
- The `cody.fixup.new` command now accepts the correct args to generate a fixup task. Previously, it was only accepting `range`, which is used as `options` and gets passed down incorrectly.
2. Type `/fix` with instruction (e.g. /fix rename function to foo) in sidebar chat
###. Before: An error pop up saying "select some code to fixup" even when you have an active selection

fix: support /fix command in chat

---

agent/src/agent.ts
agent/src/jsonrpc.ts
agent/src/protocol.ts
agent/src/vscode-shim.ts
vscode/src/testutils/mocks.ts

Previously, the agent didn't support canceling autocomplete requests. This PR adds support for cancellation through the new `$/cancelRequest` notification, which mirrors the structure of the same notification in LSP.
Manually tested with IntelliJ here https://github.com/sourcegraph/sourcegraph/pull/56119

Agent: add cancelation support

---

agent/package.json
agent/src/esbuild.mjs
agent/src/vscode-shim.ts
lib/shared/src/prompt/prompt-mixin.ts

Previously, Cody Chat would regularly complain how it doesn't understand the language `undefined` when running through the agent. This PR fixes the issue by implementing `vscode.env.language` in the `vscode` shim.

Agent: implement `vscode.env.language`

---

.github/workflows/ci.yml
vscode/src/chat/GraphContextProvider.test.ts
vscode/src/chat/GraphContextProvider.ts

This PR modifies the initial implementation in #692 to not only track definitions _within the current user selection_, but also _definitions of symbols referenced in fetched definitions_. This goes two hops deep in the code navigation graph, but the implementation is general enough to go an arbitrary number of hops by updating a `recursionLimit` global variable.
Existing unit tests; validated by hand.

Intelligent Cody: Fetch locations multiple hops in the graph

---

vscode/package.json
vscode/test/e2e/helpers.ts
vscode/test/e2e/install-deps.ts
vscode/test/integration/main.ts

Updates the VScode version to 1.81.1 from 1.79.2.
Tells Playwright to just download Chromium and ffmpeg instead of all browsers. This saves roughly 200MB of serialized downloads. Chromium is required for now because Electron is a Chromium and Playwright expects to find Chromium in that configuration.
Changes the test:e2e launch to download VScode and Playwright in parallel.
Pre-caches VScode for test:e2e. Previously this download happened as under the auspices of the test runner and could hit test timeouts which, sadly, restarted the download from scratch on the very next test.
(macOS, adjust paths for other platforms)
```
rm -rf ~/Library/Caches/ms-playwright/*
rm -rf vscode/.vscode-test
pnpm test:e2e  # should see VScode and Playwright download concurrently
pnpm test:e2e  # test runs w/ …
```

vscode e2e: Download less, faster, update VScode version

---

vscode/CONTRIBUTING.md
vscode/test/README.md
vscode/test/e2e/README.md

I keep forgetting the difference between test/e2e and test/integration, so document that.
This is a doc-only change.

vscode: Add docs about the purpose of different kinds of tests

---

agent/src/jsonrpc.ts

* Run IntelliJ
* Open settings
* Update endpoint URL
* Click "Apply" button
* Confirm there is no stack trace from the agent

Agent: fix bug when reading `.id` from null

---

vscode/CHANGELOG.md
vscode/webviews/Chat.module.css

RE: https://github.com/sourcegraph/cody/issues/812
fix: use editor font and line height in chat view
- Set font family and size in code blocks to match editor font.

fix: use editor font for code blocks in chat view

---

.github/workflows/vscode-insiders-release.yml
vscode/src/chat/GraphContextProvider.ts

I don't know why but for some reason we can't import from`'@sourcegraph/cody-shared'` directly. I've seen this error a couple of times now. This time it was only noticable on CI though (which is weird, I thought we fixed that but perhaps the PR was not based on the latest changes on `main` yet).
Anyway, this should fix the import and also makes the CI notification more useful.
```
α vscode (ps/fix-insiders)
pnpm run build
> cody-ai@0.8.0 build /Users/philipp/dev/cody/vscode
> tsc --build && pnpm run -s _build:esbuild:desktop && pnpm run -s _build:esbuild:web && pnpm run -s _build:webviews --mode production
dist/extension.node.js      6.0mb ⚠️
dist/extension.node.js.map  9.7mb
⚡ Done in 228ms
dist/extension.web.js      5.0mb ⚠️
dist/extension.web.js.map  7.7mb
⚡ Done in 167ms
vite v4.4.3 …
```

Fix insders build and make CI notification pretty

---

lib/shared/src/chat/prompts/index.ts
vscode/CHANGELOG.md
vscode/src/chat/MessageProvider.ts
vscode/src/custom-prompts/CommandsController.ts
vscode/src/custom-prompts/CustomPromptsStore.ts
vscode/src/custom-prompts/PromptsProvider.ts
vscode/src/custom-prompts/utils/helpers.ts
vscode/src/custom-prompts/utils/menu.ts
vscode/test/e2e/custom-command.test.ts

Close https://github.com/sourcegraph/cody/issues/804
- fix issue where invalid json file for custom commands blocks command menu
- Wrap prompt loading in try/catch to handle errors
- Return empty prompt map on error instead of throwing
- Log errors loading prompts using debug logging
- Add editor-specific commands to the default commands list
- Create editor-specific commands with /fix
- Add alwaysShow option to createQuickPickItem
- Minor menu item cleaning
1. Remove a line from your current workspace config file for cody custom commands so you can see an inline error, ex:
2. You should still be able to open the command menu:
Before - you won't be able to open the command menu and see this error message instead:

fix: invalid json file for custom commands blocks command menu

---

vscode/src/services/InlineController.ts

Added a null check for Inline Controller event on editor change before reading the clipboard text.
This avoids potential null pointer exceptions that cause errors in console
check console log to see the errors gone!

add null check before accessing editor in inline controller

---

vscode/CHANGELOG.md
vscode/src/chat/ChatViewProvider.ts
vscode/src/chat/MessageProvider.ts
vscode/src/chat/protocol.ts
vscode/webviews/UserHistory.module.css
vscode/webviews/UserHistory.tsx

feat: add chat history export
- Add exportHistory method to export chat history to a JSON file
- Add UI button and logic to trigger history export 
- Update protocol to support new 'history' message for export and clear history action
This will make debugging easier, as it's been difficult to debug/compare context and chat issues as we have to go through each history item in UI manually. 
Before:
After:
try clicking on the Export button
https://github.com/sourcegraph/cody/assets/68532117/4e3fe075-c58d-474e-95ce-3bc196e04fa4

feat: add button to export chat history to JSON

---

vscode/src/chat/MessageProvider.ts

Follow up on https://github.com/sourcegraph/cody/pull/829
just realized it was exporting the current chat only instead of the entire chat history 🥴 
locally confirmed

export all chat history

---

vscode/src/completions/context/context-embeddings.ts

Noticed that embeddings for autocomplete were not refreshing every 5 min.  
Added temporary logging to confirm 
before:
```
embeddings for /projects/sourcegraph/cmd/frontend/backend/app.go are -3 minutes old
```
after:
```
embeddings for /Users/chriswarwick/projects/sourcegraph/cmd/frontend/backend/app.go are 1 minutes old
```

Fix autocomplete embeddings refresh condition

---

lib/shared/src/chat/recipes/fixup.ts
vscode/src/chat/MessageProvider.ts
vscode/src/custom-prompts/CommandsController.ts
vscode/src/custom-prompts/PromptsProvider.ts
vscode/src/custom-prompts/utils/menu.ts
vscode/src/main.ts
vscode/src/non-stop/FixupTypingUI.ts
vscode/src/services/InlineController.ts
vscode/test/e2e/fixup-decorator.test.ts
vscode/test/e2e/inline-assist.test.ts
vscode/test/e2e/task-controller.test.ts
vscode/walkthroughs/inline-assist.md

Next iteration on https://github.com/sourcegraph/cody/issues/631
Follow-up on https://github.com/sourcegraph/cody/pull/798
Updates `/fix` command labels to `/edit` according to the [design](https://www.figma.com/file/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?node-id=4560:14212&mode=dev).
||Before|After|
|-|--|--|
|Sidebar chat|<img width="299" alt="Screenshot 2023-08-28 at 11 23 56" src="https://github.com/sourcegraph/cody/assets/25318659/1e13d3b5-4363-4979-892b-bb82455d19dd">|<img width="299" alt="Screenshot 2023-08-28 at 11 22 50" src="https://github.com/sourcegraph/cody/assets/25318659/4298231a-7d32-4924-a07b-09f352ef88a0">|
|Main quick pick|<img width="602" alt="Screenshot 2023-08-28 at 11 24 12" src="https://github.com/sourcegraph/cody/assets/25318659/92216075-5fb0-4 …

rename /fix command to /edit

---

.vscode/settings.json

Makes `node_modules` visible in the VS Code explorer view.
Often, I need to dig into the implementation of the `npm` modules and modify their code for debugging purposes. 
The modified setting hides files from the explorer tree, which makes it hard to navigate the `node_modules` tree. `search.exclude` already prevents searches from going into the `node_modules` folder, so it should be fine keeping it accessible in the explorer view. We have the same setup in the main monorepo.
n/a

dx: show `node_modules` in the VS Code explorer

---

.vscode/settings.json

- Same as https://github.com/sourcegraph/cody/pull/838 but for `dist` folders
> Often, I need to dig into the built code for debugging purposes.
> The modified setting hides files from the explorer tree, which makes it hard to explore `dist` folders. `search.exclude` already prevents searches from going into `dist` folders, so it should be fine keeping it accessible in the explorer view. We have the same setup in the main monorepo.
n/a

dx: show `dist` in the VS Code explorer

---

vscode/src/completions/getInlineCompletions.ts
vscode/src/completions/logger.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/provider.ts
vscode/src/completions/providers/unstable-azure-openai.ts
vscode/src/completions/providers/unstable-codegen.ts
vscode/src/completions/providers/unstable-fireworks.ts
vscode/src/completions/providers/unstable-huggingface.ts

This is going to be necessary only for the Fireworks provider where we will ship with the option to change models. For the A/B experiment, we need to be able to filter out users that have configured a different `model` from the on we want to test against.
This PR now includes the model next to the provider identifier in the autocomplete logs.
Check the outputs tab
```
CodyVSCodeExtension:completion:suggested {"multiline":false,"providerIdentifier":"anthropic","providerModel":"claude-instant-1","languageId":"typescript","type":"inline","multilineMode":null,"id":"qmq2pshbi","contextSummary":{"duration":0.20449999906122684},"source":"LastCandidate","lineCount":1,"charCount":27,"latency":989.3145000003278,"displayDuration":721.9014170002192,"read":true,"accepted":true,"otherCompletionProviderE …
```

Autocomplete: Include model identifier with autocomplete logs

---

lib/shared/src/configuration.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/providers/createProvider.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/main.ts
vscode/test/completions/run-code-completions-on-dataset.ts

Tested that anthropic is still the default locally
```
█ AuthProvider:init:lastEndpoint: https://sourcegraph.com/
█ CodyCompletionProvider:initialized: provider: anthropic
```

Autocomplete: Add feature flag to enable Fireworks as the default provider

---

agent/src/AgentTextDocument.ts
agent/src/language-file-extensions.json
agent/src/language.test.ts
agent/src/language.ts
agent/tsconfig.json

Adds language detection to the AgentTextDocument, by porting over the language file extension file from the sourcegraph repo.  Added in additional languages to match the vscode languages for `javascriptreact` and `typescriptreact`  
resolves https://github.com/sourcegraph/cody/issues/785
unit tests added 
`./gradlew -PforceAgentBuild=true :runIde`
Verified that I got multi line autocompletes for typescript and react(typescript)
Verified logs contain the correct language id
```
[Trace - 04:48:07 PM] Sending request 'graphql/logEvent - (39)'
Params: {
"event": "CodyJetBrainsPlugin:completion:suggested",
"url": "",
"source": "IDEEXTENSION",
"referrer": "JETBRAINS",
"publicArgument": {
"latency": 805,
"displayDuration": 1283,
"isAnyKnownPluginEnabled": false,
"contextSummary": {
"embeddings": …
```

Agent: improve langage detection 

---

.github/workflows/vscode-insiders-release.yml
.github/workflows/vscode-stable-release.yml
vscode/src/completions/processInlineCompletions.ts

`main` builds is failing again with this:
```
FAIL  |vscode| src/completions/vscodeInlineCompletionItemProvider.test.ts [ vscode/src/completions/vscodeInlineCompletionItemProvider.test.ts ]
Error: Failed to resolve entry for package "@sourcegraph/cody-shared". The package may have incorrect main/module/exports specified in its package.json.
❯ packageEntryFailure node_modules/.pnpm/vite@4.4.3_@types+node@20.4.0/node_modules/vite/dist/node/chunks/dep-210e5610.js:28691:11
❯ resolvePackageEntry node_modules/.pnpm/vite@4.4.3_@types+node@20.4.0/node_modules/vite/dist/node/chunks/dep-210e5610.js:28688:5
❯ tryNodeResolve node_modules/.pnpm/vite@4.4.3_@types+node@20.4.0/node_modules/vite/dist/node/chunks/dep-210e5610.js:28422:20
❯ Context.resolveId …
```

Fix main: Don't use shared import

---

vscode/src/completions/processInlineCompletions.ts
vscode/src/completions/tree-sitter/parse-tree-cache.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.ts
vscode/src/main.ts

- Enables incremental parsing for tree-sitter by subscribing to `onDidChangeTextDocument` and forwarding `edit.contentChanges` to the existing parse-tree + calling `parser.parse(text, oldTree)`.
- Closes #850 
- Part of #809 
- Planned follow-up https://github.com/sourcegraph/cody/issues/860
- Existing unit tests
- Verified manually that parse-trees are correctly updated for all visible documents.

Autocomplete: use tree-sitter incremental parsing

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
lib/shared/src/sourcegraph-api/errors.ts
vscode/src/completions/client.ts
vscode/src/completions/logger.ts

This PR adds request tracing for autocomplete behind a feature flag. The plan is to enable tracing for 5% of the population so we can start collecting traces.
- Connect to localhost and throw in the `codecompletion.go` file
- Enable the FF for your user
- Observe that a trace ID is included in the error ping
```
█ logEvent (telemetry disabled): CodyVSCodeExtension:completion:error {"message":"error parsing response CodeCompletionResponse: SyntaxError: Unexpected token 'U', \"Unsupporte\"... is not valid JSON, response text: Unsupported custom model\n","traceId":"5a672ce14f16225b53e46f0afc6e02e9","count":1}
```

Autocomplete: Add tracing for network requests

---

pnpm-lock.yaml
vscode/package.json
vscode/src/completions/logger.ts
vscode/src/extension.common.ts
vscode/src/extension.node.ts
vscode/src/extension.web.ts
vscode/src/external-services.ts
vscode/src/services/EventLogger.ts
vscode/src/services/sentry/sentry.node.ts
vscode/src/services/sentry/sentry.ts
vscode/src/services/sentry/sentry.web.ts

This PR adds a simple setup for Sentry to be used inside the extension host thread. It does not set up any default integration and we will instead need to wrap top-level entry points with calls to `Setnry.captureException`.
This also wires up autocomplete errors to be routed to Sentry so we have an easy service in place to understand the reliability of the product.
Note: When the user is connected to an instance other than dotcom, this does not send any events. 
- Add a throw case into the anthropic handler
- Force the env to be production
- See that the error is logged to Sentry
I have also changed the backend to S2 and observed that no error is logged.

VSCode: Add Sentry to extension host process

---

vscode/src/chat/ChatViewProvider.ts
vscode/src/chat/MessageProvider.ts
vscode/src/configuration.ts
vscode/src/custom-prompts/CommandsController.ts
vscode/src/main.ts
vscode/src/notifications/setup-notification.ts
vscode/src/services/AuthProvider.ts
vscode/src/services/EventLogger.ts
vscode/src/services/LocalAppDetector.ts
vscode/src/services/SecretStorageProvider.ts

- A follow-up to https://github.com/sourcegraph/cody/pull/876: migrates other `localStorage` and `secretStorage` consumers to importing singletons instead of using them as arguments.
- Part of #874
The end goal of this effort (as stated in https://github.com/sourcegraph/cody/issues/874) is to decouple `getConfiguration` from the other entities in the codebase and introduce atomic and reactive getting for config values.
CI

VS Code: use singleton storage providers in rest consumers

---

package.json
vscode/src/services/sentry/sentry.ts

Sentry: Don't crash the extension when we can't init

---

.github/workflows/ci.yml
vscode/playwright.config.ts
vscode/test/e2e/helpers.ts
vscode/test/e2e/history.test.ts

This fixes the flaky E2E test. It tried to bring the Cody sidebar into the foreground but it was never hidden in the first place. I also added additional assertions about the `Hola` case that was not asserted on before.
This PR also brings back video uploads from failed cases so we can easily debug CI errors again.
- Checked with a failing E2E test

E2E tests: Upload recording artifacts and fix flaky test

---

vscode/src/completions/getInlineCompletions.test.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/text-processing/utils.ts

- Fixes one incorrect unit test.
- Uses a shared constant for a multiline completion stop sequence to ensure consistency.
CI

Autocomplete: improve `detectMultiline` unit tests

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/package.json
vscode/src/completions/providers/createProvider.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.ts

As part of our eval we want to test more than one model. Adding this second switch before our release will allow us to save 1-2 days because we don't have to do a patch release when we want to change the default.
Also tested everything locally where it turns out it didn't work before because the default was never `null` which needs to be added to the enum specifically.
👀

Autocomplete: Add model specific feature flags

---

vscode/src/completions/providers/unstable-codegen.ts

Bringing some of the recent changes to the provider logic to codegen too. 
- Make sure to use the right `fetch` version so we can benefit from TCP connection pooling
- Set the `Connection: 'keep-alive',` header for tcp connction pooling
- Remove post processing that is now part of the shared logic
👀

Autocomplete: Modernize codegen provider

---

.github/workflows/secrets-scan.yml

This PR adds _**non-blocking** secret scanning_ action to scan for verified secrets and notifies Security team.
Additionally, this github action check should execute on diff changes and takes ~30-60 seconds to execute.
We have implemented one already in [sourcegraph/sourcegraph](https://github.com/sourcegraph/sourcegraph/pull/56299) repo
CI should be 🟢  and notify security team if any verified secrets are reported by trufflehog.

Add trufflehog secret scanning

---

vscode/src/completions/client.ts

Request debug logging is currently not working for the stream reader because I forget to call `log?.onComplete`. There are two cases when we call this:
- Either when the request is aborted (i.e the stream is early terminated) and we log the last completely received message
- Or when the stream is exhausted and we have closed the request.
- Open the output console and see network requests being logged

Fix streaming logs

---

vscode/src/services/EventLogger.ts

#468 added a new mechanism to publish logs to a seperate env for test builds. However as part of it it added a new branch that sets `process.env.CODY_TESTING` to true in development builds which breaks the current assumption that this is only true in test runs.
It's important we don't set this flag in dev builds since it also changes a bunch of other small things in the extension so I’m reverting this here. Not to mention that this was also breaking the changes in #468 as my dev env was now flooded in these errors:
```
Error logging event Error: error fetching Testing Sourcegraph API: FetchError: request to http://localhost:49300/.api/testLogging failed, reason: connect ECONNREFUSED 127.0.0.1:49300 (http://localhost:49300/.api/testLogging)
at …
```

Fix dev build by not overwriting CODY_TESTING env

---

lib/shared/src/chat/prompts/index.ts
vscode/CHANGELOG.md
vscode/src/chat/MessageProvider.ts
vscode/src/custom-prompts/CustomPromptsStore.ts

RE: https://sourcegraph.slack.com/archives/C05AGQYD528/p1693983800785199
refactor: remove starter and premade fields from custom config
- Removed the `starter` and `premade` fields from the MyPrompts and MyPromptsJSON interfaces in the prompts module.
- Removed usage of the `premade` field in the MessageProvider class.
- Removed logs and telemetry related to the custom `premade` field.
Seems like permade was not working before as well so no harm in removing it
Move starter config option to user/workspace config
- set `starter` and `premade` in your cody.json
- Check the output log, the starter and premade strings should not be found anywhere in the output:
Before:

refactor: remove starter and premade from cody.json

---

vscode/package.json

dx: bump memory and disable warnings for the vscode `lint:js` script

---

vscode/src/dev/helpers.ts

In 80% of the times I start VS Code in dev mode, I need to open the output console and find Cody in the dropdown list. This will save me some precious seconds lol 
- Set `"cody.dev.openOutputConsole": true,` in the VS Code config
- Start VS Code in dev mode => See that the output console opens

Add dev flag to open output console on startup

---

vscode/CHANGELOG.md
vscode/src/completions/createVSCodeInlineCompletionItemProvider.ts

Feature flags in the provider init code won't evaluate right now because I forgot to pass through the feature flag provider 🤦 
We need a patch release out with this, pronto.

Autocomplete: Fix feature flag init

---

vscode/src/completions/providers/unstable-fireworks.ts
vscode/test/completions/completions-dataset.ts

This changes the default temperature for StarCoder from `0.4` to `0.2` which is also used in [their own testing](https://github.com/bigcode-project/bigcode-evaluation-harness). In my experiments, this made the model behave a bit more predictable while still providing enough variation. 
**CONTROVERSIAL:** I also tweaked the example Bee added in #945. I’m happy to revert though. StarCoder was not completing this and I think it was because there are two reference function in that file that are implemented the same way with the same line missing so starcoder did pattern match and thought that this is the expected result. I feel that the example is a bit contrived so I changed it into something that I would encounter while developing. 
Ran the completions test suite and made sure the output …

Autocomplete: Tweak StarCoder temperature

---

vscode/src/graph/graph.ts
vscode/src/graph/section-observer.ts

After testing locally, here are some tweaks that makes graph context for autocomplete much more usable (although not as powerful - yet!)
- We removed the recursion limit so it's faster and far fewer irrelevant symbols are included
- Instead of Go To Type Defs, we default to Go To Defs now because in a lot of cases, Go To Type Defs wouldn't work very well. We need a heuristics to decide which one to follow.
- Rewrite the markdown extracting logic because I build 💩 
The result is that I had the first autocomplete request that included the proper props for a React component that I never had opened or anything. Just because we found the right definitions 💥  (The completion is still wrong because the dummy objct is defined in the suffix and Anthropic doesn't read the suffix yet. Baby steps 😬)

Autocomplete: Tweaks to the graph context to make it actually slightly usable already

---

vscode/CHANGELOG.md
vscode/package.json

Preparing a patch release of 0.10.1. It contains two cherry-picked commits from #965 and #966

VS Code: Release 0.10.1

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/package.json
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/createProvider.ts

Close https://github.com/sourcegraph/cody/issues/811 https://github.com/sourcegraph/cody/issues/944
This PR contains changes related to adding "infill" mode to the Anthropic autocomplete provider for the Claude instant model:
- A new CodyAutocompleteClaudeInstantInfill feature flag was added to the FeatureFlagProvider.
- The vscode/package.json file was updated to include "claude-instant-infill" as a new advanced autocomplete model.
- "cody.autocomplete.advanced.model": "claude-instant-infill"
- createProvider.ts was updated to use the "infill" mode when "claude-instant-infill" is configured instead of the default mode for Anthropic `claude-instant-1`
- AnthropicOptions now accepts a mode parameter to specify either 'default' (`claude-instant-1`) or 'infill' (`claude-instant-infill`).
- …

feat: add infill mode to anthropic claude instant

---

lib/shared/src/sourcegraph-api/graphql/client.ts
vscode/src/services/EventLogger.ts
vscode/test/fixtures/mock-server.ts

Patch to #468 and #935,  to add logic so that on dev mode it does not try to log events to the testing API and only e2e test events are logged.
tested locally to ensure only e2e tests are sending data and debug console is not showing errors

E2e test logging patch1

---

vscode/CHANGELOG.md
vscode/src/completions/logger.ts
vscode/src/completions/statistics.ts
vscode/src/completions/tracer/traceView.ts

I often find myself wanting to know when exactly we count something as suggested vs. when we count it as accepted. Looking at the output tab is not super helpful here either so I added a small UI to the trace view.
This also adds the "infra" to support the trace view to show other views that re-render which I want to use for the section observer shortly.
I’m specifically hoping that this will help with #923.
https://github.com/sourcegraph/cody/assets/458591/2279928c-4056-4d0e-9f56-d5bdff6dbc03

Autocomplete: Add bare bones statistics logging and UI

---

vscode/CHANGELOG.md
vscode/src/completions/createVSCodeInlineCompletionItemProvider.ts
vscode/src/main.ts
vscode/src/services/AuthProvider.ts
vscode/src/services/StatusBar.ts
vscode/test/completions/run-code-completions-on-dataset.ts

Closes #928
Avoid setting up autocomplete when the user is not signed in and log the states properly to the UI.
https://github.com/sourcegraph/cody/assets/458591/1444833c-0bce-4377-a894-cb97022ec2fa

Autocomplete: Don't init when not logged in and add UI to show that to users

---

vscode/src/custom-prompts/CustomPromptsStore.ts

If user/workspace Cody config file contains commands in old format, show notification with accept/ignore config update options. If user accepts, overwrite the config file and open it.
Previously we updated user/workspace cody config file if commands were in old format and then informed user about this change. This behavior may be annoying as there is no way for users to avoid these changes: if user discards or stashes config changes, these changes would be reapplied next time  user interacts with the main quick pick or sidebar chat ([thread](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1694010637819529)).
CI passes. Tested manually (video attached).

Show commands format changed notification

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/CHANGELOG.md
vscode/src/completions/client.ts

Removing the feature flag, we've shipped this feature to 100% and now it's time for enterprise customers to also get this goodie.
👀

Autocomplete: Remove cody-autocomplete-streaming-response flag

---

vscode/src/completions/context/context.ts
vscode/src/completions/get-current-doc-context.test.ts
vscode/src/completions/get-current-doc-context.ts
vscode/src/completions/getInlineCompletions.ts
vscode/src/completions/request-manager.test.ts
vscode/src/graph/section-observer.ts

Just a few assorted graph context tweaks:
- We now extract the range of everything in the prefix and suffix. This is helpful so we can disregard definitions that are already in our context anyways. 
- Remove the `.d.ts` logic since it doesn't make sense to special case. Instead, we should fix this with other heuristics
- Add tests for the document context logic 
Tests green, this is not shipped yet anyways.

Autocomplete: Various section observer tweaks

---

agent/src/agent.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
vscode/src/fetch.ts
vscode/src/services/LocalAppDetector.ts

Previously, there was no way for agent clients to customize the `User-Agent` HTTP header that is sent for network requests. This PR adds the ability to customize the `User-Agent` header based on the name and version of the client that is sent during the `initialize` handshake.
Fixes https://github.com/sourcegraph/sourcegraph-inc239/issues/65
- Add `console.log()` statements before `fetch` requests
- Start local build of the JetBrains plugin
- Use plugin, confirm that all requests have the `User-Agent` header set

Agent: add support for custom User-Agent

---

lib/ui/src/chat/Transcript.tsx

Previously the behavior was:
1. When a new human message is entered, scroll all the way to the bottom.
2. As the assistant response appears, continue scrolling to keep the bottom in view (this is done with the browser's default scroll anchor behavior).
This worked fine for most chat inputs, but it was not a good UX for `/search` and `/symf`, because both these commands often generate a response that's taller than the viewport, meaning the user has to scroll back up to get to the top of results.
This PR updates the scrolling behavior in the Cody sidebar to the following:
1. When a new human message is entered, scroll that human message up toward the top of the viewport, but not past the top.
2. If the assistant response is streamed (not the case for `/search` and `/symf`) and the bottom of …

update scrolling behavior

---

vscode/test/e2e/helpers.ts
vscode/test/fixtures/mock-server.ts

Adds `testRunID` to the logged data so that we can identify each test run uniquely. 
Verify events are coming through with updated fields

Introduce testRunID when logging events from e2e tests

---

agent/src/agent.ts
agent/src/protocol.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.ts

Clearing the last candidate ensures that autocomplete id's and cached potential suggestions are not reused.  This adds a notification an extension can send when it no longer wishes the consider the last candidate.  The most common reason is that the suggestion was accepted. 
Tested using JetBrains extension 
Accepted an autocomplete and then immediately removed it and triggered another 
Got the same suggestion but verified the id was different.

Agent: add notification that clears the last autocomplete candidate

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/context/context-graph.ts
vscode/src/completions/createVSCodeInlineCompletionItemProvider.ts

Add a feature flag so we can remotely enable graph context and only enable it for supported languages.
- Enable graph context via the VS Code setting
- Observe it still works using the trace view

Autocomplete: Add a feature flag for graph context and only enable it for supported languages

---

lib/shared/src/sourcegraph-api/errors.ts
vscode/src/completions/client.ts
vscode/src/completions/logger.ts

- Do not report auth errors ([467k reports in a couple of weeks](https://sourcegraph.sentry.io/issues/4448742691/?query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=14d&stream_index=0)) from completion generation to Sentry to reduce the volume of reported events.
- [Slack discussion](https://sourcegraph.slack.com/archives/C05AGQYD528/p1694556997905489)
- TODO follow-up https://github.com/sourcegraph/cody/issues/1027
1. Sign in to sourcegraph.com.
2. Drop the token via the DotCom interface.
3. Generate a completion.
4. Ensure that the `not authenticated` error is not reported to Sentry.

Autocomplete: do not report auth errors to Sentry

---

lib/shared/src/sourcegraph-api/errors.ts
vscode/src/completions/client.ts
vscode/src/completions/logger.ts
vscode/src/services/sentry/sentry.ts

- This PR makes our error reporting rules more strict on top of https://github.com/sourcegraph/cody/pull/1028 by omitting network errors with a network status >= 500. The assumption is that these errors are already monitored on the backend.
- Filtering logic is moved right into the Sentry's `beforeSend` hook to ensure we do not accidentally report these types of errors from another `captureException` call site.
- A separate `NetworkError` class is added in addition to the `TracedError` to distinguish between transport-level and application logic errors. 
- Disabled Sentry error reporting for non-production environments + introduced an environment variable to enable it for local debugging.
- Addresses the third most reported Sentry error `read ECONNRESET` ([292k …

Autocomplete: do not report some network errors to Sentry

---

vscode/src/completions/providers/unstable-fireworks.ts

This PR adds a stop sequence to Fireworks requests. We can rely on `\n` for single line completions because the prefix is not truncated. We also use `\n\n` in Anthropic to terminate multi-line requests so this just brings it on par.
- Enable StarCoder and be connected to dotcom
- `cody.autocomplete.advanced.provider": "unstable-fireworks"`
- Observe that single line completions still work

Autocomplete: Add stop sequence to Fireworks

---

vscode/CHANGELOG.md
vscode/src/services/AuthProvider.ts

- Sign out immediately instead of showing the quick-pick menu.
- [Slack discussion](https://sourcegraph.slack.com/archives/C05AGQYD528/p1694569149605279)
Signed-out locally.

VS Code: remove sign-out menu

---

lib/shared/package.json
lib/shared/src/chat/useClient.ts
lib/shared/src/sourcegraph-api/completions/browserClient.ts

- Typewriter needs to be closed before stopping. 
- Need to catch error while updating typewriter.
- Stop retrying for fetchEventSource
Slack:
https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1694529000641279
https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1694466882019489
- Submit a chat message on /cody
- Go to network tab, search for `stream` XHR request and block it
- There should be a network request failed message in the chat
- But no infinite retries.

[Cody Web] fix typewriter err handling and closing

---

lib/shared/src/codebase-context/messages.ts
vscode/src/completions/context/graph-section-observer.test.ts
vscode/src/completions/context/graph-section-observer.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/unstable-fireworks.ts
vscode/src/completions/text-processing/utils.ts
vscode/src/completions/types.ts
vscode/src/graph/graph.ts

**Idea:** We have context snippets that contain type definition and implementation hover text, but that doesn't help link it to a local variable. We'll want to provide this data to the LLM in the form of _type `T` is the type of variable `X`_ or _type `T2` implements type `T1`_ so that the LLM can reason about the shape of `X` and `T1` (not just `T` and `T2`).
Manual testing.

Intelligent Cody: Track which local variable types/implementations alter

---

vscode/src/completions/providers/unstable-fireworks.ts

Fixes: #1037
Prevents some rare cases where the prompt leaks into the completion (c.f. #1037) by using the `<filename>` token to announce the filename instead of injecting a code comment into the prefix.
- Change the model to starcoder and provider to fireworks in the VS Code settings and be connected to dotcom, additionally enable graph context
- create a file `test.ts` and export a random function 
- create a second file `test.test.ts` and see what StarCoder wants you to import there and to test
- Observer that it's the right stuff

Autocomplete: Use <filename> token in StarCoder prompt

---

vscode/src/completions/context/graph-section-observer.ts
vscode/src/graph/graph.ts

This is a small regression from the last changes. We were only filtering out these common imports path when loading the files into the content map, however if the location of a symbol would end up being inside a common import, we would still include its hover tooltips. We would not have a symbol name then, though, because that would require us to read the ranges of these files which we haven't loaded.
So this PR filters out all locations in these ultra common imports

Autocomplete: Don't cull symbols that are defined in common import paths

---

vscode/src/graph/graph.ts

Reduce noise by not returning context/error or libexec/src (Go stdlib) entries.
Manually ensured go stdlib paths are not passed back to the provider.

Intelligent Cody: Add additional Go heuristics

---

doc/dev/index.md
doc/dev/quality/autocomplete-review-tool.md
doc/dev/quality/index.md
vscode/CONTRIBUTING.md

Adds docs overview for cody quality tools (LLM judge, etc.) explaining what they are and how we can use them, plus a dedicated page for how to run/use the autocomplete review tool today.
Docs only

doc: add cody quality tools + autocomplete review tool docs

---

agent/src/agent.ts
agent/src/protocol.ts

Previously, there was no way for clients to determine whether a repository had embeddings available. This PR closes the gap by adding a new request endpoint `graphql/getRepoIdIfEmbeddingExists`.
Tested with [IntelliJ](https://github.com/sourcegraph/sourcegraph/pull/56584)

Agent: add `graphql/getRepoIdIfEmbeddingExists`

---

vscode/CHANGELOG.md
vscode/src/chat/ChatViewProvider.ts
vscode/src/chat/ContextProvider.ts
vscode/src/chat/protocol.ts
vscode/src/services/AuthProviderSimplified.ts
vscode/src/services/OnboardingExperiment.test.ts
vscode/src/services/OnboardingExperiment.ts
vscode/test/e2e/helpers.ts
vscode/webviews/App.story.tsx
vscode/webviews/App.tsx
vscode/webviews/Login.tsx
vscode/webviews/OnboardingExperiment.tsx

Users are randomly assigned to get the classic onboarding experience ('control') or a simplified onboarding experience without app setup ('treatment'.) This allocation is hard-coded in the extension; if we want a different rollout we need to update the extension.
Once we render the login component, we consider the user has been exposed to a specific arm of the trial and we cache this fact in local storage.
Currently fixes the rollout at 0.5 so people running main will get exposed to the experiment. We can bump `SIMPLIFIED_ARM_ALLOCATION` back to zero if we want to hold back the experiment.
Testers can set a boolean property, `testing.simplified-onboarding`, to force the extension to display the treatment (true) or control (false) arm of the trial.
Part of #632 
Automated test:
```
pnpm …
```

Simplified onboarding experiment assignment and logging

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/completions/getInlineCompletions.ts

Closes #1019
This adds the manual completion shortcut to trigger completions.
This change also disables the debounce timings when the completion was manually requested (that is, either using this shortcut or when hovering over completions). This is done to slightly increase latency when we already have a strong sign that the user really wants that completion
- Move the cursor somewhere
- Press alt+\
- Observe a completion being loaded
https://github.com/sourcegraph/cody/assets/458591/be4f9070-8b4c-47c5-bd0c-5611519318a4

Autocomplete: Add alt+\ shortcut to trigger autocomplete and bypass debouncing times

---

vscode/src/chat/MessageProvider.ts

Any thoughts on this change @abeatrix ? Is there a reason why we've used `:called` in the past for the explain|doc|test|smell commands? Context: https://sourcegraph.slack.com/archives/CN4FC7XT4/p1694630386266389
Note that I left the various `:clicked` event names where the object in question was a "button"
No test required, just a string constant change

Consistent event names for commands

---

.github/workflows/ci.yml

- Extracts linting into a separate CI job to run it in parallel with builds.
CI

dx: extract linting into a separate CI job

---

vscode/src/completions/detect-multiline.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions-tests/triggers.test.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/vitest.d.ts

- A follow-up for https://github.com/sourcegraph/cody/pull/913
- Apply the same logic to `enableExtendedTriggers` (non-empty-line multi-line triggers): do not trigger multi-line completions for opening brackets if the content already exists in the block.
- [Slack discussion](https://sourcegraph.slack.com/archives/C05AGQYD528/p1694609236944899)
- Added `vitest` custom matchers for multi vs sigle-line completions checks.
```ts
// Previously generated multi-line completions.
function bubbleSort() {█
const a = []
}
```
```ts
// We request multi-line completions only for empty blocks now.
function bubbleSort() {█
}
```
Added unit-tests.

Autocomplete: trigger multiline completions on empty block only

---

agent/src/agent.ts
agent/src/protocol.ts

Previously, the worker (aka. agent) didn't correctly manage the chat transcript:
- The transcript was reset on every `recipes/execute` request.
- The transcript was reset every time we updated extension configuration (including access tokens or codebase setting).
This PR fixes the problem by always preserving the transcript history unless the client sends a `transcript/reset` notification.
Tested with IntelliJ (will update  link to PR)

Worker: support correct transcript management

---

lib/shared/src/sourcegraph-api/completions/browserClient.ts

The WorkerGlobalScope symbol is not defined when running the Cody Agent. This is rolling back one of Valery's changes from https://github.com/sourcegraph/cody/pull/1075 -- it must have looked as if the symbol was clearly defined, in the VSCode environment.
I would welcome ideas on how to test this, because clearly it's easy to break. But for now let's get it running again?

Fix broken Cody Agent

---

vscode/.storybook/main.ts

The VScode storybook config was not mangling kebab-case identifiers as camelCase. As a result, a bunch of rules weren't being applied in the storybook.
Before:
After:
1. `pnpm -C vscode storybook`
2. Open http://localhost:6007/?path=/story/cody-loginexperiment--login
3. The sign-in buttons should be the same width.

Fix VScode storybook CSS class name mangling

---

agent/README.md
agent/package.json

- Enables [sourcemaps](https://esbuild.github.io/api/#sourcemap) by default.
- Adds the `pnpm agent:debug` command which runs the agent, allowing attaching an
[inspector](https://nodejs.org/en/docs/inspector) to it.
1. `pnpm agent:debug`
2. Attach the node-inspector to the running process.
3. Add a breakpoint to sources.
4. Verify that breakpoints work as expected with sourcemaps.

Agent: add `pnpm agent:debug` command

---

.eslintignore
.eslintrc.js
.prettierignore
vscode/.eslintignore
vscode/package.json
vscode/src/completions/tree-sitter/queries/README.md
vscode/src/completions/tree-sitter/queries/annotate-and-match-snapshot.ts
vscode/src/completions/tree-sitter/queries/blocks.test.ts
vscode/src/completions/tree-sitter/queries/languages/javascript/blocks.scm
vscode/src/completions/tree-sitter/queries/test-data/blocks.snap.ts
vscode/src/completions/tree-sitter/queries/test-data/blocks.ts
vscode/tsconfig.json

- Adds an experimental logic for snapshot testing tree-sitter queries. This is the first iteration, which is not a final version, but it already provides great value — a bug found because of the visual representation of matching code. 
- Snapshot tests use tree-sitter queries defined in `.scm` files, whereas the application code still uses queries defined in TS sources. It will be fixed in #1056 
- Based on discussion with @olafurpg ([ref](https://sourcegraph.slack.com/archives/C05P6R9CV3Q/p1694769193088069))
- Part of #1076 
- Snapshot tests are powered by [vitest.toMatchFileSnapshot()](https://vitest.dev/guide/snapshot.html#file-snapshots), which means we can iterate on the logic easily in the watch mode and update snapshots if needed by pressing `u`.
Input for snapshot tests where the …

Autocomplete: add snapshot tests for tree-sitter queries

---

vscode/src/completions/providers/anthropic.ts

Follow up on https://github.com/sourcegraph/cody/pull/1063
Sorry was sick on Thursday and wasn't thinking straight 😅 
This PR fixes my oversight in https://github.com/sourcegraph/cody/pull/1063.  
The trim() logic should be added [inside the replacement block](https://github.com/sourcegraph/cody/pull/1063/files#diff-2f517c653a75e0f3b05fcb8cfc041e5125a7d347878749f828e9d8d0bb732753L109), instead of trimming the whole infillBlock
Test this change with the incomplete comment test case

fix: use infillBlock not infillBlock.trimEnd()

---

vscode/src/graph/graph.ts

This removes common and not helpful hover text like you can see in this screenshot:
The common and unhelpful hover text is no longer included in the context. Here instead we only see a previous selected section being added (the example does not have any references to code that is outside the context window)

Autocomplete: Remove common TS hover text for graph context

---

vscode/CHANGELOG.md
vscode/src/completions/request-manager.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.ts

RE: https://github.com/sourcegraph/cody/issues/969
Spin off from discussion in https://github.com/sourcegraph/cody/pull/1064
This PR adds the ability to remove an unwanted suggestion where the user performs deletion on a displayed suggestion from the cache.
This is built on @valerybugakov 's idea in the other issue comment https://github.com/sourcegraph/cody/pull/1064#pullrequestreview-1628364816 that we all agreed:
> It would be intuitive for me if we removed cached completions if a user deleted text past the initial trigger point. It covers the case @abeatrix mentioned in the PR description when you got an unhelpful completion, deleted the trigger point, typed com again, and got the same cached unhelpful completion. It would also preserve all the benefits of the request-manage cache PR …

feat: remove unwanted suggestion from the cache

---

vscode/src/completions/providers/anthropic.ts
vscode/src/completions/text-processing/utils.ts

follow https://github.com/sourcegraph/cody/pull/1063#discussion_r1326883085
refactor: Simplify prefix code extraction for anthropic infill prompt building step
- Extract raw prefix code rather than reconstructing as suggested by @valerybugakov (thank you!)
- Remove custom infill block extraction from prefix
- Simplify infill model prompt
Infill model still works as expected.

refactor: simplify prefix code extraction for anthropic

---

vscode/CHANGELOG.md
vscode/src/completions/createVSCodeInlineCompletionItemProvider.ts

Close https://github.com/sourcegraph/cody/issues/1112
The inline completion provider was previously registered for all languages ('*') at all places. 
This change updates the registration to explicitly include notebook and text documents with file scheme to ensure autocompletion only works in places that we currently support.
- Completions should work the same on saved text documents and notebook cells
- Completions should not work in source control input box or any other places that are not editor files / notebook files
https://github.com/sourcegraph/cody/assets/68532117/7a9ec776-398d-47ba-b3cc-6aeda86c3b24

change: register inline completion provider for files and notebooks only

---

vscode/CHANGELOG.md
vscode/src/chat/ChatViewProvider.ts

Reported by @toolmantim, current insert at cursor button uses replace instead of insert
fix: Use insert instead of replace for ` insert at cursor` button
- Change edit.replace to edit.insert for code block insertion button
- Insert completion text at selection start instead of replacing by range
- start cody from this branch
- use the insert at cursor button on code block
current selection will be replaced by code block insertion on button click
code block will be inserted at the start of the current cursor, and current selection will not be replaced

fix: insert not replace for insert at cursor

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.ts

This splits up the minimum latency feature flag with results based on the data analysis we have done internally https://sourcegraph.slack.com/archives/C05AGQYD528/p1694703243819199?thread_ts=1694617270.496189&cid=C05AGQYD528
👀

Autocomplete: Split minimum latency tests into two thresholds

---

vscode/src/main.ts
vscode/src/services/LocalAppFsPaths.ts
vscode/src/services/LocalAppSetupPublisher.ts

Currently always reflects configuration changes by overwriting the whole file.
Part of #958 
Manual test:
1. Start VScode
2. Sign in with dotcom
3. `cat ~/Library/Application Support/com.sourcegraph.cody/vscode.json`
The access token and root of the current workspace should appear in the file, like this:
```
{"dotcomAccessToken":"sgp_etcetc","repoPaths":["/Users/foo/bar"],"redirect":"vscode://sourcegraph.cody-ai/etc"}
```

Share a dotcom access token with app, when available

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/custom-prompts/CommandsController.ts
vscode/src/custom-prompts/menus/index.ts

Currently, none of the commands from the Custom Commands menu work. 
Steps to reproduce:
1. Open the Custom Command menu from the right click menu in your editor
2. Choose a Custom Command to run from the menu
3. None of the commands would work
This PR includes:
- Fixed the issue mentioned above
- added a back button to move from Custom Command Menu to Cody Menu
Also made the following changes in our package.json
- Rename "Smell Code" to "Find Code Smells" for clarity
- Move commands to "Ask Cody" category for better organization 
- Disable duplicated commands in command palette as /doc /test /smell etc are already covered in our Commands Menu
- Organize Cody submenu into "command" and "other" groups
- Rename "Start New Thread" to "Ask Cody Inline"
- Rename "Custom Commands …

fix: custom command in context menu

---

vscode/src/completions/logger.ts
vscode/src/completions/vscodeInlineCompletionItemProvider.ts

During exploration outlined in [this thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1695136853673249) we found two situations when we currently mark a completion as `suggested` even though it is still visible on the UI for a bit.
One such scenario is when the network requests were resolving out-of-order (mostly noticeable via the `CacheAfterRequestStart` cache hit behavior). A _prior_ completion start would return `null` (because the VS Code check if the completion is visible checks for it being terminate) and that would in turn reset the `lastCandidate` even though that might already have been set by the request of a later network response that already succeeded.
The safest and easiest fix for this is to ignore any follow-up work if we notice a completion request to be …

Autocomplete: Do not reset lastCandidate with invalidated requests

---

vscode/CHANGELOG.md
vscode/CONTRIBUTING.md
vscode/package.json

pending https://github.com/sourcegraph/cody/pull/1124
version bump

Cody release v0.12.0

---

vscode/CHANGELOG.md

Moving changelog item for https://github.com/sourcegraph/cody/pull/907 from v0.8.0 to v0.12.0. It was added to the wrong release when it was merged.
changelog update

fix: changelog item for pull/907

---

vscode/CHANGELOG.md
vscode/src/completions/providers/createProvider.ts

Seems like there was a conflict between @abeatrix's addition of the feature flag and @taras-yemets' restructurings. The result of `resolveDefaultProviderFromVSCodeConfigOrFeatureFlags` was no longer used for the Anthropic initialization causing users to load the wrong prompt mode if `cody-autocomplete-claude-instant-infill` is enabled.
- Make sure you are connected to doctom
- Be in the control group of the StarCoder experiment (needs dotcom admin access)
- Ensure no model or provider overwrites are active
- Observe that the right mode is loaded

Autocomplete: Fix cody-autocomplete-claude-instant-infill experiment

---

vscode/src/chat/MessageProvider.ts
vscode/src/custom-prompts/CommandsController.ts

Updated event names for commands-related telemetryService events.
Removed events we logged for opening the menu as a command
log names updated

refactor: telemetry names for command events

---

agent/src/agent.ts
agent/src/index.test.ts
agent/src/protocol.ts
agent/src/vscode-shim.ts
vscode/src/completions/createVSCodeInlineCompletionItemProvider.ts
vscode/src/main.ts
vscode/src/services/AuthProvider.ts

When the server or authtoken changes the agent needs to reload the auth status so that the autocomplete provider is regenerated with the new url & token.
This presented itself during first setup because the agent is initialized prior to the user providing account information.  Chat had continued to work because I new client was created when the configuration changed however the the autocomplete provider is created during activation and depends on events from the AuthHandler to reset itself.
resolves https://github.com/sourcegraph/sourcegraph/issues/56880 
Unit test added
Also did the following in IDE:
- Cleared all accounts and closed IDE
- Opened IDE created account on s2
- Verified autocomplete and chat worked
- Added a 2nd account to sourcegraph.com
- Switched account to dotcom
- …

Agent: re-authenticate during configuration changes

---

agent/src/language.test.ts
agent/src/language.ts

Improves the language detection for files that don't have extensions like Dockerfile and BUILD
unit tests added

Agent: add better lang detection support for files without extensions

---

lib/shared/src/chat/recipes/fixup.ts

RE: https://github.com/sourcegraph/cody/issues/207
> There's a hard error "The amount of text selected exceeds Cody’s current capacity" which isn't true because the same thing is possible in chat.
We should use `MAX_CURRENT_FILE_TOKENS` for the current selection instead of limiting it to a quarter of it, because surrounding code is not as important if users cannot use the command in the first place.
We can limit the context to include the quarter rule instead.
- Start Cody from this branch
- Select line 198 to 234 and run the /edit command, you can use this instruction for testing `correct any typos`
you will get an error from Cody say `The amount of text selected exceeds Cody's current capacity.` 
Cody fixed all typos it found

fix: fixup token limits

---

vscode/CHANGELOG.md
vscode/src/code-actions/fixup.ts
vscode/src/custom-prompts/CommandsController.ts

This PR adds the missing Changelog items for [pull/1116 1139](https://github.com/sourcegraph/cody/pull/1116) & https://github.com/sourcegraph/cody/pull/1139
Also fixed a minor oversight from pull/1116.
changelog update

add missing changelog for pull/1116 1139

---

agent/src/agent.ts
agent/src/index.test.ts
agent/src/jsonrpc.ts
lib/shared/src/chat/client.ts

Previously, sending `$/cancelRequest` notification for `recipes/execute` did not correctly cancel the chat request. This PR fixes the problem with two changes:
- Don't return from `recipes/execute` until the last `chat/updateMessageInProgress` has been sent. This was necessary for cancelation to work correctly because the request needs to be running for it to be cancelable. We delete the `CancellationTokenSource` after a request returns.
- Correctly propagate the cancelation token from the agent into the chat client.
See updated `index.test.ts`

Agent: add support to cancel chat

---

vscode/src/completions/logger.ts

Improve the uniqueness of autocomplete logger IDs by using UUIDs instead of the custom random thingy lol

Autocomplete: Use UUID for compltion ids

---

vscode/src/completions/context/graph-section-observer.test.ts
vscode/src/completions/context/graph-section-observer.ts

I saw that sometimes the last sections are full of the same section. Turns out we compare on the object instead the key function 🤦 
- select a bunch of sections in code
- ensure that the last sections is not containing dupes

Autocomplete: Use location key rather then location object for uniqueness test

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/CHANGELOG.md
vscode/package.json
vscode/src/completions/get-inline-completions-tests/common.test.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/createProvider.test.ts
vscode/src/completions/providers/createProvider.ts

Update to use infill prompt by default.
Based on the numbers, users are getting higher-quality of suggestions using the infill prompt. 
Removed the old prompt for anthropic that does not support infilling.
Set provider to anthropic without setting modal. You should see an infill prompt being used.
Keeping the infill model feature flag for now as it's being used in the A/B test

change: use infill prompt by default for anthropic

---

vscode/src/completions/get-inline-completions-tests/last-candidate.test.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/request-manager.ts
vscode/src/completions/reuse-last-candidate.ts
vscode/src/completions/text-processing/utils.ts

fix: use lastTriggerDocContext instead current 
- Add `lastTriggerDocContext` field to `LastInlineCompletionCandidate` interface to store document context for last triggered completion.
- Pass `lastTriggerDocContext instead` of current docContext when handling unwanted completion to ensure correct context is used.
- Update reuse logic to also check if the current prefix is shorter than the last triggered prefix before clearing the last candidate. 
- Set `lastTriggerDocContext` when creating a completion candidate.
https://github.com/sourcegraph/cody/assets/68532117/b40a9294-3b53-430a-bf08-856904f21cff

fix: use lastTriggerDocContext instead current

---

vscode/src/completions/text-processing/process-inline-completions.ts
vscode/src/completions/text-processing/truncate-parsed-completion.ts
vscode/src/completions/tree-sitter/ast-getters.ts
vscode/src/completions/tree-sitter/parser.ts
vscode/src/completions/tree-sitter/queries.ts
vscode/src/completions/tree-sitter/queries/annotate-and-match-snapshot.ts
vscode/src/completions/tree-sitter/queries/blocks.test.ts
vscode/src/completions/tree-sitter/queries/node-at-cursor-and-parents.test.ts

- Separates the tree-sitter analytics getter from queries SDK to ensure it's invoked for languages where queries are not defined.
- Follow-up for https://github.com/sourcegraph/cody/pull/1154
CI

Autocomplete: separate tree-sitter analytics getter from queries

---

vscode/src/configuration.test.ts
vscode/src/configuration.ts

- Sets `config.autocompleteExperimentalSyntacticPostProcessing` to `true` by default to enable tree-sitter parsing for all supported languages for everybody.
CI

Autocomplete: enable tree-sitter by default

---

vscode/package.json
vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/completions/get-inline-completions-tests/common.test.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions-tests/last-candidate.test.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/logger.ts
vscode/src/completions/request-manager.test.ts
vscode/src/completions/request-manager.ts
vscode/src/completions/reuse-last-candidate.ts
vscode/src/completions/tracer/index.ts
vscode/src/completions/tracer/traceView.ts

This PR improves the manual completion triggered via the keyboard shortcut:
- We are now able to separate between manually triggered completions and hover over the ghost text
- The refined trigger kinds are now part of the suggestions logged
- When using the manual keyboard triggers, we now hide the current ghost text so that we are able to cycle through new completions with this shortcut
- Opt out from cache hits when manual suggestions are triggered
```
█ logEvent (telemetry disabled): CodyVSCodeExtension:completion:suggested {"multiline":false,"triggerKind":"Automatic","providerIdentifier":"anthropic","providerModel":"claude-instant-infill","languageId":"typescript","type":"inline","multilineMode":null,"id":"6370b94f-4c07-44ac-903c-149aa75abba5","contextSummary":{"duration":0.1342079639 …
```

Autocomplete: Improved manual completion trigger

---

vscode/package.json

Follow-up from #1172. I tried the changes and they weren't working for me. Turns out we also have to change the default in `package.json`
```
█ logEvent (telemetry disabled): CodyVSCodeExtension:completion:accepted {"multiline":false,"providerIdentifier":"anthropic","providerModel":"claude-instant-infill","languageId":"typescript","type":"inline","multilineMode":null,"id":"ej0smjm3u","contextSummary":{"duration":0.6125419735908508},"source":"Network","lineCount":1,"charCount":11,"items":[{"lineCount":1,"charCount":11,"parseErrorCount":0,"nodeTypes":{"atCursor":"(","parent":"arguments","grandparent":"call_expression","greatGrandparent":"expression_statement"}},{"lineCount":1,"charCount":9,"parseErrorCount":0,"nodeTypes":{"atCursor":"(","parent":"arguments","grandparent":"call_expression","g …
```

Autocomplete: Set default for tree sitter

---

vscode/CHANGELOG.md
vscode/src/completions/get-inline-completions.ts

fix: remove params from logError verbose logging
(Discovered and fixed by @philipp-spiess 🙇‍♀️  ) This PR removed the params object from the verbose logging in logError inside getInlineCompletions.
This avoids logging potentially sensitive information from the params as well as invoking the windowActivity proposal API that breaks the extension from displaying the rate limit error properly:  
Reset after 26 year 🥲

fix: remove params from logError verbose logging

---

vscode/CHANGELOG.md
vscode/package.json

This merges back the 0.12.2 release data into `main`
Just a change log change, the release is already out.

VS Code: Release 0.12.2

---

vscode/CHANGELOG.md
vscode/package.json

Currently, the `Ask Cody Inline`  would show up but not working when `Inline Chat` is disabled.
1. disable inline chat
2. check your cody context menu
3. `Ask Cody Inline` should be disabled

fix: add enablement for inline chat in context menu

---

lib/shared/src/configuration.ts
vscode/CHANGELOG.md
vscode/package.json
vscode/src/completions/providers/createProvider.test.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/local-context/download-symf.ts
vscode/src/local-context/symf.ts
vscode/src/main.ts

Previously, `symf` talked directly to the Anthropic API. Now, it goes through a Sourcegraph instance to access the LLM. This PR updates Cody to pass the Sourcegraph auth token to `symf` and removes the old code for setting an Anthropic API token.
Test locally:
- Check out the main branch
- Remove any `cody.experimental.symf.anthropicKey` in your settings.
- Try running `/symf [query]`. You should see an error indicating that `symf` is unauthorized.
- Check out this branch and run the extension
- In the sidebar, run `/symf [query]`, where query is either a keyword search or a natural language question
- You should observe a pop-up indicating a new version of `symf` (v0.0.1) is being downloaded
- You should see successful search results

/symf: remove direct anthropic dependency, pass sourcegraph token

---

lib/shared/src/prompt/constants.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/createProvider.ts
vscode/src/completions/providers/provider.ts
vscode/src/completions/providers/unstable-codegen.ts
vscode/src/completions/providers/unstable-fireworks.ts
vscode/src/completions/providers/unstable-openai.ts
vscode/src/completions/request-manager.test.ts
vscode/test/completions/completions-dataset.ts

- Clarify the max prefix and suffix length are merely hints and are not precise (because they do not use the LLM tokenizer)
- Consolidate defaults for providers (eg 2048 tokens for the OpenAI provider now only appears once as a constant)
- Standardize how different providers compute the prompt chars available
- Allow providers greater flexibility in specifying the max prefix and suffix length (which is important for, eg, local Ollama, because it needs an absolute cap of ~15 tokens, not a % of the overall size, on the suffix to have decent performance)
CI.

refactor options and hints for context size

---

vscode/CHANGELOG.md
vscode/src/completions/get-inline-completions-tests/triggers.test.ts
vscode/src/completions/get-inline-completions.ts

Autocomplete: Don't trigger on closing characters

---

agent/src/agent.ts
agent/src/protocol.ts

This PR exposes the grapqhl query getRepoId in protocol so we can distinguish in the plugins whether the repo is not found at all or whether it has no embeddings
- JetBrains plugin uses this query, so you can test it there in different PR -> https://github.com/sourcegraph/sourcegraph/pull/57128

JetBrains: expose graphql query getRepoId in protocol

---

agent/src/agent.ts
agent/src/index.test.ts
agent/src/protocol.ts
cli/src/commands/complete/command.ts

VScode has a couple of kinds of autocompletions ("Invoke", "Automatic") which Cody splits into three: Manually triggered ones, hovers, and automatic ones. Adds an optional field, `triggerKind` to `autocomplete/execute` which specifies one of the VScode kinds. Additionally, makes the completion provider do a "manual" completion when`triggerKind` is "Invoke".
Tested manually by adding triggerKind to cody-emacs and triggering an autocomplete with `C-c c`

Agent: Add a way to trigger "manual" autocompletions

---

agent/src/vscode-shim.ts

The VS Code extension now has logic that checks the connected instance's configuration to determine which autocomplete provider should be used.  Removing the default to allow this logic to run.
`sg start` instance configured with azure-openai
`./gradlew -PforceAgentBuild=true :runIDE`
`connect Cody to local instance`
verifed autocomplete works and is served by azure

Agent: don't default provider to anthropic so detection logic can run

---

vscode/src/chat/ContextProvider.ts
vscode/src/external-services.ts

The console.info messages with \n were causing an error 
```
java.lang.IllegalStateException: Missing header Content-Length in input
```
replaced with the debug logger 
`./gradlew -PforceAgentBuild=true :runIDE`
Open a repo that does not have embeddings
ensure no error occurs.

Agent: replace console.info with debug logs

---

vscode/src/services/OnboardingExperiment.ts

There are still users in the control arm of the experiment. This does not remove the control arm, it just changes the rollout to direct all new users into the treatment arm of the experiment.
This has already shipped to half of users, this just increases the rollout.

Increase simplified onboarding experiment rollout to 100%

---

lib/shared/src/sourcegraph-api/completions/nodeClient.ts

The JetBrains extension has a setting to allow untrusted certs, however requests to the chat client set this option directly on the request.  This adds a check of the environment variable set by the extension if it wishes to accept untrusted certs.
`sg start`
`./gradlew -PforceAgentBuild=true :runIDE`
connect to the local instance `https://sourcegraph.test:3443`
verify I can chat successfully

Agent: make chat client respect NODE_TLS_REJECT_UNAUTHORIZED

---

vscode/src/custom-prompts/CommandRunner.ts

RE: https://sourcegraph.slack.com/archives/C05AGQYD528/p1695902300751599?thread_ts=1695733768.715559&cid=C05AGQYD528
fix: check if selection is visible before revealing range
Only reveal the selection range if it is not already visible. This avoids unnecessarily revealing the range and disrupting the user's view if the selection is already on screen.
- Get the visible ranges from the editor
- Check if selection is contained in visible ranges
- Only reveal selection if not visible
https://github.com/sourcegraph/cody/assets/68532117/6dbd9f96-4e40-46ab-8e0f-498bfd1a844f
Won't scroll to range if it's already visible

change: /doc scroll on invisible range only

---

vscode/src/main.ts

This fixes the following bug:
- User is logged out
- User logs in
- We don't propagate the auth token to SymfRunner, so it doesn't make it to `/symf`, which uses it to query claude-instant for query expansion
- Verify the bug behavior on `main`
- Check out this branch and log out
- Log back in and verify `/symf [query]` works

Auth symf after login

---

vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/completions/get-inline-completions-tests/last-candidate.test.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/logger.test.ts
vscode/src/completions/logger.ts
vscode/src/completions/request-manager.ts
vscode/src/completions/reuse-last-candidate.ts

This PR will add a new book keeping for completion IDs. These are different from the existing suggestion IDs in that:
- Suggestion IDs are used for one suggestion life cycle: One time a completion is rendered on the screen
- Completion IDs are used to identify a specific completion that is printed in a specific document location
The new change makes it so that we will log multiple completions events with the same id. This will help us identify how useful the current cache behavior is.
https://github.com/sourcegraph/cody/assets/458591/5e6604f8-e4a3-4b38-ab5c-16776677d265

Autocomplete: Add bookkeeping to reuse completion IDs over multiple suggestions

---

vscode/src/main.ts
vscode/test/e2e/custom-command.test.ts
vscode/test/e2e/fixup-decorator.test.ts
vscode/test/e2e/inline-assist.test.ts
vscode/test/e2e/task-controller.test.ts

Update expectedEvents within the E2E tests. There have been changes made to the events logged and the e2e tests need to be updated.
tested using `pnpm test:e2e`

update expectedEvents in E2E tests

---

vscode/src/chat/ChatViewProvider.ts
vscode/src/chat/ContextProvider.ts
vscode/src/services/LocalAppDetector.ts
vscode/src/services/LocalAppWatcher.ts

LocalAppDetector stops monitoring app once the user has signed in. Simplified Onboarding needs to pick up the app token, even if the user has logged into dotcom, so that we can use app for local embeddings. This makes simplified onboarding's LocalAppWatcher ping the LocalAppDetector to retrieve the app token, if it detects a change in the app.json file, even after the user has logged in.
Part of #632.
0. Open Cody App, add a repo, and add embeddings for a private local repository which has a remote.
1. Quit Cody App if it is running. Open Keychain and delete any vscodesourcegraph.cody-ai tokens. Delete ~/Library/Application Support/com.sourcegraph.cody/app.json . This means VScode will not have a cached app token. (Some uncertainty around where VScode stores secrets across versions. You …

Simplified Onboarding: Pick up the app token if available after sign-in

---

vscode/CHANGELOG.md
vscode/src/custom-prompts/CommandRunner.ts
vscode/src/custom-prompts/CommandsController.ts
vscode/src/editor/vscode-editor.ts

Put /doc behind a temporary flag (hard coded) until the next release. 
Try the /doc command, smart selection will not work and you will have to highlight code before running the /doc command

add doc behind feature flag

---

vscode/CHANGELOG.md
vscode/package.json

Releasing 0.12.4 from `main` in preparation for the big release.
Version and change log change

VS Code: Release 0.12.4

---

vscode/CHANGELOG.md
vscode/src/custom-prompts/CommandRunner.ts
vscode/src/custom-prompts/CommandsController.ts
vscode/src/editor/vscode-editor.ts

revert https://github.com/sourcegraph/cody/pull/1248 for next release
revert https://github.com/sourcegraph/cody/pull/1248

revert pull/1248

---

lib/shared/src/configuration.ts
vscode/package.json
vscode/src/chat/ContextProvider.ts
vscode/src/chat/FixupViewProvider.ts
vscode/src/chat/InlineChatViewProvider.ts
vscode/src/code-actions/explain.ts
vscode/src/code-actions/fixup.ts
vscode/src/completions/providers/createProvider.test.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/logged-rerank.ts
vscode/src/services/StatusBar.ts

- Group the fix and explain actions
- Allow enabling/disabling the actions all together
Enabled:
Disabled:
Interface:
Tested locally, enabling and disabling through interface and manually in VS Code settings

Code Action: Allow enabling/disabling and improve ranking of explain

---

vscode/CHANGELOG.md

Add missing 0.12.x changelog notices related to simplified onboarding.
Documentation only change.

Update changelog with 0.12.x onboarding changes.

---

vscode/src/graph/graph.ts

Reduce concurrent lang server requests and decrease the timeout to reduce stress on the lang server.
👀

Autocomplete: Throttle lang server requests for LSP graph context

---

lib/shared/src/configuration.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/CHANGELOG.md
vscode/package.json
vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/providers/createProvider.test.ts
vscode/src/completions/request-manager.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts

This ships completeSuggestWidgetSelection by default but keeps a VS Code config option to turn of the behavior in case people are not happy with the config overwrite. 
This also improves the behavior slightly:
- Introduces a new `triggerKind` `SuggestWidget` so we detect if a completion was triggered because the user cycles through the suggest widget
- Based on this new `triggerKind`, ensure that no latency is used. A user selecting an option is a strong sign that they want to continue code in this direction so we should treat this more like a manual invocation and not like the automatic one.
- Start VS Code in dev mode
- Type `console.` and wait for the dropdown
- Select `dir(` from the dropdown and observe a fast completion like this:

Autocomplete: Enable completeSuggestWidgetSelection by default

---

vscode/src/chat/MessageProvider.ts

follow up on https://github.com/sourcegraph/cody/pull/1220
Right now we are not streaming assistant response as we are not setting display text in typewriter for assistant response because of the change in 1220.
This PR should fix the issue
1. run /test command on selected code
2. before the change, you will not see the response until cody has finished the response
3. when building from this branch, you should see the response from cody streaming in chat view

fix: set display text for typewriter

---

vscode/src/services/AuthMenus.ts

Now we have the new login options, it doesn't make sense to have sourcegraph.com in the quickpick items, so this removes it. 
| - | - |
| <img width="886" alt="Screenshot 2023-10-03 at 12 30 02 pm" src="https://github.com/sourcegraph/cody/assets/153/702a0154-d071-4815-bff2-4707716f0b3d"> | <img width="886" alt="Screenshot 2023-10-03 at 12 29 44 pm" src="https://github.com/sourcegraph/cody/assets/153/33b3439d-d816-4468-a41b-d89ec19638aa"> |
In the future, it would be good to provide a "Sign in to sourcegraph.com with Access Token" option (currently you have to use "recently used" to achieve that).
Fixes #1280
No changelog necessary
- While logged out, click "Sign in to Enterprise Instance" and review quickpick items

Remove .com from enterprise login options

---

vscode/CHANGELOG.md
vscode/package.json

Fixes the "Ask Cody Inline" context menu incorrectly showing for logged out users.
| - | - |
|  <img width="462" alt="Screenshot 2023-10-03 at 12 03 13 pm" src="https://github.com/sourcegraph/cody/assets/153/dfd8b860-c8eb-47e0-98e2-ceb71a79e62f"> | <img width="355" alt="Screenshot 2023-10-03 at 12 04 08 pm" src="https://github.com/sourcegraph/cody/assets/153/589f18fa-8c84-46cb-af2b-63215ac9f458"> |
Part of #1275
- While logged out, right clicked on code, verified menu item no longer there

Only show "Ask Cody Inline" context menu item when signed in

---

vscode/test/e2e/inline-completion.test.ts

Adds logging validation to`inline-completion.test.ts`, to ensure that the correct events are logged when inline completions occur. 
To note, for this test we sort the array of expectedEvents and loggedEvents when comparing because `CodyVSCodeExtension:completion:suggested` and `CodyVSCodeExtension:completion:accepted` events fire at the same time making this test flaky if we do not sort when comparing the arrays.
Tested locally running pnpm test:e2e

add event logging validation to inline test

---

vscode/src/services/OnboardingExperiment.test.ts
vscode/src/services/OnboardingExperiment.ts

We want to make simplified onboarding the default. Move users who were previously allocated to the control arm onto the simplified onboarding experience by ignoring their cached arm.
The only users who use classic onboarding are users on web.
Part of #1229.
- Ensure `"testing.simplified-onboarding"` is not set in User Settings JSON.
- Run VScode. Sign out of Cody if signed in. You should see the GitHub, GitLab, Google sign in buttons.

VScode: Move onboarding control group onto simplified onboarding

---

vscode/src/notifications/setup-notification.ts

In user testing, we found that after installing Cody from the extension marketplace, people scroll through the extension marketplace page trying to log in to Cody. Instead, open the Cody sidebar the first time the extension activates.
Fixes #1298 
This creates an environment similar to a fresh install:
```
mkdir /tmp/project
code-insiders --user-data-dir=/tmp/test-plan --profile test-plan /tmp/project
```
Now build and install the extension in that profile:
```
cd vscode
CODY_RELEASE_TYPE=stable pnpm release:dry-run
code-insiders --user-data-dir=/tmp/test-plan --profile test-plan /tmp/project --install-extension dist/cody.vsix
code-insiders --user-data-dir=/tmp/test-plan --profile test-plan /tmp/project
```
Observe that the Cody sidebar panel is visible.
Select the file explorer panel—or …

VScode: Show Cody on first install

---

vscode/src/completions/get-inline-completions-tests/multiline-truncation.test.ts

- Closes https://github.com/sourcegraph/cody/issues/1294
- We already have unit tests for similar cases for both truncation strategies, tree-sitter and indentation-based. This PR adds another one that matches the example shared in the linked issue to ensure we cover this case.
CI

Autocomplete: add multiline truncation unit test

---

lib/shared/src/chat/prompts/utils.test.ts
lib/shared/src/chat/prompts/utils.ts
vscode/CHANGELOG.md

I asked GPT4 to give me some common examples and made the test pass. WDYT @abeatrix? 
Test green

Detect more test files

---

vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/latency.test.ts
vscode/src/completions/latency.ts

Close https://github.com/sourcegraph/cody/issues/1177
NOTE: This change is hidden behind a feature flag `CodyAutocompleteMinimumLatency` and can land after code freeze is over
We learned that from the last experiment, the current logic is too aggressive and not helpful for supported languages.
After our discussion in person ([see slack thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1695991988424799)), this PR includes the following changes:
- The getLatency function now takes the file name and language ID as parameters instead of just the language ID. This provides more context for determining latency values.
- The logic for gradually increasing latency has also been updated to require 5 rejected suggestions before increasing. This avoids prematurely increasing latency due to …

change: add latency gradually

---

vscode/package.json
vscode/src/configuration.test.ts

Leftover from removing the embeddings context from Autocomplete
👀

Autocomplete: Remove outdated embeddings config

---

lib/shared/src/experimentation/FeatureFlagProvider.test.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
lib/shared/src/sourcegraph-api/completions/client.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/index.ts
vscode/src/completions/client.ts
vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/providers/createProvider.test.ts
vscode/src/completions/providers/createProvider.ts
vscode/src/external-services.ts
vscode/src/main.ts
vscode/test/completions/run-code-completions-on-dataset.ts

- Makes graphql client and feature flag provider singletons to avoid passing them around as parameters.
- Continue the migration to the singleton module-level exports. Related work: https://github.com/sourcegraph/cody/pull/876 and https://github.com/sourcegraph/cody/pull/912
CI and verified that `pnpm generate:completions` still works.

VS Code: singleton graphql client and feature flag provider

---

lib/shared/src/configuration.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/package.json
vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/providers/createProvider.test.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts

- Adds a feature flag for syntactic triggers based on tree-sitter queries.
- Follow-up for https://github.com/sourcegraph/cody/pull/1259
- Part of https://github.com/sourcegraph/cody/issues/1157
CI

Autocomplete: add a feature flag for syntactic triggers

---

vscode/CHANGELOG.md
vscode/src/completions/text-processing/process-inline-completions.test.ts
vscode/src/completions/text-processing/string-comparator.test.ts
vscode/src/completions/text-processing/string-comparator.ts

We have gotten reports for cases where Cody didn't suggest a useful completion. One such case can be reproed with this example:
```
interface DoInteractionRequest {
chatId: string
prompt: string
systemPrompt: string
}
interface Fuzz {
string: () => string
}
const z: Fuzz = {} as any
const interactionRequest: DoInteractionRequest = {
chatId█
prompt: z.string(),
systemPrompt: z.string(),
}
```
This was caused by the string distance between the inserted line `chatId: z.string(),` and the next line `systemPrompt: z.string(),` (or the one above, for that matter) to be too close. We use to guard heavily against it since our initial Claude Instant implementation could not do infilling well and was repeating the suffix in many cases.
Since we have infilling now, we can make this overlap much more …

Autocomplete: Make string distance filters more lenient

---

.github/workflows/ci.yml

Refactor the CI job to use a matrix instead, allowing us to also run tests on windows once #1256 lands
Test green

Unit test matrix

---

agent/src/vscode-shim.test.ts
vscode/src/testutils/mocks.ts
vscode/src/testutils/uri.ts

Previously, `vscode.Uri.parse(...) instanceof URI` returned true with vscode-shim and false in VS Code itself. This PR fixes the problem by creating a wrapper `Uri` classes that implemements the same API as `vscode.Uri` but delegates all underlying logic to vscode-uri `URI`.
See updated tests.

Agent: mirror runtime behavior for `instanceof URI`

---

lib/ui/src/chat/Transcript.tsx

Fixing the Cody chat jump to the top on initiating a new chat
Solves [Issue Link](https://github.com/sourcegraph/cody/issues/1341)
The bug was first introduced in [PR #1224](https://github.com/sourcegraph/cody/pull/1224).
For a detailed discussion on resolving the original issue, see [Issue Link](https://github.com/sourcegraph/cody/issues/1191).
We can't remove the extra utility function because older versions of Node don't support it. This bug was surprising, as the utility function first creates a shallow copy before reversing the array. This still causes unintended side effects. Now, I've replaced it with a loop iterating from the end of the array, which resolves the issue. 
CC @dominiccooney @philipp-spiess 
There is not functionality/logic change here and all the tests pass already. …

Fixing the cody chat jump to the top on initiating a new chat

---

agent/src/agent.ts

Previously, Cody Agent would return no empty items array and no further indication that an error occurred. On the JetBrains side I want to update the status icon when certain errors are encountered, such as 401
Confirmed output is as expected:
```
-> {
"jsonrpc": "2.0",
"id": "15",
"error": {
"code": -32603,
"message": "Request to https://sourcegraph.com/.api/completions/code failed with 401: Unauthorized",
"data": "{\"error\":{\"status\":401},\"stack\":\"\\nError: Request to https://sourcegraph.com/.api/completions/code failed with 401: Unauthorized\\n    at Object.complete (/snapshot/dist/agent.js)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async /snapshot/dist/agent.js\"}"
}
}
```

Agent: reject promise on completions exception

---

vscode/src/completions/request-manager.test.ts
vscode/src/completions/reuse-last-candidate.ts

> Digging into analytics events shows that pretty often, completion events come without the node types info from tree-sitter.
Fixes the above issue where we discard completion metadata when a cached completion is used.
Updated unit tests.

Autocomplete: keep completion metadata on cache hit

---

vscode/CHANGELOG.md
vscode/src/services/InlineController.ts
vscode/test/e2e/inline-chat.test.ts

Close: https://github.com/sourcegraph/cody/issues/1350 https://github.com/sourcegraph/sourcegraph/issues/56644
Issue caused by the change in  https://github.com/sourcegraph/cody/pull/404 where `<` and `>` are manually replaced by the `naiveHtmlEscape method`, which is being removed in this PR.
The naiveHtmlEscape method was replacing < and > characters with escaped version of the characters from the markdown text before rendering. This prevented markdown syntax like <tags> from rendering correctly by the `vscode.MarkdownString` method which has the `supportHtml` turns enabled.
Removed the naiveHtmlEscape method call so markdown text renders as intended.
`<` and `>` are replaced with ` &lt` and `&gt`
`<` and `>` are displayed correctly:
1. Start an inline chat for line 310 to 325 …

fix: remove HTML escaping in inline chat markdown

---

vscode/src/non-stop/FixupController.ts

fix: log failures during fixup apply and respin
This adds additional logging around fixup failures:
- Log when applying a fixup fails
- Log when respinning a fixup task, including the respin count
You can see the log events in the output channel for all events when running a fixup task.

fix: log failures during fixup apply and respin

---

vscode/CHANGELOG.md
vscode/src/completions/client.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/unstable-fireworks.ts
vscode/src/completions/providers/unstable-openai.ts

This PR adds client side timeouts as discussed in [this Slack thread](https://sourcegraph.slack.com/archives/C05497E9MDW/p1696521645079319).
The reason for this are the following:
Our current server-side backend does request retrying for a fixed number of times. For Autocomplete however, latency is of upmost importance so we don't really want to retry requests for a long time. In some cases, we see requests being retried for up to 30 minutes which is just putting additional pressure on the downstream processes without providing a great UX. Since timeouts are highly client specific, we decided that adding those to the client is the best approach for now. All of our middleware respect aborted requests so all we need to do is to start a race between a timeout and abort the request if that is …

Autocomplete: Implement client-side timeouts

---

vscode/src/completions/get-inline-completions-tests/analytics.test.ts
vscode/src/completions/logger.ts
vscode/src/completions/text-processing/process-inline-completions.test.ts
vscode/src/completions/text-processing/process-inline-completions.ts
vscode/src/completions/tree-sitter/ast-getters.ts
vscode/src/completions/tree-sitter/query-tests/node-at-cursor-and-parents.test.ts
vscode/src/completions/tree-sitter/query-tests/test-data/parents.snap.ts
vscode/src/completions/tree-sitter/query-tests/test-data/parents.ts

Via exploring data in BigQuery, I found that the definition of the `at_cursor` node types is inconsistent. I used the multiline trigger position for multiline suggestions and the completion start for singleline suggestions. Meaning that for singleline completions, we were getting data about the first suggested node. 
```ts
const value = █
```
And with the inserted completion:
```ts
const value = "hello"
```
We were getting `atCursor: 'string'` instead of `program` as per the initial AST. The second one has "more" data because tree-sitter does not understand that it's a variable declaration until the completion is inserted.
```ts
function getData(value█
```
And with the inserted completion:
```ts
function getData(value) {
```
We were getting `atCursor: ')'` (from the start of the inserted …

Autocomplete: collect node types without pasted completion

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/providers/createProvider.ts
vscode/src/completions/providers/unstable-fireworks.ts

StarCoder supports up to 8k token windows but we're currently limiting it to 2k to match out anthropic usage.
This PR adds an A/B test to increase the prompt up to an estimated 7k tokens which should still leave plenty of room for the answer.
- Be in the starcoder test group and connected to dotcom
- Mock out the call to `featureFlagProvider.evaluateFeatureFlag(FeatureFlag.CodyAutocompleteStarCoderExtendedTokenWindow)` (i.e return true instead)
- Observe the right limit is being picked up

Autocomplete: Add StarCoder context window experiment

---

vscode/src/completions/text-processing/process-inline-completions.test.ts
vscode/src/completions/text-processing/process-inline-completions.ts

Fixes the runtime error caused by the negative `position.character` value.
Unit tests

Autocomplete: prevent negative `position.character` value

---

lib/shared/src/configuration.ts
vscode/CHANGELOG.md
vscode/package.json
vscode/src/completions/providers/createProvider.test.ts
vscode/src/completions/providers/createProvider.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/configuration.ts

90% of our community usage now goes through this code path so it better be stable
Ensured that starting this with `unstable-fireworks` in the config option will properly load the right adapter.

Autocomplete: Mark Fireworks provider as stable

---

vscode/src/completions/get-inline-completions-tests/analytics.test.ts
vscode/src/completions/logger.ts

Log the delta of accepted lines with every completion accepted event. c.f.: https://sourcegraph.slack.com/archives/C05AGQYD528/p1696413170173559
Uploading Screen Recording 2023-10-11 at 16.11.26.mov…

Autocomplete: Add logging for partial acceptence delta

---

vscode/src/services/InlineController.ts

RE: https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1697126442193659
fix: simplify inline chat thread label and update with Mac shortcuts
The inline chat thread label was updated to remove unnecessary text and focus on the key keyboard shortcuts.
Just label text change

fix: simplify inline chat thread label

---

lib/shared/src/chat/recipes/custom-prompt.ts

fix: remove redundant conditional checks
Removed redundant conditional checks and nested if statements that were added by accident when switching from `switch` statement to `if` statement 😓 
Simple removal of redundant code. Current tests for custom commands are still passing.

fix: remove redundant conditional checks

---

lib/shared/src/chat/context.ts
lib/shared/src/codebase-context/index.ts
lib/shared/src/embeddings/client.ts
lib/shared/src/embeddings/index.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/test/mocks.ts
lib/ui/src/Chat.tsx
vscode/CHANGELOG.md
vscode/src/chat/ContextProvider.ts
vscode/webviews/App.tsx
vscode/webviews/Chat.tsx
vscode/webviews/ChatInputContextSimplified.module.css
vscode/webviews/ChatInputContextSimplified.story.tsx
vscode/webviews/ChatInputContextSimplified.tsx
vscode/webviews/Notices/EmbeddingsEnabledNotice.story.tsx
vscode/webviews/Popups/OnboardingExperimentPopups.story.tsx
vscode/webviews/Popups/OnboardingExperimentPopups.tsx

Dotcom/App users can always click on the chat input status indicator and see the state of embeddings in a popup.
Caveats/limitations:
- There's no progress indicator while app is indexing. You need to wait and hit the "Reload" button.
- Only for dotcom/App users however this will be fixed in a follow up PR.
- Various existing quirks of local embeddings remain for now. For example, your git repository must have a remote with a slash in the name.
Part of #632 
This does not add automated tests yet. That is in a follow-up change, I need to update the existing tests to use simplified onboarding first.
UI check: `pnpm storybook` and examine the App-less Onboarding stories.
Manual tests:
*A directory that's not a git repository:*
```
mkdir /tmp/project
cd /tmp/project
echo hello > main.c
code . …
```

VScode: Add popups for all embeddings conditions

---

vscode/src/completions/can-use-partial-completion.ts
vscode/src/completions/get-inline-completions-tests/streaming.test.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/unstable-openai.ts
vscode/src/completions/text-processing/process-inline-completions.ts
vscode/src/completions/text-processing/truncate-multiline-completion.ts

In cases where multiline completions start with a leading new line, we do not account for the fact that the `truncateMultilineCompletion` call strips it. That's why `canUsePartialCompletion` returns false positives, leading to prematurely truncated multline completions.
```js
{
"completion": {
"text": "\nconst merge = (left, right) => {\n  let arr = [];\n  while (left.length && right.length) {",
"newLines": 4
},
"truncated": {
"text": "const merge = (left, right) => {\n    let arr = [];\n    while (left.length && right.length) {",
"newLines": 3
},
"conditionForPartialReuse": "truncated.split('\n').length < completion.split('\n').length"
}
```
- [Slack thread.](https://sourcegraph.slack.com/archives/C05AGQYD528/p1697139038515929)
- A follow-up issue: …

Autocomplete: fix `canUsePartialCompletion` for completions with leading new lines

---

.gitattributes
.github/workflows/ci.yml
.vscode/launch.json
.vscode/settings.json
agent/src/vscode-shim.test.ts
vscode/src/completions/context/lsp-light-graph-cache.test.ts
vscode/src/completions/context/section-observer.test.ts
vscode/src/completions/context/section-observer.ts
vscode/src/graph/lsp/graph.test.ts
vscode/src/testutils/textDocument.ts

(Re-do of https://github.com/sourcegraph/cody/pull/1150 because all the bots won't run on forks)
I don't know how sound all of these changes are, but they fix the failing tests I have on Windows.
1. Use platform-correct paths (drive letters + backslashes on Windows) in tests and debug printing
Previously lots of code assumed posix-style paths then had mismatches on windows because of slash direction
2. Replace fake Uri class with vscode-uri
As part of doing (1), I found that `vscode.Uri` was missing. While adding it, I realised there was a mock `Uri` implementation (presumably to avoid importing `vscode` where it won't be available), however the `vscode-uri` package (which does not depend on VS Code) was also already imported, so I removed the fake `Uri` class and just used this. This …

Fix unit tests on Windows + enable on bots

---

vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/logger.ts

RE: https://github.com/sourcegraph/cody/pull/1351
fix: apply min latency only when last suggestion was read
The minimum latency for code suggestions is now only applied when the last suggestion was read by the user. This avoids applying the latency when the user is actively typing and has not read the previous suggestions.
The lastCompletionRequestTimestamp property tracks when the last suggestion request was made. The latency is skipped if the time since last request is less than 750ms.
Check the output channel. You should not see latency getting increased after 5 keystrokes, which is the current behavior.

fix: apply latency only when last suggestion was read

---

vscode/CHANGELOG.md
vscode/src/custom-prompts/PromptsProvider.ts

RE: https://sourcegraph.slack.com/archives/C052G9Y5Y8H/p1697536651010599?thread_ts=1697536557.499619&cid=C052G9Y5Y8H
fix: swap custom prompts and default prompts order 
The order of adding custom prompts and default prompts to allCommands map is swapped to prioritize default prompts over custom.
This fixes an issue where custom prompts were overriding default prompts with the same name.
Loom provided by Vincent: https://www.loom.com/share/d8aea1426d4b409a86fde3eaefc76ed0?sid=2058611d-5f2d-4457-b3cf-6490ceefe08b
- Create a custom command and name it `explain`
- Before: you will be running the custom command when trying to run `/explain`
- After: the new custom command will not override the built-in `/explain` command

fix: swap custom prompts and default prompts order

---

vscode/CHANGELOG.md
vscode/src/chat/MessageProvider.ts
vscode/src/custom-prompts/CommandsController.ts
vscode/src/custom-prompts/utils/menu.ts

RE: https://sourcegraph.slack.com/archives/C05AGQYD528/p1697105184992049
This PR fixes the issuses reported by Philipp where `` does not work in Custom Commands Menu. This issue was caused by the previous update when `description` has become a required field. 
- Updated options to include `description` field
- Now check for the description option instead of labels when checking the selected option in custom command menu.
- Also fixed `last five used custom commands` not showing up in the same menu
This fixes an issue where commands with null descriptions would not be run when selected.
1. Open the Custom Commands Menu from right clicking in your editor and then select `Custom Commands`
2. At the bottom you will find `Configure Custom Commands...` and `New Custom Command...`
These options …

fix: unresponsive selections in custom command menu

---

lib/shared/src/chat/prompts/utils.ts
lib/shared/src/chat/recipes/chat-question.ts
lib/shared/src/chat/recipes/context-search.ts
lib/shared/src/chat/recipes/custom-prompt.ts
lib/shared/src/chat/recipes/inline-chat.ts
lib/shared/src/chat/transcript/interaction.ts
lib/shared/src/chat/transcript/messages.ts
lib/ui/src/Chat.tsx
lib/ui/src/chat/CodeBlocks.tsx
lib/ui/src/chat/TranscriptItem.tsx
vscode/src/chat/ChatViewProvider.ts
vscode/src/chat/MessageProvider.ts
vscode/src/chat/protocol.ts
vscode/src/main.ts
vscode/src/non-stop/FixupController.ts
vscode/src/non-stop/FixupTask.ts
vscode/src/services/InlineController.ts
vscode/test/e2e/fixup-decorator.test.ts
vscode/test/e2e/inline-assist-inline-touch.test.ts
vscode/test/e2e/inline-assist.test.ts
vscode/test/e2e/inline-chat.test.ts
vscode/test/e2e/task-controller.test.ts
vscode/webviews/Chat.tsx

RE: https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1697492286748349
This PR adds `source` to trace the origin for the code generated by Cody.
- Add source field to InteractionMessage to track origin of messages
- Populate source with recipe ID for each message
- Populate source with command name for custom prompts
- Log 'custom' for custom commands in source field  
- Pass source through newInteraction and log in messages
- Log source in messages
- Also removed `chatResponse:noCode` telemetry as it was not being logged correctly (all `hasCode` events will always ends with `noCode`)
Example output for `/doc` command:
```
█ logEvent (telemetry disabled): CodyVSCodeExtension:fixupResponse:hasCode {"codeCount":{"lineCount":7,"charCount":246},"source":"doc"}
█ logEvent (telemetry …
```

feat: add source tracing for code generated

---

vscode/src/completions/inline-completion-item-provider.ts

I forgot to properly forward the newly computed flag. C.f.: https://github.com/sourcegraph/cody/pull/1262#discussion_r1361461844
👀

Autocomplete: Fix forwarding of completeSuggestWidgetSelection

---

vscode/src/completions/tree-sitter/queries.ts
vscode/src/completions/tree-sitter/query-sdk.ts
vscode/src/completions/tree-sitter/query-tests/test-data/blocks.go
vscode/src/completions/tree-sitter/query-tests/test-data/blocks.snap.go
vscode/src/completions/tree-sitter/query-tests/test-data/blocks.snap.ts

- Compare the found block node start position to the cursor position to improve query reliability.
- The same approach is already used to capture singleline completion triggers.
CI

Autocomplete: use cursor position for the `blocks` query

---

vscode/CHANGELOG.md
vscode/src/non-stop/FixupController.ts

Fix regression caused by changes in https://github.com/sourcegraph/cody/pull/1317
The commit fixes an issue where getSmartSelection was always recalculating a selection even when a valid selectionRange was already provided.
Currently, the /edit command does not respect user selection when it's available:
https://github.com/sourcegraph/cody/assets/68532117/1b07e72f-3802-4f2a-8f14-f2abbb33ae84
This becomes an issue as folding range is still in the experimental stage. It also cause the code lens to jump around, unless it's intended as I haven't read through the PR 😅 
This PR adds a check to use selectionRange when it is available and not an empty range. 
This provides a fallback in case where "smart" selection is not working for users.
Select code in your editor and run the /edit command, …

fix: use selectionRange in edits when available

---

vscode/package.json
vscode/test/completions/mock-vscode.ts

Updated the outdated setting description. The `fireworks` provider is stable.
n/a

Autocomplete: update the outdated setting description

---

lib/shared/src/experimentation/FeatureFlagProvider.test.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts

This way we can turn on some features on our dogfooding instance. They will default to return `null` for enterprise instances anyways.
- Tests still pass

Enable feature flag checking for non dotcom instances

---

vscode/src/completions/context/context-graph.ts
vscode/src/completions/context/context.ts
vscode/src/completions/context/lsp-light-graph-cache.ts
vscode/src/completions/logger.test.ts
vscode/src/graph/bfg/BfgContextFetcher.ts
vscode/test/completions/run-code-completions-on-dataset.ts

Adds a new `strategy` string to the context summary field so we can differentiate between lsp-light and bfg

Autocomplete: Log which retrieval strategy is used

---

vscode/package.json
vscode/src/graph/bfg/download-bfg.ts

Previously, we used an ad-hoc naming convention for BFG binaries. Going forward, we will publish binaries using the naming conventions from RFC
795. The new binaries are named
- bfg-macos-arm64
- bfg-macos-x86
- bfg-linux-x86
- bfg-windows-x86
Manually tested by running plugin with BFG enabled and confirmed the following tree structure in the global cache directory
```
❯ pwd
/Users/olafurpg/Library/Application Support/Code/User/globalStorage/sourcegraph.cody-ai
❯ tree
.
└── bfg
└── bfg-0.1.0-macos-arm64
```

BFG: use RFC 795 naming conventions

---

agent/src/index.ts

We are seeing some cases for JetBrains team where the Cody agent process is still running after IntelliJ exits. I'm not sure if the diff in this PR fixes the problem but I figured it was worth a shot.
I'm open for suggestions to alternative fixes. We have already made changes on the JetBrains side that fix most of the instances of this problem. Since those changes, we have only been able to reproduce this issue with a local sandbox of IntelliJ (not normal installation)
n/a

Agent: exist process when stdout/stdin close

---

vscode/CHANGELOG.md
vscode/src/non-stop/FixupController.ts

Reported / requested in https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1697672986475259?thread_ts=1697672318.465339&cid=C05MW2TMYAV and https://sourcegraph.slack.com/archives/C03CSAER9LK/p1697148745798389?thread_ts=1696469865.956429&cid=C03CSAER9LK
fix: format code after applying edits
Automatically format the edited code after applying edits. 
A new range is calculated to format the selected area where fixes were applied.
The document is then formatted using the new range.
This commit fixes an issue where code was not formatted after applying quick fixes.
https://github.com/sourcegraph/cody/assets/68532117/f5179669-5521-474e-bdde-38f328bb078b
Perform an edit and confirm the edited area was formatted correctly.

feat: auto format code after applying edits

---

vscode/package.json
vscode/test/e2e/helpers.ts
vscode/test/e2e/install-deps.ts

This changes the npm script for `test:e2e` to not use syntax that doesn't work on Windows. I believe the intention of the script was to install VS Code and Chromium in parallel which this change still does, but with both done from the TS file which is more easily run in the NPM script in a way that works across platforms.
While this fixes `pnpm test:unit` on Windows for me locally, this change does not enable the bots yet because some of the tests fail when run on GitHub on Windows and that requires some debugging (locally, everything passes). I'll debug this in another PR (I'd like to get screenshots or videos working for failures, but when I try this locally I just get blank white screenshots/videos so it also requires some additional debugging).
These changes are to the test setup …

Move Chromium installation into install-deps so "pnpm test:e2e" works on Windows

---

vscode/src/local-context/symf.ts
vscode/src/main.ts

Pass the Sourcegraph URL via environment variable to `symf`, in addition to the access token, which is already passed. This enables `/symf` to work with non-sourcegraph.com instances.
Locally on this branch:

pass the sourcegraph url to symf

---

vscode/src/completions/tree-sitter/query-tests/annotate-and-match-snapshot.ts

Adds `// only` support to tree-sitter snapshot tests. It's similar to `it.only()` from `jest` and helps to debug code samples in isolation.
CI

Autocomplete: add `// only` support to `tree-sitter` snapshot tests

---

vscode/src/non-stop/FixupController.ts

This PR:
- Only applies the formatting changes to the fixup selection. By calling the format provider directly and filtering the edit down to the selection range. VS Code only provides `formatDocument` and `formatSelection` direct commands, so this is the approach that gives us the control we need.
- Preserves a single undo/redo action for both the fixup and the formatting change. A user would have to undo a fixup twice if it also applied formatting. This should be an implementation detail and not visible to the user. Now both changes are consolidated into a single undo/redo action.
https://github.com/sourcegraph/cody/assets/9516420/7f5d6b9f-7c2b-4594-b1ad-25ac2d0b575b
Tested locally, see demo

Fixup: Only apply formatting changes to a range, and clean the undo stack

---

lib/shared/src/chat/preamble.ts
lib/shared/src/prompt/prompt-mixin.ts
vscode/src/extension.common.ts

Updating current preamble, rules, and prompt mixin with new findings from https://github.com/sourcegraph/cody/pull/907.
Issue 1: Cody hallucinates about file path and code
One of the main issues we saw in Chat is Cody hallucinating about files and code that do not exist in the shared context.
I noticed this is mainly because of how we phrased our context, as Cody do not understand the relationship between each code snippet we share with them. For more information, see https://github.com/sourcegraph/cody/pull/907#discussion_r1320490212
One of the many prompts I've tried to prevent hallucination is to add `Do not make any assumptions about the code and file names or any misleading information` to the question, which has been working well for me. This is also the prompt we added to all our …

refactor: update preamble rules and mixin

---

completions-review-tool/data/anthropic-infill-1698086370191.json
completions-review-tool/data/anthropic-infill-1698092878117.json
vscode/src/completions/get-inline-completions-tests/common.test.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/text-processing/parse-and-truncate-completion.ts
vscode/test/completions/mock-vscode.ts

fix: use full infill block and adjust prefix
- fix prompt structure order, context should be shared after the role assigning
- empty prefix if it contains the infill block for issue where first line is duplicated 
- Simplify prompt messages to focus on providing clear context
- Add CLOSING tag for Assistant's infill block to preserve ending whitespace 
- This also fixed issues where multi-line autocomplete gets cut off.
- remove tags for context code as that might cause confusion for claude
Fix: show multi-line completion after `{`:
Fix: show multi-line completions the line after `{`

fix: update post process logic for claude instant

---

vscode/CHANGELOG.md

Adding missing changelog entries from pull/1440 and pull/1442
Changelog updated

Add missing changelog entries

---

vscode/CHANGELOG.md
vscode/src/completions/get-current-doc-context.test.ts
vscode/src/completions/get-current-doc-context.ts
vscode/src/completions/get-inline-completions-tests/last-candidate.test.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/request-manager.ts
vscode/src/completions/reuse-last-candidate.ts

This PR fixes a race condition that was observed when picking items from the suggest widget. The main reason for this was that the `reuseLastCandidate` logic was not aware of the _actual_ document state but only comparing the doc context `prefix`. This, in some cases, can have the suggest widget candidate injected. 
Now, for that logic, these two completions are exactly the same:
- A completion request for `console.█` with `log` selected in the suggest widget
- A completion request for `console.log█`
This made this logic conclude that it is safe to return the same suggest (`log`) in both cases, causing the repitition.
While working on this, I also noticed another issue with how we calculate the `current-doc`: Right now, this would only work if the selection to be replaced is non-emtpy. …

Autocomplete: Fix suggest item race condition

---

lib/shared/src/telemetry/EventLogger.ts

This change makes it so that you can provide `hasV2Event` in `properties`, because it is easy to accidentally put `opts` as the second argument, and also adds `hasV2Event` to the published event log properties.
n/a

eventlogger: accept hasV2Event in properties, add to properties

---

vscode/test/benchmark/datasets/typescript/object-property-access-closed-file/config.json
vscode/test/benchmark/datasets/typescript/object-property-access-open-file/config.json

When running noticed the config was backward on these two
n/a bnechmark config change only

Benchmarks: update benchmark config to match folder name

---

vscode/src/completions/test-helpers.ts
vscode/src/completions/tree-sitter/queries.ts
vscode/src/completions/tree-sitter/query-tests/intents.test.ts
vscode/src/completions/tree-sitter/query-tests/test-data/intents.jsx
vscode/src/completions/tree-sitter/query-tests/test-data/intents.snap.jsx
vscode/src/completions/tree-sitter/query-tests/test-data/intents.snap.ts
vscode/src/completions/tree-sitter/query-tests/test-data/intents.snap.tsx
vscode/src/completions/tree-sitter/query-tests/test-data/intents.ts
vscode/src/completions/tree-sitter/query-tests/test-data/intents.tsx

- This PR adds the JSX-specific completion intent, `jsx_attribute`, which is one of the most popular suggestions (~10% of all JS/TS suggested completions) with low average CAR (~15%) based on [the analytics data](https://console.cloud.google.com/bigquery?sq=839055276916:addb416ff2c146e39f524b526cccd9d8).
- Follow-up for https://github.com/sourcegraph/cody/pull/1457
- Closes https://github.com/sourcegraph/cody/issues/1472
- Part of https://github.com/sourcegraph/cody/issues/1455
Added new unit tests.

Autocomplete: add `jsx_attribute` completion intent

---

vscode/src/os.ts

A new alias x64 was added for the x86_64 architecture in the getOSArch function.
For windows with x64 returned by`os.arch()` currently returns undefined as it's missing on the list.
On Windows, os.arch() can return 'x64', 'ia32', or 'x86' to indicate 64-bit or 32-bit architectures.
Without the 'x64': 'x86_64' mapping, if os.arch() returns 'x64' on Windows, the arch value would be undefined in the return value of getOSArch.
This is also what we used to create the URLs for downloading Cody App

add new aliases for x86_64 architecture

---

vscode/src/repository/repositoryHelpers.ts

Previously, the URI was encoded incorrectly because we passed a Windows path with backslashes as URI paths, meaning they got escaped. This PR fixes the problem by removing the logic to send the .git/ subdirectory because gix infers it anyways on the server side.
Manually tested on Windows.

BFG: fix git URI inference on Windows

---

lib/shared/src/telemetry-v2/index.ts
vscode/src/chat/ContextProvider.ts
vscode/test/e2e/inline-assist.test.ts
vscode/test/e2e/task-controller.test.ts

run extension in debug mode
check test eventlogs on dotcom for event emission
check bigquery for event reception

Add secondary telemetry to ContextProvider

---

lib/shared/src/chat/markdown.ts
lib/ui/src/chat/TranscriptItem.module.css
vscode/webviews/Chat.module.css

Improves the rendering of headings and inline code elements in chat.
| - | - |
| <img width="929" alt="Screenshot 2023-10-27 at 1 52 41 pm" src="https://github.com/sourcegraph/cody/assets/153/28bd1cc0-3d83-47c0-bbda-a4b018b3dede"> | <img width="929" alt="Screenshot 2023-10-27 at 1 52 08 pm" src="https://github.com/sourcegraph/cody/assets/153/1b4d8657-09fa-4cd0-b00a-54871f0896ab"> |
| <img width="929" alt="Screenshot 2023-10-27 at 1 52 45 pm" src="https://github.com/sourcegraph/cody/assets/153/3ea057a5-ea51-421c-9ff9-c6eef361a7d8"> | <img width="929" alt="Screenshot 2023-10-27 at 1 52 04 pm" src="https://github.com/sourcegraph/cody/assets/153/7bf0f7bf-4851-4c0d-92a4-f9353f03db7f"> |
| <img width="929" alt="Screenshot 2023-10-27 at 1 59 05 pm" …

Chat: Fix heading styles and inline code colors

---

vscode/CHANGELOG.md
vscode/src/editor/vscode-editor.ts

fix: smart selection not working on the first line of code
This issue was caused by `!selection?.start.line` in the smart selection function excluding the possibility of `selection?.start.line === 0` (the vs code API returns the line number on display - 1, so line 1 in the editor would returns 0). 
This commit fixes that by explicitly checking selection.start.line is not null and is not equal to 0 before failing.
Try running the `Generate Unit Tests` command on the first line of the file:
You should be able to run the command and the expanded range will be selected for you automatically when available:

fix: smart selection not working on the first line of code

---

vscode/package.json

feat: add icons and enablement conditions for commands
This commit adds icons and "when" enablement conditions for various Cody commands in the package.json file. 
Commands should be toggled based on the new when clauses.

feat: add icons and enablement conditions for commands

---

vscode/src/graph/bfg/BfgContextFetcher.ts
vscode/src/graph/bfg/download-bfg.ts
vscode/src/jsonrpc/bfg-protocol.ts

The release is running so the binary artifacts are not available yet. Let's wait with merging until Monday.
- Start local mode with BFG enabled
- Confirm that it downloads the binary, indexes the codebase and returns relevant symbol context

BFG: bump to 5.2.4257

---

vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/text-processing/process-inline-completions.test.ts
vscode/src/completions/text-processing/process-inline-completions.ts

- Fixes the issue where completions were needlessly hidden: `myFunction(█)` with the insert text being `"one", false` because the current line suffix `)` was not present in the generated completion. However, we still adjusted the completion insertion range to include it. 
- Fixes the issue where all the generated completions were hidden, even if only one needed to be ignored. Now, we filter out invisible completions individually and keep visible completions if we have any.
Added unit tests.

Autocomplete: do adjust a completion range if it does not match the current line suffix

---

vscode/CHANGELOG.md
vscode/src/custom-prompts/CustomPromptsStore.ts

The Custom Commands action shows the incorrect menu (the generic custom commands config quickpick) if you only have a single custom command defined, due to an off-by-one. This fixes it so it shows the correct menu.
- Created a single custom command. Tested the action.

Custom Commands: Fix custom command menu not showing for a single custom command

---

vscode/CHANGELOG.md
vscode/src/chat/MessageProvider.ts

The commit adds a new call to saveTranscriptToChatHistory() before cancelling completion and notifying turn is complete. This saves the chat transcript to history when aborting a chat message.
1. abort a message in progress
2. reload chat
3. open chat history for the message you aborted
cody's response before you pressed abort is removed
cody's response before you pressed abort is showing up in chat history

fix: save transcript to chat history on abort

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/get-inline-completions-tests/analytics.test.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/createProvider.test.ts
vscode/src/completions/providers/createProvider.ts

Adds a new feature flag to test Claude Cyan (c.f. https://sourcegraph.slack.com/archives/C04D0GRD1GB/p1698383238134869)
The flag is evaluated after the starcoder one so if we set it to a `50/50` split it will only affect users that are not in the starcoder test group.
Manually changed the code to be inside the Claude Cyan group and ensure the right request is sent. The dotcom instance was already updated to support this.

Autocomplete: Add feature flag to test Claude Cyan

---

vscode/package.json
vscode/src/chat/chat-view/ChatPanelProvider.ts

Added chat panel icon and update view type name for chat panel
In Time's design, there is an icon to create a new chat in each chat panel, this PR addresses that.
- Change chat panel icon from $(add) to $(empty-window)
- Change view type const from chatID to 'cody.chatPanel'

update chat panel icon and view type

---

vscode/src/non-stop/FixupCodeLenses.ts

The new error handling logic was being hidden due to the codelens being removed.
It was already fixed this is just from a bad merge.
Force an error
Check code lens appears
Check code lens is functionality

Fixup: Fix error codelens being hidden

---

vscode/src/non-stop/FixupController.ts

We accept fixups automatically if there is any change within the fixup range (includes undo). We were not exiting early here so we were also recomputing the diff and showing decorations. We need to remove all decorations once the fixup is considered accepted.
Tested locally
-> Create fixup -> Undo -> Check decorations
-> Create fixup -> Edit text -> Check decorations

Fixup: Avoid recreating diff on acceptance

---

lib/shared/src/chat/recipes/fixup.ts
lib/shared/src/editor/index.ts
vscode/src/chat/InlineChatViewProvider.ts
vscode/src/non-stop/FixupController.ts

Solves Part 1 of #1544 
Quoting @umpox 
Tested locally in debug mode with fixup/chat/inline

Removing classifyIntent call to LLM to optimize Fixup recipes

---

vscode/src/chat/MessageProvider.ts

fix: remove extra call to loadChatHistory()
This fixes issue where the last response from Cody is missing after starting a new chat session
This commit removes the extra unnecessary call, which avoids loading the old chat history before saving it in `saveChatHistory`.
Ask Cody a question, and then restart your VS Code. Go back to your chat history for your last session.
Cody's response in the last chat was not stored
Cody's response in the last chat was stored properly and can be seen in UI

fix: remove extra call to loadChatHistory

---

lib/ui/src/Chat.tsx
vscode/CHANGELOG.md

fix: prevent chat command selection from propagating event
Prevent the up/down arrow key events from propagating when cycling through chat command suggestions. This stops the cursor within the input box from moving up to the front when selecting a suggestion.
Using arrow up in command selection box will move the cursor to the front
Moving up and down should not move the cursor position when the command selection box is showing. Cursor should stays in the back:

fix: prevent chat command selection from propagating event

---

vscode/src/completions/context/lsp-light-graph-cache.test.ts
vscode/src/completions/context/lsp-light-graph-cache.ts
vscode/src/graph/lsp/graph.ts
vscode/src/testutils/test.ts

Closes #1506
The recursion doesn't work well and there's no ned for improving it right now. Better test a stupider version that is less prone to have perf issues before we roll out the bigger changes.
- Enable `lsp-light` context
- Open the trace view
- Trigger a completion and see that nothing but the hover information is added

Autocomplete: Remove recursion from lsp light

---

vscode/src/completions/logger.test.ts
vscode/src/completions/logger.ts

Log partial accept events only if the partial acceptance length increases to avoid overcounting the number of partially accepted chars.
Added a unit test.

Autocomplete: log partial acceptance events only if the length increases

---

vscode/src/completions/get-current-doc-context.ts
vscode/src/completions/get-inline-completions-tests/last-candidate.test.ts
vscode/src/completions/request-manager.ts
vscode/src/completions/reuse-last-candidate.ts
vscode/src/completions/text-processing/process-inline-completions.ts

- Reuse the last candidate if the user types forward as suggested despite the updated completion info.
- See the new added test with the inline description for the use-case. 
Updated unit tests

Autocomplete: reuse the last candidate if the user types forward as suggested despite the updated completion info

---

vscode/src/completions/get-inline-completions-tests/last-candidate.test.ts
vscode/src/completions/reuse-last-candidate.ts

- Log partial acceptance events on every word instead of every char to reduce the volume of the partial acceptance event being sent.
Updated unit tests

Autocomplete: log partial acceptance events on every word instead of every char

---

vscode/package.json
vscode/src/services/treeViewItems.ts

Add a new 'Chat' item to the sidebar tree view commands. 
This will open a new chat panel when clicked.
- Click on the new `Chat` command in the new chat view
- The command should open a new chat panel for you

feat: add chat command to sidebar view

---

vscode/src/non-stop/FixupController.ts
vscode/src/non-stop/FixupTask.ts
vscode/src/non-stop/codelenses.ts
vscode/src/non-stop/utils.ts

Adds a codelens state for the formatting part, as this could take a noticeable amount of time depending on the users' formatter.
Also added the ability to skip formatting if it's taking a long time:
https://github.com/sourcegraph/cody/assets/9516420/b0c06318-b8da-465f-bccd-9e661ee7fe38
Tested locally with different formatters.

Fixup: Add formatting codelens and the option to skip

---

lib/ui/src/chat/CodeBlocks.tsx
vscode/CHANGELOG.md

Pass requestID and source metadata to copy button event handlers directly instead of through dependencies.
Using metadata as a dependency caused useEffect to keep re-rendering and append multiple copy buttons on mount. Passing the metadata directly to the event handler fixes this issue.
By constructing the metadata object inside the callback and passing it directly, the metadata gets passed to the buttons without causing re-renders from useEffect.
This avoids the issue of useEffect appending multiple buttons on each render.
To reproduce:
1. Ask Cody a question that generate code: `What does a button looks like in html?`
2. in the same Window, send Cody another question, e.g. `Hello`

fix: code block actions event handlers

---

vscode/src/main.ts

We often call `setupAutocomplete` multiple times, which throws a VS Code error and possibly causes other unintended behavior.
This change queues the calls so we don't attempt to create parallel completion providers.
Tested locally:
- Open a fresh VS Code window with the Cody sidebar already open
- Confirm no errors like `[sourcegraph.cody-ai]command 'cody.autocomplete.manual-trigger' already exists` are shown in dev tools

Completions: Fix duplicate InlineCompletionItemProvider bug

---

.github/ISSUE_TEMPLATE/prd-issue.md

github didn't update docs when they changed the value of `description` to `about` and it broke the template 😢 
n/a

fix about value in template

---

vscode/CHANGELOG.md
vscode/src/non-stop/FixupController.ts

We use a temp document to provide a "before" version of the edited fixup file. There is an edge case where, if we are adding new code (thus deleting from the temp document), we can reuse the already diffed temp document. This leads to the diff expanding every time it is triggered, as we delete more code from the selection.
We now ensure each diff has its own unique ID, so it always uses a fresh "temp" document. 
https://github.com/sourcegraph/cody/assets/9516420/c584f8a5-e21c-468f-bb82-c9eece29cc38
https://github.com/sourcegraph/cody/assets/9516420/20eb4fd5-b318-47d2-b66c-c9a3b9d076c1
Tested locally:
- Diff for edits that expand ranges
- Diff for an edit where the doc has been changed elsewhere after it was applied

Edit: Fix recursive diff expansion

---

vscode/CHANGELOG.md
vscode/src/non-stop/FixupController.ts
vscode/src/non-stop/utils.ts

closes https://github.com/sourcegraph/cody/issues/1552
It appears that VS Code doesn't use these automatically, and some formatters expect that they are provided.
Related issue: https://github.com/sourcegraph/cody/issues/1552
Tested with different formatters
Tested with `Python Black Formatter` which was erroring previously

Fixup: Use editor `tabSize` and `insertSpaces` when available

---

vscode/CHANGELOG.md
vscode/src/non-stop/FixupController.ts
vscode/src/non-stop/FixupTask.ts

The retry instruction text has the command attached, which recursively adds to each retry. This PR fixes this issue that in case of any fixup task, only the previous instruction is used/shown in the quick pick. 
- Tested manually.
Before behaviour:
https://github.com/sourcegraph/cody/assets/44617923/70daecc9-bf38-4dd5-bca9-271367f4441c
After:
https://github.com/sourcegraph/cody/assets/44617923/1916df2e-b616-4f1c-96a6-c7144844759d

Update the FixUp retry instruction text

---

lib/shared/src/local-context/index.ts
pnpm-lock.yaml
vscode/package.json
vscode/src/chat/chat-view/SidebarChatProvider.ts
vscode/src/chat/local-code-search.ts
vscode/src/chat/protocol.ts
vscode/src/local-context/download-symf.ts
vscode/src/local-context/symf.ts
vscode/src/main.ts
vscode/src/search/SearchViewProvider.ts
vscode/test/e2e/helpers.ts
vscode/webviews/SearchPanel.module.css
vscode/webviews/SearchPanel.tsx
vscode/webviews/search.html
vscode/webviews/search.tsx
vscode/webviews/vite.config.ts

Adds a symf-powered Cody search panel that meets @toolmantim's design.
Watch the loom: https://www.loom.com/share/7ea48cc631d5407e9b746463275625ae?sid=f68e7f01-be12-472d-a2ab-19975808940d
There is no easy way to import the language-specific file icons from the user's VS Code theme. We could just use one of the default themes' (there are two) icon sets, but I think that would look janky if the user is using another theme. So all files currently share the same icon, which is pulled from the non-file icon set, which is made available to exensions:
Try it on different repositories in different languages (including ones we don't typically use).

Cody search panel

---

lib/shared/src/sourcegraph-api/environments.ts
vscode/webviews/Chat.tsx

The goal of this PR is to collect `transcript` again when a user submits feedback. IMPORTANT to note, that we only want to collect transcript for free community users that are connected to dotcom.
steps added:
- Add `isDotCom` check before setting `transcript` (only set if `isDotCom` endpoint)
- Stringify transcript before adding to eventData
Tested locally by connecting to S2 and ensuring no value is sent for `transcript` and when connected to sourcegraph, `transcript` value is populated

add back `transcript` to cody feedback event data for dotcom users

---

vscode/src/completions/detect-multiline.ts
vscode/src/completions/get-current-doc-context.test.ts
vscode/src/completions/get-current-doc-context.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions-tests/last-candidate.test.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/logger.test.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/provider.ts
vscode/src/completions/providers/unstable-openai.ts
vscode/src/completions/request-manager.test.ts

This was added specifically to opt-out of some multi-line completion triggers when using the CodeGen backend (as it would not honor the max tokens set and only return a single-line result).
Since we no longer have to support that backend, we don't need to branch off anymore based on this field. This fixes an issue where the OpenAI client has different multi-line behavior.
- Tests green
- TS happy

Autocomplete: Remove enableExtendedTriggers flag

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/ChatPanelProvider.ts

RE: https://sourcegraph.slack.com/archives/C05AGQYD528/p1699403470817339
fix: open document side by side with chat panel
Check current webview panel location before opening the document to show it side by side instead of replacing the chat panel.
https://github.com/sourcegraph/cody/assets/68532117/bca885f8-8b09-4908-8500-707e5b3eeb91

fix: open document side by side with chat panel

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/ChatManager.ts

Reported in https://sourcegraph.slack.com/archives/C05AGQYD528/p1699400897961909
fix: do not open chat for doc/edit commands
The `/doc` and `/edit` commands were incorrectly opening a new chat panel. This fixes it to not creating any new chat panel or opening existing chat window  when running the `/doc` and `/edit` commands.
https://github.com/sourcegraph/cody/assets/68532117/0b365a6d-f380-4093-91a9-fdf01efb588b
First, close the cody sidebar
Then try running the `/doc` command from:
An empty chat window will pop up
All chat windows remains closed (when closed)

fix: do not open chat for doc/edit commands

---

vscode/package.json
vscode/src/completions/providers/fireworks.ts

Reusing the Anthropic prompt seems to work alright so far. Need to run this through our local eval suite next 👀

Autocomplete: Add initial prompting for Mistral 7b

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
lib/shared/src/sourcegraph-api/errors.ts
vscode/CHANGELOG.md
vscode/src/completions/client.ts
vscode/src/completions/logger.ts
vscode/src/completions/providers/createProvider.ts
vscode/src/completions/providers/fireworks.ts

Now that I have added support for `fireworks/accounts/sourcegraph/models/starcoder-16b` and `fireworks/accounts/sourcegraph/models/starcoder-7b` to the Cody Gateway, we can start using it on the dotcom clients.
To roll this out, I’m adding a new flag `cody-autocomplete-default-starcoder-hybrid-sourcegraph` that is only used when `cody-autocomplete-default-starcoder-hybrid` is also true. This way we can set `cody-autocomplete-default-starcoder-hybrid-sourcegraph` to a 50:50 split and it will only affect the test group that is already in the StarCoder branch.
I expect this to be very short lived but it would be great if we can measure the affect of that migration. 
I plan to roll this out as a patch release so we can turn this on in the next days.

Autocomplete: Add feature flag for Sourcegraph specific Fireworks setup

---

vscode/src/local-context/download-symf.ts

Fixes a bug where the extension tries to download `symf` for Linux from https://github.com/sourcegraph/symf/releases/download/v0.0.2/symf-x86_64-linux.zip, which 404s because the symf build names it `symf-x86_64-linux-musl.zip`. Now, `linux` maps to `linux-musl` and `windows` maps to `windows-gnu`. This matches the filenames in the release at https://github.com/sourcegraph/symf/releases/tag/v0.0.2.
Tested on Linux and confirmed that `symf` is downloaded successfully.

fix symf download URL for linux and windows

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/ChatPanelsManager.ts

fix: Prevent sidebar from opening when switching editor panels
The chat panel switching logic was incorrectly opening the sidebar. 
This fixes it by not revealing chat item in tree view when sidebar is not visible. 
https://github.com/sourcegraph/cody/assets/68532117/36da179f-a87b-4002-be2a-b0072d575074
https://github.com/sourcegraph/cody/assets/68532117/48ee4a96-c72b-495c-a05b-2f5abeb16434

fix: stop sidebar from opening on panels switch

---

vscode/src/chat/chat-view/ChatPanelProvider.ts
vscode/src/chat/chat-view/SidebarChatProvider.ts
vscode/src/main.ts
vscode/src/non-stop/FixupController.ts
vscode/src/services/InlineAssist.test.ts
vscode/src/services/InlineAssist.ts
vscode/src/services/InlineController.ts
vscode/src/services/utils/code-count.test.ts
vscode/src/services/utils/code-count.ts
vscode/src/services/utils/codeblock-action-tracker.ts
vscode/src/services/utils/workspace-action.ts

refactor: move codeblock and workspace actions out of view providers (SidebaChatProvider and ChatPanelProvider)
This separates code block action and workspace files action handling from the SidebaChatProvider and ChatPanelProvider.
Currently they are duplicated.
Move codeblock action and workspace files handling to separate utils files. 
- Handle insert at cursor in `handleCodeFromInsertAtCursor`
- Handle save to new file in `handleCodeFromSaveToNewFile` 
- Handle copied code in `handleCopiedCode`
Only move the handling to separate files. This should not change any existing functions or features.

refactor: move codeblock and workspace actions

---

vscode/CHANGELOG.md
vscode/package.json

fix: prevent "command not found" error when chat panel disabled
Update the keybinding enablement conditions to avoid invoking the command when the chat panel config is disabled. This fixes the "command not found" error that currently shows when invoking the keybinding while `cody.experimental.chatPanel` is false.
In the old chat UI, focus on the chat input box, and then press `alt` + `/` - you will see an error message pops up:
Do the same thing as described above - you should not see the error message pop up again.

fix: error from new chat shortcut

---

agent/src/agent.ts
vscode/src/jsonrpc/agent-protocol.ts

This is needed to fix [JetBrains: integrate autocomplete with lookup manager#57335](https://github.com/sourcegraph/sourcegraph/issues/57335).
It appends element from IntelliJ's lookup manager to the file in place of autocompletions, in order to generate completion including part from lookup manager.
Test requires changes on Jetbrains part so it is not possible at the moment. Those changes should not affect regular autocompletion behaviour.

Integrating autocompletion with lookup manager

---

vscode/src/chat/chat-view/ChatPanelProvider.ts

feat: change chat panel view column to beside
Change the default view column for the chat panel from Two to Beside.
This will always open the chat panel next to the current editor instead of panel two.
Try creating a new chat panel, a new one should always opened next to your current active editor panel
https://github.com/sourcegraph/cody/assets/68532117/b07e3cc1-052b-4ea5-b6ce-1f7c4f881e35

change chat panel view column to beside

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/chat/chat-view/ChatPanelProvider.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/main.ts

Added reset current chat button in editor title when new cody chat panel is active
- Add new "cody.chat.restart" command to restart the chat session
- Update ChatManager to call clearAndRestartSession() on active chat panel
- Update ChatPanelsManager to handle chat reset in current panel
- Add command registration in main.ts
https://github.com/sourcegraph/cody/assets/68532117/99d17032-d27a-4a39-b088-418123128469
Start a chat session in the new Chat UI, and then click the new reset button
Nothing is affected in the old chat UI

feat: add restart chat btn to new chat panel

---

agent/src/editor.ts
lib/shared/src/chat/context-filter.ts
lib/shared/src/chat/ignore-helper.test.ts
lib/shared/src/chat/ignore-helper.ts
lib/shared/src/chat/transcript/interaction.ts
lib/shared/src/codebase-context/messages.ts
vscode/src/completions/context/context-graph.ts
vscode/src/completions/context/context-local.ts
vscode/src/completions/context/context.ts
vscode/src/completions/context/lsp-light-graph-cache.test.ts
vscode/src/completions/context/lsp-light-graph-cache.ts
vscode/src/completions/context/section-observer.test.ts
vscode/src/completions/context/section-observer.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/types.ts
vscode/src/editor/vscode-editor.ts

add fileUri

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/can-use-partial-completion.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/provider.ts
vscode/src/completions/providers/unstable-openai.ts
vscode/src/completions/text-processing/parse-and-truncate-completion.ts
vscode/src/completions/text-processing/truncate-parsed-completion.ts

- Removed the `cody-autocomplete-disable-streaming-truncation` feature flag.
- Changed the multiline truncation cache, which enhances performance by eliminating the need to re-parse the first line for each new line received in a completion.
- Follow-up for https://github.com/sourcegraph/cody/pull/1709/
- Part of https://github.com/sourcegraph/cody/issues/1402
Unit tests + local manual testing.

Autocomplete: use streaming truncation for all completion requests

---

vscode/src/completions/client.ts

- There's no need to process the already received completion chunks if the signal is aborted (it means we already received the completion that we can show to the user).
CI

Autocomplete: do not trigger the partial response callback when the request is aborted

---

agent/package.json
agent/src/agent.ts
agent/src/bfg/BfgContextFetcher.test.ts
agent/src/cli/evaluate-autocomplete/Queries.ts
agent/src/cli/evaluate-autocomplete/evalaute-autocomplete.ts
agent/src/cli/jsonrpc.ts
agent/src/cli/root.ts
agent/src/index.ts
agent/src/vscode-shim.test.ts
agent/src/vscode-shim.ts
agent/tsconfig.json
package.json
pnpm-lock.yaml
vscode/src/completions/context/retrievers/bfg/bfg-retriever.ts
vscode/src/custom-prompts/ToolsProvider.ts
vscode/src/graph/bfg/download-bfg.ts
vscode/src/jsonrpc/agent-protocol.ts
vscode/src/jsonrpc/jsonrpc.ts
vscode/src/services/sentry/sentry.ts
vscode/src/services/utils/workspace-action.ts

Previously, I didn't have a good way to test BFG alongside Cody. I just
manually started a local build of the extension, waited for indexing to
finish and triggered autocomplete. This PR fixes this problem by making
it easy to run Cody autocomplete in batch mode against any codebase by
adding a new `evaluate-autocomplete` subcommand. This new command made
it much easier for me to debug BFG and implement critical fixes. It also
makes it much easier to compare the difference between BFG and non-BFG
context.
```
pnpm install
pnpm build
cd agent
pnpm agent evaluate-autocomplete --workspace ~/dev/sourcegraph/bfg-private --queries ~/dev/sourcegraph/bfg-private/crates/bfg/queries/ --include-pattern crates/bfg/snapshots/input/typescript/main.ts --test-count 1 --snapshot-directory …
```

Agent: add `evaluate-autocomplete` subcommand

---

agent/src/agent.ts
agent/src/bfg/BfgContextFetcher.test.ts
agent/src/cli/evaluate-autocomplete/evaluate-autocomplete.ts
agent/src/cli/root.ts
agent/src/vscode-shim.ts
vscode/src/completions/context/retrievers/bfg/bfg-retriever.ts
vscode/src/extension.node.ts
vscode/src/repository/repositoryHelpers.ts

Previously, we tried to infer the git repository based on open documents. This logic was brittle causing BFG to not pick up repositories when it should. This PR replaces this logic with direct calls to the git extension, which gives us access to this information directly.
See updated `BfgContextFetcher.test.ts`. I also manually tested that BFG is loaded when running the new autocomplete evaluation.

BFG: correctly load git repositories

---

lib/shared/src/chat/prompts/display-text.test.ts
lib/shared/src/chat/prompts/display-text.ts

The file link markdown generation was previously erroring when the start line was 0. This fixes it by checking for a valid end line instead of start line.
Also simplifies the regex used to replace the file name with a markdown link.
Added new test for  edge case error when generating markdown links for selections starting at line 0.

fix: handle @ files with start line 0

---

agent/src/cli/evaluate-autocomplete/evaluate-autocomplete.ts
vscode/src/completions/context/retrievers/bfg/bfg-retriever.ts
vscode/src/graph/bfg/download-bfg.ts

The name of the binary appears in activity monitors and we want to make it easy for users to trace it back to Cody. We still keep the "bfg" codename in the implementation (variable names, JSON-RPC protocol, etc.)
because it requires non-trivial engineering effort to change the name
everywhere and we don't think this is worth the effort at this early
stage of the project.
I kept the `graphContext: 'bfg'` setting name because that is specifically about code graph. I'm open to changing that as well to `cody-engine` but I don't think it's necessary.
Ran extension manually and confirmed that the output channel doesn't print BFG-related messages. Also confirmed that the binary name is now named "cody-agent-*"

BFG: rename `bfg` binary name into `cody-engine`

---

vscode/webviews/Components/ChatModelDropdownMenu.module.css

fix: adjust width and height of header logo
Minor UI change: Reduced height of header logo and adjusted styling to fit dropdown container width.
- The width of the dropdown container was increased to 100% to take up full width. 
- The height of the header logo was reduced from 1.5rem to 1rem to better fit the container. 
- The logo width was also reduced and padding added.
Minor UI change:

fix: adjust width and height of provider logo

---

lib/shared/src/chat/markdown.ts
vscode/CHANGELOG.md

Currently the `<style>` tag is breaking Cody as reported in https://sourcegraph.slack.com/archives/C03CSAER9LK/p1698893918877999:
This PR adds 'style' to the FORBID_TAGS array in the DOMPurify config to prevent style tags from being allowed.
1. Ask Cody :
Where is the styling defined for the code below?
```
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
viewBox="0 0 16 16" style="enable-background:new 0 0 16 16;" xml:space="preserve">
<style type="text/css">
.st0{fill:none;stroke:#231F20;stroke-width:1.5;stroke-linecap:round;stroke-miterlimit:10;}
</style>
<path class="st0" d="M4,5.6h2.5"/>
<path class="st0" d="M11,3.8v2.5"/>
<path class="st0" …
```

fix: forbid `<style>` tags in DOMPurify config

---

agent/src/agent.ts
agent/src/cli/evaluate-autocomplete/evaluate-autocomplete.ts
agent/src/cli/evaluate-autocomplete/formatSnapshot.ts

Previously, `evaluate-autocomplete` required all the arguments to be passed from the command-line and it was only able to evaluate a single workspace at a time (with no parallelization!). Now, you can evaluate multiple workspaces in parallel based on JSON configuration inside a file. This makes it easy to run evaluations on a cron job to track progress.
I've been iterating with a command like this
```
pnpm agent evaluate-autocomplete --evaluation-config ~/dev/sourcegraph/bfg-evaluation/evaluation.json --include-workspace '**/flask' --test-count 1
```

Agent: support multiple workspaces with `evaluate-autocomplete`

---

lib/shared/src/experimentation/FeatureFlagProvider.ts

Autocomplete: Remove unused feature flag

---

vscode/src/chat/ContextProvider.ts
vscode/src/external-services.ts

Part of https://github.com/sourcegraph/cody/issues/1544
Part of https://github.com/sourcegraph/cody/issues/1464
The LLM reranker adds a significant amount of latency to reranking any fetched context. This applies to all commands, chat and edits. The latency is typically between 2-5 seconds.
This PR just disables the reranker for now.
I think this is worth doing as:
- The added latency from the reranker is not worth the possible benefit right now. It still can sometimes rerank poorly and doesn't provide enough value to justify waiting that long.
- Context doesn't have a constant value, in many cases context will provide little value (e.g. simple fixups) in some cases, like chat, context would provide a lot more value. We don't have a way of determining that right now, so we're often adding …

Chat/Commands: Remove LLM reranker for repos without embeddings

---

vscode/webviews/App.tsx

CLOSE https://github.com/sourcegraph/cody/issues/1754
Do not reset file matches on every key press.
The panel flashes on every input change
https://github.com/sourcegraph/cody/assets/68532117/d2ef0df2-94cf-428c-9462-9a4d0bb89ebb
The panel gets updated in place
https://github.com/sourcegraph/cody/assets/68532117/6cf7321e-fc89-4f5f-89b3-4ff53fe64d9d

fix: do not reset file matches on every key

---

lib/shared/src/chat/recipes/helpers.test.ts
lib/shared/src/chat/recipes/helpers.ts
vscode/CHANGELOG.md

Due to the prompt, the LLM sometimes gets confused and adds some of the mentioned XML tags (`selectedCode`|`problemCode`) to the start and end of the text.
We were only removing this from the end previously. This will fix that
Create multiple edits. Check for `selectedCode`

Edit: Fix `selectedCode` and `problemCode` appearing in edits

---

vscode/CHANGELOG.md
vscode/src/non-stop/FixupController.ts

Fixes https://github.com/sourcegraph/cody/issues/1762
If a user has `autoSave` set to a value like `onFocusChange` or `afterDelay`, then it is possible that the edit code lens will immediately be dismissed.
The best thing we can do here is just to avoid dismissing on save for these cases. The code lens will still be dismissed when a user clicks "Done" or if a user manually changes some code in the selection.
1. Set `files.autoSave` to something other than the default value
2. Create a fixup and check the codelens doesn't immediately disappear

Edit: Fix flickering code lens for users with autoSave enabled

---

lib/shared/src/telemetry/EventLogger.ts
lib/ui/src/chat/components/EnhancedContext.tsx
vscode/src/chat/MessageProvider.ts
vscode/webviews/Components/FileLink.tsx

Some minor cleanup for the things I noticed when running the main build for 0.16.0:
Chat UI:
the new context files display widget does not work well with conversation from old chat history, where lines will always be 0:
After:
Other housekeeping items:
- log numbers of context added by users via @ command
- log  usage of the new chat UI
Start Cody and check your chat history.

fix: context files always display 0 lines

---

vscode/src/completions/logger.test.ts
vscode/src/completions/logger.ts

- Part of #1775 
- Based on [the Slack thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1700212920663709?thread_ts=1698983739.534099&cid=C05AGQYD528).
n/a

Autocomplete: remove top level `charCount` from completion events

---

vscode/src/completions/context/retrievers/bfg/bfg-retriever.ts
vscode/src/graph/bfg/download-bfg.ts
vscode/src/local-context/download-symf.ts

Just adding a sentry callback to error handlers

Capture dependency download issues in Sentry

---

vscode/src/configuration-keys.ts
vscode/src/configuration.ts

This PR closes #1667. 
I have implemented a function that checks for the allowed enum values for the Cody config. If the config value is not from the allowed list of enum values, then it shows an error during startup.
Open the `settings.json` and change `cody.autocomplete.advanced.provider` to `gpt-4`. After this, reload the window a VSCode error message will be displayed during the startup.

Add config error handler

---

vscode/src/jsonrpc/jsonrpc.ts

Issue: https://github.com/sourcegraph/sourcegraph/issues/56455.
Jetbrains part: https://github.com/sourcegraph/jetbrains/pull/111
mock throw the error from the autocompletion and recipe request
runide with a local clone of cody

Add RateLimitError to jsonrpc

---

vscode/src/jsonrpc/jsonrpc.ts

Silences all the "Promise returned in function argument where a void return was expected."
N/A type checker fixes

Allow promise return in notifications

---

agent/src/vscode-shim.ts
vscode/src/jsonrpc/agent-protocol.ts

Checked for existing values of `ClientInfo.name` for editors:
1. [neovim](https://sourcegraph.com/github.com/sourcegraph/sg.nvim/-/blob/lua/sg/cody/rpc.lua?L281) 
2. [jetbrains](https://sourcegraph.com/github.com/sourcegraph/jetbrains/-/blob/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt?L69)
3. [emacs](https://sourcegraph.com/github.com/sourcegraph/emacs-cody/-/blob/cody.el?L311:24)

Return 'cody.advanced.agent.ide' from ClientInfo.name

---

lib/shared/src/chat/prompts/vscode-context.ts
lib/shared/src/telemetry-v2/TelemetryRecorderProvider.ts
vscode/CHANGELOG.md
vscode/src/chat/ContextProvider.ts
vscode/src/editor/vscode-editor.ts
vscode/src/local-context/filename-context-fetcher.ts
vscode/src/local-context/local-keyword-context-fetcher.ts

Fixes an error that occurred when attempting to get the current VS Code document context. The previous methods for retrieving the active editor, document, and document text do not work with the new chat panel because when an user focuses on the webview panel we run the vscode.window.activeTextEditor, it would always returns `undefined`,  cause Cody unable to fetch local context.
This replaces the previous logic with new utility functions `getActiveEditorFromVisibleEditors`, `getCurrentVSCodeDoc`, and `getCurrentVSCodeDocText` that more robustly retrieve the current document context that is not the focused webview chat panel.
- Select some code in your editor
- In the new chat panel UI, type `/test` to run the test command
- Before the fix, Cody will tell you it doesn't have any context …

fix: resolve editor when getting doc context

---

lib/ui/src/chat/Transcript.tsx
lib/ui/src/chat/TranscriptItem.module.css
lib/ui/src/chat/TranscriptItem.tsx
vscode/webviews/Chat.module.css
vscode/webviews/Chat.tsx

CLOSE https://github.com/sourcegraph/cody/issues/1655 && https://github.com/sourcegraph/cody/issues/1780
This PR fixes the issue where edit button was not showing up in Chat. 
Previously it was set to shown on the second to last message `transcript.length - index === 2` and only when speaker is "human",  but that did not factor in the fact the last message is handled separately, so transcript.length - index === 2 will always have the speaker as assistant instead of human, causing the edit button not showing up correctly.
Expected behavior:
- only the last user message can be edited
- you cannot edit a message that is a command, e.g. `/explain`
- 
Try to submit a message and then edit the message once Cody has replied.
https://github.com/sourcegraph/cody/assets/68532117/586a66cf-2ee8-4532-b …

fix: show edit button on last user message

---

lib/ui/src/Chat.module.css
lib/ui/src/Chat.tsx
vscode/CHANGELOG.md
vscode/webviews/Chat.module.css
vscode/webviews/Chat.tsx
vscode/webviews/Components/EnhancedContextToggler.module.css
vscode/webviews/Components/EnhancedContextToggler.tsx

Updated submit button and stop button to match the design in figma
The Submit button will become the Stop button
- Send a message
- Stop a message
- Enable and disiable enhance context
https://github.com/sourcegraph/cody/assets/68532117/e44d8469-124e-4f39-b6aa-4f9a0aa85678

refactor: update submit and stop buttons

---

agent/src/agent.ts
agent/src/bfg/BfgContextFetcher.test.ts
agent/src/cli/evaluate-autocomplete/evaluate-autocomplete.ts
agent/src/vscode-shim.ts
lib/shared/src/configuration.ts
vscode/src/completions/context/retrievers/bfg/bfg-retriever.ts
vscode/src/completions/providers/createProvider.test.ts
vscode/src/completions/providers/createProvider.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/jsonrpc/agent-protocol.ts
vscode/src/jsonrpc/jsonrpc.ts

Previously, we only supported evaluating one concrete fixture (set of
config options). For example, this meant that we could evaluate BFG
in isolation but we couldn't compare it against non-BFG. This PR fixes the problem by adding the notion of "fixuture", which is a set of configuration options.
Manually tested with the command
```
❯ pnpm agent evaluate-autocomplete --evaluation-config ~/dev/sourcegraph/bfg-evaluation/evaluation.json --test-count 400
```
Resulted in this chart, which is the first time we see an actual difference between BFG vs non-BFG.

Agent: add support for fixtures with `evaluate-autocomplete`

---

agent/src/agent.ts
agent/src/index.test.ts
agent/src/vscode-shim.ts
vscode/src/completions/context/retrievers/bfg/bfg-retriever.ts
vscode/src/jsonrpc/jsonrpc.ts
vscode/src/repository/repositoryHelpers.ts

Previously, the agent e2e tests were failing after the recent introduction of BFG support. This PR fixes the regressions so that the e2e tests are working against. To get the tests passing again, I had to update our JSON-RPC bindings to correctly handle error respones from the server, which required fixing how `recipes/execute` handles errors.
```
src login
cd agent
pnpm run test src/index.test.ts
```

Agent: get tests running again

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/ChatPanelProvider.ts

CLOSE https://github.com/sourcegraph/cody/issues/1827
Right now in the new chat UI, users cannot loop through their input history on UP arrow. This is because we are not sending the history back to the webview
Start Cody from this build, and then press the `UP` arrow on your keyboard to loop through your input history/
Input history is not showing up on UP arrow press
You can loop through input history on UP arrow

fix: chat history handling in ChatPanelProvider

---

.github/workflows/scip-typescript.yml
agent/src/agent.ts

The scip-typescript job was failing with this error
```
error This project's package.json defines "packageManager": "yarn@pnpm@8.6.7". However the current global version of Yarn is 1.22.21.
Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
```
Green scip-typescript CI job

Fix scip-typescript upload job

---

lib/shared/src/chat/prompts/vscode-context.ts
lib/ui/src/Chat.tsx
vscode/CHANGELOG.md
vscode/src/commands/CommandRunner.ts
vscode/src/commands/CommandsController.ts
vscode/src/editor/EditorCodeLenses.ts
vscode/webviews/ChatCommands.tsx

CLOSE: https://github.com/sourcegraph/cody/issues/1813
- Fixed issues described in https://github.com/sourcegraph/cody/issues/1813
- Fixed issue where errors from getting open tabs context would cause commands to be stuck
- Updated Editor Code Lenses to show up once only using `SET`
Follow the instruction in https://github.com/sourcegraph/cody/issues/1813 and try to reproduce it in this branch build.
https://github.com/sourcegraph/cody/assets/68532117/9f956ef0-5668-4a8c-8110-01829982eb95
https://github.com/sourcegraph/cody/assets/68532117/6b797c2d-86bb-46ad-88e8-dcff24d7231e

fix: select first command on slash

---

vscode/src/chat/chat-view/ChatManager.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/services/treeViewItems.ts
vscode/test/e2e/inline-assist.test.ts
vscode/test/e2e/task-controller.test.ts
vscode/webviews/App.tsx

CLOSE https://github.com/sourcegraph/cody/issues/1809
This PR  moves the command registration step to chat manager, and new condition to check if the current panel has been activated or not. If it's not activated, display a warning and ask users to wait for the current panel to be activated before opening a new one to prevent race condition described in the issue https://github.com/sourcegraph/cody/issues/1809
https://github.com/sourcegraph/cody/assets/68532117/1619b1de-bc5b-40e9-9598-66c708d53f5e
Try to reproduce the steps described in the original issue to confirm.
RE: https://github.com/sourcegraph/cody/issues/1757
I also cannot reproduce the issue mentioned in https://github.com/sourcegraph/cody/issues/1757 with this build
https://github.com/sourcegraph/cody/assets/68532117/cbb9d307-39 …

fix: race condition on new panel creation

---

vscode/src/tree-sitter/queries.ts
vscode/src/tree-sitter/queries/javascript.ts
vscode/src/tree-sitter/query-tests/test-data/intents.snap.ts
vscode/src/tree-sitter/query-tests/test-data/intents.ts

- JS completion intent queries are too broad because of the "any" matches used in queries: `(arguments (_) @argument)`. It leads to misleading completion intent analytics results. E.g., too many node type combos fall into the "argument" completion intent even though they are deeply nested inside the `arguments` node. This PR limits the `argument` completion intent query to a few popular node types. We can expand the list later based on the analytics data.
Example of the misleading match for the `argument` completion intent:
```ts
myFunction(() => {
const value = {
█
}
```
- Adds a query for the `pair.value` completion intent.
- Part of https://github.com/sourcegraph/cody/issues/1455
Updated snapshot tests.

Autocomplete: make javascript completion intent queries more precise

---

lib/shared/src/telemetry/EventLogger.ts

This is needed in some places in the new logger cc @bobheadxi 
Tested with telemetryLevel = 'agent' and it doesnt blow up :slightly_smiling_face:

Enable support for legacy event logger in non-vscode clients

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/providers/createProvider.ts
vscode/src/completions/providers/fireworks.ts

Follow up to sourcegraph/sourcegraph#58404
This PR moves the client logic of picking the right StarCoder model to the server.

Autocomplete: Move decision which StarCoder model to use to the server

---

lib/ui/src/Chat.module.css
vscode/webviews/Chat.module.css

CLOSE https://github.com/sourcegraph/cody/issues/1841
Address the following issues:
- The new send button isn't quite a circle
- And changes size as the text field changes size
https://github.com/sourcegraph/cody/assets/68532117/df667230-c44b-4afa-bfa7-caf2d0a88322

fix: chat submit button style

---

vscode/CHANGELOG.md
vscode/src/commands/menus/index.ts

CLOSE https://github.com/sourcegraph/cody/issues/1816
The `ignoreFocusOut` property for the Custom Commands menu is now set to true. This allows user to close the quick pick menu on focus out. 
https://github.com/sourcegraph/cody/assets/68532117/457aa1a9-ed9c-4b4d-8853-e47e1950683c

change: set ignoreFocusOut to false for custom commands

---

vscode/package.json

CLOSE https://github.com/sourcegraph/cody/issues/1812
Move the "cody.search" webview definition to appear after the "cody.commands" webview in the sidebar viewContainers array.
Search view should now show up under Commands for new users:

move cody.search webview position in sidebar

---

agent/src/cli/evaluate-autocomplete/AutocompleteDocument.ts
agent/src/cli/evaluate-autocomplete/SnapshotWriter.ts
agent/src/cli/evaluate-autocomplete/strategy-bfg.ts
agent/src/cli/evaluate-autocomplete/strategy-git-log.ts
agent/src/cli/evaluate-autocomplete/triggerAutocomplete.ts
vscode/src/completions/artificial-delay.ts

Previously, the `git-log` strategy did not run correctly due to a regression in the last change. This PR fixes that regression and adds two new columns to the generated CSV file:
- `EVENT`: for detailed information about each autocomplete response like latency. This is the JSON object we include in telemetry events.
- `REVISION`: to be able to know at which git commit the request was sent. This is mostly helpful to know if two requests for the same file/line location happened on the same file content.
Manually tested.

evaluate-autocomplete: fix git-log strategy and add more CSV columns

---

agent/src/cli/evaluate-autocomplete/AutocompleteDocument.ts
vscode/src/completions/get-inline-completions-tests/analytics.test.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/logger.test.ts
vscode/src/completions/logger.ts
vscode/src/jsonrpc/agent-protocol.ts

Closes #1820
Some improvements to how we type analytics events. `logCompletionEvent` is now an overloaded function with exact documentation for each event payload.
- No function changes just type changes
- `pnpm build`

Autocomplete: Better document analytics interfaces

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/main.ts

Adds and evaluates a mock feature flag for the Cody chat A/A test. This will help us construct metrics to evaluate chat performance and verify that results are consistent between both groups.
- Compiled and ran the extension
- Logged the feature flag with different users to verify it evaluated to different values (for a 50/50 rollout feature flag)

chat: mock feature flag

---

vscode/CHANGELOG.md
vscode/src/chat/protocol.ts

Follow up on https://github.com/sourcegraph/sourcegraph/pull/58451
Update the clients with the following changes:
- Upgrade the default Claude model used from the unpinned claude-2 to claude-2.0 
- Also add v2.1 as a non-default preview option 
Find the new models in drop down

feat: add Claude model 2.0 and 2.1

---

lib/ui/src/chat/components/EnhancedContext.tsx

As discussed with @toolmantim on slack ([thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1700631673836569?thread_ts=1700622656.385639&cid=C05AGQYD528)), the context display widget should also include local context except the ones added by the user manually via @ 
>  I was considering anything that wasn't explicitly @-included as "enhanced context"
Try running the `/test` command, which use local context only.
Used local context is not showing up in the enhance context widget
Used local context is included in the context widget

fix: display local context

---

vscode/CHANGELOG.md
vscode/src/completions/get-inline-completions-tests/triggers.test.ts
vscode/src/completions/get-inline-completions.ts
vscode/test/e2e/inline-completion.test.ts
vscode/test/e2e/install-deps.ts
vscode/test/fixtures/mock-server.ts

- Fix flaky inline completion test by making sure we do not trigger a follow up completion after the last action that may or may not be logged
- Clean up VS Code install noise when the file was already downloaded. Not helpful.
- Don't spam the console with logging noise when not on CI
- Prevent completions from showing up after a `;` (similar to `)` `]` `}`)
bliss!
- Run inline completion test a bunch of times and make sure it doesn't fail anymore
- No more noise in the console

Fix flaky completion test and clean up console

---

agent/package.json
agent/src/agent.ts
agent/src/cli/evaluate-autocomplete/EvaluationDocument.ts
agent/src/cli/evaluate-autocomplete/SnapshotWriter.ts
agent/src/cli/evaluate-autocomplete/Timer.ts
agent/src/cli/evaluate-autocomplete/evaluate-autocomplete.ts
agent/src/cli/evaluate-autocomplete/strategy-bfg.ts
agent/src/cli/evaluate-autocomplete/strategy-git-log.ts
agent/src/cli/evaluate-autocomplete/testTypecheck.ts
agent/src/cli/evaluate-autocomplete/triggerAutocomplete.ts
agent/src/cli/jsonrpc.ts
pnpm-lock.yaml

Previously, evaluate-autocomplete only supported testing whether an autocomplete result was an exact match with the original code or if it was an empty result. This PR adds an additional test to check whether the code typechecks.
Ran it manually.

evaluate-autocomplete: add support to run test commands

---

agent/src/agent.ts
vscode/src/services/LocalStorageProvider.ts
vscode/src/services/telemetry.ts

For clients that generate, persist and include this via ClientInfo.extensionConfiguration, we dont want to generate CodyInstalled events at every agent startup. For now, this means that JetBrains (the only non-vscode IDE that matters :clueless:) will continue to emit CodyInstalled events itself until we come up with a solution for agent to do so based on IDE-provided info.
Based on [the existing agent-side code](https://sourcegraph.com/github.com/sourcegraph/cody@nsc/agent-anonymoususerid/-/blob/vscode/src/services/telemetry.ts?L93%3A4-116%3A2), 
Confirmed based on whether CodyInstalled event is fired or not when a client provides anonymousUserID

Provide anonymousUserId via agent clients

---

agent/src/agent.ts
agent/src/bfg/BfgContextFetcher.test.ts
vscode/src/extension.common.ts
vscode/src/extension.node.ts
vscode/src/extension.web.ts

Discovered while debugging why commands executed in agent on initialization weren't being fired, there can be a race condition whereby the extension hasnt activated yet by the time we attempt to execute the commands due to activation of the extension being unawaitably async.
Confirmed by observing that [looking up commands to execute](https://sourcegraph.com/github.com/sourcegraph/cody@nsc/promise-extension-activation/-/blob/agent/src/vscode-shim.ts?L412) no longer fails

Allow awaiting extension activation instead of being unawaitably async

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/CHANGELOG.md
vscode/src/completions/artificial-delay.test.ts
vscode/src/completions/artificial-delay.ts
vscode/src/completions/inline-completion-item-provider.ts

Shipping this FF which was already at 100% rollout on dotcom for a while
- 👀

Autocomplete: Reduce frequency of low performance language

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/chat/protocol.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/createProvider.test.ts
vscode/src/completions/providers/createProvider.ts

Cyan is now the default Claude Instant mechanism so no need to have that specialised in the client code anymore. We can always bring it back if they deploy another experiment onto that codename.
👀

Remove Claude Instant Cyan

---

vscode/src/completions/text-processing/string-comparator.test.ts
vscode/src/completions/text-processing/string-comparator.ts

- While working on dynamic multiline completion, I extensively tested autocomplete manually and noticed that helpful completions were hidden in multiple cases. It happened because `isAlmostTheSameString` decided that the generated completion matches the string after it. This PR lowers the percentage defined in `isAlmostTheSameString` to fix the issue.
- The main reason for this functionality was the lack of fill-in-the-middle support by the existing models, so LLMs generated completion, duplicating the current code. That's not the case anymore, and we may not need this logic or can lower the percentage further.
- To repro, open `src/completions/request-manager.ts`, go to line 210, delete the implementation of the `get` method keeping `public ge`, and generate the completion at the end of …

Autocomplete: use a smaller percentage to detect the same string

---

vscode/CHANGELOG.md
vscode/package.json

REQUESTED AND CLOSE  https://github.com/sourcegraph/cody/issues/1821
Add a check for !editorReadonly in the 'when' condition for the editor title menu command to prevent the menu from showing when the editor is readonly or in non-file editors view.
Cody Icon should not show up in non-editable editor view:
Cody icon shows up in editor view for editable files:

change: show editor icon in non-ready only

---

lib/ui/src/Chat.tsx
vscode/CHANGELOG.md

CLOSE https://github.com/sourcegraph/cody/issues/1869
Previously, we blocked any keys with Cltr and Alt that's not on the key allow list.
This PR allows any keystrokes that have 'Backspace' and 'Delete' to pass through to use default behavior. 
After this change:
- Pressing "Delete" removes the character behind the cursor as mentioned in the issue https://github.com/sourcegraph/cody/issues/1869
- Pressing "Alt+Delete" removes the word behind the cursor
- Pressing "Ctrl+Delete" on Mac does nothing as that's the default behavior. You can test the default behavior in a slack chat box:
https://github.com/sourcegraph/cody/assets/68532117/5dc0b57d-cafb-48bc-9d7a-97fd9b962c5f
- in the chat box, move your cursor in the middle of a text string, then press "Delete" 
- Before: nothing happens
- …

fix: backspace and delete keys to remove character

---

vscode/CHANGELOG.md
vscode/src/chat/MessageProvider.ts

Spin off from https://github.com/sourcegraph/cody/pull/1856
Include chat prompt and response to `CodyVSCodeExtension:chatResponse` and `CodyVSCodeExtension:recipe` log events is users are connected to dotCom.
Check the Output channels to confirm the log events include prompt and LLM response IF you are connected to DotCom only.
You can see when the instance is switched to a non-DotCom instance, promptText and responseText are not included.
https://github.com/sourcegraph/cody/assets/68532117/516953f0-8f2f-4aa9-9421-cdbae7a3246c

add: include text in dotCom chat events

---

vscode/src/main.ts

closes https://github.com/sourcegraph/cody/issues/1815
Matches behaviour of other commands.
We can still support creating a document behind the scenes, but this fixes the immediate problem.
1. Open document
2. Try edit command from sidebar
3. Close document
4. Try edit command from sidebar

Edit: Show notification when no valid document

---

lib/shared/src/chat/prompts/display-text.test.ts
lib/shared/src/chat/prompts/display-text.ts
vscode/CHANGELOG.md
vscode/src/chat/chat-view/ChatManager.ts

CLOSE: https://github.com/sourcegraph/cody/issues/1819
This PR replace the vscode links with custom protocol for the file links in chat view.
- Replace the vscode file links with a custom "cody.chat.open.file" command protocol when displaying file names in chat. This allows handling file opening in a more customizable way without the error message described in the issue.
Run the /explain command, and then click on the link after the @ sign:
https://github.com/sourcegraph/cody/assets/68532117/fdf7cad2-5eb3-48c5-926a-88fb56b751b3

change: replace vscode links with command

---

lib/shared/src/chat/prompts/cody.json
lib/shared/src/chat/recipes/fixup.ts
lib/shared/src/editor/index.ts
vscode/CHANGELOG.md
vscode/src/code-actions/document.ts
vscode/src/code-actions/edit.ts
vscode/src/code-actions/fixup.ts
vscode/src/commands/CommandRunner.ts
vscode/src/editor/vscode-editor.ts
vscode/src/non-stop/FixupController.ts

closes https://github.com/sourcegraph/cody/issues/1464
This PR:
- Streamlines the `doc` intent flow for fixup tasks. Previously we would treat these as "edit", which means we would try to fetch lots of context from the selected code. That is very rarely helpful, for documenting we really just want to take the surrounding code and the current selection.
I also investigating going the other way, and fetching relevant reference code for a documentable symbol. This confirmed to me that it's not necessarily helpful. It can lead to the LLM documenting code based on how it is used elsewhere rather than how it should be used. That might help for "explaining" code but not for documenting. (Related PR: https://github.com/sourcegraph/cody/pull/1904)
1. Run doc command via right click menu
2. Run doc …

Edit: Faster `doc` workflow with more target context

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

^ Make sure we get the loading dots on the context as it loads
Tested locally

new chat panel: trigger progress indicator

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/chat/chat-view/ChatPanelProvider.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/chat/chat-view/SidebarChatProvider.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/protocol.ts
vscode/src/main.ts
vscode/src/services/AuthProvider.ts
vscode/webviews/App.tsx

CLOSE https://github.com/sourcegraph/cody/issues/1814
This PR added support for reviving the last opened chat panel (if any) on reload. 
- Build Cody from this branch
- Open a chat and ask Cody a question
- Reload your editor
- You should see the last opened chat opened in your editor before the reload
- Works with SimpleContext
Last panel that was not closed gets disposed before it gets recreated.
https://github.com/sourcegraph/cody/assets/68532117/9a1136df-9162-4eb3-8661-64aaab7a98c7
Loom: https://www.loom.com/share/1b7acfa69fff4b708bde8c9f3282bdb3?sid=f89aecb4-4caf-4525-bc56-63b34e5c9369
Last panel that was not closed gets revived properly.
https://github.com/sourcegraph/cody/assets/68532117/5aabc6f3-facd-406b-ba7a-0c4c2e89c1ff

feat: restore chat webview on reload

---

lib/shared/src/configuration.ts
vscode/CHANGELOG.md
vscode/package.json
vscode/src/chat/ContextProvider.ts
vscode/src/commands/menus/index.ts
vscode/src/commands/utils/menu.ts
vscode/src/completions/providers/createProvider.test.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/main.ts
vscode/src/services/StatusBar.ts
vscode/test/e2e/helpers.ts

CLOSE https://github.com/sourcegraph/cody/issues/1521
This PR includes the following changes:
Also update Chat Pre-Instructio on config change
Check if the features above are showing up with the correct label

change: custom commands to beta

---

vscode/src/graph/bfg/download-bfg.ts

This rolls Cody engine, including an improved tsx matcher. This does *not* include local embeddings because of a release build issue with that.
CI tests.

Roll cody-engine to v5.2.9998.

---

vscode/CHANGELOG.md
vscode/webviews/ChatCommands.module.css
vscode/webviews/ChatCommands.tsx

CLOSE https://github.com/sourcegraph/cody/issues/1943
Align the stylings for the chat command pop-up selection box with the one for @ command.

fix: aligns chat pop-up selection style

---

vscode/webviews/Chat.module.css
vscode/webviews/Chat.tsx

CLOSE https://github.com/sourcegraph/cody/issues/1974
Updated styles for send-button so that:
https://github.com/sourcegraph/cody/assets/68532117/cdeb7581-8527-4635-a432-bebe246837a8

fix: send-button resizes on click

---

agent/recordings/FullConfig_234680970/recording.har
agent/src/AgentTextDocument.test.ts
agent/src/AgentTextDocument.ts
agent/src/AgentWorkspaceDocuments.ts
agent/src/agent.ts
agent/src/bfg/BfgContextFetcher.test.ts
agent/src/cli/evaluate-autocomplete/EvaluationDocument.ts
agent/src/cli/evaluate-autocomplete/cli-parsers.ts
agent/src/cli/evaluate-autocomplete/evaluate-autocomplete.ts
agent/src/cli/evaluate-autocomplete/strategy-bfg.ts
agent/src/cli/evaluate-autocomplete/strategy-git-log.ts
agent/src/cli/evaluate-autocomplete/testTypecheck.ts
agent/src/cli/evaluate-autocomplete/triggerAutocomplete.ts
agent/src/cli/jsonrpc.ts
agent/src/editor.ts
agent/src/index.test.ts
agent/src/vscode-shim.ts
cli/src/commands/complete/command.ts
vscode/src/completions/context/retrievers/bfg/bfg-retriever.ts
vscode/src/jsonrpc/TextDocumentWithUri.ts
vscode/src/jsonrpc/agent-protocol.ts

Previously, the agent used a property named `filePath` as the unique string identifier of documents. This was problematic for several reasons, including
- There's no idiomatic way to encode virtual files
- File paths have different formatting in Windows and Linux/macOS
This PR does a big refactoring around the agent internals so that we use URIs instead of `filePath`. URIs solve both problems above.
The motivation to prioritize this change was that bfg wasn't loading correctly in the evaluation because of a bug related to handling of relative file paths. This bug was trivial to prevent after moving to URIs.
The diff includes a few minor `evaluate-autocomplete`-related changes that I included since I wanted to validate that bfg evaluation works correctly after the refactoring.
Green CI.

Agent: use `uri: vscode.Uri` instead of `filePath: string`

---

lib/shared/src/utils.test.ts
lib/shared/src/utils.ts

Previously, the tests always printed out a stack trace to stderr when running `src/utils.test.ts` even if the tests passed. I've been debugging CI failures lately and this error message has repeatedly been a red herring. This PR refactors the implementation so that we use a separate function for testing purposes that doesn't log to stderr.
Green CI.

Reduce noise in test logs

---

vscode/package.json

Closes #1979
Since we use a custom action that's different from the default "trigger inline suggestion" feature so we can detect that code branch, we should add it as a command as well. The only confusing thing now is that if you search for "trigger", you will see two commands (Both will work but the Cody specific one will be logged as a manual completion triggered via the action where as the other will log the same as hovering over an existing completion).
As a benefit, this documents the keyboard shortcut.

Autocomplete: Document manual completion trigger action

---

agent/src/bfg/BfgContextFetcher.test.ts
lib/shared/src/configuration.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/package.json
vscode/src/completions/can-use-partial-completion.ts
vscode/src/completions/context/context-mixer.test.ts
vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/completions/detect-multiline.ts
vscode/src/completions/get-current-doc-context.test.ts
vscode/src/completions/get-current-doc-context.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions-tests/last-candidate.test.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/logger.test.ts
vscode/src/completions/post-process-logger.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/fetch-and-process-completions.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/provider.ts
vscode/src/completions/providers/unstable-openai.ts
vscode/src/completions/request-manager.test.ts
vscode/src/completions/text-processing/parse-and-truncate-completion.ts
vscode/src/completions/text-processing/parse-completion.ts
vscode/src/completions/text-processing/process-inline-completions.ts
vscode/src/completions/text-processing/truncate-parsed-completion.ts
vscode/src/completions/text-processing/utils.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts

- **TLDR**: we now use the completion's first line to determine if it starts the new multiline syntax node. If it does, we continue streaming until the completion is truncated or we reach the token sample limit.
- Closes https://github.com/sourcegraph/cody/issues/1619
- Adds a **feature flag** `cody-autocomplete-dynamic-multline-completions` to run an experiment on the updated logic.
- Adds an **experimental setting**, `cody.autocomplete.experimental.dynamicMultilineCompletions` to test the feature locally.
- Adds `completionPostProcessLogger` used for local debugging. It's disabled by default, and I will replace it with OpenTelemetry spans in a follow-up PR. I put a little effort into improving this logger because it's a throw-away code, but I need it here because debugging …

Autocomplete: dynamically switch to multliline completions

---

agent/src/agent.ts
vscode/src/jsonrpc/agent-protocol.ts

We recently moved from `filePath` to `uri` in the agent while supporting old clients by automatically recovering the URI from `filePath`. This PR fixes a bug in that recovery logic that was causing autocomplete to not work.
Green CI

Agent: fix URI fallback for autocomplete requests

---

lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/tracing/index.ts
vscode/src/completions/client.ts

Let's not roll our own if we don't have to 😅 
- Add yourself to the `cody-autocomplete-tracing` feature flag
- Observe that a `traceparent` is appended to the request (I used console.log to validate since my proxyman isn't working anymore)

Autocomplete: Use OpenTelemtry traceparent logic

---

vscode/src/jsonrpc/TextDocumentWithUri.ts

Unbreaks Jetbrains plugin autocomplete with manual testing

Fix TextDocumentWithUri when uri is not set

---

vscode/package.json

CLOSE: https://github.com/sourcegraph/cody/issues/1978
renamed chat panel command title from "Start a New Chat Panel" to "New Chat"

change: rename chat panel command title

---

agent/src/bfg/BfgRetriever.test.ts
vscode/src/completions/context/context-mixer.test.ts
vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/completions/detect-multiline.ts
vscode/src/completions/get-current-doc-context.test.ts
vscode/src/completions/get-current-doc-context.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions-tests/last-candidate.test.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/logger.test.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/fetch-and-process-completions.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/provider.ts
vscode/src/completions/providers/unstable-openai.ts
vscode/src/completions/request-manager.test.ts

- Enables generation of the multiline completions inside brackets when the cursor is on the new empty line inside them. This change is behind the `dynamicMultilineCompletions` feature flag.
- With the improved context, this change should lead to more correct completions from the type system POV.
- Improved units around detecting the multiline trigger with and without the `dynamicMultilineCompletions` feature flag.
- Builds on top of #1894 
- Closes https://github.com/sourcegraph/cody/issues/1999
```ts
generateContext(
█
)
const oddNumbers = [
█
]
```
- Added new unit tests.
- Test it locally by setting `cody.autocomplete.experimental.dynamicMultilineCompletions` to true and generating completions similar to examples on screenshots.

Autocomplete: extended multiline triggers inside brackets

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/main.ts

This changes the current icon from `reload` (which is too close to a browser reload) to `clear-all` (which isn't perfect but looks more destructive). It also adds a confirmation dialog:
| - | - |
| <img width="372" alt="Screenshot 2023-11-30 at 4 09 59 pm" src="https://github.com/sourcegraph/cody/assets/153/8a704d00-ed72-4557-aa62-7e2bf85175c6"> | <img width="372" alt="Screenshot 2023-11-30 at 4 10 24 pm" src="https://github.com/sourcegraph/cody/assets/153/e1795346-f551-4657-aede-adf879bd202c"> |
| Confirmation |
| - |
| <img width="1238" alt="Screenshot 2023-11-30 at 4 03 17 pm" src="https://github.com/sourcegraph/cody/assets/153/7a97ad51-84ce-428f-8974-b63f484c5a57"> |
- Viewed the button
- Clicked the button, verify prompt cancel does nothing
- Clicked the button, …

Change "Restart Chat Session" icon and add a confirmation

---

vscode/package.json

Noticed by @toolmantim that it wasn't showing.
It is because the text focus moves to the command palette.
We show an error when no file is open so this should be fine to always show when activated
1. Open command palette
2. Check the command shows

Edit: Fix edit command palette

---

.github/workflows/ci.yml
lib/shared/src/common/markdown/markdown.test.ts

I've had three PRs today get a test failure for Node.js v16 in this file that got fixed by re-running the job. This problem has existed for a while, see https://sourcegraph.slack.com/archives/C05AGQYD528/p1700090891393639
Green CI without flaky failure.

Disable flaky markdown test in Node.js v16

---

vscode/CHANGELOG.md
vscode/src/non-stop/tracked-range.test.ts
vscode/src/non-stop/tracked-range.ts

We want to allow affixing non-whitespace characters and including that in the edit selection range (e.g. `export` before a function, or a JSDoc above an identifier).
We do not want to affix whitespace characters, as this may be from the user moving their cursor onto a different line, or repositioning the code.
https://github.com/sourcegraph/cody/assets/9516420/aab05bc5-4c19-4a93-ac41-53de10b3dc60
https://github.com/sourcegraph/cody/assets/9516420/2db9a97f-85d0-41a2-b905-e151938135ce
1. Create fixup
2. Move cursor to start of range
3. Enter non-whitespace characters and see range expands
1. Create fixup
2. Move cursor to start of range
3. Enter whitespace characters and see range does not expand

Edit: Only affix non-whitespace changes to ranges

---

vscode/src/non-stop/FixupController.ts
vscode/test/e2e/task-controller.test.ts

closes https://github.com/sourcegraph/cody/issues/1949
Renames the diff view title
Reflects how we brand "Edit" and doesn't confuse user
1. Create an edit
2. Click the diff button

Edit: Rename diff view from Fixup to Edit

---

lib/shared/src/codebase-context/context-status.ts
lib/shared/src/codebase-context/index.ts
vscode/src/chat/ContextProvider.ts
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/external-services.ts
vscode/src/jsonrpc/embeddings-protocol.ts
vscode/src/local-context/local-embeddings.ts
vscode/src/main.ts

The initial download for local embeddings can be arbitrarily slow, so we should avoid it until we are likely no need it and not block user interaction on it.
This ameliorates the startup cost of local embeddings in these ways:
- Cache the access token and don't start cody-engine, *just* to provide it a token.
- Cache the endpoint and don't start cody-engine for non-dotcom. (Should investigate adding it back for integration tests, though.)
- Add a hint from SimpleChatPanelProvider, to local embeddings, to start up when a chat panel provider is created. But do not block on that.
- When polled for local embeddings, respond that they're unavailable unless cody-engine has started.
 
1. Set the following configuration:
```
"cody.debug.enable": true,
"cody.debug.verbose": true, …
```

VScode: Start up local embeddings less often

---

vscode/src/graph/bfg/download-bfg.ts

This PR includes a fix related to how we handle concurrent requests to indexing a repo. It should handle this more gracefully now.
Green CI.

BFG: bump to latest version

---

agent/src/agent.ts
agent/src/bfg/BfgRetriever.test.ts
vscode/src/completions/context/retrievers/bfg/bfg-retriever.ts

Previously, our BFG integration had a chance of failing in certain cases. Specifically, I was seeing errors when we sent concurrent `bfg/revision/didChange` requests. This PR adds a try/catch to that block along with a few other defensive changes to make BFG more resilient overall.
Manually tested by running the evaluation suite with parallel `revision/didChange` results and confirmed that it recovers.

BFG: increase resilience

---

vscode/src/chat/chat-view/ChatManager.ts
vscode/src/chat/chat-view/ChatPanelProvider.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/chat/chat-view/SimpleChatModel.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

CONTEXT: https://sourcegraph.slack.com/archives/C05AGQYD528/p1701316056167949
- Revived simple chat panel when extension is reactivated by registering existing webviewPanel and setting chatID. 
- Added error handling in revive method to dispose panel and log debug message on failure.
- Updated related methods to handle null chatPanelsManager.
1. Enable SimpleChatPanel
2. Ask Cody a question and keep the new chat panel opened
3. Reload VS Code
4. You should see the chat has been restored
5. Check Output Channel to confirm the view is created by SimpleChatPanel 
https://github.com/sourcegraph/cody/assets/68532117/24a9ac6f-988d-437e-8879-27a43be55d36

fix: revive simple chat panel

---

vscode/src/chat/ContextProvider.ts
vscode/src/chat/MessageProvider.ts
vscode/src/chat/chat-view/ChatPanelProvider.ts
vscode/src/main.ts

Fixes #2027 
1. Set the following VScode settings:
```
"cody.debug.enable": true,
"cody.debug.verbose": true,
"cody.experimental.chatPanel": true,
```
Note `"cody.experimental.simpleChatContext"` is *not* present/enabled.
2. Open a repository which should have remote embeddings, for example sourcegraph/sourcegraph. Start a chat. Open the enhanced context selector. "Embeddings ... Inherited from github.com/sourcegraph/sourcegraph" should appear.
3. Open a repository which was indexed by App, that is *not* indexed on dotcom. Start a chat. Open the enhanced context selector. After a delay to download and start cody-engine, "Embeddings" should appear with a checkmark.
4. Open a repository that is not indexed by App or dotcom. Start a chat. Open the enhanced context selector. You should get a …

VScode: Enhanced context selector updates in new "not simplified" panel chats

---

vscode/CHANGELOG.md

This cleans up the changelog language around versions, removing the mention of odd version numbers that aren't actually included in this document, and instead mentioning that it's the `[Unreleased]` features that may be included.
This will also help when we link directly to the changelog in #2025
- None required

Clarify pre-release builds in changelog

---

vscode/package.json
vscode/scripts/release.ts
vscode/src/configuration.ts

- Removes experimental settings from the `package.json` file before stable releases.
- [Slack thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1701398005070439)
Tested it locally using a dry-run release.

VS Code: hide experimental settings for stable releases

---

pnpm-lock.yaml
vscode/package.json
vscode/src/chat/ContextProvider.ts
vscode/src/local-context/local-embeddings.ts
vscode/webviews/Components/EnhancedContextSettings.story.tsx
vscode/webviews/Components/EnhancedContextSettings.tsx
vscode/webviews/Popups/Popup.module.css
vscode/webviews/storybook/VSCodeStoryDecorator.module.css

- Load local embedding indexes once indexing completes. Fixes #1972.
- Cleans up some UI cruft:
- 'Enabled' events do not spam if there is no change.
- Click events on the enhanced context status button don't bubble to the popup.
- The pointy bit of the pop-up sits on top of the border around the enhanced context status button.
- Storybook:
- You can interact with and edit an Enhanced Context Status tile.
- The Enhanced Context Status button has the indicator color when enabled.
Manual test:
0. Enable new chat UI.
1. Open a repository not indexed on dotcom or by App. Open a file from the workspace (to work around #2032)
2. Start a chat. Open the Enhanced Context Settings widget.
3. After cody-engine starts and the Enable Embeddings button appears, click on it. The tile should change to …

Embeddings: Display indexing status in Enhanced Context Selector, query new index when done

---

agent/src/AgentTextDocument.ts
agent/src/AgentWorkspaceDocuments.ts
agent/src/agent.ts
agent/src/bfg/BfgRetriever.test.ts
agent/src/editor.ts
vscode/src/completions/persistence-tracker.ts

Extracted from https://github.com/sourcegraph/cody/pull/2017/commits/64406749bebf2f79d53bf6d9f2140c93119cd80e, this brings the AgentTextDocument more in-line with vscode TextDocument references. This addresses a dangerous issue where multiple instances of an AgentTextDocument can exist for a given uri with a different view of the actual document (primarily, different text contents), resulting in operations happening on stale data.
Tested as part of https://github.com/sourcegraph/cody/pull/2017 through autocomplete (with specific emphasis on the state of data when computing persistence events)

Agent: single instances of AgentTextDocument per uri

---

vscode/CHANGELOG.md
vscode/package.json

Reverting back to v0.16.1, due to critical issue found in v0.16.2. 
Release will be built off of branch `kalan/vscode-0.16.3` which was branched from git tag `vscode-v0.16.1`
Thread for more context:
https://sourcegraph.slack.com/archives/C05AGQYD528/p1701464754444749
Ensure the diff has only version bump and changelog updates.

VS Code: Cody release v0.16.3

---

vscode/test/e2e/chat.test.ts
vscode/test/e2e/common.ts
vscode/test/e2e/history-new-ui.test.ts
vscode/test/fixtures/mock-server.ts

This fixes two flakes in recent tests I added:
1. VS Code toast notifications obscuring the chatbox so the test could not click them.
The failure looked like:
```
retrying click action, attempt #2
waiting 20ms
waiting for element to be visible, enabled and stable
element is visible, enabled and stable
scrolling into view if needed
done scrolling
<div title="Git (Extension)" class="notification-list…>Source: Git (Extension)</div> from <div class="notifications-toasts visible">…</div> subtree intercepts pointer events
```
This was fixed by turning on Do Not Disturb mode (something already done in another test, so I extracted a function and reused it).
2. Triggering rate limits in the second test sometimes not working.
This one was confusing. It appears that in e2e tests we stop the server, …

Fix flaky e2e chat tests

---

vscode/test/e2e/chat.test.ts
vscode/test/fixtures/mock-server.ts

Adds an extra test for the rate limit for a non-dotcom instance (where the `x-is-cody-pro-user` header will not be set and upgrade options should not be shown).
- New automated test, run with `pnpm test:e2e`

Add a test for non-dotCom chat rate limit

---

lib/shared/src/experimentation/FeatureFlagProvider.ts

Only fixing a typo. The FF is not used yet.

Autocomplete: Fix dynamic multiline feature flag typo

---

vscode/package.json
vscode/src/completions/providers/fireworks.ts

This code was never used besides some experiments and we no longer host the model to support it, leading to a bunch of errors when enabled.
Can no longer enable wizardcoder in the experimental model selection

Autocomplete: Remove Wizardcoder support

---

vscode/webviews/Components/ChatModelDropdownMenu.tsx

feat: add telemetry for LLM selection and CTA clicks
Track events when users click on the Cody Pro upgrade CTA and when they select an AI model from the dropdown.
https://github.com/sourcegraph/cody/assets/68532117/976a5981-db66-4697-b115-e46859ba7643

add telemetry for LLM selection and CTA clicks

---

lib/shared/src/sourcegraph-api/completions/nodeClient.ts
lib/ui/src/chat/ErrorItem.tsx
lib/ui/src/chat/TranscriptItem.tsx
vscode/src/completions/client.ts
vscode/test/e2e/chat.test.ts
vscode/test/fixtures/mock-server.ts

add: log Cody chat rate limit related events
Log  Cody chat rate limit events
Added `CodyVSCodeExtension:upsellUsageLimitCTA:shown` and `CodyVSCodeExtension:upsellUsageLimitCTA:clicked` to chat_commands
https://github.com/sourcegraph/cody/assets/68532117/287966cf-5ae8-422f-b1bd-9194db51fd18

log chat rate limit events

---

vscode/CHANGELOG.md
vscode/src/chat/MessageProvider.ts
vscode/src/chat/chat-view/ChatHistoryManager.ts
vscode/src/chat/chat-view/ChatPanelProvider.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/chat/chat-view/SidebarChatProvider.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/services/LocalStorageProvider.ts
vscode/src/services/treeViewItems.ts
vscode/test/e2e/history-new-ui.test.ts
vscode/test/integration/commands.test.ts

CLOSE https://github.com/sourcegraph/cody/issues/1968
This PR focused on simplify chat history handling by moving the old chat history handling in MessageProvider to the new Chat History Manager.
Removed redundant chat history code and use shared chatHistory module instead. This simplifies the MessageProvider by removing duplicated chat history logic.
This also fixes issue described in the attached issue as previously, we would save chat history as group instead of individual chat, so a new group can overwritten the old one, unable to keep history across panels in sync.
Follow instructions in attached issue

fix: migrate to chat history manager

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

CLOSE https://github.com/sourcegraph/cody/issues/2093
fix: open file with range in SimpleChatPanelProvider
Added the missing range parameter to the openFile command handler in SimpleChatPanelProvider and pass it to the openFilePath function. This allows opening a file to a specific range.
Try clicking on the context with range to see if the file opens at the correct range.
https://github.com/sourcegraph/cody/assets/68532117/e6ce69e7-29a1-422c-8d03-870407e33c12

fix: open file with range in simple chat

---

vscode/CHANGELOG.md
vscode/webviews/Components/EnhancedContextSettings.tsx

To help people discover Enhanced Context, this adds an onboarding glowy dot until the user has opened it for the first time. After it's been opened the first time it is never shown again.
https://github.com/sourcegraph/cody/assets/153/ff255c92-8f74-45a3-8942-715c922349b1
Fixes #2083
- Open chat
- See glowy dot
- Open enhanced context
- See glowy dot disappear
- Reload window
- See glowy dot not visible

Chat: Show onboarding glowy dot guide until first time opening Enhanced Context

---

vscode/webviews/Components/EnhancedContextSettings.tsx

Prevents long paths from expanding the width of the popover.
- Developer tool inspected edit the folder name in Enhanced Context
- Checked it wrapped and didn't force the size of the popover to increase

Chat: Line break folder names in Enhanced Context popover

---

lib/ui/src/Chat.tsx
vscode/CHANGELOG.md
vscode/webviews/Chat.tsx
vscode/webviews/Components/EnhancedContextSettings.story.tsx
vscode/webviews/Components/EnhancedContextSettings.tsx
vscode/webviews/storybook/VSCodeStoryDecorator.module.css

Updates the Enhanced Context popover so it closes when the chat message input is focused, removing an extra click.
Before:
https://github.com/sourcegraph/cody/assets/153/9e06b6da-3f6c-4ab7-b495-ac92fad9c4eb 
After:
https://github.com/sourcegraph/cody/assets/153/46b6a469-cb44-4e51-b7f5-912622fa2a2c
- Start a new chat
- Click the enhanced context button
- Click the text input
- Click the enhanced context button again
- Click close button

Chat: Close the Enhanced Context popover on chat input focus

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/ChatPanelProvider.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts

CLOSE https://github.com/sourcegraph/cody/issues/1969
Reuse the empty New Chat panel when there is one available to prevent having multiple new chats open at once 
Click on the New Chat button when there is a "New Chat" available should reveal the existing one instead of creating a new one:
https://github.com/sourcegraph/cody/assets/68532117/95f7ee4a-a848-479d-923b-87f88dd54963

change: reuse empty "New Chat" panel

---

vscode/src/chat/chat-view/SimpleChatModel.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

https://github.com/sourcegraph/cody/assets/1646931/757f0780-946f-4eac-93ff-9761caeece26
* Abort now works in the simplified chat panel
* Fixes a possible race condition where an error in local embeddings search seems sometimes to result in empty context, even if remote embedding search yields results
Note: the context fetching step (prior to response generation) cannot yet be aborted.

Make abort work in the simplified chat panel

---

vscode/package.json
vscode/src/services/treeViewItems.ts

Replaced `usage` and `upgrade` commands with the proper registered command `show-page`
Before:
https://github.com/sourcegraph/cody/assets/51868853/8134b68e-229b-4fc0-bf06-c05765938c9c
After:
https://github.com/sourcegraph/cody/assets/51868853/44590675-759c-4bae-8eda-7dd796fe0a23
N/A

plg: fix incorrect commands for admin buttons

---

vscode/CHANGELOG.md
vscode/package.json

* Removes the old "Ask Cody" wording
* Adds Cody’s built-in commands to the VS Code command palette (which users have tried to search in with user testing)
* Cleans up the context menu
| - | - |
| <img width="609" alt="Screenshot 2023-12-05 at 8 08 13 pm" src="https://github.com/sourcegraph/cody/assets/153/6eb338ab-8cf1-4286-a891-4398b84e08c6"> | <img width="591" alt="Screenshot 2023-12-05 at 8 07 43 pm" src="https://github.com/sourcegraph/cody/assets/153/e4447ea4-efed-4be2-8504-3ef044ae1de4"> |
| <img width="629" alt="Screenshot 2023-12-05 at 8 12 50 pm" src="https://github.com/sourcegraph/cody/assets/153/c611beaf-52ae-4609-9e34-394c320354a1"> | <img width="659" alt="Screenshot 2023-12-05 at 8 12 19 pm" src="https://github.com/sourcegraph/cody/assets/153/9c10343d-ce50-4 …

Commands: Expose commands in the VS Code command palette and clean up the context menu

---

vscode/src/graph/bfg/download-bfg.ts

Previously, we tried to download a non-existent windows-arm64 binary,
which resulted in a 404 error for end users. This PR fixes the problem
by using the windows-x84 binary instead. This works because Windows
Arm PCs support x86 emulation https://learn.microsoft.com/en-us/windows/arm/apps-on-arm-x86-emulation
Fixes https://github.com/sourcegraph/cody/issues/2022
Test it on Windows using Parallels Desktop on Apple Silicon.

Replace windows-arm64 with windows-x84 binary

---

agent/package.json
lib/shared/package.json
lib/shared/src/sourcegraph-api/telemetry/GraphQLTelemetryExporter.test.ts
lib/shared/src/sourcegraph-api/telemetry/GraphQLTelemetryExporter.ts
pnpm-lock.yaml
vscode/package.json
vscode/src/completions/logger.test.ts
vscode/src/completions/logger.ts

As of 5.2.4, V2 telemetry has a notion of "interaction ID" as a first-class citizen to align series of events and to provide an explicit string-value field for propagating a UUID-style interaction ID. See https://github.com/sourcegraph/telemetry/pull/4, https://github.com/sourcegraph/sourcegraph/pull/58539, https://github.com/sourcegraph/sourcegraph/pull/58016 and https://docs.sourcegraph.com/dev/background-information/telemetry/protocol#telemetrygateway-v1-EventInteraction
This change adds support for it in Cody, and makes sure the mechanism is compatible pre-5.2.4 instances. It also extracts `id` from `params` in completion events into the first-class field.
Unit tests

telemetry: add v2 interactionID support

---

vscode/test/e2e/common.ts

The notification toggle logic was inverted, so notifications were being enabled when they should have been disabled. This fixes the logic to disable notifications when intended.
all e2e tests should be passing

fix: invert notification toggle logic

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/ChatManager.ts

Follow up to #2115, this ensures we trigger chat panel creation and restoration straight away (on the leading edge of the timeout), and reduces the restoration timeout to match.
- Open new chat
- Open existing chat
- Reload window and ensure restores correct

Chat: Speed up chat panel debounce w/ trigger on leading edge too

---

lib/ui/src/Chat.module.css
vscode/CHANGELOG.md
vscode/webviews/Chat.module.css

This fixes the message input overlapping the enhanced context button, and cleans up the send button to be consistent with VS Code styles.
Before:
https://github.com/sourcegraph/cody/assets/153/b1781cf9-b27a-4529-90af-e420a29f1a91
After:
https://github.com/sourcegraph/cody/assets/153/fdeb6f79-b424-4a25-a31a-83bbff1555f1
- Opened chat
- Typed in message input
- Hovered and clicked send button

Chat: Fix message input overlapping with enhanced context button

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/local-context/download-symf.ts
vscode/src/search/SearchViewProvider.ts
vscode/webviews/SearchPanel.module.css
vscode/webviews/SearchPanel.tsx

A raft of small cleanups to the search UX:
- Fix search input size to match VS Code
- Make whole rows clickable
- Fix pointer and text selection on rows
- Add high contrast hover border
- Add blank words as well as "No results"
- Improve notification copy
- Fix file icon vertical alignment
- Fix truncation of long paths
https://github.com/sourcegraph/cody/assets/153/89ef33ee-ff5f-4c0e-8466-4cb38667d265
- Ran a search
- Matched no results
- Matched some results
- Clicked rows
- Hovered over truncated results

Search: Style and UX improvements to the search panel

---

vscode/CHANGELOG.md
vscode/package.json
vscode/test/e2e/common.ts
vscode/test/e2e/custom-command.test.ts
vscode/test/e2e/history-new-ui.test.ts

Tighten up the blank chat copy to make room for the search panel.
| - | - |
| <img width="314" alt="Screenshot 2023-12-06 at 5 53 11 pm" src="https://github.com/sourcegraph/cody/assets/153/29746ee1-fb46-4279-a8fa-2734d0579af3"> | <img width="293" alt="Screenshot 2023-12-06 at 5 54 26 pm" src="https://github.com/sourcegraph/cody/assets/153/20a574e8-143e-4955-983f-3bbad0158ea6"> |
- Deleted all chats
- Viewed new chat copy

Chat: Reduce size of chats list blank copy

---

vscode/CHANGELOG.md
vscode/webviews/Chat.tsx

Now commands are staying in for release, time to update the input placeholder:
| - | - |
| <img width="436" alt="Screenshot 2023-12-06 at 8 23 21 pm" src="https://github.com/sourcegraph/cody/assets/153/90386905-c3bd-4bdc-886e-713743441775"> | <img width="436" alt="Screenshot 2023-12-06 at 8 22 02 pm" src="https://github.com/sourcegraph/cody/assets/153/08f036db-00c1-4121-bf9c-47400c27e77e"> |
- Opened a chat
- Inspected placeholder

Chat: Update message input placeholder to mention slash commands

---

lib/shared/src/codebase-context/index.ts
vscode/src/chat/CachedRemoteEmbeddingsClient.ts
vscode/src/chat/ContextProvider.ts
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/chat-helpers.ts
vscode/src/main.ts

Fixes https://github.com/sourcegraph/cody/issues/2107
Previously, `SimpleChatPanelProvider` accepted an instance of `EmbeddingsSearch`, which was extracted from the `CodebaseContext` instance created on startup.
* `EmbeddingsSearch` instances are tied to a specific codebase.
* When the current codebase changes (e.g., file in a separate repo was opened or a new repo was added to the workspace), this approach does not update the `EmbeddingsSearch` instance held by `SimpleChatPanelProvider`.
* As a result, the remote embeddings context was fetched from the old codebase
This patch modifies `SimpleChatPanelProvider` to switch out `EmbeddingsSearch` for `CachedRemoteEmbeddingsClient`, which wraps a `SourcegraphGraphQLAPIClient` instance.
* The current codebase is now provided (to …

Chat: update embeddings and codebase identifiers

---

vscode/CHANGELOG.md
vscode/package.json

Preparing a PR for the 0.18 release later today.
I've copy-pasted the 0.16.2 change log entries for completeness (as we're re-landing those changes).
Let me know when I can ship 🚢 
Just a changelog/readme change

VS Code: Release 0.18.0

---

.github/workflows/ci.yml

Follow on from #2127, #2146 and #2147, this increases the macOS runner size which takes the macOS tests from 6m to 4m.
I've broken this out into its own single change, because it requires us update our required checks.
- N/A

chore: Bump up macOS e2e runner instance size

---

lib/shared/src/chat/transcript/index.ts
lib/shared/src/chat/transcript/messages.ts
lib/ui/src/chat/ErrorItem.tsx
vscode/src/chat/chat-view/SimpleChatModel.ts

We were dropping error messages from Cody chat, because Error objects omit all fields when serialized.
Before/after:
Tested locally (see screenshots) by posting an error to the view in `sendLLMRequest`.

ensure error message makes it through to chat view

---

lib/ui/src/Chat.tsx
vscode/src/chat/chat-view/ChatHistoryManager.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/chat/chat-view/SimpleChatModel.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

CLOSE https://github.com/sourcegraph/cody/issues/2148 https://github.com/sourcegraph/cody/issues/2150 https://github.com/sourcegraph/cody/issues/2170 https://github.com/sourcegraph/cody/issues/2169
Fix issues where:
- chats don't appear until stream ends (simplified chat) #2148
-  active chats block new chats being started (simplified chat) #2150
- getReadmeContext is slow
Changse included:
- saveSession after human submission instead of only saving chat after assistant has responded
- combine saveAndPostHistory and saveSession
- limit getReadmeContext to 1 file at root of repo using global pattern
- ask Cody a question
- before Cody has responded, the tree view has already been updated with the new session added
- you can start a new chat panel while waiting for Cody to response
- you …

fix: chat show up in tree view on submit

---

vscode/src/graph/bfg/download-bfg.ts
vscode/src/jsonrpc/embeddings-protocol.ts
vscode/src/local-context/local-embeddings.ts

Rolls cody-engine to v5.2.11713.
cody-engine used to enumerate indices on startup, which slows down engine startup for autocompletes. Instead, enumerate indexes in an `embeddings/initialize` method.
- Set `"cody.debug.enable": true, "cody.debug.verbose": true,`
- Open a repository with App embeddings and chat, check that local embeddings context appears
- Open a repository with local embeddings and chat, check that local embeddings context appears
- Open a repository with no embeddings and click Enable Embeddings and check that indexing happens and then queries work
You can verify when local embeddings is returning results with Cmd-Shift-P, Output: Show Output Channels... Cody by Sourcegraph and looking for messages like `LocalEmbeddingsController: returning 15 results`.

VSCode: Send `embeddings/initialize` to the local embeddings controller

---

vscode/CHANGELOG.md
vscode/src/editor/vscode-editor.ts

Fixes #2184. `Uri.parse` parses URIs, `Uri.file` takes a file path and turns it into a URI. For UNIX-style paths, `Uri.parse` works fine, but for Windows file paths, parsing them as URIs is wrong; the the drive separator is URL-encoded and the URI is unusable, etc.
https://github.com/sourcegraph/cody/assets/55120/417332a4-9c10-4728-a2de-b24bfb8d4fb3
1. Open a workspace, start a chat
2. @-mention a file in the workspace
3. The file should be included in the chat context, Cody can see the content, etc.

VSCode: Do not parse Windows file paths as URIs

---

.vscode/settings.json
vscode/package.json
vscode/src/chat/FixupViewProvider.ts
vscode/src/main.ts
vscode/src/non-stop/FixupController.ts
vscode/src/non-stop/FixupTask.ts
vscode/src/non-stop/codelenses.ts

This adds an update CTA to code edits.
Fixes #2123
Free user rate limit:
https://github.com/sourcegraph/cody/assets/153/31a1650a-fe9b-4567-90ee-4c4fb3ff5ef2
Pro user rate limit:
https://github.com/sourcegraph/cody/assets/153/304cb79d-1eb0-4aab-9cd8-89def9abf6ff
- Ran as free rate limited user. Run doc command. Click code lens. Click dialog options.
- Ran as pro rate limited user. Run doc command. Click code lens. Click dialog options.

Add rate limit upgrade for code edits

---

vscode/CHANGELOG.md
vscode/src/editor/utils/editor-context.ts
vscode/test/e2e/at-file-context-selecting.test.ts
vscode/test/fixtures/workspace/.mydotfile
vscode/webviews/App.tsx

This should fix https://github.com/sourcegraph/cody/issues/2199, although I'm not certain if the behaviour is exactly correct, because:
1. Dot files appear to have been excluded specifically (@toolmantim you added `fileExcludesPattern` in `editor-context` so maybe have an opinion?)
2. Typing `@.` although showing dotfiles at the top, will also basically match every file because of the fuzzy patch
I also hit an issue (filed at https://github.com/sourcegraph/cody/issues/2208) while testing this.. The existing tests can fail depending on the full fs path to your Cody checkout. I think this is a bug but I'd like some confirmation before trying to fix.
- Run `pnpm test:unit` for the updated test
- Open chat, and type `@.` and verify dotfiles show up and can be selected (note: ignore rules …

Allow dotfiles to be included in context files list

---

lib/ui/src/Chat.tsx
vscode/CHANGELOG.md
vscode/test/e2e/at-file-context-selecting.test.ts

This code was using `input.lastIndexOf(fileDisplayText)` to find the location of the text to compute the suffix, but it didn't take into account the length, so any time input contained fileDisplayText, the contents of fileDisplayText would become duplicated.
(@abeatrix the original code was added as part of a fix for https://github.com/sourcegraph/cody/issues/1973 - in my testing that still seems to work correctly with my change, but let me know if I've misunderstood).
Fixes https://github.com/sourcegraph/cody/issues/2200
- Run `pnpm test:unit at-file` or
- Open the chat window
- Type "@" followed by a **complete** filename including the very last character
- Press `<tab>` to accept the file
- Ensure the chat input does not contain the filename duplicated

Don't duplicate @-filenames when pressing tab if the whole string has been typed

---

vscode/src/local-context/symf.ts
vscode/src/main.ts
vscode/src/search/SearchViewProvider.ts

Fixes https://github.com/sourcegraph/cody/issues/1876

symf: support cancelling index

---

vscode/src/local-context/symf.ts

We can't use an absolute path containing a colon as a sub-path, so just remove the colon.
@beyang @jdorfman I tested this manually, but couldn't find a nice way to get a test around this (I tried writing a test that tried to create an index and verify it existed, but it seemed to want to trigger downloads). If there's a reasonable way I could get a test around this, please let me know.
- Run extension on Windows
- Open a project
- Type a query into the search box
- Ensure results appear and no errors in the console

Fix symf index dir on Windows

---

agent/src/agent.ts
vscode/src/jsonrpc/agent-protocol.ts

It helps [PLG: Add "Upgrade to Cody Pro" and "Current Usage" settings buttons#149](https://github.com/sourcegraph/jetbrains/issues/149). In JetBrains plugin we need to be able to evaluate feature flags.
* Send request to agent's new `featureFlags/getFeatureFlag` endpoint

Adding endpoint for fetching feature flag

---

vscode/CHANGELOG.md
vscode/scripts/release.ts
vscode/src/services/treeViewItems.ts
vscode/src/version.test.ts
vscode/src/version.ts
vscode/webviews/App.tsx
vscode/webviews/Notices/VersionUpdatedNotice.tsx
vscode/webviews/Notices/index.tsx

Fixes #2025
* Links to changelog for pre-release builds
* Label pre-release builds with "Pre-Release Notes" instead of "Release Notes"
* Removes some dupe version/URL code
| - | - |
| <img width="379" alt="Screenshot 2023-12-08 at 11 37 50 pm" src="https://github.com/sourcegraph/cody/assets/153/a085ba2b-d63a-4695-b42b-28bb4534eedb"> | <img width="379" alt="Screenshot 2023-12-08 at 11 36 35 pm" src="https://github.com/sourcegraph/cody/assets/153/2375a2e0-355c-4485-a27f-1f8d8aba1318"> |
| Links to [Non-Existent Release](https://github.com/sourcegraph/cody/releases/tag/vscode-v0.19.1689391131) | Links to [Changelog](https://github.com/sourcegraph/cody/blob/main/vscode/CHANGELOG.md) |
- Changed package.json `version`
- Reloaded extension, verified treeitem, clicked treeitem …

Fix "Release Notes" label & link for pre-releases in sidebar

---

vscode/CHANGELOG.md
vscode/webviews/SearchPanel.module.css
vscode/webviews/SearchPanel.tsx

The search instructions take a lot of permanent visual space/noise when not in use, so this hides the search instructions until you hover or focus within that panel.
https://github.com/sourcegraph/cody/assets/153/625daf2a-ce61-4314-bf2a-2e76a0301ff7
- Hovered over panel
- Focused in panel

Search: Only show search instructions on hover or focus

---

vscode/src/services/TreeViewProvider.test.ts
vscode/src/services/TreeViewProvider.ts
vscode/src/services/treeViewItems.ts

Fixes https://github.com/sourcegraph/cody/issues/2203
@kalanchan I don't have an enterprise account, are you able to test they're not showing now?
I'm also assuming the issue was specifically for the sidebar, but let me know if not (the other places tied to rate limiting are supposed to appear based on the presence of the Pro header that shouldn't exist for non-dot-com users).
- Login as a dotCom user
- Verify Usage link is visible in sidebar (and if not Pro, the Upgrade link)
- Login as enterprise user
- Verify both links are not visible

Mark Upgrade/Usage links as dot-com only

---

vscode/CHANGELOG.md
vscode/src/editor/utils/editor-context.ts
vscode/test/e2e/at-file-context-selecting.test.ts

Fixes https://github.com/sourcegraph/cody/issues/2198
- Run `pnpm test:e2e at-file` to run updated test, or:
- On Windows, open chat and try to attach a file in chat using backslashes and forward slashes for searching filenames

Handle context file searching using forward slashes on Windows

---

vscode/CHANGELOG.md
vscode/src/release.test.ts
vscode/src/release.ts
vscode/src/services/OpenTelemetryService.node.ts
vscode/src/services/sentry/sentry.ts
vscode/src/services/telemetry.ts
vscode/src/services/treeViewItems.ts
vscode/src/version.test.ts
vscode/src/version.ts
vscode/webviews/Notices/VersionUpdatedNotice.tsx

Follow on from #2210, this fixes pre-release version not being shown correctly in the sidebar. This was because the version value is baked at build time, before pre-release bumps the package.json.
This updates the version detection to use the vscode extensions API (borrowed & moved from Telemetry, which was already doing this correctly).
The update notice in the web UI still uses the static version, as it always has. We can update that to handle pre-release/insider builds better in the future.
- Ran the extension with different versions, verified nav change
- Modified compiled source and reloaded the extension, verified nav change

Fix pre-release version numbers not being correctly detected

---

lib/shared/src/codebase-context/context-status.ts
lib/shared/src/configuration.ts
lib/shared/src/sourcegraph-api/environments.ts
vscode/src/completions/providers/createProvider.test.ts
vscode/src/configuration.ts
vscode/src/extension.common.ts
vscode/src/extension.node.ts
vscode/src/external-services.ts
vscode/src/graph/bfg/download-bfg.ts
vscode/src/local-context/local-embeddings.ts
vscode/src/services/AuthProvider.ts
vscode/test/e2e/chat.test.ts
vscode/test/e2e/helpers.ts
vscode/test/e2e/local-embeddings.test.ts
vscode/test/fixtures/mock-server.ts
vscode/webviews/Components/EnhancedContextSettings.tsx

- When opening a non-git repo, instead of the enhanced context selector showing a non-functional "enable embeddings" button, do not show local embeddings status.
- When opening a git repo without a remote, instead of showing a spinner indefinitely and "Indexed", show the circle-slash. Fixes #2217.
- During embeddings index generation, show the current file being indexed in the status bar item tooltip.
- If embeddings index generation fails, show the error message in a tooltip on the status bar. (Test coverage and improvements planned in a follow-up change.)
Adds e2e tests for the major cases above.
Also improves the e2e test framework:
- Fixes a race condition creating the workspace `.vscode` directory, and writing `.vscode/settings.json`. This sometimes meant the tests were running …

VSCode: Fix local embeddings status for non-git workspaces, git repos w/out remotes

---

vscode/CHANGELOG.md
vscode/src/local-context/local-embeddings.ts

Fixes #2245. Local Embeddings was not using the initial access token, when available.
https://github.com/sourcegraph/cody/assets/55120/833c1783-5384-45e4-94c4-bb93fbb8f471
Manual test:
1. Open a workspace, start a chat
2. Open the enhanced context selector and check that there's some local embeddings status
3. Cmd-Shift-P, Reload the window
4. Open the enhanced context selector; local embeddings status should appear

VSCode: Local Embeddings should pick up initial access token

---

agent/README.md
agent/recordings/FullConfig_234680970/recording.har
agent/src/agent.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
vscode/CHANGELOG.md
vscode/package.json
vscode/src/chat/protocol.ts
vscode/src/chat/utils.test.ts
vscode/src/chat/utils.ts
vscode/src/main.ts
vscode/src/services/AuthProvider.ts
vscode/src/services/TreeViewProvider.test.ts
vscode/src/services/treeViewItems.ts
vscode/test/fixtures/mock-server.ts

Replaces the "Sign Out" option with a new Account dialog that gives you visibility of what user you're signed in as, which server, and what plan.
| State | Screenshot |
| - | - |
| Cody Pro FF Not Enabled | <img width="1253" alt="Screenshot 2023-12-11 at 8 39 59 pm" src="https://github.com/sourcegraph/cody/assets/153/32b32e8d-34f8-40a2-af1f-7e97b7ef9c4f"> |
| Cody Pro FF Enabled | <img width="1253" alt="Screenshot 2023-12-11 at 8 40 22 pm" src="https://github.com/sourcegraph/cody/assets/153/2cff6715-48cb-4e39-a820-dac198f3cf76"> |
| Enterprise Instance | <img width="1253" alt="Screenshot 2023-12-11 at 8 41 16 pm" src="https://github.com/sourcegraph/cody/assets/153/bb0f1d59-25a9-4d66-af17-d122e4314d19"> |
Notes:
- Display name is often missing in Enterprise accounts, so we just use the …

Replace "Sign Out" with an account dialog

---

lib/ui/src/chat/TranscriptItem.module.css
vscode/CHANGELOG.md
vscode/resources/active-chat-icon.svg
vscode/src/chat/chat-view/ChatPanelProvider.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

Updates the chat editor icon:
| Theme | Preview |
| - | - |
| Before | <img width="429" alt="Screenshot 2023-12-11 at 10 57 55 pm" src="https://github.com/sourcegraph/cody/assets/153/02432ce1-62c5-4587-8457-6d3fa6c9ad69"> |
| After (Dark) | <img width="429" alt="Screenshot 2023-12-11 at 10 42 56 pm" src="https://github.com/sourcegraph/cody/assets/153/9f1cd108-5b63-49db-96de-ea55116dbf6f"> |
| After (Light) | <img width="429" alt="Screenshot 2023-12-11 at 10 43 12 pm" src="https://github.com/sourcegraph/cody/assets/153/c3c503c2-fa71-4311-8ff4-05c71715f34d"> |
- Start a new chat
- Observe icon
- Change color themes
- Observe icon

Chat: Update chat icon and transcript gradient

---

vscode/src/editor/utils/editor-context.ts
vscode/test/e2e/at-file-context-selecting.test.ts

[This depends on a function added in https://github.com/sourcegraph/cody/pull/2215 so this will fail bots until that lands and I rebase/merge]
Fixes https://github.com/sourcegraph/cody/issues/2208
- Run `pnpm test:e2e at-file` to run the updated test, or
- Open chat, and mention a file using `@` but type part of the file path outside of the folder opened in VS Code (eg. if you have `C:\Source\cody\ open, type `source`)
- Ensure that the results don't list every file because `source` exists in their full fspaths

Only search relative paths when @-mentioning files in chat

---

vscode/src/main.ts

"Continue setting up Cody" prompt does not need to be `await`ed; waiting on it breaks flow.

Do not await `showSetupNotification`

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/local-context/symf.ts

Previously, symf indexes for Cody were stored at `~/.cody-symf`. This moves them under the VS Code extension directory (where they'll be automatically if uninstall is triggered.
Also fixes https://github.com/sourcegraph/cody/issues/2172 by hiding slash commands in the chat input if they are inline edit commands.

use context.globalStorageUri for symf indexes

---

lib/shared/src/chat/preamble.ts
vscode/CHANGELOG.md
vscode/src/chat/chat-view/prompt.test.ts
vscode/src/chat/chat-view/prompt.ts

This adds support for the `cody.chat.preInstruction` setting in simplified chat, especially important now we have a "Chat Settings" button in the top of the chat editor:
Fix #2165
- Edit the setting
- Type a message

Chat: Add support for cody.chat.preInstruction in the new preamble

---

vscode/CHANGELOG.md
vscode/src/services/StatusBar.ts

Fixes #2162 
| - | - |
| <img width="633" alt="Screenshot 2023-12-12 at 5 37 48 pm" src="https://github.com/sourcegraph/cody/assets/153/62825cc1-5418-4101-8c6c-1937cd051da4"> | <img width="633" alt="Screenshot 2023-12-12 at 5 30 25 pm" src="https://github.com/sourcegraph/cody/assets/153/2017e3df-16f0-459c-9f36-2c8fd07cabba"> |
- Open settings
- Verify label

Settings: Relabel "symf Context" as "Search Context"

---

vscode/CHANGELOG.md
vscode/src/services/StatusBar.ts

This removes the experimental "Chat Suggestions" from the settings menu. Fixes #2281 
| - | - |
|  <img width="633" alt="Screenshot 2023-12-12 at 5 11 31 pm" src="https://github.com/sourcegraph/cody/assets/153/6bc0b991-1803-493a-83ad-ba11750ffc26"> | <img width="633" alt="Screenshot 2023-12-12 at 5 11 08 pm" src="https://github.com/sourcegraph/cody/assets/153/c6e3684a-164b-4408-9d93-b3de3b5dee79"> |
- Opened settings menu
- Verified no longer there

Chat: Remove Chat Suggestions setting that no longer works

---

lib/shared/src/sourcegraph-api/errors.ts
vscode/src/completions/inline-completion-item-provider.test.ts

Fixes #2272
- Logged in as rate limited pro user, verified rate limit error message changed
- Logged in as rate limited free user, verified rate limit error message unchanged

Update rate limit error wording for Cody Pro users

---

vscode/src/services/StatusBar.ts
vscode/test/e2e/command.test.ts

Removes the following "Simple Chat Context" setting from the settings quickpick, as it'll only be used internally or for specific support requests.
- Opened settings
- Verified it's gone

Settings: Remove the "Simple Chat Context" setting

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatModel.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/prompt.ts

Brings back the `chat-question:executied` metric for the new chat. I tried to recreate the metadata so it matches the old payloads. Anything we want to add? cc @chenkc805 
Open the output console and trigger chat messages. Observe the event being logged

Simple chat: Bring back chat telemetry

---

vscode/CHANGELOG.md
vscode/src/main.ts

Fixes #2292
Previously, detecting pastes into the document required the inline chat controller to be listening for changes. Since that was removed in #2079, we no longer detected pasts. This brings this behavior back via a dedicated event listener we add in `main`.
- Ask cody to gen code
- Copy it
- Paste it into a doc

Fix keyDown:Paste:clicked events

---

vscode/CHANGELOG.md
vscode/src/non-stop/FixupController.ts

closes https://github.com/sourcegraph/cody/issues/2259
Previously we would always scroll a completed task into view on completion.
We have a bug with this already (https://github.com/sourcegraph/cody/issues/2259).
One fix here is just to scroll this into view when the code is NOT already in view.
However, I think this might actually be annoying behaviour. The user already gets a notification for edits that are made if the file is not currently active. It seems overly aggressive to force their scroll back to the code when editing an active file.
1. Edit code in a large file
2. Scroll the code out of view
3. Check we don't hijack the scroll

Edit: Do not scroll into view on complete

---

vscode/webviews/Components/ChatModelDropdownMenu.module.css
vscode/webviews/Components/ChatModelDropdownMenu.tsx
vscode/webviews/Components/EnhancedContextSettings.module.css
vscode/webviews/Components/EnhancedContextSettings.tsx

Improves the tooltip for chats that can't change the model, and for Enterprise instances.
Fixes #2196
Also includes some fixes to unscoped styles that were leaking globally.
- Logged in dot com free. Opened a new chat. Hovered over chat model selector.
- Logged in dot com pr. Opened a new chat. Hovered over chat model selector.
- Logged in Enterprise. Opened a new chat. Hovered over chat model selector.
- Visually inspected enhanced context selector & dropdown for now style changes

Chat: Add tooltip to disabled chat model selector

---

vscode/src/commands/CommandRunner.ts

closes https://github.com/sourcegraph/cody/issues/2058
`getDocCommandRange` for the `/doc` command was returning the incorrect selection. It was overriding the end position rather than just adjusting the start position for python.
This meant that the edit command was treating this as an `add` (no selected code thus nothing to edit)
https://github.com/sourcegraph/cody/assets/9516420/62121460-3ddf-47d1-9b41-f86d94f43e12
https://github.com/sourcegraph/cody/assets/9516420/23519065-fd6c-4969-b034-e0530330d328
1. Highlight some code where there is not already a folding range
2. Use the "doc" command via the chat or right click menu
3. Check that the inserted documentation is correct

Edit: Fix malformed comments from doc command with selection

---

vscode/src/non-stop/FixupController.ts

closes https://github.com/sourcegraph/cody/issues/2082
Diffs can be scheduled - these update decorations, but this can conflict with removing the decorations when a task is applied.
So we have a race condition where it is possible that:
1. The task is applied, and decorations are removed
2. Later, a scheduled diff updates and re-applies the old decorations
To work around this, we just ensure that any scheduled diff updates are ran before we finally remove all decorations
1. Run an edit
2. Confirm that decorations are not shown on apply
1. Run the `/doc` command
2. Confirm that decorations are not shown on apply

Edit: Flush diffs on apply

---

vscode/src/commands/CommandRunner.ts

closes https://github.com/sourcegraph/cody/issues/2101
It is possible that the selection contains more code than is visible on the screen.
In this case, visibleRanges will never contain the entire selection.
We only really care about the start position of the selection (where the edit will be inserted). We use that position instead.
Run the /doc command on a large function when the entry point is already visible
Check the editor does not scroll unnecessarily
Run the /doc command on a large function when the entry point is NOT visible
Check the editor does scroll the entry point into view

Edit: Fix doc command jumping unnecessarily

---

vscode/src/services/telemetry-v2.test.ts
vscode/src/services/telemetry-v2.ts

The current returned type is too "loose" to be accepted directly by `telemetryRecorder.recordEvent`. This change makes it stricter (but still correct based on the intended behaviour of the helper) with some type hackery, courtesy of StackOverflow.
Previously, this kind of worked by accident because we "broadened" the type beforehand.
New and existing unit tests.

telemetry-v2: fix splitSafeMetadata to generate acceptable type

---

.github/workflows/ci.yml

These were added to try to allow third-party forks to successfully run our GitHub Actions CI steps… but alas they did nothing.
- N/A

Chore: Remove some GHA `ifs` that didn't work

---

lib/shared/src/sourcegraph-api/completions/nodeClient.ts
vscode/CHANGELOG.md

We were calling `[0]` even though it was a string which lead to it picking the first character. So if the rate limit was `222` it would show up as `2`
- Log in with rate limited David user
- Send a message

Fix rate limit number being displayed

---

vscode/CHANGELOG.md
vscode/src/completions/inline-completion-item-provider.ts

As the title says
https://github.com/sourcegraph/cody/assets/458591/4eb3f9b6-e0c2-4503-aa9c-082b1a4b49b5
- Be rate limited
- Trigger completions

Autocomplete: Don't show loading spinner when rate limited

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/graph/bfg/download-bfg.ts
vscode/src/jsonrpc/embeddings-protocol.ts
vscode/src/local-context/local-embeddings.ts
vscode/test/e2e/local-embeddings.test.ts

- If an incomplete index is loaded, explain the situation in the status bar.
- User can resume an incomplete index.
- Displays error messages from local embeddings in the UI.
- Updates the local embeddings protocol to 0.1.2. The client now learns the "names" (identifying keys) of repositories it is loading and indexing, so events can be related to the repositories they belong to. New methods to query the status of indexes and resume indexing.
https://www.loom.com/share/242be2c7abcd49d19e1709e0529651b1
UX refresh: https://www.loom.com/share/2654feb99c9f4985add94470a362bec7
Manual test:
1. Open a repository which doesn't have any embeddings.
2. Start generating local embeddings.
3. In Activity Monitor, kill the cody-engine process, leaving a partial index. Note, there's no handling process …

VSCode: Make embeddings errors visible, resume indexing on restart

---

agent/src/index.test.ts

Skip this test as it seems to be the last consistent flake on GitHub Actions
- N/A

Chore: Skip flaky agent chat cancellation test

---

vscode/package.json
vscode/src/completions/create-inline-completion-item-provider.test.ts
vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/completions/providers/createProvider.test.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts

- Removes `scminput` from the default values of the `cody. auto-complete.languages` setting to avoid confusing users with unknown language IDs. 
- Keeps autocomplete disabled for `scminput`.
- [Slack thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1702330574550309).
Updated unit tests.

Autocomplete: remove `scminput` from the autocomplete languages setting default value

---

agent/src/index.test.ts

Manually failed a test and confirmed that it shows a stack trace.

Agent: enable source maps in tests

---

vscode/src/completions/providers/dynamic-multiline.ts

- Closes #2288 
Generate multiline completions starting with an empty new line (e.g., if it starts with a line break).

Autocomplete: fix invalid position

---

lib/shared/src/sourcegraph-api/completions/client.ts
lib/shared/src/sourcegraph-api/completions/nodeClient.ts
vscode/src/completions/client.ts
vscode/src/log.ts

- Log the raw error with the stack trace to the console in the development environment.
- Part of #2288 
n/a

Autocomplete: log raw error in the development env

---

agent/recordings/FullConfig_234680970/recording.har
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/unstable-openai.ts

- Stop sequences were intentionally removed from the dynamic multiline completion request params. 
- This PR reverts relevant changes from https://github.com/sourcegraph/cody/pull/2118 to preserve this change.
Try generating multiline completion with two consecutive new lines and ensure they are not truncated in the middle.

Autocomplete: remove stop sequences for dynamuc multliline completions

---

vscode/CHANGELOG.md
vscode/webviews/index.html

This adds `data:` support for font loading to allow inline bundled fonts (like the cody icon set)

Chat: Fix cody icon font usage

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

closes https://github.com/sourcegraph/cody/issues/2300
Filters out custom edit commands from the chat input
Create a custom command with a mode that can edit
Check it does not appear in the slash command menu

Custom Commands: Filter out insert and edit commands from chat input

---

agent/recordings/FullConfig_234680970/recording.har
agent/src/index.test.ts
agent/src/vscode-shim.ts
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/jsonrpc/isRunningInsideAgent.ts
vscode/src/local-context/local-embeddings.ts

Previously, the agent tests didn't test the case where the client sends a notification for an accepted autocomplete request. Turns out that this notification caused uncaught errors that may have been the root cause behind sourcegraph/jetbrains#191
This PR adds a test case to reproduce the situation where a client accepts an autocomplete request and fixes the errors that happen when doing so.
Green CI.

Agent: add test case to accept autocomplete

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

closes https://github.com/sourcegraph/cody/issues/2260
Fixes the title of reopened chat panels.
We were using the `chatId` by accident before, due to a mistake when calling this function
> [!NOTE]  
> We could just not pass the `chatId` but we have two implementations of the ChatPanelProvider right now. One relies on the `chatId` and one doesn't. Will start a thread on Slack to discuss this as it can be quite confusing to debug!
1. Create a chat and ask a question
2. Close the chat
3. Reopen the chat by selecting it from the chat history in the sidebar
4. Inspect the title

Chat: Fix chat panel titles

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

The `fileUri` provided will be absolute. Instead, we always want to use a better Uri based on the relative file path that we already know.
closes https://github.com/sourcegraph/cody/issues/2331
1. Start chat, ask "what does this file do?"
2. Check context
3. Confirm current file is shown relative to users editor directory root.
4. Confirm context is correctly used
5. Confirm current file is clickable

Chat Context: Provide relative path as current file

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

closes https://github.com/sourcegraph/cody/issues/2317
This is something else which was covered in the chat logic but hasn't been lifted over to here yet
Click this button
Check menu opens

Chat: Fix settings menu not opening on click

---

vscode/CHANGELOG.md
vscode/package.json

adds upon https://github.com/sourcegraph/cody/issues/2162
Changing NLS from experimental to beta in the side panel
n/a

change nls label to beta

---

agent/package.json

Forgot this in the previous PR
n/a

Agent: enable source maps in `pnpm agent`

---

vscode/test/e2e/local-embeddings.test.ts

When we enabled search, Search — Indexed started appearing in the enhanced context selector. This will cause spurious passes in `local-embeddings.test.ts` which was just looking for the text "Indexed"; and spurious failures when the word "Indexed" appears twice, for search *and* embeddings.
Fix the test by looking specifically for "Embeddings — Indexed".
Note, this passed locally before this change, so check that we did not break it. But the real test is whether CI results are accurate now.
```
pnpm test:e2e -- local-embeddings.test.ts
```

VSCode: Fix local embeddings e2e test to specifically check that *embeddings* are indexed

---

vscode/CHANGELOG.md
vscode/src/graph/bfg/download-bfg.ts

Fixes #2328.
CI.
The "os error 5" issue specifically is covered by tests upstream.

VSCode: Roll cody-engine to v5.2.12792

---

vscode/CHANGELOG.md
vscode/src/local-context/local-embeddings.ts

- Do not display "Cody Embeddings Index Complete" if there's an error from the last local embeddings indexing attempt.
- Display the local embeddings percent *complete* in the status bar. Previously we displayed the percent *in*complete.
See https://www.loom.com/share/869556cee0dc42e4b1694f924c9e61fd?sid=8234ac0d-c984-4def-a31f-5d474d5b294d
0. Sign in with a rate-limited token.
1. Generate an incomplete embeddings index by opening a repo without embeddings, starting chat, enabling embeddings, and let it hit the rate limit. Alternatively, kill the cody-engine process and reload VSCode.
2. The status bar should indicate an appropriate, low percentage completion.
3. Resume indexing to hit the failure again. You should not see a sparkle toast that the index is complete when indexing fails.
4. …

Embeddings: Display accurate percent done; do not toast continued embeddings failure

---

vscode/webviews/Components/ChatModelDropdownMenu.tsx

- Part of https://github.com/sourcegraph/cody/issues/2311
- Send `openLLMDropdown:clicked` only on dropdown open
For the `CodyVSCodeExtension:openLLMDropdown:clicked` event, it fires only when:
- the dropdown is open-able AND opens
- Don't fire if the dropdown is disabled, if the dropdown is closing, or if the user clicks and LLM which causes the dropdown to close.

Chat: send `openLLMDropdown:clicked` only on dropdown open

---

lib/ui/src/chat/ErrorItem.tsx
vscode/src/completions/inline-completion-item-provider.ts

- Closes of https://github.com/sourcegraph/cody/issues/2311
- Use the correct user tier in the upsell event.
- Use the correct event when pro users hit the usage limit.
- For the `CodyVSCodeExtension:upsellUsageLimitCTA:shown` event, ensure the correct "tier" is being passed into the payload. The tier should be the tier the user is on.
- For users on the Pro tier, when they hit the abuse limit for chat/commands or autocompletes and the abuse UI shows up, we should log `CodyVSCodeExtension:abuseUsageLimitCTA:shown`

Chat: use the correct user tier in the upsell event

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

Re-adds /edit and /doc commands purely as entry points away from chat.
Long term we will remove these from chat altogether, but this is a bandage fix for the release as we have various docs and marketing materials that shows these commands as part of this list.
Relevant thread: https://sourcegraph.slack.com/archives/C05AGQYD528/p1702428819446009
Further follow up on https://github.com/sourcegraph/cody/issues/2300
Edit:
1. Open chat
2. Type /edit with no instruction
3. Check re-prompted for instruction
Edit with text:
1. Open chat
2. Type /edit add some logs
3. Check edit executes
Doc:
1. Open chat
2. Type /doc
3. Check doc executes
Doc with no selection
1. Open chat
2. Type /doc
3. Check doc doesn't execute

Chat: Re-add /edit and /doc commands

---

lib/shared/src/index.ts
lib/shared/src/sourcegraph-api/errors.ts
lib/ui/src/chat/ErrorItem.tsx
vscode/src/chat/chat-view/SimpleChatModel.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/prompt.test.ts
vscode/src/chat/chat-view/prompt.ts
vscode/src/chat/protocol.ts
vscode/webviews/App.css

Also display warning nicely:
Partially addresses https://github.com/sourcegraph/cody/issues/2352
Test locally:

chat: display CTA to create new chat when context limit reached

---

.vscode/launch.json
lib/shared/src/sourcegraph-api/completions/codyRateLimitWorkaround.ts
lib/shared/src/sourcegraph-api/completions/nodeClient.ts
vscode/src/completions/client.ts
vscode/src/local-context/symf.ts

This attempts to work around the rate limiting header issues and instead parses the first SSE payload error text and tries to reverse-engineer the PLG headers.
To do that, we parse the error string, e.g.:
```
Sourcegraph Cody Gateway: unexpected status code 429: you have exceeded the rate limit of 10 requests. Retry after 2023-12-15 14:36:37 +0000 UTC\n
```
To get the quota and the retry after field, and make a request to the backend to find out if the user is already a pro user.
https://github.com/sourcegraph/cody/assets/458591/fca610e3-f3a5-4b5d-9f0c-5b765e18512f
https://github.com/sourcegraph/cody/assets/458591/ebba8005-0ee9-4ee8-825d-637415252689

HACK: Work around rate limiting errors by parsing the SSE message and reverse-engineering the headers

---

vscode/CHANGELOG.md
vscode/package.json

Release 1.0.0
trivial change; just updating version numbers

VS Code: Release 1.0.0

---

lib/ui/src/chat/Transcript.tsx
vscode/CHANGELOG.md

c.f. https://sourcegraph.slack.com/archives/C05AGQYD528/p1702648955261399?thread_ts=1702602272.959489&cid=C05AGQYD528
The current experience is poor since it does not show proper names and appears just broken. Also you can not _change_ the model for enterprise setups anyways (we have a hard check for this on the backend).
- `sg start` locally

Hide LLM dropdown for enterprise users

---

lib/shared/src/sourcegraph-api/completions/nodeClient.ts
vscode/CHANGELOG.md

Welcome to callback hell. Even though we handle a bazillion cases here, we did never call any of the callbacks if:
- The connection opens
- We receive headers
- However, none of these headers indicate errors
- And we receive no body and instead closes
This adds some form of handling for this so the request doesn't appear stuck.
We should also make it so the backend indicates the error in the response somehow (c.f. https://sourcegraph.slack.com/archives/C05AGQYD528/p1702648140278529)
- git revert 2a00da01ae8b83ecd5450af7be2682c32edf3080 (to bring back the issue that beyang fixed)
- Create a chat message with GPT 3.5

Handle connection close events with no prior errors or messages

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/CodebaseStatusProvider.ts

Added cody.codebase support to the CodebaseStatusProvider, when the cody.codebase setting is set it should take priority over the git remote detection
resolves https://github.com/sourcegraph/cody/issues/2409
**When connected to enterprise (s2)**
Opened a local only repo (no git) - verified no embeddings mentioned in enhanced context
Set the cody.codebase setting to `github.com/sourcegraph/sourcegraph` verified enhanced context showed embeddings now available
Opened a repo with a git remote `hashicorp/go-multierror` - verified it showed no embeddings detected for this repo on remote
Set cody.codebase to `github.com/sourcegraph/sourcegraph` - verified it showed embeddings now available
**When connected to dotcom**
Opened a local only repo (no git) - embeddings not available (and no …

Chat: honor cody.codebase setting

---

vscode/CHANGELOG.md
vscode/src/editor/EditorCodeLenses.ts

Closes #2428
Looks like a whoopsie after the recent setting name change.

Fix code lenses feature
