vscode/CHANGELOG.md
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/SubmitButton.module.css
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/SubmitButton.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.module.css
vscode/webviews/storybook/VSCodeStoryDecorator.tsx

Fixes the send button styles, including hover, focus and high contrast modes:
https://github.com/sourcegraph/cody/assets/153/44e7a62e-1478-400e-8a9d-c9b46cbe919e
Also fixes the Storybook theme selector to apply the correct class name for the High Contrast Dark theme.
- CI

Chat: Fix contrast and colors of send button

---

vscode/CHANGELOG.md
vscode/package.json

- Patch release with everything we have on main
- Release branch to publish from https://github.com/sourcegraph/cody/compare/vscode-v1.20.1
CI

VS Code: Release 1.20.1

---

agent/src/fix.test.ts

This test typechecking with `tsc` so it may take more than 10s to run in CI where 1) we have less powerful machines and 2) we're running a very large number of tests in parallel. On my local computer, this test takes ~340ms to run per vitest output.
Green CI, no flaky failure.

CI: increase timeout for Fix integration test

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/completions/context/retrievers/jaccard-similarity/bestJaccardMatch.bench.ts
vscode/src/completions/context/retrievers/jaccard-similarity/bestJaccardMatch.ts
vscode/vite.config.ts

User reported high-cpu usage with Cody installed https://github.com/sourcegraph/cody/issues/4348. Their CPU profile revealed an average 4 seconds spent getting context for autocomplete with a large amount spent counting word occurrences. 
Now instead of stemming each word individually we maintain a small cache which speeds up stemming by more than 7x (if cache cleared before every benchmark run. Can be much higher in real-world scenarios).
Fixes CODY-1928
- tested several options by writing a simple benchmark and picking the most performant alternative
- ran existing unit tests to ensure no altered behavior

Jaccard Retriever: Reduce performance overhead

---

vscode/CHANGELOG.md
vscode/webviews/chat/cells/messageCell/assistant/AssistantMessageCell.tsx

Don't append unnecessary @'s if you press the "Add context..." button in chat multiple times. Instead, this change just refocuses the input at the relevant location.
- CI (could not find any relevant test to update/add to)

Chat: Don't append @ when "Add context" is pressed multiple times

---

agent/recordings/customCommandsClient_509552979/recording.har.yaml
vscode/src/commands/context/file-path.ts
vscode/src/prompt-builder/unique-context.test.ts
vscode/src/prompt-builder/unique-context.ts
vscode/test/e2e/command-custom.test.ts

"Add file to cody chat" command from a right click on a file would fail since we would have an empty range set. This treats any empty range as an indication the user wanted to add the whole file, which should plug the hole for other potential call sites on getContextFileFromUri.
Additionally if we do not have a range defined, we now do not set range on the returned ContextItem. This is so we render the file in chat as just the filename, rather than the filename with the range 1:lineCount.
Test Plan: Manually added and removed a file from chat. Then added the file via right click on the text area, right click on the explorer. Additionally tested that selecting text and right clicking correctly selected just the range.
Fixes https://linear.app/sourcegraph/issue/CODY-1996/add-file-to-cody-cha …

commands: getContextFileFromUri treats empty ranges as full file

---

agent/src/esbuild.mjs
agent/src/vscode-shim.ts
agent/tsconfig.json
biome.json
lib/shared/tsconfig.json
package.json
pnpm-lock.yaml
tsconfig.json
vscode/.gitignore
vscode/package.json
vscode/package.schema.json
vscode/scripts/enable-typehacks.ts
vscode/scripts/tsconfig.json
vscode/scripts/validate-package-json.ts
vscode/src/main.ts
vscode/src/services/StatusBar.ts
vscode/test/integration/tsconfig.json
vscode/tsconfig.json
vscode/typehacks/README.md
vscode/typehacks/vscode.ts

During debugging of [CODY-1928](https://linear.app/sourcegraph/issue/CODY-1928/) I noticed we were re-registering a global command. 
The fix would have been simple but encouraged by @olafurpg's urge to seize every opportunity to guard against regressions and capture reproductions in tests; I spent some time ensuring that these kind of mistakes can't creep in again.
1. Avoid (transitive) imports of `vscode` in the `agent/vscode-shim.ts`. This was the third time I accidentally tripped it and each time I wasted too much time remembering there is a massive disclaimer comment. Now we simply check this condition during the build...as a service to future self.
2. The package.json manifest now has a schema that we can expand upon. It's only basic right now, because VSCode doesn't provide a schema …

DX: Add type/build checks for common hard-to-notice pitfalls

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/package.json
vscode/src/completions/providers/create-provider.test.ts
vscode/src/completions/providers/create-provider.ts

This deployment is not used and does no longer exist: https://sourcegraph.slack.com/archives/C0514L18QHG/p1715708673418439?thread_ts=1711144019.316819&cid=C0514L18QHG
- CI

Autocomplete: Remove multi-tenant llama code

---

pnpm-lock.yaml
vscode/CHANGELOG.md
vscode/package.json
vscode/webviews/components/MarkdownFromCody.tsx

rehype-highlight, the syntax highlighting lib we use, has a memory leak bug (https://github.com/remarkjs/react-markdown/issues/791). Downgrading to rehype-highlight@^6.0.0 as recommended fixes the memory leak.
This was causing an issue where the Cody chat webview turned gray due to an out-of-memory situation.
- Fixes https://github.com/sourcegraph/cody/issues/4431
- Fixes https://linear.app/sourcegraph/issue/CODY-2062/gray-screen-in-chat
- Fixes https://linear.app/sourcegraph/issue/CODY-2017/reports-of-chat-ui-lagginess-on-long-messages
- Fixes https://community.sourcegraph.com/t/a-condensed-report-on-key-issues-affecting-cody/439#h-8-performance-issues-with-vscode-extension-18
- Fixes https://discord.com/channels/969688426372825169/969688427232641136/1247496110428258365
- Fixes …

fix memory leak in syntax highlighting (causing gray webviews)

---

agent/src/generate-unit-test.test.ts

Skip due to flakiness on CI: https://github.com/sourcegraph/cody/actions/runs/9377140919/job/25818213028#step:7:1017.
CI

skip flaky test `Generate Unit Test > editCommands/test 1`

---

vscode/CHANGELOG.md
vscode/webviews/chat/ChatMessageContent.tsx

The better fix would be to not leak event handlers in the useEffect hook, but this is a quick fix.
Fix https://linear.app/sourcegraph/issue/CODY-2102/vs-code-freezes-when-copy-pasting-selected-text-from-code-block-in
CI
Copy code in chat and confirm in the output channel that no event log spam occurs

disable copy event logging on code blocks to fix event log spam

---

vscode/CHANGELOG.md
vscode/webviews/chat/ChatMessageContent.tsx

The `usePreserveSelectionOnUpdate` hook is actually not necessary with the new more stable Markdown rendering. Confirmed on macOS and Linux.
Fix https://community.sourcegraph.com/t/copy-while-generating-answer/466/5
Start a chat like `write 50 jokes about fruits in code blocks` and try to copy as the message streams in.

fix inability to copy text in streaming chat response

---

vscode/src/local-context/local-embeddings.ts

We don't have a good way to distinguish between which errors users can take action to fix and which they can't. This leads to annoying errors, such as for when the user opens a non-Git repository.
In https://linear.app/sourcegraph/issue/DES-7/show-errors-in-symf-and-embeddings-indexing-and-re-index-ability we will improve error display in the chat UI, where the errors will at least be relevant and not annoying/disruptive.
Fix https://linear.app/sourcegraph/issue/CODY-2088/error-when-opening-vs-code-in-a-subdirectory-of-a-git-repo
Fix https://linear.app/sourcegraph/issue/CODY-2071/bug-cody-embeddings-error-path-to-subdirectory-mono-repo-does-not
Open a non-Git repo folder. Confirm that no embeddings error shows up upon VS Code initial load and when opening chat.

suppress embeddings error notifications

---

vscode/webviews/chat/ChatMessageContent.module.css

If the VS Code setting `editor.fontSize` was set to 20 (or another large number), the line-height in chat was too small and code lines overlapped each other.
Fix https://community.sourcegraph.com/t/line-height-issue/364
Fix https://linear.app/sourcegraph/issue/CODY-2045/code-line-height-in-chat-is-wrong
Set VS Code setting `editor.fontSize` to 20 and ensure chat code blocks render OK.

fix chat line-height and font-size

---

vscode/CHANGELOG.md
vscode/webviews/promptEditor/plugins/atMentions/atMentions.tsx

Fix https://linear.app/sourcegraph/issue/CODY-2106/entering-key-when-input-is-at-bottom-causes-scroll-up-to-top
CI

Fix an issue where opening the @-mention menu in a followup input would scroll the window to the top

---

vscode/webviews/Notices/index.module.css

Currently the version-updated toast covers up the chat input. This is annoying and confusing. Now, it shows up above in flow. This is more prominent but less annoying IMO. And it's OK for it to be this prominent since it only shows up once every 2 weeks.
Fix https://linear.app/sourcegraph/issue/CODY-2116/move-the-cody-updated-toast-to-the-bottom-of-the-window
CI

show version-updated toast above (relative not floating)

---

package.json
vscode/CONTRIBUTING.md
vscode/package.json
vscode/scripts/version-bump.ts
vscode/src/uninstall/post-uninstall.ts

feat: add scripts to automatically bump the version and update the changelog
- Added a new script `vsce-version-bump` to the root `package.json` to bump the VS Code extension version.
- Added a new script `version-bump:minor` to the `vscode/package.json` to handle minor version bumps.
- Implements a `version-bump.ts` script that:
- Increments the version number based on the `RELEASE_TYPE` environment variable
- Updates the version in `package.json`
- Updates the version in the `CHANGELOG.md` file
- Commits and pushes the changes VS Code: Release v1.20.2
- Updated `vscode/CONTRIBUTING.md`
Try running `vsce-version-bump` and check `git log` to confirm `package.json` and `CHANGELOG.md` are updated correctly.

VS Code: Add version bump scripts (#4442)

---

vscode/src/chat/chat-view/context.ts

This is a tiny fix to our `needsReadmeContext` detection. Previously, we split
the question on punctuation, but did not do the same for the root directory
name. So we would never match if the repo contained a hyphen, etc.
Manually tested the question "what does`@symf-private` do?" repo on the
`symf-private` repo and checked we now include `README.md`.

Improve 'needs README' context detection

---

vscode/src/models/index.ts

This change is related to https://github.com/sourcegraph/jetbrains/issues/1498.
Previously, users received a misleading error message when the problem actually was caused by an expired authentication token. 
Try to start a new chat after your token has expired. The stack trace should say "You are not authenticated".
Verified manually that the behaviour of VS Code is not affected.

Correct error message when the chat/new request fails to authenticate to the Sourcegraph API

---

vscode/CHANGELOG.md
vscode/test/e2e/chat-context.test.ts
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/contextCell/ContextCell.story.tsx
vscode/webviews/chat/cells/contextCell/ContextCell.tsx

Previously, it was not clear which context was used in followup messages. The way it works is that context used previously in the conversation is automatically used for followups, but only *newly introduced* context is displayed. This was confusing, because it could seem like *only* that newly introduced context was used.
Now, the UI says `X new item` and expands to mention `Prior messages in this thread` for followup message context rows if new context was introduced. If no new context was introduced, there is no context row and the prior conversation context is still used (we assume this is implicit to the user).
Fix https://linear.app/sourcegraph/issue/CODY-2092/show-full-actual-context-used-for-followups
CI + new e2e test

indicate context used for followup messages

---

vscode/src/chat/chat-view/prompt.test.ts
vscode/src/chat/chat-view/prompt.ts

Previously, when assembling the prompt we added new enhanced context last, even
after historical context. This PR updates the prompt logic to always place new
context before historical context. Reasoning: the new context is more likely to
be relevant to the user's question, and should be given precedence.
Relates to SPLF-6
Added new case to `prompt.test.ts`. Manually tested long chats in VSCode.

Prefer new enhanced context over historical context

---

vscode/package.json

This is specified in the OpenCtx extensions, but when we ported the support over to cody we did not specify this. This is important to specify.
Test Plan: Made a new workspace and opened it and did not trust it to ensure I was in restricted mode. I then successfully used cody with my user configured providers. I added a workspace provider setting and vscode warned me I needed to trust the workspace + the provider did not show up in chat.

vscode: specify untrusted configuration "openctx.providers"

---

vscode/src/context/openctx.ts
vscode/src/main.ts

This allows initialization to happen concurrently with the other promises in main when the configuration changes. The main motivation for this change is it makes another change I want to make cleaner. View this diff with whitespace changes turned off to see how minimal it actually is.
Test Plan: Started up vscode and still saw OpenCtx providers in chat.

openctx: refactor exposeOpenCtxClient to async function

---

vscode/src/context/openctx.ts

This commit will show a warning if the OpenCtx extension is installed and tell the user to disable it. It will additionally open up the extensions view filtered down to just the OpenCtx extension.
This isn't an ideal user experience, but after exploring the vscode APIs and codebase I couldn't find a more surefire way.
The reason this is added is the extensions currently conflict, leading to openctx providers in cody failing to initialize. I looked into ways to try and gracefully detect and avoid conflict, but did not manage to find a way.
Note: this checks at startup and on config change. I could add something which listens for the OpenCtx extension, but that is more complicated and the only time mention items break in cody is if it isn't the first to call createController.
Note: …

openctx: warn if sourcegraph.openctx ext is enabled

---

vscode/src/main.ts

This call will fail since it doesn't update config nor is it idempotent. It tries to re-register all vscode commands/etc which would fail. You can observe this by viewing cody output and updating your settings, you will see a line like:
```
openctx: Failed to load OpenCtx client: Error: command 'openctx.toggleEnable' already exists
```
As follow-up the vscode-lib controller needs to support being able to have providers updated, then we can implement a correct responding to config changes.
Test Plan: updated config and did not see openctx errors in cody output. Then tested that openctx providers still appear in mentions.

openctx: do not call exposeOpenCtxClient on config change

---

agent/recordings/defaultClient_631904893/recording.har.yaml
recordings/rewrite-query_2689977722/recording.har.yaml
vscode/src/local-context/rewrite-keyword-query.test.ts
vscode/src/local-context/rewrite-keyword-query.ts

For some inputs, our LLM query rewrite would produce multiple lines of XML, whereas we expect a single line. This caused us to return no rewritten term, which results in no context.
This change updates the prompt to encourage the LLM to produce a single line. Additional fixes:
* Make sure to split `value` (the main keyword) on whitespace, to avoid duplicated rewritten terms
* If the rewrite fails for whatever reason, return the original string instead of failing the whole search
Relates to CODY-1615
Added new test case for query that triggered the broken behavior:
```
type Zoekt struct {
\tClient zoekt.Searcher
\t// DisableCache when true prevents caching of Client.List. Useful in
\t// tests.
\tDisableCache bool
\tmu       sync.RWMute
```

Fix symf rewrite failures

---

lib/shared/src/configuration.ts
vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/completions/create-multi-model-inline-completion-provider.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/testutils/mocks.ts

This allows the user to set the timeout used for dynamic multiline completions. When this timeout is hit, we truncate the in-progress completion and propose whatever has streamed out as the completion. The default is 1500ms, which is low enough to be hit for many multiline completions. This causes our completion to appear as "partial" (we don't complete the whole syntactic block), which leads to a poor user experience.
In future work, we should investigate bumping or eliminating this timeout altogether, but this will at least allow us to bump the timeout internally while we investigate new completions models.
Setting is experimental. Tested locally.

cody.experimental.autocomplete.firstCompletionTimeout setting

---

vscode/webviews/components/modelSelectField/ModelSelectField.tsx
vscode/webviews/components/shadcn/ui/command.tsx

Link to enterprise model and model provider options in the model selector to show the additional options available in Cody Enterprise.
Depends on https://github.com/sourcegraph/docs/pull/396.
CI

enterprise model options link in model selector

---

vscode/src/configwatcher.ts
vscode/src/main.ts
vscode/src/services/UpstreamHealthProvider.ts
vscode/test/e2e/initial-context.test.ts

Current config handling is a bit of a mess with many different patterns in use, related code spread across multiple locations, and at least one update cycle (main.ts config change handler -> syncAuthStatus -> PlatformContext.onConfigurationChange -> main.ts config change handler).
This introduces a `ConfigWatcher` class that encapsulates the logic of listening for changes. Using this class simplifies the `register` function in `main.ts`. Objects that need to listen to config changes can register a listener immediately after they are declared/initialized, rather than needing to put all the config change listeners in the `onConfigurationChange` inline function (which was returned to the `start` function, which had the responsibility of invoking it).
No change in functionality.
Checks to …

Add ConfigWatcher class to simplify config change handling

---

vscode/webviews/components/modelSelectField/ModelSelectField.tsx
vscode/webviews/components/shadcn/ui/command.tsx

Previously it only sent when using the mouse.
Also fixes https://linear.app/sourcegraph/issue/CODY-2189/links-in-model-selector-dropdown-do-not-close-dropdown-until-later.
Confirm that events get sent when selecting any enterprise model option link via the keyboard and mouse.

send cody.modelSelect telemetry when using keyboard

---

lib/shared/src/mentions/api.ts
vscode/webviews/mentions/mentionMenu/MentionMenu.module.css
vscode/webviews/mentions/mentionMenu/MentionMenu.test.tsx
vscode/webviews/mentions/mentionMenu/MentionMenu.tsx

closes: https://linear.app/sourcegraph/issue/CODY-2109/double-dividers-in-loading-state
This PR fixes the double divider in the loading/empty state of the @-mention menu. 
It also updates the label when the query is nil and fixes the padding. 
Before: 
After: 
Demo: https://www.loom.com/share/362c851761ea44499a54cd40c6b90c76?sid=93a4d6f3-62ad-477f-bde0-60599570e598

Fix empty state for @-mentions

---

vscode/CHANGELOG.md
vscode/webviews/mentions/mentionMenu/MentionMenu.module.css

The model selector shows scrollbars if needed, but the @ mention menu doesn't, and I've witnessed multiple occasions where people didn't scroll down. This updates them to be consistent with each other, and the user's O/S.
Fixes https://linear.app/sourcegraph/issue/CODY-2150/-mention-menu-missing-scrollbar
- CI

Make sure to show scrollbar in the @ menu if needed

---

vscode/src/chat/chat-view/agentContextSorting.ts
vscode/src/commands/services/runner.ts

Tiny improvements to context sorting:
* Remove redundant function `sortContextFiles`
* Make sure to set locale when comparing context items, to avoid different
results across environments
Just clean-up, and no real behavioral changes.
Test-only change

Solidify context sorting for tests

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

This commit fixes an issue where pressing ESC to abort an in-progress chat puts chat in an unusable state, reported by our users during a customer call.
Context: https://linear.app/sourcegraph/issue/CODY-2259
To reproduce:
1. Send Cody a question
2. While the response is being streamed, press ESC to stop the stream
3. You will not be able to submit a new chat as it's still in loading state 
Fix:  move abortSignal.throwIfAborted() to the callback function for error and remove them from the update and close callback functions.
We should also consider adding back a stop button in a follow-up.
To Manually test the changes in this PR:
2. Ask Cody a question
3. While the response is being streamed, press ESC to stop the stream
5. Confirm the Submit button is not …

Chat: Fix aborted requests

---

vscode/CHANGELOG.md
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/clientStateBroadcaster.ts
vscode/src/commands/context/selection.ts
vscode/webviews/promptEditor/nodes/ContextItemMentionNode.ts

CONTEXT: https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1717600416051439
Address one of the user feedback in https://linear.app/sourcegraph/issue/CODY-2259, specifically: "Large file was added to new chat initially without warning"
This PR fixes an issue where initialContext that are too large do not have the styles intended for large files.
Also added line-through to large file styles to make it obvious the context will not be included.
Changes included:
- Add chatModel parameter to startClientStateBroadcaster function
- Use chatModel.contextWindow to determine user context size when adding current file/selection to context items
- Add getSelectionOrFileContext function for getting context file from current selection, or entire file when there is no selection
- Update …

Chat: update token styles for initial @-file that are too large

---

vscode/webviews/promptEditor/nodes/ContextItemMentionNode.ts

Update large file tooltip text for context file added initially:
Tooltip text update. No feature changes.

Chat: Update large file tooltip text

---

agent/recordings/customCommandsClient_509552979/recording.har.yaml
agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/__snapshots__/custom-commands.test.ts.snap
agent/src/index.test.ts
lib/shared/src/prompt/templates.ts
vscode/src/prompt-builder/index.test.ts

Follow-up on https://github.com/sourcegraph/cody/pull/4516
Comment: https://github.com/sourcegraph/cody/pull/4516#discussion_r1633816517
> we are adding @ in front of the file name for selected code, but we don't do the same for other context
This PR removes the `@` from the SELECTED_CODE_CONTEXT_TEMPLATE to align it with the format we use for other codebase context files.
Check the updated tests to confirm no regression was introduced by this change.

Chat: Remove @ from selection context template

---

vscode/package.json

Moved playwright install to `test:e2e` to minimize cost of `pnpm install`
Green CI

chore/ci: moved playwright install command

---

vscode/CHANGELOG.md
vscode/package.json
vscode/scripts/version-bump.ts

VS Code: Release 1.22.0 - Stable Release
Blog Post: 
- PR: https://github.com/sourcegraph/about/pull/7001
- Preview: https://deploy-preview-7001--sourcegraph.netlify.app/blog/cody-vscode-1-22-0-release
Updated the version-bump script that I used for creating this PR!

VS Code: Release v1.22.0

---

lib/shared/src/prompt/templates.ts

Follow up to #4527. This parameter is not used, so removing it for clarity.
Covered by CI

Minor: remove unused repoName param

---

lib/shared/src/context/openctx/api.ts
package.json
pnpm-lock.yaml
vscode/package.json
vscode/src/chat/context/chatContext.ts
vscode/src/context/openctx.ts
vscode/src/editor/utils/editor-context.ts
vscode/src/main.ts

Previously we passed the controller's client. However, the controller also exposes the client API, but additionally has vscode specific error reporting logic.
Additionally we updated the OpenCtxClient type we declare as Picking only the fields we use.
We need to update client call sites to pass in providerUri as part of the new option interface.
Test Plan: See test plan of https://github.com/sourcegraph/openctx/pull/142
Here is what it looks like with a provider failing and initialize and at mentions.
Full demo at https://www.loom.com/share/107e380a1d1a43ca8302ac61ebf81805
Fixes https://linear.app/sourcegraph/issue/CODY-2082/show-errors-from-openctx-providers

openctx: update to directly use controller

---

vscode/CHANGELOG.md
vscode/src/certs.js

It works because the error was a patching error in this code 
```
var require_inject = __commonJS({
"../node_modules/.pnpm/win-ca@3.5.1/node_modules/win-ca/lib/inject.js"(exports2, module2) {
var https4;
var tls;
var der2;
var toPEM;
var agentOptions;
var roots;
var patchMode;
var saveCreateSecureContext;
https4 = require("https");
tls = require("tls");
der2 = require_der2();
module2.exports = iFactory;
iFactory.inject = inject;
toPEM = der2(der2.pem);
agentOptions = https4.globalAgent.options;
roots = [];
function iFactory(mode) {
inject(mode, []);
return add2;
}
function add2(der) {
roots.push(
toPEM(
der
)
);
}
patchMode = 0;
function inject(mode, array) {
if (array) {
roots.length = 0;
roots.push.apply(roots, array);
}
mode = "+" === mode ? 2 : mode ? 1 : 0;
if (mode === patchMode) { …
```

Adding a temporary fix to the win-ca package to remove the patched inject method that fails with Vscode's insiders build

---

.github/workflows/agent-bindings.yml
.github/workflows/ci.yml
.github/workflows/lints.yml
.github/workflows/scip-typescript.yml
.github/workflows/vscode-insiders-release.yml
.github/workflows/vscode-stable-release.yml

These are all old and using node 16 which will be removed soon according to GitHub. For pnpm I used the commit for the latest tagged release, which is v4.
Test Plan: CI

ci: use latest setup-gcloud, checkout and pnpm/action-setup

---

vscode/package.json

In our enablements and when in a few cases we had resourceScheme == file. However, Cody supports remote files if the editor can get the text. So instead we update those checks to be based on if the editor is in focus.
Additionally for the explorer it will only show the command if the enablement is also true, so we also check if filesExplorerFocus is true.
Finally we fix a bug where we showed the action on folders in the explorers, which does not work.
Test Plan: Tested the action showed up when right clicking on the editor or explorer if cody was open. Otherwise checked it was not shown.
Additionally checked the cody.menu.commands still showed up, but did not show up on other panes (eg the extension view).
Fixes https://linear.app/sourcegraph/issue/CODY-2340/the-length-of-the-file-caused-t …

vscode: show "Add File to Cody Chat" for remote files

---

vscode/CHANGELOG.md
vscode/src/models/utils.ts

CONTEXT: https://sourcegraph.slack.com/archives/C05AGQYD528/p1718323087549179?thread_ts=1718316482.993009&cid=C05AGQYD528
CLOSE https://linear.app/sourcegraph/issue/CODY-2356/add-gemini-to-the-list
- This change adds support for additional chat models with expanded context windows, including 'claude-3-opus', 'claude-3-sonnet', 'gpt-4o', 'gpt-4-turbo', and 'gemini-1.5'. 
- The `isModelWithExtendedContextWindowSupport` function has been updated to check for these model substrings, and the `getEnterpriseOutputLimit` function has been simplified to use the new function for determining the appropriate output limit.
N/A.
Adding a new string to the current list. No feature was changed.

Enterprise: add support for expanded context window to Gemini 1.5 models

---

vscode/CHANGELOG.md
vscode/webviews/mentions/mentionMenu/MentionMenuItem.tsx

Fixes the hover titles not showing on the @-mention file picker, so you can now differentiate between two files that may share a common and long path root:
- CI

Chat: Fix hover tooltips on overflowed paths in the @-mention file picker

---

lib/shared/src/llm-providers/clients.ts
vscode/CHANGELOG.md

The issue was caused by model providers being capitalized, which was not taken into account when matching clients. This change converts the model provider to lowercase before looking up the corresponding client.
1. Choose an Ollama model
2. Say hello to Cody
Before: Cody will response that it's Claude to confirm we are not connected to the Ollama client.
After: No more Claude in the response.

Ollama: Fix Ollama models not connected to correct client

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/fireworks.ts

We are shipping Finetuned model as the default model for `typescriptreact`, `javascriptreact` & `python`. Whereas keeping `starcoder-hybrid` as the default model for all the other language.
1. We are creating a new feature flag `cody-autocomplete-fim-fine-tuned-model-hybrid` for the fine-tuned hybrid model. For `typescriptreact`, `javascriptreact` & `python` it will pick up `fine-tuned model`, else `starcoder-hybrid` model.
2. [Slack conversation for the shipment decision(https://sourcegraph.slack.com/archives/C05AGQYD528/p1717313696244799)
3. [Finetuned Model Qualitative & Quantitative results](https://docs.google.com/document/d/1D8qzoXvUwJ8-5b4CKlkOYUSvz8qYrO_lxYUtiDgMvkM/edit#heading=h.p3zauxumq548)  
Manual Testing:
Tested manually that for [typescriptreact, javascriptreact & python] …

Finetuned model shipment for tsx, jsx and py

---

vscode/package.json
vscode/test/e2e/chat-keyboard-shortcuts.test.ts
vscode/test/e2e/common.ts
vscode/test/e2e/initial-context.test.ts

There are 2 hotkeys to open Cody chat: Opt+/ and Opt+L. In most places we document Opt+L. There are slight differences (Opt+L adds your selection, Opt+/ t) that do not merit having 2 different prominent keybindings.
We will standardize on Opt+L as the hotkey and as the single behavior. Opt+L also has the benefit of being similar to Opt+K, the edit hotkey. It makes Opt+/ an alias with the same behavior (for people with muscle memory).
Also fixes issues with Opt+L inserting a character instead of opening chat on macOS in some cases.
- Fixes https://github.com/sourcegraph/cody/issues/4215
- Fixes https://github.com/sourcegraph/cody/issues/4419
- Fixes https://github.com/sourcegraph/cody/issues/4178 (again)
- Fixes https://github.com/sourcegraph/cody/issues/4483
- Fixes …

Unify Opt+L and Opt+K hotkeys, fix Opt+L inserting a char instead of opening chat

---

vscode/src/minion/MinionController.ts
vscode/src/minion/MinionStorage.ts
vscode/src/minion/action.ts
vscode/src/minion/blocks/plan.ts
vscode/src/minion/statemachine.ts
vscode/webviews/minion/MinionApp.story.tsx
vscode/webviews/minion/MinionApp.tsx
vscode/webviews/minion/webview_protocol.ts

Remove the checkpoint logic, currently unused. Also rename "nodes" to "blocks" ("nodes" are now static identifiers for block constructors, and blocks are the actual execution units).
Remove unused code from experimental feature

minion: remove unused checkpoint

---

vscode/test/e2e/helpers.ts
vscode/test/e2e/troubleshooting-authConnection.test.ts

It's better to use a FrameLocator rather than a Frame in playwright, as a Frame can be invalidated by a navigation action. Fixes a sometimes-flaky test by using an appropriate FrameLocator, instead of a Frame, to target the Cody sidebar.
Test-only change.

fix flaky test

---

vscode/webviews/components/FileLink.tsx

Minor UI change to reflect the recent name change:
- Replace "Enhanced Context" with "Automatic Codebase Context" for various file sources.
Current: 
1. Ask Cody a question
2. Verify when hovering over the context file list icon, the tooltip displays `Automatic Codebase Context` instead of `Enhanced Context`.

Chat: update file source display text

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/TestClient.ts
agent/src/index.test.ts
vscode/src/extension.node.ts

Previously, symf was enabled in agent integration tests. We have observed quite a lot of unstable test failures that seem to be related to symf so this PR disabled symf entirely in the agent integration tests to see if it stablizes the CI.
Non-flaky green CI.

CI: disable symf in agent integration tests

---

.github/workflows/scip-typescript.yml
agent/src/fix.test.ts

Previously, the scip-typescript indexing job ran on every push. This changes the job to only run on pull requests and after merging into `main`.
* Manually confirmed that the job didn't run on this commit before opening a PR
* Manually confirm the job runs after opening a PR because I added a basic change to a TS file https://github.com/sourcegraph/cody/actions/runs/9549918620/job/26320644157?pr=4587

CI: refine workflow triggers

---

vscode/test/e2e/troubleshooting-authConnection.test.ts

Related [CODY-2432 : Re-enable vscode/test/e2e/troubleshooting-authConnection.test.ts - allow retrying on connection issues](https://linear.app/sourcegraph/issue/CODY-2432/re-enable-vscodeteste2etroubleshooting-authconnectiontestts-allow)
Skipping these tests because they have been very flaky recently, see
- https://github.com/sourcegraph/cody/pull/4591#issuecomment-2174170405
- https://sourcegraph.slack.com/archives/C05AGQYD528/p1718684941695799
Stable green CI

Skip flaky tests

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ClientInfo.kt
agent/src/AgentWorkspaceConfiguration.ts
lib/shared/src/configuration.ts
lib/shared/src/telemetry/EventLogger.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/jsonrpc/agent-protocol.ts
vscode/src/services/telemetry.ts
vscode/src/testutils/mocks.ts

1. Report proper extension version (previously Cody version was incorrectly used for both Jetbrains and NeoVim)
2. Add IDE version to the telemetry data 
1. Build [Jetbrains PR](https://github.com/sourcegraph/jetbrains/pull/1785) with this Cody changes
2. Run some Cody actions like commands and edit.
4. Wait ~2h
5. Check if event with new field(s) containing correct versions will appear in looker

Add ide version and proper Cody extension version to the telemetry

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/fim-prompt-utils.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/tree-sitter/language.ts

These are the changes for the autocomplete experiment. Following are the variant details, along with the hypothesis. (cc: @rishabhmehrotra)
1. `CodyAutocompleteFIMModelExperimentBaseFeatureFlag`: Any user in this feature flag will be assigned to this experiment.
2. `Control`: This is the current production model.
3. `Variant-1 `: This is current production model + 200 msec delay. The goal of this variant is to see the effect of latency increase on other metric. More details about this is given in the [RFC: Autocomplete metric governance](https://docs.google.com/document/d/1CSf4Nnfmy8Jch1CKVaGFGKruhwAsCq1rMIoxJP8PuHA/edit). In summary, we want to establish a pareto-curve for latency/Quality trade-off. Since the current production model is a combination of starcoder + Mixtral fine-tuned - …

adding completions experiment variants

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/certs.js
vscode/src/extension.node.ts
vscode/src/fetch.node.test.ts
vscode/src/fetch.node.ts

Fixes CODY-2176
Previously, we used the `win-ca` "fallback" method to install local certificates. We used the fallback because we use esbuild to bundle the Cody VSC extension, which breaks automatic detection of a `roots.exe` binary that is included with the `win-ca` npm package. In the latest VS Code Insiders, this no longer works and causes Cody to fail all network requests. This PR is an attempt to fix this problem by removing the "fallback", bundling the `roots.exe` binary along with the Cody extension and adding logic to compute the file path of the bundled `roots.exe` at runtime (via `vscode.ExtensionContext`).
* Get a Windows computer
* Install latest VS Code Insiders
* Install the latest Cody pre-release and reproduce the actual bug (network requests fail)
* Checkout this branch …

Windows Certificates: bundle roots.exe

---

lib/shared/src/models/utils.ts
vscode/src/models/sync.test.ts
vscode/src/models/sync.ts

- Add a new ModelUIGroup called Enterprise
- Assign the new ModelUIGroup to the Enterprise model during sync
This fixes an issue where we cannot identify if a Gemini is an Enterprise model or a model imported from cody.dev.models
Right now all enterprise models do not have a ModelUIGroup assigned, which would fails the logic here: https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/lib/shared/src/llm-providers/clients.ts?L47
No UI or feature change as we currently do not display model dropdown for Enterprise users.

Chat: Assign ModelUIGroup for Enterprise model

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/webviews/chat/Transcript.tsx

Part of https://linear.app/sourcegraph/issue/CODY-2149/feedback-bring-the-stop-button-back-again#comment-4c363fea
- Notify the webview when aborting a message submission operation to indicate there is no message in progress
- Update the `priorAssistantMessageIsLoading` prop to check if there is a message in progress, not just if the previous message was loading
- Ask Cody a question
- Hit ESC to abort the request during the context fetching step
- Verify the loading state disappeared on abort:
https://github.com/sourcegraph/cody/assets/68532117/a553602a-3772-484d-b1ea-3c559eef430a
You will be stuck in this loading state even after you hit ESC to abort the request:

Chat: fix abort message loading state

---

vscode/CHANGELOG.md
vscode/package.json

- Release workflow: https://github.com/sourcegraph/cody/actions/runs/9576633890
- Release branch: https://github.com/sourcegraph/cody/tree/vscode-v1.22.2
Updated change and package.json.

VS Code: Release v1.22.2

---

agent/package.json
agent/src/agent.ts
agent/src/esbuild.mjs
pnpm-lock.yaml
vscode/package.json
vscode/scripts/copy-win-ca-roots.ts

In the PR https://github.com/sourcegraph/cody/pull/4598, we fixed a bug related to how we installed self-signed certificates on Windows. This PR only fixed the issue for VS Code. This PR additionally fixes the problem for the agent. For the agent, we use a slightly different `extensionUri`. This PR adds logic to manually copy the `roots.exe` file over to the directory we use as `extensionUri` with the agent. The benefit of solving this problem like this is that it works automatically for all agent clients, avoiding the need to do custom solutions for individual clients like JetBrains.
Manually confirmed that we are no longer printing out an error when running the tests on Windows.

Windows: make win-ca also work with the agent

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ContextMentionProviderMetadata.kt
lib/shared/src/mentions/api.ts
vscode/webviews/mentions/mentionMenu/MentionMenu.story.tsx
vscode/webviews/mentions/mentionMenu/MentionMenu.test.tsx
vscode/webviews/mentions/mentionMenu/MentionMenu.tsx

This updates the mentions API to be more explicit. Every provider already supplies the title, queryLabel and emptyLabel so we might as well mark those fields as required and rely on them when rendering.
Additionally we update call sites of queryLabel to be used when prompting the user for querying only. For the mention title we now always use title. Previously we prefered the queryLabel for titles which was strange.
Note: this change has no user visible behaviour change, it just makes us internally more consistent.
Test Plan: updated unit tests to demonstrate how the fields are now used. Additionally manually tested openctx and builtin providers in the mention menu to ensure there are no changes in behaviour.

mentions: display queryLabel if no results and no query yet

---

agent/src/cli/scip-codegen/JvmCodegen.ts

Previously, the generated code didn't compile because it used `implements` instead of `extends`.
Manually confirm that the Eclipse plugin compiles.

Agent: fix bug related to `extends`/`implements`

---

lib/shared/src/mentions/api.ts
vscode/src/context/openctx/web.ts

This sets the query label to the newly added "label" field in OpenCtx. This is a field which prompts the user what to type in an at mention.
Test Plan: Tested manually the following cases
- non-openctx providers have same behaviour (no header)
- openctx provider has loading display before query label (see devdocs below)
- openctx query label goes away once query is being typed
- openctx provider which doesn't set label shows "Search..." (see notion below)
- web provider has updated label
https://github.com/sourcegraph/cody/assets/187831/6b3ade90-13b2-43bb-8ba9-e3e822514679
Parent https://github.com/sourcegraph/cody/pull/4621
Fixes https://linear.app/sourcegraph/issue/CODY-2275/add-all-the-right-labels-for-provider-mentions-query-stats

openctx: set query label if provided

---

lib/shared/src/lexicalEditor/nodes.ts
vscode/src/context/openctx/remoteFileSearch.ts

The title & label for the remote file search item are both file basename now. Not need for the `mention?.data?.mentionLabel` hack.
Cleaning up
tested

Cleanup mention label

---

lib/shared/src/index.ts
lib/shared/src/mentions/api.ts
vscode/webviews/mentions/mentionMenu/MentionMenu.story.tsx

This greatly expands the storybook for mention menu to cover some corner cases in file search as well as adding stories for OpenCtx.
Test Plan: ran pnpm story and browsed newly added items

mentions: add stories for no query and openctx

---

vscode/src/completions/providers/create-provider.ts

[Linear Issue](https://linear.app/sourcegraph/project/claude-3-on-gcp-8c014e1a3506/overview)
This PR adds support for completions support for Google Vertex but only for Anthropic based models(NOTE: Gemini and other models don't support completions when used with the google provider). 
Sense of Urgency: This is a P0 because of enterprise requirements so I would appreciate a fast approval and merging. 
- Run this branch for sourcegraph instance  -> https://github.com/sourcegraph/sourcegraph/pull/63282 
- Ask @arafatkatze to dm you the siteadmin config to make things work 
- Check the logs and play with completions

Adding completions to google vertex provider only for anthropic based models

---

lib/shared/src/models/dotcom.ts
vscode/CHANGELOG.md
vscode/src/models/utils.ts
vscode/webviews/components/modelSelectField/ModelSelectField.tsx

CLOSE https://linear.app/sourcegraph/issue/CODY-2177/integrate-new-model
Add Claude 3.5 Sonnet model for Chat and Commands.
Marking it as Recommended as Claude 3.5 Sonnet is better than Opus at all the metrics: https://sourcegraph.slack.com/archives/C05AGQYD528/p1718897456502589?thread_ts=1718896254.676939&cid=C05AGQYD528
Verify the new model is showing up in the model Dropdown list for Chat and Edit:
Verified we are getting response from Cody Gateway using the new model id:

PLG: Claude 3.5 Sonnet model

---

vscode/CHANGELOG.md
vscode/package.json

CLOSE https://linear.app/sourcegraph/issue/CODY-2506/cut-vs-code-release-for-sonnet-35
Just a version bump after the patch release in https://github.com/sourcegraph/cody/pull/4632

VS Code: Patch Release 1.22.4

---

vscode/src/configuration.ts
vscode/src/testutils/mocks.ts

It's a better user experience to wait a bit longer to generate a syntactically whole completion rather than a completion that does not complete the syntactic block. The issue with the latter is both the sense of "incompleteness" but also, we get "stuck" in a more deeply nested block.
| Column 1 | Column 2 |
| --------- | --------- |
|       <img width="522" alt="image" src="https://github.com/sourcegraph/cody/assets/1646931/8bee39ef-458d-42e2-bbda-7a6875af1d60">  |   <img width="738" alt="image" src="https://github.com/sourcegraph/cody/assets/1646931/d814b58f-e55c-4915-a749-4b0310390a08"> |
Tested locally

bump time to first completion up to 2.5 seconds to allow for more syntactically complete code completions

---

vscode/src/chat/clientStateBroadcaster.ts
vscode/test/e2e/chat-atFile.test.ts

Previously, it only debounced the postMessage. Now it debounces the entire operation to get the right selection context. I still see it called 2x for a cursor move (empty selection) and 4x for a non-empty selection due to VS Code calling the event handler multiple times for some reason, but this is a big improvement over before.
Fixes https://linear.app/sourcegraph/issue/CODY-2481/debounce-or-throttle-commandscontextselection-file-calls-to-prevent
Try selections and see how many OT spans get sent (and use logpoints).

debounce selection determination to reduce CPU load

---

agent/scripts/generate-agent-kotlin-bindings.sh

We recently changed the script and it's missing a `git fetch origin` step. Reported here https://github.com/sourcegraph/cody/pull/4583/files#r1648367376
While testing the script locally, I also noticed it was missing a `pnpm install` step in the cody repo.
Run `pnpm generate-agent-kotlin-bindings` and it succeeds

Agent: fix Kotlin bindings script

---

vscode/src/completions/get-inline-completions.ts
vscode/src/completions/logger.test.ts
vscode/src/completions/logger.ts
vscode/src/completions/providers/fetch-and-process-completions.ts
vscode/src/completions/text-processing/process-inline-completions.ts

- Logs resolved model for cached autocomplete items by attaching this value to `InlineCompletionItemWithAnalytics` which is cached, instead of adding it directly to analytics events.
- Fixes the issue with logging cached completion suggestion events. Some of them were not logged because we didn't have a `CompletionLogger.start()` call. This part of the logger is fragile. The type system and existing abstraction don't guard us from making such mistakes. Created [a follow-up issue](https://linear.app/sourcegraph/issue/CODY-2520/[autocomplete-latency]-improve-autocomplete-client-logger-resiliency) to address that.
- Closes https://linear.app/sourcegraph/issue/CODY-2521/[autocomplete-latency]-log-resolved-model-for-cached-autocomplete
- Closes …

Autocomplete: log resolved model for cached results

---

vscode/src/context/openctx/remoteFileSearch.ts

Our search language takes regular expressions as input so we need to escape the user input. Additionally for repository we need to add anchors otherwise we will match all repos that contain another repo name. For example at Sourcegraph we have the deploy-sourcegraph repo as well as many example of deploy-sourcegraph-${target} repos.
Test Plan: remote file search on deploy-sourcegraph only returned filenames for deploy-sourcegraph when signed into s2. Additionally adding "." in the filename selection only selected "." and didn't match any char.
See before and after screenshots
Fixes https://linear.app/sourcegraph/issue/CODY-2265/regex-escape-reponame-and-filepath-for-remote-files-provider

mentions: remote file search regex escapes and anchors inputs

---

lib/shared/src/sourcegraph-api/errors.ts
vscode/src/completions/nodeClient.ts

I was running into a cloudflare issue on s2 when communicating with the LLM. It was quite hard to diagnose since the error message and our logging only contained the response body. This updates SourcegraphNodeCompletionsClient to use NetworkError in the same way our code completions client uses it.
Side-note: it seems like there is a lot of duplication. It seems like there is an opportunity to share code. In particular the code completion client seems well written and more effectively uses instrumentation and error wrapping.
Test Plan: while I could reproduce cloudflare issues I manually tested that the error response shown improved.

vscode: use NetworkError in nodeClient

---

lib/shared/src/prompt/prompt-string.ts
vscode/src/prompt-builder/utils.ts

closes: https://linear.app/sourcegraph/issue/CODY-2509/update-prompt-template-for-openctx-context-items
The current prompt template for all the context items is `Codebase context from file {filePath{inRepo}:\n{languageID}\n{content}`.
For OpenCtx context items such as Linear issues, it doesn't make sense. 
The updated prompt template for OpenCtx items is `Content for "{title}" from {displayPath}:\n{content}`.
manually tested

Update prompt template for openctx context items

---

vscode/src/completions/get-inline-completions.ts
vscode/src/completions/logger.ts
vscode/src/repository/git-metadata-for-editor.ts

This PR make the following changes:
1. Fix the `recordsPrivateMetadataTranscript` in case no private metadata is send to the telemetry. Earlier we were always sending `1` in this fields even if there was no private metadata. More context behind the fix [on the slack thread](https://sourcegraph.slack.com/archives/CN4FC7XT4/p1718914278731939?thread_ts=1718821081.192759&cid=CN4FC7XT4).
2. Adds a `filePath` variable to the logging for only the `dotComUsers` and `publicGitHubRepos`, which indicates for which file the completion was triggered.
3. Adds a `gitUrl` variable for the `dotComUsers` repos. More context on [the slack thread.](https://sourcegraph.slack.com/archives/CN4FC7XT4/p1719001526612899?thread_ts=1716253514.127349&cid=CN4FC7XT4)
**Manual testing**
1. Start the debugger from this …

fixing recordsPrivateMetadata field when the private context is empty

---

cli/src/chat.ts

Fixes CODY-2502
Previously, the experimental cli printed all output to stderr making it cumbersome to pipe the output into other cli tools. The reason for this was that we change `console.log` to become `console.error` when the agent cli starts up. The motivation for this behavior is that the Cody codebase has a lot of `console.log` statements that are used for debugging purposes, and we don't have any linting rules to prevent these statements from getting added.  This PR changes the behavior so that cli uses `process.stdout` explicitly to ensure the cli output goes to stdout. This gives us fine-grained control over what the cli outputs.
Implementation detail: I considered fixing this issue by removing the `console.log` remapping to `console.error` when we run the cli. I'm not 100% …

CLI: print to stdout instead of stderr

---

vscode/webviews/mentions/mentionMenu/MentionMenu.tsx
vscode/webviews/promptEditor/plugins/atMentions/atMentions.tsx

Previously whenever setEditorQuery was called we would replace the @-mention node. However, this lead to the anchor reference for the mention menu to no longer be visible, leading to the position of the mention menu moving to (0, 0).
Note that if you triggered the @-mention menu without typing anything into selection first, this wouldn't call setEditorQuery which is why the behaviour didn't always happen.
Right now all of the text is around your @-mention is a single text node. This meant that our previous naive text manipulation and setting of cursor had several easy to trigger bugs. We make the behaviour more correct now, but not perfect. To be perfect at replacement time and updating time we need to know where the cursor is. The "more correct" is now to do replacement from the end of …

mentions: update text node rather than replace

---

agent/src/cli/cody-bench/cody-bench.ts

When running the tool locally, I noticed that it was hanging after completing the eval run. Probably, what's happening is that there's some background promise that hasn't completed running. I didn't experience this when I originally created the tool so it looks like a regression. This PR "fixes" the problem by calling `process.exit(0)`, which is good enough to unblock usage of the tool
Clone sourcegraph/cody-leaderboard next to the cody repo. Run this from the Cody repo
```
pnpm install
pnpm build
cd agent
pnpm agent:skip-root-build cody-bench --evaluation-config ../../cody-leaderboard/fix-bench.json
```

cody-bench: exit the process after finishing

---

pnpm-lock.yaml

The recent PR folding CLI into the agent package didn't come along with updates to the pnpm-lock.yaml file. I now get this diff when I run pnpm install in the root of the repository.
Test Plan: pnpm i has no diff and CI is happy
See #4653

cli: pnpm lock file changes since move into agent

---

vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx

Before this change we always added @ leading to confusing behaviour such as only filtering for files containing @.
Test Plan: Manually tested clicking the "@" button when the text already has a "@". See video below
https://github.com/sourcegraph/cody/assets/187831/adb5b8a2-be12-4d78-9b7e-9818cb2f0569
Fixes https://linear.app/sourcegraph/issue/CODY-2470/duplicated-mentions-in-cody-chat-in-vscode-unexpectedly-filters-to

mentions: onMentionClick focusses if input already has @

---

vscode/src/editor/vscode-editor.ts

We already have a uri passed in and I am unsure why we converted that into a uri which was just the filepath. I am assuming it was due to code evolution.
In particular this makes it so that cody can understand context from unsaved files.
Test Plan: create a new unsaved file with the word "hello world" in it. Start a cody chat and ask cody about the file. Expect cody mentions hello world in the response. Before this change we got an error.
Fixes https://linear.app/sourcegraph/issue/CODY-2469/a-new-chat-with-an-unsaved-buffer-as-context-shows-an-error

editor: support all uri schemes for getTextEditorContentForFile

---

lib/shared/src/common/range.test.ts
lib/shared/src/common/range.ts
lib/shared/src/index.ts
vscode/src/chat/clientStateBroadcaster.ts
vscode/test/e2e/chat-keyboard-shortcuts.test.ts

For the auto-updating "Current File" context we only made it a "Current Selection" if the selection was multi-line. I am unsure why we had this behaviour, this seems more correct.
I came across this while looking into https://linear.app/sourcegraph/issue/CODY-2276/buggy-line-range-logic-for-open-files-in-new-chat
Test Plan: loads of testing with selecting. See video.
https://github.com/sourcegraph/cody/assets/187831/01ad21d0-6e14-4dfa-a2d2-9485f2cea51b

chat: always use range if there is an active selection

---

agent/src/cli/cody-bench/EvaluationDocument.ts
agent/src/cli/cody-bench/cody-bench.ts
agent/src/cli/cody-bench/evaluateEachFile.ts
agent/src/cli/cody-bench/strategy-chat.ts

Fixes CODY-2548
* Run `pnpm agent:skip-root-build cody-bench --evaluation-config ~/dev/sourcegraph/cody-leaderboard/chat-bench.json`
* Confirm it generates this output here https://github.com/sourcegraph/cody-leaderboard/pull/3

Chat: add infrastructure to run chat evals

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/Constants.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/WebviewMessage.kt
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/clientStateBroadcaster.ts
vscode/src/chat/protocol.ts
vscode/src/context/openctx/remoteRepositorySearch.ts
vscode/webviews/promptEditor/nodes/MentionComponent.tsx

closes: https://linear.app/sourcegraph/issue/CODY-2503/make-mention-chips-link-to-the-uri-on-pressing-cmd-click
This PR makes the mention chips redirect to the item URI when the user presses CMD(mac) + click. 
In case the URI is a file, it opens it in a new tab. Otherwise, it opens the external link in the browser. 
Demo: https://www.loom.com/share/e4e7bd04fe744f4aafac43461a68ea5e?sid=6afa205a-6e66-4232-a25b-80b2ec4fc26d

Make mention chips open links

---

agent/src/cli/cody-bench/strategy-chat.ts

Update to allow files to be optional in ChatTask interface for chat command.
This is because for chat questions, users can submit a question without context.
Related to https://github.com/sourcegraph/cody-leaderboard/pull/7

Bench: allow files to be optional in ChatTask interface

---

agent/src/cli/cody-bench/EvaluationDocument.ts
agent/src/cli/cody-bench/strategy-chat.ts

Add chat question to EvaluationDocument and strategy-chat
Makes it easier to display chat question associated with the file path in leaderboard:
Used by https://github.com/sourcegraph/cody-leaderboard/pull/7

Bench: Add chat question to EvaluationDocument and strategy-chat

---

vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/chat-view/prompt.ts

When running the cody-bench there are lots of events that we are logging when submitting a question:
```
Cody by Sourcegraph: █ SimpleChatPanelProvider:resolveWebviewViewOrPanel: registering webview view/panel
Cody by Sourcegraph: █ SimpleChatPanelProvider: handleInitialized
Cody by Sourcegraph: █ SimpleChatPanelProvider: updateViewConfig
Cody by Sourcegraph: █ telemetry-v2: recordEvent: cody.chat-question/submitted
Cody by Sourcegraph: █ DefaultPrompter.makePrompt: Ignored context due to context limit: user=0, enhanced=0, previous=0
Cody by Sourcegraph: █ telemetry-v2: recordEvent: cody.chat-question/executed
Cody by Sourcegraph: █ SimpleChatPanelProvider: streamAssistantResponse
Cody by Sourcegraph: █ CompletionLogger:onComplete: …
```

Remove redundant loggings

---

vscode/src/completions/logger.ts

Fixes CODY-2571
Enable completions persistence tracking for agent.
Looks like [it was disabled from the start](https://github.com/sourcegraph/cody/pull/1463/files#r1377442685), but I do not see a good reason why it should be.
@valerybugakov you asked a good question but @philipp-spiess answer does not really explain the rationale of the decision to skip the agent. Do you maybe remember any additional context of that decision?
1. Build and run JetBrains with this Cody branch
2. Initiate any completion and accept it
3. Add some code before and after the completion
4. Wait 30 seconds
5. Remove suggested line
6. Wait 1min 30sec
You should see something like that in the log:
```
2024-06-25 15:46:21,885 [  21579]   WARN - #c.s.c.a.CodyAgentClient - Cody by Sourcegraph: █ telemetry-v2: …
```

Enable completion persistence loging in agent

---

web/README.md

When the demo app doesn't load, it could be an invalid token; added instructions to `README.md` for clearing out invalid token.
documentation

Add troubleshooting tip to README.md

---

vscode/test/e2e/command-edit.test.ts

Adds some `nap` calls to make this test more robust
Ran the tests about 10 times and had no failures 
E2E tests

Edit: Make e2e test less flaky

---

agent/src/cli/cody-bench/llm-judge-chat-template.ts
agent/src/cli/cody-bench/llm-judge.ts
agent/src/cli/cody-bench/strategy-chat.ts

- Add `llmJudgeChatTemplate` to generate a prompt for evaluating LLM responses
- Integrate `LlmJudge` into the `evaluateChatStrategy` to score each chat response
- Store the numeric score in the `EvaluationDocument` for each chat response
- Log the total score for the fixture at the end of the evaluation
There are still follow-up works that we can do, including improving the prompt used for the LLM judge, but currently, it works as intended and IMO a good starting point for us to build from.
Currently being used by https://github.com/sourcegraph/cody-leaderboard/pull/8

Bench: add LLM judge for response scoring to chat strategy

---

agent/src/cli/cody-bench/EvaluationDocument.ts
agent/src/cli/cody-bench/SnapshotWriter.ts
agent/src/cli/cody-bench/cody-bench.ts
agent/src/cli/cody-bench/llm-judge-chat-template.ts
agent/src/cli/cody-bench/strategy-chat.ts
vscode/src/extension.node.ts

This PR adds 'hedging' and 'conciseness' checks for Chat benchmarks. The 'conciseness' check uses an LLM to judge repetitiveness.
It also tweaks the main LLM judge score to just focus on helpfulness, and not penalize models for apologizing. This makes the scores less biased, since some models tend to apologize more ("I'm sorry...") instead of using other hedging terms like "Unfortunately...", but otherwise the responses are very similar.
Ran  `pnpm agent:skip-root-build cody-bench --evaluation-config ~/code/cody-leaderboard/chat-bench.json` and checked output.

Bench: add hedging and conciseness scores for Chat

---

vscode/CHANGELOG.md
vscode/src/edit/output/match-indentation.test.ts
vscode/src/edit/output/match-indentation.ts

Fixes the `match-indentation` function on files where there is no detected indentation.
For example, if a user tries to edit a file that just contains "hello", we should not assume the indentation for the file is `0` and then update the incoming response to match that.
> [!NOTE]
> Some files may genuinely have 0 indentation, and this may be correct behaviour. However, it is far more reliable to just assume the LLM has gotten this right here, rather than handle different edge cases.
1. Create a file that just contains "hello" (no indentation)
2. Select all of "hello" and start an edit, e.g. "write a merge sort function"
3. Check that the edit has _some_ indentation, and is not all set to 0 indent

Edit: Fix incorrect indentation for undetected files

---

agent/src/cli/cody-bench/EvaluationDocument.ts
agent/src/cli/cody-bench/strategy-chat.ts

This PR adds a 'question class' column, so we can categorize chat questions during evals.
Also updated Cody leaderboard to expose the question class:

Bench: add class for chat questions

---

agent/src/agent.ts
agent/src/custom-commands.test.ts
vscode/src/commands/services/custom-commands.ts
vscode/src/jsonrpc/agent-protocol.ts

This change adds a new API endpoint `customCommands/list` that allows clients to retrieve a list of available custom commands stored in the local `.cody/commands.json` file. This is used to populate the list of custom commands in the Cody UI acrooss IDEs.
- Adding a new `customCommands/list` request handler in the `Agent` class that calls the `cody.commands.get-custom-commands` command to retrieve the list of custom commands.
- Updating the `agent-protocol.ts` file to define the new `customCommands/list` request type.
- Adding a test in `custom-commands.test.ts` to verify that the `customCommands/list` API returns the expected number of custom commands.
- Implementing the `cody.commands.get-custom-commands` command in the `CustomCommandsManager` class to return the …

Agent: Add custom commands list API

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/CodyAgentServer.kt
agent/src/agent.ts
vscode/src/jsonrpc/agent-protocol.ts

RPC 1:  Added a `textDocument/change` request, so the test can block on the editing operation.
This is the same as `textDocument/didChange` except that it returns a result.
I did not know what kind of meaningful result to return here, so it just returns an object with a `success' boolean that can be extended with more properties.
The reason integration tests need this is that they have no reliable way of knowing when the Agent finishes updating its `AgentWorkspaceDocuments` after a `textDocument/didChange` notification.
- added a `testing/workspaceDocuments` rpc for fetching the agent's current copy of a document, so it can be compared against the client's copy.
- This RPC allows you to specify zero or more uris for which to fetch the corresponding protocol document. Zero means get them …

added some support for client-side integration tests

---

vscode/src/completions/inline-completion-item-provider.ts
vscode/src/services/autocomplete-stage-counter-logger.test.ts
vscode/src/services/autocomplete-stage-counter-logger.ts

- Adds `providerModel` to autocomplete stage counter events.
- Closes https://linear.app/sourcegraph/issue/CODY-2636/[autocomplete-latency]-add-providermodel-to-autocomplete-stage-counter
- Discussed [here](https://sourcegraph.slack.com/archives/C0729T2PBV2/p1719426870642669?thread_ts=1719286653.272099&cid=C0729T2PBV2).
Updated tests

Autocomplete: add `providerModel` to stage counter logger

---

.vscode/launch.json
doc/dev/index.md
vscode/CONTRIBUTING.md

2 people were using the separate instance one that requires signing in each time because they thought it was better. It's not. This helps clarify that.
n/a

add recommended label for the Launch VS Code Extension launch task

---

pnpm-lock.yaml
vscode/package.json
vscode/src/context/openctx.ts
vscode/src/context/openctx/linear-issues.ts
vscode/webviews/mentions/mentionMenu/MentionMenuItem.tsx

This includes a change which makes it possible for javascript OpenCtx providers to use the vscode APIs.
Test Plan: Use the linear-issues provider and get magic integration with Linear Connect VSCode extension.
Stacked on #4701

vscode: upgrade @openctx/vscode-lib to 0.0.13

---

vscode/src/auth/account-menu.ts
vscode/src/chat/utils.ts
vscode/src/services/AuthProvider.ts
vscode/src/services/LocalStorageProvider.ts
vscode/src/services/StatusBar.ts
vscode/webviews/Troubleshooting/ConnectionIssuesPage.tsx

Follow up on https://github.com/sourcegraph/cody/pull/4691#pullrequestreview-2143240367
This PR addresses the linked comment by @sqs :
> it would be great if we made it so that Cody worked without network access in the normal mode, instead of being in a separate offline mode. For example, Cody would start up and start working using the last configured account even before it had logged in again with the server. 
Proposed solution in this PR:
- store the last used username so that we will be able to get the chat history from the last logged-in user 
2. Open Ollama
3. Open Chat and ask Cody a question to verify Cody still works when there is an Internet connection
4. Turn off your Wi-Fi settings
5. Reload VS Code
6. Verify you are seeing the connection issue …

Auth: update Ollama offline mode UI

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/Chat_ExportParams.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/CodyAgentServer.kt
agent/src/agent.ts
vscode/src/jsonrpc/agent-protocol.ts

This PR extends the existing chat/export rpm API in order to be able to query full chat history, not only non-empty chats (standard behaviour). Default behaviour hasn't been changed so this should very safe to merge
- CI is green (test passes)

Extend `chat/export` rpc API (add fullHistory option)

---

agent/CHANGELOG.md
agent/package.json
agent/recordings/cody-chat_103640681/recording.har.yaml
agent/src/cli/__snapshots__/chat.test.ts.snap

Previously, the CLI release failed because the version number in package.json was outdated.
```
Release tag and version in agent/package.json do not match: '0.1.0' vs. '0.0.5b'
```
Cut a new release and see if the CI passes.

CLI: bump package version to v0.1.0

---

pnpm-lock.yaml
vscode/src/extension.common.ts
vscode/src/extension.web.ts
vscode/src/main.ts
web/package.json
web/src/agent/agent.test.ts
web/src/agent/client.ts
web/src/agent/index-db-storage.ts
web/src/agent/shims/fs.ts
web/src/agent/worker.ts

**History note:** This is the second attempt to bring custom storage support for cody web. 
(The first attempt with async storage support is [here](https://github.com/sourcegraph/cody/pull/4714)) 
This is the first PR that comes from the biggest change we did for Cody Web in this main PR https://github.com/sourcegraph/cody/pull/4605
This PR extends the `PlatformContext` API in order to support newly created IndexDB storage.
We have to support index db storage since this is the only storage that can be run within
web-worker freely. (web workers don't support standard browser local storage)
- CI is green
- General manual checks in vs code extension UI
- Check …

Add sync index-db-based storage to cody web package

---

vscode/src/chat/chat-view/ChatHistoryManager.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts

This PR just add notification calls on history items change, this is what Cody Web needs to listen 
in order to update history chat items and chat statuses (new chat, chat with messages, ..etc)
- CI is green

Send history change notification to the client

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/Chat_Web_NewResult.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/CodyAgentServer.kt
agent/src/agent.ts
vscode/src/jsonrpc/agent-protocol.ts

This PR adds a new rpc JSON API to create a new chat and return the newly created chat ID, which is very useful for Cody Web client (waiting for the transcript event might be tricky especially because it event won't be sent if no transcription hasn't been published yet)
Change is safe to merge since it's only web-specific and has no effect on other clients.
- CI is green

Add `chat/web/new` method to rpc JSON API

---

vscode/package.json
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/webviews/App.tsx
vscode/webviews/Chat.story.tsx
vscode/webviews/Chat.tsx
vscode/webviews/chat/Transcript.story.tsx
vscode/webviews/chat/Transcript.test.tsx
vscode/webviews/chat/Transcript.tsx
web/src/App.tsx

https://github.com/sourcegraph/cody/assets/1646931/48ebfc54-ebb2-4039-ac15-c5dc67344f2c
- Adds a button to refresh the chat in the sidebar. Previously, there was no way to reset/clear the state of the chat view in the sidebar
- Adds a button to move the chat session in the sidebar to a new editor panel.
Populating the initial context chips in the chat input depends on some behavior that is only triggered on the first-time render. In order to trigger this, we key the chat input component on the chat session ID, rather than just the array index. so that these components are recreated when the chat session changes on reset. Otherwise, the existing component from the previous session would be reused, and the input would not be populated with the initial context chips on reset. …

Chat: enable sidebar refresh and moving from sidebar to editor

---

biome.json

I had a file that was killing biome inside of the .vscode-test-web directory. This ensures biome doesn't search inside of this directory. Additionally I enabled the vcs ignore integration. However, it seems to ignore nested .gitignore files, so I still needed the vscode-test-web rule.
Test Plan: pnpm biome doesn't make my fan spin on my desktop.

biome: use git ignore file

---

lib/shared/src/cody-ignore/context-filters-provider.ts

- Disables Enterprise Context Filters debug log for unit tests to make the CI output less noisy.
- Discussed [here](https://sourcegraph.slack.com/archives/C05AGQYD528/p1719614138604569).
n/a

Cody Context Filters: disable logs in tests

---

vscode/package.json
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/test/e2e/update-notice.test.ts

Add a button to move chat in an editor panel back into the sidebar:
https://github.com/sourcegraph/cody/assets/1646931/ff1a5b39-a95d-42a2-af8b-189189e407e1
Tested locally. Feature not yet enabled for users.

Enable moving the chat from editor back into the sidebar

---

agent/CHANGELOG.md
agent/package.json
agent/recordings/cody-chat_103640681/recording.har.yaml
agent/src/cli/__snapshots__/chat.test.ts.snap
agent/src/cli/chat.ts
pnpm-lock.yaml

Previously, `npm install -g @sourcergraph/cody-agent` didn't work. This PR fixes the problem
* Includes keytar file in Cody cli npm release
* Uses `peerDependencies` instead of `depenencies` and `devDependencies` so users don't install transitive dependencies
Manually tested by running a local `verdaccio` registry and installing from there.

CLI: Fix npm release

---

vscode/CHANGELOG.md
vscode/webviews/components/modelSelectField/ModelSelectField.tsx

Declutters the model option selectors by using only a single Enterprise documentation CTA.
| - | - |
| ![CleanShot 2024-07-02 at 11 31 02@2x](https://github.com/sourcegraph/cody/assets/153/35b2c258-2245-4df3-8508-d1e4291e0d10) | ![CleanShot 2024-07-02 at 11 30 33@2x](https://github.com/sourcegraph/cody/assets/153/c61a0ce3-3bfd-41b3-8049-fe62460af623) |
Closes https://linear.app/sourcegraph/issue/CODY-2316/combine-chat-model-selector-enterprise-model-options-into-a-single
- CI

Chat: Simplify the Enterprise docs in the model selector

---

vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions-tests/hot-streak.test.ts
vscode/src/completions/providers/hot-streak.ts
vscode/src/testutils/mocks.ts

- Restrict the number of lines we await during hot-streak completion generation to prevent overwhelming inference providers. Based on empirical observations, we'll initially set this limit to five. We can adjust this value later according to the A/B test results.
- Part of https://linear.app/sourcegraph/issue/CODY-2190/[autocomplete-latency]-ab-test-hot-streak
Updated unit tests and verified locally.

Autocomplete: limit the number of hot-streak lines

---

agent/src/certs.ts

`globalAgent.options.ca` was always set to empty array because the function returns _before_ the promise from `loadLinuxCerts()` resolves
Tested locally with print statements, it was not working for me otherwise

fix loading of linux certs for agent

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/MentionQuery.kt
lib/shared/src/common/uri.ts
lib/shared/src/index.ts
lib/shared/src/mentions/query.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
vscode/src/chat/chat-view/ChatManager.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/chat/context/chatContext.ts
vscode/src/editor/active-editor.ts
vscode/src/editor/utils/debounce-promise.ts
vscode/src/editor/utils/editor-context.ts
vscode/webviews/promptEditor/plugins/atMentions/chatContextClient.tsx
web/src/App.tsx
web/src/agent/client.ts

This PR adds support for the remote context items files and symbols. Note that eventually, we will use
open context provides for any remote contexts but for now as a semi-temporary solution for Cody Web 
we include this logic outside the open context providers.
This is safe to merge since it only affects Cody Web package. 
- Check that CI is passing 
- Check cody web demo (`cd web` and `pnpm dev`) and check that you can mention remote files and symbols 
- Check that mentioned files and symbols were included in the prompt …

Cody Web: Add remote context support

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/Chat_DeleteParams.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/CodyAgentServer.kt
agent/src/agent.ts
vscode/src/jsonrpc/agent-protocol.ts

This PR extends agent RPC API in order to delete chats from Cody Web client, currently, it's not used
anywhere in main so it's safe to merge this since it has no effect on other clients.
- Check that CI is passing

[Agent] Add delete chat method to json rpc

---

vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/UploadImageButton.story.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/UploadImageButton.tsx
vscode/webviews/components/modelSelectField/ModelSelectField.module.css
vscode/webviews/components/modelSelectField/ModelSelectField.tsx

@abeatrix some UI changes for image upload:
* New icon, given it only supports image upload (not CSV etc that some other LLM uploads do)
* Button state (and Storybook) for when an image is uploaded, with UI for removing
* Badge in the model selector for showing models that support image upload
https://github.com/sourcegraph/cody/assets/153/41cdb4c0-b08c-4128-96eb-9e080c8f9a71
https://github.com/sourcegraph/cody/assets/153/2e7ab980-c0e6-410c-8caf-adebf47d5868
- CI

Upload image UI

---

vscode/src/services/AuthProviderSimplified.ts

After https://github.com/sourcegraph/sourcegraph/pull/63373, the `/post-sign-up` indirection/redirection is no longer necessary.
Manually test in debug ext host sign out then sign in

remove /post-sign-up needless redirect

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/rateLimitedClient_2043004676/recording.har.yaml
agent/src/index.test.ts
vscode/src/testutils/testing-credentials.ts

- Switches the rate-limited integration tests client to the new testing account.
- Creds can be found in 1Password
- The integration test is disabled because Polly cannot process the request. I spent 1.5 hours digging into Polly's internals to find out why with no success. For some reason, the error message does not propagate to the top level. @olafurpg, is the same issue that you mentioned in `autocomplete/trigger (RateLimitError)` test?
- Documented that the tests are disabled for now here: https://linear.app/sourcegraph/issue/CODY-2623/re-enable-ratelimitedagent-test#comment-0878a16a
Updated tests and creds in 1Password.

Agent: switch rate-limited client account

---

agent/recordings/customCommandsClient_509552979/recording.har.yaml
agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/document-code_965949506/recording.har.yaml
agent/recordings/edit_1541920145/recording.har.yaml
agent/recordings/fix_3001320056/recording.har.yaml
agent/src/AgentWorkspaceConfiguration.ts
vscode/src/configuration.ts

Closes CODY-2346
1. Start JetBrains extension with this branch using `CODY_DIR` param
2. See in debugger that `setHasAuthenticatedBefore` is called instead of `handleFirstEverAuthentication`
3. Check in looker to check that `cody.auth.login:firstEver` event was not fired

Fix telemetry event cody.auth.login:firstEver firing too often in agent

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/CodyIDE.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ConfigParams.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/Constants.kt
agent/src/AgentWorkspaceConfiguration.ts
lib/shared/src/configuration.ts
lib/shared/src/telemetry-v2/TelemetryRecorderProvider.ts
lib/shared/src/telemetry/EventLogger.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts
vscode/src/services/AuthProvider.ts
vscode/src/services/telemetry.ts
web/lib/agent/agent.client.ts

This is one of the PRs that come from the main change PR that I made for Cody Web here: https://github.com/sourcegraph/cody/pull/4605. 
This PR introduces the `cody.web` configuration field that allows running the cody agent 
- Without provided access token 
- Always fetching remote context (not only for sourcegraph.com instance)
This change is safe to merge because it affects only Cody Web package and has no impact 
on any other agent clients
- CI is passing

[Cody Web]: Allow agent auth running without access token

---

.github/workflows/agent-bindings.yml
.github/workflows/agent-release.yml
.github/workflows/e2e-flakiness-detector.yml
.github/workflows/lints.yml
.github/workflows/scip-typescript.yml
.github/workflows/vscode-insiders-release.yml
.github/workflows/vscode-stable-release.yml

The CI has been failing lately with this error
```
 WARN  GET https://registry.npmjs.org/pnpm error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
```
This is an attempt to fix the problem by bumping up pnpm-setup.
Slack https://sourcegraph.slack.com/archives/C05AGQYD528/p1720014583901319
Commit hash taken from https://github.com/pnpm/action-setup/releases
Green CI.

Bump pnpm-setup action

---

vscode/src/non-stop/FixupController.ts
vscode/src/non-stop/FixupDocumentEditObserver.ts
vscode/src/non-stop/codelenses/items.ts
vscode/src/non-stop/codelenses/provider.ts
vscode/src/testutils/mocks.test.ts
vscode/src/testutils/mocks.ts

https://github.com/sourcegraph/cody/assets/9516420/fddd099e-432d-498a-96de-b8fcf40df0f1
This PR:
- Allows opening a full diff via "Open Diff". With additional functionality for reverting specific lines etc.
- Note: We have to "accept" the task when we do this, this is so we don't have have a duplicate diff in this view from the inline diff and the separate diff. We could try to remove the inline-diff when opening this, and re-add when closing it, but that would spam the users' undo/redo stack, and likely lead to bugs keeping everything in sync
- Improves functionality for editing the inline diff like it is just text
1. Make edits
2. Make changes
3. Check decorations
4. "Open Diff"

Edit: Support opening a separate diff and improve diff editing

---

agent/CHANGELOG.md
agent/package.json
agent/src/cli/auth/AuthenticatedAccount.ts
agent/src/cli/auth/command-accounts.ts
agent/src/cli/auth/command-login.ts
agent/src/cli/auth/command-logout.ts
agent/src/cli/auth/messages.ts
agent/src/cli/auth/secrets.ts
agent/src/cli/auth/settings.ts
agent/src/cli/chat.ts
agent/src/esbuild.mjs
pnpm-lock.yaml
vscode/CHANGELOG.md

Previously, we used Keytar to write/read/delete secrets. This was problematic for two reasons:
- Keytar has been unmaintained since 2022
- Keytar required native Node modules that meant `cody-agent` was crashing on macOS when using a release that was built on Linux (in CI)
This PR addresses both problems by replacing keytar with a custom solution that shells out to different secret managers (`security` on macOS, `secret-tool` on Linux, and `powershell` on
Windows). See comment in `secrets.ts` for a more detailed reasoning why
we went with this approach.
Manually tested on macOS/Linux/Windows.

CLI: replace keytar with custom solution

---

lib/shared/src/prompt/prompt-mixin.ts

Simplify the preamble for preventing hedging and verified with the updated data in: https://github.com/sourcegraph/cody-leaderboard/pull/12/commits/88eb291906c6b602e999fa5dcf0d0bd85e96002b

update hedges prevention preamble in prompt-mixin

---

web/lib/components/CodyWebChat.tsx
web/lib/components/CodyWebChatProvider.tsx
web/lib/components/CodyWebHistory.tsx

Based on https://github.com/sourcegraph/cody/pull/4756
Closes [SRCH-632](https://linear.app/sourcegraph/issue/SRCH-632/merge-cody-web-experimental-package-to-the-cody-repo-main-branch)
After this change we will be able to publish Cody Web package from main again.
This PR fixes UI-flash problems when we switch chats or set the initial chat transcript. 
Previously, the CodyWebChat component didn't wait for any restoring event and render
all available transcripts right away, this caused problems when you opened the chat and 
could see how we render empty chat only then render actual transcript UI. 
This PR makes CodyWebChat wait for the actual current chat restoration and fixes the problem 
with flashing. 
**Tech note:** I'm not happy with the current approach with refs and panel and chat …

Cody Web: fix cody web UI flashes problem

---

pnpm-lock.yaml
web/demo/App.module.css
web/demo/App.tsx
web/lib/global-styles/styles.css
web/package.json

This PR prepares things before publishing cody web package to the npm registry. 
- Removes highlight styles since Sourcegraph client already imports these styles
- Clean up package.json dependencies (since this package is self bundled) it should has no common dependencies 
- CI is green

[Cody Web]: Prepare cody web package for publishing

---

vscode/src/edit/input/get-items/model.ts

PR to set Cody logo as fallback provider icon when the provider is not on our list.
Small UI change to match the same behavior we use in the chat dropdown list:
Before
After

Edit: set Cody logo as fallback provider icon

---

vscode/webviews/Chat.tsx
vscode/webviews/components/ScrollDown.tsx
web/lib/components/CodyWebChat.tsx

Fixes https://linear.app/sourcegraph/issue/SRCH-670/fix-scroll-to-bottom-button-for-cody-web
Fixes scroll down button for arbitrary scrollable container 
- Check that the scroll-down button works properly in the VSCode extension
- Check that the scroll-down button works in the cody web demo (`cd web` and `pnpm dev`)

Fix ScrollDown button for cody web case

---

vscode/CHANGELOG.md
vscode/src/completions/request-manager.ts

- Increases the request manager cache size from 50 to 250 to better leverage it because we plan to send more requests in the upcoming A/B tests.
- Closes https://linear.app/sourcegraph/issue/CODY-2750/[autocomplete-latency]-increase-request-manager-cache-size
CI

Autocomplete: increase autocomplete request manager cache size

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/completion-provider-config.ts

- Prep for running two A/B tests in parallel: hot-streak and smart-throttle.
- Closes https://linear.app/sourcegraph/issue/CODY-2751/[autocomplete-latency]-prepare-for-two-parallel-ab-tests
CI

Autocomplete: feature flags for parallel latency A/B tests

---

vscode/CHANGELOG.md
vscode/src/non-stop/FixupController.ts

Small QOL improvement: We don't need the selection to showcase the range, now we have decorations that do the same. And even for clients that don't show decorations, the selection is likely no longer helpful after this point
**Before:**
https://github.com/sourcegraph/cody/assets/9516420/849b5bc1-0507-4938-bd82-5377c8154236
**After**
https://github.com/sourcegraph/cody/assets/9516420/bb4c9473-826d-49e7-977d-20928cb6453f
1. Make edits with selections
2. Expect selection to collapse

Edit: Collapse selections to cursor position after prompt

---

agent/src/cli/scip-codegen/JvmCodegen.ts

Previously, the generator was not emitting the `static` modifier for inner classes resulting in a compile error for Java 11.
Manually verified this fixes compile errors in the Eclipse plugin.

Agent: fix Java bindings bug

---

pnpm-lock.yaml
recordings/vscode/e2e_2083974793/auth-test-ts_1102405082/Pre-Authenticated_3817348620/recording.har.yaml
recordings/vscode/e2e_2083974793/example-test-ts_2069432700/Show-off-v2-features_1731159314/recording.har.yaml
vscode/e2e/auth.test.ts
vscode/e2e/example.test.ts
vscode/e2e/utils/tmpdir.setup.ts
vscode/e2e/utils/vscody/constants.ts
vscode/e2e/utils/vscody/fixture.ts
vscode/e2e/utils/vscody/uix/cody.ts
vscode/package.json
vscode/playwright.v2.config.ts
vscode/src/testutils/CodyPersisterV2.ts
vscode/src/testutils/testing-credentials.ts

Fixes CODY-2727, CODY-2728, CODY-2764, CODY-2735
This is far from the final implementation but it sets up some solid primitives to continue work from.
We now essentially allow the configuration of multiple proxy endpoints. For now there are just two SourceGraph variants but we can effectively have as many proxies as we want (Ollama, FastPath, etc.) Note that the "implementation" of these variants can easily be switched out during a test. This is so that later we can leverage this for debugging by allowing a user to seamlessly switch between production and local variants without invalidating all recorded messages.
For the Sourcegraph proxies we now also have several default Polly handlers setup. For some of those, such as telemetry, we can both send a fixed response as well as record the …

E2E V2: Basic authenticated flow

---

lib/shared/src/sourcegraph-api/completions/browserClient.ts
web/vite.config.ts

`@openctx/vscode-lib` uses global. sets under the hood which breaks Cody Web use case since we're importing vscode-lib within web worker context where we don't have global object. 
This PR adds hack/workaround for Cody Web, proper fix should happen in `@openctx/vscode-lib` here https://github.com/sourcegraph/openctx/issues/169
- Run cody web demo
- Check that you can see and use repositories and files mentions providers

Fix @openctx/vscode-lib initialization for Cody Web

---

vscode/webviews/App.tsx
vscode/webviews/Chat.tsx
vscode/webviews/chat/components/WelcomeMessage.test.tsx
vscode/webviews/chat/components/WelcomeMessage.tsx
vscode/webviews/chat/fixtures.ts
web/lib/components/CodyWebChat.tsx

CLOSE: https://linear.app/sourcegraph/issue/CODY-2291/port-chat-ux-vscode-isms-to-jetbrains
This change adds the IDE information (VSCode or other) to the user account info object. This allows the WelcomeMessage component to conditionally render certain features based on the IDE being used. This is because most of the current welcome messages (`New Chat` and `Config`) only applies to VS Code and not other clients:
- Adding the `ide` property to the `UserAccountInfo` interface in `Chat.tsx`
- Passing the `ide` value from the App component to the Chat component
- Updating the `WelcomeMessage` component to conditionally render the "Start a new chat" feature based on the IDE
Verify the following:
- The New Chat and Settings items in the welcome message should display on VS …

Chat: update welcome message to be IDE based

---

vscode/test/e2e/chat-history.test.ts
vscode/test/e2e/common.ts

- Adds checks to ensure the correct input boxes are visible before filling in the URL and access token fields during the sign-in flow
This attempted some of the failing E2E tests on main where the filling step is performed before the input box has shown up based on the recordings we got from the failed tests.
Example captured from recordings:
1. After we have input the URL:
2. We did not enter the token (because the token step was performed before the input box is ready):
3. This means we weren't able to login for the test:
Example 2:
Green CI.

E2E: ensure input boxes are visible before filling in auth

---

vscode/CHANGELOG.md
vscode/webviews/LoadingPage.module.css
vscode/webviews/LoadingPage.tsx

Minor UI fix: adjust LoadingPage layout to use the full viewport height.

Webview: adjust LoadingPage layout to fill the full viewport height

---

vscode/src/editor/utils/editor-context.ts
web/CHANGELOG.md
web/package.json

Fixes https://linear.app/sourcegraph/issue/SRCH-633/links-in-the-prompt-has-incorrect-url-in-cody-web
This affects only cody web package and has no impact on other clients
- Start a new chat and include files and remote repositories via mentions
- Check that links in the Context list have proper URL

Cody Web: fix cody web remote files link uri

---

vscode/webviews/chat/components/LoadingDots.module.css

CLOSE https://linear.app/sourcegraph/issue/CODY-2792/busy-dots-arent-themed-correctly
- replace hard-coded background-color for LoadingDots
- use input foreground color for loading dots
Start Cody from this branch in debug mode to confirm the loading dots when waiting for Cody's reply are updated when you change editor theme

Chat UI: update loading dots color to adapt to theme

---

vscode/src/completions/client.ts
vscode/src/completions/providers/fireworks.ts

Adds `charCount` to `yield` span events. This would allow us to compare the number of characters received on the client to the number of characters sampled on the Cody Gateway side.
CI

Autocomplete: add char count to `yield` span events

---

vscode/CHANGELOG.md

- Changelog entry for https://github.com/sourcegraph/cody/pull/4804
n/a

Autocomplete: changelog

---

lib/shared/src/completions/types.ts
vscode/CHANGELOG.md
vscode/src/completions/get-current-doc-context.test.ts
vscode/src/completions/get-current-doc-context.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions-tests/hot-streak.test.ts
vscode/src/completions/inline-completion-item-provider-config-singleton.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/text-processing/utils.ts

- We do not account for long documents that hit the document context prefix limit. That causes request manager cache keys to be incorrect for preloaded hot-streak completions. This PR fixes this issue by taking into account `maxPrefixLength`.
- Closes https://linear.app/sourcegraph/issue/CODY-2815/[autocomplete-latency]-fix-cache-keys-for-hot-streak-completions-in
1. Updated unit tests
2. Verified manually in `src/completions/inline-completion-item-provider.ts` by removing code before the `logDebug` in the `logIgnored` function and generating a completion. The first completion should be an if statement and right after it should be the preloaded hot streak completion where we assigned the value to `lasIgnoredUriLogged`. Hot Streak should be enabled: …

Autocomplete: fix hot-streak cache keys for long documents

---

vscode/CHANGELOG.md
vscode/src/completions/providers/fetch-and-process-completions.ts

Added an extra abort call to ensure all requests are canceled when we exit the post-processing stage of the completion generation.
CI

Autocomplete: an extra abort call for API request

---

agent/recordings/defaultClient_631904893/recording.har.yaml
lib/shared/src/guardrails/client.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
vscode/src/chat/chat-view/SimpleChatPanelProvider.ts
vscode/src/commands/execute/ask.ts
vscode/src/commands/services/runner.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/edit/manager.ts
vscode/src/main.ts
vscode/src/models/sync.ts

Here are the changes that make the return type of `ClientConfigSingleton` potentially undefined, and avoids fetching if the user is not authenticated.
Green CI

chore(codyconfig): made CodyClientConfig optional

---

agent/src/agent.ts

- Remove unnecessary logic for determining the default model ID
- We were not using `theModel` value previously
- Set default model ID to empty string if there is no model found as it should be sync again when webview is created
- Simplify the process of deserializing and adding chat messages to the chat model
- Use the provided model ID and chat messages directly to create the chat model
No feature change so CI should be green. The chat/restore test should continues to be green to validate the change.

Agent: Simplify chat model restoration logic

---

vscode/webviews/chat/ChatEnvironmentContext.ts
vscode/webviews/components/MarkdownFromCody.tsx
web/CHANGELOG.md
web/lib/components/CodyWebChat.tsx
web/package.json

Fixes https://linear.app/sourcegraph/issue/SRCH-633/links-in-the-prompt-has-incorrect-url-in-cody-web
Initially, I thought that I fixed problems with links in this PR https://github.com/sourcegraph/cody/pull/4809 but cody can render links in answers too via the markdown component. This PR simply disables vscode deep links when we render chat UI components for Cody Web case. 
Original logic about link building stays untouched, we provide simpler URL transform only for cody web case, safe to merge. 
- Check that markdown links still work properly in vscode exntesion.

Cody Web: Use deep links only in vscode extension

---

lib/shared/src/completions/types.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
lib/shared/src/prompt/prompt-string.ts
vscode/src/completions/get-completion-provider.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/fim-prompt-utils.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/provider.ts
vscode/src/repository/git-metadata-for-editor.ts

These are the changes for the autocomplete experiment. Following are the variant details, along with the hypothesis. (cc: @rishabhmehrotra)
1. `Control`: This is the current production model.
2. `Current-best`: The best model we have on autocomplete till now.
3. `Variant-1 `: DeeSeek-v2 lite base.
4. `Variant-2`: Deepseek Fine-tuned model on stack-dedup.
5. `Variant-3`: CodeQwen 1.5 - 7B
6. `Variant-4`: Deepseek Fine-tuned model trained on symbol context.
Offline evaluation: https://docs.google.com/spreadsheets/d/1i0Hz-Db-_ZKT3xAfjKtwTn2amGjKPBONyPCp4iEdUas/edit#gid=0
Backend PR: https://github.com/sourcegraph/sourcegraph/pull/63702
**Local Testing**
1. Start the debugger and Change my user-id among variants.
2. Observe the payload and model we are triggering for each variant combination.

adding deepseek-v2 and deepseek fine-tuned model for A/B test

---

vscode/src/chat/protocol.ts
vscode/src/release.test.ts
vscode/src/release.ts

CLOSE https://linear.app/sourcegraph/issue/CODY-2832
- Changes the behavior of `getReleaseNotesURLByIDE` to always return the release blog post URL for VS Code.
- Adds a new `getReleaseBlogPostURL` function to construct the release blog post URL based on the version number.
- Updates the unit tests to reflect the new behavior.
Verify clicking on the following options will redirect you to the release blog post instead of github release notes:
- "Release Notes" option in the sidebar 
- Upgraded notification in Chat pop-up
https://github.com/sourcegraph/cody/assets/68532117/b4e8537f-87b6-4598-ae2c-eb4fc877f00b

Sidebar: use release blog post URL for release notes

---

vscode/scripts/validate-package-json.ts

I was trying to do development offline and this step was failing due to it needing internet access to download schema files. Given it is still covered by CI this enables disabling it via the usual OFFLINE environment variable.
Note: I looked a little bit into caching here, but I didn't want to over-engineer. However, it may be useful to do given this step takes 7s for me. It may be faster for you if you live closer to schemastore servers.
Test Plan: ran "pnpm run check:manifest" with and without OFFLINE=1 specified.

skip check:manifest if OFFLINE is set

---

vscode/CHANGELOG.md
vscode/package.json

Removes a no-op command `New Chat in Sidebar` that was added prematurely. (This will be added back with functionality in the next minor stable release version.)
Tested locally

hide "New Chat in Sidebar" command

---

vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatPanelsManager.ts

This PR fixes an issue where submitting a question in sidebar chat view does not display the correct icon associated with the selected model as the model ID was not updated in the ChatModel previously on auth change because the chat provider can only be created when the user is logged in, which is no longer the case for the sidebar chat view.
Changes:
- Update the ChatModel based on the available chat model list for the current user on auth status change.
2. In the sidebar chat, send Cody a question without changing the model
3. Verify the response from Cody is showing the logo associated with the model shown in your model dropdown list.
The response from Cody is not showing the correct logo associated with the model shown in the chat input box. Hovering …

Chat: update chat model selection and default model on auth sync

---

vscode/package.json
vscode/src/commands/execute/auto-edit.ts
vscode/src/commands/index.ts
vscode/src/main.ts
vscode/test/e2e/command-edit.test.ts

proof of concept: a new command that triggers multi-line autocompletes but uses the inline-edit.
Loom: https://www.loom.com/share/eb82aab84d7d423381e6f16d46c3a2e8?sid=660401f3-0388-4cc1-9379-609111c25bf0
Currently behind the `cody.internal.unstable` configuration for internal testing purposes.
2. Enable `cody.internal.unstable` in your VS Code User Settings 
3. Open a file in your editor and place your cursor in a position where you would usually want to trigger multi-line autocompletes
4. Press `Option+Tab` to execute the command
5. Verify the command works as intended

Command: experimental auto-edit command

---

vscode/src/completions/get-inline-completions-tests/analytics.test.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/logger.test.ts
vscode/src/completions/logger.ts
vscode/src/completions/request-manager.test.ts
vscode/src/completions/request-manager.ts

This PR adds fuzzy matching to the autocomplete request manager cache. Fuzzy matching allows for approximate cache key matching, which should increase the cache hit ratio for all autocomplete requests. It should be especially useful for hot streak completions where we pre-generate multiple suggestions upfront. Currently, these completions are discarded if users slightly tweak the suggested code, even by adding a semicolon or an extra space. The fuzzy-matcher fixes this inefficiency. 
- We use the Levenshtein distance to measure the similarity between strings.
- The matching threshold is dynamically adjusted based on the length of the string, allowing for more flexibility with longer strings while maintaining precision for shorter ones.
- The fuzzy matching is applied to multiple previous …

Autocomplete: fuzzy cache matches

---

lib/shared/src/configuration.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/CHANGELOG.md
vscode/package.json
vscode/src/completions/completion-provider-config.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/smart-throttle.test.ts
vscode/src/completions/smart-throttle.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/testutils/mocks.ts

This PR adds an extended version of the smart-throttle, that increases the `THROTTLE_TIMEOUT` from 250 to 500ms. This will help us assess if the additional requests by the smart throttle are causing increased latency. This experiment should result in _fewer_ in-flight requests
1. Enable smart throttle experiment
2. Expect to see in-flight requests and smart abort
3. Also covered by https://github.com/sourcegraph/cody/pull/4735

Autocomplete: Add extended version of smart throttle

---

agent/src/local-e2e/README.md
agent/src/local-e2e/helpers.ts

As I was about to record a loom video showcasing this, I noticed that when the access token is rejected, it wasn't handle as well as it should; which is now fixed. Also adjust the docs a bit. 
Before:
After: 
CI + local

fix(local_e2e): diagnose properly access token issues

---

vscode/CONTRIBUTING.md
vscode/scripts/version-bump.ts

Updating our docs on Stable release after going through them with @jamesmcnamara in the last release.
Also updated the version-bump script to include the release checklist in the release commit message.
docs update.

VS Code: Update release documentation and version bump script

---

vscode/CHANGELOG.md
vscode/package.json

CLOSE https://linear.app/sourcegraph/issue/CODY-2861/vscode-outdated-cody-command-ask-cody-to-explain-throws-error
Current issue:
The command is actually a valid command, but it only works when you highlight some text in your terminal and right click on it:
The command is not expected to show up in the command palette menu, which is now fixed by this PR by setting the when condition to `false` for the command in the menu field.
Confirm the command is still available when you select some text in your terminal and right-click:
Confirm the command is no longer available in the command palette menu:

Command : remove "Ask Cody to Explain" from command palette

---

cli/README.md

The `@sourcegraph/cody` npm package didn't get published because our CI job doesn't have permissions to create npm packages. I am working on resolving the problem. In the meantime, let's revert the changes to the docs.
n/a

CLI: revert changes in docs that mention new npm package

---

vscode/src/completions/inline-completion-item-provider.test.ts

Improves the tests to use the more useful `getInlineCompletions` test helper
Tests only change - CI should pass

Autocomplete: Refactor tests to use getInlineCompletions helper

---

vscode/src/chat/protocol.ts
web/lib/components/CodyWebChat.tsx

- Add a comment to clarify that the default chat model is always the first one in the list
- Refactor chat model update logic to notify the host about manual changes, and let the host return the updated chat models
Green CI, as there should not be any behaviour change.

Web: update chat model handling

---

lib/shared/src/models/index.ts
vscode/webviews/App.tsx

Right now we are limiting FreeUser to use first model only which is incorrect.  Removing the check fixed the issue where non-Cody Pro users are unable to use other free models
Build from this branch and log in to Cody as Cody Free user, try selecting a model
I can select a model that's not 3.5 Sonnet:
Also tried logging in as dotcom pro users to confirm the model selection is working as expected:

Chat: remove isFreeUser model check and simplify model selection

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/CodyIDE.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ConfigParams.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/Constants.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/protocol_generated/ExtensionMessage.kt
agent/src/AgentWorkspaceConfiguration.ts
lib/shared/src/configuration.ts
vscode/webviews/components/MarkdownFromCody.tsx

This change adds support for the Visual Studio IDE in the AgentWorkspaceConfiguration class. A new case has been added to the `getIDE()` method to handle the 'visualstudio' configuration value and return the corresponding CodyIDE.VisualStudio enum value.
Additionally, the CodyIDE enum in the shared configuration.ts file has been updated to include the VisualStudio value.
Green CI as this PR is adding a new value to the enum object that is not being used by other clients yet.
Also there is no feature change.

Agent: add support for Visual Studio IDE in AgentWorkspaceConfiguration

---

lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/rest/client.ts
vscode/src/models/sync.test.ts
vscode/src/models/sync.ts
vscode/src/services/telemetry-v2.ts
web/CHANGELOG.md
web/lib/components/CodyWebChat.tsx
web/package.json

Fixes https://linear.app/sourcegraph/issue/SRCH-732/telemetry-send-extension-related-events-in-cody-web
Also, this PR fixes problems with different `isOldStyleEnterpriseUser` definitions; this field controls LLM selector appearance for enterprise customers, and prior to this PR, it was a bit different compared to the check we have for VSCode Cody extension chat.  
Note that at the moment, there is no enterprise test instance where we can test this locally (since S2 doesn't support server-side models yet), but @jamesmcnamara tested it manually, so this PR pretty much relies on his prior testing. 
- CI is green

Fix cody web telemetry and multiple llm checks

---

agent/src/cli/command-chat.test.ts
agent/src/cli/command-chat.ts

Fixes CODY-2742
Previously, the CLI tried to support `--context-repo` on dotcom accounts even if remote repo context doesn't work on dotcom. This PR changes the behavior to report an error message if the user tries to pass --context-repo with a dotcom account.
Manually tested with
```
❯ pnpm agent chat --context-repo github.com/sourcegraph/cody -m 'what is the agent?'
> @sourcegraph/cody@ agent /Users/olafurpg/dev/sourcegraph/cody
> pnpm -C agent agent "chat" "--context-repo" "github.com/sourcegraph/cody" "-m" "what is the agent?"
> @sourcegraph/cody@0.2.0 agent /Users/olafurpg/dev/sourcegraph/cody/agent
> pnpm run build && node --enable-source-maps dist/index.js "chat" "--context-repo" "github.com/sourcegraph/cody" "-m" "what is the agent?"
> @sourcegraph/cody@0.2.0 build …
```

CLI: only support --context-repo on dotcom accounts

---

agent/src/cli/command-chat.ts

Previously, passing the `--endpoint` or `--access-token` options crashed the CLI tool because it got parsed as a boolean `true`. This PR fixes the problem by adding the correct Commander.js syntax to the option declaration.
Reported https://linear.app/sourcegraph/issue/CODY-2742/-context-repo-is-not-working#comment-a0d5b6b5
Manually tested with
```
❯ pnpm agent chat --context-repo github.com/sourcegraph/cody -m 'what is the agent?' --endpoint ...
```
It no longer crashes with the stack trace
```
at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
at new NodeError (node:internal/errors:405:5)
at new URL (node:internal/url:778:13)
at buildGraphQLUrl (/Users/jan/repos/cody/lib/shared/src/sourcegraph-api/graphql/url.ts:13:22)
at …
```

CLI: fix --endpoint and --access-token options

---

vscode/CHANGELOG.md
vscode/package.json

Patch release with some telemetry improvements for ongoing autocomplete A/B tests.
**Diff:** https://github.com/sourcegraph/cody/compare/vscode-v1.26.2...vscode/1.26.3?expand=1
**Build:** https://github.com/sourcegraph/cody/actions/runs/9957559854
Tested through the PRs:
- https://github.com/sourcegraph/cody/pull/4865
- https://github.com/sourcegraph/cody/pull/4866
Please CI, my test plan is here ^

VS Code: Release 1.26.3

---

agent/package.json
agent/recordings/cody-chat_103640681/recording.har.yaml
agent/src/cli/__snapshots__/command-chat.test.ts.snap
agent/src/cli/codyCliClientName.ts
agent/src/cli/command-chat.test.ts
agent/src/cli/command-chat.ts
agent/src/cli/isNonEmptyArray.ts
vscode/src/testutils/CodyPersister.ts

Fixes CODY-2742
Previously, the `--context-repo` option did not work with the CLI because of two issues:
- The CLI used the client name "cody-cli", which Sourcegraph Enterprise rejects due to a problem that is described in the PR https://github.com/sourcegraph/sourcegraph/pull/63855 To work around this problem, the CLI will use the client name "jetbrains" for time being.
- The `addEnhancedOptions` was set to false in `chat/submitMessage`. We now set this option to `true` when `--context-repo` or `--context-file` is enabled.
See updated test case that fixes the Squirrel test. This change required using S2 credentials instead of dotcom.

CLI: fix enhanced context

---

agent/CHANGELOG.md

We have to bump the version to 5.5.9 to bypass the server checks that will (most likely) be removed in
https://github.com/sourcegraph/sourcegraph/pull/63855
n/a

CLI: release v5.5.9

---

vscode/package.json
vscode/src/chat/chat-view/ChatsController.ts
vscode/webviews/App.tsx

https://github.com/user-attachments/assets/db166dc0-538e-44ca-9760-8416d0d737f8
Enable the user to build some good muscle memory:
* `Alt+L` toggles between chat and editor
* `Alt+Shift+L` creates a new chat session in the chat panel
* `Alt+L` with an editor selection still adds the selection to the current chat context (but it now shows the chat panel if it is hidden)
Tested locally

make alt+l toggle chat, rather than create a new chat

---

lib/shared/src/sourcegraph-api/graphql/client.ts
web/CHANGELOG.md
web/lib/agent/agent.client.ts
web/lib/components/CodyWebChatProvider.tsx
web/package.json

So, with the new `client-config` handler (which is part of REST API), we've got a runtime fail in Cody Web in production. The problem is that the GET request doesn't send the Origin request header (since it's a plain get request), also we don't send custom client headers like 
```
x-requested-with: Sourcegraph
x-sourcegraph-client: https://sourcegraph.sourcegraph.com/
```
because of this lack of request headers this `client-config` fails in a runtime with 401 status. This PR exposes `customHeaders` API for Cody Web components, so consumer components in the Sourcegraph client would be able to set the proper set of headers that we have in `window.context.xhrHeaders`
- This change doesn't change much in cody vs code logic so here we should just make sure that CI is passing 
- Later as this …

Cody Web: Fix client-config request for Cody Web in production

---

agent/src/cli/command-chat.test.ts

I have retried the windows unit test step 3 times on a PR of mine, no luck. I also see this failing on main right now.
CI is green
Part of https://linear.app/sourcegraph/issue/CODY-2912/cli-squirrel-test-failing-on-windows

agent: skip squirrel test on windows

---

vscode/CHANGELOG.md
vscode/src/completions/request-manager.test.ts
vscode/src/completions/request-manager.ts
vscode/src/completions/test-helpers.ts

The current implementation doesn't account for cases where the current line suffix is an empty string. This PR fixes it and updates unit tests. Part of https://linear.app/sourcegraph/issue/CODY-2190/[autocomplete-latency]-ab-test-hot-streak
Updated unit tests.

Autocomplete: fix prefix computation in cache keys

---

agent/src/agent.ts
agent/src/index.test.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/services/AuthProvider.ts

Makes sure we await the this.updateAuthStatus(authStatus) step in this.setAuthStatus(authStatus) during authStatus change to make sure Models are synced accordingly. This fixes the issue introduced by the recent refactor where we have moved the syncModels step into `setAuthStatus` from the authProvider listener. 
Previously, we skip waiting for this.updateAuthStatus(authStatus) in authProvider.setAuthStatus(authStatus) step because we didn't want to wait for the token to be stored inside the local storage.
Green CI - a new unit test is added to an agent to ensure this behaviour is respected in the future.

Auth: fix AuthStatus update handling

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
lib/shared/src/prompt/prompt-mixin.ts
vscode/src/main.ts

Follow up on https://linear.app/sourcegraph/issue/CODY-2507/evaluate-claude-35-sonnet-as-new-default
As mentioned in the linked issue, we were able to verify the context preamble has improved chat quality. This PR is to remove the CodyChatContextPreamble feature flag so that the Context Preamble is always used by default. This also applies to Enterprise users as they do not have access to feature flags.
The CodyChatContextPreamble feature flag has been removed, and the context preamble is now always enabled by default in the PromptMixin. This simplifies the code and removes the need for the feature flag.
BREAKING CHANGE: The CodyChatContextPreamble feature flag has been removed. The context preamble is now always enabled by default when context is used.
Green CI, as all existing features …

Chat: use Context Preamble by default

---

agent/src/agent.ts
agent/src/cli/command-chat.test.ts
agent/src/cli/command-chat.ts
vscode/src/commands/services/custom-commands.ts
vscode/src/extension-client.ts
vscode/src/main.ts
web/lib/agent/agent.client.ts
web/vite.config.ts

Fixes CODY-2945
Previously, the `cody chat` command enabled autocomplete providers even if we don't use autocomplete. This resulted in noisy console logs in errors related to loading autocomplete. This PR fixes the problem by entirely disabling autocomplete from `cody chat`.
Example console output before this PR
Green CI.

CLI: disable autocomplete and clean up logs

---

agent/CHANGELOG.md
agent/package.json
agent/src/cli/command-chat.ts

Fixes CODY-2947
Previously, the CLI would silently continue even if `--context-repo` had a spelling or referenced a repo that doesn't exist on the instance. Now, the CLI fails fast with a helpful error message.
Manually tested.
```
❯ pnpm agent chat --context-repo sourcegraph/cody --context-repo github.com/sourcegraph/jetbrains -m 'what is the agent'
...
✖ The repository sourcegraph/cody does not exist on the instance. The name needs to match exactly the name of the repo as it appears on your Sourcegraph instance. Please check the spelling and try again.
```

CLI: fail fast if `--context-repo` does not have a matching name

---

agent/package.json
lib/shared/src/utils.ts
vscode/src/repository/git-metadata-for-editor.test.ts
vscode/src/repository/git-metadata-for-editor.ts

`config.codebase` is picked up from the workspace root, but it is a Sourcegraph repository name (for example, `github.com/sourcegraph/cody`) not a git remote URL (for example, `https://github.com/sourcegraph/cody.git`.)
This cheesily reformats `config.codebase` to look like a git remote URL. Keeping the real fetch URL instead of making one up would be better, but doing this local rewrite for now to try to ease customer pain in CODY-2846.
Related: sourcegraph/cody#4924
Automated test:
```
pnpm -C vscode test:unit
```
Manual test:
1. Set up sourcegraph/jetbrains
2. `CODY_DIR=/absolute/path/to/cody ./gradlew :runIDE -PforceAgentBuild=true`
3. Open multiple files, some inside a git repository, some outside.
4. Logs with `convertGitCloneURLToCodebaseName` should NOT appear.

When substituting the config.codebase for a git remote name, make it look like one

---

agent/src/cli/command-root.ts

The most common flags for CLI applications to show the current version are --version and -v (lowercase).
This PR makes Cody CLI consistent with that convention.
Run manually
```
❯ pnpm agent -v
...
5.5.10
```

Lowercase the version flag of Cody CLI

---

lib/shared/src/lexicalEditor/editorState.ts
vscode/src/chat/chat-view/ChatController.ts

This approach supersedes the one from #4920 and is more elegant. We reconstruct the editor state at query time and remove all context chips from the text, then use that text for querying context retrievers.
Tested locally - context retriever queries for symf/bfg no longer include repo or @-mentions.

Remove context chips from context retriever queries

---

agent/recordings/autocomplete_2136217965/recording.har.yaml
agent/src/autocomplete.test.ts
lib/shared/src/inferenceClient/misc.ts
vscode/src/completions/client.ts
vscode/src/completions/providers/fireworks.ts

Part of [CODY-2775](https://linear.app/sourcegraph/issue/CODY-2775/%5Bautocomplete-latency%5D-apply-the-same-timeout-on-the-cody-gateway-side)
Sends the `timeoutMs` config value to the backend using via `X-Timeout-Ms` header in both default and fast paths.
Backend support added in https://github.com/sourcegraph/sourcegraph/pull/63875
Manually tested (using a debugger) alongside https://github.com/sourcegraph/sourcegraph/pull/63875 on both default and fast paths, using a locally running Sourcegraph instance and Cody Gateway.

Pass timeoutMs value in the request headers

---

agent/src/vscode-shim.ts

Previously, the name of the workspace in the Eclipse chat UI was "Workspace Root" instead of the basename of the folder like it is in VS Code. This PR fixes the problem.
Fixes CODY-2986
Confirmed that the directory name is now listed in the chat UI, just like in VS Code

Agent: fix name of workspace root

---

vscode/CHANGELOG.md
vscode/package.json

Patch release with https://github.com/sourcegraph/cody/pull/4936.
Changelog and VSCode version are both updated.

VS Code: Release v1.26.5

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/completions/context/retrievers/cached-retriever.ts

Patch release with cherry pick from https://github.com/sourcegraph/cody/pull/4942 to address bug where untitled files were being opened
N/A

VS Code: cherry pick into v1.26.6

---

vscode/package.json

Overlooked this when clause in the last commit that is causing the support sidebar to show up
this PR updates the when clause to match the ones for the commands tree view so that it would work as expected
support sidebar not showing up

fix: support tree view for non-plg users only

---

vscode/CHANGELOG.md
vscode/package.json

PATCH RELEASE for v1.26.6 gogogog
N/A

VS Code: Release v1.26.6

---

vscode/webviews/chat/components/CustomCommandsList.tsx
vscode/webviews/tabs/CommandsTab.tsx

After discussing with kevin, we believe removing the custom commands from the command list would cause discovery issuse. This PR update the Commands tab list Custom Commands if there is any.
- Adds a `CustomCommandsList` component to the `CommandsTab` to display any custom commands the user has defined
- The `CustomCommandsList` is only rendered if there are any custom commands to display
Check if your custom commands are showing up in the commands tab:

Chat UI: add custom commands list

---

lib/shared/src/sourcegraph-api/graphql/url.ts

A recent change brok the urls. This PR reverts the original behaviour.
The recent change: https://github.com/sourcegraph/cody/pull/4706#discussion_r1658684268
Slack thread: https://sourcegraph.slack.com/archives/C05AGQYD528/p1721382757890889
- chat context file items looks properly for remote files

Fix context files urls

---

vscode/CHANGELOG.md
vscode/src/commands/index.ts
vscode/src/non-stop/codelenses/provider.ts

Problem: When there are multiple editor groups open and vscode determines there isn't enough room, if the "open diff" button is clicked, the diff will just open up as another vertical diff, rather than the intended horizontal diff. 
https://github.com/user-attachments/assets/2dae5868-2c6f-4851-9e24-3a7b965cc4a0
This PR checks if multiple editor groups are open, if so, it maximizes the current editor. This guarantees the horizontal diff will open properly.
Video below shows this change( open diff with one editor vs with two editors)
https://github.com/user-attachments/assets/8f9faa51-829e-47dd-a3d4-167f3dadb8bb
- Manual testing with various number of tabs/editors/editor groups/types.
- Ran unit tests - handful failed, but they seem unrelated. Output is attached …

Fix open diff

---

vscode/CHANGELOG.md
vscode/src/completions/context/retrievers/cached-retriever.ts
vscode/src/completions/context/retrievers/jaccard-similarity/jaccard-similarity-retriever.ts

Follow-up for https://github.com/sourcegraph/cody/pull/4942, which causes some autocomplete never to be resolved because we return a pending promise for non-file document URIs in the cached context retriever. This PR changes this behavior by returning a promise resolved with `undefined` in such cases.
CI and manually verified by opening user JSON settings in VS Code alongside "normal" files and forcing autocomplete requests.

Autocomplete: always resolve something on document open calls

---

agent/src/agent.ts
lib/shared/src/models/index.test.ts
lib/shared/src/models/index.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatsController.ts
vscode/src/chat/protocol.ts
vscode/src/chat/utils.test.ts
vscode/src/chat/utils.ts
vscode/src/commands/scm/source-control.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/edit/input/get-input.ts
vscode/src/edit/manager.ts
vscode/src/edit/utils/edit-models.ts
vscode/src/main.ts
vscode/src/models/sync.ts
vscode/src/services/AuthProvider.ts
vscode/src/services/tree-views/TreeViewProvider.test.ts

@abeatrix found a bug with the model defaults when switching accounts. This scopes selections and defaults per endpoint, so that (mostly for us internally) you won't end up submitting a chat with a model that doesn't exist because you've switched accounts.
I also:
* Refactored the cache in ModelsService to make it simpler
* Stored the auth status in ModelsService because we're already calling it on every status update and it simplifies call sites
* Refactored newAuthStatus
Updated unit tests

fixed(models): allow per-site preferences to be configured for ModelsService

---

vscode/CHANGELOG.md
vscode/package.json

Patch release with autocomplete hotfix: https://github.com/sourcegraph/cody/pull/4961
CI, package.json version and changelog ✅

VS Code: Release v1.26.7

---

vscode/package.json
vscode/src/chat/chat-view/ChatsController.ts
vscode/src/main.ts
vscode/src/services/AuthProvider.ts
vscode/test/e2e/attribution.test.ts
vscode/test/e2e/chat-input.test.ts
vscode/test/e2e/chat-rateLimit.test.ts
vscode/test/e2e/initial-context.test.ts
vscode/webviews/chat/components/CustomCommandsList.tsx

- Sets the `cody.isConsumer` context before setting `cody.activated` to avoid flickering
- Moves the `cody.isConsumer` context setting from `ChatsController` to `AuthProvider` to centralize auth status handling
- Also fixed Custom Commands not working when invoked from Custom Commands list
Issue: The non-consumer view / non-chatInSidebar view is displayed before  the sidebar chat is rendered, this is because cody.activated is currently set before cody.isConsumer && cody.chatInSidebar are set:
https://github.com/user-attachments/assets/3c22c044-a61a-4eb2-b1ff-08dbfaed7274
E2E tests are updated
https://github.com/user-attachments/assets/fecd2705-c6b2-4cc3-8074-b04f50f78a59

fix: set cody.chatInSidebar context before cody.activated

---

vscode/src/main.ts
vscode/src/services/AuthProvider.ts

Fix typo made in https://github.com/sourcegraph/cody/pull/4952
Revert the start event check since those are unnecessary.
Green CI since everything should behave the same with the change (as they were unnecessary)

revert chatInSidebar at start

---

vscode/webviews/components/shadcn/ui/collapsible.tsx

Update to show CollapsibleMenu when isOpen is set to true, else, do not show the CollapsibleMenu element at all.
Collapse the Commands / Chat Help menu and confirm the border box is gone

Chat UI: (fix) do not display menu border on hide

---

agent/package.json
agent/src/cli/command-bench/command-bench.ts
pnpm-lock.yaml

Closes CODY-2707.
In the agent dir, run:
`rm ../pnpm-lock.yaml`
Then:
`pnpm install`
The previous warnings seen as CODY-2707 should have disappeared.

Update glob in agent (sourcegraph/cody CLI)

---

cli/README.md

Previously, the docs for the CLI lived in a readme in the `cli/` sub-directory. I've seen several customers link to this page. This PR updates these docs to link to the new docs at https://sourcegraph.com/docs/cody/clients/install-cli
n/a

CLI: link to new documentation

---

vscode/src/commands/index.ts

This Cody Command has `''` instead of ``` `` ```, so the `osIcon` is not expanded.
N/A

fix: use backticks for correct string template syntax

---

vscode/webviews/themes/jetbrains.css

Fix the keybinding label border and background color for jb
Currently showing up with border but no background color 
TBC as the latest jb branch is not working for me.

JB: Update keybindingLabel color

---

lib/shared/src/sourcegraph-api/graphql/client.ts
vscode/src/services/AuthProvider.ts

The EHOSTUNREACH error was misleading, since we only know the request timed out and not that the host was unreachable. I believe we used EHOSTUNREACH since the original thing we where debugging was unexpected behaviour when using a proxy. This was introduced in https://github.com/sourcegraph/cody/pull/4243
ETIMEDOUT isn't exactly correct since we aren't getting a TCP layer timeout. However, I am using the errno approach so the isNetworkError code still works.
Note: the autocomplete code uses specific error types to encode these behaviours which we should switch to. However, that is a bigger change and I wasn't sure how it would work given the RPC stuff between extension worker, webview, etc.
Test Plan: CI
Part of CODY-2959

graphql: use ETIMEDOUT for request timeouts

---

vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/create-provider.ts

- Fixes the issue when enterprise instances use the non-deployed Anthropic model as a default value. Now we set the default Anthropic model only for DotCom users and only in cases where the autocomplete provider is set to Anthropic in local settings. It keeps [the original issue](https://github.com/sourcegraph/cody/issues/4639) fixed and also addresses the enterprise problem.
- Slack investigation [here](https://sourcegraph.slack.com/archives/C07CVL78MDF/p1721694416152009).
- Follow-up issues:
- Write unit/integration tests for `ModelsService` and autocomplete: https://linear.app/sourcegraph/issue/CODY-3030/write-test-for-modelsservice-usage-with-autocomplete-on-the-client
- Update terminology by removing multiple entities named `provider`: …

Autocomplete: set the default anthropic model only for certain cases

---

vscode/webviews/chat/ChatMessageContent.module.css

CLOSE https://linear.app/sourcegraph/issue/CODY-3023/bug-code-markdown-in-chat-has-wrong-spacing
Change the overflow property of pre elements in chat messages from 'scroll' to 'auto' to improve the user experience. This modification allows the browser to determine when scrollbars are necessary, potentially reducing visual clutter when the content doesn't require scrolling.
Scroll bar will only show up if needed, and there is no weird spacing when scroll bar is not needed:
There is a weird spacing on the left and bottom of the code snippet:

Chat: fix overflow property for pre elements in chat messages

---

vscode/src/main.ts

CLOSE https://linear.app/sourcegraph/issue/CODY-3007/new-sidebar-ui-does-not-get-picked-up-on-extension-reload
Add a condition to check if `newSidebarChatUI_isReloaded` has been set before or not.
If not, reload the window to ensure the new webview is registered before the extension host is activated. 
After discussing with @kalanchan and @vovakulikov , we think this is a better approach than showing the CTA to ask users to reload without knowing if the user has reloaded or not.
Green CI - The extension should not be affected by this change and work as expected.

VS Code: Reload window on first activation event 

---

vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatsController.ts
vscode/src/chat/chat-view/ContextFetcher.ts
vscode/src/chat/chat-view/context.ts
vscode/src/main.ts

This change introduces an internal flag `cody.internal.serverSideContext` to toggle on using the server-side context API. Without this flag, behavior is unchanged.
Code-structure-wise, this factors out all context fetching into the `ChatController.fetchContext` method, which includes both the legacy and new server-side context, the latter of which is contained in the new `ContextFetcher` class. This should help ease the transition.
The flagged new `unsafe_` invocation is just a relocation of an existing call.
Behavior is unchanged. Test locally.

Introduce server-side context behind feature flag

---

vscode/webviews/chat/components/GenerateUnitTestsButton.tsx

For the experimental generate unit test button, this adds a tooltip with:
- what it is
- a clickable link to Slack
- how to disable
It also updates the muted label to point out it's internal only for now.
Future ideal: move it into the standard Command List, as it's quite intrusively placed where it is now.
- CI
- N/A — internal only

Clarify experimental Generate Unit Test command

---

lib/shared/src/lexicalEditor/editorState.test.ts
lib/shared/src/lexicalEditor/fixtures.ts
vscode/src/commands/execute/test-chat-experimental.ts

This makes it easier to read.
Test Plan: click the generate unit test button and view it in storybook.

noodle: new lines in the generate unit test prompt template

---

vscode/webviews/promptEditor/nodes/TemplateInputComponent.tsx
vscode/webviews/promptEditor/nodes/TemplateInputNode.tsx

Minor change I had in a stash. We should just pass in the editor we are given rather than relying on useLexicalComposerContext.
Additionally removed unused TemplateInputState.
Test Plan: viewed the generate unit test fixture in storybook

chat: pass in editor to TemplateInputNode

---

vscode/src/commands/index.ts

This change adds a `requires` property to the `CodyCommandMenuItems` configuration for the `cody.command.auto-edit` command. The `requires` property specifies that the `cody.internal.unstable` setting must be enabled for this command to be available.
This ensures that the auto-edit command is only accessible when the user has opted-in to using unstable Cody features.
Auto Edit doesn't show up for enterprise users if they don't have the config enabled

Command: add requires setting for auto-edit command

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ExtensionConfiguration.kt
agent/src/AgentWorkspaceConfiguration.ts
lib/shared/src/configuration.ts
lib/shared/src/index.ts
lib/shared/src/telemetry-v2/TelemetryRecorderProvider.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/jsonrpc/agent-protocol.ts
vscode/src/services/telemetry-v2.ts
vscode/src/uninstall/serializeConfig.ts
web/CHANGELOG.md
web/demo/App.tsx
web/lib/agent/agent.client.ts
web/lib/components/CodyWebChatProvider.tsx
web/package.json

Closes https://linear.app/sourcegraph/issue/SRCH-568/create-telemetry-spec-or-look-at-usage-numbers-for-usage-of-cody-in
This PR exposes a custom telemetry client API so consumers of the Cody Web (Sourcegraph client) would be able to set this name directly, it's needed because we should make Cody Web send events with the same clients in which we're running it, (on dotcom it would be `dotcom.web` on enterprise instance it would be `server.web`)
- Run code web demo and check that events have `testing.cody` client name in event's metadata

Cody Web: Allow to set custom telemetry client name

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/CompletionBookkeepingEvent.kt
vscode/CHANGELOG.md
vscode/src/completions/get-inline-completions-tests/analytics.test.ts
vscode/src/completions/inline-completion-item-provider-e2e.test.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/logger.test.ts
vscode/src/completions/logger.ts
vscode/src/completions/suggested-autocomplete-items-cache.ts

This PR fixes an issue where we would incorrectly log a suggestion as "suggested" even though it wasn't actually suggested by our intended criteria.
When we determine a completion is visible, we currently "chuck it over the fence" to the completion logger, and assume it is still visible after 750ms. There are some cases where that might not happen, for example if the user triggers a new completion, or deletes some characters then we explicitly will not log it. However we did not handle if the user moves their cursor away from the completion, or leaves the document _before_ those 750ms have passed. In those cases the completion will certainly not be visible in VS Code, but will be marked as visible in our analytics.
Example of how this can happen:
1. Cody generates a completion
2. We …

Autocomplete: Check completions are _still_ visible before logging them as suggested and `read`

---

lib/shared/src/configuration.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/package.json
vscode/src/completions/completion-provider-config.ts
vscode/src/completions/get-inline-completions-tests/hot-streak.test.ts
vscode/src/completions/inline-completion-item-provider-e2e.test.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/smart-throttle.test.ts
vscode/src/completions/smart-throttle.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/testutils/mocks.ts

This PR enables the `hot-streak` and `smart-throttle` experiments together.
This is under a new feature flag:
`cody-autocomplete-hot-streak-and-smart-throttle`
1. Enable the setting for this
2. Check that hot streak and smart throttle are enabled
3. Enable the flag for this
4. Check hot streak and smart throttle are enabled

Autocomplete: Merge the `smart-throttle` and `hot-streak` experiments

---

vscode/package.json

Typo
1. Enable setting
2. Check smart throttle and hot streak are actually enabled

Autocomplete: Fix typo in setting

---

web/demo/App.tsx

Previously, you could only use https://sourcegraph.com. Now you can set a different endpoint in localStorage:
```
localStorage.setItem('serverEndpoint', 'https://sourcegraph.test:3443')
```
This makes it possible to use the Cody Web demo against localhost for local dev, for example.
CI

support using a different endpoint in the Cody Web demo

---

lib/shared/src/index.ts
lib/shared/src/misc/rpc/proxy.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/context/chatContext.ts
vscode/src/edit/input/get-matching-context.ts
vscode/webviews/AppWrapper.tsx
vscode/webviews/index.tsx
vscode/webviews/minion/MinionApp.story.tsx
vscode/webviews/minion/MinionApp.tsx
vscode/webviews/promptEditor/plugins/atMentions/chatContextClient.test.tsx
vscode/webviews/promptEditor/plugins/atMentions/chatContextClient.tsx
vscode/webviews/promptEditor/plugins/atMentions/fixtures.ts
vscode/webviews/storybook/VSCodeStoryDecorator.tsx
vscode/webviews/utils/VSCodeApi.ts
web/lib/components/CodyWebChat.tsx
web/lib/components/CodyWebChatProvider.tsx

This is a useful pattern that we use for fetching @-mention context. This helper makes it easy to add more. In the future we can adopt a real RPC protocol for exthost<->webview communication, and this helper will make that eventuality easier.
e2e tests. Also try a lot of @-mentions in chat and see if any behavior changes.

helper for webview to call extension (ChatController) API and get a result

---

vscode/src/local-context/utils.ts

Adds a check for when the stream closes before finishing. This ensures that if the stream closes unexpectedly, an error is thrown, improving error detection and handling in the file download process.
Related to CODY-3057 and user reported https://github.com/sourcegraph/cody/issues/5000
In our current e2e testing setup it's hard to control exact network timings. I'll be adding additional test in the e2ev2 setup which allows much more granular network control.
For now I've manually verified that by abruptly destroying the stream does indeed resolve the promise.

VSCode: Handle improperly aborted bfg/symf download

---

vscode/src/chat/chat-view/ChatController.ts
vscode/test/e2e/attribution.test.ts

Previously we do not update the value for attributions in webview on auth change, so when we updated the test to use sidebar chat instead of panel chat, the test for attributions failed.
Green CI.

Guardrails: update webview on auth change

---

lib/shared/src/configuration.ts
lib/shared/src/guardrails/client.ts
lib/shared/src/index.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/external-services.ts
vscode/src/testutils/mocks.ts

We are currently experiencing long response times from guardrails servers. We have a hardcoded timeout of 10s. Until the issue is resolved we want to provide a way to workaround the timeout. It is marked experimental since I don't expect this setting to remain in the config forever. Instead when we invest more in the guardrails product I would expect this to live server side (along with other parts of the configuration for it).
Note the configuration key is "cody.experimental.guardrailsTimeoutSeconds"
Test Plan: hardcoded guardrails on to test against s2. Then configured the following and tested guardrails by asking chat to generate a sort implementation of more than 10 lines:
- unconfigured :: default timeout of 10s used
- 0.1 timeout :: timed out
- 40 :: no timeout
Context in …

guardrails: experimental configuration of timeouts

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ExtensionMessage.kt
lib/shared/src/sourcegraph-api/graphql/queries.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/protocol.ts
vscode/webviews/App.tsx
vscode/webviews/utils/useFeatureFlags.tsx
web/lib/components/CodyWebChat.tsx

This is not used by anything yet, but it will be used by the impending PR #4903 for the prompt selector (using the prompts in the prompt library).
Run in vscode and web and console.log the values.

useFeatureFlag hook for getting feature flag value in webview

---

vscode/webviews/App.tsx
vscode/webviews/AppWrapper.tsx
vscode/webviews/index.tsx
vscode/webviews/storybook/VSCodeStoryDecorator.tsx
vscode/webviews/utils/composeWrappers.tsx
web/lib/components/CodyWebChat.tsx
web/lib/components/CodyWebChatProvider.tsx

This makes it easier to add new React context or other wrappers without making the JSX tree even more deeply nested. It also eliminates duplication.
CI, `pnpm -C web dev`

extract React context/wrapper components

---

lib/shared/src/index.ts

With an error about `./guardrails/client.ts` not having a `GuardrailsClientConfig` export.
CI

fix lack of type import that broke storybooks

---

agent/CHANGELOG.md
agent/package.json
agent/src/cli/__snapshots__/command-chat.test.ts.snap
agent/src/cli/command-chat.test.ts
agent/src/cli/command-chat.ts
agent/src/vscode-shim.ts

Previously, the `--show-context` option in the `cody chat` command didn't actually print out context. This PR fixes the issue for both local files and remote repo files.
See updated test case for `--context-file`. I manually tested it works with `--context-repo` because the test case is skipped due to [CODY-2960 : Re-enable `--context-repo` integration test](https://linear.app/sourcegraph/issue/CODY-2960/re-enable-context-repo-integration-test)

CLI: fix bug in `--show-context`

---

vscode/package.json
vscode/webviews/tabs/TabsBar.tsx

CLOSE https://www.figma.com/design/f078wFMKsIOaEwj7Iwj5xy/Unified-Cody?node-id=2798-35343&t=ZxGguMkLYWrDAm7f-0
add button for Move (sidebar chat) to Editor from editor menu to sidebar chat tab bar for unified cody: https://www.figma.com/design/f078wFMKsIOaEwj7Iwj5xy/Unified-Cody?node-id=2798-35343&t=ZxGguMkLYWrDAm7f-0
After:

Chat UI: add button for Move to Editor

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/CHANGELOG.md
vscode/package.json
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatsController.ts
vscode/src/commands/CommandsController.ts
vscode/src/commands/services/custom-commands.ts
vscode/src/commands/services/provider.ts
vscode/src/main.ts
vscode/src/services/AuthProvider.ts
vscode/test/e2e/chat-history.test.ts
vscode/test/e2e/chat-keyboard-shortcuts.test.ts
vscode/test/e2e/helpers.ts
vscode/webviews/App.tsx

CLOSE https://linear.app/sourcegraph/issue/CODY-3075/vs-code-enterprise
This PR updates the chat experience for everyone to start with Sidebar chat that is currently available to PLG users only.
- Remove all the tree view registrations events.
- Remove all the constrain that start sidebar chats for DotCom users only.
- Update E2E tests to run in sidebar views and editor views for keyboard shortcut test.
- The rest of the chat behavior should stay the same.
- Sign into S2 and confirm you no longer see the old chat experience that render tree views for commands, support and chat history.
- Verify the sidebar starts at Chat view
Green CI since no features should be changed by this PR, and everything should work as currently do.
Default to sidebar chat for both Enterprise and non-Enterprise …

Chat: Default to sidebar chat and remove tree views registrations.

---

lib/shared/src/context/openctx/context.ts
lib/shared/src/index.ts
package.json
pnpm-lock.yaml
vscode/package.json
vscode/src/chat/chat-view/ChatController.ts
web/package.json

This PR is a follow-up of https://github.com/sourcegraph/openctx/pull/178. 
When a chat message is submitted, it calls the OpenCtx providers with matching selectors to get context items and include them in the context. 
Include the Hello World OpenCtx provider:  "https://openctx.org/npm/@openctx/provider-hello-world": true
Send any message in chat, there should be a openctx context item in the list. 
- Cody will now bring in context from OpenCtx providers for a chat message on submission.

Consume context from OpenCtx for chat message based on selectors

---

vscode/CHANGELOG.md
vscode/src/completions/get-inline-completions-tests/streaming.test.ts
vscode/src/completions/providers/fetch-and-process-completions.ts
vscode/src/completions/text-processing/utils.ts

Ignore leading empty new lines for autocomplete suggestions to reduce the number of cases when Cody doesn't suggest anything. Example use case below:
```ts
class Something {
private one = 1
private two = 2
█
private three = 3
█
private four = 4
█
}
```
- Closes https://linear.app/sourcegraph/issue/CODY-3060/[autocomplete-latency]-start-completion-detection-in-the-chars-stream
- Follow up for https://github.com/sourcegraph/cody/pull/4901
Update unit tests, CI, and manually tested.

Autocomplete: ignore leading empty leading lines

---

lib/prompt-editor/src/plugins/atMentions/atMentions.tsx

Fixes https://linear.app/sourcegraph/issue/SRCH-805/mention-menu-in-narrow-sidebar-chat-causes-erroneous-h-scrolling
In narrow sidebar, type @ and open menu a lot of times. Confirm no h-scroll.

fix h-scrolling in @-mention menu on narrow screens

---

agent/src/cli/command-bench/llm-judge.ts
agent/src/cli/command-bench/strategy-chat.ts

Due to some recent changes in ModelsService, the API whose usages were removed here wasn't returning any results when run inside cody-bench. Turns out we don't need them at all.
I also upgraded the LLM judge to the latest Claude 3.5 Sonnet. I know this will cause some changes in eval results, but we probably always want the best possible model as the judge.

Make cody-bench chat work again after ModelsService changes + upgrade LLM judge model

---

agent/src/cli/command-chat.test.ts

This test is failing in CI.
Green Windows CI

CLI: skip permanently failing test case on Windows

---

lib/shared/src/index.ts
lib/shared/src/sourcegraph-api/rest/client.ts
vscode/src/models/sync.ts
web/CHANGELOG.md
web/package.json

Fixes https://linear.app/sourcegraph/issue/SRCH-801/supported-llm-rest-api-handler-fails-in-cody-web-client
This PR passes client custom headers to the rest API client to make it work on Cody Web side with Sourcegrph client. 
- At this point, we just need to ensure that CI is passing 
- For full testing, you should 
- build cody web `cd web` and `pnpm build`
- link it with `pnpm link --global` running from web directory 
- go to the sourcegraph repo and update the package.json `cody-web-experimental` package to `0.2.9` version
- run sg start web-standalone with `SOURCEGRAPH_API_URL: https://sg02.sourcegraphcloud.com` (the staging where we have remote LLMs enabled)
- Go to the Cody Web page and check that `.api/modelconfig/supported-models.json` call has custom client request headers like …

Pass custom headers to rest API client

---

vscode/webviews/Chat.tsx
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/contextCell/ContextCell.tsx
vscode/webviews/chat/cells/messageCell/assistant/AssistantMessageCell.tsx
vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx
web/CHANGELOG.md
web/lib/components/CodyWebChatProvider.tsx
web/package.json

Attempt to fix https://linear.app/sourcegraph/issue/SRCH-724/prinova-found-an-issue-on-cody-web
The problem that some customers have is somewhere in the react rendering pipeline, I couldn't reproduce this problem from the issue on my machine but I noticed that even though we have `useCallback` and `useMemo` hooks in high-level components we still don't use memoization on components level for anything, this means that the whole chate (all messages) would be re-rendered if one of messages has been changed (by re-rendering I mean react reconciliation). 
This PR 
- Removes props drilling from high-level components (it's easy to track dependencies graph when we don't spread the whole props object to each component)
- Adds `memo()` wrappers for heavy UI components such as transcript …

Cody Web: Add high-level memoization for chat/transcript UI

---

vscode/webviews/components/modelSelectField/ModelSelectField.tsx

[CODY-3084](https://linear.app/sourcegraph/issue/CODY-3084)
Removes a less-than-useful link for enterprise users in the LLM dropdown.
Manually tested.
* Removed "Enterprise Model Options" link in the LLM dropdown for enterprise clients

changed(model dropdown): removed enterprise-model options link for enterprise users

---

vscode/src/chat/chat-view/ChatController.ts
web/CHANGELOG.md
web/README.md
web/lib/components/CodyWebChat.tsx
web/package.json

At the moment, I think we recently did some work around adding the `useFeatureFlag` hook. 
Cody Controller was sending the `setConfigFeatures` event too early before we init in Cody Web component, and because of this we render transcript UI with no feature flag info and hence `useFeatureFlag ` was failing with `useFeatureFlags must be used within a FeatureFlagsProvider`
This PR simply adds `setConfigFeatures` to the ready event handler so it would be sent after Chat UI is ready. 
Also, in this PR I changed the name of the cody web package to make it more standard and move out of my personal NPM account to sourcegraph organization. 
- Run Cody Web demo `cd web & pnpm dev`
- Open Dev tools and remove all tables in your IndexDB for the demo domain
- Refresh the page
- You should see chat UI …

Cody Web: Fixes config features event

---

lib/prompt-editor/src/mentions/mentionMenu/useMentionMenuData.ts
vscode/test/e2e/chat-atFile.test.ts
vscode/test/e2e/common.ts

closes: https://linear.app/sourcegraph/issue/SRCH-775/debounce-requests-for-openctx-providers
There is no debounce for @-mention query input, which causes a continuous search for context items and telemetry event requests for every keystroke. 
This PR adds a 300ms debounce which reduces the redundant requests by many folds. 
- cd web
- pnpm dev
- play with @-mentions and check for API calls in network tab. They should not be triggered for every keystroke when you type quickly. 
- Added a 300ms debounce for at-mention query input.

Add 300ms debounce for at-mention query input

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/CodyAgentServer.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/EditCommands_CodeParams.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/EditTask.kt
agent/src/AgentFixupControls.ts
agent/src/TestClient.ts
agent/src/agent.ts
agent/src/edit.test.ts
vscode/src/edit/input/get-input.ts
vscode/src/jsonrpc/agent-protocol.ts
vscode/src/non-stop/FixupController.ts
vscode/src/non-stop/codelenses/items.ts
vscode/src/non-stop/roles.ts
vscode/src/non-stop/strategies.ts

Fixes CODY-2802
1. Added support for receiving lenses notifications through agent (plus some fixes for tests)
2. Added two new endpoints: `editTask/getTaskDetails` and `editTask/retry`
Full manual QA together with [corresponding JetBrainsPR](https://github.com/sourcegraph/jetbrains/pull/1955)

Add lenses and edit retry support to agent

---

lib/prompt-editor/src/mentions/mentionMenu/useMentionMenuData.test.tsx
lib/prompt-editor/src/mentions/mentionMenu/useMentionMenuData.ts

In the chat @-mention menu, often the current file was shown twice: once at the top because it's part of initial context, and once below because it's an open tab. This caused a glitch where it would be highlighted in 2 places in the mention menu and would prevent navigating down with the arrow key. Now it's only shown once.
Fix https://linear.app/sourcegraph/issue/CODY-2749/mention-menu-glitches-when-you-try-to-navigate-with-the-updown-arrows
Open mention menu and confirm only shown once.
- Fixes a bug where the same file was sometimes shown twice in the @-mention menu, causing a glitch in arrow-key navigation.

don't show file 2x in mention menu

---

agent/src/index.test.ts

This PR reverts the changes to `index.test.ts` from the PR https://github.com/sourcegraph/cody/pull/4911
The command `pnpm run test agent/src/index.test.ts` does not pass for me locally after that PR got merged. Removing the updated assertions makes the tests pass again. The `index.test.ts` file is problematic because it tests some cases where there are dependencies between the tests. I've been slowly grinding through moving most of the tests out of this file with the eventual goal of ideally removing it. We should not add new assertions or test cases to this file.
Green CI.

Agent: get `index.test.ts` passing locally

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/scripts/export-cody-http-recording-tokens.sh
agent/src/index.test.ts
vscode/src/chat/chat-view/ChatController.ts

It is still added if addEnhancedContext is true to preserve the behavior for older non-webview clients for backcompat.
fix https://linear.app/sourcegraph/issue/SRCH-819/duplicate-context-entries-appearing-when-only-using-the-selection
fix https://linear.app/sourcegraph/issue/CODY-1972/file-selection-is-included-as-context-even-if-the-user-deletes-it
Open editor. Select code. Run chat. Ensure selection is not duplicated. Now run chat without a selection @-mention. Ensure there is no selection used in the context.

don't implicitly or duplicatively add user selection in chat context

---

.vscode/launch.json
.vscode/tasks.json

This helps debug Agent during Windows development.
Manual test: In VSCode on Windows, pick the "Launch Agent port 3113" launch configuration and hit Play.

Make the Agent debugging launch configuration work on Windows.

---

pnpm-lock.yaml
vscode/CHANGELOG.md
vscode/package.json
vscode/src/non-stop/line-diff.ts

Fixes an issue where we would generate incorrect diffs due to trailing CR characters in the users' selected code, and this not being matched by the response from the LLM.
1. Enable end of line sequence CRLF (e.g. in VS Code)
2. Start an edit
3. Check that the diff only shows what changed

Edit: Strip trailing CR characters when computing diff

---

lib/shared/src/prompt/prompt-mixin.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/prompt.ts
vscode/src/chat/protocol.ts
vscode/src/services/utils/codeblock-action-tracker.ts
vscode/webviews/Chat.tsx
vscode/webviews/chat/ChatMessageContent.module.css
vscode/webviews/chat/ChatMessageContent.tsx

- Updates preamble to have LLM include file name for each code snippets in responses
- Displays full file name for each code snippet when available
This enables smart apply to work beyond current opened file.
- Ask cody to produce some code and verify the file name shows up at the bottom of the code blocks
- Click smartapply should apply those code snippets to the associated file

Chat: Show file name for code snippets 

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/CodyAgentClient.kt
agent/src/TestClient.ts
agent/src/agent.ts
agent/src/vscode-shim.ts
vscode/src/extension-client.ts
vscode/src/jsonrpc/agent-protocol.ts
vscode/src/non-stop/FixupController.ts

Closes https://linear.app/sourcegraph/issue/CODY-2004/bug-cody-recreates-the-file-that-was-created-by-generate-unit-tests
Some IDEs (maybe even most IDEs except VSC) does not have notion of unsaved files.
Keeping two different models in IDE and in the agent is problematic and leads to hard to track errors.
It is easier to let client be honest and notify agent about real protocol which it is using (most likely `file://` instead of `untitled://`).
As a result that change slightly modifies behaviour of the `openTextDocument`. 
One could now call `openTextDocument` with `untitled://abc` parameter, and as a result get a `TextDocument` which uri points to `file://abc` (or any other path, really).
1. Build [JetBrains branch ](https://github.com/sourcegraph/jetbrains/pull/1903)with this PR using …

Allow clients to redefine untitled files protocol during their creation

---

vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ContextFetcher.ts
vscode/src/chat/chat-view/context.test.ts
vscode/src/chat/chat-view/context.ts
vscode/src/external-services.ts
vscode/src/local-context/download-symf.ts
vscode/src/local-context/symf.ts
vscode/src/main.ts
vscode/src/repository/git-extension-api.ts

This modifies behavior when the `cody.internal.serverSideContext` setting is true. If this setting is not set, there should be no behavior changes.
- Remote context is fetched from Sourcegraph, the latest HEAD revision of the repository (which is how enterprise context currently works)
- Local context is fetched from files changed since the merge base of the current local working state and the upstream of the current branch. If the upstream doesn't exist, then the changes since last local commit are used.
- Context from the locally edited files is removed from the remote context to avoid duplication/staleness.
- Currently the local context is limited to 5 entries and concatenated with the remote context. In the future, we should rerank these context items together. …

Experimental: fetch context from both remote and locally modified source files

---

lib/prompt-editor/src/mentions/mentionMenu/useMentionMenuData.test.tsx
lib/prompt-editor/src/plugins/atMentions/atMentions.tsx
lib/prompt-editor/src/plugins/atMentions/chatContextClient.tsx
vscode/webviews/Chat.tsx
web/CHANGELOG.md
web/lib/components/CodyWebChatProvider.tsx
web/package.json

Recently, probably since we changed our logic for global contexts, I've noticed that as you switch between chats in the Cody Web sometimes the context providers like Repositories and Files just disappear from the @ menu. 
This PR fixes this by ensuring that we always listen to these events from the extension host, this PR also removes some old logic about reloading providers (it's no longer needed because providers' state became local)
- Check Cody Web demo (`cd web & pnpm dev`)
- Try to use the @ menu you should see set of three providers Repositories, Files and Symbols
- Change chat (or create new one) you should see the same set of providers

Cody Web: Fix mention provider fetching when user is switching between chats

---

lib/shared/src/models/index.ts
vscode/src/main.ts
web/CHANGELOG.md
web/package.json

Local Ollama models don't make sense much for Cody Web at the moment; disable it for now to avoid any confusion when users see a request to the local host from the source.com
- Check Cody Web demo, make sure that we don't call ollama local models handler `api/tags`

Disable Ollama local models in Cody Web

---

lib/shared/src/context/openctx/api.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
pnpm-lock.yaml
vscode/package.json
vscode/src/context/openctx.ts

If "openctx.providers" is configured in a users settings on a Sourcegraph instance, it will merge that in. This allows admins and users to set the configuration and automatically have it included in Cody.
The implementation prefers the vscode settings for a provider, but will merge the list of remote and local providers. This is hidden behind the noddle configuration so we can dogfood this.
Test Plan: added a provider to my sourcegraph settings and it appeared in Cody.
See the loom for demo https://www.loom.com/share/c861edd7ad17452aae9056019d9771e8
Fixes https://linear.app/sourcegraph/issue/SPLF-173/openctx-configuration-via-sourcegraph-instance-settings

openctx: merge in "openctx.providers" from Sourcegraph instance

---

lib/prompt-editor/src/plugins/atMentions/atMentions.tsx
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/context/chatContext.ts
vscode/src/edit/input/get-matching-context.ts
vscode/src/editor/utils/editor-context.test.ts
vscode/src/editor/utils/editor-context.ts
web/CHANGELOG.md
web/lib/components/CodyWebChat.tsx
web/lib/types.ts
web/package.json

Part of https://linear.app/sourcegraph/issue/SRCH-561/add-support-for-file-ranges-in-cody-web
This PR adds support for file ranges in remote file mentions, prior to this there was a problem that after you submitted too large a file the mention wasn't properly added (The @ sign was removed and `:` range column was added but nothing more) This PR fixes this too, (I think this problem existed in VSCode too, but I couldn't find a too large file in VSCode build) 
- Check that mentioning too big files requires `:` ranges flow and check that this flow works properly with Cody Web demo

Cody Web: Add range support for remote file mentions

---

lib/prompt-editor/src/config.ts
lib/prompt-editor/src/mentions/mentionMenu/MentionMenu.module.css
lib/prompt-editor/src/mentions/mentionMenu/MentionMenu.test.tsx
lib/prompt-editor/src/mentions/mentionMenu/MentionMenu.tsx
lib/prompt-editor/src/mentions/mentionMenu/MentionMenuItem.module.css
lib/prompt-editor/src/plugins/atMentions/atMentions.module.css
vscode/src/chat/clientStateBroadcaster.ts
vscode/webviews/components/shadcn/ui/command.tsx
vscode/webviews/promptEditor/MentionMenu.story.tsx
vscode/webviews/promptEditor/config.ts
vscode/webviews/tailwind.config.mjs
web/index.html
web/tailwind.config.mjs

The @-mention menu does not feel "stable" or "solid" enough IMO. Here are changes that make it feel more "stable".
- Make all rows the same height, and make the total height an integer multiple of the row height so that no row is ever partially obscured. This also means removing horizontal separators between groups and making the text rows (such as the "empty" message and group headings) use the same font size as results.
- Remove "Loading...". This causes jitter in every case, and it only helps in rare cases where loading takes a long time.
- Fix an issue in the horizontal positioning.
- Fix an issue where navigating into the `Files ->` menu would not select the first item
Storybooks, and run in debug mode and try using it.

make @-mention menu feel more stable

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatsController.ts
vscode/src/services/LocalStorageProvider.ts
vscode/test/e2e/chat-keyboard-shortcuts.test.ts
vscode/webviews/App.tsx
vscode/webviews/tabs/TabsBar.tsx

`Alt+L` now toggles between editor and sidebar chat:
- `Alt+L`: think of this as the muscle-memory "chat" shortcut
- From text editor: opens/focuses the chat sidebar panel
- From text editor with active selection: adds the active selection to chat
- From chat sidebar: focuses the last editor panel
- From chat editor: no-op
- `Shift+Alt+L`:
- From text editor: opens a new chat editor panel
- Anywhere else: starts a new chat in the sidebar
This is in line with our goal of using `Alt-{J,K,L}` as the standard shortcuts in Cody.
There is still a bit of jank when invoking `Shift+Alt+L` from a chat editor panel, because this will open a new chat in the *sidebar*. But fixing this will require a bit more work in the form of adding a VS Code context to detect when focus is in chat in an editor …

change default keybinding for creating chat in editor to Shift+Alt+L

---

vscode/package.json
vscode/src/chat/chat-view/ChatsController.ts

Follow-up fixes to https://github.com/sourcegraph/cody/pull/5089
- Give `New Chat *` commands unique names
- Prevent loss of focus when creating a new chat in the sidebar
Test locally

fix focus and dupe command name

---

.gitignore
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
vscode/src/context/openctx.ts
vscode/src/context/openctx/web.ts
web/CHANGELOG.md
web/package.json

This updates the web context provider to optionally use the new endpoint in the GraphQL API (introduced [here](https://github.com/sourcegraph/sourcegraph/pull/64223)) to fetch web context in cody web to get around CORS issues.
Tested dev build against local Sourcegraph instance. Also tested that web mentions still work in VSCode.

Use server proxy for web mentions in Cody Web

---

vscode/webviews/App.tsx

FOLLOW UP on https://github.com/sourcegraph/cody/pull/5039
Made a change couple days again in https://github.com/sourcegraph/cody/pull/5039 to make sidebar chat the default for both DotCom and Enterprise users in prepare for the next release, but missed to remove the condition about the nav bar for enterprise users. This PR removes the condition to check if the user is Enterprise users or not, and display the nav bar for everyone until the chat is in the Editor panel.
1. log into s2
2. open a new chat in the editor
3. confirm the nav bar is showing up in the sidebar 
4. confirm the nav bar is not showing up in the editor panel

Chat UI: Tab bar available to all users

---

web/CHANGELOG.md
web/demo/App.tsx
web/lib/components/CodyWebChatProvider.tsx
web/lib/index.ts

Part of [SRCH-720](https://linear.app/sourcegraph/issue/SRCH-720/new-chat-button-in-side-panel-view)
This PR simply exposes the internal CodyWebProvider API so a consumer would be able to call it proactively (in this particular case to trigger chat creation outside of CodyWebProvider children components)
- No manual testing is required (pure tech PR)

Cody Web: Expose internal create chat API from Cody Web root component

---

lib/shared/src/context/openctx/context.ts
lib/shared/src/guardrails/client.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ContextFetcher.ts
vscode/src/chat/chat-view/context.ts
vscode/src/context/remote-search.ts
vscode/src/editor/utils/editor-context.ts
vscode/src/local-context/rewrite-keyword-query.ts
vscode/src/local-context/symf.ts
vscode/src/repository/git-extension-api.ts
vscode/src/repository/remote-urls-from-parent-dirs.ts
vscode/src/repository/repo-name-resolver.ts

AbortSignals let us cancel potentially resource-intensive tasks when their result is no longer needed. Now we pass them around in more places.
Many methods in the GraphQL client now accept AbortSignals. This preserves the timeouts and timeout-related error behavior.
Test with an added 6-second-plus sleep and ensure that the error thrown is an ETIMEDOUT.

pass AbortSignals in more places

---

lib/shared/src/index.ts
lib/shared/src/token/constants.ts
lib/shared/src/token/counter.test.ts
lib/shared/src/token/counter.ts
lib/shared/src/token/index.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/context.ts
vscode/src/chat/chat-view/prompt.test.ts
vscode/src/chat/chat-view/prompt.ts
vscode/src/chat/clientStateBroadcaster.ts
vscode/src/local-context/rewrite-chat-query.ts
vscode/src/prompt-builder/index.test.ts
vscode/src/prompt-builder/utils.ts

Now, the context-fetching code looks at the mentions to determine which repo(s) to search in. For example, if there is an @-mention of a repository, then that repository is searched. These special @-mentions are called "corpus" mentions because they need to be expanded specially (unlike file @-mentions that refer to just a single document).
This is better than the previous way, which:
1. still used the "enhanced context" concept (a coarse boolean) instead of reading the context @-mentions (such as `@repository`) to determine the behavior
2. was built in a way that made support for multiple workspaces hard
There is no (intended or known) behavior change. Note that none of the agent snapshot tests needed changing.
Test context-fetching on PLG and enterprise. Ensure that PLG uses symf and …

refactor context-fetching

---

vscode/CHANGELOG.md
vscode/package.json

CLOSE https://linear.app/sourcegraph/issue/CODY-3141/new-chat-and-chat-history-icons-appearing-in-various-places-in-vs-code
Fixed an issue where buttons to start a new Cody chat and show Chat History were visible in non-Cody views.
Also removed the `cody.hasChatHistory` when clause since those are no longer being set and is invokable via the chat UI instead of sidebar tree views.
Log into Cody as PLG users and open Chat and a new chat in Editor to verify the History button and New Chat button only shows up in the Editor Chat Panel:
Verify the same thing with Enterprise users:
Open other extension panels and verify those buttons are not showing up in non-Cody panels:
Fixed an issue where buttons to start a new Cody chat and show Chat History were visible in non-Cody views.

Chat: Cody chat buttons are visible in Cody views only

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/CodyAgentServer.kt
agent/src/agent.ts
vscode/src/jsonrpc/agent-protocol.ts

This PR adds `extensionConfiguration/getSettingsSchema` endpoint which generates json schema file useful for validating cody settings and for documentation purposes.
1. Build Jenkins [PR #1972](https://github.com/sourcegraph/jetbrains/pull/1972)  with CODY_DIR set to this PR branch.
2. Run action `Open Cody Settings Editor` (you can use `shift shift` to find it)
3. Change some Cody settings. E.g. you can try to disable autocomplete:
`"cody.autocomplete.enabled": true`
4. Hit `Ctrl + S` to trigger the config update
5. Try to use autocomplete in some other file and make sure it does not work.
6. Revert your changes and make sure autocomplete is enabled again.

Get settings schema endpoint

---

vscode/webviews/components/modelSelectField/ModelSelectField.story.tsx
vscode/webviews/components/modelSelectField/ModelSelectField.tsx

[CODY-3138](https://linear.app/sourcegraph/issue/CODY-3138)
Previously we did not allow enterprise users to use cody pro models that were enabled on their instance. Here we refine that test to check only if it's a free user.
Manual test
Fix bug where enterprise users were stopped from using enabled, server-sent models.

fixed/dropdown: enterprise users can use any model available

---

web/CHANGELOG.md
web/lib/agent/agent.client.ts
web/package.json

context: https://linear.app/sourcegraph/issue/SRCH-821/context-is-not-being-fetched-on-vs-code-even-though-its-being-fetched
https://sourcegraph.slack.com/archives/C05D629GWJK/p1722933166623269?thread_ts=1722620916.715349&cid=C05D629GWJK
The `experimental.noodle` flag is enabled by default for Cody Web which should not be the case. Some experimental feature like chat query rewrite are therefore enabled right now.
This PR sets the `experimental.noodle` flag to false.
- cd web
- pnpm dev
- Submit a chat message in chat and monitor the network request to `getCodyChat` to make sure the query string is the chat message without the mention chips text.

Remove noodle flag set to true for Cody Web

---

vscode/webviews/App.tsx

Avoid emitting a `÷` in the chat input when the user hits `alt-/` (this happens on macOS, as alt is used for emitting unicode)
Test locally

suppress ÷ on alt-/ in the chat input

---

vscode/src/completions/providers/create-provider.ts

Adding a check `isDotCom` for ML experiments. This should restrict any modeling experiment to PLG users and will not run on enterprise.
Manual testing
1. Switch to s2 instance and added myself in the experiment override.
2. Added debugger to check that experiment condition does not satisfy for me.
1. Adding isDotCom check for ML modeling experiments.

add isDotCom check for ML modeling experiments

---

agent/src/vscode-shim.ts

close https://linear.app/sourcegraph/issue/CODY-2799/implement-vscodeopen-command-in-shims-to-get-local-context-link
This change adds support for the `vscode.open` command in the vscode-shim. The `vscode.open` command is used to open a URI in the default application. The implementation first tries to open the URI as a text document, and if that fails, it falls back to using the `open` library to open the URI in the default application.
Additionally, the `env.openExternal` function has been implemented to open a URI in the default external application.
These changes ensure that the vscode-shim provides a more complete implementation of the VSCode API, allowing for better integration with VSCode-based applications.
Can open context link from chat in JetBrains

Agent: add vscode-shim support for open commands

---

vscode/src/commands/menus/items/menu.ts
vscode/src/commands/services/provider.ts
web/lib/agent/agent.worker.ts
web/lib/agent/shims/os.ts

This makes Cody Web more similar to Cody in the editor. The commands provider will be used in the future for providing a nice transition path from Commands to Prompt Library; it is not per se desirable functionality we want.
CI

load CommandsProvider in web

---

vscode/webviews/chat/components/CustomCommandsList.tsx
vscode/webviews/chat/components/DefaultCommandsList.tsx
vscode/webviews/chat/components/WelcomeMessage.test.tsx
vscode/webviews/chat/components/WelcomeMessage.tsx
vscode/webviews/components/CollapsiblePanel.tsx
vscode/webviews/tabs/HistoryTab.tsx

Now these friends stay open or closed, the last way you left them, across chat sessions and editor restarts:
Collapse and reload editor. Confirm state.

persist open/closed state of CollapsiblePanel

---

vscode/webviews/tabs/TabsBar.tsx

If the screen is 768px wide or wider, then the Cody chat panel tabs will show text labels. This means that the standalone Cody Web chat screen will show text labels for most users, which fixes https://linear.app/sourcegraph/issue/CODY-3171/history-tab-is-hard-to-find-on-cody-web.
https://github.com/user-attachments/assets/7790d9ff-af8e-4e6f-929a-ea3210be1f2d
Make screen (or containing panel) narrow and wide. When it's wide, confirm tooltips are NOT shown but tab titles are visible. When narrow, confirm tab titles are NOT shown but tooltips are.

show tab labels on wide screens

---

vscode/src/chat/chat-view/ChatController.ts

There was a unintentional protocol change to a legacy `getUserContext` message where it didn't trigger the associated `userContextFiles` message. This message was still being used by Jetbrains causing [CODY-3196](https://linear.app/sourcegraph/issue/CODY-3169/sourcegraphjetbrains1990-jetbrains-file-tagging-is-not-working)
This reverts the change and ensures that the correct messages are triggered. As a follow up [CODY-3172](https://linear.app/sourcegraph/issue/CODY-3172/cascading-messages-arent-type-checked) will ensure that these class of issues are properly (type-)checked and tested.
- Current tests pass
- Verified locally that with the change JetBrains once again shows context files
- Deferred testing of the actual testing of the message handler until CODY-3172

Agent: Revert breaking protocol change

---

vscode/src/external-services.ts
vscode/src/local-context/symf.ts

Previously, the extension would download and run local indexing with symf for all accounts including enterprise accounts. This PR changes the behavior so that symf only starts running after the user has authenticated with a non-enterprise accounts. This is an important step towards removing all network traffic to other hosts besides the connected Sourcegraph instance.
We don't have agent integration tests for symf so this needs to be manually tested. You don't have to do all of these steps but these are cases I tried to cover.
* Clear local symf caches: `rm -rf '/Users/olafurpg/Library/Application Support/Code/User/globalStorage/sourcegraph.cody-ai/symf/'`
* Confirm you don't have this user setting enabled `"cody.experimental.symf.enabled": false`
* Authenticate to S2
* Clone and open …

Chat context: disable symf for enterprise accounts

---

vscode/src/non-stop/codelenses/items.ts

Before the "Edit & Retry" lens was shown after using the "Ask Cody to Fix" code action. Although it worked this would then show a prompt that the user never wrote which is confusing.
Now we don't show the Edit & Retry lens and only allow Accept/Reject.
CI
Manually verified that the Edit & Retry lens no longer shows up

Code Lenses: disable "Edit & Retry" for non-user prompts

---

vscode/src/edit/prompt/smart-apply.ts

Adds request error handling to the smart apply feature
Note: This is feature flagged and only enable for internal dogfooding right now
So if we get a network request or anything, we show it to the user. Previously we would end up just assuming we wanted to `insert`
1. Trigger a smart apply
2. Force a network error
3. Check the error message is shown to the user

Smart Apply: Handle request errors

---

vscode/CHANGELOG.md
vscode/src/local-context/download-symf.ts
vscode/src/local-context/symf.test.ts
vscode/src/local-context/symf.ts

The local search index is now rebuilt more frequently when many files are changed since the last index (such as when the user checks out a revision that differs from the current revision).
The frequency of update is dependent on:
- # files changed since last index
- time since last index
- time it took for last index
Test locally. See unit test.

symf: regenerate index more frequently

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/providers/create-provider.test.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/fireworks.ts

1. This PR adds a feature flag `cody-autocomplete-deepseek-v2-lite-base` to ship the deepseek-v2-lite-base model. For now, the model will be shipped for all the PLG users.
2. Sends a `anonymousUserId` fields in the fireworks payload. This payload is send to fireworks so that each user can be redirected to the same deployment and can leverage prompt caching.
1. Override myself in the feature flag and ensure we are hitting `deepseek` model when on dotCom instance.
2. Override myself in the feature flag and ensure we are hitting `starcoder` model when on S2 instance.
3. Checked that we pass `anonymousUserId` correctly to CG.
1. Shipping `deepseek-coder-v2-lite-base` as the default autocomplete model for PLG users.
2. Add `anonymousUserId` in the CG payload to leverage fireworks prompt …

Shipment of deepseek-v2-lite-base on autocomplete for PLG users

---

vscode/src/services/utils/codeblock-action-tracker.ts

This PR:
- Adds click events for telemetry
- Improves the type safety of this function slightly
- Correctly calls `setLastStoredCode` _before_ we apply any edits/files. This is needed as we set `insertInProgress` to gate against incorrectly checking a new insertion is a copy/paste from the clipboard.
1. Trigger telemetry events by clicking code block actions
2. Check that the fired telemetry is correct

Smart Apply: Add click events for telemetry

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/fireworks.ts

1. Adding the context window experiment with DeepSeek model.
2. The primary goal is to experiment with different context length and observe the change in the following metics: `CAR`, `latency`, `# Num Suggestions` and breakdown of latency at various stages such as `Client -> CG`, `CG -> Fireworks` to identify the bottleneck during inference when context window is increased.
3. Default context window of DS model is `128k`, offline experiment shows no issues with increasing context window upto `32k`.
4. Latency change Offline metrics show (The testing is done from a GCP VM ):
- with increase from `2048` to `4096`: 100ms
- with increase from `2048` to `8196`: 250ms
- with increase from `2048` to `16k`: 450ms
- with increase from `2048` to `32k`: 650ms
5. Initially run the experiment with 5% …

experiment DS with different context window

---

vscode/CHANGELOG.md
vscode/package.json

Patch release follow-up based on https://github.com/sourcegraph/cody/blob/main/vscode/CONTRIBUTING.md
version/CHANGELOG only
Autocomplete: Add a feature flag for DeepSeek-coder-v2 lite base model. [pull/5151](https://github.com/sourcegraph/cody/pull/5079)

VS Code: Release 1.30.1

---

agent/src/AgentDiagnostics.ts
agent/src/agent.ts
agent/src/vscode-shim.ts

VSCode URIs can sometimes be %-encoded. The JetBrains client doesn't entirely correctly handle this yet meaning that sometimes the URI used to publish diagnostics differed from the URI to fetch code-actions.
This meant that on paths with special characters (Such as most Windows paths or paths with spaces) diagnostics weren't correctly returned.
Now we ensure that only normalized strings are used by first converting them back to a Uri.
Fixes CODY-3217
> Note: There's a follow up action item to improve URI normalization in the Bindings (de)serializer (CODY-3223)
- Added additional opaque `UriString` type to ensure no unintended strings are passed in to Diagnostics anymore
- CI

Ensure normalized URI is used

---

vscode/webviews/tabs/TabsBar.tsx

Fixes: https://linear.app/sourcegraph/issue/SRCH-872/new-chat-button-should-open-up-new-chat-in-same-location-editorsidebar
Test locally
Fixed: The "New Chat" button in the sidebar now always opens the new chat in the sidebar, never the editor panel. Previously, a bug was introduced where the behavior was "sticky" as to which option the user last selected.

ensure "New Chat" in sidebar opens in sidebar, not editor

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ContextItem.kt
lib/shared/src/codebase-context/messages.ts
lib/shared/src/configuration.ts
lib/shared/src/local-context/index.ts
vscode/package.json
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ContextRetriever.ts
vscode/src/chat/chat-view/context.ts
vscode/src/chat/protocol.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/local-context/symf.ts
vscode/src/testutils/mocks.ts
vscode/webviews/chat/cells/contextCell/ContextCell.module.css
vscode/webviews/chat/cells/contextCell/ContextCell.tsx

Context items now include optional metadata about their source or scoring, which can help developers understand why certain items are appearing in the context. This change adds a `metadata` field to the `ContextItemCommon` interface and populates it for context items from Sourcegraph search, the local symbol index, and live search results.
You can view these by setting `"cody.internal.debug.context": true` in settings. The `cody.internal.showContextAlternatives` has been removed and replaced by this one.
Test locally, doesn't affect prod.

Add metadata to context items

---

agent/package.json

- Update the `build:webviews` script to output the built webviews directly to the `agent/dist/webviews` directory instead of copying them over
The change was commit accidentally in the last PR. It works the same but using --outDir simplify the build process and ensures the webviews are properly included in the agent distribution on machines where the cp command doesn't work
Confirmed running pnpm:webviews create the webviews dir in agent/dist
NA

Agent: update webview build script

---

vscode/CHANGELOG.md
vscode/webviews/App.module.css
vscode/webviews/Chat.module.css
vscode/webviews/chat/Transcript.tsx
vscode/webviews/prompts/PromptsTab.tsx
vscode/webviews/tabs/AccountTab.tsx
vscode/webviews/tabs/HistoryTab.tsx
vscode/webviews/tabs/SettingsTab.tsx

- Update the chat transcript container styles to use `height: 100%` and `overflow: scroll` to properly handle overflow of chat messages
- Adjust the padding and margin of the transcript container to improve the layout
Fixes an issue where @-mentions would cause the focus to shift to the top chat input box due to the container overflow settings causing the reference to the bottom chat input box to be lost.
Before

Chat: fix chat input focus issues

---

vscode/src/non-stop/codelenses/items.ts

"Retry" is not relevant to smart apply
1. Execute a smart apply
2. Observe the code lens in the document
3. Check that "Retry" is not visible

Smart Apply: Disable retry lens

---

vscode/src/chat/chat-view/ChatController.ts
vscode/webviews/index.html

- Update the content security policy in the chat webview template file index.html to use `'self'` instead of `{cspSource}` to allow the webview to load resources from the same origin by default without needing to specific cspSource
This change allows clients to run the webview with the template file by default
Green UI - This  change should not have impact with any current features or webviews setup

Chat: update webview content security policy template

---

vscode/CHANGELOG.md
vscode/src/edit/manager.ts

Edit `instruction` is no longer a `string`, but a `PromptString` object.
This meant that our equality check failed, the two strings were identical, but not considered the same due to how object equality works in JS
1. Select some code
1. Open the Cody sidebar
1. Hit "Document Code" or "Generate Unit Test" multiple times
1. Confirm that only one "Document Code" or "Generate Unit Test" command runs

Edit: Correctly guard against duplicate in-progress edits

---

agent/src/vscode-shim.ts
vscode/webviews/Chat.module.css
vscode/webviews/OnboardingExperiment.tsx
vscode/webviews/tabs/TabsBar.tsx
vscode/webviews/themes/visual-studio.css

- Add empty mock of "vscode.executeWorkspaceSymbolProvider" to vs code shim.
- Display New Chat keybinding for VS Code only as the shortcut only works for VS Code. In the future we should allow clients to send a list of shortcuts and display those instead. Part of https://linear.app/sourcegraph/issue/CODY-3046/web-ui-displays-vscode-shortcuts-not-jetbrains-ones
- Update stylesheet for Visual Studio
- In Login page, remove mention of VS Code, replace "Add the Access Token to VS Code" with "Add Access Token to Cody" - CLOSE https://linear.app/sourcegraph/issue/CODY-2920/sign-in-screen-mentions-vscode-doesnt-have-pretty-buttons
- Also fixed a minor regression on main where scrollbar is always shown by default:
Green CI - since all changes are mostly UI specified and should not change any …

Chat: update stylesheet for visual studio

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Chat_Sidebar_NewResult.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/CodyAgentClient.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/CodyAgentServer.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Window_DidChangeContextParams.kt
agent/src/agent.ts
agent/src/vscode-shim.ts
pnpm-lock.yaml
vscode/package.json
vscode/src/chat/chat-view/ChatController.ts
vscode/src/jsonrpc/agent-protocol.ts
vscode/webviews/App.tsx
vscode/webviews/OnboardingExperiment.story.tsx
vscode/webviews/OnboardingExperiment.tsx
vscode/webviews/components/ClientSignInForm.module.css
vscode/webviews/components/ClientSignInForm.tsx
vscode/webviews/components/shadcn/ui/form.tsx

Part of https://linear.app/sourcegraph/issue/CODY-3208/user-friendly-login-for-plg-and-enterprise https://linear.app/sourcegraph/issue/CODY-3055/web-based-login-ui-may-spuriously-appear
- Add a new `chat/sidebar/new` request to the agent protocol that creates a new chat panel with a sidebar webview type
- Update the `vscode-shim` to notify the agent when the window context changes, e.g. when the user's authentication status changes
- Update the `ChatController` to handle `signin` and `signout` messages from the webview
- Add a new `ClientSignInForm` component for clients that don't support the sign-in quickpick
These changes address the following issues:
- 'chat/sidebar/new' enables clients to start a new sidebar chat. The current 'chat/new' starts an editor chat where the nav bar is …

Agent: add new sidebar panel agent protocol & webview sign-in form

---

vscode/webviews/tabs/AccountTab.tsx

Follow up on https://github.com/sourcegraph/cody/pull/5192
Update the Sign Out button command in Account Tab (only used by non-VS Code clients) to `signout` auth command that would send a notification to client on setContext change via `window/didChangeContext`.
Green UI. No feature chanegs.

Chat: update signout button command in account tab

---

agent/src/agent.ts

There's a current bug somewhere (I think in Vite?) that tries to externalize node dependencies, and print out a warning message. But when it loads the dependencies of `fs-extra`, specifically `graceful-fs` it comes in as a symbol instead of string, which can't be interpolated and it crashes.
Our only use of it is to copy a file, which we can do with `fs` so it is unneeded.
Compiles and runs in browser.

fixed(web): removed `fs-extra`

---

vscode/CHANGELOG.md
vscode/src/main.ts

The debug commands were recently moved to be available in test/dev mode only, most likely by accident. 
This PR fixes this issue by always registering the commands for debugging on extension start-up.
Run the Export Debug Logs command and verify the command works:
Before this change, the command returns an error
Fixed issues where debug commands are not available in production.

Debug: make debug commands available outside of test

---

agent/src/vscode-shim.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/webviews/OnboardingExperiment.tsx

Fix an issue with vscode shim where the args value of setContext command always returned undefined, due to args was not being deconstructed properly during the "executeCommand" step.
Also updated the logic for displaying the new sign-in form for non-vscode IDE clients
'window/didChangeContext' should now show the correct key-value pair for notifying authStatus change:
NA

Agent: Fix setContext command args value always undefined

---

agent/CHANGELOG.md
agent/package.json
agent/recordings/cody-chat_103640681/recording.har.yaml
agent/src/TestClient.ts
agent/src/cli/__snapshots__/command-chat.test.ts.snap
agent/src/cli/command-chat.ts
vscode/src/jsonrpc/jsonrpc.ts

Previously, the CLI didn't give any hint when `--context-file` was too
large to fit into the context window. The VS Code chat UI refuses to
add these files as explicit context. This PR fixes the problem so that
the CLI also fails fast in the same scenario. Users can pass the
`--ignore-context-window-error` to skip this check.
Manually tested with
```
> pnpm -C agent build:agent && node agent/dist/index.js chat --context-file agent/src/cli/scip-codegen/scip.ts --context-file agent/src/agent.ts -m 'list all the methods here'
✖ The provided context is too large to fit into the context window.
To fix this problem, either remove the files from --context-file or
edit these files so they become small enough to fit into the context window.
Alternatively, set the flag …
```

fix/CLI: fail fast if the provided --context-file is too large

---

vscode/src/edit/manager.ts
vscode/src/edit/output/response-transformer.test.ts
vscode/src/edit/output/response-transformer.ts
vscode/src/edit/output/test-fixtures.ts
vscode/src/non-stop/FixupTask.ts

closes CODY-3243
Initially reported here: https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1723448811005809
Fixes a bug with Smart Apply where:
- Cody wants to `insert` a change to the bottom of the file, but that file doesn't have an empty final line
This uncovered two aspects that I've fixed here:
- Chat responses don't typically include line spacing, but we do need it here. I've added logic to manually inject a whitespace line if the final line is non-empty.
- The `responseTransformer` for the `add` command doesn't work effectively. New lines _are_ valuable information here that the LLM is more likely to provide, as we're essentially asking it to continue from the previous cursor position with an instruction.
1. Create edits with the `add` intent, check that they appear correctly
2. …

Edit/Smart Apply: Correctly handle `add` insertion ranges

---

.github/workflows/ci.yml

https://github.com/buildkite/test-collector-javascript/blob/9d29eb099a89bdab9e2b0d3420cc0e111fb0c0bc/util/ci.js#L72-L81 is really imprecise and doesn't account for all variants the value can take. This PR fixes it on our side until they do on their side. 
If we don't have this, we can't filter properly the results in the UI and `main` stats gets merged in the rest, completely throwing off the value of these analytics (while it's useful to track those in all branches, the timings and flakiness really matter solely on `main`). 
Tested on this PR + CI

chore(ci): fix reported branch name in BKA

---

agent/src/agent.ts
vscode/src/commands/CommandsController.ts
vscode/src/main.ts
vscode/webviews/components/MarkdownFromCody.tsx

This change updates the `CommandsController` to handle edit commands based on the client's capabilities. If the client's edit capability is set to `'none'`, the controller will disable all edit commands and throw an error if an edit command is attempted.
- Add a new `isEditEnabled` flag to track the edit capability
- Update `init` method to set the `isEditEnabled` flag based on the client capabilities
- Filter out edit commands from the command list if edit is disabled
- Throw an error if an edit command is executed and edit is disabled
1. Start Cody with edit capability set to `'none'`
2. Verify that edit commands are not shown in the command list
3. Attempt to execute an edit command and verify that an error is thrown
With Edit enabled:
edit === "none"

Commands: filter commands based on client capabilities

---

vscode/src/chat/chat-view/ChatController.ts
vscode/webviews/chat/ChatMessageContent/ChatMessageContent.tsx
vscode/webviews/chat/ChatMessageContent/create-buttons.ts
vscode/webviews/chat/cells/messageCell/assistant/AssistantMessageCell.tsx

The current smart apply implementation uses an OS-native dropdown for "Insert at Cursor" and "Save to New File". This is via a VS Code API. It works well for this initial MVP version, but obviously will not work in other clients.
This PR implements a fallback UI for other clients that is the same as the current UI for these actions.
See screenshots
**VS Code WebView**
**Other Clients WebView**
1. Test all code block actions in VS Code mode in the webview, check they all works
1. Test all code block actions in non-VS Code mode in the webview, check they all works

Smart Apply: Add basic UI to support other IDEs

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/index.test.ts
vscode/src/chat/chat-view/ChatController.ts

The Smart Apply functionality should be OK to enable in other clients as:
1. We have a generic UI that should work in any webview client. PR: https://github.com/sourcegraph/cody/pull/5188
2. It proxies from chat to inline edit, so any client that has the `edit` capability should be able to use this
Test in other clients that have the Edit capability

Smart Apply: Enable in other clients based on client capabilities

---

lib/prompt-editor/src/initialContext.test.ts
lib/prompt-editor/src/initialContext.ts
lib/shared/src/lexicalEditor/editorState.ts

If you manually @-mention a file in Cody chat and then change your current editor selection, your manual @-mention is clobbered. This was a bug introduced when we changed the @-mention nodes from Lexical TextNodes to DecoratorNode-based nodes. Now we need to traverse the tree and check all nodes instead of just checking the TextNodes.
As described above.
- Fix a chat issue where manually entered @-mentions would be clobbered if you changed your selection or active file in the editor.

do not clobber other @-mentions when initial context changes

---

lib/prompt-editor/src/mentions/mentionMenu/MentionMenu.tsx
lib/prompt-editor/src/mentions/mentionMenu/useMentionMenuData.test.tsx
lib/prompt-editor/src/mentions/mentionMenu/useMentionMenuData.ts
lib/prompt-editor/src/plugins/atMentions/util.ts
vscode/webviews/promptEditor/MentionMenu.story.tsx

This was unintentionally caused by https://github.com/sourcegraph/cody/pull/5057. The intent was to not show 2 mention items `Current File: foo.ts` and `foo.ts`, but it meant that if you typed `@foo` then neither would show up.
Also simplify how initial context is passed to MentionMenu. Just include it in `items` so we don't spread responsibility for displaying and filtering it across multiple components.
A future improvement would be to move all of this logic to the backend (extension host) and just give the UI the fully filtered list.
Open a new Cody chat. Type `@` and then the name of the currently open file in your editor. Confirm that Cody shows `Current File: ...` as an option.
- Fixed a bug in chat where the current file would not show up when @-mentioning a file and searching for …

fix a bug where the current file would not show up when searching for @-file mentions

---

vscode/src/completions/logger.ts

PR adds all the values from string array: `otherCompletionProviders` in `privateMetadata` to `metadata` so that we can collect this data on all instances. 
Goes through string array and adds each completionsProvider to the `metadata` as `otherCompletionProviders.{completionProvider} : 1`. Sample Payload below:
Tested locally and confirming that `privateMetadata` does not change and `metadata` includes the new fields.

Add `otherCompletionProviders` to metadata 

---

.config/viteShared.ts
web/lib/agent/agent.client.ts
web/lib/agent/shims/fs-extra.ts
web/lib/agent/shims/open.ts
web/lib/agent/shims/worker_threads.ts
web/lib/components/CodyWebPanelProvider.tsx
web/vite.config.ts

This makes `pnpm -C web dev` work again. This is just for the local dev build of Cody Web, and we separately test before bringing it into the main web app.
- fix shared vite config to use sources instead of built monorepo packages
- explicitly pass null argument to fix Cody Web
- specify Cody Web capabilities.webview agentic
- fix "stack too deep" error in typechecking
- add shim for new agent dep to unbreak Cody Web;5B
Run `pnpm -C web dev` and confirm the chat screen loads.

fix Cody Web dev build

---

lib/prompt-editor/src/BaseEditor.module.css
lib/prompt-editor/src/BaseEditor.tsx
lib/prompt-editor/src/mentions/mentionMenu/MentionMenu.module.css
lib/prompt-editor/src/mentions/mentionMenu/MentionMenu.tsx
lib/prompt-editor/src/plugins/atMentions/atMentions.module.css
lib/prompt-editor/src/plugins/atMentions/atMentions.tsx
package.json
pnpm-lock.yaml

See code comments. Now, the orientation won't flip, and sometimes it flipped the wrong way if it was 0px tall for a brief period (and then did not re-detect the available height after it filled in with content).
In the Chat storybook, type `@` and ensure the menu is not obscured.
In the web demo or the Transcript storybook, type `@a` and then delete so you just have `@`. The menu should be positioned correctly.
Fixed glitches in the positioning of the @-mention menu.

fix more @-mention menu glitchiness by fixing height

---

agent/src/agent.ts
lib/shared/src/auth/types.ts
lib/shared/src/cody-ignore/context-filters-provider.ts
lib/shared/src/configuration.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/telemetry/GraphQLTelemetryExporter.ts
lib/shared/src/telemetry-v2/TelemetryRecorderProvider.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/protocol.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/extension.common.ts
vscode/src/main.ts
vscode/src/services/cody-ignore.ts
vscode/src/services/sentry/sentry.ts
vscode/webviews/App.story.tsx
vscode/webviews/App.tsx
vscode/webviews/AppWrapperForTest.tsx
vscode/webviews/Chat.story.tsx
vscode/webviews/Chat.tsx
vscode/webviews/CodyPanel.tsx
vscode/webviews/OnboardingExperiment.tsx
vscode/webviews/tabs/AccountTab.tsx
vscode/webviews/tabs/SettingsTab.tsx
vscode/webviews/utils/useConfig.tsx
web/lib/components/CodyWebPanel.tsx

These were some small fixes that were piling up on one of my branches. No user-facing behavior change.
- perform auth in agent slightly earlier
- don't call it dispose if it's called multiple times and doesn't invalidate the instance
- use minimal Config type when access token is not needed
- SourcegraphGraphQLAPIClient cleanup
- use types instead of `satisfies`
- merge configFeatures webview RPC message into existing config message
- rm FeatureFlagProvider endpoint arg
- get userAccountInfo through React context
CI, run locally and ensure no errors

many various code cleanups and removals

---

pnpm-lock.yaml
vscode/webviews/components/MarkdownFromCody.tsx
web/lib/agent/agent.client.ts
web/package.json
web/vite.config.ts

- only import 37 common langs' highlighting support. Saves ~1MB on the bundle size, at the expense of losing syntax-highlighting support for languages like: isbl, mathematica, gcl, 1c, sqf, maxima, pgsql, x86asm, mel, arduino.
- import web worker in separate file
- add vite-bundle-analyzer
CI

bundle size improvements

---

agent/src/cli/command-chat.ts
lib/shared/package.json
lib/shared/src/index.ts
lib/shared/src/prompt/truncation.test.ts
lib/shared/src/prompt/truncation.ts
lib/shared/src/token/counter.test.ts
lib/shared/src/token/counter.ts
pnpm-lock.yaml
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/prompt.test.ts
vscode/src/chat/chat-view/prompt.ts
vscode/src/commands/context/directory.ts
vscode/src/commands/context/file-path.ts
vscode/src/commands/context/git-api.ts
vscode/src/commands/context/selection.ts
vscode/src/commands/context/shell.ts
vscode/src/commands/scm/source-control.ts
vscode/src/commands/utils/create-context-file.ts
vscode/src/edit/prompt/context.ts
vscode/src/edit/prompt/index.ts
vscode/src/edit/prompt/smart-apply.ts
vscode/src/editor/utils/editor-context.ts
vscode/src/prompt-builder/index.test.ts
vscode/src/prompt-builder/index.ts
vscode/test/e2e/chat-input.test.ts

`js-tiktoken` is a very large JavaScript library. This changes how we use it, cutting ~6mb from the initial bundle size (3mb for each of the webviews and agent).
- Now, we only import `cl100k_base` and not the other tokenizers. These were being tree-shaken anyway, but this protects us from regressions there.
- We now lazily import the `cl100k_base` data, which means all token counting functions are now async. In the webviews and on the web, this results in a significant speedup in page load (~6mb smaller initial bundle and ~25% faster DOMContentLoaded).
n/a

lazily import js-tiktoken to cut ~6mb from initial bundle size

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/CodyAgentClient.kt
agent/src/vscode-shim.ts
vscode/src/jsonrpc/agent-protocol.ts

Needed for https://linear.app/sourcegraph/issue/CODY-2801/implement-vscodewindowshowsavedialog-to-get-save-file-button
JetBrains part: https://github.com/sourcegraph/jetbrains/pull/2040
Use the test plan from: https://github.com/sourcegraph/jetbrains/pull/2040

Add window/showSaveDialog to the protocol

---

agent/package.json
lib/shared/package.json
lib/shared/src/telemetry-v2/TelemetryRecorderProvider.ts
package.json
pnpm-lock.yaml
vscode/package.json
vscode/src/services/telemetry-v2.test.ts
vscode/src/services/telemetry-v2.ts
web/package.json

- use latest @sourcegraph/telemetry without RxJS
- update openctx to use version without rxjs
- use single version of highlight.js to reduce bundle size by ~278kB
CI

more bundle size fixes + removing RxJS transitive deps

---

lib/prompt-editor/src/PromptEditor.module.css
vscode/test/e2e/chat-input.test.ts
vscode/webviews/chat/Transcript.test.tsx
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/Cell.tsx
vscode/webviews/chat/cells/contextCell/ContextCell.tsx
vscode/webviews/chat/cells/messageCell/BaseMessageCell.tsx
vscode/webviews/chat/cells/messageCell/assistant/AssistantMessageCell.tsx
vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx
vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.module.css
vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx
vscode/webviews/chat/components/WelcomeMessage.tsx
vscode/webviews/components/UserAvatar.module.css
vscode/webviews/components/UserAvatar.story.tsx
vscode/webviews/components/UserAvatar.tsx
vscode/webviews/components/shadcn/ui/accordion.tsx

Many people have asked for Cody chat to use the full width in the viewport. This is especially important now that we often show chat in a narrow sidebar instead of an editor panel.
Example request: https://x.com/riipandi/status/1825414693860856206 (this was just now, there have been many others)
This is a partial impl of this Figma: https://www.figma.com/design/f078wFMKsIOaEwj7Iwj5xy/%E2%AC%9C%EF%B8%8F--Unified-Cody?node-id=4157-66156&t=UY3VI8o9wD53jilb-0.
Fixes https://linear.app/sourcegraph/issue/SRCH-930/chat-should-use-full-viewport-width
Use Cody chat on a narrow screen.
The chat UI now uses the full width of its viewport, which is helpful when using chat in a narrow editor sidebar.

use the full width of the Cody chat viewport

---

vscode/src/completions/logger.ts

Adds `SuperMaven` and `CodeGPT:Chat & AI Agents` to the list of `otherCompletionProviders`.
Got the `extensionId` by right clicking the extension on VSCode and grabbing it from there.
Test CI and confirm that local build runs

add additional `otherCodeCompletionProviders`

---

vscode/webviews/chat/cells/Cell.tsx
vscode/webviews/tabs/TabsBar.tsx

Fixes https://linear.app/sourcegraph/issue/CODY-3381/fix-new-chat-button-display-issue-when-window-narrows
Make App or Chat storybook narrow and ensure icons do not get smaller

fix squished "new chat" and user avatar icons

---

lib/prompt-editor/src/mentions/mentionMenu/MentionMenu.module.css
lib/prompt-editor/src/nodes/ContextItemMentionNode.tsx
lib/prompt-editor/src/plugins/atMentions/atMentions.tsx
vscode/webviews/CodyPanel.tsx
vscode/webviews/tabs/TabsBar.tsx
web/CHANGELOG.md
web/lib/components/CodyWebPanel.tsx
web/package.json

This PR addresses a few regressions since the last time we did a release of Cody Web (0.4.0), most of the fixes are trivial and come from the fact of very high speed of changing in VSCode codebase (after Cody Web GA I will guard cody web package with proper e2e tests)
- Now Cody Web renders tabs UI (small regression in recent commits about editor mode)
- Fixes create new chat command
- Adds additional selector to override styles for at mentioned portal menu
- Fixes problem when you can't remove initial context items due to a problem with the lexical node key
- No longer renders EDIT-like snippets actions  
- Run Cody Web demo and check that core chat functionality is intact

Cody Web: Fixes regressions since 0.4.0 (the last published version)

---

vscode/src/edit/manager.ts
vscode/src/edit/smart-apply.ts
vscode/src/services/utils/codeblock-action-tracker.ts

This PR routes the "new file" logic through the edit command, meaning:
- Applying state works correctly
- Accept/Reject buttons are shown and work
- Decorations are shown
- Telemetry is correctly recorded
- Stuck on Applying
- No decorations
- No Accept/Reject
1. Create a smart apply edit with a prompt like "Create a Heading component in a new file"
2. Click Apply
3. Expect that the file is created, "Accept" and "Reject" are shown

Smart Apply: Route new file logic through edit command

---

vscode/webviews/tabs/TabsBar.tsx

Fix a minor regression made y https://github.com/sourcegraph/cody/pull/5260
Revert to using ternary operator to handle falsy value.
Green CI

Webview: conditionally render tabs based on multipleWebviewsEnabled

---

agent/recordings/cody-chat_103640681/recording.har.yaml
agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/cli/__snapshots__/command-chat.test.ts.snap
agent/src/index.test.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
lib/shared/src/prompt/prompt-mixin.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/prompt.ts
vscode/src/chat/protocol.ts
vscode/webviews/App.story.tsx
vscode/webviews/App.tsx
vscode/webviews/Chat.tsx
vscode/webviews/CodyPanel.tsx
vscode/webviews/chat/ChatMessageContent/ChatMessageContent.tsx
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/messageCell/assistant/AssistantMessageCell.tsx

Enables the "smart apply" feature by default, removing the feature flag.
Chat Eval: https://github.com/sourcegraph/cody-leaderboard/pull/16
Looker Dashboard: https://sourcegraph.looker.com/looks/2016
Test Smart Apply on:
- Note: Further testing will be done by the JetBrains team when the WebView is fully implemented

Smart Apply: Enable by default

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Model.kt
agent/src/cli/command-bench/command-bench.ts
agent/src/cli/command-chat.ts
agent/src/edit.test.ts
agent/src/index.test.ts
lib/shared/src/llm-providers/ollama/utils.ts
lib/shared/src/llm-providers/utils.ts
lib/shared/src/models/dotcom.ts
lib/shared/src/models/index.test.ts
lib/shared/src/models/index.ts
lib/shared/src/models/types.ts
pnpm-lock.yaml
vscode/src/chat/chat-view/prompt.test.ts
vscode/src/commands/scm/source-control.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/openaicompatible.ts
vscode/src/edit/input/get-items/model.ts
vscode/src/models/modelMigrator.ts
vscode/src/models/sync.test.ts
vscode/src/models/sync.ts
vscode/webviews/App.tsx
vscode/webviews/chat/cells/contextCell/ContextCell.tsx
vscode/webviews/chat/cells/messageCell/assistant/AssistantMessageCell.tsx
vscode/webviews/chat/models/chatModelContext.tsx
vscode/webviews/components/modelSelectField/ModelSelectField.story.tsx
vscode/webviews/components/modelSelectField/ModelSelectField.tsx
vscode/webviews/storybook/VSCodeStoryDecorator.tsx
web/lib/components/CodyWebPanel.tsx

Renaming `model.model` to `model.id` used by the `ModelsService` to make it easier to reason about the code. AFAIU, this is a client-only field, so it's safe to refactor without backend changes.
CI
No functional changes

Model Provider: rename `model.model` to `model.id`

---

lib/shared/src/auth/types.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
vscode/src/completions/create-multi-model-inline-completion-provider.ts
vscode/src/completions/providers/create-provider.test.ts
vscode/src/completions/providers/create-provider.ts
vscode/test/fixtures/mock-server.ts

- Removing the Anthropic autocomplete provider fallback. If the instance does not return a `completionModel`, we fail with an error message asking users to update their instance site-config.
- Refactored a small part of the `createProviderConfig` code with no functional changes. I'll have multiple follow-up updates to this part. Splitting it into numerous smaller PRs to make it easier to review.
- Discussed in [the Slack thread](https://sourcegraph.slack.com/archives/C075G57B5PH/p1724211970457949?thread_ts=1724202783.269599&cid=C075G57B5PH).
CI

Autocomplete: remove Anthropic fallback

---

vscode/src/edit/manager.ts
vscode/src/edit/prompt/smart-apply.ts

Closes CODY-3397
We didn't notify the webview of the failure when getting the smart selection, as the task wasn't created yet.
Fixed:
1. Force that the smart selection request will fail (e.g. add a `request.abort()` inside `nodeClient`)
2. Trigger a smart apply
3. Expect the error to show
4. Expect the smart apply to not be stuck on "Applying"

Smart Apply: Notify WebView of failure when erred from selection request

---

agent/recordings/customCommandsClient_509552979/recording.har.yaml
agent/recordings/document-code_965949506/recording.har.yaml
agent/recordings/edit_1541920145/recording.har.yaml
agent/recordings/fix_3001320056/recording.har.yaml
agent/src/__snapshots__/custom-commands.test.ts.snap
agent/src/__snapshots__/document-code.test.ts.snap
agent/src/edit.test.ts
vscode/CHANGELOG.md
vscode/src/non-stop/FixupTask.ts
vscode/src/non-stop/decorations/compute-decorations.test.ts
vscode/src/non-stop/decorations/compute-decorations.ts

Closes https://linear.app/sourcegraph/issue/CODY-3236/bug-with-edit-command-inserts-newline-incorrectly-and-removes-trailing
Closes https://github.com/sourcegraph/cody/issues/5209
Fixes issues where we would not include the final new line character of a line, so the edit would not be correct. Mainly happened for single line edits, where we'd often squash the change into the next line.
Original fix by @arafatkatze, I just re-implemented it and did some more testing
Test with:

Edit: Fix single line edits

---

vscode/webviews/chat/ChatMessageContent/utils.ts

Fixes an issue where "Open Diff" would not work for the smart apply diffs. This is because the ID used was too long, we were using the entire contents of the codeblock for the ID. We should just hash this and it'll be a lot shorter.
1. Create smart apply edits
2. Click "Open Diff"

Smart Apply: Hash the ID used for the FixupTask

---

vscode/CHANGELOG.md
vscode/src/non-stop/decorations/compute-decorations.ts

Noticed a bug where this could happen:
1. Trigger an edit, e.g. try one that deletes a bunch of comments
2. Change the file immediately, so the edit you are in is no longer visible
3. When the edit is applied, go back to the original file.
4. Notice that decorations are missing
This was an oversight when I added the original diff logic, we still want to _compute_ decorations for hidden files, we just can't show them yet! (We already handle showing decorations when a file becomes visible)
https://github.com/user-attachments/assets/44c1fcbc-10da-41d8-bb5f-9ce28dc580ec
https://github.com/user-attachments/assets/b890f765-ff57-41fe-8013-61723ab48a42
1. Trigger an edit, e.g. try one that deletes a bunch of comments
2. Change the file immediately, so the edit you are in is no longer visible
3. …

Edit: Compute decorations for hidden files

---

vscode/CHANGELOG.md
vscode/package.json

ready to roll out VS Code `v1.32.0` googog
N/A

VS Code: Release v1.32.0

---

vscode/webviews/components/promptList/PromptList.tsx

The `cody.promptList/query` telemetry event in `PromptList.tsx` currently fires with every change to the result, error, and debouncedQuery variables, resulting in a high volume of data (approximately 2 million records per day). This frequency is among the highest of all events we collect.
This PR proposes recording `cody.promptList/query` event only when the user interacts with the promptList to select an item (same time as `cody.promptList/select` fires); this will help reduce the number of times `cody.promptList/query` fires, but still allows us to get query data from users using promptList.
Note: If this data point is valuable and the frequency is as expected, please do let me know.
CI + local build

Telemetry: Update `cody.promptList/query` event to fire less

---

lib/shared/src/sourcegraph-api/telemetry/MockServerTelemetryExporter.ts

PR adds `testOnlyAnonymousUserId` to the testing event payload. This allows us to test `anonymousUserId` stays consistent within each test run.
Tested Locally and confirming that `testOnlyAnonymousUserId` is coming through

update `mockServerTelemetryExporter` to send `anonymousUserId`

---

lib/shared/src/models/index.ts
vscode/src/completions/create-multi-model-inline-completion-provider.ts
vscode/src/completions/providers/create-provider.test.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/openaicompatible.ts

- Merged case statements from the `createProviderConfig` function with the switch statement in the `createProviderConfigHelper` function to keep one source of truth and simplify the setup.
CI

Autocomplete: reduce `createProviderConfig` duplication

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/get-inline-completions-tests/models.test.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/fireworks.ts

- Removed the unused `starcoder2` support and feature flag from the Fireworks provider. 
CI

Autocomplete: remove starcoder2

---

lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts

Call to `getCodyContext` API is broken in Cody due to the `filePatterns` argument. Passing null just fails the graphql query. 
This PR fixes it. 
- Open Cody and connect to s2
- Test Remote Repository & Remote Directories

Fix getCodyContext fetching

---

agent/src/vscode-shim.ts

Fixes https://linear.app/sourcegraph/issue/CODY-3368/context-file-link-no-longer-works.
Tested with JetBrains. Context file link navigates properly to the file AND THE SELECTED RANGE.

Fix context file selection ranges & remote file links

---

vscode/src/chat/chat-view/ChatController.ts
vscode/src/editor/utils/editor-context.ts
web/CHANGELOG.md
web/demo/App.tsx
web/lib/components/CodyWebPanel.tsx
web/lib/components/CodyWebPanelProvider.tsx
web/lib/types.ts
web/package.json

Fixes CODY-3375
Fixes CODY-3376
This PR makes symbol and file mention search respect the initial context repository, so we will look for files and symbols only within this repository. You can still select files from different repositories by selecting the "Files" category directly. 
- Check that you can select files in the cody web demo by typing `@<search term>` string and you see files only within sourcegraph/cody repository (which is set as a default context for the cody web demo)

Cody Web: Fix cody web file/symbol mention search

---

web/CHANGELOG.md
web/demo/App.tsx
web/lib/components/CodyWebPanel.tsx
web/lib/types.ts
web/package.json
web/vite.config.ts

Part of SRCH-940
See the original issue; in the Sourcegraph repo page, it's a common case when you open Cody Web chat from the directory page, so it makes sense to support directories as an initial mention for the chat. 
- Check that Cody Web demo resolves proper context with default directory mention (demo already has directory mention by default)

Cody Web: Support directory as initial context

---

lib/shared/src/models/dotcom.ts

* Remove "Balanced" group, only have "Power" and "Speed" groups
* Remove Mixtral 8x22B because it's not a "powerful" model, we should be using Mistral Large here to give Mistral a fair representation. I kept 8x7B in the fast group.
* Moved Google Flash above Haiku in the "Speed" group (I think it's a stronger fast model, but don't have strong evidence to support this). We can always change the order later.
Ran a local build and took this screenshot 
* Updated model selection for Pro/Free users to only have two groups: "Most powerful models" and "Faster models". The "Balanced" group has been removed.
* Removed Mixtral 8x22B for Pro/Free users, use Mixtral 8x7B or Sonnet 3.5 instead.

PLG: simplify model selection

---

agent/recordings/cody-chat_103640681/recording.har.yaml
agent/recordings/customCommandsClient_509552979/recording.har.yaml
agent/recordings/defaultClient_631904893/recording.har.yaml
agent/recordings/document-code_965949506/recording.har.yaml
agent/recordings/edit_1541920145/recording.har.yaml
agent/recordings/enterpriseClient_3965582033/recording.har.yaml
agent/recordings/fix_3001320056/recording.har.yaml
agent/src/__snapshots__/custom-commands.test.ts.snap
agent/src/__snapshots__/document-code.test.ts.snap
agent/src/cli/__snapshots__/command-chat.test.ts.snap
agent/src/edit.test.ts
agent/src/enterprise-demo.test.ts
agent/src/index.test.ts
lib/shared/src/chat/preamble.ts
lib/shared/src/prompt/prompt-mixin.ts
lib/shared/src/prompt/templates.ts
vscode/src/chat/chat-view/prompt.test.ts
vscode/src/chat/chat-view/prompt.ts
vscode/src/commands/scm/source-control.ts
vscode/src/edit/prompt/index.ts
vscode/src/edit/prompt/smart-apply.ts
vscode/src/local-context/rewrite-keyword-query.ts
vscode/src/prompt-builder/index.test.ts
vscode/src/supercompletions/get-supercompletion.ts

This PR improves the smart apply prompt tweak so that:
- We use the system prompt when available
- We use the same desired Markdown syntax when _we_ include codebase context, which helps steer the LLM onto the right path.
I have ran an eval on this here: https://github.com/sourcegraph/cody-leaderboard/pull/16
Quite happy with the results so far

Smart Apply: Use system prompt to encourage code blocks being created

---

vscode/src/chat/chat-view/ChatController.ts
vscode/webviews/App.tsx

Close https://sourcegraph.slack.com/archives/C06R69BC8UW/p1724339360841049
Right now we are sending a lot of duplicated messages to webview.
This PR makes the following improvements to the Cody Web initialization and view handling:
1. Sets the webview view to `Chat` after the `initialized` message is received, ensuring the view is displayed correctly instead of setting it on every config change.
2. Simplifies the `setAuthStatus` method by only fetching the default chat model when the user is logged in.
3. Removes the unnecessary call to `sendConfig` after the `handleInitialized` method, as the config is already sent in the `handleReady` method.
4. Removes the unnecessary call to `postChatModels` after the `handleInitialized` method, as the chat models are now updated via the …

Chat: Improve Cody Web initialization and view handling

---

pnpm-lock.yaml
vscode/CHANGELOG.md
vscode/package.json

There has been a (long ongoing) issue with `rehype-highlight` / `highight-js` causing OOM issues on `>v6.0.0`. This reverts a recent version bump that might have [re-introduced this issue](https://github.com/sourcegraph/cody/pull/4459) in Cody chat causing grey-screens and crashes.
> Important: I wasn't able to re-produce the issue myself for some reason. So this is a bit of a "shot-in-the-dark" fix. Hopefully we can have those who reported the issue validate if it actually worked. Lowering the version shouldn't hurt any other changes though as it was merely done to reduce the bundle size somewhat.
CI

Revert: rehype-highlight bump

---

vscode/package.json
vscode/test/e2e/chat-keyboard-shortcuts.test.ts

Previously, the option+l shortcut triggered two commands:
- Toggle chat
- Add selection to chat
This was problematic because the selection is already an initial context in chat so the chat input ended up having duplicate chips (one "initial"
and one "user").
This PR fixes the problem by removing the option+l shortcut for "Add selection to chat" so that it only toggles the visibility of the sidebar. Users can still manually add the selection to the chat input with the option+/ shortcut.
* Local build
* Select text
* Trigger option+l multiple times
* Confirm that it doesn't keep adding the selection to the chat
* Fix bug where continuously triggering alt+l (option+l for macOS) would add duplicate context items to the chat input. Use the alt+/ shortcut to explicitly add the selection to the …

Chat: don't add selection to chat on option+l shortcut

---

vscode/webviews/themes/jetbrains.css

CLOSE https://linear.app/sourcegraph/issue/CODY-3419/fix-css-incompatibilities-in-jetbrains
As per requested: https://linear.app/sourcegraph/issue/CODY-3419/fix-css-incompatibilities-in-jetbrains#comment-d2189743
This change updates the JetBrains theme colors for the following CSS variables:
- `--vscode-quickInput-background`
- `--vscode-quickInput-foreground`
- `--vscode-quickInputTitle-background`
The changes aim to improve the visual appearance of the command menu elements in the JetBrains webview and aligns it with the one in VS Code.
After:
Before:

Chat: update JetBrains theme colors for command menu

---

lib/shared/src/configuration.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/CHANGELOG.md
vscode/package.json
vscode/src/completions/completion-provider-config.ts
vscode/src/completions/get-completion-provider.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions-tests/hot-streak.test.ts
vscode/src/completions/get-inline-completions-tests/streaming.test.ts
vscode/src/completions/inline-completion-item-provider-e2e.test.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/expopenaicompatible.ts
vscode/src/completions/providers/fetch-and-process-completions.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/get-completion-params.ts
vscode/src/completions/providers/openaicompatible.ts
vscode/src/completions/providers/provider.ts
vscode/src/completions/request-manager.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/testutils/mocks.ts

- Enables hot-streak and smart-throttle for enterprise users.
- Removes related feature flags and user settings.
- Removes the unused `autocompleteTimeouts` setting.
- Closes https://linear.app/sourcegraph/issue/CODY-3299/rolling-out-hot-streak-and-smart-throttle-to-plg-and-enterprise-august
CI and manually tested autocomplete.

Autocomplete: enable smart-throttle and hot-streak by default

---

vscode/webviews/App.module.css
vscode/webviews/tabs/TabsBar.module.css
vscode/webviews/tabs/TabsBar.tsx
web/CHANGELOG.md
web/demo/App.module.css
web/demo/App.tsx
web/lib/components/CodyWebChat.module.css
web/package.json

Part of https://linear.app/sourcegraph/issue/CODY-3404/add-confirmation-to-clear-all-chat-history-button
This PR adds support for a confirmation UI for clients like Cody Web, for which we don't have a native confirmation UI. 
- Run Cody Web demo
- Check that "Clear history chats" action renders an intermediate confirmation UI 
- For full testing in Sourcegraph client use this sg PR https://github.com/sourcegraph/sourcegraph/pull/144

Add support for web-like modal UI in Cody Web

---

pnpm-lock.yaml
vscode/.storybook/main.ts
vscode/package.json
vscode/webviews/postcss.config.js

Manually tested:
1. Clone `sourcegraph/jetbrains` and set up dependencies.
2. `CODY_DIR=/path/to/cody/repo ./gradlew runIDE -PforceAgentBuild=true`
3. Right click on chat, Open DevTools
4. ..., More Tools, Search for `--prompt-editor-padding` and confirm that the rules aren't in nested CSS
In addition, sidebar chat CSS should look OK. (Not perfect yet, but better...)

fix/JetBrains: Use postcss-nested to support Chromium 111 in JetBrains 2023.2 JBCEF

---

lib/shared/src/prompt/prompt-string.ts
vscode/src/prompt-builder/utils.ts

Fixes CODY-3421
Previously, smart apply didn't work for empty files, it would create a new file in the root directory instead. This was problematic because users could create an empty file in a subdirectory, ask chat to write code, press smart "Apply" and Cody would open a different file with the same name (but in the root directory).
This PR fixes the problem by adding empty files to the context if those files are explicitly added as context items in the chat input. Previously, we skipped empty files, presumably because they add limited value when pulled implicitly (via embeddings or keyword search).
* Create empty file in subdirectory lib/foo.ts
* Ask chat question with empty file added as context: "@foo.ts write fibonacci"
* Click "Apply"
* Expectation: it adds the code to lib/foo.ts
* …

Smart Apply: support writing to empty files

---

vscode/webviews/chat/ChatMessageContent/ChatMessageContent.tsx
vscode/webviews/chat/Transcript.tsx

Fixes SRCH-942
Previously, if an enterprise user had a chat window open with a code block containing more than 10 lines of code, then Cody would send a request to our Guardrails server on every single editor event. This was caused by a `useEffect` block that has a large number of dependencies where one of the dependencies (`humanMessage`) was not memoized.
This PR fixes the bug by wrapping `humanMessage` in a `useMemo` block. Ideally, the code should be refactored a bit to have more narrow `useEffect` blocks with fewer dependencies.
* Sign into enterprise account (S2)
* Open chat in an editor
* Ask a question that generates a code block with >10 loc
* Open webview developer tools, network tab
* Select text in the editor
* Old behavior: the guardrails icon was spinning on every selection …

Guardrails: fix DDoS bug

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ClientCapabilities.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/CodyAgentClient.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/CodyAgentServer.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Secrets_DeleteParams.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Secrets_DidChangeParams.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Secrets_GetParams.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Secrets_StoreParams.kt
agent/src/AgentSecretStorage.ts
agent/src/TestClient.ts
agent/src/agent.ts
agent/src/allClientCapabilitiesEnabled.ts
agent/src/bfg/BfgRetriever.test.ts
vscode/src/jsonrpc/agent-protocol.ts

Previously, the agent only supported stateless secret storage, where the agent server stored secrets in a temporary hashmap that was lost whenever the agent started. Now, clients can optionally declare that they're able to store secrets using the `secrets: 'client-managed'` capability. With this new capability, client can
store/retrieve/delete/change secrets using the new JSON-RPC methods:
* `secrets/get`
* `secrets/store`
* `secrets/delete`
* `secrets/didChange`
Here's the PR moving to client-managed secrets for the Eclipse plugin, which allowed us to delete 600 lines of native UI code 😮 https://github.com/sourcegraph/eclipse/pull/54
This PR changes `TestClient` to use client-managed secrets, so we're stressing this new code path in all the integration tests by default.

Agent: add new `secrets` capability to implement secret storage

---

vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/get-experiment-model.ts
vscode/src/completions/providers/get-model-info.ts

- Moving code around to make `createProvider` less intimidating and easier to scan:
- Extracted model parsing logic into a separate module
- Extracted experiment-model resolution into a separate module.
CI

Autocomplete: split `createProvider` into multiple files

---

lib/prompt-editor/src/mentions/mentionMenu/MentionMenu.test.tsx
lib/shared/src/cody-ignore/context-filters-provider.test.ts
package.json
pnpm-lock.yaml
vscode/.storybook/main.ts
vscode/src/completions/context/retrievers/lsp-light/lsp-light-retriever.test.ts

The PR https://github.com/sourcegraph/cody/pull/5344 made it so that Tailwind CSS was not being emitted, which broke CSS styles in the storybook.
It should not be necessary to specify the postcssNested plugin here, as the referenced PostCSS config file already references it. This reduces duplication of PostCSS config and makes it so that storybooks' Tailwind CSS is emitted.
Upgrades vite and vitest to avoid stack depth errors from TypeScript when type-checking the Vite config files. I saw multiple versions of Vite types being used (check `pnpm -r why vite`).
Run `pnpm -C vscode storybook` and confirm CSS works.

fix storybook CSS

---

vscode/webviews/tabs/AccountTab.tsx

1. `Manage Account`  is no longer visible for enterprise accounts
2. New option `Switch Account...` was added
Run with this JetBrains PR:
**For free/pro account:**
1. Go to the Account panel and check if both `Switch Account...` and `Manage Account` options are present
3. Make sure `Manage Account` redirects you to the account web management page
4. Make sure `Switch Account...`  opens native account management panel
**For enterprise account:**
1. Go to the Account panel and check if both `Switch Account...` and `Manage Account` options are present
2. Make sure `Manage Account` is not visible
3. Make sure `Switch Account...`  opens native account management panel

Add 'Switch account' option to webview panel

---

vscode/src/chat/clientStateBroadcaster.ts
vscode/test/e2e/chat-keyboard-shortcuts.test.ts
vscode/test/e2e/initial-context.test.ts

Previously, the chat input defaulted to using the chips REPO_CONTEXT FILE_CONTEXT. This PR flips the order so that REPO_CONTEXT appears after FILE_CONTEXT. The motivation for this change is to make it easier for users to disable repo context (press backspace twice). The reasoning is that users more frequently disable repo context than file context.
**Before**: observe how many keystrokes I need to perform to remove the repo chip
https://github.com/user-attachments/assets/76d6850f-4fe3-4f62-9b7b-e058a4288d54
**After**: only two backspaces needed to remove the repo chip
https://github.com/user-attachments/assets/180abcd0-f41b-4127-a8d6-c0b0e25098e2
* Select text
* Press option-shift-l to start new chat
* Confirm that the repo chip appears after the file chip
* Chat: the order of the initial …

Chat: flip order of initial context chips

---

vscode/webviews/OnboardingExperiment.module.css

Closes: https://linear.app/sourcegraph/issue/CODY-3540/login-view-doesnt-work-in-default-eclipse-view
**Before:**
https://github.com/user-attachments/assets/68b6ad11-8d68-429a-93bc-8fd8b82b41f1
---
**After:**
https://github.com/user-attachments/assets/e591ac29-5952-4836-b852-b3b4e5730bb9
Tested with Local build of VSCode and Storybook. 
Did not test on eclipse, but this is was an issue on VSCode as well

Adds Scroll to login screen

---

vscode/webviews/components/promptList/PromptList.tsx
vscode/webviews/components/shadcn/ui/badge.tsx

Part of SRCH-876
This small change is about making our badge UI a bit closer to the new badge that we have in new designs. Note that I didn't touch colors, for Cody Web color override will happen on the Sourcegraph side anyway and I don't want to change colors for all vscode themes we have while we don't have it in our design system. 
| ------- | ----- |
| <img width="411" alt="Screenshot 2024-08-28 at 21 38 28" src="https://github.com/user-attachments/assets/04330abc-3b56-4316-b10c-ed3995990b59"> | <img width="418" alt="Screenshot 2024-08-28 at 21 37 29" src="https://github.com/user-attachments/assets/6d5a1208-f175-4e61-9058-6a42e0940dbe"> | 
- Check that badges look fine for Cody Chat UI

Bring badge UI a bit closer to the new shadcn UI

---

vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/SubmitButton.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx
vscode/webviews/components/shadcn/ui/toolbar.module.css
web/CHANGELOG.md
web/package.json

Part of SRCH-810
This PR improves the search box position based on @taiyab suggestion. The logic is 
- When you submit your very first message the next textbox sticks to the bottom of the container 
- And it stays there if the content doesn't push it below 
- If there is enough content it pushes the textbox further 
- So the last textbox is always at the bottom of the container 
Note that this logic isn't standard sticky position; you still can scroll the whole container, and the textbox will scroll along with the content. 
The reason for this is that it is less jumpy at the beginning with your first message is resolving (textbox is in one place) but it doesn't take additional space from the actual content because it scrolls with the content
| ------ | ------ | 
| …

Make textbox partially sticky to the bottom

---

vscode/src/completions/providers/create-provider.test.ts
vscode/src/completions/providers/create-provider.ts

- This fixes the issue of using the `codeCompletion` model from site configuration with the Anthropic provider for PLG users. In the current state of things, we should always default to the `DEFAULT_PLG_ANTHROPIC_MODEL` on DotCom.
- Closes https://github.com/sourcegraph/cody/issues/4639
- Follow up: we should deprecate `cody.autocomplete.advanced.*` settings to avoid such cases and ensure that Cody users always use the recommended setup. 
Updated unit tests to account for this case.

Autocomplete: fix Anthropic model for PLG users

---

vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions-tests/hot-streak.test.ts
vscode/src/completions/providers/fetch-and-process-completions.ts

- When the generation is same as the suffix, the hot-streak logic trims the first correct. Adding the reproducer of the issue in the unit test.
- Closes https://linear.app/sourcegraph/issue/CODY-3542/autocomplete-suggestion-post-processing-check-for-additional-trimming
1. Added unit test to reproduce the issue

repro the hotstreak issue

---

lib/shared/src/index.ts
lib/shared/src/mentions/api.ts
vscode/src/chat/context/chatContext.ts

Fixes CODY-3554
1. Launch JetBrains instance with `CODY_DIR` pointing to cody repo with those changes checked out.
2. Make sure no `Symbols` provider is visible in chat context.

Temporarily do not show symbols provider for jetbrains

---

vscode/webviews/chat/Transcript.tsx
vscode/webviews/components/ScrollDown.tsx

Part of SRCH-810
This PR updates scroll-down button styles and makes that after you send a follow-up message we focus and scroll to view the last textbox element
Visual change has done by @taiyab designs 
| ----- | ------ |
| <img width="369" alt="Screenshot 2024-08-29 at 15 36 39" src="https://github.com/user-attachments/assets/5e375cf4-f81a-4878-9020-b8671edbdb95">  | <img width="379" alt="Screenshot 2024-08-29 at 15 36 30" src="https://github.com/user-attachments/assets/0d33a4c7-d9e8-4639-af05-c9f3a488c2ce"> |
- Manual checks on Cody Chat UI

Focus textbox after we submit a follow-up message

---

vscode/webviews/CodyPanel.tsx
vscode/webviews/tabs/HistoryTab.story.tsx
vscode/webviews/tabs/HistoryTab.tsx
vscode/webviews/tabs/TabsBar.tsx
vscode/webviews/tabs/utils.ts

Part of SRCH-810
This PR adds zero state for the history tab by @taiyab designs listed [here](https://www.figma.com/design/f078wFMKsIOaEwj7Iwj5xy/⬜%EF%B8%8F--Unified-Cody?node-id=5081-155750&node-type=FRAME&t=E311cWtgz19OTYip-0) 
Note that colors might be different compared to what we have in Figma since Figma designs operate with updated design components (we will update our component implementation after the release), for now, I used the standard UI that we have in the current cody chat implementation
- Go to the history tab
- Remove all chats
- Check that zero state look good and start a new chat button works as expected

Add zero state for history tab

---

agent/src/agent.ts

Fixes https://linear.app/sourcegraph/issue/CODY-3553/continuous-loading-on-clicking-apply-button.
See the scenario for https://linear.app/sourcegraph/issue/CODY-3553/continuous-loading-on-clicking-apply-button
make sure workspace uri is file schemed

Fix workspace uri

---

agent/src/cli/command-chat.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatsController.ts
vscode/src/chat/chat-view/ContextRetriever.ts
vscode/src/chat/chat-view/context.ts
vscode/src/chat/clientStateBroadcaster.ts
vscode/src/chat/context/chatContext.ts
vscode/src/chat/protocol.ts
vscode/src/main.ts
vscode/src/repository/git-extension-api.ts
vscode/src/repository/repo-metadata-from-git-api.ts
web/lib/components/use-cody-agent.ts

Kills off RemoteSearch and separate code path for enterprise context. Also kills off the legacy context for PLG. Both are replaced by a unified context-fetching path that runs through the `ContextRetriever` class.
This maintains behavioral parity, as verified by this spreadsheet: https://docs.google.com/spreadsheets/d/1DWxPW6ktY4XgM_IEBw10hjpI00mqcv08-APOtpNfaAY/edit
This also inadvertently fixes a bug where we can return empty context if we receive a context result from the server with a negative end line.
Run against s2 and dotcom with new and old context with example queries.

kill RemoteSearch, unify context fetching paths

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/get-experiment-model.ts
vscode/src/completions/providers/get-model-info.ts

Cherry-pick
- Autocomplete: Add direct routing for experimental models. [pull/5356](https://github.com/sourcegraph/cody/pull/5356)
- Autocomplete: Split create provider into seperate files. [pull/5394](https://github.com/sourcegraph/cody/pull/5394)
updated version and changelog

Hitesh/vscode 1.32.6 patch release

---

lib/prompt-editor/src/BaseEditor.module.css
vscode/webviews/themes/jetbrains.css

Closes:
https://linear.app/sourcegraph/issue/CODY-3564/consistent-styling-issues-with-light-theme-on-windows
Also:
- Adds a native look to scrollbars
- fixes padding on input box
Tested locally with IntelliJ 2023.2 on multiple theme
| Theme | Before | After |
|--------|--------|--------|
| Light | <img width="300" alt="Screenshot 2024-08-30 at 12 52 06" src="https://github.com/user-attachments/assets/3b392ff7-82b9-4bf8-9583-b389333b5308"> | <img width="300" alt="Screenshot 2024-08-30 at 12 52 25" src="https://github.com/user-attachments/assets/d04f6bae-4dbb-4b31-99cf-fd0422b09980"> |
| Dark | <img width="300" alt="Screenshot 2024-08-30 at 12 52 45" src="https://github.com/user-attachments/assets/c64f9cf2-d7a3-44e2-80bb-e61a31b98afb"> |<img width="300" alt="Screenshot 2024-08-30 at 12 52 …

Fixes Light theme list colors, fixes scroll bars fixes paddings

---

vscode/webviews/tabs/AccountTab.tsx

Fixes CODY-3549
1. Build with JetBrains using CODY_DIR
2. Open `Accounts` tab
3. Click `Switch account...`
4. Make sure after the switch webui is not crashing and `Accounts` tab is still visible

Fix crash on account switching

---

vscode/src/chat/chat-view/ChatsController.ts
vscode/webviews/tabs/TabsBar.tsx

Fixes https://linear.app/sourcegraph/issue/CODY-3530/export-chat-history-doesnt-do-anything.
Try chat export in JetBrains.
Send the command notification when the IDE is not VSC.

Trigger `cody.chat.history.export` command when the IDE is not VSC

---

lib/prompt-editor/src/nodes/MentionComponent.tsx
vscode/webviews/App.module.css
vscode/webviews/chat/cells/Cell.tsx
vscode/webviews/tabs/TabsBar.module.css
vscode/webviews/tabs/TabsBar.tsx
web/CHANGELOG.md
web/package.json

Prior to this PR tabs UI tooltips were using just media query which doesn't work in the case of sharable webview where the client usually has a bigger viewport than actual cody chat UI sizes. 
This PR basically uses a container query to decide when we should show tooltips for tabs UI.
- Manual checks on Cody Chat UI

Fix floating ui elements (tooltips and popovers)

---

vscode/changelog_experimental.md
vscode/scripts/version-bump.ts

This adds a step in the version bump to experimentally generate the changelog with the [devx-service changelog](https://github.com/sourcegraph/devx-service/tree/main/cmd/changelog). Currently this would just be to see what the autogenerated changelog looks like compared to the manually updated one. It will be pretty rough before people start updating their PRs to include changelogs and update their title format.
Ran locally and committed the output.
Adds automatic changelog generation to the release script.

added(changelog): updated version bump to build experimental changelog

---

lib/prompt-editor/src/mentions/mentionMenu/MentionMenu.tsx

Fixes [SRCH-698](https://linear.app/sourcegraph/issue/SRCH-698/cursor-jumping-in-safari-when-you-try-to-pick-suggestions-with-cursor)
| --------  | ------- |
| <video src="https://github.com/user-attachments/assets/027a71ac-1f06-4f1c-aaa6-cc90028426a3" /> | <video src="https://github.com/user-attachments/assets/b7a039b8-04d2-426c-908f-fead0267d750" /> |
Safari has a weird problem with focus handling and event propagation; as a result, when you try to select an item in the mentioned menu, a down event triggers focus loss on the contenteditable area (makes sense) and moves the cursor at the beginning of the input. It happens only in Safari, which makes me think that event dispatching to handle portal anchor element propagation doesn't work right in Safari. 
This PR simply …

Cody Web: Fix mention selection in Safari

---

agent/CHANGELOG.md
agent/package.json
agent/recordings/cody-chat_103640681/recording.har.yaml
agent/src/cli/__snapshots__/command-chat.test.ts.snap
agent/src/cli/command-auth/AuthenticatedAccount.ts
agent/src/cli/command-auth/command-accounts.ts
agent/src/cli/command-auth/command-auth.ts
agent/src/cli/command-auth/command-login.ts
agent/src/cli/command-auth/command-logout.ts
agent/src/cli/command-auth/command-whoami.ts
agent/src/cli/command-auth/messages.ts
agent/src/cli/command-chat.test.ts
agent/src/cli/command-chat.ts

Fixes Cody-3261.
Fixes CODY-2967.
Fixes CODY-2909.
Previously, Cody CLI users got a poor experience if they had provided expired credentials with `SRC_ACCESS_TOKEN`. The `cody chat` command reported that the user was "not logged in" and `cody auth login` confusingly reported that the user was already logged in.
Now, Cody CLI reports a helpful error message saying the user has invalid credentials and documents how to fix the problem by creating a new access token.
This fix ended up being harder to implement than I original expected because the code related to authentication was badly organized. Specifically, we didn't distinguish between error cases (invalid token) and unauthenticate cases (the user hasn't logged in yet). I used this issue as an opportunity to clean up the code so that all …

CLI: fix error handling for invalid access tokens

---

vscode/webviews/tabs/AccountTab.tsx

Fixes https://github.com/sourcegraph/jetbrains/issues/2174
1. Login to Cody ad free user
2. Switch to `Accounts` panel
3. `Upgrade` button should be visible
4. clicking it should open [https://sourcegraph.com/cody/subscription](https://sourcegraph.com/cody/subscription)

Add 'Upgrade' button to Accounts panel for free users

---

vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatsController.ts

Fixes https://github.com/sourcegraph/jetbrains/issues/2173.
See the issue: https://github.com/sourcegraph/jetbrains/issues/2173
1. log in to an account 
2. write something in chat
3. switch account
4. review the chat history
expected:
The chat from the first account should not appear in the account switched into.

Fix account switching and chat history issue

---

agent/src/global-state/AgentGlobalState.ts

Previously, server-managed global storage had some special cases for specific keys like "last recently used server endpoint", which is only relevant for client-managed global storage. This was problematic because the Eclipse plugin had a bug where enterprise users couldn't use the plugin at all with server-managed global storage after moving to the webview-based login flow (which involved stopping sending configurations about the connected endpoint URL).
Now, when using server-managed global storage, it works 100% like in VS Code with no special cases for special keys. This fixes the critical bug for Eclipse where enterprise users would authenticate successfully but all network requests would fail because they get sent to dotcom (default    endpoint) instead of their enterprise instance. …

Agent: fix bug in server managed global storage

---

vscode/webviews/chat/Transcript.test.tsx
vscode/webviews/chat/cells/messageCell/BaseMessageCell.tsx
vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx
vscode/webviews/components/shadcn/ui/tooltip.tsx
vscode/webviews/tabs/TabsBar.module.css
vscode/webviews/tabs/TabsBar.tsx
web/CHANGELOG.md
web/package.json

This PR updates tabs UI based on the latest suggestions from @taiyab 
| ----- | ------ |
| <video src="https://github.com/user-attachments/assets/f8fdc326-f109-4943-8b93-5da46d87ed7d" /> | <video src="https://github.com/user-attachments/assets/700f417f-6c7e-4d97-b7a6-f4e1a3b0f064" /> |
- Show the "New chat" button unconditionally as global actions on the right side 
- Always show subactions in separate rows below the main tabs row
- Don't hide labels for sub-actions 
- Change label text for sub-actions like export and delete
We still rely on containers query for showing/hiding labels for tab items, but this PR makes breakpoints for Cody Web different (since Cody Web has different tab configurations it makes sense to hide labels with a bit smaller screens)
Also, I've …

Improve tabs UI for different consumers

---

agent/CHANGELOG.md
agent/package.json

I was going to release 5.5.13 but found out that this version was already released
https://github.com/sourcegraph/cody/actions/runs/10550894460 so I'm bumping up to 5.5.14 instead.
n/a

Agent: bump to version 5.5.14

---

package.json
pnpm-lock.yaml
vscode/package.json
vscode/src/chat/clientStateBroadcaster.ts
vscode/src/chat/context/chatContext.ts
vscode/src/repository/repo-metadata-from-git-api.ts
web/package.json

context: https://linear.app/sourcegraph/issue/PROD-264/one-pager-for-how-to-get-this-set-up-using-openctx
We have [added](https://github.com/sourcegraph/openctx/pull/199) `meta.mentions.autoInclude` property for OpenCtx providers. The providers which set that to `true` will be used to include the mentions they return as initial context items. We are also passing the active file uri and codebase names to the `mentions` function. 
Set the following as the vs code setting and see the hello world mention item chip appearing as the default context item. 
```json
"openctx.providers": {
"https://openctx.org/npm/@openctx/provider-hello-world": true
}
```
Include initial context from OpenCtx providers.

Include initial context from OpenCtx providers. 

---

lib/shared/src/configuration.ts
lib/shared/src/index.ts
lib/shared/src/utils.ts
vscode/src/completions/create-multi-model-inline-completion-provider.ts

Mutating the fields in this object will not do anything. The `ReadonlyDeep<T>` type helper helps us avoid mistakes where the fields were mutated and someone expected that to do something.
No behavior change.
CI

make ClientConfiguration readonly to prevent mistakes

---

vscode/src/services/utils/codeblock-action-tracker.ts

Previously, the "Insert code at cursor" button always added the code at the start of the cursor or text selection. This was problematic because when you have a text selection, you intuitively expect it to replace the whole selection, not add the code. This PR fixes the issue by replacing when there is a text selection, and adding when there is a cursor.
Manually tested this with a text selection and with a cursor.
* The "Insert code at cursor" action now replaces the selected text instead of adding it to the start of the selection. The behavior is unchanged when there is a cursor (no text selection).

Chat: make "insert code at cursor" replace selection

---

agent/src/agent.ts
agent/src/cli/command-chat.ts
agent/src/cli/legacyCodyClientName.ts
agent/src/vscode-shim.ts
vscode/src/extension-client.ts
vscode/src/main.ts

Fixes CODY-3597
Previously, Cody CLI used the client name "jetbrains" to work around an issue where old SG instances would reject LLM requests for unknown client names. This issue was fixed in July but it will take some months until we can assume all users have upgraded their instances.
Now, we can use the client name "cody-cli" for telemetry and only "jetbrains" for the LLM requests.
n/a

CLI: use client name "cody-cli" instead of "jetbrains"

---

lib/prompt-editor/src/mentions/mentionMenu/useMentionMenuData.ts
lib/prompt-editor/src/plugins/atMentions/useChatContextItems.tsx
lib/shared/src/mentions/query.ts
vscode/src/chat/context/chatContext.ts
web/lib/components/CodyWebChat.tsx

This PR fixes regression after https://github.com/sourcegraph/cody/pull/5379
In https://github.com/sourcegraph/cody/pull/5379 remote repository context logic was removed, which was important for Cody Web. 
When you start typing `@<mention-term>` by default, we do a file mention search; in Cody Web world, we rely on remote context repository API to look for files within these repositories from remote context API. This is convenient when you open Cody Web on the repository page, and automatically, your file and symbol mentions will be scoped to this repo. 
Since this context remote repository has been removed this PR passes remote repositories info for mentions directly through API (it's even better because we don't rely on the internal chat controller state anymore) 
Note that this change …

Fix Cody Web remote context for mentions

---

vscode/src/chat/chat-view/context.ts

Test locally with the following query against s2: `@sourcegraph/cody where do we check for content attribution?`
s2 returns a result with a negative end line, which causes the rest of the context items to be discarded. This should not happen with this change.

prevent invalid ranges from borking context

---

vscode/CHANGELOG.md
vscode/src/commands/context/git-api.ts
vscode/src/commands/scm/source-control.ts

CLOSE  https://linear.app/sourcegraph/issue/CODY-3601/bug-error-failed-to-get-git-output-when-using-commit-generation-on https://github.com/sourcegraph/cody/issues/4863
This commit fixes an issue where the `Generate Commit Message` command would fail on Windows due to incorrect parsing of the git diff output. The change ensures that the file path is correctly identified even when the diff output does not contain the full file path specifically on Windows
Manually tested the `Generate Commit Message` command on both Windows and Mac to ensure it works as expected.
We also have an e2e test covering this command on all platforms, will look into it separately on why this error didn't happen during the e2e tests
Confirmed the command still works correctly on Mac:
Command: Fixed an issue where …

fix: handle git diff path parsing on Windows

---

agent/src/AgentTextEditor.ts
vscode/CHANGELOG.md
vscode/src/edit/manager.ts

[Linear Issue
](https://linear.app/sourcegraph/issue/CODY-3234/prefer-visual-indication-of-running-status-after-clicking-a-command#comment-459cd279)
This PR addresses two key issues with the Generate Tests and Document Code commands:
1.	Lack of User Feedback: Previously, when users clicked on Generate Tests or Document Code, there was no immediate visual feedback, leaving users uncertain whether the commands were executed. This often led to users repeatedly clicking the buttons, as they couldn’t see any change or indication that something was happening.
2.	User Experience Improvement: To mitigate this issue, I’ve implemented a change where the cursor now jumps to the appropriate location when either command is executed. This provides instant feedback, informing users that the command is …

Commands ux improvements

---

lib/shared/src/misc/rpc/webviewAPI.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
vscode/test/e2e/command-core.test.ts
vscode/webviews/AppWrapperForTest.tsx
vscode/webviews/Chat.story.tsx
vscode/webviews/Chat.tsx
vscode/webviews/CodyPanel.tsx
vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx
vscode/webviews/chat/components/WelcomeMessage.test.tsx
vscode/webviews/chat/components/WelcomeMessage.tsx
vscode/webviews/components/UserAvatar.module.css
vscode/webviews/components/UserAvatar.story.tsx
vscode/webviews/components/UserAvatar.tsx
vscode/webviews/components/promptList/PromptList.story.tsx
vscode/webviews/components/promptList/PromptList.tsx
vscode/webviews/components/promptList/fixtures.ts
vscode/webviews/components/promptSelectField/PromptSelectField.story.tsx
vscode/webviews/components/promptSelectField/PromptSelectField.tsx
vscode/webviews/components/promptSelectField/fixtures.ts
vscode/webviews/components/shadcn/ui/command.tsx
vscode/webviews/prompts/PromptsTab.story.tsx
vscode/webviews/prompts/PromptsTab.tsx
vscode/webviews/tabs/TabsBar.tsx
web/CHANGELOG.md
web/package.json

Revert https://github.com/sourcegraph/cody/pull/5438
This PR reverts new prompts UI, reasoning 
- The new UI doesn't take into account a good zero/empty state
- The current JetBrains integration doesn't use the new prompt UI due to a release freeze in the JetBrains integration repository 
We will include a new polished UI in the next stable release
| ------ | ------ |
| <img width="408" alt="Screenshot 2024-09-02 at 20 24 49" src="https://github.com/user-attachments/assets/305df1fb-63cc-4fe3-9e18-12b685257395"> | <img width="408" alt="Screenshot 2024-09-02 at 20 25 42" src="https://github.com/user-attachments/assets/018f833e-83b1-443c-9dbe-ec66328c2014"> |
- CI is green

Revert "Improve Prompts & Commands list UI #5438"

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ClientSideConfig.kt
lib/shared/src/llm-providers/anthropic/chat-client.ts
lib/shared/src/llm-providers/groq/chat-client.ts
lib/shared/src/llm-providers/index.ts
lib/shared/src/llm-providers/ollama/chat-client.ts
lib/shared/src/llm-providers/utils.ts
lib/shared/src/models/index.ts
vscode/src/models/sync.ts

This change adds support for configurable model options in the local configured LLM providers available behind `cody.dev.models` feature. 
The `CompletionsModelConfig` type has been extended to include an `options` field, which allows users to specify additional settings for the model, such as temperature, max tokens, and whether to use streaming.
The changes have been implemented across the various LLM provider chat clients (Anthropic, GROQ, and Ollama) to handle the new configuration options.
Additionally, the `getCompletionsModelConfig` utility function has been updated to extract the `options` field from the model's client-side configuration.
Finally, the `ChatModelProviderConfig` interface in the VSCode extension has also been updated to include the `options` field, allowing users to …

Dev: add support for configurable model options

---

vscode/src/edit/manager.ts

This PR refactors the telemetry event for 'cody.smart-apply...' event to use a consistent name for the various `selectionType` and update the action to be a verb as it's intended.
Changes:
- Standardized the event name to `cody.smart-apply:selected` for all selection types.
- Updated the `action` to `selected` to indicate the action being recorded.
- Included a metadata object to capture the `selectionType` with a value of 1.
Tested locally

Telemetry: Update naming for smart-apply

---

lib/shared/src/models/index.ts
vscode/CHANGELOG.md
vscode/webviews/components/ChatModelIcon.tsx
vscode/webviews/components/modelSelectField/ModelSelectField.tsx

CLOSE https://linear.app/sourcegraph/issue/CODY-3628/bug-icon-display-incorrectly-for-anthropic-and-openai-models
PR to fix issues where local models are showing up twice in the model list, and the icons are not displayed correctly for openAI and Anthropic models.
- Updates the `ChatModelIcon` component to display the correct icon based on the model provider instead of the model ID.
- Fixes an issue where local models were being duplicated in the model list by filtering out any models that are already in the cache when adding new models.
- The `ChatModelIcon` component now expects the model provider instead of the model ID as the input.
1. Icons are not displayed correctly for openAI and Anthropic models: 
2. Local Models are duplicated:
Fixed:
Chat: Model list now shows the correct icon …

Chat: show correct model icons and deduplicate local models

---

vscode/src/chat/protocol.ts
vscode/src/release.test.ts
vscode/src/release.ts

updating the blog URL to the new changelog format. Hoping it will be a temp change for now, I think we should send users to a tagged version instead of a general landing page but we will need to coordinate with PMM to figure that out
N/A

update blog to new changelog URL

---

vscode/src/chat/clientStateBroadcaster.ts
vscode/src/prompt-builder/utils.ts
vscode/test/e2e/chat-atFile.test.ts
vscode/test/e2e/command-custom.test.ts
vscode/test/e2e/initial-context.test.ts

Closes SRCH-1013.
This change enhances the display of context items in the client state broadcaster by:
- Always adding the current file item, with the file name as the description
https://linear.app/sourcegraph/issue/SRCH-1013/always-show-current-file-mention-option-even-if-there-is-a-selection
Manual testing.

feat(chat): improve context item display in client state broadcaster

---

vscode/src/auth/auth.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/services/AuthProviderSimplified.ts

Follow https://github.com/sourcegraph/cody/pull/5325
This PR updates the current auth to replace getAuthReferralCode with the new getCodyAuthReferralCode added in https://github.com/sourcegraph/cody/pull/5325
All the current tests should pass to confirm this change works the same as before.

Auth: use getCodyAuthReferralCode

---

lib/shared/src/cody-ignore/ignore-helper.ts
vscode/CHANGELOG.md

CLOSE https://linear.app/sourcegraph/issue/CODY-3448/auto-edit-does-not-work-with-ipynb-files
This change updates the IgnoreHelper to properly handle notebook cell URIs when the .cody/ignore file is enabled. Previously, Cody would treat notebook cells as ignored files, which was incorrect. This fix replaces the notebook cell scheme with the file scheme and removes the fragment containing the cell ID, so that the same logic can be used for regular files.
1. Try running the Document Command in an `ipynb` file and verified that it works and you no longer see the pop-up about file being ignored:
2. Create a .cody/ignore file and set it to ignore all .ipynb files:
```
*.ipynb
```
3. Try running the Document Command again in an `ipynb` file and verified that you are now seeing the pop-up about …

Cody Ignore: handle notebook cell URIs

---

agent/src/agent.ts
lib/shared/src/prompt/prompt-string.ts
vscode/src/services/utils/codeblock-action-tracker.ts
vscode/webviews/chat/extract-file-path.ts

Fixes https://github.com/sourcegraph/jetbrains/issues/2195
Fixes for Smart Apply:
1. Add proper support for paths with spaces
2. Add support for absolute paths
* Build with JetBrains plugin and:
1. Create new `quicksort.py` file outside of your workspace, in directory with space in name
3. Open that file and ask Cody to give you an quicksort imlementation
4. Use Smart Apply
5. Make sure code was inserted in `quicksort.py` properly

Fix how smart apply handles various absolute paths and spaces in paths

---

vscode/src/common/persistence-tracker/index.test.ts
vscode/src/common/persistence-tracker/index.ts
vscode/src/common/persistence-tracker/types.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/logger.test.ts
vscode/src/completions/logger.ts
vscode/src/non-stop/FixupController.ts

This PR adds a persistence telemetry event which logs the git diff of the file for each suggestion after 30 seconds **only for dotCom users and public github Repos** in the private metadata field.
The utility of this data is:
1. For the completions with `negative CAR` values, this event can give the actual code typed by the user after rejecting cody suggestions. These are typically called `negative examples` which can be used to improve the completions quality.
2. The `git diff` at different location than the suggestion one can give us an initial dataset for `next-edit-suggestion`. This data can be used to draw insights into `next-edits` (for the same file).
3. All the online datasets typically uses BM25/Embeddings as the context sampler but ignores the user activity like recent edits. …

add suggestions diff tracker for online context and nes dataset

---

agent/src/AgentFixupControls.ts
agent/src/agent.ts
agent/src/edit.test.ts
vscode/src/non-stop/codelenses/provider.ts

Fixes https://github.com/sourcegraph/jetbrains/issues/2197.
Try to reproduce https://github.com/sourcegraph/jetbrains/issues/2197.
Move updateCodeLenses from agent.ts to AgentFixupControls.ts

Move updateCodeLenses logic to AgentFixupControls

---

vscode/CHANGELOG.md
vscode/src/commands/context/git-api.test.ts
vscode/src/commands/context/git-api.ts
vscode/test/e2e/command-commit.test.ts
vscode/test/e2e/command-custom.test.ts

FIX https://github.com/sourcegraph/cody/issues/4863
This PR fixes an issue where the generate commit message doesn't work on Windows:
Root cause: the displayPath function returns file path native to the OS system, while the file path returned by the diff output is following the unix one, causing the file match logic to always be false.
This PR fixed this by always replace all \\ used by Windows with '/' before doing matching.
Summary:
- Fixed an issue where the `Generate Commit Message` command would fail on Windows due to file path handling in the `getContextFilesFromGitDiff` function.
- Normalized file paths to use forward slashes instead of backslashes to ensure consistent handling across platforms.
- Improved the logic for matching the git diff output to the actual file URIs to handle …

fix(Generate Commit Message): handle file paths in git diff on Windows

---

lib/shared/src/llm-providers/groq/chat-client.ts
vscode/CHANGELOG.md

Fix: https://linear.app/sourcegraph/issue/CODY-3672
This PR fixes an issue where the `chatParams` was being passed as a parameter object when using the local GROQ model provider, causing all network requests to fail when using the local config models.
The fix is to properly destructure the `chatParams` object before passing it to the fetch request.
- Destructure the `chatParams` object before passing it to the fetch request in the `groqChatClient` function.
- Verified that the local GROQ model provider now works correctly when using the `chatParams` object.
Dev: Fixed an issue where incorrect request parameters caused stream requests to fail when using local OpenAI-compatible model provider through the groqChatClients.

fix(dev): fix params used by groqChatClient

---

agent/src/autocomplete.test.ts
lib/shared/src/experimentation/FeatureFlagProvider.test.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
lib/shared/src/misc/observable.test.ts
lib/shared/src/misc/observable.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/completions/completion-provider-config.ts
vscode/src/completions/context/context-mixer.test.ts
vscode/src/completions/context/context-mixer.ts
vscode/src/completions/context/context-strategy.ts
vscode/src/completions/context/retrievers/jaccard-similarity/history.ts
vscode/src/completions/context/retrievers/jaccard-similarity/jaccard-similarity-retriever.ts
vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/completions/create-multi-model-inline-completion-provider.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions-tests/hot-streak.test.ts
vscode/src/completions/inline-completion-item-provider-e2e.test.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/logger.test.ts
vscode/src/completions/logger.ts
vscode/src/completions/providers/create-provider.test.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/get-experiment-model.ts
vscode/src/main.ts
vscode/src/testutils/mocks.ts

Make it so our autocomplete logic reacts to config and feature flag changes using Observables, instead of the current situation where there are many different ad-hoc ways configuration and feature flag values are passed through. This simplifies (or at least standardizes) the code, reduces bugs, and (once this kind of change is applied everywhere in our code) eliminates the need for users to reload the editor to pick up new config.
e2e tests. Also try changing Cody autocomplete configs and signing in/out and ensure that the right config is loaded.

react to config/feature-flag changes using Observables in autocomplete

---

agent/src/global-state/AgentGlobalState.ts

Fixes CODY-3675
`LocalStorage` by default have quota of 5MB.
It is easy to exceed that, as chat history contains content of the context files, which sometimes can be large.
For now I bumped quota ro 256MB, but we should also implement some cleanup strategy.
1. I checked my existing history size:
➜  jetbrains git:(main) ✗ ls -lh ~/Library/Application\ Support/Cody-nodejs/JetBrains-globalState/ | grep chatHistory
-rw-r--r--  1 pkukielka  staff   2,6M  9 wrz 14:36 cody-local-chatHistory-v2
2. I decreased quota to 2MB, and run this PR with JetBrains - it failed to start throwing `QUOTA_EXCEEDED_ERR` error.
3. I changed it to 256MB and rebuilded - it starts fine now.

Increase default LocalStorage size from 5MB to 128MB

---

vscode/src/certs.js

In a VS Code extension debug host on Linux, all GraphQL requests fail with a TLS error `cannot find local issuer certificate`. This fixes that issue.
This started occurring for me on VS Code 1.93.0. I can't find anything about it online, although https://github.com/microsoft/vscode/issues/187716 *might* be related. This fix seems harmless and has been a long-recommended way of adding CAs anyway (https://stackoverflow.com/questions/68896243/how-to-properly-configure-node-js-to-use-self-signed-root-certificates).
On Linux, run Cody in the debug extension host and ensure that the chat window signs in upon initial load.

fix linux "cannot find local issuer certificate" auth error

---

vscode/CHANGELOG.md
vscode/webviews/chat/components/FeedbackButtons.tsx

CLOSE https://linear.app/sourcegraph/issue/CODY-3682/feedback-buttons-not-working
The order of the `setFeedbackSubmitted` and `feedbackButtonsOnSubmit` calls was reversed, which could lead to an inconsistent state. This commit fixes the order to ensure the feedback submission state is updated before the callback is invoked.
Before and After: 
Click on the thumb up / down button underneath a LLM response, nothing happened:
Click on the thumb up / down button underneath a LLM response to verify there is now a "check" mark to indicate the feedback button was clicked and submitted successfully:
Chat: Fixed feedback buttons not working in chat.

fix(chat): reorder feedback button submission logic

---

agent/CHANGELOG.md
agent/package.json
agent/recordings/cody-chat_103640681/recording.har.yaml
agent/src/TestClient.ts
agent/src/cli/command-bench/strategy-chat.ts
agent/src/cli/command-chat.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatsController.ts
vscode/src/chat/clientStateBroadcaster.ts
vscode/src/chat/protocol.ts
vscode/src/commands/execute/explain-history.ts
vscode/src/commands/execute/explain.ts
vscode/src/commands/execute/smell.ts
vscode/src/commands/execute/terminal.ts
vscode/src/commands/execute/test-chat.ts
vscode/src/commands/services/runner.ts
vscode/webviews/chat/Transcript.tsx

Fixes CODY-3687
Previously, `cody chat --context-repo REPO` didn't use the provided repo as context due to a regresion in the PR https://github.com/sourcegraph/cody/pull/5379 This bug was limited to version 5.5.14 of the CLI, it was not part of 5.5.13.
This PR fixes the bug by adding repo context to the `'submit'` `contextItem` property where we previously only sent files.
Manually tested with this command
```
❯ pnpm agent chat --show-context --context-file agent/README.md --context-repo github.com/sourcegraph/cody -m 'what is the agent?'
...
> Context items:
> 1. /Users/olafurpg/dev/sourcegraph/cody/agent/agent/README.md
> 2. https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody/-/blob/agent/src/__tests__/graph-test/README.md
> 3. …
```

CLI: fix `--context-repo`

---

vscode/webviews/themes/visual-studio.css

CLOSE https://linear.app/sourcegraph/issue/CODY-3685
This commit updates the scrollbar color in the visual-studio.css file to better match the Visual Studio theme. Specifically, it changes the background colors of the scrollbar slider to use the `--visualstudio-toolwindowbackground` variable instead of the previous values.
Manually test the appearance of the webviews in the Visual Studio theme to ensure the scrollbar styles are updated as expected.
Before

fix(webviews): update visual-studio.css scrollbar color

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/completions/create-multi-model-inline-completion-provider.ts
vscode/src/completions/inline-completion-item-provider-config-singleton.ts
vscode/src/completions/inline-completion-item-provider-e2e.test.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/inline-completion-item-provider.ts

[Solves Linear Issue
](https://linear.app/sourcegraph/issue/CODY-3331/introduce-option-to-control-suggestion-pause-time-in-vscode) to introduce configurable trigger delays before making autocomplete suggestions for people who might want to slow down autocomplete suggestions for different reasons
[Added a loom video](https://www.loom.com/share/30266970e3c640e4a3cd2accce8e1503) showing trigger delay in different cases with the debugger. 
The way I tested this was first setting the trigger delay to really high and saving it in the settings of Vscode(as shown in the video) and then the slow manifestation of completion suggestions was obvious and then I lowered the trigger delay to 0 in the settings and the completion suggestions were much much faster thereby proving that the setting for …

Adding trigger delay to the code

---

lib/shared/src/logger.ts

- No functional changes
- Disabled logger to unclutter CI output. Example [here](https://github.com/sourcegraph/cody/actions/runs/10786462290/job/29913368825).
CI

VS Code: disable logger in unit tests

---

lib/shared/src/completions/types.ts
vscode/src/completions/context/context-mixer.test.ts
vscode/src/completions/context/context-mixer.ts
vscode/src/completions/context/retrievers/bfg/bfg-retriever.ts
vscode/src/completions/context/retrievers/jaccard-similarity/bestJaccardMatch.test.ts
vscode/src/completions/context/retrievers/jaccard-similarity/bestJaccardMatch.ts
vscode/src/completions/context/retrievers/jaccard-similarity/jaccard-similarity-retriever.ts
vscode/src/completions/context/retrievers/lsp-light/lsp-light-retriever.ts
vscode/src/completions/context/retrievers/recent-edits/recent-edits-retriever.ts
vscode/src/completions/context/retrievers/tsc/tsc-retriever.ts
vscode/src/completions/context/utils.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/logger.test.ts
vscode/src/completions/logger.ts
vscode/src/completions/model-helpers/__tests__/test-data.ts
vscode/src/graph/lsp/symbol-context-snippets.ts

1. The PR fixes the `contextCandidates` logged in the `inlineCompletionItemContext` to the `rankedContextCandidates`. Without this, the offline dataset is not much useful, since the candidates are limited to items sent in the final prompt, and hence we are not able to evaluate the effect on other context items. 
2. Adds a field `identifier` to the `AutocompleteContextItem` to help identify, from which retriever does this item come from. 
1. Added the test cases to check payload limits before logging 
2. CI Checks

fix context logging payload and add identifier field in context snippets

---

lib/prompt-editor/src/BaseEditor.module.css
vscode/webviews/themes/jetbrains.css

Let's backport this change to `main` (https://github.com/sourcegraph/cody/pull/5403).
- ci
- no issue in light theme

Fixes Light theme list colors

---

agent/src/global-state/AgentGlobalState.ts

Backport of https://github.com/sourcegraph/cody/pull/5504
Fixes CODY-3675
`LocalStorage` by default have quota of 5MB.
It is easy to exceed that, as chat history contains content of the context files, which sometimes can be large.
For now I bumped quota ro 256MB, but we should also implement some cleanup strategy.
1. I checked my existing history size: ➜ jetbrains git:(main) ✗ ls -lh ~/Library/Application\ Support/Cody-nodejs/JetBrains-globalState/ | grep chatHistory -rw-r--r-- 1 pkukielka staff 2,6M 9 wrz 14:36 cody-local-chatHistory-v2
2. I decreased quota to 2MB, and run this PR with JetBrains - it failed to start throwing `QUOTA_EXCEEDED_ERR` error.
3. I changed it to 256MB and rebuilded - it starts fine now.

Increase default LocalStorage size from 5MB to 256MB (#5504)

---

lib/prompt-editor/src/mentions/mentionMenu/MentionMenuItem.module.css
lib/prompt-editor/src/mentions/mentionMenu/MentionMenuItem.test.tsx
lib/prompt-editor/src/mentions/mentionMenu/MentionMenuItem.tsx
vscode/CHANGELOG.md
vscode/test/e2e/mention-repository.test.ts

CLOSE https://linear.app/sourcegraph/issue/CODY-3499/increase-width-of-remote-repo-selector-in-vs-code-sidebar
The repository titles in the mention menu were displaying the full repository path, which could make the menu items too long to be displayed in the dropdown menu.
This change shortens the repository titles to only show the repository name (the part after the last slash) rather than including the codebase as display name since this open more spaces to display the actual repository name, and secondly, it is not common for our customers to host the same repository in two different codehost, and then have both of them imported to their Sourcegraph instance.
Manually verify that repository titles in the mention menu are shortened as expected.
1. Connect to S2
2. @-mention `Remote …

Chat: shorten remote repository titles in mention menu

---

vscode/webviews/components/CollapsiblePanel.tsx
vscode/webviews/tabs/HistoryTab.tsx

This PR adds an id prop to the History Chat items that allows dev identify chat history by period in E2E test 
- Adds an `id` prop to the `CollapsiblePanel` component to provide a unique identifier
- Updates the `Collapsible` and `CollapsibleContent` components to use the `id` prop
- Ensures each `CollapsiblePanel` in the `HistoryTab` has a unique identifier based on the period
Green CI - Everything should works the same.

Chat: add unique identifiers to CollapsiblePanel components

---

vscode/webviews/CodyPanel.tsx
vscode/webviews/index.html

This fixes an issue where clicking on the "Export" chat history button in Eclipse would open the chat history as json in the current webview, instead of showing up as a download dialogue.
- Open the blob link in a new window instead of current window
- Add timestamp to the downloaded file name to make it unique
- Update Content Security Policy to allow more connections for the webview
Run this branch in Eclipse to confirm the Chat History export button works. Here is a demo when running this branch from the latest eclipse main branch:
https://github.com/user-attachments/assets/4ef85c4d-0cb5-4130-9d57-c4e5c78183db

Chat: update chat history export button

---

vscode/CHANGELOG.md
vscode/package.json

Cherry-pick
Autocomplete Logging: The PR fixes the contextCandidates logged in the inlineCompletionItemContext. [pull/5507](https://github.com/sourcegraph/cody/pull/5507)
Updated version and changelog

VS Code: Release 1.34.2

---

lib/shared/src/auth/authStatus.ts
lib/shared/src/auth/types.ts
lib/shared/src/misc/observable.test.ts
lib/shared/src/misc/observable.ts
lib/shared/src/telemetry-v2/TelemetryRecorderProvider.ts
vscode/src/auth/account-menu.ts
vscode/src/auth/auth.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatsController.ts
vscode/src/commands/GhostHintDecorator.ts
vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/completions/create-multi-model-inline-completion-provider.ts
vscode/src/completions/logger.ts
vscode/src/edit/input/get-input.ts
vscode/src/edit/manager.ts
vscode/src/edit/provider.ts
vscode/src/extension.node.ts
vscode/src/external-services.ts
vscode/src/main.ts
vscode/src/minion/MinionController.ts
vscode/src/non-stop/FixupController.ts
vscode/src/notifications/cody-pro-expiration.test.ts
vscode/src/notifications/cody-pro-expiration.ts
vscode/src/repository/repo-name-resolver.test.ts
vscode/src/repository/repo-name-resolver.ts
vscode/src/services/AuthProvider.ts
vscode/src/services/AuthProviderSimplified.ts
vscode/src/services/telemetry-v2.ts
vscode/src/uninstall/post-uninstall.ts

No more `authProvider.instance!`.
Also move `AuthProvider.status` to `currentAuthStatus()` funcs.
Refactor helpers:
```
fastmod -e ts -F 'authProvider.statusAuthed' 'currentAuthStatusAuthed()'
fastmod -e ts -F 'authProvider.status' 'currentAuthStatus()'
```
CI

make authProvider a simple singleton, expose currentAuthStatus() sync

---

agent/src/AgentFixupControls.ts
agent/src/agent.ts
agent/src/edit.test.ts
vscode/src/non-stop/FixupController.ts
vscode/src/non-stop/codelenses/provider.ts
vscode/src/non-stop/strategies.ts

Backport of https://github.com/sourcegraph/cody/pull/5477 and https://github.com/sourcegraph/cody/pull/5428.
- see https://github.com/sourcegraph/jetbrains/issues/2197

Move updateCodeLenses logic to AgentFixupControls 

---

lib/prompt-editor/src/mentions/mentionMenu/MentionMenu.tsx

I found the label/prompt to select a remote directory confusing when using @-mention remote directories. It was not clear to me that it was possible to continue typing to search for matching directories within the repo.
Open Cody
Select Remote Directories
Check for updated label once repo selected
Update Remote Directory label.

Update Remote Directory label

---

vscode/package.json
vscode/src/non-stop/codelenses/items.ts

Close https://linear.app/sourcegraph/issue/CODY-251/bug-no-visual-indication-in-editor-when-a-users-access-token-is-no
The original issue in the linked issue has been issue, but Dom mentioned the code lenses right now are just displaying "Applying Edit Fails" on authentication error. This PR adds an if statement to display "Authentication Failed" when an authentication error occurs or "Network Disconnected" when a network error occurs during Edits.
This change adds handling for authentication errors in the codelenses, displaying a "Authentication Failed" message and providing a command to sign in.
Additionally, the "Show Rate Limit Modal" command has been removed from the package.json as this is a utils command that should not be registered for users to use.
I'm not sure how to replicate …

Edit: display authentication and network errors with code lenses

---

vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/Cell.tsx
vscode/webviews/chat/cells/contextCell/ContextCell.tsx
vscode/webviews/components/FileContextItem.tsx
vscode/webviews/components/codeSnippet/CodeSnippet.module.css
vscode/webviews/components/codeSnippet/components/CodeExcerpt.tsx
vscode/webviews/components/shadcn/ui/accordion.tsx
web/CHANGELOG.md
web/demo/App.module.css
web/lib/components/CodyWebChat.tsx
web/lib/global-styles/styles.css
web/package.json

This PR 
- Fixes styles problem with Cody Web (the whole time vs code dark theme was included in the main lib bundle, which shouldn't be used anywhere outside of storybook demos)
- Prepare one box UI (render code block only for search intent results and only for one box UI)
- Check Cody Web UI (with one box functionality)
- Check that vscode one box doesn't get any regressions

Prepare one box UI for Cody Web usage

---

lib/shared/src/auth/authStatus.ts
lib/shared/src/auth/types.ts
lib/shared/src/misc/observable.ts
vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/completions/create-multi-model-inline-completion-provider.ts
vscode/src/completions/get-inline-completions-tests/analytics.test.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/get-inline-completions.ts
vscode/src/completions/inline-completion-item-provider-e2e.test.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/create-provider.test.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/get-experiment-model.ts
vscode/src/completions/providers/get-model-info.ts
vscode/src/completions/providers/provider.ts
vscode/src/notifications/cody-pro-expiration.test.ts
vscode/src/repository/repo-name-resolver.test.ts
vscode/src/services/LocalStorageProvider.ts
vscode/src/testutils/mocks.ts

- Replaces the `authStatus` propagation in the autocomplete provider creation logic with new global getters, which are reactively updated.
CI

Autocomplete: use new `authStatus` helpers for provider creation

---

vscode/src/chat/chat-view/ChatController.ts
vscode/webviews/chat/Transcript.tsx

context: https://sourcegraph.slack.com/archives/C07EQBRSF35/p1726126230126479
Removed the mention chips text from queries sent for intent detection for improvement accuracy. 
- check if the intent is returned correctly....
- Removed the mentioned chips from the query sent for intent detection.

Remove mentions for intent detection query

---

vscode/webviews/chat/Transcript.tsx
vscode/webviews/components/codeSnippet/CodeSnippet.module.css
web/CHANGELOG.md
web/package.json

Part of https://linear.app/sourcegraph/issue/SRCH-1061/cody-web-leaks-styles-for-highlighted-code-matches
This simply renames color variables to avoid namespaces overlapping with the Sourcegraph Web App. 
- This doesn't change anything about existing Cody Chat styles, so no regression

Cody Web: Fix code snippets leaking styles

---

vscode/src/chat/chat-view/ChatsController.ts
vscode/webviews/tabs/TabsBar.tsx

~Let's include the change from the release branch (https://github.com/sourcegraph/cody/pull/5405).~
Fixed in JB: https://github.com/sourcegraph/jetbrains/pull/2282
- chat export works

Pass title for a dialog

---

vscode/CHANGELOG.md
vscode/src/commands/menus/index.ts
vscode/src/commands/services/provider.ts
vscode/test/e2e/command-custom.test.ts
vscode/test/e2e/helpers.ts

CLOSE https://linear.app/sourcegraph/issue/CODY-3698/remove-duplicate-command-buttons-in-ui-to-avoid-confusion
This PR fixes an issue where duplicated default commands are listed as custom commands in the Cody Commands QuickPick menu.
Root cause: All commands (including default ones) were being sent to the quick pick menu during the build step used to append to the menu.
Fix: Send only custom commands to the menu, preventing default commands from being listed as custom.
- Update showCommandMenu function to use only custom commands
- Modify CommandsProvider to pass only custom commands for menu display
- Update E2E tests to verify default commands are not shown as custom
- Refactor command menu opening functions for consistency
- Update CHANGELOG.md to reflect the fix
This change ensures …

fix(commands): remove duplicated commands from Cody Commands menu

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/index.test.ts
lib/shared/src/models/dotcom.ts
vscode/src/chat/chat-view/ChatModel.ts

fix: update model selection to only allow available models
- Only update the model ID if the new model is available to the user
- Rename the 'OpenAI o1' model to 'OpenAI o1-preview' to better indicate it is a preview model
Switch to OpenAI o1-preview model to confirm it opens the waitlist blog
Then switch to another model to confirm you can submit chat without issue
Rename the 'OpenAI o1' model to 'OpenAI o1-preview'

Chat: rename the 'OpenAI o1' model to 'OpenAI o1-preview

---

lib/shared/src/sourcegraph-api/completions/browserClient.ts
lib/shared/src/sourcegraph-api/completions/client.ts
vscode/CHANGELOG.md
vscode/src/completions/nodeClient.ts

Follow up on https://github.com/sourcegraph/cody/pull/5508
CLOSE https://linear.app/sourcegraph/issue/CODY-3741/oai-o1-hits-parsing-error
This change adds support for non-streaming requests, particularly for new OpenAI models that do not support streaming. It also fixes a "Parse Error: JS exception" issue that occurred when handling non-streaming responses in the streaming client.
- Remove HACK for handling non-streaming requests in the stream method in nodeClient.ts that's resulting in parsing error
- Implement a new `_fetchWithCallbacks` method in the `SourcegraphCompletionsClient` class to handle non-streaming requests
- Update the `SourcegraphNodeCompletionsClient` and `SourcegraphBrowserCompletionsClient` classes to use the new `_fetchWithCallbacks` method when `params.stream` is …

fix(chat): support non-streaming chat completion requests

---

lib/shared/src/prompt/truncation.ts
vscode/src/chat/chat-view/ChatController.ts

Previously, chat telemetry events were not capturing `promptText` and `responseText` due to the asynchronous nature of the `truncatePromptString` function, which was modified in a recent pull request(https://github.com/sourcegraph/cody/pull/5231). 
Now, we have added the proper `await` calls when using `truncatePromptString`, re-enabling the collection of this data for chat telemetry events.
Key changes:
1. Added `await` to `ChatController` where `truncatePromptString` is being used
2. Made `addBotMessage` an async func
Tested locally and verified `promptText` and `responseText` are being recorded again.
https://github.com/user-attachments/assets/b3952819-0945-4162-baf7-d98704aec21d

Chat Telemetry: Restores `prompt` and `response` text recording

---

web/CHANGELOG.md
web/package.json

Simply update version in `package.json` and `changelog` to bump recent changes about new GPT models for cody web in Sourcegraph web app 
- No test plan

Cody Web 0.8.2 release

---

vscode/src/completions/context/retrievers/recent-edits/recent-edits-retriever.ts

`psDedent` removed the spaces making diff invalid. Replaced with `ps`
1. Manual testing by checking the diff validity

fix the diff for recent edits by replacing psDedent with ps

---

vscode/CHANGELOG.md
vscode/webviews/chat/cells/messageCell/assistant/AssistantMessageCell.tsx

- Update the `AssistantMessageCell` component to provide more informative messaging when a non-streaming model is used
- The new message explains that non-streaming models may take longer to respond, but are recommended for complex reasoning and coding tasks
This may be slightly too heavy-handed, but I think it's important to show why it takes longer since not everyone will be familiar with the models.
Test manually.

feat(chat): improve messaging for non-streaming models

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ClientCapabilities.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/CodyAgentClient.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/WebviewNativeConfig.kt
agent/src/NativeWebview.ts
agent/src/agent.ts
agent/src/cli/scip-codegen/Codegen.ts
agent/src/cli/scip-codegen/Formatter.ts
vscode/src/chat/chat-view/ChatController.test.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/jsonrpc/agent-protocol.ts

Adds support for linux for Cody Eclipse. Replacement for https://github.com/sourcegraph/cody/pull/5354.
There is a bug in the logic for processing the webview index.html file that was allowing the eclipse plugin to work accidentally, because the MacOS and Windows integrated browsers were effectively  ignoring the content security policy. 
This patches that logic and allows a setting for injecting scripts and removing the CSP (required for inline-scripts) and allows skipping converting all embedded links into file:// paths (the eclipse browser cannot handle custom protocols).
Also fixes two bugs around Java code generation.
Unit tests added.

feat(eclipse): Add support for linux (CODY-3536)

---

lib/shared/src/models/index.test.ts
lib/shared/src/models/index.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatsController.ts
vscode/src/commands/scm/source-control.ts
vscode/src/main.ts
vscode/src/models/sync.test.ts
vscode/src/models/sync.ts
vscode/src/services/AuthProvider.ts

Previously, the ChatController listened for auth changes and assumed that model changes would have been already applied. This required a specific ordering of operations in the AuthProvider, which was a brittle way of ensuring this behavior (and the `chat model selector` e2e test broke when that behavior was slightly changed). Now, the ModelsService exposes a `changes` observable and the ChatController listens to that to follow changes to models, which makes sense.
e2e tests cover this well.

expose ModelsService.changes and listen to that in ChatController

---

vscode/src/services/UpstreamHealthProvider.ts
vscode/src/testutils/mocks.ts

Skip the UpstreamHealthProviderCheck if the window is not focused, and try again when the window becomes focused again. Some users have OS firewalls that make periodic background network access annoying for users. See https://linear.app/sourcegraph/issue/CODY-3745/codys-background-periodic-network-access-causes-2fa.
This check is used to gather latency information to properly measure actual latency for autocomplete. As long as the user has VS Code focused for slightly more than 10 seconds, it will still gather the necessary latency information for these calculations.
Fixes https://linear.app/sourcegraph/issue/CODY-3745/codys-background-periodic-network-access-causes-2fa
Open VS Code and check logs for the UpstreamHealthProvider call. Ensure that it does not trigger when the window is not …

reduce background network access

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/completions/context/retrievers/recent-edits/recent-edits-retriever.ts

Autocomplete Logging: Fix the diff for recent edits by replacing psDedent with ps to preserve the indentation. [pull/5574](https://github.com/sourcegraph/cody/pull/5574)
version and changelog change

Hitesh/vscode 1.34.3 release

---

agent/src/cli/command-bench/llm-judge.ts
lib/shared/src/inferenceClient/misc.ts
lib/shared/src/llm-providers/ollama/completions-client.ts
lib/shared/src/sourcegraph-api/completions/browserClient.ts
lib/shared/src/sourcegraph-api/completions/client.ts
vscode/src/completions/default-client.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/nodeClient.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/experimental-ollama.ts
vscode/src/completions/providers/expopenaicompatible.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/google.ts
vscode/src/completions/providers/openaicompatible.ts
vscode/src/completions/providers/provider.ts
vscode/src/completions/providers/unstable-openai.ts
vscode/src/completions/request-manager.test.ts
vscode/src/completions/request-manager.ts
vscode/src/configuration.ts
vscode/src/extension.common.ts
vscode/src/external-services.ts
vscode/src/local-context/rewrite-keyword-query.test.ts
vscode/src/main.ts
vscode/src/services/LocalStorageProvider.ts

Makes it so that our completions HTTP clients observe the config using the standard global `resolvedConfig` observable instead of through an ad-hoc way of reading it. (Actually, in practice, since it is not a long-lived instance, it just reads it on-the-fly at request time, but the idea is to standardize this, and that's what is achieved here.)
e2e

completion client: observe config

---

vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ContextRetriever.ts
vscode/webviews/App.module.css

When context retrieval or computation throws an error preventing context from being fetched, don't just silently use no context, display a user-visible message conveying the error and explaining why the response does not incorporate context.
Throw an unexpected error in `ChatController._computeContext` or `ContextRetriever.retrieveContext`, and verify the error shows.

user visible error when context retrieval or computation fails

---

lib/shared/src/configuration.ts
vscode/CHANGELOG.md
vscode/package.json
vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/completions/create-multi-model-inline-completion-provider.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/providers/create-provider.test.ts
vscode/src/completions/providers/create-provider.ts
vscode/src/completions/providers/provider.ts
vscode/src/configuration-keys.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/testutils/mocks.ts

TLDR: clean up autocomplete settings and improve visibility/debuggability of autocomplete provider creation errors.
- Changed the exposed values for `cody.autocomplete.advanced.provider` to:
- `default` — our recommended setup.
- `experimental-ollama` — for Ollama users.
- Added proper descriptions to `cody.autocomplete.advanced.provider` and its options.
- <img width="694" alt="Screenshot 2024-09-16 at 12 02 23" src="https://github.com/user-attachments/assets/65eeac9f-5e76-4d59-82d5-123a85962fd3">
- Hidden `cody.autocomplete.advanced.model`. It's kept for internal testing purposes only.
- Removed unused `cody.autocomplete.advanced.serverEndpoint` and `cody.autocomplete.advanced.accessToken`.
- Replaced provider value validation based on enums specified in package.json with the runtime …

Autocomplete: clean up settings

---

agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/cli/command-auth/AuthenticatedAccount.ts
agent/src/cli/command-auth/command-login.ts
agent/src/cli/command-bench/command-bench.ts
agent/src/cli/command-context/command-context.ts
agent/src/index.test.ts
agent/src/local-e2e/helpers.ts
lib/shared/src/index.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
vscode/src/completions/context/context-mixer.test.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/inline-completion-item-provider-e2e.test.ts
vscode/src/main.ts
vscode/src/models/sync.test.ts
vscode/src/models/sync.ts
vscode/src/services/AuthProvider.ts

Previously, it relied on having its config updated in `vscode/src/main.ts`. Now, it observes the global `resolvedConfig` just as everything else does now.
e2e

make graphqlClient observe global config/auth

---

vscode/src/completions/model-helpers/default.ts
vscode/src/completions/model-helpers/mistral.ts
vscode/src/completions/model-helpers/openai.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/openaicompatible.ts
vscode/src/completions/providers/unstable-openai.ts

- Use model helpers with the `unstable-openai` provider to reduce code duplication.
CI and manually tested the `unstable-openai` provider with the sg02 backend.

Autocomplete: add openai model helper for the `unstable-openai` provider

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/artificial-delay.test.ts
vscode/src/completions/artificial-delay.ts
vscode/src/completions/completion-provider-config.ts
vscode/src/completions/inline-completion-item-provider.ts

This PR aims to remove the artificial delay introduced for low-performance languages and specific AST nodes, as outlined in th [issue](https://linear.app/sourcegraph/issue/CODY-3315/delete-the-artificial-latency). The artificial delay was originally implemented for low performance languages so that users are not spammed with unhelpful suggestions. , but it has become less relevant over time, and it may now impact the predictability of autocomplete latency and user experience (UX).
A new feature flag has been added to toggle the artificial delay.
- Objective: The main objective is to achieve predictable latency and a consistent autocomplete UX for all languages.
- After merging this PR, the feature flag will be enabled for controlled testing, and data will be collected to assess the impact …

Testing the Removal of Artificial Latency behind a feature flag

---

vscode/src/completions/context/retrievers/jaccard-similarity/jaccard-similarity-retriever.ts

Closes https://linear.app/sourcegraph/issue/CODY-3760/cody-prerelease-%E2%96%88-jaccardsimilarityretriever-cannot-add-dependency
1. Local VS Code build
2. Open multiple files in the editor
3. Generate a completion in one of them
4. Observe that `jaccardsimilarityretriever-cannot-add-dependency` is not logged in the Cody output channel

Autocomplete: use prefetched flag in the jaccard-similarity retriever

---

vscode/src/completions/context/retrievers/jaccard-similarity/history.ts
vscode/src/completions/context/retrievers/jaccard-similarity/jaccard-similarity-retriever.ts

- Properly fixes https://linear.app/sourcegraph/issue/CODY-3760/cody-prerelease-%E2%96%88-jaccardsimilarityretriever-cannot-add-dependency
- Follow up based on [this comment](https://github.com/sourcegraph/cody/pull/5602#discussion_r1762312541). 
Enabled [the feature flag](https://sourcegraph.com/site-admin/feature-flags/configuration/cody-autocomplete-context-extend-language-pool) for my user on DotCom and verified that it's `true` at the runtime.

Autocomplete: use prefetched flag in the jaccard-similarity retriever [2]

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/shared/get-experiment-model.ts

Shipment of direct routing and prompt caching to all users.
Online Results: https://sourcegraph.slack.com/archives/C0729T2PBV2/p1725574821564519 
1. https://github.com/sourcegraph/sourcegraph/pull/571
1. Manually overriding in the feature flag and checking completions results.

shipment of direct routing and prompt caching to PLG users

---

lib/shared/src/prompt/prompt-mixin.ts

This change adds a prompt that prevents the Claude 3.5 Sonnet model from constantly apologizing. Currently we are adding this prompt to model ID that matches claude-3-5-sonnet; However, the server side config on S2 is using claude-3.5-sonnet as the model ID, causing this check to fail.
The prompt now applies to model when the model ID contains '3.5-sonnet' or '3-5-sonnet'.
Connect to S2 and open the Output channel to confirm the chat Model id is showing up as `sourcegraph/claude-3.5-sonnet`:
```
█ CodyLLMConfiguration: {"chatModel":"sourcegraph/claude-3.5-sonnet"}
```
Ask Cody a question and confirm the heading prompt is attached to your question when checking the transcript in the Output channel.

Chat: prevent Claude 3.5 Sonnet model from apologizing constantly

---

package.json
pnpm-lock.yaml
vscode/package.json
vscode/src/context/openctx.ts
web/package.json

Incorporates https://github.com/sourcegraph/openctx/pull/207 and https://github.com/sourcegraph/openctx/pull/206.
Fixes https://linear.app/sourcegraph/issue/CODY-3799/quieter-openctx-provider-ui-notifs-in-vs-code-and-better-error-logging.
Open VS Code with an OpenCtx provider that throws an error. Ensure that no VS Code error notification is shown in the UI, and that it's logged to the `OpenCtx` output channel with the provider URI mentioned.

bump openctx for quieter provider errors

---

agent/src/enterprise-s2.test.ts
lib/shared/src/cody-ignore/context-filters-provider.test.ts
lib/shared/src/cody-ignore/context-filters-provider.ts
vscode/src/jsonrpc/jsonrpc.ts

There were a few problems:
- If the overridePolicy was not set at the start, it would trigger a background fetch. This would overwrite the filters value at some random point during testing, causing flakiness.
- We can use currentAuthStatus() instead of having a live subscription to determine if we're on dotcom. That is simpler.
CI

deflake Cody Context Filters test

---

lib/shared/src/llm-providers/ollama/utils.ts

This will make our tests more reliable when run locally.
It is possible that this could make it harder to spot issues in unit tests and agent tests where Ollama being available causes issues. If we see such an issue, then we should build in a case to prevent that problem. As is, CI and many/most devs aren't running Ollama, so we have at best uneven protection, and at worst the flakiness causes wasted dev time and possibly bad workarounds.
CI

disable fetching Ollama models during vitest unit testing to avoid nondeterminism

---

vscode/test/e2e/chat-input.test.ts

It often complains that there are 3 matching elements. Any of them would work, but now the e2e test more specifically mentions the one we intend to select.
See https://github.com/sourcegraph/cody/actions/runs/10984735543/job/30495688350?pr=5221#step:10:155 for an example of a flake.
CI

deflake "chat input focus" e2e test

---

lib/shared/src/misc/rpc/webviewAPI.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/protocol.ts
vscode/webviews/App.story.tsx
vscode/webviews/App.tsx
vscode/webviews/Chat.tsx
vscode/webviews/CodyPanel.tsx
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx
vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/SubmitButton.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx
vscode/webviews/utils/useExperimentalOneBox.tsx
web/lib/components/CodyWebChat.tsx

Refactor onebox experimental flag drill down to rather use `useConfig`.
- Connect to s2, the chat submit button should have a dropdown and on submit, intent detection box should be visible.
- Connect to dotcom, the chat submit button should have no dropdown and the intent detection box should not be visible.
None.

Refactor onebox experimental flag

---

vscode/webviews/chat/Transcript.tsx

closes: https://linear.app/sourcegraph/issue/SRCH-1080/dont-show-an-llm-response-when-we-trigger-a-code-search
Hides the hard coded LLM response for search intent.
- connect to s2 and enter a code search query. 
- no LLM response text should be visible.

Do not show an LLM response when we trigger a code search

---

agent/src/cli/command-bench/strategy-chat-context.ts

Adjust the overlap threshold at which we count something as a "hit". The ground truth now includes some pretty large blocks of context, so we use a min of a percentage threshold and a constant line overlap.
Make error messages more descriptive when `cody internal bench` fails.
N/A (benchmarks only)

Small improvements to cody bench context

---

lib/shared/src/index.ts

For reasons I don't fully understand, these imports were causing the storybook build (`pnpm -C web dev`) to fail. It looks like the re-exported symbols in question (`modelsService`, `CodyClientConfig`) were stripped but then later expected from within Storybook, which caused errors like this:
```
Uncaught SyntaxError: The requested module '/@fs/home/beyang/src/github.com/sourcegraph/cody/lib/shared/src/models/modelsService.ts' does not provide an export named 'ModelCategory' (at index.ts:7:5)
```
Dev-only

fix storybook build (`pnpm -C web dev`)

---

agent/recordings/cody-chat_103640681/recording.har.yaml
agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/__snapshots__/index.test.ts.snap
lib/shared/src/commands/types.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
lib/shared/src/misc/rpc/webviewAPI.ts
vscode/package.json
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatsController.ts
vscode/src/chat/protocol.ts
vscode/src/commands/CommandsController.ts
vscode/src/commands/execute/doc.ts
vscode/src/commands/execute/test-chat.ts
vscode/src/main.ts
vscode/src/prompts/prompts.ts
vscode/webviews/App.story.tsx
vscode/webviews/Chat.tsx
vscode/webviews/CodyPanel.tsx
vscode/webviews/chat/cells/contextCell/ContextCell.tsx
vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx
vscode/webviews/chat/components/WelcomeMessage.tsx
vscode/webviews/components/promptList/PromptList.tsx
vscode/webviews/components/shadcn/ui/accordion.tsx
vscode/webviews/prompts/PromptsTab.tsx
vscode/webviews/tabs/TabsBar.tsx

Main Linear issue [SRCH-1052](https://linear.app/sourcegraph/issue/SRCH-1052/get-rid-of-out-of-the-box-commands-for-walmart-parent-task)
Closes [SRCH-1064](https://linear.app/sourcegraph/issue/SRCH-1064/automatically-create-ootb-prompts-for-plg-new-enterprise-prospects)
Closes [SRCH-1049](https://linear.app/sourcegraph/issue/SRCH-1049/kill-all-out-of-the-box-commands-put-behind-a-feature-flag-for-walmart)
Closes [SRCH-1050](https://linear.app/sourcegraph/issue/SRCH-1050/create-prompts-that-replace-todays-commands-and-automatically-load)
So this PR does a few things with prompts and commands (I recorded a loom with changes walkthrough [here](https://www.loom.com/share/fb8c8e18d34847eca248d9e0f729d59f))
- First of all, all changes in this PR are behind the feature flag …

Add prompt-like standard commands

---

vscode/src/completions/providers/openaicompatible.test.ts
vscode/src/completions/providers/unstable-openai.test.ts

- Adding request params tests for all possible configurations of the `openaicompatible` provider.
- Follow up for https://github.com/sourcegraph/cody/pull/5604
- Part of https://linear.app/sourcegraph/issue/CODY-3778/add-autocomplete-provider-tests-to-assert-request-parameters
CI with updated unit tests.

Autocomplete: add request-params tests for the `openaicompatible` provider

---

vscode/src/completions/model-helpers/starcoder.ts
vscode/src/completions/providers/expopenaicompatible.test.ts
vscode/src/completions/providers/expopenaicompatible.ts
vscode/src/completions/providers/shared/__mocks__/create-provider-mocks.ts
vscode/src/completions/providers/shared/create-provider.test.ts
vscode/src/completions/providers/shared/helpers.ts

The problem: currently, we [assert](https://github.com/sourcegraph/cody/blob/d10b88f3bcaad1c140352088a15f641f4697c80f/vscode/src/completions/providers/shared/create-provider.test.ts#L218-L219) the model ID assigned to the provider instance, but often, it's not used at all to make requests, which means this assertion is irrelevant to the actual functionality where we bump into bugs.
- This PR adds tests for autocomplete request parameters in all supported instance configurations: dotcom/enterprise X local-settings/server-side-model-config/site-config for the `experimental-openaicompatible` provider.
- Removes model specific code by leveraging model helpers we already use in other providers.
- Follow up for https://github.com/sourcegraph/cody/pull/5604.
- Part of …

Autocomplete: add `experimental-openaicompatible` provider tests

---

vscode/src/completions/model-helpers/__tests__/gemini.test.ts
vscode/src/completions/model-helpers/default.ts
vscode/src/completions/model-helpers/gemini.ts
vscode/src/completions/model-helpers/index.ts
vscode/src/completions/providers/google.test.ts
vscode/src/completions/providers/google.ts

The problem: currently, we [assert](https://github.com/sourcegraph/cody/blob/d10b88f3bcaad1c140352088a15f641f4697c80f/vscode/src/completions/providers/shared/create-provider.test.ts#L218-L219) the model ID assigned to the provider instance, but often, it's not used at all to make requests, which means this assertion is irrelevant to the actual functionality where we bump into bugs.
- This PR adds tests for autocomplete request parameters in all supported instance configurations: dotcom/enterprise X local-settings/server-side-model-config/site-config for the `google` provider.
- Removes model-specific code by leveraging model helpers we already use in other providers.
- Follow up for https://github.com/sourcegraph/cody/pull/5604.
- Part of …

Autocomplete: add `google` provider tests

---

lib/shared/src/models/utils.ts
vscode/CHANGELOG.md

Protential fix for https://linear.app/sourcegraph/issue/SRCH-1086
The changes expand the smart context window to cover additional Claude Sonnet models, including 'claude-3-sonnet' and 'claude-3-5-sonnet', in addition to the existing 'claude-3-opus' model. This ensures the smart context window is correctly set for all Claude Sonnet models configured on the server side, which is using the 3.5-sonnet instead of 3-5-sonnet substring.
This fixes an issue where server-side configurations using the claude-3.5-sonnet are assigned a basic context window (7k token limit) instead of the expanded context window, which has a 45k token limit.
Try connecting to S2 and add a file with more than 7k token using @-mention to confirm you don't run into the context window limit.
Enterprise: Smart context …

Enterprise: expand smart context window for all Claude Sonnet models

---

web/CHANGELOG.md
web/package.json

This is just a Cody Web bump PR in order to publish new version of cody chat with fixes from https://github.com/sourcegraph/cody/pull/5221
- CI is green

Bump Cody Web version 0.9.0

---

vscode/test/e2e/command-custom.test.ts
vscode/webviews/chat/cells/contextCell/ContextCell.story.tsx
vscode/webviews/chat/fixtures.ts
vscode/webviews/components/FileLink.module.css
vscode/webviews/components/FileLink.test.tsx
vscode/webviews/components/FileLink.tsx

Improve the rendering of context items in Cody
* Render the basename first
* Followed by line numbers in gray text
* Repo and dirname after in gray text and smaller font
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Test locally and on web.

prettier rendering of context items

---

agent/README.md
agent/scripts/export-cody-http-recording-tokens.ps1
agent/scripts/export-cody-http-recording-tokens.sh
package.json

Follow the steps in `agent/README.md`:
1. Install gcloud, src
2. Run the `agent/scripts/export-cody-http-recording-tokens.ps1`
3. `pnpm update-agent-recordings-windows`
This should produce new agent records, for example see #5688

Add a way to update agent recordings on Windows

---

agent/src/agent.ts
lib/shared/src/experimentation/FeatureFlagProvider.test.ts
lib/shared/src/experimentation/FeatureFlagProvider.ts
lib/shared/src/misc/observable.ts
lib/shared/src/misc/rpc/webviewAPI.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/protocol.ts
vscode/src/completions/completion-provider-config.ts
vscode/src/completions/default-client.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/notifications/cody-pro-expiration.test.ts
vscode/src/notifications/cody-pro-expiration.ts
vscode/src/prompts/prompts.ts
vscode/src/services/open-telemetry/OpenTelemetryService.node.ts
vscode/src/tutorial/helpers.ts
vscode/webviews/App.story.tsx
vscode/webviews/Chat.tsx
vscode/webviews/CodyPanel.tsx
vscode/webviews/chat/components/WelcomeMessage.tsx
vscode/webviews/tabs/TabsBar.tsx
vscode/webviews/utils/useFeatureFlags.tsx

- Updates some places in code to watch feature flags instead of evaluating them once. This makes our application immediately reactive to changes in feature flag values, which means users can get the desired functionality without needing to restart their editor.
- Renames the `evaluateFeatureFlag` method to `evaluateFeatureFlagEphemerally`, deprecates it, documents when it may be safely used, and makes it cache the result.
This also reduces the latency of autocomplete after #5221 was merged because it makes `evaluateFeatureFlag` calls not hit the network each time (and each autocomplete calls that 1-2 times).
Fixes https://linear.app/sourcegraph/issue/CODY-3846/remove-most-uses-of-evaluatefeatureflag-method.
CI. Check that the unified prompts feature flag works correctly.

watch feature flags instead of calling evaluateFeatureFlag (which is non-reactive)

---

lib/shared/src/misc/observable.ts
vscode/package.json
vscode/src/services/AuthProvider.ts

This VS Code action in the command palette only shows up when you have `cody.internal.unstable` set to `true` in your VS Code user settings. It causes Cody to re-authenticate to your current endpoint, which is useful for testing signin/account-switching behavior.
Use it and ensure it reloads auth by seeing it flash to unauthed and then authed again.

`Cody: Refresh Settings (Debug)` helper action

---

agent/src/agent.ts
lib/shared/src/chat/preamble.ts
lib/shared/src/cody-ignore/context-filters-provider.ts
lib/shared/src/models/modelsService.ts
lib/shared/src/prompt/prompt-mixin.ts
vscode/src/chat/chat-view/ChatBuilder.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/prompt.test.ts
vscode/src/chat/chat-view/prompt.ts
vscode/src/chat/clientStateBroadcaster.ts
vscode/src/chat/context/chatContext.ts
vscode/src/services/HistoryChat.ts

Previously, the ChatModel was a source of truth and a cache. It cached the model that would be used for the next assistant message, and ChatController had to update that whenever the default chat model changed. Now, ChatBuilder (renamed from ChatModel to be less confusing) only stores the chat model *if* the user explicitly selected one; otherwise, its `model` is `undefined` and it is resolved to the default chat model as late as possible, when the chat is actually submitted. The actual chat model used is then stored in the message transcript.
This is better because ChatController does not need to worry about stale state being present in the ChatBuilder, except if the user's explicitly chosen model is no longer available on the endpoint, which is an error case that needs to be handled …

treat ChatBuilder (nee ChatModel) as having minimal state

---

vscode/src/context/openctx.ts

Fixes https://linear.app/sourcegraph/issue/CODY-3885/openctx-status-bar-item-shows-in-cody-extension.
Run and ensure there is no empty OpenCtx status bar item.

do not show phantom OpenCtx editor status bar item

---

vscode/webviews/tabs/TabsBar.tsx

Fixes https://linear.app/sourcegraph/issue/CODY-3837/new-chat-button-does-not-focus-chat-sidebar-panel-if-clicked-on.
Open the chat view and go to the history tab. Press New Chat. Confirm it opens up the chat tab. Try clicking New Chat from the chat tab to ensure it doesn't do anything weird.
Fixes an issue where the "New Chat" button would not take you to the chat tab with your new chat.

switch to chat tab when clicking New Chat from another tab

---

vscode/src/commands/services/provider.ts

CLOSE https://linear.app/sourcegraph/issue/CODY-3679/in-non-vs-code-editors-remove-manage-link-from-commands-section-hide
The custom commands store is only supported in the VS Code, so this change ensures it is only initialized in that case. This avoids unnecessary initialization and also ensure the custom commands will not show up in non-VS Code environment.
1. Verify the custom commands store is not initialized in the web app
2. Verify the custom commands store is initialized in the VS Code extension
When agentIDE is undefined (because VS Code doesn't run agent) or agentIDE is not equal to VS Code:

Custom Commands: initialize in VSCode only

---

vscode/src/context/workspace-repo-mapper.ts
vscode/src/repository/repo-metadata-from-git-api.ts

Previously, the repo name->ID mapping was not cleared when switching accounts. This meant that if you were on one instance and switched to another, and if you had a chat that was open but had not sent any messages on it, then after switching accounts, the chat would return an error `Error retrieving context, no search context was used: Error: could not find repo with id ...`. The repo ID was the ID from the prior instance before the account switch. Now, it properly clears the mapping when you switch accounts.
This code is due for some improvements, but this fixes the immediate issue.
Fixes https://linear.app/sourcegraph/issue/CODY-3838/error-retrieving-context-could-not-find-repo-id-error-when-chatting.
As described above. Confirm there is no error.

reset repo name->ID mapping when switching accounts

---

vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/protocol.ts
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/contextCell/ContextCell.tsx
vscode/webviews/chat/cells/messageCell/assistant/AssistantMessageCell.tsx
vscode/webviews/components/FileLink.tsx
vscode/webviews/components/FileSnippet.tsx

closes: https://linear.app/sourcegraph/issue/AI-298/log-telemetry-for-one-box-clicks
Add telemetry events for onebox as per the linear issue requirements. 
Check if the telemetry events are triggered for the following
- expand and collapse context files accordion for both search and chat intents
- click on search results and context files 
- switch intent from response.

Add intent telemetry

---

lib/shared/src/configuration.ts
lib/shared/src/misc/rpc/webviewAPI.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/testutils/mocks.ts
vscode/webviews/AppWrapperForTest.tsx
vscode/webviews/CodyPanel.tsx
vscode/webviews/components/StateDebugOverlay.tsx

Adds a component that displays the current state (configuration, auth status, models, etc.) at the top of the CodyPanel to help when debugging. To enable, set the `cody.internal.debug.state` user setting to `true`.
n/a

StateDebugOverlay debug helper for seeing state values in the webview

---

vscode/src/chat/chat-view/ChatBuilder.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatsController.ts

If you are on endpoint E1 and choose a model M1 in a new chat that is NOT sent, and then switch accounts to endpoint E2, the model selector will show your default model for E2 but your unsent chat will, when sent, use the model M1, which is likely not valid on E2. Now, we reset the new chat when your endpoint changes, which eliminates this problem.
Fixes https://linear.app/sourcegraph/issue/CODY-3898/explicitly-selected-model-in-new-chat-is-not-overwritten-on-account.
As described above.

fix explicitly selected model on new chat is not reset on account switch

---

vscode/src/chat/chat-view/ChatController.ts

Currently there is a problem that you can't switch account with new auth logic (after we make auth state reactive), my guess this is because we fire config event too late and in this method we wait for the last event which never will be emited because by the time we run send config we already missed this. 
This PR just tries to take the last auth value, I'm not sure that maybe I should use `currentAuthStatusOrNotReadyYet` instead, but I think it should be not possible to run into config event without non init auth status observable. 
- Try to switch accounts 
- Try to log out completely and sign in in multiple accounts

Fix switching accounts auth problem

---

lib/shared/src/auth/types.ts
vscode/src/auth/auth.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/utils.test.ts
vscode/src/chat/utils.ts
vscode/src/services/AuthProvider.test.ts
vscode/src/services/AuthProvider.ts

This PR is on top of another fix for auth https://github.com/sourcegraph/cody/pull/5709
So, currently, you can see the log-out UI state when we're verifying the auth state. This PR tries to fix it on the extension side (so, in theory, we should fix this problem for all consumers). 
The fix is simple but I'm not sure we shouldn't send the configuration if we're verifying the auth state, maybe this prevent rendering logic should be on the client side and we just need to expose verify status information
- Try to run the VSCode extension and check you don't see log out screen if you're already signed in

Fix auth flashes

---

agent/src/edit.test.ts
lib/shared/src/index.ts
lib/shared/src/models/dotcom.ts
lib/shared/src/models/modelsService.test.ts
lib/shared/src/models/types.ts
vscode/src/commands/scm/source-control.ts
vscode/webviews/AppWrapperForTest.tsx
vscode/webviews/components/modelSelectField/ModelSelectField.story.tsx

Remove all the current usage of the client-side dotcom models from the codebase.
Replace with a copy of the server-side model config from DotCom as mock that can be use for testing.
green CI

Remove Client served models

---

lib/shared/src/codebase-context/messages.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
vscode/src/chat/chat-view/ContextRetriever.ts
vscode/webviews/components/FileSnippet.tsx

Closes https://linear.app/sourcegraph/issue/SRCH-978/highlight-results-with-keyword-matches-in-cody-chat-queries
This PR simply adds highlights ranges to the code blocks with search context files. 
- Check that in Search mode in one box you have matched range highlights

Add matched range matches to context files

---

lib/shared/src/misc/observable.test.ts
lib/shared/src/misc/observable.ts

Adds a leak detector to ensure that in the observable tests, subscriptions get cleaned up.
n/a

add tests to detect observable subscription leaks

---

vscode/src/edit/input/get-items/model.ts

- Refactor `getModelProviderIcon` function to use a constant mapping object `MODEL_PROVIDER_ICONS` instead of a switch statement
- This makes the icon mapping more explicit and easier to maintain
- This also fixes an issue where OpenAI models are not using the correct logo because the capitalized "AI" in the previous switch map
Check the Edit model dropdown list to confirm openAI models are showing the correct logo:
OpenAI model (GPT-4o) is showing up with Cody logo instead of OpenAI logo.

Edit: use consistent model provider icon mapping

---

lib/shared/src/index.ts
vscode/src/completions/inline-completion-item-provider-e2e.test.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/expopenaicompatible.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/google.ts
vscode/src/completions/providers/openaicompatible.ts
vscode/src/completions/providers/shared/create-provider.ts
vscode/src/completions/providers/shared/provider.ts
vscode/src/completions/providers/unstable-openai.ts
vscode/src/completions/request-manager.test.ts

- Reusing the `generateCompletions` method across all autocomplete providers, which became identical after the recent refactorings.
- Part of https://linear.app/sourcegraph/issue/CODY-3778/add-autocomplete-provider-tests-to-assert-request-parameters
CI

Autocomplete: reuse `generateCompletions` across providers

---

lib/shared/src/auth/referral.ts

- Update the referral code mapping to use consistent codes across the client and server
- This ensures that the referral codes used in the client match the ones registered on the server side
- This fixes an issue where the referral codes were different on the server side for certain IDEs like JetBrains and Neovim
- EMACS is not registered on the server side so we will fall back to CODY for now
The referral code mapping has been updated, which may require changes on the server side to ensure the new codes are registered
Closes https://linear.app/sourcegraph/issue/CODY-3912/fix-redirection-url-and-referral-tokens-for-jetbrains-sign-in-panel
Build JB with this branch to confirm the redirection works.
Agent: fix auth referral code mapping across client and server

Agent: fix auth referral code mapping across client and server

---

vscode/test/e2e/mention-repository.test.ts

Attempted to fix the mentioned repository e2e test that is failing on main.
It's reproducible by running `pnpm test:e2e mention-repository` locally
This shows the user repo is not showing up in the chat input, and based on the replay, it looks like this is because the mentioned menu is opened before the initial context is ready and added.
Adding a check to make sure the initial user repo is showing up in the chat input box before we open the mention menu fixes the issue for me locally.
Run the `pnpm test:e2e mention-repository` command from the root of the repo to confirm the e2e test is now passing locally:

E2E: fix flanky mention-repo test

---

vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/protocol.ts
vscode/webviews/App.tsx
vscode/webviews/Chat.story.tsx
vscode/webviews/Chat.tsx
vscode/webviews/CodyPanel.story.tsx
vscode/webviews/CodyPanel.tsx
vscode/webviews/chat/Transcript.story.tsx
vscode/webviews/chat/Transcript.tsx
web/lib/components/CodyWebChat.tsx

This was only used to control whether to show feedback buttons after a message, and any message with isTranscriptError would also have an assistant reply with an error as well, so this did not do anything.
CI

remove unused, needless transcript-errors/isTranscriptError

---

vscode/webviews/tabs/TabsBar.module.css

The removal of `z-index: 1` is what was needed, and I don't see why other elements would be on top of this tab bar or its popovers.
The other diffs are from stylelint.
Test that @-mentions are not clipped by the tabs bar in `pnpm -C web dev`.

fix Cody Web issue with @-mention menu appearing behind tabs bar

---

agent/src/agent.ts
lib/shared/src/misc/rpc/webviewAPI.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatHistoryManager.ts
vscode/src/chat/protocol.ts
vscode/src/services/LocalStorageProvider.ts
vscode/webviews/App.story.tsx
vscode/webviews/App.tsx
vscode/webviews/AppWrapperForTest.tsx
vscode/webviews/CodyPanel.tsx
vscode/webviews/chat/downloadChatHistory.ts
vscode/webviews/tabs/HistoryTab.story.tsx
vscode/webviews/tabs/HistoryTab.test.tsx
vscode/webviews/tabs/HistoryTab.tsx
vscode/webviews/tabs/TabsBar.tsx
web/lib/components/CodyWebChat.tsx

Previously, chat history was synced to the webview using the old postMessage protocol. Now, the ChatHistoryManager exposes an observable and that is read directly (using the standard webviewAPI) by the webview. This is a code refactor with no user-facing behavior change.
In Cody Web and in VS Code, try downloading chat history. Ensure the JSON file is downloaded and is a JSON array of chat history.

pass chat history to webview using webviewAPI, not old postMessage protocol

---

agent/recordings/unauthed_2245427793/recording.har.yaml
agent/src/TestClient.ts
agent/src/agent.ts
agent/src/unauthed.test.ts
agent/src/vscode-shim.ts
vscode/e2e/utils/vscody/fixture.ts
vscode/src/jsonrpc/agent-protocol.ts
vscode/src/testutils/testing-credentials.ts

The agent can now initialize when no access token is initially provided. Previously it would exit with a fatal error:
```
Cody Agent: failed to initialize VSCode extension at workspace root path 'file:///Users/pkukielka/Work/jetbrains-test2/': Error: AuthStatus is not initialized
```
Fixes https://linear.app/sourcegraph/issue/CODY-3915/agent-fails-to-start-up-if-no-access-token-is-provided.
Added agent test.

allow agent to initialize when no access token is provided

---

lib/shared/src/misc/rpc/webviewAPI.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/protocol.ts
vscode/webviews/chat/Transcript.tsx

closes: https://linear.app/sourcegraph/issue/SRCH-1028/log-telemetry-of-the-output-of-the-intent-detection-model-with-each
Passes intent scores to `chat-question:executed` event.
- execute chat and check if the intent scores are logged.
- execute chat with manually triggering search intent, that should not log the intent scores. 
- execute chat with manually triggering chat intent, that should not log the intent scores.

Pass intent scores to telemetry

---

agent/src/cli/command-bench/command-bench.ts
agent/src/cli/command-bench/strategy-chat-context-types.ts
agent/src/cli/command-bench/strategy-chat-context.ts

Previously, `cody internal bench` when running the `chat-context` strategy would emit an `output.csv` file. This was fine for a standalone eval run, but there was no way to easily compare results across different eval runs.
Update the `chat-context` strategy to do the following:
* Emit an output CSV whose name incorporates the following:
* The input file name
* The product version of the Sourcegraph instance run against
* Emits an output YAML file with the following metadata:
* timestamp
* Sourcegraph instance URL
* Sourcegraph username and id of the access token used
* evaluated feature flags returned for that user on that instance
Outputs from multiple runs will be displayed in the next version of cody-leaderboard-private.
Run
```
pnpm -C agent agent:skip-root-build internal bench …
```

Improve chat context eval runner

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/artificial-delay.test.ts
vscode/src/completions/artificial-delay.ts
vscode/src/completions/inline-completion-item-provider.ts

Solves [Linear Issue](https://linear.app/sourcegraph/issue/CODY-3759/remove-codyautocompleteuserlatency-feature-flag)
When working on the Removal of Artificial Latency [behind a feature flag](https://github.com/sourcegraph/cody/pull/5480)  Valery said FeatureFlag.CodyAutocompleteUserLatency feature flag and all the related logic is not used anymore and plan on conducting [no further experiments with it](https://github.com/sourcegraph/cody/pull/5480#discussion_r1762175835). So I removed that and a lot of related logic that made this function and its tests very intricate. 
- Remove user-based latency adjustments and related feature flag
- Simplify getArtificialDelay function to only consider language and completion intent
- Update lowPerformanceConfig to include both language IDs and …

Simplify artificial delay logic and remove user-based latency

---

vscode/src/main.ts
vscode/src/prompts/prompts.ts

This PR returns inline documentation code command functionality, We deleted it for unified prompts experience but found that our smart apply can't replace our inline commands fully at the moment (it's still too slow in most of the cases). 
So this PR brings back the inline documentation command, but note that documentation code button on the welcome screen still works as a prompt (this is intended) cc @aramaraju 
- Check that with the unified-prompts feature flag (currently enabled on s2) 
- You can trigger the inline documentation command by shortcut opt+D and by right-clicking the context menu sub-option.
- Check that documentation code standard prompt on the welcome screen works

Unified prompts: Return inline documentation command

---

lib/shared/src/commands/types.ts
vscode/CHANGELOG.md
vscode/src/commands/CommandsController.ts
vscode/src/commands/execute/test-chat.ts
vscode/src/main.ts

CLOSE https://linear.app/sourcegraph/issue/QA-81
Currently, some commands unrelated to the chat commands are not registered when unified prompts feature is enabled, which I believe is unintentional.
This PR add some documentations around some cody commands, and refactor the logic to make it clear what the new unified prompts commands are during the command registeration.
This PR also fixes the issue where the generate unit test command was unintentionally removed when the unified prompts feature is enabled.
Manual Testing: Sign into S2 where the feature flag is enabled for all users.
1. In the Cody Commands menu, search for the following commands to make sure they are working:
- Auto Edit
- Generate Unit Test
2. Open the Terminal panel and highlight some text, right click to select "Ask …

Command: register missing commands when unifiedPrompts is enabled

---

vscode/CHANGELOG.md
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/contextCell/ContextCell.tsx

CLOSE https://linear.app/sourcegraph/issue/CODY-3886/context-says-0-items-while-its-loading
Displays "Retrieving codebase files..." instead of "0 items" when codebase context is loading  in the chat interface.
Submit a chat question with current repository added with @-mention to confirm we are now showing 'Retrieving codebase files…' instead of '0 item' during the context retrieval step: 
https://github.com/user-attachments/assets/eca567b7-fbf6-4ae5-9ad3-c828ea7d5bb3
Chat: Display the correct loading state during codebase context retrieval instead of 0 item by default.

Chat: show loading state during codebase context retrieval

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/context/context-data-logging.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/logger.test.ts
vscode/src/completions/logger.ts
vscode/src/completions/model-helpers/__tests__/codeqwen.test.ts
vscode/src/completions/model-helpers/codeqwen.ts
vscode/src/completions/model-helpers/index.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/shared/get-experiment-model.ts
vscode/src/completions/text-processing/process-inline-completions.ts
vscode/src/repository/githubRepoMetadata.ts
vscode/src/services/LocalStorageProvider.ts

The PR improves the following:
1. When calculating the `diff` over time for suggestion, we were using `document.getText`. Analyzing offline telemetry we see in ~20% we get some extra chars if user types between calculating `docContext` and `loaded` call. We leverage already computed `completePrefix` and `completeSuffix` to compute the text, which is accurate.
2. We were using in-memory cache for calculating `repoVisibility` before. But without passing token, we frequently hit rate limit for querying github api and cached tokens are evicted from in-memory cache when user refresh. This PR stores the tokens in `localStorage` instead of in-memory store to cache the repo visibility.
3. Adds the `code qwen` and `deepseek` model optimized for long prompts.
1. Added unit tests.
2. Manual Testing: …

use the accurate docContext and persist repo visibility using local storage

---

lib/shared/src/misc/rpc/webviewAPI.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
vscode/src/prompts/prompts.ts
vscode/test/e2e/chat-atFile.test.ts
vscode/test/e2e/common.ts
vscode/webviews/AppWrapperForTest.tsx
vscode/webviews/Chat.story.tsx
vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.module.css
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx
vscode/webviews/chat/components/WelcomeMessage.test.tsx
vscode/webviews/chat/components/WelcomeMessage.tsx
vscode/webviews/components/StateDebugOverlay.tsx
vscode/webviews/components/hooks.ts
vscode/webviews/components/promptList/ActionItem.module.css
vscode/webviews/components/promptList/ActionItem.tsx
vscode/webviews/components/promptList/PromptList.module.css
vscode/webviews/components/promptList/PromptList.story.tsx
vscode/webviews/components/promptList/PromptList.tsx
vscode/webviews/components/promptList/fixtures.ts
vscode/webviews/components/promptList/utils.ts
vscode/webviews/components/promptSelectField/PromptSelectField.tsx
vscode/webviews/components/promptSelectField/fixtures.ts
vscode/webviews/components/shadcn/ui/command.tsx
vscode/webviews/components/shadcn/ui/popover.module.css
vscode/webviews/components/shadcn/ui/popover.tsx
vscode/webviews/prompts/PromptsTab.story.tsx
vscode/webviews/prompts/PromptsTab.tsx
vscode/webviews/tabs/TabsBar.tsx

Part of https://linear.app/sourcegraph/issue/SRCH-1103/update-prompts-ui-welcome-screen
This PR does a few things (TL;DR I suggest checking the [loom](https://www.loom.com/share/3922d57405fc4db2b328a317c211231e?sid=28e903cd-aa63-4c7c-93cb-262b1de6ef7d))
- Improve prompts and commands list UI (you can find the latest designs for it [here](https://www.figma.com/design/f078wFMKsIOaEwj7Iwj5xy/Unified-Cody?node-id=4845-20933&node-type=symbol&t=Ao2Y68OYj5lFV3rA-0))
- Adds smart last-used prompts/commands sorting
So this PR is another attempt to bring commands and prompts closer and smooth transition from commands to prompts, so in this PR
- There is no separation between commands and prompts it is basically one list
- on the welcome screen we show only the last 4 used actions (action here means …

Update Prompts UI (enhanced with client last used action sorting)

---

vscode/webviews/chat/components/WelcomeMessage.tsx

Don't stretch "Recently used" and "All prompts" buttons on full width of the block
- Check that buttons don't grow and placed on the center of the prompts suggestion layout

Fix prompts button layout on welcome screen

---

lib/shared/src/configuration.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
vscode/src/auth/auth.ts
vscode/src/services/LocalStorageProvider.ts
vscode/src/services/SecretStorageProvider.ts
vscode/src/services/autocomplete-stage-counter-logger.ts

Solves [Linear issue](https://linear.app/sourcegraph/issue/CODY-350/bug-revoke-the-access-token-when-a-user-signs-out-of-jetbrains-and)
When signing in to Sourcegraph (and potentially JetBrains) using certain sign-in providers, access tokens are automatically generated. These tokens are subject to deletion under specific conditions, primarily upon logging out. However, there are nuances depending on the method of sign-in, the access token source, and whether multiple instances are involved.
Details:
1. Automatic Token Generation:
•Tokens can be automatically generated when signing in using one of the following providers:
•GitHub
•GitLab
•Google
•Sourcegraph instance (via  sign-in without token for v5.1 and above)
2. Token Deletion Criteria:
•An automatically generated token will only be …

Remove automatically generated Tokens to reduce redundant tokens

---

vscode/webviews/CodyPanel.tsx
vscode/webviews/chat/components/WelcomeMessage.tsx
vscode/webviews/components/promptSelectField/PromptSelectField.tsx
vscode/webviews/components/shadcn/ui/command.tsx
vscode/webviews/utils/useTabView.ts

This adds 
- Ghost styling for welcome area buttons
- Link "Browser library" to prompt popover UI
- Check that links work properly

Add browse library link to prompt popover

---

vscode/webviews/chat/Transcript.tsx
vscode/webviews/components/FileLink.tsx

This PR renames a bunch of OneBox telemetry events metadata fields and make them camelcase.
~~This PR also removes the check `isDotCom` from the `promptText` private metadata field passed with the `chat-question:executed` event. None of the private metadata fields are sent to SG through the telemetery pipeline, so that data is still private, similar to the other present privateMetadata field. The only change is that the `promptText` will be recorded in the event_logs on that sourcegraph instance.~~
We need to remove the check so that we can selectively collect that field for the S2 instance, configured by a env var here: https://github.com/sourcegraph/cloud/pull/15143
Make sure all the updated events are still recorded correctly.

Rename onebox telemetry metadata fields

---

lib/shared/src/sourcegraph-api/graphql/client.ts

The 6000ms timeout may be too short for some users on high-latency network connections. I have experienced this as a problem once or twice recently when on airplane (satellite) wifi. This may also help with https://github.com/sourcegraph/cody/issues/5783, but I am not certain of that since this timeout has been in place for a while and the reports of that issue are new.
Why 20s and not higher/lower? This makes it so the user does get feedback about network problems without waiting 60s (default) or longer. Why not lower (like 15s)? Arbitrary decision.
n/a

higher default timeout than 6s

---

agent/package.json
agent/src/esbuild.mjs

The benefits (smaller bundle size) are not worth the additional debugging pain, esp. since this build was only ever used for desktop releases and not web.
n/a

never minify agent

---

lib/shared/src/sourcegraph-api/errors.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
vscode/src/auth/auth.ts
vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/services/AuthProvider.ts
vscode/src/services/UpstreamHealthProvider.ts

- Improve logging
- Clean up usage of timeouts and aborts:
- Re-throw AbortErrors so that they can be treated as control flow instead of returning them. Returning them might cause callers to treat it as a network error and store (eg) a "not authenticated" result instead of abandoning the operation entirely.
- Factor out the common abort signal and timeout logic.
CI & e2e, manually reload under poor network conditions and ensure that timeouts and network errors are logged

improve auth-related logging and abort/timeout handling

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/shared/get-experiment-model.ts
vscode/src/repository/githubRepoMetadata.ts
vscode/src/services/LocalStorageProvider.ts

Fixes https://github.com/sourcegraph/cody/issues/5787 and https://github.com/sourcegraph/cody/issues/5780
1. The PR removes the caching introduced in the vscode `localStorage` in the [PR](https://github.com/sourcegraph/cody/pull/5767/files#diff-795b77ed195550f3e764295bad38afdec49b0f2ad96476c63c945df119b561f7R40) to get the repo status, and uses local cache to store the results. 
2. get request from `localStorage` was being triggered for every logging request [here](https://github.com/sourcegraph/cody/blob/main/vscode/src/completions/logger.ts#L741) causing the slowness in vscode workspace.
Do this test before and after the PR commits.
1. Open multiple workspace in vscode in the debug mode.
2. Follow the steps listed by @arafatkatze …

use local cache instead of localStorage to get repo status

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
vscode/CHANGELOG.md
vscode/package.json
vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/shared/get-experiment-model.ts
vscode/src/repository/githubRepoMetadata.ts
vscode/src/services/LocalStorageProvider.ts

- Autocomplete: The PR fixes the slowness in vscode because because of completions by using local cache instead of querying vscode localStorage. [pull/5798](https://github.com/sourcegraph/cody/pull/5798)
- Sourcegraph API GraphQL: Increase the default timeout from 6sec to 20sec. [pull/5789](https://github.com/sourcegraph/cody/pull/5789)
Cherry-pick commits & update changelog, version

VSCode: 1.36.1 Release

---

vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/providers/anthropic.test.ts
vscode/src/completions/providers/expopenaicompatible.test.ts
vscode/src/completions/providers/fireworks.test.ts
vscode/src/completions/providers/google.test.ts
vscode/src/completions/providers/openaicompatible.test.ts
vscode/src/completions/providers/shared/helpers.ts
vscode/src/completions/providers/unstable-openai.test.ts

- @sqs spotted an issue with the incorrect assertion in the `anthropic` provider tests. The problem was caused by inconsistent `authStatus` mocks. This happened because `params` from `vscode/src/completions/get-inline-completions-tests/helpers.ts` independently changed mock values to the DotCom auth status. This PR fixes it by making `params` check if the mock already exists.Inconsistent `authStatus` mocks caused the problem
CI and `pnpm vitest vscode/src/completions/providers/*.test.ts`

Autocomplete: fix `authStatus` mocks in provider tests

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/AuthStatus.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Location.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Range.kt
lib/shared/src/sourcegraph-api/graphql/client.ts
vscode/webviews/components/FileSnippet.tsx
vscode/webviews/components/codeSnippet/CodeSnippet.story.tsx
vscode/webviews/components/codeSnippet/CodeSnippet.tsx
vscode/webviews/components/codeSnippet/components/RepoLink.tsx
vscode/webviews/components/codeSnippet/types.ts

Compile JetBrains repo with CODY_DIR set to checked out code from this branch.
There should be no errors.

Fix exported types conflicting with agent protocol

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ModelAvailabilityStatus.kt
agent/src/agent.ts
agent/src/auth.test.ts
agent/src/cli/command-chat.ts
agent/src/index.test.ts
lib/shared/src/models/modelsService.ts
vscode/src/jsonrpc/agent-protocol.ts

This change will allow clients to know if model is useable for them with  of manually fetching account tier and computing model availability.
This makes client code simpler, ensures the same conditions are used by both Cody and clients, and is less error prone.
This is only used in JetBrains currently.
Testplan on the JetBrains side:
https://github.com/sourcegraph/jetbrains/pull/2386

Send info if model is available together with the model

---

lib/shared/src/experimentation/FeatureFlagProvider.ts

In the earlier cody version we had the same feature flag names. Starting experiments on these names will trigger deprecated model for the client version not updated yet. Changing the feature flag names ensures that the experiment only runs for new client version and we dont trigger deprecated models.
No functional change

change feature flag names

---

vscode/webviews/Chat.tsx
vscode/webviews/chat/components/WelcomeFooter.module.css
vscode/webviews/chat/components/WelcomeFooter.tsx
vscode/webviews/chat/components/WelcomeMessage.test.tsx
vscode/webviews/chat/components/WelcomeMessage.tsx
vscode/webviews/chat/fixtures.ts
vscode/webviews/utils/useConfig.tsx

This PR introduces a redesigned footer for Cody Chat in the VS Code extension.
NOTE: I added the `IDE` property back to UserAccountInfo in order to get this out for the release, but we should ultimately resolve this issue another way with a useIDE() hook, or something like it. 
- Manual testing
- Passing CI
- Update unit tests to reflect UI changes. Confirmed they are passing.

Add new footer design to welcome screen

---

vscode/CHANGELOG.md
vscode/src/repository/remoteRepos.ts

CLOSE: https://linear.app/sourcegraph/issue/CODY-3971/investigate-submit-button-issue-in-chat-for-enterprise-users
The `remoteReposForAllWorkspaceFolders` function was incorrectly handling non-array results, such as errors or pending operations, which could cause the function to hang indefinitely. This change filters out these non-array results and returns an empty array instead, ensuring the function behaves correctly.
Description:
This PR addresses an issue where Cody would hang when encountering a workspace folder without a remote origin URL. The problem was caused by incorrect error handling in the repository name resolution process, which led to unresolved promises and pending operations that cause the function to hang indefinitely.
Root Cause:
- The RepoNameResolver class was …

Chat: Fix hanging issue in repository name resolution for workspaces

---

vscode/CHANGELOG.md
vscode/package.json

VSCode Release: 1.36.2
changelog and version update

VS Code: Release 1.36.2

---

vscode/src/completions/inline-completion-item-provider.ts
vscode/src/completions/logger.test.ts
vscode/src/completions/logger.ts

Use the current document for tracking the insertText. Using the pre-calculated text was making the offline diffs inaccurate, as introduced in the [PR](https://github.com/sourcegraph/cody/pull/5767/files).
CI checks

use the current document to track range for persistence

---

vscode/src/commands/context/shell.ts

If DeepCody tries to execute a disallowed shell command, it will remain in the `thinking' state.
This PR fixes and improves the error handling mechanism for disallowed shell commands in the `getContextFileFromShell` function.
Changes:
- Relocated the disallowed command check inside the try block for better error management
- Implemented a user-facing error message using `vscode.window.showErrorMessage`
- Retained the existing error throw for maintaining consistency with error handling patterns
- Verified that disallowed commands trigger the new error message and DeepCody does not hang.
- Ensured that allowed commands continue to function as expected
- Checked that the error throw still occurs for proper error propagation

DeepCody: Enhance error handling for disallowed shell commands

---

agent/src/TestClient.ts
agent/src/agent.ts
agent/src/cli/command-bench/strategy-chat.ts
agent/src/cli/command-chat.ts
agent/src/index.test.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatsController.ts
vscode/src/chat/protocol.ts
vscode/src/code-actions/explain.ts
vscode/src/commands/execute/ask.ts
vscode/src/commands/execute/doc.ts
vscode/src/commands/execute/explain-history.ts
vscode/src/commands/execute/explain.ts
vscode/src/commands/execute/smell.ts
vscode/src/commands/execute/terminal.ts
vscode/src/commands/execute/test-chat.ts
vscode/src/commands/menus/index.ts
vscode/src/commands/services/runner.ts
vscode/test/integration/single-root/chat.test.ts
vscode/webviews/chat/Transcript.tsx

This controlled whether a chat would reuse the same window or create a new one. Replies and edits reuse the same chat window, but everything else (except for custom commands, optionally) starts a new chat.
The only user-facing behavior change is for custom commands (described below).
The `user` `ChatSubmitType` was used in 2 places:
- For edits in ChatController (not needed, can refactor more simply internally)
- For custom commands
Since custom commands are being removed and the "reuse existing chat window" of custom commands is not important to preserve even for now, we can simplify the code by removing this mode and `submitType` throughout.
CI & e2e

remove ChatSubmitType user-newchat

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/CodyAgentServer.kt
agent/protocol.md
agent/recordings/defaultClient_631904893/recording.har.yaml
agent/src/__snapshots__/index.test.ts.snap
agent/src/agent.ts
agent/src/global-state/AgentGlobalState.ts
agent/src/index.test.ts
lib/shared/src/configuration/resolver.ts
lib/shared/src/index.ts
lib/shared/src/misc/observable.ts
lib/shared/src/models/modelsService.ts
lib/shared/src/models/sync.test.ts
lib/shared/src/models/sync.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/jsonrpc/agent-protocol.ts
vscode/src/services/LocalStorageProvider.ts

In the agent tests, the `testing/reset` command was not entirely resetting
the state between tests. This meant that 2 tests (explain and smell) that
performed explicit `chat/setModel` requests to change the model to Mixtral but
were (incorrectly) running with the chat model used for the previous tests.
The reason is that `testing/reset` just cleared the in-memory
`LocalStorageProvider` backing `Map` and did not cause
`LocalStorageProvider` to fire a change event, which is necessary for the
`ModelsService` to know that the models preferences changed.
Also clean up types.
Agent tests

fix agent tests model preferences state

---

.config/viteShared.ts
agent/src/document-code.test.ts
agent/src/edit.test.ts
vscode/src/completions/context/retrievers/lsp-light/lsp-light-retriever.integration.test.ts
vscode/src/tree-sitter/grammars.test.ts
vscode/src/tree-sitter/query-tests/documentable-nodes.test.ts

Almost all tests finish in 500ms. If a test is taking longer, it's probably hanging indefinitely, and killing it at 500ms gives faster feedback.
n/a

default vitest unit test timeout of 500ms

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/CodyAgentServer.kt
agent/protocol.md
agent/src/__snapshots__/index.test.ts.snap
agent/src/agent.ts
agent/src/index.test.ts
vscode/src/jsonrpc/agent-protocol.ts

This is [not used in JetBrains](https://sourcegraph.com/search?q=repo:sourcegraph/jetbrains+chat/restore&patternType=keyword&sm=0) and was marked for deletion 2 months ago.
CI & e2e

remove unused chat/restore agent method

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/AuthStatus.kt
lib/shared/src/auth/types.ts
lib/shared/src/chat/chat.ts
lib/shared/src/index.ts
lib/shared/src/misc/observable.ts
lib/shared/src/misc/rpc/webviewAPI.ts
lib/shared/src/models/modelsService.test.ts
lib/shared/src/models/modelsService.ts
lib/shared/src/models/sync.test.ts
lib/shared/src/sourcegraph-api/userProductSubscription.ts
lib/shared/src/telemetry-v2/TelemetryRecorderProvider.ts
lib/shared/src/telemetry-v2/cody-tier.ts
vscode/src/auth/account-menu.ts
vscode/src/auth/auth.ts
vscode/src/chat/agentic/DeepCody.test.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/protocol.ts
vscode/src/chat/utils.ts
vscode/src/completions/fast-path-client.ts
vscode/src/completions/providers/shared/create-provider.test.ts
vscode/src/completions/providers/shared/helpers.ts
vscode/src/edit/input/get-input.ts
vscode/src/main.ts
vscode/webviews/App.story.tsx
vscode/webviews/AppWrapperForTest.tsx
vscode/webviews/utils/useConfig.tsx

This moves the user's product subscription status to a separate global observable, which saves one roundtrip and at least ~300ms from the time it takes to sign in when using Sourcegraph.com.
CI & e2e

do not block on fetching the user's Cody Pro subscription status when authing

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/AuthStatus.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ServerInfo.kt
agent/src/agent.ts
lib/shared/package.json
lib/shared/src/auth/types.ts
lib/shared/src/chat/chat.ts
lib/shared/src/cody-ignore/context-filters-provider.test.ts
lib/shared/src/index.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/siteVersion.test.ts
lib/shared/src/sourcegraph-api/siteVersion.ts
pnpm-lock.yaml
vscode/src/auth/auth.ts
vscode/src/chat/agentic/DeepCody.ts
vscode/src/chat/chat-view/ChatController.test.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/utils.test.ts
vscode/src/chat/utils.ts
vscode/src/commands/scm/source-control.ts
vscode/src/edit/manager.ts
vscode/src/edit/prompt/smart-apply.ts
vscode/src/edit/provider.ts
vscode/src/external-services.ts
vscode/src/jsonrpc/agent-protocol.ts
vscode/src/supercompletions/get-supercompletion.ts
vscode/webviews/App.story.tsx

The site version and Cody API version is now exposed in the `siteVersion` global observable, which returns the site version and Cody API version for the currently authenticated endpoint (and caches the value).
If the Sourcegraph instance does not have Cody enabled, this means that the error message will come later, not at sign-in. With one box, the lines are getting blurrier anyway, and the logic for determining if Cody was enabled was complex and often treated network errors as "Cody is disabled". It is not worth it to invest time in making this more robust because few users will encounter this, and those who do will just get an error that Cody is disabled when they actually try to perform any operation.
This means that initial auth takes 1-3 less HTTP requests.
CI & e2e

do not block on getting the site version or is-cody-enabled during auth

---

agent/src/enterprise-s2.test.ts
vscode/src/chat/chat-view/ChatController.test.ts
vscode/src/chat/chat-view/ChatController.ts

This makes `ChatController.handleUserMessageSubmission` less unwieldy and makes other future refactors easier.
CI

extract ChatController.sendChat

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/AuthStatus.kt
lib/shared/src/auth/types.ts
lib/shared/src/index.ts
lib/shared/src/models/configOverwrites.ts
lib/shared/src/models/modelsService.ts
lib/shared/src/models/sync.test.ts
lib/shared/src/models/sync.ts
vscode/src/auth/auth.ts
vscode/src/chat/utils.ts
vscode/src/completions/create-inline-completion-item-provider.ts
vscode/src/completions/get-inline-completions-tests/helpers.ts
vscode/src/completions/inline-completion-item-provider-e2e.test.ts
vscode/src/completions/inline-completion-item-provider.test.ts
vscode/src/completions/providers/anthropic.test.ts
vscode/src/completions/providers/anthropic.ts
vscode/src/completions/providers/expopenaicompatible.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/google.ts
vscode/src/completions/providers/openaicompatible.ts
vscode/src/completions/providers/shared/create-provider.test.ts
vscode/src/completions/providers/shared/create-provider.ts
vscode/src/completions/providers/shared/helpers.ts
vscode/src/completions/providers/shared/provider.ts
vscode/src/completions/providers/unstable-openai.ts
vscode/src/completions/request-manager.test.ts

To authenticate a user and start showing the UI, we actually don't need to
fetch the CodyLLMSiteConfiguration (`configOverwrites`). This reduces the
number of HTTP requests (albeit they were parallelized somewhat) needed
before the user can be authenticated and start seeing the Cody UI.
This uncovered some possible "bugs" in the `anthropic.test.ts` autocomplete
tests, where they were asserting that the `model` would be set but it
actually would not be in real life. In `Provider.maybeFilterOutModel` it
sees that `this.configOverwrites?.provider === 'sourcegraph'` in the test,
but that should not be true in real life because it’s being passed an
`authStatus` that is non-dotcom. The reason the test is bad is because that
method gets the auth status from `currentAuthStatus()`, which is dotcom …

do not block on CodyLLMSiteConfiguration (configOverwrites) fetch in initial auth

---

agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml
agent/src/enterprise-s2.test.ts

- Re-enables the S2 context filters autocomplete agent tests.
- Disables 25 runs of the `testing/ignore/overridePolicy` that was flaky, but it looks like [the latest improvement](https://github.com/sourcegraph/cody/pull/5647) from @sqs stabilized it, so we can run it only once. 
- Part of https://linear.app/sourcegraph/issue/CODY-3910/add-autocomplete-integation-tests-for-server-side-model-config
- Closes https://linear.app/sourcegraph/issue/CODY-2814/fix-and-re-enable-cody-context-filters-agent-integration-test
CI and `pnpm vitest agent/src/enterprise-s2.test.ts`

Autocomplete: context filters autocomplete agent tests

---

.vscode/settings.json
lib/shared/src/chat/transcript/index.ts
lib/shared/src/chat/transcript/messages.ts
vscode/src/chat/chat-view/ChatController.test.ts

Some previous refactoring caused a regression bug which broke, showing a response based on intent for One Box. The intent was not getting serialized as part of the chat message. This PR fixes it. 
- make sure all intent executions work correctly on s2.

Fix chat message intent serialization

---

lib/shared/src/sourcegraph-api/environments.ts
lib/shared/src/telemetry-v2/events/chat-question.ts
vscode/src/chat/chat-view/ChatController.ts

Issue: https://linear.app/sourcegraph/issue/AI-337/create-way-to-query-s2-query-privatemetadata-data
We need to record `promptText` on S2 instance for learning from dog fooding. 
- Submit a chat and make sure that the prompt Text is being recorded.

Record promptText for S2

---

vscode/webviews/themes/visual-studio.css

CLOSE https://linear.app/sourcegraph/issue/CODY-3954/visual-studio-fix-color-on-light-theme
- Updates the `--vscode-inputOption-activeBackground`, `--vscode-inputOption-activeBorder`, and `--vscode-inputOption-activeForeground` variables in the visual-studio theme to use more appropriate colors.
- The previous colors were using the `--visualstudio-startpagebuttonunpinned`, `--visualstudio-startpagebuttonborder`, and `--visualstudio-startpagebuttontext` variables, which were not the best fit for input option active styles.
- The new colors use the `--visualstudio-startpagetextcontrollinkselected` and `--visualstudio-startpagetextbody` variables, which works better in both light and dark theme in Visual Studio for @-mention tokens
Build Visual Studio with this branch to confirm the @ …

Visual Studio: update at-mention token colors

---

lib/shared/src/models/sync.test.ts
lib/shared/src/models/sync.ts
vscode/src/chat/agentic/DeepCody.test.ts
vscode/src/chat/agentic/DeepCody.ts
vscode/src/chat/chat-view/ChatController.ts

CLOSE https://linear.app/sourcegraph/issue/CODY-3988/move-enrollment-out-of-models-getter that addresses comment in https://github.com/sourcegraph/cody/pull/5687/files#r1788676940 
Main change
Eemove the logic that mutate user-selected model from the "getter" in ChatController on models changes & add new logic handles setting Deep Cody as the default on first sync:
- Set Deep Cody as default chat model on first sync when it is available.
- Add logic to set the user's selected chat model to Deep Cody during the first sync.
This also fixes the issue where Deep Cody is showing up in the Edit model dropdown as we updated to set `data.preferences!.defaults.edit` and `data.preferences!.defaults.chat` separately:
Manual Test Plan:
1. Log into S2 and make sure you can see `Deep Cody` is selected …

Chat: update logic to select Deep Cody as default model when available

---

vscode/webviews/components/promptList/PromptList.tsx
vscode/webviews/prompts/PromptsTab.tsx

Fixes https://linear.app/sourcegraph/issue/SRCH-1131/make-prompts-dropdown-menu-a-recently-used-list
This PR changes how smart recently used prompt ordering works. Previously, we counted the number of times a user clicked on prompts and used this aggregated count value to sort the list of prompts. 
Now we just set the timestamp to the used prompt and sort it by this, so it's truly the most recently used prompt (always will be on top of the list)
- Check that in the prompt list you can see the right order of prompts

Fix last used prompts ordering

---

agent/src/cli/command-bench/command-bench.ts

Call `setClientCapabilitiesFromConfiguration(getConfiguration())` in the right place so `cody internal bench` doesn't throw an exception.
Only affects `cody internal bench`

fix bug in cody bench

---

vscode/src/chat/chat-view/ChatController.ts
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx
vscode/webviews/tabs/TabsBar.tsx
vscode/webviews/utils/debugger.ts
vscode/webviews/utils/useConfig.tsx

Fixes part of https://linear.app/sourcegraph/issue/CODY-3943/optimize-performance-for-large-chat-windows-in-cody
It looks like since https://github.com/sourcegraph/cody/pull/5036 we've lost memoization in a few places. As a result, our chat UI doesn't perform well with more than 4-5 messages (depending on how long these chat messages are)
This PR tries to improve it by fixing memoization on expensive components (Transcript, HumanMessage, ...etc)
| ------- | ------- |
| <video src="https://github.com/user-attachments/assets/79e7b93c-ac82-4a8c-9b2e-6c712af3fb2c" /> | <video src="https://github.com/user-attachments/assets/223b3513-0f30-47cc-b24c-c54f4861329c" /> | 
This PR also fixes a problem with one-box intention detection; previously, it produced a state where we …

Fix Cody Chat UI rendering reconciliation

---

vscode/src/services/utils/codeblock-action-tracker.ts

[Loom Video
](https://www.loom.com/share/bea3a44d28764ebd91170858915a5139)
[Linear Issue
](https://linear.app/sourcegraph/issue/QA-82/vsc-continuous-loading-is-shown-on-clicking-apply-button-when-source)
Tested locally and attached a video showing the solution

Adding more checks for absolute paths while generating new files with smart Apply

---

vscode/webviews/components/promptList/ActionItem.module.css
vscode/webviews/components/promptList/PromptList.module.css
vscode/webviews/components/promptList/PromptList.tsx
vscode/webviews/components/promptSelectField/PromptSelectField.tsx
vscode/webviews/prompts/PromptsTab.module.css
vscode/webviews/prompts/PromptsTab.tsx

Fixes: https://linear.app/sourcegraph/issue/SRCH-1146/stick-browse-library-link-to-the-bottom-irrespective-of-scroll
This PR
- Makes prompt search input UI sticky 
- Fixes paddings for Cody Web
- Fixing browser prompt footer 
- Check that the Prompt UI list looks ok in the welcome area, prompts select field modal and prompts tab UI

Fix prompt input and browse prompts UI 

---

vscode/webviews/Chat.story.tsx
vscode/webviews/Chat.tsx
vscode/webviews/CodyPanel.tsx
vscode/webviews/chat/Transcript.story.tsx
vscode/webviews/chat/Transcript.test.tsx
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx
vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.test.tsx
vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx
vscode/webviews/components/modelSelectField/ModelSelectField.tsx

Description: This PR aims to improve the performance and reduce potential memory leaks in our chat component by lifting the chatModels observable creation to a higher-level component and passing it down as props. This change eliminates multiple subscriptions created for each chat message.
Key changes:
- Moved the chatModels observable creation from individual components to the CodyPanel component.
- Added a 'models' prop to relevant components to pass down the chat models.
- Updated the Transcript, HumanMessageCell, HumanMessageEditor, and Toolbar components to use the passed models prop instead of creating their own observable.
- Updated related test files and storybook stories to accommodate the new 'models' prop.
- Verify that the chat functionality works as expected with the new …

Chat: move chatModels observable creation to top level

---

vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx

Follow up on https://github.com/sourcegraph/cody/pull/5866
- Use `useMemo` to get the first current chat model instead of `useObservable` to avoid unnecessary re-renders
- Update `Transcript` to use the `humanMessage.index` as the key for `TranscriptInteraction` components
Green CI
Same test plan as https://github.com/sourcegraph/cody/pull/5866
Chat: Fix performance issue with Chat webview.

Chat: use memoized models props in HumanMessageEditor

---

vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/messageCell/assistant/AssistantMessageCell.tsx

- Use the `models` prop passed down from the parent component instead of creating a new observable for the chat models for each assistant message cell
- Update `useChatModelByID` to use the passed `chatModels` array instead of creating a new observable
- Update `Transcript` to pass the `models` prop to `AssistantMessageCell`
No behavior changes. Everything including the tests are expected to work the same.

Chat: use memoized chat models in AssistantMessageCell

---

lib/shared/src/editor/hydrateAfterPostMessage.test.ts
lib/shared/src/editor/hydrateAfterPostMessage.ts
lib/shared/src/index.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/minion/MinionController.ts
vscode/webviews/utils/VSCodeApi.ts

Webviews' RPC system registers "a lot" (in a long chat, hundreds) of 'message' event handlers. Each of these typically causes the following work:
- Deliver the message, including creating MessageEvent.data. For chat transcripts this can be a large object.
- Walk the whole event data, testing whether each value is a URI, and if so, instantiating a URI for it.
- Examine a field, like `type` or RPC stream ID, and decide to discard the message because it is for a different subscriber.
This work is dispatched synchronously to the hundreds of listeners on the webview main thread, causing us to have long pauses where we don't produce a frame. In extreme cases we can hang the renderer enough for VSCode to trigger a webview reload, (...but our webview reloading may not be robust because we do not …

fix/chat: Improve performance in streaming responses in long chats

---

vscode/CHANGELOG.md
vscode/webviews/chat/cells/messageCell/assistant/AssistantMessageCell.tsx

Currently, bot messages get re-render on every message change even when the message text does not. This should help with Code Blocks getting re-rendered constantly during streaming when the message text does not.
- Use memoized `reformatBotMessageForChat` function to avoid unnecessary re-renders when `message.text` prop is unchanged
- Simplify `displayMarkdown` calculation by checking if `message.text` is defined before calling `reformatBotMessageForChat`
All the current tests should pass since this is an unbreaking change.

Chat: optimize rendering bot message

---

lib/shared/src/configuration.ts
lib/shared/src/prompt/prompt-string.ts
vscode/src/chat/agentic/DeepCody.test.ts
vscode/src/chat/chat-view/prompt.test.ts
vscode/src/chat/chat-view/prompt.ts
vscode/src/configuration.ts
vscode/src/edit/prompt/index.ts
vscode/src/testutils/mocks.ts

This fixes 2 minor problems:
- The chat and edit preinstructions were being read from global VS Code config instead of the `resolvedConfig` observable, which is now the standard way to read config.
- Each call to `getConfiguration` would result in new distinct PromptString instances being created and added to the WeakMap that implements immutability and encapsulation for PromptString. Now, in the common case where these are not set, this garbage is not created in the first place.
Neither of these were causing any problems I've observed, but these are good fixes nonetheless.
CI

allow undefined chat/edit preinstructions, read from global config

---

lib/shared/src/editor/hydrateAfterPostMessage.test.ts
lib/shared/src/editor/hydrateAfterPostMessage.ts

PromptString instances can't be cloned because their reference value is used as the key in the WeakMap that implements immutability and encapsulation for PromptString.
(This broke something on a separate branch, so I extracted the fix and test case to merge separately here.)
Added test case

support forceHydration on PromptString

---

agent/src/cli/command-bench/strategy-chat-context-types.ts

Corrected Parsing logic for essentialContext with comma separated instead of newline separated
No review required: deploys tested changes.

Corrected parsing logic for essentialContext

---

agent/src/autocomplete.test.ts
agent/src/enterprise-s2.test.ts
vscode/src/completions/inline-completion-item-provider.ts

- **Do not merge this until all the clients are updated**.
- This PR proposes to change the behavior of the `autocomplete/execute` requests for the agent based on the [feedback in Slack](https://sourcegraph.slack.com/archives/C073U3KE5DK/p1728559419953909). 
- `InlineCompletionItemProvider.provideInlineCompletionItems()` no longer executes the VS Code-specific logic, which makes all completions start at the beginning of the line no matter what the current cursor position is. This logic was added to avoid UI jitter in VS Code, but it does not apply to other Cody clients and requires them to implement additional post-processing logic for no apparent reason.
- This is a breaking change for clients using the agent API `autocomplete/execute`. cc @abeatrix @PiotrKarczmarz
- Previous PR with the …

Autocomplete: keep the original insert range for agent `autocomplete/execute` calls

---

pnpm-lock.yaml
vscode/package.json
vscode/webviews/components/codeSnippet/CodeSnippet.tsx

visibility-sensor uses `findDOMNode`, which triggers a warning in strict mode. This swaps it out for a more modern and actively maintained alternative, react-intersection-observer
The warning this PR fixes:
There should be no end-user-visible changes.
Test out one box search to ensure results are still rendered properly

Swap out visibility-sensor for react-intersection-observer

---

agent/src/cli/command-auth/AuthenticatedAccount.ts
agent/src/cli/command-models.ts
agent/src/cli/command-root.ts

Fixes CODY-4031
Previously, there was no easy to way to know what LLM model IDs are accepted by the backend. We have HTTP APIs to retrieve this information, but it was cumbersome to discover the APIs and construct the correct cURL invocation. Now, Cody CLI users can just run `cody models list`. I want with a `models list` command structure so that we can add more model-related commands in the future, like configuring the default model for the `cody chat` subcommand.
```
❯ pnpm agent models list
...
anthropic::2023-06-01::claude-3.5-sonnet
anthropic::2023-06-01::claude-3-opus
anthropic::2023-06-01::claude-3-haiku
fireworks::v1::starcoder
fireworks::v1::deepseek-coder-v2-lite-base
google::v1::gemini-1.5-pro
google::v1::gemini-1.5-flash
openai::2024-02-01::gpt-4o …
```

CLI: add `cody models list` command

---

vscode/src/edit/provider.ts
vscode/src/services/utils/codeblock-action-tracker.ts
vscode/src/services/utils/edit-create-file.test.ts
vscode/src/services/utils/edit-create-file.ts

Fixes https://linear.app/sourcegraph/issue/QA-116
It's hard to reproduce actual issue as it depends on the LLM response.
Test scenario which sometimes can reproduce it:
**For "Generate Unit Test":**
1. Opens some workspace, and then file from outside of that workspace
2. Run "Generate Unit Test" for that file
3. Make sure test file is generated properly and the location of the file looks sensible
**For "Smart Apply":**
Case1:
1. Open some workspace
2. Ask Cody to generate some code sample in totally unrelated to the existing workspace (e.g. "quicksort in haskell")
3. Click Smart Apply
4. Make sure Cody created new file for the given snipped and it's name and location looks sensible
Case 2: 
1. Open some workspace, and then unrelated file from outside of that workspace
2. Ask Cody to …

Improve edit task and smart apply destination file path computation

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Constants.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ModelTag.kt
lib/shared/src/models/dotcom.ts
lib/shared/src/models/model.ts
lib/shared/src/models/modelsService.test.ts
lib/shared/src/models/modelsService.ts
lib/shared/src/models/tags.ts

CLOSE : https://linear.app/sourcegraph/issue/CODY-4059/opus-should-be-listed-under-othe
The issue: When processing the Opus model, which had a category of 'other', the getServerModelTags function was adding the ModelTag.Balanced tag to it. This is why it was showing up under the "Balanced" category in the UI.
The fix:  This change adds a new 'other' model category to the ModelTag enum and updates the related model service and configuration code to handle this new category. This change allows the 'other' category to be directly used without being converted to 'Balanced'.
- Adding 'other' as a new ModelTag enum value
- Updating the ModelCategory type to include 'other'
- Updating the getServerModelTags function to handle the 'other' category
- Updating the mocked server …

Chat: Display 'other' model category

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/completion-provider-config.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/shared/get-experiment-model.ts

- Adds a feature flag for the fast-path A/B test.
- Removes redundant `cody-autocomplete-claude-3` and `cody-autocomplete-fim-fine-tuned-model-hybrid` feature flags.
- Updates the preload-completions-on-cursor-movement A/B debounce time for the second phase of the A/B test.
- Part of https://linear.app/sourcegraph/issue/CODY-4037/ab-test-fast-path-to-get-the-up-to-date-impact-stats
- No functional changes. All of the updates are behind feature flags.
- CI

Autocomplete: a/b test the fast-path

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/WebviewNativeConfig.kt
agent/src/NativeWebview.ts
agent/src/agent.ts
agent/src/allClientCapabilitiesEnabled.ts
agent/src/cli/command-bench/command-bench.ts
agent/src/cli/command-bench/llm-judge.ts
lib/shared/src/auth/referral.ts
lib/shared/src/configuration.ts
lib/shared/src/configuration/clientCapabilities.ts
vscode/src/chat/protocol.ts
vscode/src/commands/CommandsController.ts
vscode/src/extension-client.ts
vscode/src/jsonrpc/agent-protocol.ts
vscode/src/main.ts
vscode/webviews/CodyPanel.tsx
vscode/webviews/chat/components/WelcomeMessage.test.tsx
web/lib/agent/agent.client.ts

Previously, only the agent code could read the agent capabilities, but they're actually useful throughout the Cody codebase and describe what the current client is capable of. We should use them instead of checking `agentIDE` and assuming based on what kind of editor it is on the other side, since that is coarse.
No behavior change.
CI

expose agent capabilities in global clientCapabilities()

---

agent/src/AgentWorkspaceConfiguration.ts
lib/shared/src/auth/referral.ts
lib/shared/src/configuration.ts
vscode/webviews/components/MarkdownFromCody.tsx
web/lib/agent/agent.client.ts

`CodyIDE.Web` previously referred to both (1) Cody Web, i.e., the Cody sidebar in Sourcegraph Code Search and the Cody chat page, and (2) this repo's `web/` demo app. They are different and have different needs. It is generally bad to change behavior based on the identity (as opposed to capabilities) of the client, which will be addressed in https://github.com/sourcegraph/cody/pull/5889 and beyond, but for now, it's helpful for them to report different client identities.
CI

different agentIDE for Cody Web vs. this repo's standalone web/

---

.vscode/settings.json
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatsController.ts
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/contextCell/ContextCell.tsx
vscode/webviews/components/FileContextItem.tsx
vscode/webviews/components/FileSnippet.tsx
vscode/webviews/components/codeSnippet/CodeSnippet.tsx
vscode/webviews/components/codeSnippet/components/RepoLink.tsx

closes: https://linear.app/sourcegraph/issue/SRCH-1119/add-to-chat-from-search-results
This PR adds 2 actions for search result snippets shown under One Box experiment. 
1. Add to follow-up question
2. Add to new Cody chat
Both actions add the file as @-mention to the chat inputs
Loom: https://www.loom.com/share/e062d698613b422fbe919738cd024594
- Perform a search intent query and try both actions.

Add context item to chat action

---

vscode/src/chat/chat-view/ContextRetriever.test.ts
vscode/src/chat/chat-view/ContextRetriever.ts
vscode/src/local-context/symf.ts
vscode/src/main.ts

Previously, the `ContextRetriever` class was using a `rewriteKeywordQuery` function to modify the original query before sending it to the server for indexed context retrieval. This client-side query rewriting is now redundant.
This PR removes the client-side query rewriting in the `ContextRetriever` class. The changes include:
1. Removing the `rewriteKeywordQuery` function call from the `ContextRetriever` class.
2. Passing the original query directly to the server for indexed context retrieval.
3. Updating the `SymfRunner` class to use the original query for live results.
4. Updating tests to reflect these changes and ensure the original query is used throughout the retrieval process.
5. Updated and added tests in `ContextRetriever.test.ts` to verify the correct usage of the original …

Remove client-side query rewriting in ContextRetriever

---

vscode/scripts/github-changelog.ts

updating release notes to include sourcegraph public changelog link instead of previous blog entries
N/A

update changelog link in release note automation

---

vscode/webviews/tabs/AccountTab.story.tsx
vscode/webviews/tabs/AccountTab.tsx

https://linear.app/sourcegraph/issue/CODY-4066/avatar-is-not-scaled-correctly-on-agent-account-page
Chat: update account tab UI
- Adjust user avatar size and position
- Add link to account endpoint URL
NOTE: The account tab is currently used by non-VS Code IDE clients only.
Starts Cody with this branch in Visual Studio / JetBrains / Eclipse, or run the storybook to verify the user avatar in the account tab is showing up nicely:

Agent: fix avatar in account tab

---

lib/prompt-editor/src/PromptEditor.tsx
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
vscode/src/chat/protocol.ts
vscode/webviews/chat/cells/messageCell/assistant/AssistantMessageCell.tsx
vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx
vscode/webviews/components/promptList/PromptList.tsx
vscode/webviews/prompts/PromptsTab.tsx

closes: https://linear.app/sourcegraph/issue/SRCH-1138/make-your-drafts-be-available-in-the-editor
closes: https://linear.app/sourcegraph/issue/SRCH-1173/prompts-have-the-option-to-be-set-to-automatically-run-without-the
Blocked on: https://github.com/sourcegraph/sourcegraph/pull/1003
This PR includes the new `includeViewerDrafts: true` argument in prompts query, added as part of the backend PR. This will allow to list user's owned draft prompts along with all the non draft prompts accessible to the user.
This PR also integrates the new `autoSubmit` field on prompts, added as part of the backend PR. The prompts with autoSubmit set as true will be automatically executed in one click when the user selected them. For other only the input box will be updated with the prompt text as currently. …

Include draft prompts for viewer

---

agent/src/agent.ts
agent/src/cli/scip-codegen/emitters/JavaEmitter.ts

In the startup of the agent, we copy over the local webview assets into the cody data directory. This overwrites the template files that eclipse writes to that directory. The eclipse extension is packaged with the webview assets it's compiled with and manages serving those resources from it's own JAR. This change prevents any version mismatch issues that can occur from the double copy.
Also includes a small fix for Java code generation.
Manually tested with Eclipse that it resolved issues loading CSS

fix(webview): Skip webview copying for eclipse

---

vscode/src/services/AuthProvider.ts

I've added `cody.serverEndpoint` context variable, which on the clients side is received through `window/didChangeContext` notification.  We need it on the jetbrains side in few places, e.g. when we are checking if current account is a dotcom account.
I think it might be better idea to replace this with a dedicated endpoint, but I'm not sure if `cody.activated` is currently used anywhere?
@dominiccooney @sqs WDYT?
Full QA with https://github.com/sourcegraph/jetbrains/pull/2382/ is needed.
It does not change anything on the Cody side.

Add setContext notification for cody.serverEndpoint

---

lib/shared/src/telemetry-v2/events/chat-question.ts

This PR corrects the `billingMetadata` for the event `cody.chat-question/executed` to be `core`, as per our definition [here](https://www.notion.so/sourcegraph/V2-telemetry-product-and-category-documentation-b4f932118ea5421587e6e0a0d90d78e1?pvs=4#f29991216c834cbd92ccacb2d3f161d4).
E2E tests + locally

Update `cody.chat-question/executed` billingMetadata

---

lib/prompt-editor/src/PromptEditor.tsx
lib/shared/src/lexicalEditor/editorState.ts
lib/shared/src/lexicalEditor/nodes.ts
lib/shared/src/misc/rpc/webviewAPI.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/commands/context/selection.ts
vscode/src/commands/context/workspace.ts
vscode/src/prompts/prompt-hydration.ts
vscode/src/prompts/utils.ts
vscode/webviews/AppWrapperForTest.tsx
vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx
vscode/webviews/client/clientState.tsx
vscode/webviews/prompts/PromptsTab.tsx
web/lib/components/CodyWebChat.tsx

Closes SRCH-1182
Closes SRCH-1165
Closes SRCH-1166
Closes SRCH-1167
Closes SRCH-1168
Closes SRCH-1169
Closes SRCH-1170
This PR adds support for generic mention in prompt messages, now you can mention the current directory, repository, file, selection, and open tabs in a prompt message via ``[[...]]`` syntax (later we will support mention UI on the web side so you don't have to type `[[..]]` manually). 
The full generic mentions syntax 
- `[[current file]]` 
- `[[current selection]]` - fall back on the current file if we don't have any active selection
- `[[current directory]]` - currently we search for the first 10 files in the local directory and replace this mention with multiple file mentions from this directory but later we will support openctx directory mention so we can mention any …

Add support for generic mentions in prompt messages

---

vscode/CHANGELOG.md

A merge messed up the CHANGELOG. This fixes it.
Read `vscode/CHANGELOG.md` and ensure that 1.38.1 and 1.38.0 are correct. Reference [this commit](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody@d21f7c00ab158485dc487ff61ea6dd8d40af67f1/-/raw/vscode/CHANGELOG.md) to ensure.

Fix VSCode CHANGELOG after merge

---

.github/labeler.yml

RELATED TO https://github.com/sourcegraph/jetbrains/pull/2472
Adding `repo/cody` to help distinguish where issues originate from when we sync them back into linear 
N/A

add repo/cody to labeler

---

vscode/webviews/tabs/AccountTab.tsx

In the client:
1. Open Accounts tab
2. There should be no `witch Account...` button.
In JetBrains switching accounts is still possible using native account management panel (accessible e.g. using Cody icon on the status bar or from the Cody settings).

Temporarily remove switch account button

---

vscode/src/services/CharactersLogger.test.ts
vscode/src/services/CharactersLogger.ts
vscode/src/testutils/mocks.ts

Updated `CharacterLogger` to gain more insights into the unexpectedly high number of insertions that affect our metrics. 
- Group document changes by size.
- Rely on `vscode.window.activeTextEditor` to track edits from the active window.
- Rely on `activeTextEditor.visibleRanges` to mark edits as outside of the viewport.
- There's no way to detect if the active text editor is focused using the VS Code API. Here's [the GitHub issue](https://github.com/microsoft/vscode/issues/117980) where I asked for updates. It means we cannot reliably detect cases where users switched to the integrated terminal window or to the sidebar where they can perform actions that would result in a high number of insertions/deletions (e.g., by interactive with version control CLI or UI).
- To gain more information …

VS Code: log more data from characters logger

---

ARCHITECTURE.md

Adds a "style" section to ARCHITECTURE.md and documents some feedback that has come up in code review recently.
This is a docs only change.
- There are now some style guidelines in ARCHITECTURE.md.

docs: Add a style section to ARCHITECTURE.md

---

vscode/webviews/components/modelSelectField/ModelSelectField.tsx

CLOSE https://linear.app/sourcegraph/issue/MKT-344
Based on the discussion in the linear issue, we would like to avoid listing Deep Cody under any existing model group but on its own under 'mixed models":
- Add a new 'DeepCody' model UI group to the `ModelUIGroup` object
- Update the `getModelDropDownUIGroup` function to handle the 'deep-cody' model ID and return the new 'DeepCody' group
Small UI change:

DeepCody: new model UI group

---

vscode/.storybook/main.ts

A recent change (e9a460ebce9306ef9da39cace4e58f11826b4a3a) broke the storybook dev build, because it made `env-paths` a dependency of `lib/shared`, resulting in an error `os.homedir is not a function` in storybook's browser environment.
This fixes it by taking `env-paths` out of `lib/shared`, duplicating it `agent/` and `vscode/`. There may be a more elegant to do this through the vite config—I see a resolve override in `agent` to prevent this dep from being imported/activated, but not sure how to do that.
No changes

fix storybook build

---

.github/ISSUE_TEMPLATE/bug_report.yml

Github issue forms doesn't allow empty keys in their template, removing `title: ''`
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#key-must-be-a-string
N/A

remove empty title key in template

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/SerializedChatMessage.kt
lib/prompt-editor/src/PromptEditor.tsx
lib/prompt-editor/src/nodes/ContextItemMentionNode.tsx
lib/shared/src/chat/transcript/messages.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
lib/shared/src/telemetry-v2/events/chat-question.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/protocol.ts
vscode/src/commands/CommandsController.ts
vscode/src/commands/execute/index.ts
vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx
vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/SubmitButton.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx
vscode/webviews/prompts/PromptsTab.tsx

closes: https://linear.app/sourcegraph/issue/SRCH-1172/prompts-can-output-into-3-places
This PR integrates with the prompt mode (chat | edit | insert) from the SG API. Prompts with edit or insert mode are executed using the `executeEdit`, the same way the commands are executed. The prompt is used as the instruction text for `executeEdit`. First the chat transcript is created, context is fetched and then the `executeEdit` is called. The `FixupTask` from the execution is used to construct the response in chat. The response for now shows the diff only. 
In BG, the state for interactions mode is saved as intent. The dropdown and icon indicator for to allow users to manually change the mode and to see which mode is set, is only available behind the OneBox feature flag and will not be released …

Implement edit/insert prompts

---

agent/src/global-state/AgentGlobalState.test.ts
agent/src/global-state/AgentGlobalState.ts

To avoid further doubts I adjusted behaviour and interface of `LocalStorageDB`to be more in sunc with `vscode.Memento`, that is:
* setting key to `null` or `undefined` removes key from the store
* get on non-existing key returns an `undefined`
Note that it means setting key to `null` and then doing get on it will result in `undefined` value, not a `null`.
I also added exception handling in the `LocalStorageDB::get` to make sure we won't fail on previously incorrectly serialised values.
Unit tests which should cover all corner cases were added.

Fix issues with incorrect serialization of LocalStorageDB items

---

lib/shared/src/configuration/environment.ts
lib/shared/src/fetch.patch.ts
vscode/src/net/net.patch.ts

There were a few leftover undressed/reverted PR comments on https://github.com/sourcegraph/cody/pull/5883
Now we:
- No longer throw an exception on early agent access. The previous exception was only used during debugging of an import order issue.
- Fixed mentioned function comments / typos
- No functionality should have changed, existing tests pass.

Networking: Fix leftover PR comments

---

lib/shared/src/misc/observable.ts
lib/shared/src/misc/observableOperation.ts
vscode/CHANGELOG.md
vscode/src/repository/remote-urls-from-parent-dirs.test.ts
vscode/src/repository/remote-urls-from-parent-dirs.ts
vscode/src/repository/repo-name-resolver.test.ts
vscode/src/repository/repo-name-resolver.ts

- Ensures the repo name resolution is cached and we don't make unexpected API calls for already resolved remote URLs.
- This fix is critical for enterprise clients because the regression significantly increases the repo-name resolution latency, which is used by every enterprise client with Cody Context filters and is on the critical path for every autocomplete request. In my local tests, it adds ~500-600ms to every repo name resolution call.
- [Slack thread](https://sourcegraph.slack.com/archives/C07RUS5NPRQ/p1729595412265549?thread_ts=1729571680.266529&cid=C07RUS5NPRQ) with more technical details.
- Closes https://linear.app/sourcegraph/issue/CODY-4139/investigate-repo-name-resolution-latency-increase
CI with updated unit tests.
- Context Filters: fixed repo name resolution cache.

VS Code: fix repo name resolution cache

---

lib/shared/src/lexicalEditor/nodes.ts
vscode/src/prompts/prompt-hydration.ts
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/SubmitButton.tsx
vscode/webviews/chat/components/WelcomeMessage.tsx
vscode/webviews/components/promptsMigration/PromptsMigration.tsx
web/CHANGELOG.md
web/lib/agent/agent.client.ts
web/package.json
web/vite.config.ts

Just a few tweaks before the Cody Web 0.10.0 release, 
- Guard new experimental edit-like prompt execution from Cody Web
- Fix the client name for the production version of Cody Web
- Fix link in the prompt migration (unrelated to Cody Web) 
- Check that Cody Web demo works properly
- Check that Cody Web works in Sourcegraph Web build

Prepare cody web 0.10.0 release

---

.github/workflows/ci.yml

Hoping to unblock #5983 and #5982.
In https://github.com/sourcegraph/cody/pull/4923 we added the google auth action to the test-unit step but did not exclude the step if the PR comes from a fork (as we do with the other auth steps).
@akalia25 Do you see any issue with this tact? Should the setup-gcloud step get skipped too?
Runs in CI

fix(ci): disable google auth login if the PR is from a fork

---

lib/shared/src/chat/typewriter.ts

The Typewriter class, which provides the typing animation effect in chat responses, was not properly handling UTF-16 characters. This could lead to broken rendering of:
- Emoji characters 😀
- Characters outside the Basic Multilingual Plane
- Combined Unicode characters
- Other UTF-16 surrogate pairs
which resulted in a **blank screen** in the Cody chat.
Added proper UTF-16 character boundary handling by:
- Implementing a new `getNextValidSlicePoint` method that respects code point boundaries
- Using `Array.from()` to properly handle UTF-16 code points
- Ensuring text slicing occurs at valid character boundaries
Before fix:
https://github.com/user-attachments/assets/8f896b06-2546-4401-bf1d-44c1a5f1d101
- Shows broken emoji/special characters during typing animation
After fix: …

fix(Blank Screen): Improve UTF-16 character handling in Typewriter class

---

vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx

This PR solves a bug and implements a minor feature. Well call it bugfix or feature whatever. 
Right now if the intent of chat is set to anything search/chat/edit/insert and you create a new chat, the intent is not reset. 
why? because the react component is not re-rendered and its key={n=index}, obviously the index stays 0 when you create a new chat. 
So this PR:
1. resets the intent when the input is cleared.
2. resets the intent when the message is changes. 
- change the intent, clear the input, the intent should reset
- change the intent, submit the message, create a new chat, the intent should reset.

Reset editor intent on new chat and empty editor value

---

vscode/webviews/chat/cells/contextCell/ContextCell.tsx

context: https://sourcegraph.slack.com/archives/C05AGQYD528/p1729773000841009
Somehow `onKeyPress` causing an infinite loop of telemetry records. Also with the most recent changes the `context items opened` event is getting recorded even when the context menu is closed. 
This PR makes it so that the event is only getting recorded once. 
- Contact Piotr, even I don't know.

Remove onKeyPress on AccordionTrigger

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
lib/shared/src/misc/rpc/webviewAPI.ts
lib/shared/src/sourcegraph-api/graphql/client.ts
lib/shared/src/sourcegraph-api/graphql/queries.ts
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/prompts-migration.ts
vscode/src/prompts/prompts.ts
vscode/webviews/Chat.tsx
vscode/webviews/CodyPanel.tsx
vscode/webviews/chat/cells/messageCell/human/editor/toolbar/SubmitButton.tsx
vscode/webviews/chat/components/WelcomeMessage.tsx
vscode/webviews/components/promptList/ActionItem.module.css
vscode/webviews/components/promptList/ActionItem.tsx
vscode/webviews/components/promptList/PromptList.tsx
vscode/webviews/components/promptList/fixtures.ts
vscode/webviews/components/promptList/usePromptsQuery.tsx
vscode/webviews/components/promptSelectField/PromptSelectField.tsx
vscode/webviews/components/promptSelectField/fixtures.ts
vscode/webviews/prompts/PromptsTab.tsx

Adds support for promoted prompts, a feature that has been added in 5.9.0 
| | |
| ------- | ------- | 
| <img width="352" alt="Screenshot 2024-10-24 at 11 13 50" src="https://github.com/user-attachments/assets/e72fdf97-430f-44f4-96df-d980e22320cc"> | <img width="353" alt="Screenshot 2024-10-24 at 11 13 59" src="https://github.com/user-attachments/assets/84c8a606-8f22-4064-887d-5c4ba5d26473"> |
- Check that the welcome area prompts section shows only promoted prompts and out-of-the-box prompts/commands. 
- Check that order of this list is by most updated prompts
- Check that promoted prompts are always on top of the list in the prompts tab + ordered by most recent updated prompts
- Check that promoted prompts have promoted icon 
- Add support for promoted prompts. Now the welcome area …

Support promoted prompts

---

vscode/src/completions/providers/fireworks.ts

- Fixing the bug where the wrong feature flag was used for the A/B test. 
CI and manually tested the feature flag via setting the override value on my account on DotCom

Autocomplete: fix the fast-path feature flag

---

vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.module.css

This is an update that increases the default height of the chat input.
@vovakulikov @thenamankumar @jasonhawkharris Can you test this rigorously?
**Before** | **After**
-- | --
Manually tested locally.

fix: make default chat input taller

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/CodyAgentServer.kt
agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Window_DidChangeFocusParams.kt
agent/src/agent.ts
agent/src/vscode-shim.ts
pnpm-lock.yaml
vscode/src/jsonrpc/agent-protocol.ts

- Adds a window state notification to the agent so that JetBrains can tell us whether the window is focused. The characters logger uses this information to mark changes as done outside of the focused window. 
- Part of https://linear.app/sourcegraph/issue/CODY-2566/investigate-data-discrepancies-in-percent-of-code-written-by-cody
- Part of https://linear.app/sourcegraph/issue/DATA-66/add-percent-of-code-written-by-cody-metric
- Part of https://linear.app/sourcegraph/issue/CODY-4041/support-percent-code-written-in-vscode
- Part of https://linear.app/sourcegraph/issue/CODY-2877/characters-logger-does-not-work-in-jetbrains-and-vs-code
CI

Agent: add window state notification

---

lib/prompt-editor/src/PromptEditor.tsx
lib/prompt-editor/src/lexicalUtils.ts
vscode/webviews/chat/Transcript.tsx
vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx

This PR refactors the `PromptEditorRefAPI` and converts all callbacks to promises.
This PR also fixes the auto-execution of prompt templates which was broken due to `submitState` not being = `submittable`. 
- Try executing a Prompt which is set for `auto excute`. That should trigger mostly all the methods on the API.

Promisify PromptEditorRefAPI

---

vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/protocol.ts
vscode/webviews/App.story.tsx
vscode/webviews/chat/ChatMessageContent/ChatMessageContent.tsx

Currently all clients default to showing the Insert and New file buttons on code snippets in an assistant response, but only editors which support the `edit` capability (i.e. not Eclipse or VS) should show these buttons. This simply hides the action if the capability is not set to `enabled`.
Tested this build in Eclipse and saw that only the Copy button was retained, but on main, all three buttons were shown
Hide non-functional edit buttons in chat if client does not support the functionality.

fix(chat): Hide insert and new file buttons if there is no `edit` capability

---

vscode/webviews/components/promptList/PromptList.tsx

Fixes SRCH-1154
- Check that the initial prompt list has no selected items 
- There are still some confusing (once you mouse out from the list, it remembers the last selected/mouse over an item). It's part of the cure functionality of the `cmdk` library, so I leave it as is for now.

Don't select first prompt by default

---

vscode/webviews/components/promptList/PromptList.tsx

Reduces the padding of the container outside the prompt search to make it slightly more dense.
Tested manually.

Reduce padding of container around search input.

---

vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx

Changes the default placeholder text for the chat input.
| -- | -- |
| ![CleanShot 2024-10-28 at 11 45 44@2x](https://github.com/user-attachments/assets/7fcfb82a-43d4-4d1d-a356-a28ca348f63f) |  ![CleanShot 2024-10-28 at 11 44 56@2x](https://github.com/user-attachments/assets/507405da-82c8-4247-8648-e618847cc8d5) |
Manually tested, locally.

fix: Change chat input placeholder text

---

lib/shared/src/token/counter.ts

Tokenisation of huge files using tiktoken is very costly, and we could save a lot of CPU by simplifying it.
Amount of tokens will always be greater than amount of words, so if amount of words exceeds `EXTENDED_USER_CONTEXT_TOKEN_BUDGET` we can just return it instead.
For determining if file can be used as user context it will remain equally correct.
For other purposes (if any) accuracy may suffer.
1. Build with the JetBrains plugin.
2. Open big file (few MB of text)
3. Select a text fragment and start moving mouse cursor while holding LMB pressed (so changing the selection).
Without this changes CPU usage jumps to 100% and stays that way for a minute.
With those changes it should drop back to single digit numbers in 2-3 seconds.

Use simplified token counting method in case of the big files

---

lib/shared/src/misc/rpc/webviewAPI.ts
vscode/package.json
vscode/src/chat/chat-view/ChatController.ts
vscode/src/chat/chat-view/ChatsController.ts
vscode/webviews/AppWrapperForTest.tsx
vscode/webviews/Chat.tsx
vscode/webviews/CodyPanel.tsx
vscode/webviews/chat/components/WelcomeFooter.module.css
vscode/webviews/chat/components/WelcomeMessage.module.css
vscode/webviews/chat/components/WelcomeMessage.test.tsx
vscode/webviews/chat/components/WelcomeMessage.tsx

Fixes SRCH-1133
This PR adds a shortcut for the "Recently used" button on the welcome screen, a few limitations 
- This action works only if Cody's side panel is open 
- And only when the Cody Chat tab opens (switching tab isn't supported at the moment)
- It's supported only in VSCode (Cody Web requires a completely different approach to shortcuts)
- Check that cmd+R opens recently used prompts popover

Add shortcut for recently used prompts

---

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ExtensionConfiguration.kt
agent/src/AgentWorkspaceConfiguration.test.ts
agent/src/AgentWorkspaceConfiguration.ts
vscode/src/jsonrpc/agent-protocol.ts

This PR adds `customConfigurationJson` field which allow passing json config.
This allow us to support obtaining config objects using dotted pattern.
For example, given the config bellow:
```json
{
"http.systemCertificates": true,
"http.experimental.systemCertificatesV2": true
}
```
Before it was only possible to get `http.systemCertificates` and `http.experimental.systemCertificatesV2` keys.
After this changes it is also possible to get `http` which would return:
```json
{
"systemCertificates": true,
"experimental.systemCertificatesV2": true
}
```
Or 'http.experimental' which would return:
```json
{
"systemCertificatesV2": true
}
```
**Additionally** it will support writing json config files utilising full json syntax, e.g.:
```json
{
"cody.debug": {
"verbose": true
}
}
```
Add the …

Add new custom configuration field which supports dotted names

---

lib/shared/src/experimentation/FeatureFlagProvider.ts
vscode/src/completions/providers/fireworks.ts
vscode/src/completions/providers/shared/get-experiment-model.ts

Adding the code llama model for the A/B test.
Backend PR: https://github.com/sourcegraph/sourcegraph/pull/1371
Manual testing by:
1. Overriding userid in `cody-autocomplete-model-experiment-variant-1` feature flag.
2. Checking the logging prompt to make sure we trigger code llama with correct infill prompt.
3. Check model response.

add code llama model for the a/b test

---

agent/src/AgentWorkspaceConfiguration.test.ts
agent/src/AgentWorkspaceConfiguration.ts
vscode/src/configuration.test.ts
vscode/src/configuration.ts
vscode/src/jsonrpc/agent-protocol.ts

I added support and tests for multiple nested objects like this:
```json
"foo.bar": {
"baz.qux": true,
"baz": {
"d1.d2": {
"v": 1
}
}
}
```
I also fixed few other minor remarks from previous review.
Automatic tests for new cases were added.

Fix support for merging multiple nested objects

---

vscode/src/main.ts
vscode/src/non-stop/FixupController.ts
vscode/src/services/CharactersLogger.test.ts
vscode/src/services/CharactersLogger.ts
vscode/src/services/telemetry-v2.ts
vscode/src/services/utils/codeblock-action-tracker.ts

- Adds new fields to the `cody.characters:flush` analytics event. This way, we can identify all code generation events coming from chat and always include them once in our PCW calculation.
- `cody_chat` — to identify document change events originating from `insert at cursor` and `copy-paste` chat actions.
- `cody_chat_inserted`
- `cody_chat_deleted`
- Part of https://linear.app/sourcegraph/issue/CODY-4197/add-metadata-to-cody-code-gen-analytics-events-to-prevent-double. See more context and related discussion there.
- Closes https://linear.app/sourcegraph/issue/CODY-4200/add-char-counts-metadata-to-chat-events
CI and updated unit tests.

VS Code: add characters logger metadata to chat code-gen events

---

vscode/webviews/components/promptList/PromptList.tsx

Fixes SRCH-1303
This PR hides empty zero state on the welcome area since we no longer show there all prompts but just promoted on and if you don't have any prompts we shouldn't show any prompts empty states there. 
- Check that you have no zero/empty prompts state on the welcome area if you don't have any prompts (promoted prompts)

Fix Prompts welcome screen initial state

---

vscode/test/e2e/uninstall.test.ts

The uninstall test could sometimes timeout in CI as it was quite heavy. This increases the timeout for that test to 1 minute.
Update to E2E test

fix(ci): Increase test timeout for uninstall test
