vscode/src/completions/completion-provider-config.ts, vscode/src/completions/providers/fireworks.ts
- We [finished](https://sourcegraph.slack.com/archives/C0729T2PBV2/p1730167483283679?thread_ts=1728366545.242119&cid=C0729T2PBV2) the fast-path A/B test, so this PR removes all related logic.
- Closes https://linear.app/sourcegraph/issue/CODY-4037/ab-test-fast-path-to-get-the-up-to-date-impact-stats
CI
=> Autocomplete: cleanup the fast-path a/b test

vscode/src/chat/context/chatContext.ts
Resolves: https://sourcegraph.slack.com/archives/C07NNEEAU4B/p1730256382790879?thread_ts=1729002871.765829&cid=C07NNEEAU4B
OpenCtx providers can define `mentions: { autoInclude: true }` to get called for retrieving initial context items. This was implemented to support Bridgewater's feature request for Pinned Context. 
However, the provider is not getting called for files not inside a git repo with the remote set. This is because the `codebase` is not recognized, and we don't call the provider in that case. We recognize the codebase based on the current working directory and the git remote set.
This PR solves it by calling the provider even when the codebase is not resolved. 
Demo: https://www.loom.com/share/1c6724808f164b798f578d7c47481fdf?sid=00219b3a-8691-4d63-8978-d31f50ce6328
Follow …
=> Fix OpenCtx include initial context integeration.

agent/src/AgentWorkspaceConfiguration.test.ts, agent/src/AgentWorkspaceConfiguration.ts
VSCode's configuration setting parsing will split dotted names where they appear at the top level. Retrieving will walk nested property names concatenated by a dot ...but not dotted property names.
See the unit tests for details.
```
pnpm -C agent test
```
=> Change nested configuration object handling to match VSCode behavior.

agent/src/vscode-shim.ts, vscode/webviews/AuthPage.tsx
CLOSE https://linear.app/sourcegraph/issue/CODY-4219
This change improves the conditional rendering logic in the `AuthPage` component. It removes the `isNonVSCodeIDE` and `isCodyWebUI` variables and simplifies the rendering logic based on the `codyIDE` value.
This change is to fix a regression caused by the logic we use for setting "isCodyWebUI" that is affecting all the non-VS Code clients as `isCodyWebUI` is now returning true for all clients. We set the uiKindIsWeb here: https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/chat/chat-view/ChatController.ts?L511
But Agent sets uiKind to Web for ALL clients: https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/agent/src/vscode-shim.ts?L1069
The key changes are:
- update uiKind to Desktop by default
- Removed the …
=> Auth: UI conditional rendering logic

vscode/CHANGELOG.md, vscode/package.json
Release v1.40.1 go!!!
Made a slight mistake, I directly pushed to the `vscode-1.40.x` branch instead of creating a PR. But this version is to cherry pick #6047 into `v1.40.0` to address login rendering on non VS Code clients
see 1.40.x branch for details - https://github.com/sourcegraph/cody/commits/vscode-v1.40.x
N/A
=> VS Code: Release v1.40.1

.github/workflows/vscode-insiders-release.yml
Updating insider release cron schedule to MWF @ 1500 UTC to prep builds for QA. 
see https://sourcegraph.slack.com/archives/C05AGQYD528/p1730416040305789 for more details
N/A
=> update insider cron schedule to MWF @ 1500 UTC

lib/prompt-editor/src/index.ts, lib/prompt-editor/src/mentions/mentionMenu/useMentionMenuData.test.tsx, lib/prompt-editor/src/mentions/mentionMenu/useMentionMenuData.ts, lib/prompt-editor/src/useExtensionAPI.tsx, lib/prompt-editor/src/useInitialContext.ts, lib/shared/src/codebase-context/messages.ts, lib/shared/src/experimentation/FeatureFlagProvider.ts, lib/shared/src/index.ts, lib/shared/src/misc/rpc/webviewAPI.ts, vscode/package.json, vscode/src/chat/chat-view/ChatController.test.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/chat-view/ChatsController.ts, vscode/src/chat/initialContext.ts, vscode/test/e2e/uninstall.test.ts, vscode/webviews/App.tsx, vscode/webviews/AppWrapperForTest.tsx, vscode/webviews/chat/Transcript.tsx, vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.story.tsx, vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx, vscode/webviews/components/StateDebugOverlay.tsx, web/lib/components/CodyWebChat.tsx
Removes the repo chip from the default chat context:
<table>
<tr>
<th>Before</th><th>After</th>
</tr
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
To make the repo context still discoverable, adds a `Rerun with repository context` button when no repo chips are present:
https://github.com/user-attachments/assets/4f8f1763-c229-4993-b198-15d41100fe32
This is behind a feature flag `no-default-repo-chip`, without which there should be no behavior change.
Test against S2 (feature flag is turned on):
- Ask a chat without repo context
- Observe button appear
Test against sourcegraph.com: there should be no change in behavior.
=> Remove repo chip from default context

package.json, vscode/src/completions/get-inline-completions-tests/hot-streak.test.ts
- Deflakes hot-streak unit tests by ensuring we reset timers and mocks after every test.
- Closes of https://linear.app/sourcegraph/issue/CODY-4217/completion-hot-streak-tests-are-flaky
[Ran](https://github.com/sourcegraph/cody/pull/6040/commits/f57d96002680e24cb2bafb56e803997b6cdfe2fd) problematic unit tests 1000 times in CI without failures.
=> Autocomplete: deflake hot-streak tests

lib/shared/src/configuration.ts, lib/shared/src/experimentation/FeatureFlagProvider.ts, vscode/CHANGELOG.md, vscode/package.json, vscode/src/completions/completion-provider-config.ts, vscode/src/completions/get-inline-completions.ts, vscode/src/completions/inline-completion-item-provider-e2e.test.ts, vscode/src/completions/inline-completion-item-provider.ts, vscode/src/configuration.test.ts, vscode/src/configuration.ts, vscode/src/testutils/mocks.ts
- Enables completions preloading on cursor movement by default based on [the A/B test results](https://sourcegraph.slack.com/archives/C0729T2PBV2/p1730438575143299?thread_ts=1723609708.830079&cid=C0729T2PBV2).
- Closes https://linear.app/sourcegraph/issue/CODY-3300/enable-the-preload-150-functionality-for-all-users-and-start-a-new
CI and manual testing: 
1. Enable autocomplete: `"cody.autocomplete.enabled": true`.
2. Open a new document.
3. Move the cursor to the line before the following empty line and wait a second.
4. Place the cursor at the beginning of the following empty line.
5. Observe that the completion appears instantly because it was preloaded while the cursor was on the previous line.
- Autocomplete: Enabled completion completions preloading on cursor movement.
=> Autocomplete: enable completions preloading on cursor movement

agent/src/vscode-shim.test.ts, agent/src/vscode-shim.ts
`getConfiguration` was working incorrectly when scope was provided.
Currently agent ignores scopes, but should respect configuration sections.
In the buggy case if scope was give, `getConfiguration` was always returning top level scope ignoring section.
Unittests are added. Test scenario with openctx providers:
1. Add the following configuration in the cody jetbrains settings:
```
"cody.experimental.noodle": true,
"openctx": {
"providers": {
"https://gist.githubusercontent.com/thenamankumar/3708f084fb2abd57adafe7f14620bdf7/raw/e7c7059cb5b04f6feead002e7b3a90c5b1a4bb96/provider.js": true
},
"enable": true
}
```
2. Restart IDE
3. You should see new @ provider
=> Fix bugs in workspace::getConfiguration vscode shim

agent/src/vscode-shim.test.ts, agent/src/vscode-shim.ts, vscode/package.json
Cherry pick https://github.com/sourcegraph/cody/pull/6058 into v1.40.2 patch release
N/A
=> VS Code: Release v1.40.2

vscode/CHANGELOG.md, vscode/package.json, vscode/test/e2e/chat-keyboard-shortcuts.test.ts
Previously, using the `alt+L` shortcut would appear to double-add the same snippet of context, because that snippet will have been already been added to the default initial context of the chat input. The `alt+L` shortcut to add a selection to context also conflicts with the `alt+L` shortcut that toggles the cursor back and forth between the sidebar and the editor.
This patch updates the shortcuts to be as follows:
- alt+L: between chat and editor (this is unchanged)
- shift+alt+L (previously alt+L): add selection as context: 
- shift+ctrl+L (previously shift+alt+L): new chat
Test the shortcuts locally.
=> prevent double-adding selected context

vscode/src/chat/chat-view/ChatController.ts
Tiny change to streamline the context error message.
Relates to [SPLF-667](https://linear.app/sourcegraph/issue/SPLF-667)
N/A
=> Context: make error message more concise

vscode/src/chat/chat-view/prompts-migration.ts, vscode/src/context/openctx.ts, vscode/webviews/components/promptList/PromptList.tsx
Closes SRCH-1278
This PR simply makes prompt migration wizard to migrate only local commands that you have in vs code settings. Repository-level commands will be migrated via instance-level wizard (see https://github.com/sourcegraph/sourcegraph/pull/1449)
- Open VSCode while you have some custom local commands 
- Check that you can see the migration wizard on the welcome screen or on the prompts tab
- Run the wizard and check that this created prompts from your local commands in prompts library
=> Run prompts migration only over local user commands

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/WorkspaceEditEntryMetadata.kt, vscode/src/completions/analytics-logger.test.ts, vscode/src/completions/analytics-logger.ts, vscode/src/completions/get-inline-completions-tests/analytics.test.ts, vscode/src/completions/inline-completion-item-provider.ts, vscode/src/services/CharactersLogger.ts
- Enhances `cody.completion:accepted` events by adding boolean fields to improve PCW tracking and avoid double-counting Cody's contributions. The updated logic now leverages the `CharactersLogger` logic for classifying document changes. 
- For example, when the accepted completion produces a change partially outside of visible ranges, it is flagged by both the autocomplete logic and `CharactersLogger` telemetry. This ensures that partially-visible changes, previously excluded due to non-manual nature, can now be accurately counted in PCW calculations because they are flagged accordingly.
- Part of [CODY-4197: Add metadata to Cody code-gen analytics events to prevent double-counting](https://linear.app/sourcegraph/issue/CODY-4197/add-metadata-to-cody-code-gen-analytics-events-to-prevent-dou …
=> Autocomplete: add characters logger metadata to `accepted` events

vscode/CHANGELOG.md, vscode/package.json, vscode/src/chat/chat-view/ChatsController.ts, vscode/src/non-stop/FixupTask.ts, vscode/src/services/CharactersLogger.ts, vscode/test/e2e/__snapshots__/chat-messages.test.ts/chat-assistant-response-code-buttons-1.txt, vscode/test/e2e/__snapshots__/command-edit.test.ts/edit-fixup-task-1.txt, vscode/test/e2e/chat-messages.test.ts, vscode/test/e2e/helpers.ts
- Adds E2E tests for telemetry events for code buttons in chat. Asserts that changes they produce in a document are correctly categorized as `cody_chat`.
- Adds a new "[Internal] Log character logger counters" for characters logger debugging.
- Closes https://linear.app/sourcegraph/issue/CODY-4233/implement-e2e-vs-code-tests-for-pcw-events-from-chat
- CI with the updated E2E test.
- Open command palette in VS Code and run "[Internal] Log character logger counters". It should output the character logger counters in the Cody output channel. Enable verbose debugging by adding "'cody.debug.verbose': true" to your VS Code settings.
=> Chat: E2E tests for chat PCW events.

lib/shared/src/experimentation/FeatureFlagProvider.ts, vscode/src/completions/context/retrievers/jaccard-similarity/history.ts, vscode/src/completions/context/retrievers/jaccard-similarity/jaccard-similarity-retriever.ts, vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-retriever.ts, vscode/src/completions/context/retrievers/recent-user-actions/recent-view-port.ts, vscode/src/completions/context/utils.test.ts, vscode/src/completions/context/utils.ts
- Removes the extended language pool option based on A/B test results. We hypothesized that including CSS family files as context for JSX family documents would increase CAR by suggesting relevant class names more frequently. However, the metrics we collected showed this wasn't the case.
CI
=> Autocomplete: remove the extended language pool option

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Constants.kt, agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/DebugMessage.kt, agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/DebugMessageLogLevel.kt, agent/src/agent.ts, agent/src/vscode-shim.ts, vscode/src/jsonrpc/agent-protocol.ts
Fixes logging capability in agent.
Previously messages logged to output channel were visible only if added using `append` or `appendLine`.
Now `trace` / `debug` / `info` / `warn` / `error` functions are also logged properly.
As in https://github.com/sourcegraph/jetbrains/pull/2583
=> Improve Cody logging agent protocol

vscode/src/chat/agentic/CodyTool.ts, vscode/src/chat/agentic/DeepCody.ts
This change removes the `TOOLCONTEXT` context item from the `DeepCodyAgent` after the review process is complete. The `TOOLCONTEXT` context item is only used during the review process and should not be included in the final context.
After: the search history (which should only be used during the review process) should not showing in the UI
Before: the search history and chat memory are showing in the UI
=> Deep Cody: remove TOOL context item after review

.github/workflows/vscode-insiders-release.yml, vscode/scripts/release.ts
This makes several changes so we can do manually triggered insiders builds from a release branch instead of nightly on `main`.
No changes to stable release builds in this PR.
This does a dry run of the insiders build and verifies that the version tag is written to outputs:
```
$ CODY_RELEASE_DRY_RUN=true CODY_RELEASE_TYPE=insiders GITHUB_OUTPUT=/tmp/output.txt pnpm \
-C vscode run release
$ cat /tmp/output.txt
version_tag=vscode-insiders-v1.41.1730969154
```
Testing the workflow itself we have to upload and trigger the workflow, here's a fork with a dry run:
https://github.com/sourcegraph/cody/actions/runs/11719764387
- VSCode Insiders builds are now manually triggered, instead of nightly.
- VSCode Insiders builds can be triggered on branches. We intend to produce these builds from …
=> chore/build: VSCode Insiders builds are manually triggered and automatically tagged

vscode/src/chat/agentic/CodyTool.ts, vscode/src/chat/agentic/DeepCody.ts, vscode/src/chat/agentic/prompts.ts, vscode/src/chat/chat-view/ContextRetriever.ts
This change adds a `skipQueryRewrite` option to the `ContextRetriever.retrieveContext` method, which is used when retrieving context for the Search tool. 
This allows the Deep Cody to bypass the query rewriting step that makes an extra LLM request when using the search tool. The reason behind this is because Deep Cody has already return a proper search query that doesn't need rewritten into keyword.
The `ContextRetriever._retrieveContext` method has been updated to handle the `skipQueryRewrite` option, and the `SearchTool` class now passes `true` for this option when calling `retrieveContext`.
Minor prompt improvement (formatting and wording).
I've also notice some response quality regression after switching to use 3.5 Haiku for the reviewing step, where Haiku was not able to fetch the …
=> Deep Cody: skip query rewrite for search tool

agent/src/AgentWorkspaceConfiguration.test.ts, agent/src/AgentWorkspaceConfiguration.ts
Unit tests added.
Also before this fix problem was visible e.g. in duplicated shortcut tooltips next to the lens actions (due to property `cody.advanced.agent.running` being incorrectly overwritten).
After this fix problem should disappear.
=> Fix issue with merging configs

vscode/scripts/github-changelog.ts, vscode/src/chat/protocol.ts, vscode/src/release.test.ts, vscode/src/release.ts
- Changed VS Code changelog links to `./vscode/changelod.md` to decouple our releases from marketing blog posts. We want all in-product messaging to point to our GitHub changelog, as we discussed with @kalanchan.
- We plan to move the changelog to the root of the repo and implement changes necessary to maintain one changelog for multiple IDEs in a follow up.
CI
=> VS Code: point releases to `./vscode/changelog.md`

vscode/src/chat/agentic/CodyTool.ts, vscode/src/chat/agentic/DeepCody.ts, vscode/src/chat/agentic/prompts.ts, vscode/src/chat/chat-view/ContextRetriever.ts
This PR backports the following commits from `main` branch to `vscode-v1.42.x`:
- 45b9ff21
- bc8b14e1
These commits contain fixes for Deep Cody
merged to main.
=> [Backport] Cherry-pick fixes from main to vscode-v1.42.x

.github/workflows/vscode-insiders-release.yml, vscode/scripts/release.ts
cherry pick #6083 to tag insider releases 
…tically tagged (#6083)
This makes several changes so we can do manually triggered insiders builds from a release branch instead of nightly on `main`.
No changes to stable release builds in this PR.
This does a dry run of the insiders build and verifies that the version tag is written to outputs:
```
$ CODY_RELEASE_DRY_RUN=true CODY_RELEASE_TYPE=insiders GITHUB_OUTPUT=/tmp/output.txt pnpm \
-C vscode run release
$ cat /tmp/output.txt
version_tag=vscode-insiders-v1.41.1730969154
```
Testing the workflow itself we have to upload and trigger the workflow, here's a fork with a dry run:
https://github.com/sourcegraph/cody/actions/runs/11719764387
- VSCode Insiders builds are now manually triggered, instead of nightly.
- VSCode Insiders builds can be …
=> cherry pick 6083

agent/src/AgentWorkspaceConfiguration.test.ts, agent/src/AgentWorkspaceConfiguration.ts
cherry pick #6084 that fixes config pickup on JetBrains
Unit tests added.
Also before this fix problem was visible e.g. in duplicated shortcut tooltips next to the lens actions (due to property `cody.advanced.agent.running` being incorrectly overwritten). After this fix problem should disappear.
=> cherry pick 6084

agent/src/edit.test.ts
- Disabled the flaky test based on CI runs [here](https://github.com/sourcegraph/cody/actions/runs/11726530828/job/32666794309?pr=5956).
- Linear issue to fix and re-enable this test.
CI
=> Agent: disable the flaky edit test

vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-retriever.test.ts, vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-retriever.ts, vscode/src/supercompletions/supercompletion-provider.ts
1. Recent edits context source outputs wrong diffs sometimes. The behaviour is not reproducible always, but can be seen from the output logs. Adding one such example in below:
2. On further inspection, it turns out that sometimes when events are received `private onDidChangeTextDocument` the text document could have changed, and reading `document.getText()` returns change with the updated text (i.e. including the change we received). Although this behaviour is not always reproducible. So, this PR reads the text document during the constructor call or when the document is first opened.
Manual inspection
=> fix recent edits context source

lib/prompt-editor/src/PromptEditor.tsx, vscode/webviews/CodyPanel.tsx, vscode/webviews/chat/components/WelcomeMessage.tsx, vscode/webviews/prompts/PromptsTab.tsx, web/CHANGELOG.md, web/lib/components/CodyWebChat.tsx, web/lib/index.ts, web/lib/types.ts, web/package.json
Part of https://linear.app/sourcegraph/issue/SRCH-1290/implement-new-prompt-library-ui
In the new Prompts Library, we're going to have a Cody Web demo staging, with which you can run your prompt; this means that we have to have some API to trigger prompts in the Cody Web UI from the Cody Web consumer. 
This PR adds this "external API" functionality by exposing the External API object 
- No Changes in the actual Cody shared webview
=> Cody Web: Add support running prompts from consumer

vscode/src/non-stop/FixupController.ts, vscode/src/non-stop/FixupTask.ts, vscode/test/e2e/__snapshots__/command-edit.test.ts/edit-fixup-task-1.txt, vscode/test/e2e/command-edit.test.ts, vscode/test/e2e/helpers.ts
- Adds latency, document language, original selection char count, and line count to the Edit command `cody.fixup.apply:succeeded` analytics events. This would allow us to conduct A/B tests focused on latency improvements.
- Closes [CODY-4301: Collect E2E latency data for the Edit commands](https://linear.app/sourcegraph/issue/CODY-4301/collect-e2e-latency-data-for-the-edit-commands)
CI + updated E2E test for the Edit command. You can see newly added analytics fields in the updated test snapshot.
- Edit: added latency and document language to the analytics event metadata.
=> Edit: collect more analytics data

agent/src/cli/command-bench/strategy-chat-context-types.ts, agent/src/cli/command-bench/strategy-chat-context.ts
We now fail immediately in case there are malformed rows in the input CSV used for context benchmarking.
Run benchmark with current cody-leaderboard/golden_queries.csv and observe failure.
=> Fail hard on errors in input context bench CSV, remove unused column

vscode/package.json, vscode/src/autoedits/prompt-utils.test.ts, vscode/src/autoedits/renderer-testing-2.ts, vscode/src/autoedits/renderer-testing.ts, vscode/src/autoedits/renderer.ts, vscode/src/main.ts
Adds a `ctrl+alt+enter` shortcut when `cody.experimental.autoedits-renderer-testing` is `true` to render the proposed edit using the format specified here: https://github.com/sourcegraph/cody-chat-eval/pull/72
The advantage of this format to the old one is that the proposed edit can be specified *in situ*, so we can better see how it would be rendered in a real-world file.
Only affects experimental test features behind the `cody.experimental.autoedits-renderer-testing` setting.
=> Add a command for testing auto-edit examples

vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/renderer.ts, vscode/src/main.ts
The current version of `auto-edits` only trigger when user types something in the editor, and not on simple cursor movements. The PR adds the functionality to trigger the `auto-edits` on every cursor movement.
Since the volume of such events can be very high, following configuration works better when I experimented with the feature offline:
1. Add a debounce of `150ms` on the cursor movements.
2. Using both inline completion provider and selection change had the issue where it would trigger twice (since as user types, selection also change). So, removed the inline completion provider. 
3. Since the user can move cursor to view the current decoration, and triggering the feature in such case would lead to discarding the previous suggestion, we don't trigger if some decoration is already …
=> Trigger autoedit on the cursor movements

lib/shared/src/experimentation/FeatureFlagProvider.ts, lib/shared/src/models/modelsService.test.ts, lib/shared/src/models/modelsService.ts, lib/shared/src/models/sync.test.ts, vscode/src/edit/manager.ts, vscode/src/edit/utils/edit-intent.ts, vscode/src/edit/utils/edit-models.ts, vscode/src/main.ts, vscode/src/non-stop/FixupController.ts
- Prepares for A/B testing gpt-4o-mini as a default model for the Edit commands. 
- Enrolled users' preferences will be switched to gpt-4o-mini automatically. They will be able to switch the model back as they see fit.
- The `cody-edit-default-to-gpt-4o-mini` feature flag will be used to start the experiment.
- Support for [the Predicted Outputs feature](https://platform.openai.com/docs/guides/predicted-outputs) will be added in a follow up.
- Related work:
- https://github.com/sourcegraph/cody/pull/6095
- https://github.com/sourcegraph/sourcegraph/pull/1591
- Part of [CODY-4306: A/B test OpenAI Predicted Outputs optimization with the Edit command](https://linear.app/sourcegraph/issue/CODY-4306/ab-test-openai-predicted-outputs-optimization-with-the-edit-command)
- Closes [CODY-4309: Make …
=> Edit: prep for the gpt-4o-mini edit a/b test

lib/shared/src/sourcegraph-api/completions/types.ts, vscode/src/edit/provider.ts
- Enables [the Predicted Outputs feature](https://platform.openai.com/docs/guides/predicted-outputs) for gpt-4o models used with Edit commands.
- Related work:
- https://github.com/sourcegraph/cody/pull/6095
- https://github.com/sourcegraph/sourcegraph/pull/1591
- https://github.com/sourcegraph/cody/pull/6110
- Part of [CODY-4306: A/B test OpenAI Predicted Outputs optimization with the Edit command](https://linear.app/sourcegraph/issue/CODY-4306/ab-test-openai-predicted-outputs-optimization-with-the-edit-command)
- Closes [CODY-4321: Add the predicted outputs feature support to the clients](https://linear.app/sourcegraph/issue/CODY-4321/add-the-predicted-outputs-feature-support-to-the-clients)
CI and manual testing:
1. Start the local Sourcegraph instance from [this …
=> feat(edit): enable predicted outputs for gpt-4o models

vscode/src/autoedits/renderer.ts
Fixes ghost text rendering for autoedits on the same line. [Linear Issue](https://linear.app/sourcegraph/issue/CODY-4320/fix-ui-rendering-on-the-same-line-when-other-extension-show-their-own)
**Before:**
**After:**
1. Turn on the auto-edit renderer tester: `"cody.experimental.autoedits-renderer-testing": true,`
2. Use [this file](https://github.com/sourcegraph/cody-chat-eval/blob/main/code-matching-eval/edits_experiments/examples/renderer-testing-examples/rendering-issue-inline-ghost-text-autoedits.go) to repro the issue.
3. Trigger `Ctrl+Option+Enter` on [line](https://github.com/sourcegraph/cody-chat-eval/blob/main/code-matching-eval/edits_experiments/examples/renderer-testing-examples/rendering-issue-inline-ghost-text-autoedits.go#L47C3-L47C20)
4. Without the fix, it will show …
=> fix rendering issue on the same line for ghost text

lib/shared/src/common/languages.ts, pnpm-lock.yaml, vscode/package.json
1. Ask Cody to create a sample Csharp program. Check if syntax highlight loads
2. Run ANALYZE=TRUE pnpm build within web folder
Check that only one copy of highlight.js is bundled
Cody Chat: fixed missing syntax highlighting of CSharp files and load only one copy of highlight.js in the WebView build
=> Cody Chat: fixed missing syntax highlighting of CSharp files and load only one copy of highlight.js in the WebView build

vscode/CHANGELOG.md, vscode/package.json
VS Code release v1.42.0!! gogo!!!
Also updating the changelog messaging to improve release communications
N/A
=> VS Code: Release v1.42.0

vscode/package.json
Slight re-wording of the description to solve the problem with it cutting off due to exceeding the character limits by 6 characters
Changed one instance of "and" to an ampersand (&), removed "to VS Code" (wasn't really needed as this only shows within the VSCode Marketplace, and wouldn't be any benefit to SEO)
Changed "latest" in the LLMs selection, to "best" - this gives a better "feeling" than "latest" as the latest LLM could be a tiny 1b parameter model which means nothing for Cody.
=> Fix for VSCode Marketplace description getting cut-off

vscode/src/autoedits/adapters/cody-gateway.ts, vscode/src/autoedits/adapters/fireworks.ts, vscode/src/autoedits/adapters/openai.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/prompt-provider.ts
Enable speculative decoding for the auto-edits deployment. The PR passes the existing code we rewrite in the file as the speculative string. Since only certain parts of the code that we rewrite change, most of the tokens are present in the speculative string that we pass.
Backend PR: https://github.com/sourcegraph/sourcegraph/pull/1673 
Monitor the `Fireworks-Speculation-Matched-Tokens` header from fireworks. This shows the number of tokens matched, which is linearly related to prefix match between the code that we rewrite and response.
- autoedits: Enable speculative decoding.
=> autoedit: add speculative decoding

.github/workflows/backport.yml
@kalan was debugging the Backport action here, and found a bug. 
We previously always attached the review to the release team, but that team is not a collaborator here in the Cody repo.
We could add them as collaborators, but that doesn't give us any benefit. 
So instead I've [changed the way the backport GHA works](https://github.com/sourcegraph/backport/pull/14), and made the team_reviews a parameter. Here we override it to set no team. This means that only the original author and / or merger of the PR will be tagged in the new backport PR. 
Add the label to this PR, and it should create a new PR that backports this one, without errors
N/A
=> fix(release): Update backport action to override team_reviews

vscode/webviews/themes/jetbrains.css
1. Run this branch with https://github.com/sourcegraph/jetbrains/pull/2654 (using CODY_DIR and `:customRunIde`)
2. In IntelliJ open `Settings > Appearance`
3. Tick `Use custom font` and change font size
4. Apply changes
5. You should notice that both editor and webview font size changed
=> Use font size variable providd by JetBrains in webview

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ParametersParams.kt, agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/TelemetryEvent.kt, vscode/src/jsonrpc/agent-protocol.ts
This change is required for the ongoing migration to the generated API in the JetBrains client.
Related PR: https://github.com/sourcegraph/jetbrains/pull/2661
Some more advanced types are skipped to simplify the code gen. We used internal types too casually. We should be more precise about the protocol. 
Related thread: https://sourcegraph.slack.com/archives/C05AGQYD528/p1728049089597009
Verified with JB. Telemetry goes through the API.
=> Simplify protocol's TelemetryEvent

lib/prompt-editor/src/PromptEditor.tsx, lib/shared/src/configuration/clientCapabilities.ts, vscode/webviews/chat/components/WelcomeMessage.tsx, vscode/webviews/components/promptList/ActionItem.module.css, vscode/webviews/components/promptList/ActionItem.tsx, vscode/webviews/components/promptList/PromptList.tsx, web/CHANGELOG.md, web/lib/agent/agent.client.ts, web/lib/components/CodyWebChat.tsx, web/lib/components/use-cody-agent.ts, web/package.json
This PR does a few improvements for the prompts library in Cody Web
- First of all, it fixes recent regression in openctx (apparently internally openctx library tries to find vs code setting file and with an empty Cody Web Workspace URI it fails in runtime and therefore doesn't produce any openctx providers such as remote files or repositories) 
- It fixes prompts editor placeholder appearance (we no longer add whitespaces to the field unconditionally)
- Disables non-runnable in Cody Web prompts (insert or inline commands) before we render them and these actions did nothing 
- Check that you can use openctx mentions in Cody Web (with Cody Web linked in sg, check ./web contribution doc to see how to link Cody Web and sg instance)
- Check that you can't click non-chat prompts in Cody Web …
=> Cody Web: Polish cody web Prompts

vscode/src/edit/provider.ts
I've noticed that on the main when you run the inline prompt, the chat doesn't have any different messages from the actual inline edit task. Apparently, it looks like there is a race condition between task execution and logic that populates chat with diffs. The main problem is that at the moment when we run populate with chat messages, `task.diff` has an undefined value. 
This PR tries to fix this problem by awaiting the task finish state.
- Create inline prompt (s2 has `prompt-creation-v2` flag enabled already)
- Try to run it 
- You should see that chat has non-empty chat messages with actual task diffs
=> Fix inline-edit prompts chat building

lib/prompt-editor/src/useInitialContext.ts, vscode/test/e2e/chat-context.test.ts, vscode/test/e2e/chat-input.test.ts, vscode/test/e2e/chat-messages.test.ts, vscode/webviews/chat/Transcript.story.tsx, vscode/webviews/chat/Transcript.test.tsx, vscode/webviews/chat/Transcript.tsx, vscode/webviews/chat/cells/contextCell/ContextCell.module.css, vscode/webviews/chat/cells/contextCell/ContextCell.story.tsx, vscode/webviews/chat/cells/contextCell/ContextCell.tsx
On a context-less chat request, we show a "none fetched" indicator in the ContextCell, along with a "Resend with current repository context" button:
Clicking "Resend with current repository context" causes the repository chip to be added and the request resent:
The "Resend with current repository context" also appears when context is at-mentioned but there is no repo chip:
This PR also removes the "Edit context" button (which previously caused the fetched context items to be moved to the input), because this was broken and not actually fetching context.
Test in local dev the scenarios in the screenshots above.
=> Chat: context cell improvements

vscode/src/autoedits/renderer.test.ts, vscode/src/autoedits/renderer.ts
This makes the following changes to how inline edit proposals are rendered:
1. Leading block whitespace in an added-line block is stripped, so that the edit doesn't render far to the right.
2. A dotted green insert indicator has been added to indicate where an added-line block will be inserted
3. Added-line blocks are now placed in a green box, rather than simply highlighting the lines in green
Before:
After:
Another example:
Test against the examples in sourcegraph/cody-chat-eval. This feature is still behind a feature flag.
=> Better rendering for auto edits

vscode/CHANGELOG.md, vscode/package.json
- Removed `Shift+Ctrl+L` (previously created a new chat) due to conflict with Windows default shortcut.
- Updated `Shift+Alt+L` to create a new chat when the focus is not in the editor. When the focus is in the editor, the behavior remains unchanged (the current selection is added to the chat context).
Test both shortcuts locally
=> remove ctrl+shift+L shortcut and update shift+alt+L shortcut

lib/shared/src/configuration.ts, lib/shared/src/experimentation/FeatureFlagProvider.ts, vscode/src/configuration.test.ts, vscode/src/configuration.ts, vscode/src/main.ts, vscode/src/testutils/mocks.ts
Adds a feature flag to enable if the `auto-edits` feature should be enable instead of autocomplete.
1. Override the userId `feature-flag` in the backend and see `autocomplete` triggers when flag is off, else `autoedits` trigger.
=> autoedit: Add feature flag to enable/disable autoedit feature

vscode/webviews/components/ScrollDown.tsx
Fixes https://github.com/sourcegraph/cody/issues/6133
This pull request allow interaction with interactive elements if we can see them. 
Previously the button parent took full width making it impossible to interact with the other elements unless scrolling.
Scroll until you see the Scroll to End button.
Check that you can interact with the buttons such as Copy or Execute.
Here are some screenshots with Cody within VSCode  and with the storybook for ScrollDown
Chat: ensure ScrollDown button only takes it's width allowing the interaction with other elements
=> Chat: ensure ScrollDown button only takes it's width

vscode/package.json
Fix https://linear.app/sourcegraph/issue/QA-171
Attempt to reproduce the issue in the report.
=> only activate autoedits command when experimental setting is enabled

vscode/src/autoedits/renderer.ts
Using absolute position for the decoration to prevent cursor from jumping.
https://github.com/user-attachments/assets/7ba3498f-245f-4638-8eb2-8e8f758fdea8
Used rendering examples from cody-chat-eval. See video attached for the examples.
=> feat(autoedit): fix cursor jumping issue

vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/prompt-utils.ts, vscode/src/autoedits/renderer.ts, vscode/src/completions/is-completion-visible.ts, vscode/src/main.ts, vscode/src/services/open-telemetry/debug-utils.ts
Combine inline completion provider and selection change.
CI
=> feat(autoedit): combine inline completion provider and selection change

vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/utils.test.ts, vscode/src/autoedits/utils.ts
Fix the lines sorting, the default method converts the numbers to string for sorting which was messing up the behaviour of skipping suggestions 
CI test case
=> fix added lines sorting in autoedits

vscode/src/autoedits/renderer.ts
- Fixes the issue where it was not possible to view suggestions partially rendered outside of the viewport. [Slack thread](https://sourcegraph.slack.com/archives/C07F8LLKE06/p1732079726971429?thread_ts=1732039129.933099&cid=C07F8LLKE06).
- Issue example. Notice the scrollbar at the bottom being almost equal to the viewport width:
1. Generate autoedits, which are partially rendered outside of the viewport
2. Ensure it's possible to fully view them by scrolling the viewport window to the right.
=> fix(audoedit): fix the scrollbar issue

.github/workflows/backport.yml
This reverts commit 0070f3c29e2945facce3b1d3774bd23666147e05.
Oversight on my part, I originally wanted to make it easier to type the backport label by chopping off the `vscode-` prefix, but I think this will create more confusion. Changing this back so that the backport label matches the branch that we are targetting
So if anyone needs a backport, please follow the format `backport vscode-v.major.minor.x` it should match the release branch
N/A
=> Revert "Update backport.yml (#6137)"

vscode/CHANGELOG.md, vscode/package.json
Releasing VS Code v1.44.0 off of the vscode-v1.42.x branch
N/A
=> VS Code: Release v1.44.0

lib/shared/src/sourcegraph-api/graphql/client.ts, lib/shared/src/sourcegraph-api/graphql/queries.ts, vscode/package.json, vscode/src/chat/chat-view/ChatsController.ts, vscode/src/chat/protocol.ts, vscode/src/edit/input/get-input.ts, vscode/src/edit/input/quick-pick.ts, vscode/src/main.ts, vscode/src/prompts/manager.ts, vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx, vscode/webviews/prompts/PromptsTab.tsx
closes: https://linear.app/sourcegraph/issue/SRCH-1264/surface-prompts-in-cmd-k-in-vscode-sorted-by-last-used
Adds quick pick for prompts with `alt+p` shortcut.
https://www.loom.com/share/18c0c54259e34704834d47544e02b2a3?sid=b112f153-48f2-4d4c-9a1c-0e248252ccf0
- alt + p
- search and select any prompt
- it should be executed the same way it does from the prompt library. 
Adds quick pick for prompts with `alt+p` shortcut.
=> Prompts Picker

package.json, pnpm-lock.yaml, vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/protocol.ts, vscode/src/services/open-telemetry/CodyTraceExportWeb.ts, vscode/src/services/open-telemetry/trace-sender.ts, vscode/webviews/App.tsx, vscode/webviews/Chat.tsx, vscode/webviews/chat/Transcript.story.tsx, vscode/webviews/chat/Transcript.test.tsx, vscode/webviews/chat/Transcript.tsx, vscode/webviews/utils/spanManager.ts, vscode/webviews/utils/telemetry.ts, vscode/webviews/utils/webviewOpenTelemetryService.ts, web/lib/components/CodyWebChat.tsx
Enhance the chat application by integrating OpenTelemetry for tracing and context management. This update includes:
- Added OpenTelemetry dependencies for context and tracing.
- Implemented tracing spans in chat interactions, feedback submission in Webview
- Managed active chat context using OpenTelemetry's context API.
- Introduced a telemetry service for managing tracing configuration.
- Added a new class for exporting trace data in `ChatController` from the webview 
These changes aim to improve observability and debugging capabilities by providing detailed trace information for chat interactions and operations
- Run sourcegraph instance locally
- Run `sg start otel `
- Run the debugger for vscode cody locally on this branch
- Perform some chat operations 
- Go to …
=> Integrate OpenTelemetry tracing in Cody Webview

agent/src/cli/command-bench/command-bench.ts
In context evals, we disable Polly recording so that responses to the Sourcegraph backend are not cached. This is important, so we can test local changes to the Sourcegraph backend and see updated eval results.
Before this PR, the command-bench code was accidentally ignoring `CODY_RECORDING_MODE` and always starting a Polly recording. 
Reran context evals, and everything works. Put in a `console.log` to ensure recording is disabled.
=> Bench: make sure to respect CODY_RECORDING_MODE

vscode/src/autoedits/autoedits-provider.ts
Fixes the issue where the inline completion item provider is used in cases where chars deletions are required after the cursor because of the incorrect suffix matching logic.
Manually tested by renaming the `attributes` to `values` in the following code and placing the cursor on the `const { currentLinePrefix, text, ...rest } = values` line: 
```ts
export const addAutocompleteDebugEvent = (
name: string,
attributes: Record<string, unknown> = {}
): Span | undefined => {
if (process.env.NODE_ENV === 'development') {
const activeSpan = trace.getActiveSpan()
const { currentLinePrefix, text, ...rest } = attributes
if (typeof currentLinePrefix === 'string' && typeof text === 'string') {
const formattedText = `${currentLinePrefix}█${text.trimStart()}`
return activeSpan?.addEvent(name, { text: …
```
=> fix(autoedit): fix suffix matching logic

package.json, patches/highlight.js@11.8.0.patch, pnpm-lock.yaml
Pull in https://github.com/highlightjs/highlight.js/commit/19819d5e6d6323c047923a13a16729554e6af040
This patch can be removed (`highlight.js@11.8.0`) once `highlight.js@11.11.0` is released and we've updated to it.
N/A
=> patch highlight.js to address memory leak

agent/README.md
Running the tests in recording mode assumes that the CLI is installed. The requirement was not described before. I was unobvious for me what is the tool and how to install it. This PR adds missing description.
n/a
This PR adds missing description.
=> Add Sourcegraph CLI installation description to README.md

vscode/src/main.ts
Restrict auto-edit to vscode.
Check if the auto-edit is enabled by default in debug window.
=> feat(autoedit): restrict autoedit to vscode

vscode/src/chat/chat-view/ChatController.ts
This eliminates a noticeable amount of loading wait time and lag, making the UX feel snappier.
Before:
https://github.com/user-attachments/assets/719c674b-0324-4df1-94c2-b537501ae878
After: 
https://github.com/user-attachments/assets/5031a3ea-fbcd-4923-8f27-36a265b0c8b4
Test out locally
=> do not block chat panel initialization or human message handling on current session save

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ClientCapabilities.kt, lib/shared/src/configuration/clientCapabilities.ts, vscode/src/auth/auth.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/protocol.ts, vscode/src/services/LocalStorageProvider.ts, vscode/webviews/App.tsx, vscode/webviews/AuthPage.tsx, vscode/webviews/CodyPanel.story.tsx, vscode/webviews/CodyPanel.tsx, vscode/webviews/components/AccountSwitcher.tsx, vscode/webviews/tabs/AccountTab.story.tsx, vscode/webviews/tabs/AccountTab.tsx, vscode/webviews/themes/jetbrains.css
That PR:
1. Fixes webview crashes when switching accounts with Account tab open
2. Add `Switch Account` button on the Accounts tab when `accountSwitchingInWebview` capability is enabled in client.
Testing with jetbrains `main`:
**Fixes https://linear.app/sourcegraph/issue/QA-150**
1. Open Accounts tab
3. Click Cody icon, then `Manage Accounts`
4. Switch the account 
5. Account tab should re-render properly (after a 1-2s delay) showing new account details
**Testing with jetbrains [migrated to webview account management](https://github.com/sourcegraph/jetbrains/pull/2382):**
Account switching:
1. Open Accounts tab
2. Click Switch Account
3. Select account you want to switch to from the list
4. Account tab should re-render properly (after a 1-2s delay) showing new account details
Signing …
=> Add account switcher component in the Accounts webview tab

vscode/src/completions/analytics-logger.ts
Shorter 20 sec diff have been helpful for generating shorter diff, adding 10 sec diff for offline autoedit model experiment.
no functional change
=> add 10 sec diff for autoedit experiments

vscode/CHANGELOG.md, vscode/scripts/changelog.sh
This PR adds a new section `### Uncategorized` in the changelog and some tooling for changelog generation. The script will be generate all commits between versions and place them under this heading as a stop gap until we integrate the release team's changelog automation.
When the release captain runs the release, all commits between the targeted commits will be appended, and all we need to do is make sure the next unreleased section gets bumped up.
Example, to generate the changelog between v1.44 and 1.46:
First we can find the commits using:
```
git ls-remote https://github.com/sourcegraph/cody | grep "refs/heads/vscode-v1\.[0-9]\+\.x" | sort -r | head -n 5
```
Output:
```
953a73af8639446aa209e840c4f3a62d8fa79f90        refs/heads/vscode-v1.42.x
7cc607bdc0f7af9cddee9af03cd2c8ab678dd924 …
```
=> add changelog templating and tooling

vscode/CHANGELOG.md, vscode/package.json
Release for VS code v1.46.0 gooo!!!!
passed [QA](https://sourcegraph.slack.com/archives/C06GFD8GFCN/p1732570954957729)
=> VS Code: Release v1.46.0

agent/src/AgentWorkspaceConfiguration.test.ts, agent/src/AgentWorkspaceConfiguration.ts
1. Open IntelliJ with this branch (using `CODY_DIR`)
2. Add context file in the chat - start searching for some file which is specified as ignored in '.gitignore'
3. It should not show up in the file search results
This partially solves https://linear.app/sourcegraph/issue/CODY-4379/ but perhaps we should think about general solution which should be better.
=> Add default value for 'search.useIgnoreFiles' in agent config

lib/shared/src/experimentation/FeatureFlagProvider.ts, lib/shared/src/models/sync.ts, vscode/src/chat/agentic/CodyTool.ts, vscode/src/chat/agentic/CodyToolProvider.ts, vscode/src/chat/agentic/DeepCody.test.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/webviews/chat/cells/contextCell/ContextCell.tsx
CLOSE: https://linear.app/sourcegraph/issue/CODY-4385 & https://linear.app/sourcegraph/issue/CODY-4381
This PR adds a new feature flag `DeepCodyShellContext` to enable the shell context for the deep cody feature. The feature flag is used to conditionally include or exclude the `CliTool` in the default cody tools.
Currently the feature flag is only enabled for all dotcom users by default. Enterprise admins must enable this feature flag manually.
Also added a check to ensure that the deep-cody model is only added once to the user's primary models when the DeepCody feature flag is enabled.
1. Connect to dotcom where the feature flag is enabled for all users
2. Ask Deep Cody: "how many files are there in the root of this codebase?"
3. Confirm the context includes `ls -1 .` command (or any …
=> Deep Cody: Move shell context behind feature flag

vscode/src/auth/auth.ts, vscode/src/services/AuthProvider.ts, vscode/webviews/tabs/AccountTab.tsx
Fixes https://linear.app/sourcegraph/issue/QA-183/jetbrains-user-doesnt-get-sign-out-immediately-when-logged-in-using
1. Start IntelliJ and open Cody panel
2. Go to the Account tab
3. Click `Sign Out`
Expected result:
You should see loading indicator when sign out is processed.
Whole process should not take more then 1-2 sec.
=> Make signout as non-blocking as possible

vscode/src/completions/context/context-mixer.test.ts, vscode/src/repository/githubRepoMetadata.test.ts, vscode/src/repository/githubRepoMetadata.ts, vscode/src/services/LocalStorageProvider.ts
We are always using in-memory cache for calculating `repoVisibility` always. But without passing github token, we frequently hit rate limit for querying github api and cached tokens are evicted from in-memory cache when user refresh. This leads to less data logged for the autocomplete. This PR stores the tokens in `localStorage` instead of in-memory store to cache the repo visibility.
We add the following condition to decide if to set the local storage values:
1. If the local storage cache data was changed due to updates in the local cache.
2. Since the updates to local storage can be expensive (disk operation), just to make sure we don't hit the call frequently, a time check is added, which updates the cache only if we pass a certain time compare to the last update. Although this can …
=> use local storage to save repo accessibility

vscode/src/autoedits/adapters/cody-gateway.ts, vscode/src/autoedits/adapters/fireworks.ts, vscode/src/autoedits/adapters/openai.ts, vscode/src/autoedits/adapters/sourcegraph-chat.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/prompt-provider.ts
`getPrompt` implement is same for all the adapters and we are not doing any provider specific processing. Removed the redunant methods.
No functional change.
=> remove redunant function

lib/shared/src/configuration.ts, vscode/src/autoedits/adapters/cody-gateway.ts, vscode/src/autoedits/adapters/fireworks.ts, vscode/src/autoedits/adapters/openai.ts, vscode/src/autoedits/adapters/sourcegraph-chat.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/prompt-provider.ts, vscode/src/main.ts
Use the ChatClient for S2 for autoedits.
1. Switch to S2 instance (by default it will give the error `error":"Cody Gateway access not enabled`)
2. In the debug mode, using S2 will work.
=> use chat client for s2

vscode/webviews/chat/ChatMessageContent/ChatMessageContent.tsx, vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx, vscode/webviews/client/clientState.tsx, vscode/webviews/prompts/PromptsTab.tsx, web/CHANGELOG.md, web/package.json
Fixes: https://linear.app/sourcegraph/issue/QA-186/jetbrains-new-session-is-not-generated-when-user-run-any-prompt-from
Prior to this PR, if a chat had some sent messages, you couldn't run prompts (selecting prompts does nothing). You had to create a new chat first and then run some prompts. 
When we had commands, each command ran a new chat and emitted the command's output to this newly created chat. However, prompts should try to reuse existing chat (otherwise, we will bloat out our history panel since we are tracking all prompts' execution now).
Also, on a technical note, running prompts in a new chat requires a big refactoring in how we work with the postMessage API. Currently, it's not possible to properly await commands execution, which is essential for running prompts in a new …
=> Fix prompt execution in existing chat

lib/shared/src/telemetry-v2/events/chat-question.ts, vscode/src/chat/agentic/DeepCody.ts, vscode/src/chat/chat-view/ChatController.test.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/chat-view/ChatsController.ts, vscode/test/integration/single-root/chat.test.ts
Make the following changes to tracing for chat:
- Removes the span tracking time-to-first-token. This didn't really make sense to track as a separate span, since all it did was track the time from the start of the chat handler to the first token emitted. This is better tracked as an event on the root span.
- Add a span that tracks the duration of the LLM response (and records an event for the first token)
- Add spans for other preprocessing actions, such as prompt construction and context fetching.
*Reviewer note:*: the warnings about invocations of `unsafe_` are due to removing the `startSpan` call corresponding to the "firstToken" span, which led to a big dedent in `ChatController.ts`.
No behavior changes, verify locally.
Code is best reviewed with `?w=1`
=> Update tracing for chat

lib/shared/src/chat/chat.ts
With the introduction of new model configuration, the model identifiers start with `provider::`. For fireworks, this would be `fireworks::version::model_name`. This leads to missing a check when using chat completions from sourcegraph instance to fireworks, which always leads to appending the `assistant` message.
This leads to very bad quality for the fireworks auto-edit models which shouldn't have this token.
The PR corrects the condition to detect the fireworks model.
Green CI
=> fix detecting the fireworks model

agent/src/AgentSecretStorage.test.ts, agent/src/AgentSecretStorage.ts, agent/src/agent.ts
There is a bug in the current auth flow for client managed secrets. This bug only affects Eclipse because it is the only extension using the `client-managed` secrets capability. The issue is simply that the `AgentClientManagedSecretStorage` did not fire the VSCode event when the secret was updated, which caused the extension to use a cached stale value for `AuthCredentials`.
Added unit tests.
Fixes a bug in the Eclipse plugin where the extension could become unresponsive.
=> fix(agent): Client-managed secrets bug

vscode/src/chat/agentic/CodyChatMemory.ts, vscode/src/prompt-builder/index.ts, vscode/webviews/chat/cells/contextCell/ContextCell.tsx, vscode/webviews/components/shadcn/ui/accordion.tsx
Part of https://linear.app/sourcegraph/issue/CODY-4282/implement-ui
This PR adds a new loading message for Deep Cody during the context fetch as shown in [figma](https://www.figma.com/design/f078wFMKsIOaEwj7Iwj5xy/Unified-Cody?node-id=7560-12708&node-type=canvas&t=eABWAYKAZQhp2lCP-0):
Will be continued in [bee/deep-cody-flow-ui](https://github.com/sourcegraph/cody/compare/bee/deep-cody-flow-ui?expand=1).
1. Enable Deep Cody
2. Ask Deep Cody a question
3. Confirm the new loading message is showing up during the context fetching step
=> Deep Cody: loading message for context fetching step

lib/shared/src/experimentation/FeatureFlagProvider.ts, vscode/webviews/CodyPanel.tsx, vscode/webviews/components/Notices.story.tsx, vscode/webviews/components/Notices.tsx, vscode/webviews/utils/useExperimentalFeature.tsx
CLOSE https://linear.app/sourcegraph/issue/CODY-4458/implement-ui-for-cta-upsell
This change introduces a new Sourcegraph Teams upgrade CTA feature flag and updates the `Notices` component that displays various notices to the user based on their account information and Cody configuration.
The new feature flag `SourcegraphTeamsUpgradeCTA` is used to control the visibility of the Sourcegraph Teams upgrade CTA in the Notices component. The CTA will now only be shown to Sourcegraph.com users when the feature flag is enabled.
The notices can be dismissed per-session, and the component will only display the active notice.
1. Enable the `teams-upgrade-available-cta` feature flag for your account on DotCom and S2
2. Start Cody from this branch
3. Log into DotCom and verify you can see the CTA …
=> Webviews: add new CTA for Sourcegraph Teams

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ClientCapabilities.kt, agent/src/vscode-shim.ts, lib/shared/src/configuration/clientCapabilities.ts, vscode/CHANGELOG.md, vscode/src/commands/context/shell.ts
CLOSE https://linear.app/sourcegraph/issue/CODY-3817
1. set shell capability based on client configuration.
This change updates the `vscode-shim` to set the `shell` capability based on the client's reported capabilities. If the client set the `shell` environment variable to `enabled`, it will be set to `'agent'`, otherwise it is set to `undefined`.
When enabled, the client must be running with node integration enabled that supports `child_process.spawn`. This is needed for the agent to spawn a shell process to run commands in IDEs that support node runtime.
This ensures that the shell command functionality is only enabled when the client has the necessary support.
2. set client environment based on configuration
This change updates the `vscode-shim` to set the client environment variables …
=> Agent: set client environment based on client configuration info

.github/workflows/vscode-stable-release.yml
This will PR will do the following:
1. push a notification to a slack channel informing us that the release is successful
2. calculates the next prerelease version, and provides a preview of the changes going into the next version (stopgap solution for GTM and PMM)
3. creates the next backport label
4. creates the next prerelease branch and pushes it to main
It will only create new prerelease branches and backport labels when there is a new minor version, patch increments will be skipped. 
The slack notification will look something like:
This will reduce the cognitive load on the release captain to always remembering to cut the next release branches, reducing the chance of error. The release captain just needs to make sure that they merge changelog and version bumps first. 
next up is …
=> Improve release process with slack notifications and automated branching

vscode/src/commands/context/shell.ts
Follow up on https://github.com/sourcegraph/cody/pull/6255
- Exclude the wildcard (`*`) from the shell command allow list when processing the user configuration.
- This ensures that the allow list is properly filtered and only allows specific commands, instead of allowing all commands by default.
Ask Deep Cody "what's my git config user name?"
This config should allow Deep Cody to run any shell commands and use it as chat context:
```json
"cody.agentic.context": {
"shell": {
"allow": [
"*"
],
}
}
```
This config should block Deep Cody to run the `git` shell commands:
```json
"cody.agentic.context": {
"shell": {
"allow": [
"*"
],
"block": [
"git"
]
}
}
```
=> fix(deep-cody): wildcard should not be ignored in allow list for shell context

vscode/CHANGELOG.md, vscode/package.json
Docs only change + version bump.
chore/release: Prepare changelog for VSCode v1.48.0
=> chore/release: Update CHANGELOG for VSCode 1.48.0

lib/shared/src/prompt/prompt-string.ts, lib/shared/src/tracing/index.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/protocol.ts, vscode/src/edit/manager.ts, vscode/src/edit/provider.ts, vscode/src/edit/smart-apply.ts, vscode/src/services/open-telemetry/CodyTraceExport.ts, vscode/src/services/utils/codeblock-action-tracker.ts, vscode/webviews/Chat.tsx, vscode/webviews/chat/Transcript.tsx, vscode/webviews/utils/spanManager.ts, vscode/webviews/utils/telemetry.ts, vscode/webviews/utils/webviewOpenTelemetryService.ts
This PR introduces distributed tracing to connect traces originating in the UX with those starting in the extension host. This ensures unified and all-encompassing traces for operations spanning both the web view and the extension host.
NOTE: this PR has been rebased to the main and is ready for review
1.  Distributed Tracing for Chat Interaction: Traces starting in the UX are now connected to corresponding traces in the extension host for chat interactions.
2. Distributed Tracing for Smart Apply: Similarly, traces for Smart Apply now span both the UX and the extension host.
These changes are in alignment with the milestone goals and aim to deliver foundational support for distributed tracing in these areas.
- Immediate Goal: Ensure distributed tracing is functional and provides value for …
=> Adding Distributed Tracing and Smart Apply to cody

vscode/src/auth/auth.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/services/AuthProvider.ts, vscode/webviews/components/AccountSwitcher.tsx
Fixes QA-194.
Manual test:
- Sign in to JetBrains with two accounts.
- Switch to the Accounts tab, Switch Accounts and remove the second account.
- Verify that you stay signed in on the accounts tab, and the second account is gone from the account switcher.
fix/accounts: Removing a second account does not dump you back at the login screen.
=> fix/accounts: Do not sign out when removing an unrelated account

vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-diff-helpers/helper.ts, vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-diff-helpers/two-stage-unified-diff.test.ts, vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-diff-helpers/utils.test.ts, vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-diff-helpers/utils.ts
We aggregate the changes which are made on the same lines together for recent edits diff calculation. However, if we replace the text block in the vscode editor, the vscode editor create seperate events for each line even though the change is a single replacement. In the PR we group the changes to if the timestamps are same 2 different change even if they are added on different lines.
Added test cases
=> fix line level aggregation logic for recent edits

lib/shared/src/prompt/prompt-string.ts, lib/shared/src/tracing/index.ts, package.json, pnpm-lock.yaml, vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/protocol.ts, vscode/src/edit/manager.ts, vscode/src/edit/provider.ts, vscode/src/edit/smart-apply.ts, vscode/src/services/open-telemetry/CodyTraceExport.ts, vscode/src/services/open-telemetry/CodyTraceExportWeb.ts, vscode/src/services/open-telemetry/trace-sender.ts, vscode/src/services/utils/codeblock-action-tracker.ts, vscode/webviews/App.tsx, vscode/webviews/Chat.tsx, vscode/webviews/chat/Transcript.story.tsx, vscode/webviews/chat/Transcript.test.tsx, vscode/webviews/chat/Transcript.tsx, vscode/webviews/utils/spanManager.ts, vscode/webviews/utils/telemetry.ts, vscode/webviews/utils/webviewOpenTelemetryService.ts, web/lib/agent/shims/stream.ts, web/lib/agent/shims/zlib.ts, web/vite.config.ts
Reverts sourcegraph/cody#6268  Reverts the original  revert of  commits https://github.com/sourcegraph/cody/commit/56866996ebbc16dc7bf145220a9c461acd8ef683 and https://github.com/sourcegraph/cody/commit/6bf801bc33760b227a5a1dfe2ca27add8caa5207 because they did NOT cause the logging of the spans so its okay to have this in our codebase again. 
Related PR https://github.com/sourcegraph/cody/pull/6292#discussion_r1878230544 
[RElated Linear Issue 
](https://linear.app/sourcegraph/issue/CODY-4494/investigate-excessive-logging-and-span-operation-issues-in-jetbrains)
[Slack Thread
](https://sourcegraph.slack.com/archives/C05AGQYD528/p1733309439863749)
I tested it locally with JAegar
=> Double revert the PRs for distributed tracing to finally get them merged into the codebase

jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt
- Add `shell` property to `ClientCapabilities` with `Enabled` value
- This makes shell command execution available for JetBrains clients when the configuration is enabled by the instance and user
This is for JetBrains client to let the agent know it has the ability to execute shell commands (added by https://github.com/sourcegraph/cody/pull/6194), so that users can follow the instructions on the UI (https://github.com/sourcegraph/cody/pull/6279) to enable shell commands if needed.
See details in https://github.com/sourcegraph/cody/pull/6194
=> feat(jetbrains): enable shell capabilities

lib/shared/src/models/sync.ts
This commit removes the logic that adds deep-cody model to user's model list.
This does so by removing the associated feature flag checks and model replacement logic.
Build from this branch and confirm you don't see Deep Cody showing up in your model list with any of your accounts (PLG or Enterprise).
=> fix(models): remove deep-cody model replacement logic

vscode/webviews/components/Notices.tsx, vscode/webviews/components/modelSelectField/ModelSelectField.story.tsx, vscode/webviews/components/modelSelectField/ModelSelectField.tsx
CONTEXT: https://sourcegraph.slack.com/archives/C06GFD8GFCN/p1733856027839759?thread_ts=1733844935.078399&cid=C06GFD8GFCN
Follow up on https://github.com/sourcegraph/cody/pull/6279
- Introduce new notice IDs 'DeepCodyDotCom' and 'DeepCodyEnterprise' to differentiate the Deep Cody notice for Pro and Enterprise users
- Update the `Notices` component to show the appropriate notice based on the user's plan
- Adjust the `NoticeContent` component to render the correct header for each notice variant
This fixes an issue where notice for Deep Cody does not show up for Cody Pro users, as the feature flag only applies to Enterprise users.
Log in as Pro user / Enterprise user:
- Notice for Deep Cody shows up when Deep Cody is available
- The notice should not show up again after you have dismissed it …
=> fix(Deep Cody): show notices for Pro and Enterprise users

jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/editor/CodyLookupListener.kt, jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt
Closes https://github.com/sourcegraph/jetbrains/issues/2572 and probably a few others. 
Invoke autocomplete in the debug console. Invoke autocomplete in the evaluate expression line/dialog. Invoke autocomplete anywhere but the main editor. It should work in the main editor only.
This PR make us more strict about where we trigger the autucomplete.
=> Fix invalid range errors

vscode/CHANGELOG.md
Fixes the errors you see when the stable release workflow runs and complains about a missing `github_changelog.md`  (ex - https://github.com/sourcegraph/cody/actions/runs/12207820901/job/34059923063#step:12:13)
The `github-changelog.ts` script will parse the existing changelog to generate a github release entry, this PR removes the `[]` in the changelog so the regex capture group will extract the version number correctly. 
tested locally by running `pnpm -C vscode run github-changelog` and checking the output of `GITHUB_CHANGELOG.md`
=> fix(release): remove brackets around version number

vscode/webviews/components/UserAvatar.module.css
CLOSE: https://linear.app/sourcegraph/issue/CODY-4496/debugger-displaying-profile-picture-in-unexpected-locations
- Adds a `max-height: 24px` rule to the `.user-avatar` class in the `UserAvatar.module.css` file to ensure the user avatar component does not exceed a maximum height of 24 pixels.
Check if your user avatar in the home screen is showing up at the right size.
=> fix(webviews): limit user avatar height to 24px

lib/shared/src/sourcegraph-api/graphql/client.ts, web/CHANGELOG.md, web/package.json
Fixes https://linear.app/sourcegraph/issue/SRCH-1456/cody-chat-fails-with-unsupported-model-error
When the user runs Cody Web (in theory this problem exists in all Cody chat clients) for the first time they don't have any configuration information in their local storage (IndexDB in the case of Cody Web) 
Seeding local storage on the initial run, we fire a lot of configuration updates, which triggers invalidation logic. Sometimes (it's a race condition between requests an configuration updates), some important requests are pending, and invalidation works in a way that cancels all ongoing flights. When we cancel all of them, we don't fetch vital information for proper chat work. 
Currently, it just omits `clientState` field from cache invalidation but ideally, we should map it to a minimal …
=> fix(cody): fix empty local storage cody chat run

lib/shared/src/experimentation/FeatureFlagProvider.ts, lib/shared/src/sourcegraph-api/errors.ts, vscode/src/chat/agentic/DeepCodyRateLimiter.test.ts, vscode/src/chat/agentic/DeepCodyRateLimiter.ts, vscode/src/chat/agentic/prompts.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/services/LocalStorageProvider.ts, vscode/webviews/chat/ErrorItem.tsx
CLOSE: https://linear.app/sourcegraph/issue/CODY-4510
- Add `deepCodyLastUsageTime` and `deepCodyDailyUsageCount` keys to `LocalStorage` class
- Implement `isAtDeepCodyDailyLimit()` method to check if the daily usage limit for Deep Cody has been reached
- In `ChatController`, check if the selected model is Deep Cody and if the daily limit has been reached, and display an error message if so
- Update `RateLimitError` to handle Deep Cody feature
- Conditionally render the "Learn More" button in `ErrorItem` for Deep Cody errors
- Add `DeepCodyRateLimitBase` and `DeepCodyRateLimitMultiplier` feature flags to control the rate limit for Deep Cody
- Implement `isAtDeepCodyDailyLimit()` method in `LocalStorage` to check if the user has reached the daily usage limit for Deep Cody
- In …
=> feat(deep-cody): implement daily usage limit

vscode/CHANGELOG.md, vscode/package.json, vscode/scripts/changelog.sh
CI
- The vscode/scripts/changelog.sh script now correctly points to *pull* not *pulls* in the GitHub URLs.
=> chore/release: VSCode, bump package.json version to 1.50.0 and update release notes

vscode/src/autoedits/renderer/decorators/base.ts, vscode/src/autoedits/renderer/decorators/inline-diff-decorator.ts, vscode/src/autoedits/renderer/diff-utils.test.ts, vscode/src/autoedits/renderer/diff-utils.ts, vscode/src/autoedits/renderer/inline-manager.test.ts, vscode/src/autoedits/renderer/inline-manager.ts
- Addressing a comment from the recent PR review: https://github.com/sourcegraph/cody/pull/6235#discussion_r1876279079
- Removes the direct mutation of the decoration info in favor of creating a new decoration info object with filtered changes (we remove changes used for the inline completion item rendering from the object). 
- I considered using array indices instead of change IDs, but that would make the code more complex and less flexible. By adding IDs, we can uniquely identify each change in any new structure we create from these object, without needing to maintain the original order or number of changes.
CI + updated unit tests.
=> feat(audoedit): avoid decoration info mutation

vscode/webviews/chat/Transcript.tsx, vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx, vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx
A bug was introduced as part of https://github.com/sourcegraph/cody/pull/6294 which causes manual selection of the intent to be ignored. This PR fixes it.
https://www.loom.com/share/dfcfcc6decca4ca19cfb3220d8026a07?sid=99e6d5f1-84d5-4838-8ed8-200126c17305
=> Fix manual intent selection for onebox

lib/shared/src/sourcegraph-api/graphql/cache.ts, lib/shared/src/sourcegraph-api/graphql/client.ts, vscode/src/auth/auth.ts, web/CHANGELOG.md, web/lib/agent/agent.client.ts, web/package.json
#6111 tried to be clever and use `using`, but Firefox does not have Symbol.dispose. Switch back to good ol' try-finally and method calls.
`pnpm -C web dev`
Run Firefox and open <http://localhost:5777>. Loading Cody Web will still fail, but there is no message about dispose in the console. This does *not* appear:
```
Authentication failed TypeError: Object not disposable
Immutable 6
__typeError
__using
validateCredentials
validateAndStoreCredentials
handleConfigChanges
Agent
```
Run Chrome and open the same. Cody Web works and you can chat, etc.
=> fix/web: Fix an error in auth arising from missing Symbol.dispose.

lib/shared/src/chat/transcript/messages.ts, lib/shared/src/index.ts, vscode/webviews/chat/Transcript.tsx, vscode/webviews/chat/cells/contextCell/ContextCell.tsx, vscode/webviews/chat/cells/messageCell/assistant/AssistantMessageCell.tsx, vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx, vscode/webviews/chat/cells/messageCell/assistant/SwitchIntent.tsx
closes: https://linear.app/sourcegraph/issue/SRCH-1423/more-results
closes: https://linear.app/sourcegraph/issue/SRCH-1426/more-results-disabled
closes: https://linear.app/sourcegraph/issue/SRCH-1427/link-to-code-search
closes: https://linear.app/sourcegraph/issue/SRCH-1434/switch-between-chat-and-search-results
This PR adds `More Results`, `Code Search` and `Switch to Chat` interactions to the OneBox Search Results. For more details, check the Loom video.
https://www.loom.com/share/9e9c3c0a2bea4b629cabcb75273b176d
=> Implement more results and intent switcher

vscode/src/chat/agentic/CodyChatMemory.ts, vscode/src/services/LocalStorageProvider.ts
- Add logging for chat memory operations
- Handle null values when setting chat memory
Fix an issue where memory is persisted after Deep Cody tries to reset the chat memory
1. Ask Cody to forget what's in your memory
2. In a new chat, ask Deep Cody about what is stored in its memory. Deep Cody should tell you there is nothing.
=> fix(deep-cody): agent can removes memory from storage

vscode/webviews/chat/cells/messageCell/BaseMessageCell.tsx, vscode/webviews/components/UserAvatar.module.css, vscode/webviews/components/UserAvatar.tsx, vscode/webviews/components/UserMenu.tsx, vscode/webviews/components/promptList/ActionItem.module.css, vscode/webviews/components/promptList/ActionItem.tsx, vscode/webviews/tabs/AccountTab.tsx, vscode/webviews/tabs/TabsBar.story.tsx
CLOSE https://linear.app/sourcegraph/issue/CODY-4496/debugger-displaying-profile-picture-in-unexpected-locations
Follow up on https://github.com/sourcegraph/cody/pull/6319
- Remove the max-height constraint on user avatars
- Apply the provided className to the inner user avatar component
- Fix the string issue in style
- Remove fixed width and height constraints on user avatars 
- Use a consistent avatar size across different UI components 
- Introduce a constant for the user menu avatar size 
- Update storybook
This should also fix the issue reported by a Discord user:
Verify that user avatars are displayed correctly in the Cody web application, with consistent sizing across different UI components..
In the main chat view
In the prompt library view
Check storybook
=> fix(webviews): standardized user avatar size

lib/shared/src/models/model.ts, vscode/webviews/components/Notices.tsx
CLOSE: https://linear.app/sourcegraph/issue/CODY-4518
CONTEXT: https://sourcegraph.slack.com/archives/C0847FJ0A73/p1734027061624399
This PR adds the `ModelTag.Experimental` tag to the `getServerModelTags` function which is the cause of Deep Cody currently missing the experimental tag in pre-release. This tag will be used to identify models that are in an experimental phase, which can be useful for displaying additional information or handling these models differently.
Also update the CTA for Deep Cody and add an info section about that daily usage limit.
Minor CTA update:
=> fix(deep-cody): missing experimental badge on model list

lib/shared/src/experimentation/FeatureFlagProvider.ts, lib/shared/src/models/modelsService.ts, lib/shared/src/models/sync.test.ts, lib/shared/src/models/sync.ts
This PR does [Run experiment on Claude 3.5 Haiku as the default chat model for Free users](https://linear.app/sourcegraph/issue/CODY-4455/run-experiment-on-claude-35-haiku-as-the-default-chat-model-for-free). This is part of [LLM cost reduction for PLG users](https://linear.app/sourcegraph/project/llm-cost-reduction-for-plg-users-57f5801d7ea1/issues).
Problem: We want to reduce the LLM cost for PLG users.
This PR prepares for A/B test on Claude 3.5 Haiku as a default chat model Free users.
Free users with cody-chat-default-to-claude-3-5-haiku feature flag set to true will have Claude 3.5 Haiku as the default model. 
The success criteria are defined in the linear ticket above.
Things the PR does:
- `FeatureFlagProvider.ts` and `sync.ts`: Add the new feature flag and the main logic.
- …
=> feat/cody: Prep for the A/B test on Claude 3.5 Haiku as the default chat model for Free users (CODY-4455)

vscode/e2e/README.md, vscode/e2e/issues/README.md
This change ensures consistent capitalization of the GitHub and GitLab brand names in Markdown documentation.
[_Created by Sourcegraph batch change `sqs/capitalize-brands-correctly`._](https://sourcegraph.sourcegraph.com/users/sqs/batch-changes/capitalize-brands-correctly)
=> Fix GitHub/GitLab brand capitalization

agent/src/agent.ts, jetbrains/src/integrationTest/kotlin/com/sourcegraph/cody/util/CodyIntegrationTextFixture.kt, jetbrains/src/integrationTest/resources/recordings/integration-test_2927926756/recording.har.yaml, lib/shared/src/auth/authStatus.ts
Automatic tests
After my recent changes `firstResultFromOperation(authStatus)` was waiting until auth status was set, but that auth status could be in `pendingValidation: true` state.
We do not want that, we want to wait until it's either authenticated successfully or not.
This PR is fixing that.
=> Wait for auth status completion during agent initialisation

lib/shared/src/models/sync.ts
This PR fixes the logic for display Deep Cody to only enable it for PLG users, not for Cody Free users. Previously, Deep Cody is visible for all DotCom users.
Log in as Free users on VS Code to make sure you don't see Deep Cody on the list:
Log in as Pro or S2 user to make sure you can see it on the model list.
=> refactor(deep-cody): show model to Pro users only

vscode/src/chat/agentic/DeepCodyRateLimiter.test.ts, vscode/src/chat/agentic/DeepCodyRateLimiter.ts
FIX https://linear.app/sourcegraph/issue/CODY-4529
This PR fixes an issue where users were unable to use Deep Cody even after the 24-hour cooldown period had elapsed.
- Added explicit 24-hour reset check in `DeepCodyRateLimiter.isAtLimit()`
- Simplified quota replenishment logic
- Improved handling of initial quota state
Previously, the rate limiter used a continuous time-based quota replenishment system that calculated partial quotas based on elapsed time. This led to unexpected behavior where users wouldn't get a fresh quota even after not using Deep Cody for over 24 hours.
The updated implementation:
1. First checks if a full day (24 hours) has passed since last usage
2. If yes, immediately resets to full quota
3. If no, calculates remaining quota using time-based replenishment
Added …
=> fix(deep-cody) Rate Limiter Reset Logic

lib/shared/src/experimentation/FeatureFlagProvider.ts, lib/shared/src/models/modelsService.ts, lib/shared/src/models/sync.test.ts, lib/shared/src/models/sync.ts
Backport https://github.com/sourcegraph/cody/pull/6368 which depends on https://github.com/sourcegraph/cody/pull/6304
See https://github.com/sourcegraph/cody/pull/6368 &. https://github.com/sourcegraph/cody/pull/6304
=> [Backport vscode-v1.52.x] show Deep Cody to pro users only

vscode/src/autoedits/prompt/default-prompt-strategy.test.ts, vscode/src/autoedits/prompt/default-prompt-strategy.ts, vscode/src/autoedits/prompt/prompt-utils.test.ts, vscode/src/autoedits/prompt/prompt-utils.ts, vscode/src/autoedits/prompt/short-term-diff-prompt-strategy.test.ts, vscode/src/autoedits/prompt/short-term-diff-prompt-strategy.ts
1. Fixes the indentation issue in the auto-edits which was happening because of using `psDedent`.
2. Added a helper function to join prompts on the new lines instead of using `psDedent`.
Added CI test cases
=> fix newline indentation as per finetuning data

vscode/src/chat/agentic/DeepCodyRateLimiter.test.ts, vscode/src/chat/agentic/DeepCodyRateLimiter.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/services/LocalStorageProvider.ts
Follow up on https://github.com/sourcegraph/cody/pull/6366
This PR fixes several issues with the Deep Cody rate limiter implementation:
Root Cause Fix: Rate Limit State Synchronization
- Fixed race condition in LocalStorageProvider.ts where concurrent Promise.all() usage led to inconsistent state between quota and timestamp storage
- Changed to sequential storage operations to ensure timestamp is always saved after quota update
- This resolves the core issue where users were locked out due to incorrect time calculations (CODY-4529)
- Added precise tests for time-based quota calculations
- Enhanced test coverage for various timing scenarios
Before this change, the Deep Cody rate limit error would always return the "Retry time" with current time + 24 hours to indicate the current time is …
=> fix(deep-cody): Rate limiter synchronization issue

agent/src/auth.test.ts, vscode/webviews/components/promptList/PromptList.tsx
@vovakulikov [discovered](https://github.com/sourcegraph/cody/pull/6346#issuecomment-2548014730) that nothing is shown when there are no prompts that match a filter. It should show "No prompts found" instead. This PR fixes it.
Manual testing
fix: show "no prompts found" when no prompt matches the filter
=> fix: no prompts found is now shown even with filters

vscode/src/autoedits/autoedits-provider.ts
Disable the shrinking logic causing frequent adding of prefix after the prediction.
[Slack thread for the Issue](https://sourcegraph.slack.com/archives/C07F8LLKE06/p1734437161597439) 
no functional change
=> autoedits disable shrink suffix logic

vscode/src/autoedits/utils.test.ts, vscode/src/autoedits/utils.ts
The PR fixes the inline completions extraction when the suggestions is to delete content and prefix matches with the suffix in the code.
Added unit test
=> autoedit: fix inline completion extraction when deletion

vscode/src/autoedits/renderer/decorators/inline-diff-decorator.ts
- Fixes the regression from https://github.com/sourcegraph/cody/pull/6359 which made removal decorations invisible.
1. Add `"cody.experimental.autoedits.renderer": "inline"` to your VS Code settings
2. Try examples from the cody-chat-eval repo which cause text removal and ensure that respective decorations are present.
=> fix(audoedit): do not render removal decorations twice

lib/prompt-editor/src/PromptEditor.tsx, lib/prompt-editor/src/lexicalUtils.ts, vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx
Closes srch-1483
Changing the focus behavior was more difficult than expected. Apparently when Lexical has a Selection then it will 'steal' the focus whenever changes to its content is made.
There have been made changes to Lexical just recently that would allow us to avoid this (https://github.com/facebook/lexical/pull/6894) but we haven't updated to this version yet and updating this closely before the EAP seems risky.
I found a workaround in one of the discussions that suggests to set the selection to `null` when making a change.
In order to do this I refactored some of the function to make them more composable. Instead of calling `editor.update` directly these functions are now supposed to be called from `editor.update`.
Since I've added a helper for promisifying `editor.update` …
=> fix(onebox): Do not focus editor when inserting/updating search results context

vscode/webviews/chat/cells/messageCell/assistant/SearchResults.module.css, vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx
This commit hides the 'Filters' and 'Add to context' lables when the
chat window is narrow.
Closes https://linear.app/sourcegraph/issue/SRCH-1481/remove-labels-from-the-search-results-header-on-small-screens
Manual testing.
=> fix(omnibox): Hide header labels in narrow chat

vscode/src/telemetry/onebox.ts, vscode/webviews/chat/Transcript.tsx, vscode/webviews/chat/cells/messageCell/assistant/SearchFilters.tsx, vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx
Part of https://linear.app/sourcegraph/issue/SRCH-1455/one-box-telemetry
Adds or updates the following events:
- onebox.intentCorrection:clicked
- oneBox.moreResults:clicked
- onebox.resultContext:selectAll
- onebox.resultContext:deselectAll
- onebox.resultContext:individualSelected
- onebox.resultContext:individualSelected
- onebox.filterModal:opened|closed
- onebox.filter:clicked
TODO:
- onebox.query:executed
- onebox.manualSearch:toggled
- onebox.searchResult:clicked
n/a
=> feat(onebox): Collect more telemetry

vscode/src/chat/chat-view/ChatController.ts, vscode/src/edit/manager.ts, vscode/webviews/components/promptList/PromptList.tsx, vscode/webviews/components/promptSelectField/PromptSelectField.tsx
This PR adds billingMetadata to key telemetry events that are considered either 'core' or 'billable' events ([as per this definition](https://www.notion.so/sourcegraph/V2-telemetry-product-and-category-documentation-b4f932118ea5421587e6e0a0d90d78e1)). Prior to this change, these events did not have any billingMetadata classifications. This change will help the analytics team group billable and core users of the product.
Key changes:
Added billingMetadata to existing telemetry events based on this [list](https://docs.google.com/spreadsheets/d/1fECquIRqzOCz-aCT25wMF1WVWbQp8u8LE2lasIzvHkM/edit?gid=949192093#gid=949192093) provided by analytics.
CI
=> chore/(telemetry): update `billingMetadata`

.github/workflows/vscode-stable-release.yml
removing the steps to automate the next pre-release branch and label creation, we should probably do this as a separate workflow to help decouple things
also adding in the announce releases webhook to notify when vs code releases are out
N/A - removing 3 steps in GHA
=> chore(release): remove next pre-release branch and label creation

vscode/src/autoedits/renderer/renderer-testing.ts
- Fixes the default renderer testing command
Use `ctrl + alt + enter` in the `code-chat-eval` renderer-testing examples.
=> fix(audoedit): fix renderer testing command

package.json, pnpm-lock.yaml, vscode/package.json, vscode/webviews/chat/ErrorItem.tsx, vscode/webviews/chat/Transcript.test.tsx, vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.test.tsx, vscode/webviews/chat/components/FeedbackButtons.tsx, vscode/webviews/testSetup.ts
This was an interesting issue to debug: In the Sourcegraph web app we have a CSS variable `--input-height`. We noticed that when cody was open, this variable was set to a different value. But nowhere in the Cody codebase to we set this value explictly.
In turns out that `@vscode/webview-ui-toolkit` constructs a stylesheet programmatically and sets a couple of global CSS variables:
We only use components from this library in two places and they can easily be replaced by our own components, thus avoiding this problem altogether.
NOTE: We'll have to cut a new cody web release for this to fix the web app issue.
Manual testing by running the web demo. I verified that the CSS variables are not created anymore and inspected the updated UI, which is slightly different (e.g. hover effects of …
=> fix: Prevent style leaks in cody web

vscode/webviews/components/UserMenu.story.tsx, vscode/webviews/components/UserMenu.tsx
CLOSE https://linear.app/sourcegraph/issue/QA-206/vsc-enterprise-label-is-misaligned-in-account-window
Fixes user menu layout issue:
- Truncate long usernames and emails to prevent overflow
- Align user avatar and information vertically
- Adjust badge styling for better readability
- Update test cases with longer email addresses
Updated Storybook to reflect the changes
After
=> refactor(user-menu): improve display of user menu

agent/src/unauthed.test.ts
- Disables the flaky agent test.
- [CODY-4546: Fix the flaky `agent/src/unauthed.tests.ts` and reenabled it back](https://linear.app/sourcegraph/issue/CODY-4546/fix-the-flaky-agentsrcunauthedteststs-and-reenabled-it-back)
CI
=> chore(agent): disable flaky test

vscode/src/autoedits/renderer/decorators/default-decorator.ts
Fixing some regressions in the rendering:
1. Fix a case for the auto-edits diff view rendering.
2. The diff view did not color the red decorations correctly because of incorrect ranges.
3. Fix ghost text rendering ranges
1. Press `ctrl + alt + enter`
2. See the [recent-edit example](https://github.com/sourcegraph/cody-chat-eval/blob/main/code-matching-eval/edits_experiments/examples/renderer-testing-examples/recent-edit.ts) in the cody-chat-eval repo.
Before:
After:
4. See the [example](https://github.com/sourcegraph/cody-chat-eval/blob/main/code-matching-eval/edits_experiments/examples/renderer-testing-examples/olaf-example-autoedits.ts) in cody-chat-eval repo:
Before (See the inconsistent insertion point for the second ghost text in lines):
After:
=> fix diff rendering for autoedits

lib/shared/src/experimentation/FeatureFlagProvider.ts, vscode/webviews/AppWrapperForTest.tsx, vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx
This updates HumanMessageEditor to use the new prompt editor when onebox is enabled.
Trival code change (also not sure how to test that locally).
=> feat(onebox): Use new prompt editor when onebox is enabled

vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx
fixes: https://sourcegraph.slack.com/archives/C07EQBRSF35/p1734729091939879
- Perform `SchemeTokenSudo @sourcegraph/sourcegraph` interaction with Cody.
- That should return into results including the `SchemeTokenSudo` symbol match.
=> include symbol matches in search results

vscode/src/chat/chat-view/ChatController.ts
closes: https://linear.app/sourcegraph/issue/SRCH-1491/get-current-repository-without-a-file-being-open
This PR uses the workspace root folder as a fallback when the active editor is null.
- execute search without mentioning a repo while no file from the repo is opened.
=> Enable repo boost for inactive editor

vscode/webviews/components/modelSelectField/ModelSelectField.module.css, vscode/webviews/components/modelSelectField/ModelSelectField.tsx
Fixes #6097 Chat model selector not showing all options
Check out https://www.youtube.com/watch?v=4LYRRSzbh_Q for the before and after effects of this fix
both in vscode and in storybook
Start storybook and notice that enterprise option is not visible before this fix
http://localhost:6007/?path=/story/cody-chat--empty
here's before:
and after:
fix(modelSelectField): missing overflow scrollbar when there isn't space to show entire list
=> fix(modelSelectField): missing overflow scrollbar when there isn't space to show entire list

vscode/src/autoedits/renderer/decorators/default-decorator.ts
The PR address dogfooding feedback:
1. Earlier `auto-edit` diff view would render on the line where the cursor is currently placed instead of where the completion is supposed to be inserted.
2.  This caused issue with rendering where, the current line text would be shifted to the right, because the text insertion range is different from where cursor could be placed.
3. The PR replaces the diff view location to where it is actually supposed to insert instead of where cursor is located. 
1. Ran on all the [cody-chat-eval](https://github.com/sourcegraph/cody-chat-eval/tree/main/code-matching-eval/edits_experiments/examples/renderer-testing-examples) examples
2. Fixes [this example](https://github.com/sourcegraph/cody-chat-eval/blob/main/code-matching-eval/edits_experiments/examples/renderer-t …
=> autoedit: address dogfooding feedback

vitest.setup.ts, vscode/src/autoedits/prompt/prompt-utils.test.ts, vscode/src/completions/test-helpers.ts, vscode/src/testutils/mocks.ts
- Added vscode.NotebookDocument mocks to be able to create basic unit tests for https://github.com/sourcegraph/cody/pull/6449
CI + new unit tests
=> feat(audoedit): add notebook mocks and basic unit tests

vscode/src/chat/agentic/CodyTool.ts, vscode/src/chat/agentic/prompts.ts
I tested several PoCs with Deep Cody, which included something in the context (in my testing, a local file) pointing Cody to run something dangerous or malicious. I was able to execute:
- network requests
- accessing sensitive files (like /etc/passwd)
- creating arbitrary files
These prompt tweaks were initially suggested by Claude with the prompt generator, but then I tested and tweaked it further. The command execution is still hit-and-miss but this definitely improves the overall behavior. We will continue to rely on explicit user consent to enable the feature and an allowlist for which commands to execute.
I created PoCs and, with the new prompt, they did not execute successfully anymore.
=> Add security considerations to prompt

lib/shared/src/completions/types.ts, vitest.setup.ts, vscode/src/autoedits/prompt/default-prompt-strategy.test.ts, vscode/src/autoedits/prompt/prompt-utils.test.ts, vscode/src/autoedits/prompt/prompt-utils.ts, vscode/src/autoedits/prompt/short-term-diff-prompt-strategy.test.ts, vscode/src/completions/analytics-logger.ts, vscode/src/completions/context/completions-context-ranker.test.ts, vscode/src/completions/context/completions-context-ranker.ts, vscode/src/completions/context/context-mixer.test.ts, vscode/src/completions/context/retrievers/jaccard-similarity/jaccard-similarity-retriever.ts, vscode/src/completions/context/retrievers/recent-user-actions/diagnostics-retriever.test.ts, vscode/src/completions/context/retrievers/recent-user-actions/diagnostics-retriever.ts, vscode/src/completions/context/retrievers/recent-user-actions/notebook-utils.ts, vscode/src/completions/context/retrievers/recent-user-actions/recent-copy.test.ts, vscode/src/completions/context/retrievers/recent-user-actions/recent-copy.ts, vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-retriever.ts, vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-tracker.ts, vscode/src/completions/context/retrievers/recent-user-actions/recent-view-port.test.ts, vscode/src/completions/context/retrievers/recent-user-actions/recent-view-port.ts, vscode/src/completions/context/retrievers/tsc/tsc-retriever.ts, vscode/src/completions/model-helpers/__tests__/test-data.ts, vscode/src/completions/test-helpers.ts, vscode/src/graph/lsp/symbol-context-snippets.ts, vscode/src/testutils/mocks.ts
The PR adds the support for the notebook in the `auto-edits`.
1. By default each cell is treated as a separate document, hence we get limited context for the current file. We add the content for the full file.
2. All the context sources used to ignore the notebooks. Now, all following the context sources tracks the support for notebooks and context is persisted between `py` and `ipynb`:
- Recent Edits
- Diagnostics
- Recent View Port 
existing CI and Manual testing to check behaviour in case of notebook
=> track notebook for auto-edits

jetbrains/src/main/kotlin/com/sourcegraph/cody/inspections/CodyFixHighlightPass.kt
Fixes CODY-4573.
The exception in that bug happened because `TypeScriptLanguageServiceFix.getFamilyName` could block the thread, but we were calling it on EDT. The fix is to simply check that the action is related to Cody before drilling down into the name.
In theory any accessor on highlights could be poorly implemented, but in practice Ask Cody to Fix works in TypeScript files now so this is an improvement.
```
cd jetbrains
SKIP_CODE_SEARCH_BUILD=true ./gradlew :customRunIde \
-PforceAgentBuild=true \
-PplatformRuntimeType=WS -PplatformRuntimeVersion=2024.3
```
- Create or open a TypeScript file. Enter some nonsense like `function f(s: string, s: number) {`
- Use the lightbulb hover, or press Alt-Enter to show quick actions.
- "Ask Cody to Fix"
- Verify that the feature works and …
=> fix/editor: Ask Cody to Fix no longer throws exceptions in TypeScript files 

vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/renderer/manager.ts, vscode/src/completions/context/context-mixer.ts, vscode/src/completions/context/retrievers/recent-user-actions/diagnostics-retriever.ts, vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-retriever.ts, vscode/src/completions/context/retrievers/recent-user-actions/recent-view-port.ts
We had report of `auto-edits` [stops working randomly](https://sourcegraph.slack.com/archives/C05AGQYD528/p1735184987501309). One hypothesis is that the `auto-edits` pipeline unexpectedly breaks in between, adding more logs in the output channel to see at what stage does `auto-edits` break.
no functional change, added more logs
=> add more debug logs to inspect autoedits issue

vscode/src/autoedits/analytics-logger/analytics-logger.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/prompt/base.ts, vscode/src/autoedits/prompt/default-prompt-strategy.test.ts, vscode/src/autoedits/prompt/default-prompt-strategy.ts, vscode/src/autoedits/prompt/prompt-utils.test.ts, vscode/src/autoedits/prompt/prompt-utils.ts, vscode/src/autoedits/prompt/short-term-diff-prompt-strategy.test.ts, vscode/src/autoedits/prompt/short-term-diff-prompt-strategy.ts, vscode/src/autoedits/prompt/test-helper.ts
- Prepping for the analytics logger integration.  
- No functional changes included.  
- Decouples the `codeToReplaceData` computation from `getPromptForModelType`. This is necessary because `codeToReplaceData` will be used to create the analytics logger request early in the autoedits generation code path. By calculating it independently, we can have it ready earlier in the pipeline.
CI + updated unit tests.
=> chore(audoedit): decouple `codeToReplaceData` from `getPromptForModelType`

vscode/src/chat/chat-view/ChatsController.ts, vscode/test/e2e/chat-history.test.ts
[Linear Issue
](https://linear.app/sourcegraph/issue/QA-216/jetbrains-clicking-on-delete-button-does-nothing-in-first-attempt-for)
Previously, whenever a user deleted a chat, disposeChat would call clearAndRestartSession(), which in turn triggered saveSession(). This saved the just-deleted chat back into local storage, negating the deletion.
Introduce a skipSave boolean to conditionally skip the clearAndRestartSession() flow during deletion. If skipSave is true (e.g., for a deletion), clearAndRestartSession() is not called. This prevents the race condition of re-saving an already-deleted chat.
1.	Avoid Conflicts – If the user explicitly wants to remove a chat, we no longer re-create or re-save the session.
2.	Maintain Clean State – Normal operations (skipSave = false) still clear and …
=> Adding fixing save chat session overwriting

.github/workflows/vscode-insiders-release.yml
The BigQuery insertion step was giving nothing in the version tag because it attempted to access `steps.create_release.outputs.version_tag` before the release step had run, resulting in missing version data in our bundle size tracking.
Reordered the GitHub Actions workflow steps to ensure the BigQuery insertion happens after the release step, when the version tag is available.
- Moved the "Insert data into BigQuery" step to execute after the `create_release` step
- No changes to the logic or data structure, just workflow ordering
- Checked github actions
=> fix: Move BigQuery insertion after release step

vscode/src/chat/agentic/CodyChatAgent.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/chat-view/handlers/ChatHandler.ts, vscode/src/chat/chat-view/handlers/DeepCodyHandler.ts, vscode/src/chat/chat-view/handlers/interfaces.ts, vscode/src/chat/chat-view/handlers/registry.ts
The statusCallback method was removed by #6469 by accident. This PR is to add the callback function to the Deep Cody Handler by passing delegate to computeContext so that the context agent (deep cody) can send its status update to the webview.
The changes in https://github.com/sourcegraph/cody/pull/6451 should be working again:
https://github.com/user-attachments/assets/41b558fb-01fe-4a0d-a8bf-8d133bc01a1c
Added `delegate.postMessageInProgress({ speaker: 'assistant', model: this.modelId })` before `streamAssistantResponse` is invoked so that the context would show up in the UI before we stream the response to webview:
https://github.com/user-attachments/assets/98cdd891-cc36-42a8-87e7-38b813f13c07
=> fix(context-agent): add status callbacks back 

agent/src/cli/command-bench/command-bench.ts, agent/src/cli/command-bench/strategy-chat-context-types.ts, agent/src/cli/command-bench/strategy-chat-nls.ts
This PR adds an NLS strategy to Cody bench that uses the `nlsSearchQuery` GraphQL endpoint. This lets us run NLS evals against the actual method used to power omnibox. Previously, we were using the `getCodyContext` endpoint and adjusting it to use `patterntype:nls`. So it resolves an important piece of tech debt in our evals.
Addresses SPLF-757
Updated `cody-leaderboard` to use this new strategy, reran evals, and results looked as expected.
I will open a follow-up PR to update `cody-leaderboard` to use the new strategy.
=> Add Cody bench command for NLS

vscode/CHANGELOG.md, vscode/package.json
- **chore/release: Bump package version and update changelog for 1.56**
- **chore/release: Bump package version and update changelog for 1.56**
Tested locally
=> chore/release: Bump package version and update changelog for 1.56

vscode/webviews/chat/cells/contextCell/ContextCell.story.tsx
This change adds new context items and sources to the ContextCell component for steps:
- Adds a new 'openctx' context item with a Linear Issue as the title
- Adds a new 'file' context item with the source set to 'Terminal'
- Updates the existing 'file' context item to have the source set to 'Search'
The context items used in the storybook now reflects the step status correctly.
Run storybook to check out the ContextCell story to see the updated context aligns with the step status:
To start storybook:
```bash
pnpm run -C vscode storybook
```
=> storybook: add context items with sources for steps

.github/workflows/vscode-stable-release.yml
Fixes error in last step of [release workflow](https://github.com/sourcegraph/cody/actions/runs/12587100152/job/35086752028) where we send off slack notifications, I forgot to add $ so the GHA kept failing. 
N/A
=> fix(release): add $ variable invocation

.github/workflows/semgrep.yml
CI has been failing for closed pull request events, fixing that by removing the closed events as this already runs on pre-merge events
- CI 🟢
=> chore(security): Fix closed events for sast scan

vscode/src/chat/chat-view/handlers/SearchHandler.ts
This adds the search param to boost a user's relevant repos. It is only added if the server version supports it (min version 6.0.0 or insiders build).
I did not yet implement the UI to enable/disable boosting, but wanted to get this out ASAP for dogfooding. Will work on the interactions next.
Manual testing of a local build.
=> feat(nls): add relevant repo boost

.github/workflows/generate-changelog.yml
uses devx token when running gh commands
n/a
=> fix(release): add GH_TOKEN for gh command

vscode/webviews/components/UserMenu.story.tsx, vscode/webviews/components/UserMenu.tsx, vscode/webviews/tabs/TabsBar.tsx
CLOSE https://linear.app/sourcegraph/issue/CODY-4607/profile-picture-size-issue-when-clicked-in-the-app
This commit addresses the following changes:
1. In the `UserMenu` component, the user avatar is now constrained to a maximum height of 9 units and the width is set to auto to maintain aspect ratio.
2. In the `TabsBar` component, the user avatar container is now set to full height to ensure proper vertical alignment.
These changes improve the visual appearance and consistency of the user avatar across different UI elements.
Updated story book with problematic image src:
=> fix(vscode): adjust user avatar image size in UserMenu and TabsBar

vscode/src/testutils/mocks.ts
Add some of the missing VS Code mocks to test utils. These are required for the analytics logger integration tests, which I'll add in one of the follow-up PRs.
CI
=> feat(audoedit): update vscode mocks

vscode/src/autoedits/autoedits-config.ts
Makes autoedits config singleton reactive to auth status. This is not enough to make autoedits fully reactive and remove the requirement to reload VS Code, but this part is required for analytics logger integration tests I'll add in one of the follow-up PRs.
CI
=> feat(audoedit): reactive config singleton

vscode/src/completions/context/context-mixer.test.ts, vscode/src/completions/context/context-mixer.ts, vscode/src/completions/get-inline-completions.ts, vscode/src/completions/tracer/traceView.ts
Rename the field name to match the type name.
CI
=> feat(audoedit): rename `logSummary` to `contextSummary` to match the type name

vscode/src/chat/chat-view/handlers/SearchHandler.ts
This commit adds the last piece for
https://linear.app/sourcegraph/issue/SRCH-1455/one-box-telemetry. Now when a message is submitted as search we also record a 'cody.chat-question/executed' event.
The intent (detected and chosen) is part of the submission as well.
I'm not sure if this is correct but I chose to pass the passed 'mentions' as context for the telemetry event, since it's from those mentions that we compute the scope(s) of the search query.
Code inspection
=> Record telemetry when executing search

vscode/src/autoedits/analytics-logger/analytics-logger.test.ts, vscode/src/autoedits/analytics-logger/analytics-logger.ts, vscode/src/autoedits/analytics-logger/suggestion-id-registry.ts
- Introduces a new `postProcessed` state to the autoedit suggestions lifecycle. This intermediate step is necessary for the agent API. Instead of transitioning the request directly to the `suggested` state, we first save the request's metadata in the analytics logger cache. This ensures the agent can access it using only the request ID during `unstable_handleDidShowCompletionItem` calls.
- Adds the `isRead` field to the autoedits events metadata, which is crucial for calculating CAR and other metrics.
- Updates unit tests to cover changes introduced in the PR.
- Exposes `autoeditIdRegistry` as a singleton, which will be used in the autoedits provider integration tests in one of the follow-up PRs.
CI + updated unit tests.
=> feat(audoedit): add `isRead` field and `postProcessed` state to the analytics logger

vscode/src/autoedits/analytics-logger/analytics-logger.test.ts, vscode/src/autoedits/analytics-logger/analytics-logger.ts, vscode/src/autoedits/analytics-logger/suggestion-id-registry.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/renderer/inline-manager.ts, vscode/src/autoedits/renderer/manager.test.ts, vscode/src/autoedits/renderer/manager.ts, vscode/src/autoedits/utils.ts
- Integrates the analytics logger with the autoedits provider. Now the autoedits feature should emit analytics events similar to autocomplete: `suggested`/`accepted`/`invalidTransitionTo${state}`
- `discarded` events will be integrated in a follow up.
- Prepares for future integration with the agent API, where editors will notify the autoedits provider that they rendered the suggestion. We use the same approach as in autocomplete for that. We expose the `unstable_handleDidShowCompletionItem`, which accepts the suggestion ID, which is enough for us to handle the rest of the logic. This requires the agent to know only about the ID of the current suggestion and nothing about its internal state.
- Removes `activeEdit` from the `manager` and instead relies solely on the suggestion ID. The …
=> feat(audoedit): integrate analytics logger with autoedits provider

agent/src/AgentWorkspaceConfiguration.test.ts, jetbrains/src/test/kotlin/com/sourcegraph/config/ConfigUtilTest.kt, lib/shared/src/configuration.ts, vscode/package.json, vscode/src/completions/create-inline-completion-item-provider.ts, vscode/src/configuration.test.ts, vscode/src/configuration.ts, vscode/src/testutils/mocks.ts, vscode/test/e2e/auto-edits.test.ts, web/lib/agent/agent.client.ts
With `auto-edits` being a replacement of `autocomplete`. Based on the [suggestion](https://sourcegraph.slack.com/archives/C07F8LLKE06/p1735327930973269?thread_ts=1735292806.801459&cid=C07F8LLKE06) The, PR adds a `drop-down` for the users to choose between the "autocomplete", "auto-edits" and "Off".
The PR deprecates the 2 earlier `configurations`:
1. `cody.autocomplete.enabled`
2. `cody.experimental.autoedits.enabled`
And introduces the `cody.suggestions.mode: 'autocomplete' | 'auto-edits' | 'off' ` for the users to choose from.
Green CI
Also tested the agent test cases with the new config. Agent takes the default values from `vscode/package.json` which uses `autocomplete` as default for suggestion mode and it works.
=> suggestion mode UI

vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx
The API supports searching for file paths and returns the results correctly, but the client was filtering them out of the results. This removes that filter.
Fixes SRCH-1514
=> fix: do not filter out path-only results

lib/shared/src/chat/transcript/messages.ts, lib/shared/src/telemetry-v2/events/chat-question.ts, vscode/src/chat/agentic/DeepCody.ts, vscode/src/chat/chat-view/ChatBuilder.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/chat-view/handlers/DeepCodyHandler.ts, vscode/webviews/chat/Transcript.tsx, vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx, vscode/webviews/chat/cells/messageCell/human/editor/ToolboxButton.tsx
- Adds a `selectedAgent` property to the `ChatController` and `ChatBuilder` to track the currently selected agent
- Updates the `handleUserMessage` method in `ChatController` to use the selected agent for the human message
- Adds the `chatAgent` property to the `SharedProperties` in the `chat-question` telemetry event
- Updates the `ToolboxButton` component to record telemetry events for opening, updating, and closing the toolbox settings
Example Events:
```
█ telemetry-v2 recordEvent: cody.toolboxSettings/opened: {
"parameters": {
"version": 0,
"billingMetadata": {
"product": "cody",
"category": "billable"
}
},
"timestamp": "2025-01-07T23:07:15.949Z"
}
█ telemetry-v2 recordEvent: cody.toolboxSettings/updated: {
"parameters": {
"version": 0,
"metadata": [
{
"key": "agent",
"value": 0
},
{ …
```
=> feat(deep-cody): add selected agent tracking and update telemetry

vscode/src/autoedits/adapters/cody-gateway.ts, vscode/src/autoedits/adapters/create-adapter.ts, vscode/src/autoedits/adapters/fireworks.ts, vscode/src/autoedits/adapters/openai.ts, vscode/src/autoedits/adapters/sourcegraph-chat.ts, vscode/src/autoedits/adapters/sourcegraph-completions.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/filter-prediction-edits.ts, vscode/src/autoedits/output-channel-logger.ts, vscode/src/autoedits/prompt/default-prompt-strategy.ts, vscode/src/autoedits/prompt/prompt-utils.ts, vscode/src/autoedits/prompt/short-term-diff-prompt-strategy.ts, vscode/src/autoedits/renderer/inline-manager.ts, vscode/src/autoedits/renderer/manager.ts, vscode/src/completions/context/context-mixer.ts, vscode/src/completions/context/retrievers/recent-user-actions/diagnostics-retriever.ts, vscode/src/completions/context/retrievers/recent-user-actions/recent-edits-retriever.ts, vscode/src/completions/context/retrievers/recent-user-actions/recent-view-port.ts, vscode/src/completions/output-channel-logger.ts
Clean the output logger for `auto-edits`:
1. Most of the debugging calls (to check where the `auto-edits` might break are enabled only if verbose debugging true. 
2. Large logs like `prompt` are shorted similar to autocomplete prompt logs.
**Logs when verbose enabled for a single `auto-edits` request.**
**Logs without verbose enabled for a single `auto-edits` request.** 
- Only response is logged
1. Trigger the auto-edits request
2. See the output logs by toggling `cody.debug.version` flag
=> feat(auto-edits): clean auto-edits output channel

vscode/src/autoedits/analytics-logger/analytics-logger.ts, vscode/src/autoedits/autoedits-provider.ts
- Improve formatting of some of the existing autoedits output channel logs.
- Adds output channel logs for key `suggested` and accepted` analytics events.
CI + manually observe the autoedit output channel logs. Now, it should output logs for the `suggested` and `accepted` analytics events.
=> feat(audoedit): improve output channel logs

agent/src/agent.ts
Fixes https://linear.app/sourcegraph/issue/QA-220/jetbrains-clicking-cancel-instead-of-authorize-and-navigating-back-to#comment-a0acf5cb
This fixes regression introduced by https://github.com/sourcegraph/cody/pull/6365.
In fact that PR fixed a bug we had in the codebase forever (`registerAuthenticatedRequest` was allowing calls which were not authorised but just `pending`). But it surfaced problem in other place - `webview/receiveMessageStringEncoded` is used also for unauthorised requests like this:
```json
{
"command": "recordEvent",
"feature":"cody.webview.auth",
"action":"simplifiedSignIngithubClick"
}
```
1. Have Cody plugin installed in your JB editor
2. Click on Sign in with Google/Github/Gitlab account
3. User will be redirected to Web browser 
4. Click on "Cancel" button from …
=> Fix not working authorisation actions after previous one was cancelled

vscode/src/autoedits/renderer/decorators/default-decorator.ts, vscode/src/autoedits/renderer/decorators/utils.test.ts, vscode/src/autoedits/renderer/decorators/utils.ts
closes https://linear.app/sourcegraph/issue/CODY-4609/address-overlapping-decorations-with-proposed-css-solutions
Fixes an issue where our absolutely positioned decorations can conflict with another decoration (most likely GitLens)
- Manually triggering an AutoEdit on lines that have a GitLens blame decoration attached
- Ensuring that this still looks as expected in different color themes
=> fix(autoedit): Ensure suffix decorations do not visually interfere with other decorations

jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt, lib/shared/src/configuration/environment.ts, vscode/CHANGELOG.md, vscode/src/net/DelegatingAgent.test.ts, vscode/src/net/DelegatingAgent.ts, vscode/src/services/NetworkDiagnostics.ts
Before JetBrains would pass proxy settings to the agent using HTTP_PROXY and HTTPS_PROXY. However these settings would not allow creating of a "proxyless" http agent since they can be used directly by node libraries. Instead now settings are passed under the CODY_NODE_DEFAULT_PROXY (which falls back to HTTP_PROXY and HTTPS_PROXY).
In addition there's a new CODY_NODE_NO_PROXY environment variable that mirrors the NO_PROXY node environment variable. This now allows ignoring of proxy settings for particular endpoints.
Lastly, before the NetworkDiagnostics would output extremely verbose logging. Including error logs on cancelled requests. The logging could also potentially leave dangling requests/sockets as event handlers weren't properly cleaned up. By moving to a weak-map for timing events …
=> Network: respect NO_PROXY settings

vscode/src/context/openctx/codeSearch.ts, vscode/webviews/chat/Transcript.tsx, vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx
This commit adds logic to remove the search result context chip when the query is resubmitted.
We can only implement this for the penultimate input because we only have a reference to the last input. That suffices however
because when editing a message earlier in the thread, all the following messages are cleared anyway.
Fixes https://linear.app/sourcegraph/issue/PROD-421/previous-context-remains-in-follow-up-chatbox-after-resubmitting-query
Manually tested locally in vscode. I created a chat with multiple messages and edited the first, middle and last one. In all cases the input was cleared.
=> fix: Remove search context chip on resubmission

vscode/src/repository/repo-name-resolver.ts
Returning an empty list on error doesn't resolve promise. Tested on both Cody Web demo and VS Code.
- cd web
- pnpm dev
- visit localhost:5777
- execute `@web/cody search` which should trigger search intent
- the response should not stuck at loading and resolve into no results.
Test the same on VS Code.
=> Fix Cody Web Search

vscode/src/chat/agentic/ToolboxManager.ts, vscode/webviews/chat/Transcript.tsx, vscode/webviews/chat/cells/contextCell/ContextCell.tsx, vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx, vscode/webviews/chat/cells/messageCell/human/editor/ToolboxButton.tsx
Updates the context cell component to be opened by default for Deep Cody instead of just the first 2 messages,  as we now run Deep Cody on all messages.
Also some minor UI updates.
The context cell is defaulted to be opened on all messages when it first loaded for Deep Cody:
Fixed drop shadow on light theme issue:
=> fix(webview): update context cell for deep cody

lib/shared/src/models/client.ts, lib/shared/src/sourcegraph-api/errors.ts, lib/shared/src/telemetry-v2/events/chat-question.ts, vscode/src/chat/agentic/DeepCodyRateLimiter.test.ts, vscode/src/chat/agentic/DeepCodyRateLimiter.ts, vscode/src/chat/agentic/ToolboxManager.ts, vscode/src/chat/chat-view/handlers/DeepCodyHandler.ts, vscode/webviews/chat/ErrorItem.tsx, vscode/webviews/chat/cells/contextCell/ContextCell.tsx, vscode/webviews/components/FileLink.tsx
CLOSE https://linear.app/sourcegraph/issue/CODY-4638/change-the-daily-hard-limit-to-200
- Updates the rate limit error message in the DeepCodyRateLimiter class to use 'Agentic Chat' instead of 'Deep Cody'.
- This change increases the Deep Cody rate limit multiplier from 2 to 4 when the feature flag is enabled. This will allow more requests to be processed for Deep Cody (200 max), improving the overall user experience.
- Remove Deep Cody client model as we have moved it out of the Model dropdown.
Green CI - No additional testing required as this is a configuration change. All current unit tests should continue to pass.
=> feat(webview): replace Deep Cody with Agentic Chat

lib/shared/src/sourcegraph-api/errors.ts, vscode/src/chat/agentic/DeepCodyRateLimiter.ts
update rate limit telemetry event to billable
none - event name change
=> fix(agentic chat): update rate limit telemetry event to billable

vscode/src/autoedits/renderer/inline-manager.ts, vscode/src/autoedits/renderer/manager.ts, vscode/src/autoedits/test-helpers.ts, vscode/src/completions/inline-completion-item-provider.ts, vscode/src/completions/is-completion-visible.ts
- Reuses the logic we have for autocomplete that verifies that completion is still visible based on the latest cursor position in the active text editor.
- CI
- Check the autoedits output channel logs (added in [this PR](https://github.com/sourcegraph/cody/pull/6551)) for the completions. Generate multiple suggestions rendered as inline completion items and dismiss them by typing forward a different text. Depending on the time each completion was visible, the suggested event should be emitted with different `isRead` values.
- TODO for the follow-up: implement integration tests similar to the one [we have for autocomplete](https://github.com/sourcegraph/cody/blob/main/vscode/src/completions/inline-completion-item-provider.test.ts#L464).
- [CODY-4621: Tests: implement tests for the timer …
=> feat(audoedit): check if suggestion is still visible before marking as read

vscode/CHANGELOG.md, vscode/package.json
Version bump and changelog update for the vscode-1.58 stable release.
CI
=> chore/release: Bump package version and update changelog for 1.58

vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx, vscode/webviews/components/codeSnippet/CodeSnippet.tsx
When a follow up query to a search result was submitted we've disabled
the checkboxes of the previous search result because changing the
selection wouldn't impact the already submitted follow up query (but
also from an implementation perspective we wouldn't actually be able to
target the follow up input).
But because we store which results have been selected in memory only,
rerendering the search results would show all checkboxes again as
selected (albeit disabled).
This might be confusing to the user.
We would have to persist the UI state somewhere/somehow but there is no
good place for this atm. So to (hopefully) reduce the confusion we
simply hide the checkboxes when the user cannot interact with the search
results anymore.
Fixes …
=> fix: Hide search result checkboxes instead of disabling them

vscode/src/autoedits/create-autoedits-provider.ts
E2E tests are failing on `main` right now since https://github.com/sourcegraph/cody/pull/6463
E2E tests pass locally and in CI
=> fix(autoedits): Fix E2E tests on main

agent/src/cli/command-bench/strategy-chat-nls.ts
For NLS search, we pass the user's query string through `content:"..."` to avoid interpreting predicates, ANDs, and ORs as search syntax. This PR updates the NLS bench strategy to do the same.
Reran evals and checked results didn't change.
=> Pass query as 'content' in NLS bench

.github/PULL_REQUEST_TEMPLATE.md
This section of the PR template isn't used by any tools. In practice people don't fill it out and it just contributes to noise in the git log.
GitHub template only change.
=> chore/release: Remove the changelog section from the PR template.

vscode/src/autoedits/renderer/manager.ts
Fixes an issues in the conflicting decoration when the tab won't work on conflicting decorations with edit command.
This happens because although the `decorator` is null in this case but `await vscode.commands.executeCommand('setContext', 'cody.supersuggest.active', true) ` was still set, which waits for dismiss unless `tab` doesn't work.
Closes https://linear.app/sourcegraph/issue/CODY-4655/fix-tab-doesnt-work-when-using-auto-edits-in-conflicting-decorations
1. Do a fix command in the editor
2. Try to make `auto-edits` completions from the `auto-edits`
3. Although the decorations won't be visible, but the tab won't work without this fix.
=> feat(auto-edits): fix tab not working when decorations are triggered on conflicting decorations

vscode/src/autoedits/renderer/manager.ts
WIP. 
Fix the suffix duplication happening on inline completion acceptance.
repro the issue from the cody-chat-eval https://github.com/sourcegraph/cody-chat-eval/blob/main/code-matching-eval/edits_experiments/examples/renderer-testing-examples/suffix-duplication-issue.ts
=> feat(auto-edits): fix the suffix duplication on inline accept

jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentClient.kt
Fixes https://linear.app/sourcegraph/issue/QA-265
Improves https://linear.app/sourcegraph/issue/CODY-4648
JetBrains can now properly show error and info messages from agent.
1. Open Cody
2. Make sure no file is opened
3. Using @ mention attach some file to the prompt without opening it
4. Run document command
5. Error message should appear in the ballon window as on screenshot
=> Implement showWindowsMessage in JetBrains

agent/src/cli/command-bench/command-bench.ts
Polly often randomly fails on requests with no clear error even if passthrough mode is enabled. Since we don't want it enabled for context evals anyway, it's probably better to disable it outright.
Running bench with a larger eval set like DS1000 for context now works without errors.
=> Bench: add option to disable Polly

vscode/src/autoedits/analytics-logger/analytics-logger.test.ts, vscode/src/autoedits/analytics-logger/analytics-logger.ts
- Addressing the feedback from [this review comment](https://github.com/sourcegraph/cody/pull/6430#discussion_r1901015283) by marking `discarded` events as `billable`.
CI + updated unit tests.
=> feat(audoedit): update billing categories

agent/src/cli/command-bench/strategy-chat-nls.ts, vscode/src/chat/chat-view/handlers/SearchHandler.ts, vscode/src/chat/chat-view/handlers/__tests__/SearchHandler.test.ts
In addition to quotes, we also need to escape backslashes in the original query string. This is because in search filters like `content:"..."`, backslashes are used to indicate control sequences.
Added new unit test.
=> NLS: escape backslashes in query string

vscode/src/autoedits/autoedits-provider.test.ts
Adds the test case for the two issues we faced:
1. Tab not working when conflicted with edit command decorations. [Resolves comment](https://github.com/sourcegraph/cody/pull/6581#discussion_r1909965922) - [test cases for PR](https://github.com/sourcegraph/cody/pull/6581)
2. Suffix getting duplicated because in addition to inline acceptance, we were modifying the document again on accept - [[test case for PR](https://github.com/sourcegraph/cody/pull/6583)] 
Added test case
=> feat(auto-edits): add test case for setting context

vscode/src/autoedits/output-channel-logger.ts
- No functional changes
- Removes the redundant `logger` instance from the `AutoEditsOutputChannelLogger` class.
CI
=> chore(audoedit): simplify output channel logger

agent/src/cli/command-bench/strategy-chat-context.ts
I noticed that we call the server to retrieve repo IDs for every example in the eval set when running context evals. This operation takes ~250ms for me whereas the actual context search is ~1s. By caching these results, we can speed up the benchmark by 20%, which is especially noticeable with larger datasets.
Context bench still works and runs faster.
=> bench/context: Cache repo IDs

vscode/src/autoedits/analytics-logger/analytics-logger.ts, vscode/src/autoedits/renderer/decorators/base.ts, vscode/src/autoedits/renderer/decorators/default-decorator.ts, vscode/src/autoedits/renderer/decorators/inline-diff-decorator.ts, vscode/src/autoedits/renderer/manager.ts
Default auto-edits renderer can not render the decorations properly when there are not enough lines in the editor. The PR adds checks if the deocrator can render the decoration properly, and if it cannot do so we don't create any request for it.
[Slack Context](https://sourcegraph.slack.com/archives/C07F8LLKE06/p1736430432651569?thread_ts=1736430399.759019&cid=C07F8LLKE06)
Closes: https://linear.app/sourcegraph/issue/CODY-4656/handle-decorations-when-not-enough-lines-in-the-editor
[Example from cody-chat-eval repo](https://github.com/sourcegraph/cody-chat-eval/blob/main/code-matching-eval/edits_experiments/examples/renderer-testing-examples/not-enough-lines-editor.ts)
Before (partial decoration rendered):
After (decorations will be discarded) - notice discard event on `cody by …
=> feat(auto-edits): fix the partial decoration issue when not enough lines in the editor

vscode/src/chat/agentic/DeepCody.test.ts, vscode/src/chat/agentic/DeepCody.ts
CLOSE https://linear.app/sourcegraph/issue/CODY-4671
Fixes a regression where the agent would mark a context as needed but got filtered out during the validation step
- Simplify the context review logic by directly extracting context names from the response and fetching the full content for the requested files.
- Remove unnecessary callbacks and optimize the context fetching process.
- Add a helper function to check if the response is ready to answer.
Manual testing:
1. Ask in new chat: "how does agentic context work in @_cody_repo" 
2. Add a follow up: "how many loop does deep cody run for the review step?"
Before
Deep Cody requested a file:
But it wasn't included in the final selected context:
After:
=> fix(cody): fix chat context review logic

vscode/webviews/chat/cells/contextCell/ContextCell.tsx, vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx, vscode/webviews/chat/cells/messageCell/human/editor/ToolboxButton.story.tsx, vscode/webviews/chat/cells/messageCell/human/editor/ToolboxButton.tsx
CLOSE https://linear.app/sourcegraph/issue/CODY-4632
Updates the `ToolboxButton` component that provides a UI for managing agent context settings with a more detailed description of the feature.
- Updates toggles for agentic context and terminal access, with appropriate warnings
- Displays the button on all messages
- Debounces the settings update to avoid excessive API calls with the removed save button
- Display button on all messages
- Display button without title text in non-first message
- Hide terminal context on unsupported instance/clients
UI update without feature change - storybook updated.
Hide shell command on unsupported client or instances
The current one doesn't explain what agentic context and terminal context are:
=> refactor(agentic context): update agent context settings

lib/shared/src/experimentation/FeatureFlagProvider.ts, lib/shared/src/sourcegraph-api/errors.ts, vscode/src/chat/chat-view/handlers/DeepCodyHandler.ts
This adds a new feature flag, `AgenticContextSessionLimit,` to limit the usage of agentic context to the first 5 human messages in a chat session, which can be used as a fallback if needed.
This change ensures that we have a fallback plan when the agentic context is causing issues and being used excessively, especially in long-running chat sessions, to optimize performance when needed.
Record events:
- `cody.agentic-chat.sessionLimit:skipped` when query is less than 3 words
- `cody.agentic-chat.sessionLimit:hit` when `AgenticContextSessionLimit` is enabled and the chat messages in current session is over 5 human messages
Manual testing to ensure agentic context is only used for the first 5 human messages when the session limit flag is enabled.
When hit:
=> feat(agentic-context): add feature flag for session usage limit 

vscode/scripts/measure-bundle-size.ts
Do not log this error about GITHUB_ENV: It is not an error when building locally, and the error message has no context.
```
pnpm -C lib/shared build && pnpm build && pnpm -C vscode build 2>&1 | grep GITHUB_ENV
```
This should not mention `GITHUB_ENV`.
=> chore/build: Do not complain about GITHUB_ENV when building locally

vscode/webviews/chat/cells/messageCell/human/editor/ToolboxButton.tsx
Run Cody signed in to s2 and open the Agentic context popover and check "this this tool" appears as simply "this tool":
=> fix/context: Nit, remove duplicate "this" from Agentic context popover

vscode/src/chat/agentic/CodyTool.ts
As discussed with @camdencheek , our search endpoint for context retrieval doesn't support Sourcegraph-style search query. This PR modifies the search examples for the "Search tool" to remove the use of Sourcegraph-style search query.
Ask Cody `Write a unit test for the openExternalAuthUrl function` with agentic context enabled:
Before:  It'd run a code search with `openExternalAuthUrl file:*` as the search query
After: It'd run a code search with `openExternalAuthUrl` as the search query
=> fix(agentic-context): update search tool prompt and examples

vscode/src/autoedits/autoedits-provider.test.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/test-helpers.ts, vscode/src/services/sentry/sentry.ts
- Most changes are whitespace-related; hide them for easier review.
- Wraps the logic inside the autoedit provider's `provideInlineCompletionItems` method in a try-catch block and logs errors to our telemetry backend and Sentry.
- Eases the conditions for filtering out errors on the client by checking for the `sourcegraph.cody-ai` substring in the error stack. We haven't seen any errors in Sentry for the last 90 days, which is suspicious. Let's verify if this condition is still valid and ensure we aren't missing any false positives due to this logic.
- Closes [CODY-4649: Telemetry: integrate with Sentry for error reporting](https://linear.app/sourcegraph/issue/CODY-4649/telemetry-integrate-with-sentry-for-error-reporting)
CI and updated integration tests for the autoedit provider.
=> feat(auto-edit): improve error logging

vscode/src/chat/agentic/ToolboxManager.ts
- Disable agentic context by default as this is an experimental feature that needs to be opt-in
- Use a new storage key for toolbox settings with experimental prefix
1. Build from this branch and confirm the agentic context is disabled by default
2. You can enable it and disable it using the google
=> feat(agentic-context): disable setting by default

lib/shared/src/experimentation/FeatureFlagProvider.ts
https://linear.app/sourcegraph/issue/CODY-4685
Updating the values of the agentic chat feature flags to match launch names.
- Update the 'deep-cody' and 'deep-cody-shell-context' feature flags to 'agentic-chat-experimental' and 'agentic-chat-cli-tool-experimental' respectively
- Rename 'context-agent-use-default-chat-model' to 'agentic-chat-use-default-chat-model'
- Rename 'agentic-context-experimental-session-limit' to 'agentic-chat-experimental-session-limit'
- Add comments to clarify the purpose of the new feature flags
These feature flags are designed for enterprise as these features are accessible without feature flag for dotcom users with pro subscriptions.
=> refactor(agentic-context): rename experimental feature flags

.github/workflows/generate-changelog.yml
Getting closer to a working Changelog Generator.
I've been running the action from this branch, and now it's complaining about common ancestors, which I think requires merging this branch into Main so that it can find common ancestors.
[Here's](https://github.com/sourcegraph/cody/actions/runs/12779368083/job/35623856267#step:5:1011) the latest run
Run the action.
=> Fix: Can actually run the changelog github action

vscode/webviews/chat/Transcript.tsx
closes: https://linear.app/sourcegraph/issue/CODY-4613/non-deterministic-intent-detection
We precompute the intent while the user is typing the input with a 300ms debounce. It is possible that after the last intent detection the user may change the query and submit within 300ms, causing the detected intent to be stale and often different than the intent for the final query. 
This PR fixes that behavior by checking if the query has changed since the last intent detection and ignoring the pre-computed intent in case the query was changed afterwards. 
https://sourcegraph.slack.com/archives/C07EQBRSF35/p1735859984632339
=> Make sure precomputed intent is not stale

vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/chat-view/sourcegraphRemoteFile.ts, vscode/src/chat/protocol.ts, vscode/src/main.ts, vscode/webviews/components/codeSnippet/CodeSnippet.tsx, vscode/webviews/components/codeSnippet/components/FileMatchChildren.tsx, vscode/webviews/components/codeSnippet/components/RepoLink.tsx, vscode/webviews/utils/useFeatureFlags.tsx
closes: https://linear.app/sourcegraph/issue/SRCH-1097/open-in-editor-from-ide
This PR open the remote files listed in the search responses locally in VS Code in readonly mode.
https://www.loom.com/share/e177bb19244247cb99627f13d2f8a8a5
=> Open remote files locally in VSCode

vscode/package.json
Sometimes, auto-edits fail to accept completions when a user has Vim installed and is currently in Vim’s normal mode. This happens because of a [keybinding conflict](https://github.com/VSCodeVim/Vim/blob/master/package.json#L115) between Vim and Cody, resulting in only one command being dispatched dynamically when conflicts occur.
After checking with @olafurpg seems like `Tab` key doesn't do much in the normal mode, and should be fine to disable it by default.
PR with similar change before: https://github.com/sourcegraph/cody/pull/551
Run Auto-Edit with the vim extension, make some document changes and auto-edit should propose related changes. Pressing Tab should accept the suggestion with this.
=> feat(auto-edit): fix problem with vim extension supressing the tab

vscode/package.json
The VS Code Vim plugin supports [several modes](https://github.com/VSCodeVim/Vim/?tab=readme-ov-file#vim-modes), and we probably want to disable the tab key only in normal mode, where code exploration happens. For example, if the user is in visual mode and wants to use `Tab`, we likely don’t want to interfere with auto-edit acceptance.
Let me know if you have any use cases where this isn’t the desired UX!
CI + tested the behavior manually.
=> feat(audo-edit): target vim normal mode only

vscode/src/chat/protocol.ts, vscode/webviews/CodyPanel.tsx, vscode/webviews/components/UserMenu.tsx, vscode/webviews/tabs/TabsBar.tsx
CLOSE https://linear.app/sourcegraph/issue/CODY-4657/profile-menu-add-upgrade-to-pro-and-explore-enterprise-plans-cta-if
- Adds an "Upgrade to Pro" CTA in the user menu for non-Pro users
- Adds an "Upgrade to Enterprise" CTA in the user menu for Pro users when Teams upgrade CTA is enabled
- Adds telemetry recording for the upgrade CTAs
Require the workspace team feature flag.
Check if the logo shows up for PLG users.
Enterprise users shouldn't see it.
=> feat(webview): add Upgrade to Pro & Enterprise plan to user menu

vscode/src/chat/protocol.ts, vscode/webviews/CodyPanel.tsx, vscode/webviews/components/UserMenu.tsx, vscode/webviews/tabs/TabsBar.tsx
CLOSE  https://linear.app/sourcegraph/issue/CODY-4658/switch-account-add-create-workspace-cta-if-they-are-on-plg
- Adds a Sourcegraph Teams upgrade CTA to the user menu and tabs bar
- The CTA is conditionally rendered based on the `isTeamsUpgradeCtaEnabled` prop
- The CTA provides a link to create a Sourcegraph workspace
1. Verify the CTA is displayed when `isTeamsUpgradeCtaEnabled` is true
2. Verify the CTA is not displayed when `isTeamsUpgradeCtaEnabled` is false
3. Verify clicking the "Create a workspace" button navigates to the correct URL
=> feat(webview): add Sourcegraph Workspaces upgrade CTA

.github/workflows/generate-changelog.yml
- **Moved the version update to happen _after_ changelog**
- **misc: remove extra debugging logs**
Finally!!! :party:
I've run the [action](https://github.com/sourcegraph/cody/actions/runs/12797290344/job/35678849540) and it's successfully generated the [changelog](https://github.com/sourcegraph/cody/pull/6658) and version update in a single PR
=> Fix: Changelog generator action frfr no cap

vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx
CLOSE https://linear.app/sourcegraph/issue/CODY-469
- Moved the `OpenInNewEditorAction` component to be displayed after the `ToolboxButton` component
- This ensures the open in new editor action is displayed after the toolbox button, maintaining the current layout and user experience
Ensure the brain icon is showing up on the left side of the open in editor btn.
=> fix(webview): reorder human editor menu buttons

.github/workflows/generate-changelog.yml
- **Moved the version update to happen _after_ changelog**
- **misc: remove extra debugging logs**
Finally!!! :party:
I've run the
[action](https://github.com/sourcegraph/cody/actions/runs/12797290344/job/35678849540) and it's successfully generated the
[changelog](https://github.com/sourcegraph/cody/pull/6658) and version update in a single PR
=> Fix: Changelog generator action frfr no cap (#6659) [cherry-pick]

vscode/CHANGELOG.md, vscode/package.json
Version bump and changelog update for the vscode-1.60 stable release.
CI
=> chore/release: Bump package version and update changelog for 1.60

lib/shared/src/prompt/__tests__/prompt-mixin.test.ts, lib/shared/src/prompt/prompt-mixin.test.ts, lib/shared/src/prompt/prompt-mixin.ts
- Rename the`PromptMixin.buildPrompt` method to `PromptMixin.join` method
- Refactor the `PromptMixin.mixedMessage` method to use `PromptMixin.join` method directly and simplify the logic
Check output log. Added new unit tests.
=> fix(agentic-chat): fix prompt-mixin for deep-cody agent

vscode/webviews/AuthPage.tsx
When you last logged into dot com, we pre-fill the enterprise login URL with https://sourcegraph.com. This is contrary to our efforts to get Enterprise users to log into the right endpoint.
You can still log in to dot com using the handy enterprise login method/hack. We just won't prefill that URL.
Fixes CODY-4534.
1. Sign out of all your accounts.
2. Sign in to dotcom. This works with social login buttons or signing into https://sourcegraph.com as an "Enterprise" URL.
3. Go to https://sourcegraph.com/user/settings/tokens and delete the token you are using.
4. Reload VSCode, or wait for it to log you out.
5. Go to sign in to an enterprise account. Verify that the URL field has a placeholder like https://instance. and NOT https://sourcegraph.com
6. Sign in to s2.
7. Go to …
=> fix/accounts: Do not prefill the dotcom URL in the Enterprise login field

vscode/src/chat/initialContext.ts, vscode/src/repository/remoteRepos.ts, vscode/test/e2e/chat-atFile.test.ts
Fixes https://linear.app/sourcegraph/issue/CODY-3906/agent-allow-use-of-existing-fallback-that-looks-at-gitconfig-to-get
Fixes https://linear.app/sourcegraph/issue/CODY-4140/jetbrains-cody-current-repo-no-longer-available-as-context
I think that was a simple mistake introduced by https://linear.app/sourcegraph/issue/CODY-3906/agent-allow-use-of-existing-fallback-that-looks-at-gitconfig-to-get
If I remove code you can see in the diff it simply works.
All git based methods themselves check if they can be executed so this safeguard was not adding any value there from what I can see.
1. Open jetbrains with cody repo and login to sg02 
2. `Current Repository` should be visible in the chat context by default
3. Remove `Current Repository`
4. Type `@` and then Start typing `Current Repository` - …
=> Fix missing current repo context in jetbrains

lib/shared/src/misc/rpc/rpc.ts, lib/shared/src/prompt/prompt-mixin.test.ts, lib/shared/src/prompt/prompt-mixin.ts, vscode/src/chat/agentic/DeepCody.ts, vscode/src/chat/initialContext.ts, vscode/src/configuration.ts, vscode/src/repository/remoteRepos.ts, vscode/test/e2e/chat-atFile.test.ts, vscode/webviews/AuthPage.tsx, vscode/webviews/CodyPanel.tsx, vscode/webviews/chat/cells/agenticCell/ApprovalCell.tsx, vscode/webviews/components/Notices.story.tsx, vscode/webviews/components/Notices.tsx
context: https://sourcegraph.slack.com/archives/C0847FJ0A73/p1736883217956529
- Simplified the title of the context retrieval step from "Retrieving additional context" to "Retrieving context"
- Updated the confirmation message for the Terminal tool from "Run command to retrieve context?" to "Allow commands to retrieve context?" to provide clearer instructions to the user
Check pnpm -C vscode storybook
=> refactor(agentic-context): update status messaging

vscode/src/autoedits/autoedit-onboarding.ts, vscode/src/autoedits/create-autoedits-provider.ts, vscode/test/e2e/auto-edits.test.ts
Fix the feature name from `Auto-Edit` to `Auto-edit` as per [release doc](https://www.notion.so/sourcegraph/FAQ-6-0-Release-Jan-29-2024-159a8e112658804ca222f7073427ce10#159a8e112658800aa9aad14bc11fa697)
no functional change
=> fix(auto-edit): fix the feature name

lib/shared/src/completions/types.ts, lib/shared/src/prompt/prompt-string.ts, vscode/src/autoedits/analytics-logger/analytics-logger.test.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/prompt/base.ts, vscode/src/autoedits/prompt/default-prompt-strategy.test.ts, vscode/src/autoedits/prompt/default-prompt-strategy.ts, vscode/src/autoedits/prompt/prompt-utils.test.ts, vscode/src/autoedits/prompt/prompt-utils.ts, vscode/src/autoedits/prompt/short-term-diff-prompt-strategy.test.ts, vscode/src/autoedits/prompt/short-term-diff-prompt-strategy.ts, vscode/src/autoedits/prompt/test-helper.ts, vscode/src/autoedits/renderer/manager.test.ts, vscode/src/autoedits/renderer/mock-renderer.test.ts, vscode/src/autoedits/shrink-prediction.test.ts
- This addresses the review comment [here](https://github.com/sourcegraph/cody/pull/6474#discussion_r1898337793) by hiding prompt components from the autoedit provider. The `CodeToReplaceData` object is now created independently and stores raw string values. For prompt construction, these string values are wrapped in a `PromptString`, like we do for the `DocumentContext`.
- Closes [CODY-4596: Hide prompt component management logic from the autoedits provider](https://linear.app/sourcegraph/issue/CODY-4596/hide-prompt-component-management-logic-from-the-autoedits-provider)
CI
=> chore(audo-edit): encapsulate prompt components

vscode/src/completions/inline-completion-item-provider.test.ts, vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.story.tsx, vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx
Previously, the storybook was failing because the `models` prop can be `undefined`.
Storybook-only
=> fix NonEmptyFirstMessage storybook

vscode/webviews/chat/components/QuickStart.tsx, vscode/webviews/chat/components/WelcomeFooter.module.css, vscode/webviews/chat/components/WelcomeFooter.tsx
This PR adds the quick start cheatsheet to the footer of the welcome area.
https://github.com/user-attachments/assets/eda30680-3162-40a2-ba10-c9db3849f050
Things left to do:
- Change its position/behaviour depending on [what's decided here](https://sourcegraph.slack.com/archives/C07EQBRSF35/p1736941478732779)
- Any tidyups/bugs/undesired behaviour
- UI should remember preference of expanded/collapsed behaviour (@thenamankumar if you could help here that would be great)
- Content check/update (@rrhyne / @camdencheek)
- Needs to be thoroughly reviewed on sg build and checked in context in the browser
_**Note: This is mostly generated code. Please check carefully!**_
Checked locally, manually.
=> feat: omnibox cheatsheet

lib/shared/src/telemetry-v2/events/chat-question.ts, vscode/src/chat/chat-view/ChatController.ts
Contributes to [SPLF-330](https://linear.app/sourcegraph/issue/SPLF-330/make-sure-the-collected-telemetry-is-usable-for-fine-tuning-the-model).
More context [in this Slack thread](https://sourcegraph.slack.com/archives/CN4FC7XT4/p1737021858607509).
I'm a bit worried about the mapping from intent names to numeric constants remaining stable as during a larger refactoring this can easily get changed. One way I'm thinking of mitigating it is to have the same data emitted through private metadata which we can see on S2, meaning it's easy to check. I'm open to any better ideas though.
Telemetry metadata contains intent scores in the expected format (`detectedIntentScores.{intent}`).
=> fix/intent: Insert detected intent scores into telemetry event metadata in acceptable format

.github/workflows/generate-changelog.yml, vscode/CHANGELOG.md
This works by using the title as the changelog entry instead.
We cannot use the compact mode version with this feature enabled, it
fails to find a `section` `formatEntry` command and exits before the
changelog is generated.
Also updated the changelog marker since it's different now?
I ran the [action](https://github.com/sourcegraph/cody/actions/runs/12799005063/job/35684227555) which produced this [PR](https://github.com/sourcegraph/cody/pull/6668)
=> fix: changelog generator with titles instead of changelog entries

vscode/webviews/chat/ErrorItem.module.css, vscode/webviews/chat/ErrorItem.tsx
[Linear issue 
](https://linear.app/sourcegraph/issue/QA-184/jetbrains-go-pro-label-doesnt-apply-in-each-tab-for-rate-limit)
Currently the UI for displaying the rate limit being exceeded is bad because it shows up in the wrong place. While I am not "stopping" the user from clicking on new chat I think showing the go pro banner at the right place and then making every chat error out is a good enough mechanism to remind people to go pro. 
Positioning Fixes:
1. Added relative positioning to the error banner
2. Correctly aligned the banner to appear in the right place for both VS Code and JetBrains interfaces
Styling Improvements:
1. Added consistent margins (12px vertical, 0px horizontal) to align with chat messages
2. Added subtle rounded corners and shadow for better visual hierarchy …
=> Fixing Css logic to correctly show rate limit banners in the correct place

vscode/webviews/components/codeSnippet/components/CodeExcerpt.module.css, vscode/webviews/components/codeSnippet/components/CodeExcerpt.tsx, vscode/webviews/components/codeSnippet/components/FileMatchChildren.tsx
Resolves the bug where line numbers are showing a pointer cursor even though the line is not clickable.
Issue:
https://linear.app/sourcegraph/issue/SRCH-1521/pointer-cursor-is-dispalying-on-code-search-results-lines
Loom
https://www.loom.com/share/1259953282ed4a96aec5bed69dda2126
* Manually test UI for the following conditions:
* When the cursor is over the line of code, the edit cursor is displayed
* When the cursor is over the line number the pointer cursor is displayed
=> Fix pointer cursor displaying on line numbers in search results

vscode/webviews/components/codeSnippet/CodeSnippet.tsx
Currently, even though only the line number and file path are interactable, we log an event when clicking the search results text. This fixes it so we only log when you actually open a file.
Fixes CODY-4708
Clicked the result, ensured there was no log unless I clicked a line number or the file path.
=> fix: only log on open file

vscode/webviews/components/codeSnippet/CodeSnippet.tsx
It's not immediately obvious that the line numbers are links, so users often end up opening the search result by clicking the file path. However, the file path doesn't currently link to a line number, just the beginning of the file. This modifies the link to point to the first line in the first chunk shown. 
Related [feedback thread](https://sourcegraph.slack.com/archives/C08754AFLMB/p1737387320315939)
Quick manual test that clicking the file path navigates the user to a specific line (though it's not highlighted, which isn't ideal, but unrelated and I don't see a super quick way to fix that)
=> omnibox: link file path to the line of the first match

.github/workflows/test.yml, jetbrains/build.gradle.kts, jetbrains/gradle.properties
New IntelliJ EAP 2025 is out! 
https://blog.jetbrains.com/idea/2025/01/intellij-idea-2025-1-eap/
This PR upgrades supported IJ platform version to 2025.1.
IJ 2025 is supposed to fix code lenses on remote, so beside full QA we should test that specifically.
One can run remote IJ locally easily, by executing in the `jetbrains` directory:
`./gradlew customRunIde -PsplitMode=true -PplatformRuntimeVersion=251.14649.49`
It also can be done by downloading and installing new EAP and then installing the Cody plugin normally.
=> chore/build: Bump IntelliJ supported platform version to 251

vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx
This removes the external "code search" link because we cannot link the user directly to the same search results in the code search UI, so it currently just links them to an empty code search page, which is not very useful.
[Related slack thread](https://sourcegraph.slack.com/archives/C08754AFLMB/p1737387320315939)
Quick video of the UI without the button:
=> omnibox: remove code search external link

vscode/src/completions/output-channel-logger.ts, vscode/src/external-services.ts
Use the correct feature label in the output channel for completions API requests.
CI + manually review the output channel logs:
1. Completions API requests from chat should be labeled with the `Completions` prefix.
2. Completions API requests from autocomplete should be labeled with the `Autocomplete` prefix.
=> chore(autocomplete): use the correct output channel label

vscode/webviews/chat/components/QuickStart.tsx
Fixes [SRCH-1554
](https://github.com/sourcegraph/cody/pull/6711)
This PR adds z-index to the quick start modal to ensure it stays above all other elements.
Uses Tailwind's z-index scaling: https://tailwindcss.com/docs/z-index
Visually tested.
=> fix: add z-index to quick start modal

vscode/src/autoedits/renderer/decorators/blockify.test.ts, vscode/src/autoedits/renderer/decorators/blockify.ts
We're not actively using this range logic _yet_ AFAIK, but we will be using it when we need to "git" highlight images to show added ranges.
This logic was broken for Tab based indentation, so I've updated it and improved the tests a lot so this is a lot more robust
Unit tests pass
=> feat(autoedit): Fix blockify range logic for tab indentation

vscode/webviews/chat/cells/messageCell/human/editor/ToolboxButton.tsx
Follow ups on #6596.
As a user I realized that working on a standard `13inch macbook` I was very commonly using the `Cody Chat` feature with a width that resulted in the exclusion of a feature I would have used. In effect the feature was hidden without me using an external monitor.
1. Change `popover` width
2. Fix over-use of `left margin`
3. Add a `space` between sentences
_Wider width of side bar_
_Narrower width of side bar - **Notice that the switch on the right gets cuts off**_
_Wider width of side bar_
_Narrower width of side bar_
Storybook:
```
pnpm -C vscode storybook
open http://localhost:6007/?path=/story/cody-toolboxbutton--default
```
Interact with agentic context popup in the chat sidebar at different widths.
=> fix/agentic-context: Reveal hidden switch in context popup

vscode/src/net/DelegatingAgent.test.ts
Specifying `.example.com` instead of `*.example.com` is a [valid way of specifying a wildcard](https://www.browserstack.com/guide/no_proxy-environment-variable#:~:text=.example.com%3A%20Excludes%20any%20subdomains%20of%20example.com%20(wildcard).), but this is not currently tested by `DelegatingAgent`.
* Adds unit tests only
=> Add NO_PROXY test that ensures dot prefixes are considered a wildcard

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/AuthenticationError.kt, agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Constants.kt, agent/scripts/simple-external-auth-provider.py, lib/shared/src/auth/types.ts, lib/shared/src/configuration.ts, lib/shared/src/configuration/auth-resolver.test.ts, lib/shared/src/configuration/auth-resolver.ts, lib/shared/src/configuration/resolver.ts, lib/shared/src/sourcegraph-api/completions/browserClient.ts, lib/shared/src/sourcegraph-api/errors.ts, lib/shared/src/sourcegraph-api/graphql/client.ts, lib/shared/src/sourcegraph-api/rest/client.ts, lib/shared/src/sourcegraph-api/utils.ts, vscode/src/auth/auth.ts, vscode/src/completions/default-client.ts, vscode/src/completions/nodeClient.ts, vscode/src/services/UpstreamHealthProvider.ts, vscode/src/services/open-telemetry/CodyTraceExport.ts, vscode/src/services/open-telemetry/OpenTelemetryService.node.ts, vscode/src/services/open-telemetry/trace-sender.ts
That PR eliminates annoying chat reload upon an token refresh if external auth provider is used.
It does so by splitting external auth provider evaluation into two steps which happens at different stages: config resolution and http request building.
At config resolution we only evaluate config itself and prepare a function which will be later used to generate auth headers later. That function (`getHeaders`) is then used to obtain auth headers every time we are doing an authorised http request. Normally headers are cached, but if they expire `getHeaders` should internally refresh the cache and return an updated headers. If updated headers are still expired error will be shown to the user.
In opposition to the previous solution errors in executing external provider command, or token …
=> Refactor external auth providers to re-generate headers on demand

vscode/webviews/chat/cells/messageCell/assistant/SearchFilters.tsx
FIXES [QA-322](https://linear.app/sourcegraph/issue/QA-322/%5Bomnibox%5D-filter-screen-fails-to-display-unselected-options-in)
Previously, filters would disappear if you tried to deselect them and were not present in the search results. This PR changes what filters should be available depending on whether we get search results returned
https://github.com/user-attachments/assets/284c3964-5fe6-48b0-85e8-91564b555353
1. Tested keyword search with `changelog`
2. chose filters that would show 0 results
3. deselecting filters keeps them in the filter group and shows accurate update after hitting apply
4. checked whether previously selected filters remained in the filter group after each search result
=> fix(omnibox): fix available filters when deselecting

vscode/webviews/CodyPanel.tsx, vscode/webviews/chat/components/WelcomeMessage.tsx, vscode/webviews/components/promptList/PromptList.module.css, web/demo/App.tsx, web/lib/components/CodyWebChat.tsx, web/lib/index.ts, web/package.json
This PR makes changes to cody web which are necessary for the new cody web page updates.
> [!NOTE]
> It's possible that I have to make additional changes to this code as I'm finalizing the Svelte and React app updates, but the core changes are ready.
Contributes to https://linear.app/sourcegraph/issue/DES-267/implement-omnibox-submenu-for-web
This PR adds a way to have more control over the behaviorTrigger a new chat. of cody web from the host. This is enabled by cody web
accepting a controller object that has a similar API as the vscode API. It allows the host and cody web to
send messages to each other.
In particular the host can now do the following:
- Intercept view changes. This allows us to navigate to the native `/prompts` page instead of cody's prompts panel.
- Get the current …
=> feat: Add more control options to cody web

lib/shared/src/prompt/prompt-mixin.ts
This change ensures that the deep-cody prompt mixin is not applied to the 'chat-preview' (o1) model, preventing potential issues with the prompt generation.
Use o1 with agentic chat enabled and confirm the agentic chat prompt isn't getting applied.
=> fix(agentic chat): exclude deep-cody prompt for o1 models

vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx
This adds a separator + message when we've reached the end of results from the current (boosted) repository. This change is in conjunction with https://github.com/sourcegraph/sourcegraph/pull/2943, which will make this 
Implements the rough designs from [here](https://www.figma.com/design/eR495BJclVpdGdXf4lhSsH/One-box?node-id=7010-98964&t=Z1DJQBeiRZ1CjT4f-4). 
Manually tested various scenarios. 
Mix of results from current repo and other repos:
No results from current repo:
Only results from current repo:
=> omnibox: add callout for results from other repos

lib/shared/src/prompt/prompt-mixin.ts
This change ensures that the deep-cody prompt mixin is not applied to the 'chat-preview' (o1) model, preventing potential issues with the prompt generation.
Use o1 with agentic chat enabled and confirm the agentic chat prompt isn't getting applied.
Backport https://github.com/sourcegraph/cody/commit/e3093feed19e620726120c08b9f1175e3ce1af5f from https://github.com/sourcegraph/cody/pull/6725
=> fix(agentic chat): exclude deep-cody prompt for o1 models (#6725)

vscode/test/e2e/chat-keyboard-shortcuts.test.ts, vscode/webviews/chat/cells/messageCell/assistant/SearchResults.module.css, vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx
fixes QA-280
currently we're showing the filter and add to context button even if there is no search results. clicking on the filter button would still open up the filters sidebar. this PR introduces a cosmetic cleanup and will not render these buttons if a user gets no search results
before:
after:
note: the padding at the top is missing on main as well
1. type in search query that will generate no results, ex - asdfjkasdfasdfas
2. filter and "add to context" buttons should not show up
3. type in search query that will generate a search result, double checked the filters and add to context buttons still work
=> fix(omnibox): add conditional rendering to buttons

vscode/CHANGELOG.md, vscode/package.json
Version bump and changelog update for the vscode-1.62 stable release.
CI
=> chore/release: Bump package version and update changelog for 1.62

vscode/src/auth/auth.ts
Part of https://linear.app/sourcegraph/issue/DES-235/[onboarding-polish]-extensions-logout-guidance-step
This small change allows us to specify the instance URL for sigh up / auth flow, it's useful for workspace flow when we don't originally start our log-in flow from vscode and fill in the workspace URL but right from the workspace instance and we should notify cody to which URL it should try to log in with access token (code URL param) 
This PR is primarily needed for the workspace log-in into VSCode Cody PR in the Sourcegraph repository. 
https://github.com/user-attachments/assets/1dd1b90d-970e-4c2d-a71a-89cdaddf354a
@mmanela I saw your contributions about instance param in this flow, do you think we should make users go through this flow manually? I still left your logic in there so …
=> Support endpoint param in auth flow (workspaces vscode sign-in flow)

vscode/src/auth/auth.ts
Revert https://github.com/sourcegraph/cody/pull/6730
This reverts commit 7e4dbf904d5265e58f3919ce3e26625331e72b8d.
This is basically a security issue, for more details see https://github.com/sourcegraph/sourcegraph/pull/2942#issuecomment-2607120685
- CI is green
=> Revert "Support endpoint param in auth flow (workspaces vscode sign-in flow)

lib/shared/src/models/sync.ts
FIX https://linear.app/sourcegraph/issue/CODY-4737
The issue was that the Tool Cody model was being added to the list of primary models regardless of whether the feature was enabled or not. The root cause was that the check for the existence of the Tool Cody model was not properly scoped to the `isToolCodyEnabled` flag but was checking the observable instead, which would always returns true as the observable is defined.
This change fixes the issue by only adding the Tool Cody model to the list of primary models if the `isToolCodyEnabled` flag is true and the Tool Cody model is not already present in the list of primary models.
Included some minor clean up.
Verify Tool Cody is not showing up in your model dropdown if you don't have the configuration in your settings:
=> fix(models): ensure Tool Cody is only added when enabled

agent/recordings/auth_2503977039/recording.har.yaml, agent/recordings/autocomplete_2136217965/recording.har.yaml, agent/recordings/cody-chat_103640681/recording.har.yaml, agent/recordings/customCommandsClient_509552979/recording.har.yaml, agent/recordings/defaultClient_631904893/recording.har.yaml, agent/recordings/document-code_965949506/recording.har.yaml, agent/recordings/edit_1541920145/recording.har.yaml, agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml, agent/recordings/fix_3001320056/recording.har.yaml, lib/shared/src/sourcegraph-api/clientConfig.test.ts, lib/shared/src/sourcegraph-api/clientConfig.ts, lib/shared/src/sourcegraph-api/graphql/client.ts, lib/shared/src/sourcegraph-api/graphql/queries.ts
Check for `codeSearchEnabled` using the
[query](https://sourcegraph.sourcegraph.com/api/console#%7B%22query%22%3A%22query%20%7B%5Cn%20%20enterpriseLicenseHasFeature(feature%3A%5C%22code-search%5C%22)%5Cn%7D%5Cn%22%7D) to make sure intent detection is only available for users with code search enabled.
Also display the intent selection dropdown only when code search is enabled.
- test that intent detection is working as intended when connected to s2.
- connect to an instance with code search disabled and intent detection should be totally disbled and hidden and there should be no intent selection dropdown as well.
(cherry picked from commit 76cc36ee742223eb729653574648f588384ad647)
- test that intent detection is working as intended when connected to s2.
- connect to an instance with code …
=> [Backport vscode-v1.64.x] Disable Intent Detection if Code Search Disabled

agent/recordings/auth_2503977039/recording.har.yaml, agent/recordings/autocomplete_2136217965/recording.har.yaml, agent/recordings/cody-chat_103640681/recording.har.yaml, agent/recordings/customCommandsClient_509552979/recording.har.yaml, agent/recordings/defaultClient_631904893/recording.har.yaml, agent/recordings/document-code_965949506/recording.har.yaml, agent/recordings/edit_1541920145/recording.har.yaml, agent/recordings/enterpriseMainBranchClient_759014996/recording.har.yaml, agent/recordings/fix_3001320056/recording.har.yaml, lib/shared/src/sourcegraph-api/clientConfig.test.ts, lib/shared/src/sourcegraph-api/clientConfig.ts, lib/shared/src/sourcegraph-api/graphql/client.ts, lib/shared/src/sourcegraph-api/graphql/queries.ts
Check for `codeSearchEnabled` using the
[query](https://sourcegraph.sourcegraph.com/api/console#%7B%22query%22%3A%22query%20%7B%5Cn%20%20enterpriseLicenseHasFeature(feature%3A%5C%22code-search%5C%22)%5Cn%7D%5Cn%22%7D) to make sure intent detection is only available for users with code search enabled.
Also display the intent selection dropdown only when code search is enabled.
- test that intent detection is working as intended when connected to s2.
- connect to an instance with code search disabled and intent detection should be totally disbled and hidden and there should be no intent selection dropdown as well.
(cherry picked from commit 76cc36ee742223eb729653574648f588384ad647)
- test that intent detection is working as intended when connected to s2.
- connect to an instance with code …
=> [Backport jb-v7.12.x] Disable Intent Detection if Code Search Disabled

lib/shared/src/sourcegraph-api/clientConfig.ts
disable omnibox on dotcom
- connect to s2 and omnibox should work as intended. 
- connect to dotcom all the omnibox features should be hidden.
(cherry picked from commit 99faa39)
=> [Backport jb-v7.12.x] disable omnibox on dotcom

lib/shared/src/sourcegraph-api/clientConfig.ts
disable omnibox on dotcom
- connect to s2 and omnibox should work as intended. 
- connect to dotcom all the omnibox features should be hidden.
(cherry picked from commit 99faa39)
=> [Backport vscode-v1.64.x] disable omnibox on dotcom

vscode/test/e2e/uninstall.test.ts
This test failed [three attempts in a row](https://github.com/sourcegraph/cody/actions/runs/12937850063/job/36087981771?pr=6781) before finally passing on the fourth attempt. This PR disables the flaky test. I created a linear issue to track re-enabling [here](https://linear.app/sourcegraph/issue/CODY-4755/test-flake-uninstall-extension)
CI passes without flakes
=> chore: disable flaky test

lib/prompt-editor/src/mentions/mentionMenu/MentionMenuItem.tsx, vscode/src/chat/initialContext.ts, web/lib/components/CodyWebChat.tsx
When working on dynamic @ mentions, I noticed that we didn't support the lucide icons for things like "current repository". There was some code that still used codicon, which this PR migrates over to using lucide icons.
Manual testing
Before:
After:
=> mention menu: migrate from codicon to lucide

vscode/src/chat/chat-view/ChatController.ts, vscode/webviews/chat/Transcript.tsx
This fixes a regression in the intent telemetry (described [here](https://linear.app/sourcegraph/issue/SPLF-330), originally fixed in https://github.com/sourcegraph/cody/pull/6637).
Two fixes:
- we weren't using the right fields in `commonProps`, meaning that the values weren't assigned to the message and thus weren't accessible in the chat controller where we emit metadata.
- we were accidentally overriding the `userSpecifiedIntent` field with `auto` because of operator precedence.
We now get the correct data emitted in the `chat/executed` telemetry events.
I want to backport this to vscode-1.64 and jb-7.12.
Why? Telemetry data will help us improve intent detection significantly and it's important we have the pipeline functioning well at launch. Furthermore, the changes are quite …
=> Fix intent telemetry

vscode/src/chat/chat-view/ChatController.ts, vscode/webviews/chat/Transcript.tsx
This fixes a regression in the intent telemetry (described [here](https://linear.app/sourcegraph/issue/SPLF-330), originally fixed in https://github.com/sourcegraph/cody/pull/6637). Two fixes:
- we weren't using the right fields in `commonProps`, meaning that the values weren't assigned to the message and thus weren't accessible in the chat controller where we emit metadata.
- we were accidentally overriding the `userSpecifiedIntent` field with `auto` because of operator precedence.
We now get the correct data emitted in the `chat/executed` telemetry events.
I want to backport this to vscode-1.64 and jb-7.12. Why? Telemetry data will help us improve intent detection significantly and it's important we have the pipeline functioning well at launch. Furthermore, the changes are quite …
=> Fix intent telemetry (#6779)

vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/protocol.ts, vscode/src/repository/remoteRepos.ts, vscode/webviews/components/codeSnippet/CodeSnippet.tsx
This modifies the behavior of clicking search results to link to local files if the result represents a file in your local repo. With the [recent changes](https://github.com/sourcegraph/sourcegraph/pull/2943) that heavily prefer results from your current repo, this should now be most results.
[Video walkthrough](https://share.cleanshot.com/kqr06zwK)
=> omnibox: open results locally if possible

lib/shared/src/index.ts, lib/shared/src/sourcegraph-api/environments.ts, vscode/src/auth/auth.ts, vscode/src/main.ts
This is cherry-picking @mmanela commit from https://github.com/sourcegraph/cody/pull/6653
It was recently reverted here https://github.com/sourcegraph/cody/pull/6794 due to problems with reverting other PRs and merge conflicts. 
This PR contains a required change for a successful Workspace Auth flow so we should include this in the upcoming 1.64 release
VS Code side part of
https://linear.app/sourcegraph/issue/SRC-908/automate-cody-authflow-vs-code
After a user creates a workspace we want to make it easy for them to sign-in to the instance in their editor. For enterprise instances today, they need to copy the instance url, go into VS Code and then choose to signin with enterprise instance and then paste the url.
This change will help stream-line that flow by allowing the UI in sourcegraph …
=> feat(auth): Allow workspace to pre-populate URL for quick sign-in (#6653)

pnpm-lock.yaml, vscode/package.json
The windows e2e test fails because `LOG_BUNDLE_SIZE` isn't recognized as a env var on windows. Using `cross-env` allows us to easily set it across platforms
CI
=> fix(ci): add cross-env dep and use with LOG_BUNDLE_SIZE

vscode/src/chat/protocol.ts, vscode/webviews/Chat.tsx, vscode/webviews/CodyPanel.tsx, vscode/webviews/chat/components/WelcomeMessage.tsx, vscode/webviews/chat/components/WelcomeNotice.tsx, vscode/webviews/components/UserMenu.tsx, vscode/webviews/tabs/TabsBar.tsx
Updated CTA links and eligibility logic, see Loom and [CODY-4659](https://linear.app/sourcegraph/issue/CODY-4659/profile-menu-ctas) for full details
https://www.loom.com/share/2222084d04a14e1ba080b06c92207a19?sid=67bc08e2-e284-4616-92e4-1f087145a480
Closes https://linear.app/sourcegraph/issue/CORE-535/cody-clients-migrate-ctas-to-live-links.
1. Tested CTA eligibility on dotcom, and enterprise instances
2. Checked dismiss notifications did not break webview
3. Checked links and confirmed that they matched with designs
4. Switched across multiple accounts and everything still worked
=> chore(ES): update CTAs and eligibility logic

lib/shared/src/models/client.ts
The display name for the deep-cody model has been updated from 'Agentic Chat' to 'Agentic chat'.
Verify the name update:
=> chore(client): update display name for agentic model

.github/workflows/agent-bindings.yml, .github/workflows/agent-release.yml, .github/workflows/backport.yml, .github/workflows/ci.yml, .github/workflows/e2e-flakiness-detector.yml, .github/workflows/experimental-release.yml, .github/workflows/generate-changelog.yml, .github/workflows/integration-stability.yml, .github/workflows/labeler.yml, .github/workflows/lints.yml, .github/workflows/nightly-release.yml, .github/workflows/pr-auditor.yml, .github/workflows/scip-java.yml, .github/workflows/scip-typescript.yml, .github/workflows/semgrep.yml, .github/workflows/stable-release.yml, .github/workflows/stale.yml, .github/workflows/test.yml, .github/workflows/vscode-insiders-release.yml, .github/workflows/vscode-stable-release.yml
Closes [DINF-644](https://linear.app/sourcegraph/issue/DINF-644/improve-github-actions-concurrency-in-cody-repo)
This helps save some GitHub action minutes by ensuring we kill previous jobs belonging to the same workflow.
CI
=> chore(ci): handle concurrency with github actions

jetbrains/src/integrationTest/resources/recordings/integration-test_2927926756/recording.har.yaml, lib/shared/src/misc/rpc/webviewAPI.ts, lib/shared/src/sourcegraph-api/clientConfig.test.ts, lib/shared/src/sourcegraph-api/clientConfig.ts, lib/shared/src/sourcegraph-api/graphql/client.ts, lib/shared/src/sourcegraph-api/graphql/queries.ts, vscode/src/chat/chat-view/ChatController.test.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/completions/inline-completion-item-provider.ts, vscode/webviews/AppWrapperForTest.tsx, vscode/webviews/chat/Transcript.tsx, vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx, vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.test.tsx, vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx, vscode/webviews/chat/cells/messageCell/human/editor/toolbar/SubmitButton.story.tsx, vscode/webviews/chat/cells/messageCell/human/editor/toolbar/SubmitButton.tsx, vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx, vscode/webviews/components/omnibox/intentDetection.tsx
This PR:
- Removes the intent toggle feature completely. 
- Changes the intent dropdown behavior to only select the intent and not execute it automatically. 
- Enables the submit button even when the chat is empty.
- the intent options in the dropdown only selects the intent mode and doesn't execute it. 
- after selecting the intent, changing the input, doesn't reset the intent. 
- on submit the selected intent is used and the intent selection message is displayed accordingly.
- loading a chat from history and editing the message, doesn't persist the intent mode previously manually selected.
- selecting a prompt correctly executes it in chat & edit modes. 
- make sure the submit button isn't disabled when the input is empty.
=> Make Play Button stateful and remove intent toggle

jetbrains/src/integrationTest/resources/recordings/integration-test_2927926756/recording.har.yaml, lib/shared/src/misc/rpc/webviewAPI.ts, lib/shared/src/sourcegraph-api/clientConfig.test.ts, lib/shared/src/sourcegraph-api/clientConfig.ts, lib/shared/src/sourcegraph-api/graphql/client.ts, lib/shared/src/sourcegraph-api/graphql/queries.ts, vscode/src/chat/chat-view/ChatController.test.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/completions/inline-completion-item-provider.ts, vscode/webviews/AppWrapperForTest.tsx, vscode/webviews/chat/Transcript.tsx, vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx, vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.test.tsx, vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx, vscode/webviews/chat/cells/messageCell/human/editor/toolbar/SubmitButton.story.tsx, vscode/webviews/chat/cells/messageCell/human/editor/toolbar/SubmitButton.tsx, vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx, vscode/webviews/components/omnibox/intentDetection.tsx
backport: https://github.com/sourcegraph/cody/pull/6833
This PR:
- Removes the intent toggle feature completely.
- Changes the intent dropdown behavior to only select the intent and not execute it automatically.
- Enables the submit button even when the chat is empty.
- the intent options in the dropdown only selects the intent mode and doesn't execute it.
- after selecting the intent, changing the input, doesn't reset the intent.
- on submit the selected intent is used and the intent selection message is displayed accordingly.
- loading a chat from history and editing the message, doesn't persist the intent mode previously manually selected.
- selecting a prompt correctly executes it in chat & edit modes.
- make sure the submit button isn't disabled when the input is empty.
=> Backport 6833 to vscode.v1.64.x

jetbrains/src/integrationTest/resources/recordings/integration-test_2927926756/recording.har.yaml, lib/shared/src/misc/rpc/webviewAPI.ts, lib/shared/src/sourcegraph-api/clientConfig.test.ts, lib/shared/src/sourcegraph-api/clientConfig.ts, lib/shared/src/sourcegraph-api/graphql/client.ts, lib/shared/src/sourcegraph-api/graphql/queries.ts, vscode/src/chat/chat-view/ChatController.test.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/completions/inline-completion-item-provider.ts, vscode/webviews/AppWrapperForTest.tsx, vscode/webviews/chat/Transcript.tsx, vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx, vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.test.tsx, vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx, vscode/webviews/chat/cells/messageCell/human/editor/toolbar/SubmitButton.story.tsx, vscode/webviews/chat/cells/messageCell/human/editor/toolbar/SubmitButton.tsx, vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx, vscode/webviews/components/omnibox/intentDetection.tsx
backport: https://github.com/sourcegraph/cody/pull/6833
This PR:
Removes the intent toggle feature completely.
Changes the intent dropdown behavior to only select the intent and not execute it automatically.
Enables the submit button even when the chat is empty.
the intent options in the dropdown only selects the intent mode and doesn't execute it.
after selecting the intent, changing the input, doesn't reset the intent.
on submit the selected intent is used and the intent selection message is displayed accordingly.
loading a chat from history and editing the message, doesn't persist the intent mode previously manually selected.
selecting a prompt correctly executes it in chat & edit modes.
make sure the submit button isn't disabled when the input is empty.
=> Backport 6833 to jb v7.12.x

vscode/src/chat/chat-view/ChatController.ts, vscode/src/services/open-telemetry/CodyTraceExport.ts, vscode/src/services/open-telemetry/OpenTelemetryService.node.ts
1. Fixing problem with `externalAuthRefreshChanges` not having initial value which was blocking the configuration
2. Making caching checks more correct
3. Makes sure the spans for chat are properly closed so  that we can actually see them in HoneyComb
4. Fixing different edge cases in the re-registration of OtelCollectors with observables
This PR ensures that the spans for handling chat messages are properly ended, so that they are properly finished and exported. This way, they can be seen in the Trace View(I have verified this behavior by testing locally too) so now honeycomb should get proper chat traces.
NOTE: This behavior was working perfectly [in the original PR](https://github.com/sourcegraph/cody/pull/6294) but in [this massive refactor …
=> Fix OpenTelemetryService initialization+observables code and  fix the span closure of Chat Spans

lib/shared/src/experimentation/FeatureFlagProvider.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/webviews/utils/useOmniBox.tsx
As per the thread: https://sourcegraph.slack.com/archives/C05AGQYD528/p1738076320715949?thread_ts=1738004127.714799&cid=C05AGQYD528
This PR adds the Omnibox FF back. 
THIS MUST BE REVERTED BEFORE THE CODY RELEASE ON 29th. 
@umpox 
- set overrides for ff `cody-experimental-one-box` on s2
- when the ff is on, the omnibox elements, intent dropdown in the submit button, auto intent detection and search results should work
- when the ff is off, all the omnibox elements should be hidden and auto intent detection also should not work. 
Tested manually.
=> [JB] Temp add Omnibox FF

lib/shared/src/experimentation/FeatureFlagProvider.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/webviews/utils/useOmniBox.tsx
As per the thread: https://sourcegraph.slack.com/archives/C05AGQYD528/p1738076320715949?thread_ts=1738004127.714799&cid=C05AGQYD528
This PR adds the Omnibox FF back. 
THIS MUST BE REVERTED BEFORE THE CODY RELEASE ON 29th. 
@umpox 
- set overrides for ff `cody-experimental-one-box` on s2
- when the ff is on, the omnibox elements, intent dropdown in the submit button, auto intent detection and search results should work
- when the ff is off, all the omnibox elements should be hidden and auto intent detection also should not work. 
Tested manually.
=> [VS Code] Temp add Omnibox FF

vscode/src/autoedits/adapters/cody-gateway.test.ts, vscode/src/autoedits/adapters/cody-gateway.ts, vscode/src/autoedits/adapters/fireworks.test.ts, vscode/src/autoedits/adapters/fireworks.ts, vscode/src/autoedits/adapters/sourcegraph-chat.test.ts, vscode/src/autoedits/adapters/sourcegraph-chat.ts, vscode/src/autoedits/adapters/sourcegraph-completions.test.ts, vscode/src/autoedits/adapters/sourcegraph-completions.ts
1. We received multiple reports describing inconsistent model outputs in the "auto-edit" feature.
2. We initially used a temperature value of 0.2. On December 17, we set it to 0 in the [client-side PR](https://github.com/sourcegraph/cody/pull/6363/files)(released December 22 pre-release, December 29 stable) for more consistent generation.
3. The [issue arises in cody-gateway](https://github.com/sourcegraph/sourcegraph/blob/main/cmd/cody-gateway/internal/httpapi/completions/upstream.go#L318), when JSON-marshaling the request, any zero-valued fields (like temperature=0) get dropped before being sent to Fireworks.
4. Because no temperature is passed, [Fireworks defaults to a temperature of 1](https://docs.fireworks.ai/api-reference/post-completions#body-temperature), which is significantly …
=> feat(auto-edit): fix the temperature value regression with the auto-edit

vscode/src/autoedits/adapters/cody-gateway.test.ts, vscode/src/autoedits/adapters/cody-gateway.ts, vscode/src/autoedits/adapters/fireworks.test.ts, vscode/src/autoedits/adapters/fireworks.ts, vscode/src/autoedits/adapters/sourcegraph-chat.test.ts, vscode/src/autoedits/adapters/sourcegraph-chat.ts, vscode/src/autoedits/adapters/sourcegraph-completions.test.ts, vscode/src/autoedits/adapters/sourcegraph-completions.ts
1. fix the temperature value to be low for output consistency. `0.1` temperature value still leads to inconsistency sometimes. Having more deterministic outputs would help repro and debug the model quality better. 
2. Refer for more context: https://github.com/sourcegraph/cody/pull/6848/files 
1. Fixed the test cases and CI.
3. Local testing on the prompt to ensure the output is consistent.
=> fix(auto-edit): fix temperature value to be low for output consistency

vscode/webviews/chat/components/WelcomeNotice.tsx, vscode/webviews/components/UserMenu.tsx
Fixes typo introduced in #6803 
Ran locally, confirmed text change has been applied to dotcom users only
=> chore(ES): fix cta typo

vscode/webviews/chat/cells/messageCell/assistant/SearchResults.tsx
This re-removes the code search external link. It was removed in https://github.com/sourcegraph/cody/pull/6706, but accidentally added back in #6714. 
Fixes SRCH-1575
=> fix: remove code search button

vscode/src/autoedits/create-autoedits-provider.ts, vscode/src/services/StatusBar.ts
Cody Status bar for `autocomplete` is broken right now with the introduction of new suggestion modes.
- The PR adds a enum in the quick pick for selecting the suggestion model between `autocomplete`/`off`/`auto-edit` (if applicable). 
- `Auto-edit` is only shown if the user is eligible for the feature. See in the demo for the free account, we don't show this option.
- Closes https://linear.app/sourcegraph/issue/CODY-4713/status-bar-autocomplete-switch-doesnt-work 
- Switch between different modes in the toggle bar.
- Added a demo below
https://github.com/user-attachments/assets/a7cbb810-04b0-449e-90d3-8d8aa8211ff5
=> fix(auto-edit): fix the cody status bar with new suggestion mode

lib/shared/src/experimentation/FeatureFlagProvider.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/webviews/utils/useOmniBox.tsx
This reverts the revert commit dde16fffa5e7ccaae6d54d97cbe8336dd72627ff.
Intention is to restore the behaviour intended with this commit: https://github.com/sourcegraph/cody/pull/6747
We reverted as we wanted to cut a pre-release without releasing this feature to all pre-release users.
Make sure all omnibox features are working with s2 but not with demo.sourcegraph.com
=> [VS Code] Release Omnibox: remove feature flag

lib/shared/src/experimentation/FeatureFlagProvider.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/webviews/utils/useOmniBox.tsx
This reverts the revert commit 47f03f1ff.
Intention is to restore the behaviour intended with this commit: https://github.com/sourcegraph/cody/pull/6747
We reverted as we wanted to cut a pre-release without releasing this feature to all pre-release users.
Make sure all omnibox features are working with s2 but not with demo.sourcegraph.com
=> [JB] Release Omnibox: remove feature flag

.github/workflows/backport.yml
Per RFC1018, we will ship VSCode and JetBrains from a single release branch. These are labeled after the milestone, for example M66, M68, etc.
The legacy branch names are preserved, but we can remove them after M66 hits stable.
I am release captain this week and will dogfood this with M66 by backporting changes like the renamed release automation in #6879 to the M66 branch.
=> chore/release: Add support for milestone branch labels for backports

jetbrains/CONTRIBUTING.md, jetbrains/scripts/next-release.sh, jetbrains/scripts/push-git-tag-for-next-release.sh
These scripts predate release branches and used to always look at global tags. This change makes it work on release branches. It uses git to list the commits on the release branch, then does the same version bump calculation using the branch's tags.
It takes care to handle newly budding branches which are just a commit on `main` that has no backports yet. In that case it looks at all of the available tags.
It will work carrying a branch from prerelease through to release:
```
$ ./scripts/push-git-tag-for-next-release.sh --minor --nightly
$ ./scripts/push-git-tag-for-next-release.sh --patch --nightly
$ ./scripts/push-git-tag-for-next-release.sh --minor
$ ./scripts/push-git-tag-for-next-release.sh --patch
```
There are some caveats with this tool:
- When working on a release branch, it only …
=> chore/build: Teach JetBrains push-git-tag-for-next-release.sh about release branches

lib/shared/src/experimentation/FeatureFlagProvider.ts, lib/shared/src/models/modelsService.ts
Changes the default chat model in cody to DeepSeek-V3 but only once 
- Locally setup sourcegraph instance using `sg start enterprise-cody-e2e` 
- enable the feature flag 
- Restart cody in the debugger. You will see default model as Deepseek but only once 
NOTE: Actually setting up deepseek properly with Cody requires some creds so feel free to DM me and I can send you the credentials but in order to just check the model setting logic we don't need the creds setup etc.
=> Changes the default chat model in cody to DeepSeek-V3 but only once

agent/recordings/auth_2503977039/recording.har.yaml, agent/recordings/unauthed_2245427793/recording.har.yaml, agent/src/auth.test.ts, jetbrains/src/integrationTest/resources/recordings/integration-test_2927926756/recording.har.yaml, lib/shared/src/misc/observable.test.ts, lib/shared/src/misc/observable.ts, lib/shared/src/models/sync.test.ts, lib/shared/src/models/sync.ts, lib/shared/src/sourcegraph-api/clientConfig.ts, vscode/src/autoedits/create-autoedits-provider.ts
There are two main fixes in this PR:
1. Changes in `lib/shared/src/models/sync.ts` 
They ensure we are not mixing new `config` and old `authStatus`.
Previously it was possible to get an update when `config` changed, and then execute model computation code before auth had a chance to update. This could lead to using remote models from outdated (already changed) endpoint.
2. Change in `clientConfig.ts`
Why we need a retry here? To explain it we need understand the whole control flow:
> 1. `syncModels` function takes  `clientConfig: ClientConfigSingleton.getInstance().changes` as a parameter
> 2. computation of `clientConfig` internally calls `this.fetchConfig(authStatus, signal)`
> 3. `fetchConfig` is doing an GraphQL query, and GraphQL is using cache (`GraphQLResultCache`)
> 4. That cache …
=> Fix problem with race between auth and config causing issues with models loading

lib/shared/src/codebase-context/messages.ts, lib/shared/src/context/openctx/context.ts, vscode/src/chat/chat-view/ContextRetriever.ts
FIX https://linear.app/sourcegraph/issue/CODY-4843/agentic-context-removes-explicitly-mentioned-remote-file
- Update `getContextForChatMessage` in `lib/shared/src/context/openctx/context.ts` to set the `source` property of `ContextItemOpenCtx` to `ContextItemSource.User` to indicate that the item was added by the user.
- Update `toStructuredMentions` in `vscode/src/chat/chat-view/ContextRetriever.ts` to set the `source` property of `ContextItem` to `ContextItemSource.User` if it is not already set.
- Add a note in `lib/shared/src/codebase-context/messages.ts` explaining the purpose of the `source` property and how it is used to prioritize user-added context items.
This change ensures that user-added context items are properly identified and can be prioritized over non-user-added items …
=> fix(context): Mark at-mention context items as user-added items

vscode/webviews/chat/ChatMessageContent/create-buttons.ts, vscode/webviews/icons/CodeBlockActionIcons.tsx
closes https://linear.app/sourcegraph/issue/CODY-4826/smart-apply-show-reapply-to-indicate-applied-state
Primary purpose of these changes:
- Give a UI indication of when a code block has already been applied and accepted. Especially useful when a user is actioning multiple code blocks in a response
- Make it obvious to the user that they can re-apply a codeblock if something went wrong, or they weren't happy with the result
https://github.com/user-attachments/assets/3c7a4094-f98c-4597-abcb-bb8897c98215
1. Make smart applies
2. Click "Apply"
3. Click "Accept"
4. Observe that "Reapply" appears
=> feat(Smart Apply): Show Reapply for applied code blocks

jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.kt
Fixes https://linear.app/sourcegraph/issue/BUGS-1272
Signatures of function `getAppSession`:
[IJ 2023.2](https://github.com/JetBrains/intellij-community/blob/idea/232.10203.10/platform/platform-impl/src/com/intellij/openapi/client/ClientSessionsManager.kt#L54): `fun getAppSession(clientId: ClientId = ClientId.current): ClientAppSession?`
[IJ 2025.1](https://github.com/JetBrains/intellij-community/blob/idea/251.18673.35/platform/core-api/src/com/intellij/openapi/client/ClientSessionsManager.kt#L33): `fun getAppSession(clientId: ClientId): ClientAppSession?`
So to fix it it was enough to add an default parameter explicitly.
**IJ 2023.2:**
1. Run IJ 2023.2 either using pre-installed IntelliJ 2023 or by using command: `./gradlew :customRunIDE -PplatformRuntimeVersion=2023.2 …
=> Use IntelliJ API which is present in all IntelliJ versions

lib/shared/src/experimentation/FeatureFlagProvider.ts, vscode/src/edit/manager.ts, vscode/src/edit/smart-apply-context-logging.ts, vscode/src/services/utils/codeblock-action-tracker.ts
- The PR adds a basic a/b testing setup to experiment with the smart apply. 
- We will try haiku in a variant and based on the a/b results decide if the model is worth switching.
- Add yourself in the feature flag `cody-smart-apply-experiment-variant-1` and `cody-smart-apply-experiment-enabled-flag`
- Try the smart apply feature and see the updated model in `█ telemetry-v2 recordEvent: cody.command.edit/executed: {` events
=> feat/smart-apply: add haiku 3.5 for a/b testing

agent/src/agent.ts
In https://github.com/sourcegraph/cody/pull/5391 the agent started forcing the workspaceRootUri to `file:` scheme. It was not documented why, and this is indicative of a bug elsewhere. In the rules PR (https://github.com/sourcegraph/cody/pull/6909), Cody Web starts caring about the workspace root URI and needs to use a `repo:` URI scheme. (Previously, the workspaceRootUri in Cody Web was an invalid URI `sourcegraph/cody`.)
CI
=> do not force agent workspace root URI to be `file:` scheme

vscode/webviews/components/promptList/PromptList.tsx
This change adds the `promptId` property to the `privateMetadata` object in the `PromptList` component. This will allow for better tracking and identification of prompts in the Cody application.
Locally
=> feat(PromptList): add `promptId` & `promptName` to privateMetadata

lib/shared/src/chat/chat.ts, lib/shared/src/sourcegraph-api/siteVersion.ts, vscode/src/chat/chat-view/handlers/ChatHandler.ts, vscode/src/edit/manager.ts, vscode/src/edit/provider.ts, vscode/webviews/chat/ErrorItem.module.css, vscode/webviews/chat/ErrorItem.tsx, vscode/webviews/chat/cells/messageCell/assistant/AssistantMessageCell.tsx
This PR is for the fix-it issue "Add a retry button for Cody API version error".
**WHY**
When we have a network error, it can cause temporary Cody API version error. It would be nice to allow user to retry for retriable errors like this.
**WHAT**
Add a retry button for Cody API version error.
Restrict the Cody API version check to claude-3 models only since we don't need the check for the rest of the models. Claude-3 models are being deprecated already, but old sg instances might still have them.
CI & tested locally with debugger (see [Loom video](https://www.loom.com/share/3468a810fdfc43f6ba560e6eba95fb5f?sid=595964ef-bc93-4c01-a2d8-afc9c33f4e71))
=> chore/(chat): Add a retry button for Cody API version error (CODY-4864)

vscode/webviews/chat/components/WelcomeMessage.module.css
The `Recently Used` and `All Prompts` buttons currently get cut off if the chat window is too small.
https://github.com/user-attachments/assets/43cc8aa7-49f2-4ac7-9be2-06b05b37b98f
Update `flex` style for these buttons so they wrap to the next line instead of getting cut off.
https://github.com/user-attachments/assets/610d76ee-da60-454b-b3bf-d7745f347ad9
CI & ran local debugger. See videos above.
=> fix/(chat): bottom prompt buttons cut off

agent/src/AgentTextDocument.ts, package.json
Previously, running the agent tests caused the following error to get
logged:
```
----stderr----
Uncaught exception: Error: Method not implemented.
at _AgentTextDocument.validateRange (/Users/olafurpg/dev/sourcegraph/cody/agent/src/AgentTextDocument.ts:136:15)
at FixupTask.getContentChanges (/Users/olafurpg/dev/sourcegraph/cody/vscode/src/non-stop/FixupTask.ts:163:41)
```
The root problem is that we are using `TextDocument.validateRange()` in
the VS Code extension and this method is not implemented yet for non-VSC
clients.
I'm not 100% sure how serious this bug is, but the fix is simple enough
that we should just merge the fix.## Test plan
Manually confirmed there are no errors in stdout when running `pnpm test src/edit.test.ts` from the agent subdirectory.
=> Agent: fix crash when using TextDocument.validateRange(...)

lib/shared/src/experimentation/FeatureFlagProvider.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/create-autoedits-provider.ts, vscode/src/autoedits/test-helpers.ts, vscode/src/main.ts
Gates the [image based renderer](https://github.com/sourcegraph/cody/pull/6545) behind a feature flag.
Will enable this by default on S2 so we get some dogfooding feedback
1. Disable the flag, check auto edits shows suffixes
2. Enable the flag, check auto edit shows images
=> feat(autoedit): Enable image based rendering for dogfooding

vscode/src/edit/edit-context-logging.ts, vscode/src/edit/manager.ts, vscode/src/non-stop/FixupController.ts, vscode/test/e2e/__snapshots__/command-edit.test.ts/edit-fixup-task-1.txt, vscode/test/e2e/command-edit.test.ts, vscode/test/e2e/helpers.ts
- Track the `taskId` for the `edit` command and propagate the same to the  smart apply context.
- This changes will help link the rejected/accepted edit context with the smart apply task and help identify the challenging tasks where it fails.  
- Observe the `smart-apply` and `edit` telemetry events, which should be tagged with same `taskId` and `applyTaskId` and should be same for the common request.
=> feat/smart-apply: log fixupID to track in the edit

lib/shared/src/experimentation/FeatureFlagProvider.ts, vscode/webviews/Chat.tsx
I missed the check for Cody Web dotcom users, this PR adds a check to only show CTAs in editor. 
ran locally, confirmed CTAs still show up on editor
=> fix(web): Don't show CTA on Cody Web for PLG

vscode/webviews/chat/components/QuickStart.tsx, vscode/webviews/chat/components/WelcomeFooter.tsx, vscode/webviews/chat/components/WelcomeMessage.tsx
This PR removes the footer links in the chat (they're already available in the profile menu) and fix border styling.
**Old UI**
**New UI**
Tested locally, manually.
=> fix: remove chat footer link removals and border fixes

agent/recordings/defaultClient_631904893/recording.har.yaml, agent/src/index.test.ts, lib/shared/src/sourcegraph-api/clientConfig.ts
FIX: https://linear.app/sourcegraph/issue/CODY-4888
The change revert the client configuration fetching logic changes made by #6710.
I haven't found a way to reproduce the issue consistently, but I suspected it was the code change because: The new code attempts to get siteVersion, viewerSettings, and codeSearchEnabled in parallel, and the timeout could be happening because we're making multiple concurrent API calls
Key changes:
- Removed AuthStatus dependency since endpoint checks were removed
- Flattened nested promise structure using .then() chains
- Improved error handling by moving catch block to end of chain
- Make the API calls sequential rather than parallel
- Potentially avoid timeout issues by not overwhelming the network with concurrent requests
This makes the code more …
=> fix(client-config): Simplify config fetching logic and fix omnibox flag

jetbrains/src/main/resources/META-INF/plugin.xml
We will create releases in sourcegraph/cody now, because that's where the commits are! And link to this page to display them:
https://github.com/sourcegraph/cody/releases?q=JetBrains&expanded=true
```
cd jetbrains
./gradlew verifyPlugin
```
Land this, backport it, then release a v7.67 nightly and check that [the JetBrains Marketplace page](https://plugins.jetbrains.com/plugin/9682-cody-ai-code-assistant/edit/versions/nightly) looks good.
=> fix/release: Update the JetBrains link to release notes.

lib/shared/src/sourcegraph-api/completions/browserClient.ts
There are currently two problems with the stop button functionality on
cody web:
1. After pressing the button the response stream continues for a while.
2. The button doesn't turn back into the submit button, making itj
impossible to submit a follow up question.
This commit solves (2).
The way the chat response propagates through the system somwhat like
this (simplified)
response chunks -> typewriter effect -> webworker transport -> ui
We are also passing an abort signal all the way down to the logic that
initiates the response stream. When the close button is activated we are
trigger that signal.
But this abortion doesn't 'trickle back up' to typewriter, etc. because
`fetchEventSource` doesn't emit any event in this case.
The fix is to directly listen to the abort event and call the …
=> fix: Stop button on cody web

vscode/webviews/components/codeSnippet/components/RepoLink.tsx
Closes https://linear.app/sourcegraph/issue/SRCH-1583/result-accordions-are-backwards
Trivial change, locally tested.
=> fix: Fix chevron for open/closed search results

lib/shared/src/models/client.ts, vscode/src/chat/agentic/CodyToolProvider.test.ts, vscode/src/chat/agentic/DeepCody.ts, vscode/src/chat/agentic/ToolboxManager.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/chat-view/handlers/registry.ts, vscode/src/chat/chat-view/prompt.ts, vscode/webviews/chat/Transcript.tsx, vscode/webviews/chat/cells/contextCell/ContextCell.tsx, vscode/webviews/chat/cells/messageCell/assistant/AssistantMessageCell.tsx, vscode/webviews/components/ChatModelIcon.tsx, vscode/webviews/components/modelSelectField/ModelSelectField.story.tsx, vscode/webviews/components/modelSelectField/ModelSelectField.tsx
This bugged me while reading and to warm up to the codebase, I decided to replace the hardcoded strings with the reference. Can't do it in `lib/shared`, but in `vscode`.
- Run Cody and see that agentic chat works.
=> chore: Remove hard-coded 'deep-cody' and replace with constant

lib/shared/src/models/client.ts, lib/shared/src/models/sync.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/chat-view/handlers/ToolHandler.ts, vscode/src/chat/chat-view/handlers/registry.ts, vscode/webviews/chat/Transcript.tsx, vscode/webviews/components/modelSelectField/ModelSelectField.tsx
This fixes `tool-cody` not working anymore by making the `model` and `agentName` checks actually check for tool-cody.
To test it, you need to set the experimental setting:
```json
{
"cody.experimental.minion.anthropicKey": "anthropic api key here",
}
```
I also added a "run terminal command" tool that's by no means production ready but helped me test things easily and get more familiar with the codebase again.
- Set `"cody.experimental.minion.anthropicKey": "anthropic api key here"` in VS Code settings
- Open Cody, select `Tool Cody` that's now visible
- Ask Cody: "Can you run `wc -l` against <filename> please?"
- See it return the output
=> experimental: Re-enable tool-cody for exploration

vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx
The user knows who they are, why show it next to every message? It clutters the UI. So I removed the avatar from the human messages (we still have the avatar in the top right).
I also removed the name from the follow-up message. It doesn't add anything.
Ideally we'd remove the "user name" every where but when I did that, the layout looked kinda bad because there was still the 'split into chat' button.
- N/A
=> chat ui: remove user avatars, remove speaker name from follow-up message

vscode/src/chat/chat-view/ChatController.ts, vscode/test/e2e/chat-context.test.ts, vscode/test/e2e/chat-input.test.ts
This removes the 500ms delay when submitting messages. It was introduced in #6720.
If I understood the PR correctly, it was introduced to fix the error message that shows up when trying to switch intent while a response is streaming in.
But instead of waiting 500ms before aborting, we go back to aborting, and explicitly abort a possible ongoing request before editing the message and resubmitting it.
In my testing, it fixes the bug.
I also re-added the tests that were commented out in #6720.
- Submit a message to Claude, saying something like "write me a long poem" so that it generates a lot of text
- While Claude is generating, switch the intent manually by clicking on the button
- No error message should pop up
=> bug fix: Fix 500ms delay when submitting chat message

vscode/webviews/.sourcegraph/no-scrollIntoView.rule.md, vscode/webviews/App.module.css, vscode/webviews/CodyPanel.tsx, vscode/webviews/chat/Transcript.tsx
Previously, pressing Enter in a chat message in VS Code's Cody chat would cause the iframe to be shifted up by ~5px. This was an annoying visual jitter. Now, this no longer happens.
CI
Also: Run in VS Code, type a chat message, press Enter, and ensure there is no jitter. Also ask a long chat question and ensure that the scroll-to-end works.
- Fixed an issue where pressing Enter in chat would cause brief visual jitter in the UI.
=> fix ~5px pixel jitter when pressing Enter in chat in VS Code

.github/workflows/release-vscode-stable.yml
No test... we will watch what happens in Slack when we release M68 to stable. This is the last step in the job so if it fails the release is still done.
The diff URLs look like this now: https://github.com/sourcegraph/cody/compare/M66...M68
=> chore/release: VSCode stable release Slack announcements to point to the correct release branches

vscode/webviews/chat/cells/messageCell/assistant/RepositorySelector.tsx
closes: https://linear.app/sourcegraph/issue/SRCH-1585/followup-box-leaks-through-repo-filters
Fix the z-index for repo search filter dropdown. It overlaps over follow up input and breaks. 
Before
After
=> Fix Repo filter dropdown z-index

vscode/webviews/tabs/HistoryTab.tsx
Removes CSS that was conflicting with default input styles
* Manually check to ensure the input has a border.
=> Fix border on history search

vscode/CHANGELOG.md, vscode/package.json
No test plan, following the release captain playbook
=> chore/release: Bump package version and update changelog for 1.66

vscode/webviews/chat/cells/agenticCell/AgenticContextCell.tsx, vscode/webviews/tabs/HistoryTab.tsx
**Before**
1. Things on the chat page are not aligned (see image)
2. The search bar text font is too big (see gif)
3. The search bar moves while typing (see gif)
**After**
1. Everything is aligned
2. Smaller font
3. Make the search bar not move while typing 
CI & local tests
=> fix(ui): Fix bugs in the UI

lib/shared/src/sourcegraph-api/client-name-version.ts, web/demo/App.tsx
After https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody/-/commit/297c4a90fe56f00520865b0f72ee5450a648c706?editor=JetBrains&version=v7.4.2-experimental&utm_product_name=WebStorm&utm_product_version=2024.3
Cody Web sandbox is broken due to problems with CORS and headers; historically, all this system with headers and sandbox proxy is very fragile. This PR brings back header changes that we had before (headers shouldn't have x-requested-with header in sandbox otherwise we get cors problems)
- Check that cody web sandbox works
=> Fix cody web sandbox cors problem

.github/workflows/ci.yml
The e2e tests pass fairly reliably on PRs where we break them up into 5 separate runs. But on main we run all the e2e tests in a single go. This appears to be causing test failures after 9min due to cancellation (and in general, it is flakier because it just takes 1 e2e test flake).
The Windows and macOS full e2e tests have been failing recently, so they are disabled. It would be good to reenable them. But now the Ubuntu e2e tests should pass on main.
n/a
=> disable windows/macOS e2e tests on main, shard ubuntu tests

web/package.json
This updates the version of cody-web to 0.30.0 Current release is 0.29.0: https://www.npmjs.com/package/@sourcegraph/cody-web
Manual testing
=> Update cody web to 0.30.0

lib/shared/src/rules/filters.test.ts, lib/shared/src/rules/filters.ts
The language filters users can specify for rules (i.e., via `lang: go`) are not currently applying correctly. Currently, a `*.rule.md` file marked with `lang: go` does not apply to Go files.
_The `Check repo permissions in handlers` rule is not applying to the current `Go` file, even though `lang: go` is specified_
Fix the matching logic for language filters to compare case-insensitive strings instead of attempting to match via regex. This is for two reasons:
- The filters `go` and `Go` should both match a file like `test.go`. Currently only `Go` would match
- Using regex would require escaping special characters for languages like `C++` (because `+` is a special character). We want an exact match between language filter and language name anyways
_The `Check repo permissions in handlers` …
=> fix(chat): language filters in rules not applying correctly

vscode/src/autoedits/renderer/decorators/default-decorator.ts
Need to set `line-height` to 0, as otherwise the "space" for the decoration is slightly padded by the empty line
Local testing, comparing images
=> feat(auto-edit): Fix slightly misaligned image decorations

lib/prompt-editor/src/plugins/atMentions/atMentions.module.css, lib/prompt-editor/src/plugins/atMentions/atMentions.tsx
When the Cody window is smaller than the min popup, the @ mention will display the tooltip box outside the bounds of the editor.
Add a parent container that can use media queries to determine when the parent is now smaller than minimum tooltip size.
I know there is a better to store these CSS variables, open to suggestions. Thank you!
- Open the extension in your browser: `pnpm -C web dev`
- Shrink your chat extension sidebar smaller than 300px, the default minimum
=> fix(chat): At mention menu open outside the editor window

vscode/src/commands/context/open-tabs.ts
Here are a few short videos:
1. The bug in action:
https://github.com/user-attachments/assets/aba8daa5-0473-4ebb-b11d-142c1ccd89c4
2. Besides fixing the generic replacement I also added an option to `selectedCodePromptWithExtraFiles`
in order to get rid of parenthesis wrapping the `otherMentions`  if we don't need it such as in the case of the current-tabs.
https://github.com/user-attachments/assets/8af553c5-afa3-4c63-bf30-c3a533d1449d
and the fix:
https://github.com/user-attachments/assets/0aab3f83-c06c-439e-a694-385fc100597e
1. Create a prompt that uses the current-tab mention.
2. Open the Settings panel on VSCode (command + ,)
4. Run the prompt and notice it being replaced by the opened editor tabs instead of remaining on cody://current-tabs
=> fix(chat): expansion of current-tab generic mention when non editor tabs are opened

.github/workflows/generate-changelog.yml
Upgrades changelog generator from my old script to dev infra's. I added a new `betweenCommit` strategy to their tooling, which let's us parse total git history between 2 commits. see https://github.com/sourcegraph/devx-service/pull/299 for full details.
Using the dev infra changelog binary will now let us group PRs by their titles and types ($type/$domain) and will make the changelog process much easier. We should start following the conventions laid out on the [Cody PR conventions page](https://www.notion.so/sourcegraph/PR-and-Changelog-conventions-ecfd817301614c399d4c8b9aa5832370)
Release captains can now run this workflow from the milestone branch to generate the changelog. 
See https://github.com/sourcegraph/cody/pull/7077 as an example of what this outputs. 
// TODO for after
Force …
=> chore(release): upgrade changelog generator

vscode/src/commands/scm/source-control.ts
Fixes [BUGS-1320](https://linear.app/sourcegraph/issue/BUGS-1320)
After the deprecation of Haiku-3 the "generate commit message" command ended up
using the currently set model for chat instead of haiku.
Now we set it to the flash-lite model as it's the cheapest and the fastest, thus being
great for replacing the previous Haiku-3 model.
Enable debug mode and make modifications to source-controlled code. Use the generate commit message command or
button and notice we no longer use the last used model, instead we use flash-lite.
=> fix(command): Generate commit message now uses flash-lite instead of last selected model

lib/prompt-editor/src/nodes/tooltip.ts, lib/shared/src/index.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/protocol.ts, vscode/webviews/promptEditor/config.ts
This pull request makes 2 changes:
1. I've added the line range to the tooltip of MentionComponent mirroring what happens in ContextCell `contextItemsToDisplay` `FileLink`
2. When you command click on the mention if the mention contains a selection range we focus on that
selection like we do from the FileLink component
See this video for demo of changes https://www.youtube.com/watch?v=aCesKaBi2nI
Run a command on a selection of code such as Explain Code and notice:
1. When you hover over the chip you see the line range in the tooltip
2. When you ctrl or command + click you are focused on the selection range of that context file
=> feat(prompt-editor): focus on file range when clicking on context item mention with ranges

vscode/webviews/chat/components/WelcomeMessage.test.tsx, vscode/webviews/components/promptList/ActionItem.tsx, vscode/webviews/components/promptList/PromptList.tsx
Closing https://linear.app/sourcegraph/issue/SRCH-1648/dont-show-unuseable-prompts-in-chat-prompt-list
Some prompts are unclickable when you can't use them in the current environment. This is bad user experience.
This PR hides the unused prompts.
Before
After
=> fix(ui): Hide unused prompts(SRCH-1648)

.github/workflows/release-jetbrains-experimental.yml, .github/workflows/release-jetbrains-prerelease.yml, .github/workflows/release-jetbrains-stable.yml, .github/workflows/test.yml, agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/CodyAgentServer.kt, agent/scripts/reverse-proxy.py, agent/src/agent.ts, jetbrains/CONTRIBUTING.md, jetbrains/build.gradle.kts, jetbrains/src/main/java/com/sourcegraph/find/FindPopupDialog.java, jetbrains/src/main/java/com/sourcegraph/find/FindPopupPanel.java, jetbrains/src/main/java/com/sourcegraph/find/FindService.java, jetbrains/src/main/java/com/sourcegraph/find/browser/HttpSchemeHandler.java, jetbrains/src/main/java/com/sourcegraph/find/browser/JSToJavaBridgeRequestHandler.java, jetbrains/src/main/java/com/sourcegraph/find/browser/JavaToJSBridge.java, jetbrains/src/main/java/com/sourcegraph/find/browser/SourcegraphJBCefBrowser.java, jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/CodyAuthService.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/config/notification/ChangeListener.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/config/notification/CodySettingChangeListener.kt, jetbrains/src/main/kotlin/com/sourcegraph/config/ConfigUtil.kt, lib/shared/src/sourcegraph-api/utils.ts, vscode/src/jsonrpc/agent-protocol.ts
This PR adds agent endpoint which allow us to fetch auth headers, which in turn we need to deliver to the sourcegraph search webview.
Webview changes are on a separate PR: https://github.com/pkukielka/sourcegraph-public-snapshot/pull/1
**Setup:** 
1. Clone git@github.com:pkukielka/sourcegraph-public-snapshot.git and checkout  `pkukielka/add-external-auth-providers-support` branch.
2. `export CODE_SEARCH_DIR_OVERRIDE=/path/to/pkukielka/sourcegraph-public-snapshot`
3. Checkout this PR (`pkukielka/ext-auth-fix-search` branch) in Cody project dir
4. `cd jetbrains`  
5. Run `./gradlew customRunIde -PforceCodeSearchBuild=true -PforceAgentBuild=true`
6.  Add external auth provider configuration:
```
{
"cody.override.serverEndpoint":  "https://piotr-kukielka.sgdev.dev", …
```
=> Add support for external auth providers in code search

vscode/webviews/chat/components/WelcomeMessage.test.tsx, vscode/webviews/components/promptList/PromptList.tsx
Reverts sourcegraph/cody#7095
I missed something essential on @julialeex's PR when I approved it. We need to account for the IDE currently being used.
this is a revert
=> Revert "fix(ui): Hide unused prompts(SRCH-1648)"

lib/prompt-editor/src/v2/promptInput.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/protocol.ts, vscode/webviews/App.story.tsx, vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx
Closes https://linear.app/sourcegraph/issue/SRCH-1667/no-results-returned-when-enabling-feature-for-queries
This PR fixes an issue with the prompt input being cleared out when a query is submitted and the new input is enabled.
The root cause for this issue is twofold:
1. Evaluating feature flags is always asynchronous. The first time `HumanMessageEditor` is rendered we will render the
old editor.
1. In the same component, `useImperativeHandle` is only run once when the component is mounted. This means we never
update the ref with the ref from the new editor once the feature flag updates.
The consequence of this is that everywhere else where `editorRef` is used we have a reference to the _old_ editor API,
which has been destroyed since. Reading the value from it will of course be empty, …
=> fix: Make it possible to dogfood new prompt editor

vscode/package.json, vscode/src/chat/chat-view/ChatsController.ts
closes https://linear.app/sourcegraph/issue/CODY-4947/re-add-right-click-file-context-option-for-cody-chat-in-vs-code-was
I tried to get it to add multiple like cursor does, but it seems that while vscode "highlights" multiple files with shift, it "selects" the one you clicked
1. Open file explorer
2. Right Click
3. Select "Add File to Cody Chat"
4. Observe file added to cody chat
https://www.loom.com/share/0deca006f6b0499cabc8b4a43a0e11cd
=> feat(vscode): add context via file explorer

vscode/src/services/open-telemetry/CodyTraceExport.ts, vscode/src/services/open-telemetry/CodyTraceExportWeb.ts, vscode/src/services/open-telemetry/OpenTelemetryService.node.ts, vscode/webviews/App.tsx, vscode/webviews/utils/webviewOpenTelemetryService.ts
Part of CODY-4771. Adds agent version and ClientPlatform in OpenTelemetryService.
NOTE: the [version string](https://sourcegraph.com/github.com/sourcegraph/cody@adding-trace-versions/-/blob/vscode/src/version.ts?L11) uses pre-release and release versions properly and @abeatrix confirmed that too. The version string is what is actually the value of clientCapabilities.agentExtensionVersion
Tested locally with the debugger
- Run a local sourcegraph instance with `sg start`
- Run Open Telemetry Collector with `sg start otel`
- Run this branch on Cody repo  with the debugger 
- Make sure that the account used in Cody is local Sg instance account 
- Go to the URL `http://localhost:16686/-/debug/jaeger ` this shows you the local traces
- Checkout webview service
Look into your specific chat …
=> fix/tracing: Add Client Platform and agentVersion to traces

lib/prompt-editor/src/v2/lexical-interop.test.ts, lib/prompt-editor/src/v2/lexical-interop.ts
To make the prosemirror implementation work as a drop-in replacement we
use some utility function to convert lexical state to prosemirror and
back.
The utility function was written by carefully inspecting the lexical
serialized state, but that doesn't give us any confidence in its
correctness.
This commit adds a test for these utility functions.
vitest
=> chore: Add prosemirror-lexical interop test

.github/workflows/release-vscode-experimental.yml, .github/workflows/release-vscode-nightly.yml, vscode/scripts/release.ts
CLOSE: https://linear.app/sourcegraph/issue/CODY-4777
This adds support for publishing nightly builds of the VS Code extension under a different package name and display name to avoid conflicts with the main extension.
- Added 'nightly' as a new ReleaseType enum value
- Added updatePackageForNightly() function to modify package.json for nightly builds
- Changed package name to 'cody-ai-nightly' for nightly releases
- Updated display name to 'Cody: AI Code Assistant - Nightly'
- Refactored insiders build checks to include nightly builds
- Updated publishing logic to handle nightly builds same as insiders
- Release nightly build under pre-release channel under the new name
NOTE: The nightly build is not intended to work with the main extension and is expected to cause conflicts if both are …
=> feat: Add experimental & nightly release channels for vsce

vscode/package.json, vscode/webviews/components/UserMenu.tsx, vscode/webviews/tabs/TabsBar.tsx
Closing https://linear.app/sourcegraph/issue/SRCH-1649/reduce-number-of-settings-buttons
Combine the two settings so that the UI is cleaner.
Tested this in the debugger.
[Before (Loom)](https://www.loom.com/share/7ec366dec5be4696b5808522674e1c3f)
[After (Loom)](https://www.loom.com/share/52ec7aa19a5e41edb7b66212e9d648dc)
=> fix(ui): Consolidate the extension settings with the web view settings(SRCH-1649)

vscode/src/chat/agentic/CodyToolProvider.test.ts, vscode/src/chat/agentic/CodyToolProvider.ts, vscode/src/context/openctx.ts
CLOSE https://linear.app/sourcegraph/issue/CODY-5063
Regression caused by https://github.com/sourcegraph/cody/pull/6909
The PR has moved the openCtx controller to be initialized before CodyToolProvider is initialized, causing the current logic to set up openctx provider listeners to fail.
This PR fixes the issue:
Move the OpenCtx provider listener setup from the controller initialization to the CodyToolProvider initialization to ensure proper setup timing and avoid circular dependencies.
- Verify OpenCtx provider listener is properly initialized when CodyToolProvider is initialized
- Confirm no functionality changes in OpenCtx controller behavior
- Ensure existing OpenCtx features continue to work as expected
Ask Cody `summarize my staged changes using the CLI tool` in agentic chat …
=> fix(agentic chat): terminal and openCtx are not registered as tools

vscode/src/chat/chat-view/ChatController.ts, vscode/src/commands/context/file-path.ts, vscode/src/editor/vscode-editor.ts, vscode/test/e2e/chat-atFile.test.ts
Close https://linear.app/sourcegraph/issue/CODY-5029
Fixes issues with range handling in file context and selection:
1. Preserves end character position when getting selection range in VSCodeEditor
2. Improves full file range detection using document validation and text length
3. Updates context source to correctly identify selection-based context
4. Uses editor helper to get active selection instead of direct VS Code API
1. Select partial lines in editor and verify range includes correct end character
2. Test full file selection and verify range is properly detected
3. Verify context items show correct source when from selection
4. Confirm editor selections work correctly through helper function
=> fix(editor): fix range handling for editor selection content

vscode/test/e2e/command-core.test.ts, vscode/webviews/chat/components/WelcomeMessage.test.tsx, vscode/webviews/chat/components/WelcomeMessage.tsx, vscode/webviews/components/promptList/PromptList.tsx
Before, unclickable prompts were still displayed in the WelcomeMessage when a user starts a new chat with Cody. This PR makes it so that only clickable items appear in the PromptList. 
The changes enhance the PromptList component by making it more context-aware with respect to the IDE and prompt modes. This should provide a better user experience, particularly for web-based clients, by showing clickable prompts and excluding non-clickable ones.
Before: 
After:
=> Unclickable links no longer display in Cody WelcomeMessage

.vscode/launch.json
This commit disables the `sourcegraph.cody-testing` extension in the VS Code launch configurations. This prevents the extension from interfering with debugging and testing workflows.
Build from this branch to confirm you are not seeing the following conflicts error when cody-testing is installed:
=> fix(vscode): Disable nightly extension in launch configurations

.github/workflows/generate-changelog.yml
Previously changelog PRs would print the raw new line strings in the PR body (example - https://github.com/sourcegraph/cody/pull/7148) because the changelog generator binary doesn't interpret `\n` properly. Manually adding new lines in the script instead to fix the markdown rendering
Tested on my `kalan/changelog-M68` branch, see [PR](https://github.com/sourcegraph/cody/pull/7148) on the fix
=> chore(release): fix new line rendering in changelog PRs

vscode/package.json, vscode/src/auth/auth.ts, vscode/src/main.ts
This PR adds code for providing Cody credential headers to Sourcegraph Search extension.
To make it more secure (and prevent other hostile extension from stealing credentials) it works based on request/response pattern:
```
Command:   cody.auth.requestEndpointSettings 
[Sourcegraph Search] ---------------------------------------------------> 
↑                                                                       |
|                                                                       |
|                                                                       ↓
<---------------------------------------------------------------- [Cody] 
Command:   sourcegraph.setEndpointSettings
```
Before executing the commands we check if extensions of a given id (`sourcegraph.cody-ai` in case of …
=> Enable credentials synchronisation between Cody and Search extensions

vscode/src/chat/initialContext.ts, vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx
This commit fixes a regression from https://github.com/sourcegraph/cody/pull/7115, which aims to remove the current selection from being added as part of initial mentions chips in first message, but removed the option completely by mistake.
-   Adding the current text selection as a context item provided to the chat webview, but removes it from the initial at-mention context chips
1. Core Functionality Tests:
- Expected: Selection should NOT appear in initial @-mention chips
- Expected: Selection should be available as context in chat webview
- Expected: Selection data exists in context payload
2. Regression Prevention:
- Expected: Chat should initialize normally
- Expected: @-mention chips should work as normal
3. Edge Cases:
4. Integration Testing:
5. UI Verification:
=> fix(chat): remove current selection from initial mention

lib/prompt-editor/src/v2/actions.ts, lib/prompt-editor/src/v2/plugins/atMention.ts, lib/prompt-editor/src/v2/promptInput-react.ts, lib/prompt-editor/src/v2/promptInput.test.ts, lib/prompt-editor/src/v2/promptInput.ts
In this PR I'm reducing the API surface of the state machine and move most of the events related to
value and mentions changes out of it. Hopefully this makes the state machine easier to understand
and to work with.
Now the state machine exposes an `document.update` event whose payload is a function that gets passed
the current editor state and returns a transaction. Note however that these changes actions are still
tested toghether with the state machine in `promptInput.test.ts`. I think it's important to have one
place to test all the expected behavior of the prompt input.
The main reason behind this change is that the current implementation is very much driven by the current
API the `PromptInput` component exposes. But going forward we might change/reduce/expand this API.
Ideally the …
=> chore: Simplify state machine implementation of prosemirror prompt input

.github/workflows/scip-java.yml, jetbrains/src/main/kotlin/com/sourcegraph/cody/inspections/CodyFixHighlightPass.kt
Closes https://github.com/sourcegraph/jetbrains/issues/3087
During creation of TextEditorHighlightingPass VirtualFile can return null. This PR handles this situation.
N/A
=> Handle case when VirtualFile is null

agent/recordings/cody-chat_103640681/recording.har.yaml, agent/recordings/customCommandsClient_509552979/recording.har.yaml, agent/recordings/document-code_965949506/recording.har.yaml, agent/src/__snapshots__/custom-commands.test.ts.snap, agent/src/__snapshots__/document-code.test.ts.snap, agent/src/custom-commands.test.ts, vscode/src/chat/chat-view/prompt.test.ts, vscode/src/prompt-builder/index.test.ts, vscode/src/prompt-builder/index.ts
This commit fixes a bug in the prompt caching feature flag implementation where we were incorrectly using the enrollment event result instead of the actual feature flag value. This caused prompt caching to be enabled for all users regardless of their feature flag state.
Key changes:
- Added proper feature flag value tracking in PromptBuilder using a PromptCachingSetting interface
- Separated the enrollment event logging from the feature flag evaluation
- Ensures the feature flag value is correctly respected while still tracking enrollment events
The fix maintains proper A/B testing capabilities while correctly respecting the intended feature flag distribution for prompt caching functionality.
prompt caching should not be used for users who are not enrolled (non-dot com users)
=> Fix(chat): prompt caching feature flag enrollement

lib/shared/src/chat/preamble.ts, lib/shared/src/index.ts, vscode/src/chat/chat-view/prompt.test.ts, vscode/src/edit/output/response-transformer.ts, vscode/src/edit/output/test-fixtures.ts, vscode/webviews/components/MarkdownFromCody.test.tsx, vscode/webviews/components/MarkdownFromCody.tsx
Issue: https://linear.app/sourcegraph/issue/CODY-4428/markdown-code-blocks-render-incorrectly-due-to-unintended-triple
Ask Cody to generate a readme that documents a file with code examples.
Notice when applying the changes that the code blocks remain
=> [Backport M72] fix(smart-apply): stripping of markdown code blocks (#7105)

agent/recordings/cody-chat_103640681/recording.har.yaml, agent/recordings/customCommandsClient_509552979/recording.har.yaml, agent/recordings/document-code_965949506/recording.har.yaml, agent/src/__snapshots__/custom-commands.test.ts.snap, agent/src/__snapshots__/document-code.test.ts.snap, agent/src/custom-commands.test.ts, vscode/src/chat/chat-view/prompt.test.ts, vscode/src/prompt-builder/index.test.ts, vscode/src/prompt-builder/index.ts
This commit fixes a bug in the prompt caching feature flag implementation where we were incorrectly using the enrollment event result instead of the actual feature flag value. This caused prompt caching to be enabled for all users regardless of their feature flag state.
Key changes:
- Added proper feature flag value tracking in PromptBuilder using a PromptCachingSetting interface
- Separated the enrollment event logging from the feature flag evaluation
- Ensures the feature flag value is correctly respected while still tracking enrollment events
The fix maintains proper A/B testing capabilities while correctly respecting the intended feature flag distribution for prompt caching functionality.
prompt caching should not be used for users who are not enrolled (non-dot com users)
(cherry …
=> Fix(chat): prompt caching feature flag enrollement (#7177)

agent/src/cli/command-bench/strategy-chat-nls.ts
In NLS evals, we weren't getting any results from repos that were directly forked, e.g. https://github.com/sourcegraph-testing/pinned-elasticsearch
Search eval now shows results from forks or archived repos.
=> NLS eval: add fork:yes archived:yes to query

agent/src/AgentWorkspaceDocuments.ts, agent/src/agent.ts, agent/src/vscode-shim.test.ts, agent/src/vscode-shim.ts, agent/vitest.config.ts, lib/shared/src/editor/displayPath.ts, lib/shared/src/index.ts, lib/shared/vitest.config.ts, vscode/src/chat/chat-view/handlers/SearchHandler.ts, vscode/src/repository/remoteRepos.ts
While trying to adapt #6947 to the changes from #6909, I noticed that workspace handling is inconsistent in the agent.
In particular:
- The agent accepts a `workspaceRootUri` upon initialization and stores it on `AgentWorkspaceDocuments`. This value
eventually ends up in `workspaceFolders`.
- We support `workspaceFolder/didChange`, which updates `workspaceFolders` but doesn't affect `workspaceRootUri` in
any way.
- `getWorkspaceFolder` and `asRelativePath` ignore `workspaces` and work directly with `workspaceRootUri`
So it seems that any client that wants to use `workspaceFolder/didChange` will eventually end up with an inconsistent state.
This PR aims to fix that. It removes `workspaceRootUri` and updates all places that used it to work with `workspaceFolders` instead. 
`asAbsolutePath` …
=> fix: Fix inconsistent workspace handling in agent

vscode/package.json, vscode/src/services/telemetry-v2.ts
This commit update the ability to disable telemetry for Enterprise-users only and no longer works for PLG users to ensure we can improve the product.
-   Updated the `cody.telemetry.level` configuration to reflect that telemetry can only be disabled for Enterprise instances.
-   Updated the telemetry provider to disable telemetry if the user is NOT on sourcegraph.com and has telemetry disabled.
This change ensures that telemetry is only disabled for Enterprise users, as telemetry is always enabled for sourcegraph.com users.
Makes sure the description for the telemetry level configuration shows that it is for enterprise only:
Verify telemetry is not disabled even if `cody.telemetry.level` is set to off.
=> refactor(telemetry): opt-out option

vscode/webviews/chat/ChatMessageContent/ChatMessageContent.tsx
CLOSE: https://linear.app/sourcegraph/issue/CODY-5137/improve-thinking-ux-for-new-sonnet-model-in-cody
This commit updates the rendering of "think" content in the chat interface to use Markdown. This improves the formatting and readability of the content.
Ask Claude 3.7 Sonnet a question and confirm the thought process is rendered as markdown:
Before
=> refactor(chat): Render think content as Markdown

vscode/webviews/chat/ChatMessageContent/ChatMessageContent.tsx
**WHAT**
- Add a minus icon for closing the thought process box.
- Change the text color.
- Remove the background color.
- Make the margin smaller.
**WHY**
To improve the thinking process UI.
[Loom](https://www.loom.com/share/5ffec50483f7415eb9b2f431947275f9)
Before
After
=> chore(chat): Add the minus button to the thought process REL-758

vscode/src/autoedits/renderer/inline-manager.test.ts, vscode/src/autoedits/renderer/inline-manager.ts
Improves the extraction of the insert text for the inline renderer from the decoration info. The issue is reproducible on main by enabling inline rendering and going to [https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody-chat-eval/-/blob/code-matc[…]rer-testing-examples/mix-added-removed-unchanged.ts?L53](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody-chat-eval/-/blob/code-matching-eval/edits_experiments/examples/renderer-testing-examples/mix-added-removed-unchanged.ts?L53). Thanks @umpox for spotting this!
CI + new unit tests
=> chore(auto-edit): improve inline renderer `insertText` extraction

jetbrains/src/main/java/com/sourcegraph/find/FindService.java
Simple fix - I just added a null check.
1. Start JetBrains
2. Make sure there is no NPE warning coming from `FindService` in the logs.
=> Fix NPE warning in JetBrains

jetbrains/src/main/java/com/sourcegraph/find/FindService.java, jetbrains/src/main/kotlin/com/sourcegraph/cody/inspections/CodeActionQuickFix.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/inspections/CodyFixHighlightPass.kt
1. Removed `highlight.unregisterQuickFix` - it was not needed, as each highlight pass recreates all highlights and fixups from scratch
2. Moved `highlight.registerFix` execution to the proper thread
3. Added caching, so if location or content of the `ProtocolDiagnostic` object created based on the highlight does not change we reuse the previous `CodeActionQuickFix` without sending anything to the Cody agent
**Scenario 1:** issue which IntelliJ does NOT know how to fix
1. Edit kotlin code and change code like `class MyClass {}` to be `clas MyClass {}` 
2. Click Option + Enter - `Ask Cody to Fix` action should appear, run it
3. Proper fix should be applied by Cody
**Scenario 2:** issue which IntelliJ does know how to fix
1. Edit kotlin code and write code like `val x: String = 1` 
2. Click …
=> Fix threading issues in 'Ask Cody To Fix' feature, add caching

lib/prompt-editor/src/v2/MentionsMenu.module.css, lib/prompt-editor/src/v2/MentionsMenu.tsx, lib/prompt-editor/src/v2/PromptEditor.tsx, lib/prompt-editor/src/v2/promptInput.ts
This PR makes the following changes:
- Add ability for popover to flip vertically if there isn't enough space
towards the bottom to show the menu.
- CSS tweaks for color and menu item size
- Prevent flickering of menu while the user is typing
Closes https://linear.app/sourcegraph/issue/SRCH-1691/expand-menu-other-directions-when-it-doesnt-fit-expanded-down
Manual testing
=> fix: Mentions menu placement/behavior in prompt input v2

lib/prompt-editor/src/PromptEditor.tsx, lib/prompt-editor/src/v2/MentionsMenu.module.css, lib/prompt-editor/src/v2/MentionsMenu.tsx, lib/prompt-editor/src/v2/PromptEditor.tsx, lib/prompt-editor/src/v2/plugins/atMention.ts, lib/prompt-editor/src/v2/promptInput-react.ts, lib/prompt-editor/src/v2/promptInput.test.ts, lib/prompt-editor/src/v2/promptInput.ts, vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx
This PR makes the @-button in the editor toolbar work with the new prompt input.
To do this I added a new method to the editor API, `openAtMentionMenu`, instead of just appending `@`.
Note that unlike the current input we don't have to check whether there is already an `@` at the end of the input
because clicking the button will already 'deactivate' any at-mention that is currently present and we cannot 'reuse'
at-mentions.
Closes https://linear.app/sourcegraph/issue/SRCH-1692/prosemirror-clicking-the-button-doesnt-show-the-mentions-menu
Manual testing. Clicking the @-button with the new input enabled inserts an at-mention and focuses the editor.
The existing input continues to work as expected.
=> fix: Make @-button work in prompt editor v2

vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/chat-view/handlers/EditHandler.ts, vscode/src/chat/diff.test.ts, vscode/src/chat/diff.ts, vscode/webviews/chat/ChatMessageContent/ChatMessageContent.module.css, vscode/webviews/chat/ChatMessageContent/ChatMessageContent.tsx, vscode/webviews/chat/ChatMessageContent/create-buttons.ts
**WHY**
Improve the agentic chat's edit UX experience
**WHAT**
Based off @abeatrix's branch bee/chat-edit
- Closing https://linear.app/sourcegraph/issue/CODY-5136/ui-for-diff-preview-in-chat
- Add line diffs in the UI
- Move the file name to the top of the code block for better readability
=> feat(chat): UI for diff preview in chat CODY-5139

jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentClient.kt
This error has not manifested in any issues yet as it is related to the recent changes.
I noticed that when I quickly open and close a project I get an error:
```
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create light service com.sourcegraph.cody.auth.CodyAuthService because container is already disposed (container=Project(name=runIde-demo, containerState=DISPOSE_COMPLETED, componentStore=/Users/mkondratek/runIdeProjects/runIde-demo) (disposed))
at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
at com.intellij.serviceContainer.ComponentManagerImpl.checkThatCreatingOfLightServiceIsAllowed(ComponentManagerImpl.kt:752)
at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:732) …
```
=> Fix already disposed from CodyAuthService

jetbrains/src/main/kotlin/com/sourcegraph/cody/ui/web/WebviewView.kt, jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt
Fixes #3040
Fixes #2660
unable to reproduce
=> Fix already disposed error from WebviewViewManager (closes #3040)

jetbrains/src/integrationTest/kotlin/com/sourcegraph/cody/util/CodyIntegrationTextFixture.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/action/CodyAgentRestartAction.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/config/notification/CodySettingChangeListener.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/initialization/PostStartupActivity.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/ui/web/WebUIProxy.kt
Fixes https://github.com/sourcegraph/jetbrains/issues/3134.
Fixes https://github.com/sourcegraph/jetbrains/issues/2689.
Fixes https://github.com/sourcegraph/jetbrains/issues/2684.
Fixes https://github.com/sourcegraph/jetbrains/issues/2673.
Fixes https://github.com/sourcegraph/jetbrains/issues/2672.
Fixes https://github.com/sourcegraph/jetbrains/issues/2668.
Fixes https://github.com/sourcegraph/jetbrains/issues/2665.
Fixes https://github.com/sourcegraph/jetbrains/issues/2656.
Fixes https://github.com/sourcegraph/jetbrains/issues/2655.
Fixes https://github.com/sourcegraph/jetbrains/issues/2653.
Fixes https://github.com/sourcegraph/jetbrains/issues/2642.
Fixes https://github.com/sourcegraph/jetbrains/issues/2622.
Fixes https://github.com/sourcegraph/jetbrains/issues/2620.
Fixes …
=> Fix already disposed exception from withAgent

web/demo/App.tsx, web/lib/agent/agent.client.ts, web/lib/components/CodyPromptTemplate.tsx, web/lib/components/CodyWebChat.tsx, web/lib/components/use-cody-agent.ts, web/lib/index.ts
One major problem with cody web right now is that we recreate the cody agent whenever we navigate to a page that shows cody web components.
Worse even, on e.g. the prompts page where we should three prompt inputs, we create three separate instances of the agent.
This initialization step takes time and uses server resources (having already caused Cloudflare overages (https://sourcegraph.slack.com/archives/C05EA9KQUTA/p1737688274086469)).
This PR proposes to only use a single instance of cody agent.
> [!IMPORTANT]
> My understanding of cody web and cody agent is limited. I don't know what implication it has to 'reuse' the same cody agent instance. I've manually tested the typical workflows (chatting, creating new chat, switching files with cody sidebar open, etc), but there are likely …
=> feat: Improve warm cody web startup time

web/package.json
The previous version didn't include TS types due to local issues. This
commit bumpts the version in order to release a fixed version.
`pnpm build` works and `dist/lib` is present
=> chore: Bump cody web version in preparation for publishing

jetbrains/src/intellij2023/kotlin/com/sourcegraph/cody/autocomplete/CodyInlineCompletionProvider.kt, jetbrains/src/intellij2024/kotlin/com/sourcegraph/cody/autocomplete/CodyInlineCompletionProvider.kt
Fixes 
https://linear.app/sourcegraph/issue/BUGS-1365
https://linear.app/sourcegraph/issue/BUGS-1241
https://linear.app/sourcegraph/issue/BUGS-1214
https://linear.app/sourcegraph/issue/BUGS-1240
Signatures of function `getAppSession`:
[IJ 2023.2](https://github.com/JetBrains/intellij-community/blob/idea/232.10203.10/platform/platform-impl/src/com/intellij/openapi/client/ClientSessionsManager.kt#L54): `fun getAppSession(clientId: ClientId = ClientId.current): ClientAppSession?`
[IJ 2025.1](https://github.com/JetBrains/intellij-community/blob/idea/251.18673.35/platform/core-api/src/com/intellij/openapi/client/ClientSessionsManager.kt#L33): `fun getAppSession(clientId: ClientId): ClientAppSession?`
So to fix it it was enough to add an default parameter explicitly.
**IJ 2023.2:**
1. Run IJ …
=> Fix API incompatibility issue in IJ 2025

jetbrains/src/main/kotlin/com/sourcegraph/cody/initialization/PostStartupActivity.kt
Fixes https://linear.app/sourcegraph/issue/CODY-5125/
That change is surpassingly simple because:
1. We already prevent various actions from being invoked if Cody is disabled, .e.g:
```kt
abstract class BaseCommandAction : DumbAwareEDTAction() {
override fun update(e: AnActionEvent) {
super.update(e)
val project = e.project
e.presentation.isVisible =
isCodyEnabled() && project != null && CodyAuthService.getInstance(project).isActivated()
}
// ...
```
2. All explicit calls to Cody are still disabled:
```kt
@JvmStatic
private fun withAgent(
project: Project,
restartIfNeeded: Boolean,
callback: Consumer<CodyAgent>
) {
if (CodyApplicationSettings.instance.isCodyEnabled) { 
// ...
```
So with this changes Cody will start and initiialize, but:
* cody toolbar is hidden
* cody actions are …
=> fix/auth: Extension authorizes Search even if Cody is disabled in site config

vscode/src/commands/execute/terminal.ts
Specifically, `Process options` should not be included if it's empty.
Before:
After:
Manually test it.
=> Clean up the "Ask Cody to Explain" functionality in terminal

vscode/src/services/utils/codeblock-action-tracker.ts, vscode/webviews/chat/ChatMessageContent/ChatMessageContent.tsx
Fixing the bug reported by @abeatrix [in Slack](https://sourcegraph.slack.com/archives/C05AGQYD528/p1740624941556639), where new empty files were being created when opening chats that suggested new files. The issue was due to the smart apply prefetching logic not accounting for the new file and command blocks.
CI
=> fix(smart-apply): do not create new files on prefetching

jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt
Fixes https://github.com/sourcegraph/jetbrains/issues/2302.
Fixes https://github.com/sourcegraph/jetbrains/issues/2335.
Fixes https://github.com/sourcegraph/jetbrains/issues/2359.
Fixes https://github.com/sourcegraph/jetbrains/issues/2441.
Fixes https://github.com/sourcegraph/jetbrains/issues/2454.
Fixes https://github.com/sourcegraph/jetbrains/issues/2514.
Fixes https://github.com/sourcegraph/jetbrains/issues/2538.
Fixes https://github.com/sourcegraph/jetbrains/issues/2570.
Fixes https://github.com/sourcegraph/jetbrains/issues/2579.
Fixes https://github.com/sourcegraph/jetbrains/issues/2580.
Fixes https://github.com/sourcegraph/jetbrains/issues/2648.
Fixes https://github.com/sourcegraph/jetbrains/issues/2659.
Fixes https://github.com/sourcegraph/jetbrains/issues/2680.
Fixes …
=> Fix assertion error from webview (closes #2845)

jetbrains/src/main/kotlin/com/sourcegraph/cody/ui/web/WebPanelTabTitleProvider.kt
Fixes https://linear.app/sourcegraph/issue/BUGS-1339
Fixes https://linear.app/sourcegraph/issue/BUGS-586
1. Open any file in. IntelliJ
2. Hover over the tab name - you should see a tooltip with a file path
=> Fix missing tab tooltips

vscode/src/chat/chat-view/ChatController.ts
We have the /reset command for clearing out chat, but I don't think anyone uses it, and I don't think it's documented well. I suggest removing it.
Manually test it
=> Remove the /reset command

vscode/webviews/chat/components/LastConversation.tsx, vscode/webviews/chat/components/WelcomeMessage.tsx
**WHAT**
Add the latest conversation to the welcome page.
**WHY**
A lot of our competitors have the past conversations on the welcome page. This is a feature with good user experience.
=> feat(chat): Add the latest conversation to the welcome page

jetbrains/src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/chat/OpenChatAction.kt
Fixes https://linear.app/sourcegraph/issue/BUGS-1051
Fixes https://linear.app/sourcegraph/issue/BUGS-1041
Fixes https://github.com/sourcegraph/jetbrains/issues/2357
Fixes https://github.com/sourcegraph/jetbrains/issues/2317
Fixes https://github.com/sourcegraph/jetbrains/issues/2296
This PR contains two changes:
1. Removes `TODO` which in kotlin throws an `NotImplementedError`
2. Adds code which makes sure chat windows always get focus on the input box when it gets opened
1. Open cody chat
2. Click outside of the input box to make sure it has no focus
3. Close Cody Chat panel
4. Hit `Option + Command + 9` (or run `Cody: Open Chat`)
5. Make sure Cody panel is visible and chat input box has focus
6. Click outside of the input box to make sure it has no focus
7. Hit `Option + Command + 9` (or …
=> Fix 'Open Chat' Action

lib/shared/src/sourcegraph-api/utils.ts, vscode/src/chat/chat-view/ChatController.test.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/chat-view/handlers/ChatHandler.ts
CLOSE https://linear.app/sourcegraph/issue/CODY-5168
This resolves an issue where aborting a chat operation and then restarting the session could cause the webview to go blank. The root cause was attempting to add aborted bot messages to a newly created empty ChatBuilder, which requires human messages first. The fix ensures we only create a new ChatBuilder if the current one isn't empty, improves abort handling, and adds better error management in the session saving process.
1. When a chat was aborted, we would clear and restart the session, creating a new empty ChatBuilder
2. Then we'd try to add a bot message (from the aborted operation) to this empty session
3. Since ChatBuilder requires human messages before bot messages, this would throw an error
4. The error would cause the webview …
=> fix(webviews): don't add aborted messages to new chat sessions

jetbrains/src/main/java/com/sourcegraph/website/FileActionBase.java, jetbrains/src/main/java/com/sourcegraph/website/SearchActionBase.java, jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyDisableLanguageForAutocompleteAction.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyEnableLanguageForAutocompleteAction.kt, jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt, jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyLanguageUtil.kt
Fixes https://github.com/sourcegraph/jetbrains/issues/3037.
I noticed there are a few places (actions) using first available editor instead of the editor from the given context. That caused the reported bug and could cause more similar issues. This PR makes Sourcegraph actions use editor provided by the context.
Try the scenario from https://github.com/sourcegraph/jetbrains/issues/3037.
=> Fix "Open Selection in Sourcegraph Web" (closes #3037)

jetbrains/src/main/kotlin/com/sourcegraph/cody/error/CodyErrorSubmitter.kt, jetbrains/src/test/kotlin/com/sourcegraph/cody/error/CodyErrorSubmitterTest.kt
Sometimes we get error reports like this one, were there is no additional debug info and stacktrace does not contain anything Cody related: https://github.com/sourcegraph/jetbrains/issues/2982
This PR fixes two issues with our error reporter:
1. It makes sure we trim stacktrace more intelligently, by always including part which contains cody related stacktrace, if any
2. Stacktraces mostly takes all the space, which with current implementation was always trimming out "Additional debug info". Now instead we always include debug info and at least minimal stacktrace, and as much stacktrace with interesting context as possible.
N/A, automatic tests added.
=> Make sure relevant stacktrace part is included in error reports

jetbrains/src/main/kotlin/com/sourcegraph/cody/ui/web/WebviewPanel.kt
Before this PR, if you open a chat in a new panel (cmd + option + 0), it appears lower than expected in Recent Files list (cmd + E). I may become hard to find it among all the other files. The expected position for the recently modified file is on the top. 
The fix is simple. There is a risk, however. We need an experimental API for it. 
1. Open a few files (project files, lib classes files, scratches, etc)
2. Open New Chat 
3. Review Recent Files - New Chat should appear on the top
=> Fix positioning of file-like chats in Recent Files

web/lib/components/CodyPromptTemplate.tsx
Contributes to https://linear.app/sourcegraph/issue/CODY-5192/fix-broken-referencing-for-prompts-on-s2
Without calling createNewChat the at-mentions menu is not properly
populuated in prompt templates. That's because we don't have a valid
panel ID.
Calling createNewChat solves this but feels like the wrong solution
since we do not actually want to create a new chat.
I think it's fine as a stop-gap solution, since that's what the previous
code this as well, but we should find a more reasonable solution.
> [!NOTE]
> We'll have to create and publish a new cody web release after this.
Created a package locally, installed it into sg client/web and verified that the at-mentions
menu is now properly populated.
=> fix: Fix at-mentions menu in prompt template

package.json
1. Run `pnpm update-agent-recordings`
2. Notice that tests get stuck in watch mode so JetBrains tests never run
1. Run `pnpm update-agent-recordings`
2. Notice that JetBrains tests run
=> chore: agent recordings: Ensure tests are not in watch mode

lib/shared/src/inferenceClient/misc.ts, vscode/src/autoedits/adapters/base.ts, vscode/src/autoedits/adapters/cody-gateway.test.ts, vscode/src/autoedits/adapters/cody-gateway.ts, vscode/src/autoedits/adapters/fireworks.test.ts, vscode/src/autoedits/adapters/fireworks.ts, vscode/src/autoedits/adapters/openai.ts, vscode/src/autoedits/adapters/sourcegraph-chat.test.ts, vscode/src/autoedits/adapters/sourcegraph-chat.ts, vscode/src/autoedits/adapters/sourcegraph-completions.test.ts, vscode/src/autoedits/adapters/sourcegraph-completions.ts, vscode/src/autoedits/adapters/utils.ts, vscode/src/autoedits/autoedits-provider.test.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/test-helpers.ts, vscode/src/completions/default-client.ts
- Bubbles up request/response metadata from auto-edit API adapters to the autoedit provider so we can later propagate this data to the auto-edit debug panel. It would allow us to quickly inspect the network traffic from the debug panel and know precisely what goes in and out without attaching the debugger to the extension. 
- Only Cody Gateway and Sourcegraph completions providers are updated to fully support newly added optional metadata properties since we use them the most (enterprise and PLG setups). We can update the rest of the adapters if needed in a follow-up.
CI
=> chore(auto-edit): capture request/response metadata from auto-edit API adapters

jetbrains/src/main/kotlin/com/sourcegraph/cody/CodyToolWindowFactory.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/OpenWebviewDevToolsAction.kt, jetbrains/src/main/resources/META-INF/plugin.xml
Allows to open devtools at will. Sometimes we want to inspect webview behaviour in the current IDE without restarting it with special env variable. Ability to open devtools easily will be handy. 
1. Hit `Shift shift`
2. Start typing `cody dev`
3. Select action `Cody: Open Dev Tools` to open the devtools for the Cody webview
=> Allow to open devtools as action for an instant debugging caability

lib/shared/src/sourcegraph-api/graphql/client.ts
This PR fixes setting `Accept` header to `'application/json'` which is required by some proxies to work.
Tested with a local reverse proxy.
Prerequisites (YOUR_TOKEN is a token configured for your user at YOUR_INSTANCE):
1. Right cody_setting.json configuration:
```
{
"cody.override.serverEndpoint":  "https://localhost:443",
"cody.auth.externalProviders": [
{
"endpoint": "https://localhost:443",
"executable": {
"commandLine": ["echo '{ \"headers\": { \"Authorization\": \"token YOUR_TOKEN\" } }'"],
"shell": "/bin/bash"
}
},
```
2. Proxy running in the console: mitmproxy -m reverse:https://YOUR_INSTANCE/ -p 443
Then you can start cody, and in the proxy console you should be able to inspect one of the graphql requests and see something like this:
=> Set Accept header to 'application/json' for GraphQL queries

vscode/webviews/chat/ChatMessageContent/ChatMessageContent.module.css, vscode/webviews/chat/ChatMessageContent/ChatMessageContent.story.tsx, vscode/webviews/chat/ChatMessageContent/ChatMessageContent.tsx, vscode/webviews/chat/ChatMessageContent/create-buttons.ts
CLOSE https://linear.app/sourcegraph/issue/CODY-5193/cody-web-copy-button-is-missing-for-code-blocks
This commit refactors the UI for code blocks in chat messages to improve the placement of action buttons (copy, apply, insert) and fixes the issue where copy button is not showing up on web.
The cause of the issue is due to the logic where actionsContainer will only be displayed when previewContainer is available, a regression from https://github.com/sourcegraph/cody/pull/7217.
The fix is to always append available actionsContainer, but also insert the previewContainer before that when available.
Key changes:
- Modified CSS styles in `ChatMessageContent.module.css` to adjust padding, borders, and background colors for code blocks and buttons.
- Updated `ChatMessageContent.tsx` to insert …
=> fix(webview): show copy button in web clients

vscode/src/chat/chat-view/ChatController.test.ts, vscode/src/chat/chat-view/ChatController.ts
This commit improves the chat title generation feature with the following changes:
- Generates a custom title only if the input text is longer than 20 characters.
- Uses the latest Gemini flash-lite model (if available) or the first speedy model as the default for title generation.
- Removes the feature flag check for auto-generating chat titles.
1. Ask a question that has less than 20 characters to confirm chat title in chat history remains unchanged.
2. Ask a question that has more than 20 characters to see if chat title was generated automatically.
3. Instance without speed model is currently not supported. Not reason to use expensive  or reasoning models for small task.
=> feat(chat): removes feature flag requirement for title generation

vscode/webviews/chat/ChatMessageContent/ChatMessageContent.tsx
This commit introduces local storage to persist the open/closed state of the "Thinking & Reasoning Space" in the chat message content.
Key changes:
-   Replaced `useState` with `useLocalStorage` hook to manage the `isOpen` state, persisting it across sessions.
-   Added `tw-min-w-full` class to the details element to ensure it takes up the full width of its container.
1. Ask 3.7 Sonent a question and expect it to have the Thought Process expanded by default
2. Collapse the Thought Process 
3. Open a new chat and ask another question
4. The Thought Process should be now collapsed as your last selected
=> feat(webview): Persist Thinking Space state using local storage

vscode/src/edit/adapters/base.ts, vscode/src/edit/edit-manager.ts, vscode/src/edit/execute.ts, vscode/src/edit/prompt/context.ts, vscode/src/edit/prompt/index.ts, vscode/src/edit/prompt/models/generic.ts, vscode/src/edit/prompt/type.ts, vscode/src/edit/provider.ts, vscode/src/edit/smart-apply-manager.ts, vscode/src/edit/types.ts, vscode/src/edit/utils/edit-models.ts, vscode/src/non-stop/FixupController.ts, vscode/src/non-stop/FixupTask.ts
Prepare for adding the custom model for smart apply. Refactored the code:
- Added a `smart-apply` intent to the edit provider. This makes it simple to differentiate smart apply from other requests and add customizations
- Added a interface for prompt builder and LLM argument provider, so that for fine-tuned model we can have a custom prompt builder instead of having the default one.
- Existing CI to make sure existing functionality does not break
- Played with various features like smart apply, edit, fixing diagnostic error and ensure no feature regression
=> feat/smart-apply: Add smart apply intent and refactor for custom models

vscode/src/services/AuthProviderSimplified.ts
VSC uses two types of login redirect, either by `vscode://sourcegraph.cody-ai` uri if browser and os supports that, or through local http server if it does not.
Url we use to trigger redirect looks like that:
https://sourcegraph.com/users/pkukielka-zvxqk/settings/tokens/new/callback?requestFrom=CODY&tokenReceiverUrl=http%3A%2F%2F127.0.0.1%3A58543%aaaabbbbccccddddeeeeffffgggghhhhhh.auth/openidconnect/login?prompt_auth=github&pc=sams&redirect=/user/settings/tokens/new/callback?requestFrom=CODY&tokenReceiverUrl=http%3A%2F%2F127.0.0.1%3A58543%aaaabbbbccccddddeeeeffffgggghhhhhh
But should be:
https://sourcegraph.com/.auth/openidconnect/login?prompt_auth=github&pc=sams&redirect=%2Fuser%2Fsettings%2Ftokens%2Fnew%2Fcallback%3FrequestFrom%3DCODY%26tokenReceiverUrl%3Dhttp%3A%2F%2F127.0.0.1%3A63992%a …
=> Fix token-receiver url generation logic

lib/shared/src/experimentation/FeatureFlagProvider.ts, vscode/webviews/Chat.tsx, vscode/webviews/CodyPanel.tsx, vscode/webviews/chat/components/WelcomeMessage.tsx, vscode/webviews/prompts/PromptsTab.module.css, vscode/webviews/prompts/PromptsTab.tsx
Part of https://linear.app/sourcegraph/issue/SRCH-1734/issue-with-migrating-local-custom-commands-for-rakuten
Prior to this PR we still had an old new prompt feature flag for prompt migration. It's been almost 5 months since the new prompt replaced cody commands, I'm removing this flag in order to simplify migration for all customers who still may have some commands in their user configs. Also I noticed some small layout shift there, fixed it too.
Note: that migration run keys haven't been changed so users who ran this migration before won't see this widget anymore (even if they have added somehow new personal commands in their configs) 
| Welcome screen | Prompts Tab |
| --------  | -------- |
| <img width="1124" alt="Screenshot 2025-03-05 at 13 31 38" …
=> Remove CodyPromptsV2 (and fix prompts migration layout)

.github/workflows/ci.yml
This is taking 2mins (wtf) to install on windows and doesn't seem to be used in `test-unit`
Github CI `test unit`job is happy
=> google auth / setup-gcloud seems unused in test-unit steps

.github/workflows/ci.yml
This fixes the windows unit test job to not timeout and complete about ~3 mins faster
* Use restore and save cache actions - so that we cache sooner
* change cache key to **not** include the node version, this allows the cache to be reused by other windows runners
CI
=> fix(ci): improve windows unit-test job and cache

lib/prompt-editor/src/mentions/mentionMenu/MentionMenuItem.tsx, vscode/src/chat/initialContext.ts, vscode/src/context/openctx.ts, vscode/src/context/openctx/remoteRepositorySearch.ts, vscode/test/e2e/common.ts, vscode/test/e2e/mention-repository.test.ts, web/lib/components/CodyPromptTemplate.tsx, web/lib/components/CodyWebChat.tsx
Make it clear when you tag in repository context, it means "search this repository" and update the icons to indicate that.
Before:
After:
Appearance only
=> at-mention menu item naming changes

vscode/package.json, vscode/test/e2e/chat-keyboard-shortcuts.test.ts, vscode/test/e2e/enterprise-server-sent-models.test.ts, vscode/test/e2e/utils/server-models.ts, vscode/webviews/components/modelSelectField/ModelSelectField.tsx, vscode/webviews/components/shadcn/ui/toolbar.tsx, vscode/webviews/tabs/TabsBar.test.tsx, vscode/webviews/tabs/TabsBar.tsx
**WHAT**
1. Fix React warnings caused by [relocating the model selector](https://github.com/sourcegraph/cody/pull/7322)
- Warning: React does not recognize the `popoverContentProps` prop on a DOM element
- Warning: Nested Buttons
- There are also other pre-existing warnings, but this PR does not fix them
2. Remove `cmd+N` keyboard shortcut as it is not compatible for other non vscode IDEs
**WHY**
Good practice to avoid React warnings. This prevents us from having bigger problems in the future
**CONTEXT**
Slack: https://sourcegraph.slack.com/archives/C05AGQYD528/p1741247210218679
Model Selector PR: https://github.com/sourcegraph/cody/pull/7322
**1. New e2e test `keyboard shortcuts cmd+M opens model selector`**
- Run `pnpm -C vscode test:e2e chat-keyboard-shortcuts.test.ts` and make sure …
=> fix(chat): Fix React warnings caused by relocating the model selector 

vscode/src/autoedits/analytics-logger/analytics-logger.test.ts, vscode/src/autoedits/analytics-logger/analytics-logger.ts, vscode/src/autoedits/autoedits-provider.test.ts, vscode/src/completions/analytics-logger.ts
Update `billingMetadata` for autoedit and completion events that should not be billable, to ensure accurate categorization.
updates:
- `cody.autoedit:discarded`
- `cody.completion:noResponse`
- `cody.completion:synthesizedFromParallelRequest`
to not be billable events.
CI  + tested locally
The events listed above do not have `billingMetadata`, and confirming the other completion events like suggested, accepted are unaffected.
=> chore(telemetry): update `billingMetadata` for autoedit and completion events

agent/scripts/minor-release.sh
- Adds a basic shell script for releasing minor versions of the agent CLI with a plan to reference it in the Cody Release Captain playbook. Here's [the updated section](https://www.notion.so/sourcegraph/Release-Captain-Playbook-13ba8e112658800d877ce7b4e8413935#1ada8e1126588036a4fcd1eede5c7870) of the playbook.
- Nothing fancy; we can tweak it in follow-up PRs to improve it based on feedback from the release captains who'll be using it.
CI + manually tested this script locally.
=> chore(agent): add minor version release script

agent/src/cli/command-auth/command-login.ts
Fixes CODY-5251
Previously, the command `cody auth login --web` failed because we used an empty access token to authenticate against Sourcegraph. This commit fixes the bug, and updates a logging statement to stop logging the access token.
Run the following command and validate it works as expected
```
❯ pnpm i
❯ cd agent
❯ pnpm agent:build
❯ pnpm agent:skip-root-build auth login --web
```
=> fix(cody): use correct access token when authenticating

jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentClient.kt, vscode/src/services/AuthProvider.ts
Instead of using `window_didChangeContext` notification to receive auth status we now use dedicated endpoint `authStatus/didUpdate` which contains a full set of auth data. 
**Test Case 1:**
1. Make sure you are logged into Cody
2. Run JB app
3. Check that Cody logs in normally
**Test Case 2:**
1. Log out of Cody
2. Restart JB
3. Go through the login process
4. Check to see if Cody has gone into logged-in state
**Test Case 3:**
1. Make sure you are logged into Cody
2. Run JB app
3. Use 'Switch Account' action in Codi's user menu to change account
4. After changing the account, Cody should remain logged in
=> Updating CodyAuthService from authStatus/didUpdate

agent/recordings/auth_2503977039/recording.har.yaml, agent/recordings/cody-chat_103640681/recording.har.yaml, agent/recordings/customCommandsClient_509552979/recording.har.yaml, agent/recordings/defaultClient_631904893/recording.har.yaml, agent/recordings/document-code_965949506/recording.har.yaml, agent/recordings/edit_1541920145/recording.har.yaml, agent/recordings/fix_3001320056/recording.har.yaml, agent/src/__snapshots__/custom-commands.test.ts.snap, agent/src/__snapshots__/document-code.test.ts.snap, agent/src/__snapshots__/index.test.ts.snap, agent/src/cli/__snapshots__/command-chat.test.ts.snap, agent/src/edit.test.ts, agent/src/index.test.ts, lib/shared/src/chat/chat.test.ts, lib/shared/src/chat/chat.ts, lib/shared/src/sourcegraph-api/clientConfig.ts, lib/shared/src/sourcegraph-api/completions/client.ts, lib/shared/src/sourcegraph-api/completions/utils.ts, lib/shared/src/sourcegraph-api/siteVersion.test.ts, lib/shared/src/sourcegraph-api/siteVersion.ts, recordings/rewrite-query_2689977722/recording.har.yaml, vscode/src/completions/nodeClient.ts, vscode/src/local-context/rewrite-keyword-query.test.ts, vscode/test/e2e/chat-input.test.ts, vscode/test/fixtures/mock-server.ts
CLOSE https://linear.app/sourcegraph/issue/CODY-5233
This commit refactors the Cody API version determination to rely on the site version, aligning with the server support.
- Removes the `latestCodyClientConfig` variable and related functions from `clientConfig.ts`.
- Updates `clientConfig.ts` to set the latest Cody API version using `setLatestCodyAPIVersion` from `siteVersion.ts`.
- Updates `completions/utils.ts` to import `serverSupportsPromptCaching` from `siteVersion.ts`.
- Updates `siteVersion.ts` to include `getLatestSupportedCompletionsStreamAPIVersion`, `setLatestCodyAPIVersion`, and `serverSupportsPromptCaching` functions.
- Updates `siteVersion.test.ts` to test the new logic.
- Updates `inferCodyApiVersion` to use `DefaultMinimumAPIVersion` and handle pre-release versions.
This …
=> fix(gateway): use latestCodyClientConfig for chat api version  

jetbrains/src/main/kotlin/com/sourcegraph/cody/edit/EditCommandPrompt.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/edit/actions/BaseEditCodeAction.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/edit/actions/EditCodeAction.kt
We got feedback that it is tedious to delete the last instruction in the input text box. However because the popup auto-dismisses as you scroll around or move your cursor, we need to save your partial input sometimes. This change:
- Saves partial input if the dialog is cancelled (ESC, click outside, etc.)
- After an edit completes, the instruction box is **empty** for the next edit (but you can use up/down for edit history as usual)
- If you "retry" an edit, the instruction box is pre-populated with that edit's instruction
Fixes CODY-5230.
This also simplifies and fixes the logic and control flow around this dialog a bunch:
- The message bus connection was unused and has been removed.
- The popup is removed from the project's user data when it is closed.
- Instead of hammering …
=> fix/edits: After a successful edit, the edit instruction field is empty #jetbrains

lib/shared/src/sourcegraph-api/siteVersion.test.ts, lib/shared/src/sourcegraph-api/siteVersion.ts
I noticed that some instances were still using api-version 1, and went to dig in why that is. Turns out some edge-case in our versioning scheme wasn't honored (branch name prefix), so I fixed that.
Test plan: Added tests that fail before the code change.
=> api: Fix version detection for non-main-branch images

vscode/src/autoedits/autoedits-provider.test.ts, vscode/src/autoedits/autoedits-provider.ts
https://github.com/user-attachments/assets/5d105794-516b-44dd-b81f-b0c991c835a1
Fixes an issue where we attempt to suggest an auto-edit that could conflict with the completion menu in a bad way. E.g. it may delete or add code that doesn't reflect the selected item in the menu. If the user was to accept this item with Tab, the edit would be accepted including the unwanted code.
- Unit tests
- Manual testing with completion items
=> fix(autoedit): Fix conflict between suggestions and completion menu

jetbrains/src/main/java/com/sourcegraph/config/GoToPluginSettingsButtonFactory.java, jetbrains/src/main/java/com/sourcegraph/find/FindPopupPanel.java, jetbrains/src/main/java/com/sourcegraph/find/HeaderPanel.java
There was an issue with the action... 
* PR #7368:
`main` ← `mkondratek/chore/cleanup-icons`
* **PR #7369 (THIS ONE)**:
`mkondratek/chore/cleanup-icons` ← `mkondratek/fix/gear-action`
1. right click in the editor
2. Sourcegraph / Find with Sourcegraph...
3. click the gear icon 
Before:
nothing
After this PR:
setttings file opens
=> Fix gear action in Find with Sourcegraph dialog

agent/src/AgentAuthHandler.test.ts, agent/src/AgentAuthHandler.ts, agent/src/vscode-shim.ts
Fixes https://linear.app/sourcegraph/issue/QA-521/
Follow-up after https://github.com/sourcegraph/cody/pull/7338 which broke JB.
In fact we could get rid of that whole logic and use the same code for VSC and agent, but that would cause compatibility issues. For migration we would need to introduce new referral codes on the server side, and that probably would complicate some telemetry, etc.
So a quick fix for now to not make things worse.
1. Open IJ
2. Sign off if needed, sign in using GitHub provider.
3. Sign off , sign in using instance url provider.
In both cases login page should appear and redirection should work as expected.
=> Fix redirection handling in JetBrains

vscode/src/autoedits/adapters/base.ts, vscode/src/autoedits/adapters/cody-gateway.test.ts, vscode/src/autoedits/adapters/cody-gateway.ts, vscode/src/autoedits/adapters/fireworks.test.ts, vscode/src/autoedits/adapters/fireworks.ts, vscode/src/autoedits/adapters/openai.ts, vscode/src/autoedits/adapters/sourcegraph-chat.test.ts, vscode/src/autoedits/adapters/sourcegraph-chat.ts, vscode/src/autoedits/adapters/sourcegraph-completions.test.ts, vscode/src/autoedits/adapters/sourcegraph-completions.ts, vscode/src/autoedits/adapters/utils.ts, vscode/src/autoedits/analytics-logger/analytics-logger.test.ts, vscode/src/autoedits/analytics-logger/analytics-logger.ts, vscode/src/autoedits/autoedits-provider.test.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/test-helpers.ts, vscode/src/completions/default-client.ts, vscode/webviews/autoedit-debug/autoedit-data-sdk.ts, vscode/webviews/autoedit-debug/sections/NetworkRequestSection.tsx
- Propagates the abort signal to the fetch call used for auto-edit requests, ensuring that we cancel them based on the logic in the auto-edit provider. This should reduce the load on our inference deployment.
- Instead of throwing an error on cancellation, we return an object indicating to the auto-edit provider that the request was cancelled. This allows us to maintain the same data flow for the integration with the analytics logger and the debug panel.
- Closes [CODY-5306: Cancel redundant network requests](https://linear.app/sourcegraph/issue/CODY-5306/cancel-redundant-network-requests)
CI + manually tested with the auto-edit debug panel + updated unit tests
=> feat(auto-edit): cancel redundant requests

vscode/src/autoedits/autoedits-config.ts
- Reduces the context limits:
- Document prefix and suffix from 5000 to 1000. 
- Recent edits from 1500 to 2500
- Diagnostics retriever from 500 to 250
- No quality evaluations are available for this change yet. We will work on it with @hitesh-1997 in the next couple of weeks. This change's goal is to reduce latency and is based on the idea that the document prefix and suffix are less important than recent edits. Since the model is relatively small, it likely does not benefit from a long context window. For example, in autocomplete, our total context limit is 2k tokens. The diagnostics retriever limit is reduced based on manual testing, seeing that most of the errors are not actionable for the model, and usually, having a couple of them is enough.
- Closes [CODY-5303: Decrease the context …
=> feat(auto-edit): reduce context size

vscode/src/context/openctx.test.ts, vscode/src/context/openctx.ts
Issue: The Remote Directories provider is hidden on the latest versions of Cody. https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1740424611276459
The issue was that the `isValidSiteVersion` was always false. Most probably due to the stale closure issue. 
I have reworked the logic and updated the tests and it appears now. 
- Open Cody
- Do @
- Remote Directories provider should be visible for non-Dotcom users.
=> Fix Remote Directories Provider Valid Site Version Logic

lib/shared/src/experimentation/FeatureFlagProvider.ts, lib/shared/src/index.ts, lib/shared/src/sourcegraph-api/siteVersion.ts, vscode/src/edit/edit-context-logging.ts, vscode/src/edit/edit-manager.ts, vscode/src/edit/prompt/constants.ts, vscode/src/edit/prompt/smart-apply/selection.ts, vscode/src/edit/prompt/smart-apply/selection/custom-model.ts, vscode/src/edit/provider.ts, vscode/src/edit/smart-apply-manager.ts, vscode/src/services/utils/codeblock-action-tracker.ts
- Each call to `currentSiteVersion` takes about ~500ms. This was happening for both the selection and apply phase and for other edit providers. The PR adds async observing the smart apply values and using that for both selection and apply. This saves ~1 sec total.
- Add a debugger breakpoint at the site version call, and check we are fetching this async.
=> feat(smart-apply): Prefetch the site version and enable for jetbrains

lib/shared/src/chat/chat.ts, lib/shared/src/models/client.ts, lib/shared/src/models/sync.test.ts, lib/shared/src/models/sync.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/chat-view/handlers/registry.ts, vscode/webviews/chat/cells/messageCell/human/editor/toolbar/ModeSelectorButton.tsx
https://github.com/sourcegraph/cody/pull/7332 to add agentic chat back to model selector.
Also only shows Agentic mode from mode selector for S2 users for internal dogfood
Revert https://github.com/sourcegraph/cody/pull/7332
=> add agentic chat back to model dropdown

vscode/webviews/autoedit-debug/AutoeditDebugPanel.tsx, vscode/webviews/autoedit-debug/autoedit-data-sdk.ts, vscode/webviews/autoedit-debug/autoedit-ui-utils.ts, vscode/webviews/autoedit-debug/components/AutoeditDetailView.tsx, vscode/webviews/autoedit-debug/components/AutoeditListItem.tsx, vscode/webviews/autoedit-debug/sections/CodeToRewriteDataSection.tsx, vscode/webviews/autoedit-debug/sections/NetworkRequestSection.tsx, vscode/webviews/autoedit-debug/sections/TimelineSection.tsx, vscode/webviews/components/codeSnippet/CodeSnippet.tsx
- Adds inference time to the list view of the debug panel.
- Adds an ability to filter out items from the list view the stage they reached. (e.g., show only suggested+ items).
- Adds code to rewrite data section that allows inspecting parts of the prompt (used for the dynamic document prefix and suffix debugging).
- Mostly implemented with Claude 3.7 and agents 😛
- Closes [CODY-5330: Add inference time to the auto-edit debug panel list view](https://linear.app/sourcegraph/issue/CODY-5330/add-inference-time-to-the-auto-edit-debug-panel-list-view)
CI + manual testing with the debug panel locally
=> chore(auto-edit): add inference time to the debug panel

vscode/src/autoedits/analytics-logger/analytics-logger.test.ts, vscode/src/autoedits/analytics-logger/analytics-logger.ts
Modify the analytics logger to avoid logging discarded autoedit events until the issue with them overfiring is fixed.
CI and locally tested
=> chore/telemetry: Stop logging discarded autoedit events

vscode/src/chat/chat-view/ChatsController.ts, vscode/src/chat/chat-view/tools/edit-history.ts, vscode/src/main.ts
This commit initializes the edit tool history feature, but only for S2 users. This is done by:
-   Moving the `initializeEditToolHistory` function to `ChatsController.ts`
-   Conditionally initializing the edit source control UI based on the user's authentication status and endpoint.
-   Updating the `initializeEditToolHistory` function to return disposables.
-   Removing the initialization from `main.ts`
This ensures that the edit history feature is only available to the intended users during dogfood period.
1. Log into S2 and confirm you can see the Cody Edit History panel in your source control tab
2. Log into a non-S2 instance and restart VS Code
3. Verify the Cody Edit History panel  doesn't show up
=> fix(edit): initialize edit tool history for S2 only

lib/shared/src/configuration.ts, vscode/src/autoedits/adapters/create-adapter.ts, vscode/src/autoedits/adapters/inceptionlabs.ts, vscode/src/autoedits/adapters/utils.ts, vscode/src/autoedits/prompt/default-prompt-strategy.ts, vscode/src/autoedits/prompt/prompt-utils.test.ts, vscode/src/autoedits/prompt/prompt-utils.ts, vscode/src/autoedits/prompt/short-term-diff-prompt-strategy.ts
- Implements the experimental auto-edit adapter for the diffusion coding model hosted by https://www.inceptionlabs.ai/
- The model is not fine-tuned on our data yet. I didn't spend much time prompt engineering the adapter to get stable results, so the model often does not follow instructions precisely and does not suggest completions as much as I would expect.
- Latency can be viewed in the auto-edit debug panel.
- Closes [CODY-5317: Implement experimental support for the diffusion model from InceptionLabs](https://linear.app/sourcegraph/issue/CODY-5317/implement-experimental-support-for-the-diffusion-model-from)
- CI
- Manually test by using local override settings for auto-edit. You can find the InceptionLabs token in 1Password.
```json
"cody.experimental.autoedit.config.override": { …
```
=> feat(auto-edit): experimental inceptionlabs adapter

vscode/src/autoedits/analytics-logger/analytics-logger.test.ts, vscode/src/autoedits/analytics-logger/analytics-logger.ts, vscode/src/autoedits/analytics-logger/types.ts, vscode/src/autoedits/autoedits-provider.test.ts, vscode/src/autoedits/renderer/inline-manager.ts, vscode/src/autoedits/renderer/manager.ts
- @umpox, when an inline completion is accepted, the `onDocumentSelectionChange` callback is triggered before the acceptance callback, which means we were marking suggestions as rejected right after they were accepted and right before the acceptance callback was triggered. For some reason, the order of the callbacks is different in E2E tests (I tried to capture this bug there). But you can verify the unexpected behavior locally in the extension host with the auto-edit debug panel by generating suggestions with inline completions only and accepting them.
- Adds reject reason fields to the analytics events.
- Closes [CODY-4719: Investigate analytics logger invalid state transitions](https://linear.app/sourcegraph/issue/CODY-4719/investigate-analytics-logger-invalid-state-transitions)
CI + …
=> chore(auto-edit): fix accept/reject analytics events

jetbrains/src/main/kotlin/com/sourcegraph/config/ConfigUtil.kt, jetbrains/src/main/kotlin/com/sourcegraph/config/GlobalCodySettings.kt
This is special usage feature, which provide JetBrains toolbox with option to manipulate cody settings.
It was requested by one of our existing customers.
In addition to reading settings from project-level `cody_settings.json` this PR add support for `%APPDATA%/JetBrains/<product><version>/options/cody.xml` file, which contains single string entry which include whole additional json config.
For json config like:
```
{
"cody.override.serverEndpoint": "https://sourcegraph.test:443",
}
```
Content of  `cody.xml` should be:
```
<application>
<component name="GlobalCodySettings">
<option name="jsonConfig" value="{&#10;  &quot;cody.override.serverEndpoint&quot;:  &quot;https://sourcegraph.test:443&quot;,&#10;}" />
</component>
</application>
```
Standard xml escaping rules applies.
1. Create …
=> Add support for global Cody config

vscode/webviews/chat/cells/contextCell/ContextCell.tsx
- Change "was" to "were" and "it" to "they" when multiple items are excluded due to token limits.
- Removed extra period showing up when view the context filter message.
cd vscode
pnpm storybook
visit http://localhost:6007/?path=/story/cody-contextcell--default
Check proper warning messages
=> fix(chat): Improve excluded context warning message

vscode/src/chat/chat-view/ChatController.ts
CLOSE https://linear.app/sourcegraph/issue/CODY-5389/in-agentic-mode-never-show-the-smart-apply-bar
Disables the smart apply codeblock toolbar when the experimental agentic chat feature is enabled. This prevents potential conflicts or usability issues between the two features.
1. Switch 2 S2 and ask cody to output a code block
2. confirm the code block doesnt come with a smart apply button
=> feat(chat): Disable smart apply toolbar in agentic chat

lib/shared/src/inferenceClient/misc.ts, lib/shared/src/llm-providers/ollama/completions-client.ts, vscode/src/autoedits/adapters/cody-gateway.test.ts, vscode/src/autoedits/adapters/fireworks.test.ts, vscode/src/autoedits/adapters/sourcegraph-completions.ts, vscode/src/autoedits/adapters/utils.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/completions/default-client.ts, vscode/src/completions/fast-path-client.ts, vscode/src/completions/get-inline-completions-tests/helpers.ts
- The diff is much smaller with hidden whitespace changes.
- Closes [CODY-5399: Fix network request abort error propagation to the auto-edit provider](https://linear.app/sourcegraph/issue/CODY-5399/fix-network-request-abort-error-propagation-to-the-auto-edit-provider)
- Wraps `fetch` calls into try/catch blocks to catch abort errors that happen before we reach the network.
- Updates the code completions API clients to `yield` abort errors from the generator as a part of the iteration loop instead of ending the generator and `return`ing the value which required an additional check which we do not have in many places: 
```ts
const finalResult = await generator.next();
if (finalResult.done) {
console.log("Final return value:", finalResult.value);
}
```
This ensures that `for await (const msg …
=> chore(auto-edit): ensure aborts are propagated to the provider

vscode/src/services/AuthProvider.ts
Previously, `cody.auth:connected` events were tagged as billable events through `billingMetadata`. Now, this PR removes  this categorization from the `cody.auth:connected` telemetry event. related [thread](https://sourcegraph.slack.com/archives/C06358CMSRM/p1740785635874799)
CI
=> chore(telemetry): Remove `billingMetadata` from auth telemetry event

vscode/src/chat/chat-view/handlers/AgenticHandler.ts
This commit updates the agentic chat handler to use a different LLM model for the first turn of a conversation compared to subsequent turns. The first turn will use `anthropic::2024-10-22::claude-3-7-sonnet-extended-thinking` and subsequent turns will use `anthropic::2024-10-22::claude-3-7-sonnet-latest`. This allows for extended thinking on the first turn.
When running the agent, confirm that:
1. The first message you sent in aan empty chat should show you there is a thinking process 
2. All the follow up should not have the Thought Process header to indicate the thinking mode l is not being used
=> feat(agentic chat): use different models for first turn and subsequent turns

jetbrains/src/integrationTest/kotlin/com/sourcegraph/cody/edit/DocumentCodeTest.kt, jetbrains/src/integrationTest/kotlin/com/sourcegraph/cody/util/CodyIntegrationTextFixture.kt, jetbrains/src/integrationTest/resources/recordings/integration-test_2927926756/recording.har.yaml, jetbrains/src/main/java/com/sourcegraph/cody/vscode/IntelliJTextDocument.java, jetbrains/src/main/java/com/sourcegraph/website/FileActionBase.java, jetbrains/src/main/java/com/sourcegraph/website/SearchActionBase.java, jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/protocol_extensions/ProtocolTextDocument.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/Utils.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/ignore/IgnoreOracle.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/inspections/CodyFixHighlightPass.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/listeners/CodyCaretListener.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/listeners/CodyFileEditorListener.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/listeners/CodySelectionListener.kt, jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt, jetbrains/src/test/kotlin/com/sourcegraph/cody/agent/protocol/ProtocolTextDocumentTest.kt
Fixes https://linear.app/sourcegraph/issue/BUGS-638
1. Removed uri conversions which were [potentially harmful ](https://github.com/sourcegraph/jetbrains/issues/3080)and hard to reason about (`FileSystems.getDefault().getPath(file.path).toUri().toString()`)
2. Skip processing documents with schema other than `file://` (if there is no schema specified `file://` is assumed)
3. Skip processing non writable documents
4. Fix WSL handling
N/A
1. Automatic test added
5. I verified in debugger we no longer send content of e.g. jar files
=> Improve URI handling

vscode/src/chat/chat-view/ContextRetriever.ts
closes: https://linear.app/sourcegraph/issue/CODY-5282/current-selection-mention-not-fetching-context-from-code-range
The current selection context item was ignored while converting to structured mentions. 
- Mention current selection
- Make sure the context file is included
=> Fix current selection in ContextRetriever

lib/shared/src/sourcegraph-api/userProductSubscription.ts
Fixes https://linear.app/sourcegraph/issue/QA-488
Since [that change](https://github.com/sourcegraph/cody/commit/dba304ff31f183d00db50baa4d07ad4e3767eab5) `AuthStatus` does not contain `userCanUpgrade` flag. Thus just relying on `AuthStatus` when updating `userProductSubscription` is working if endpoint is changing, but not otherwise.
QA bisect points to my PR as the source of the problem, but I think that was strictly because of subtle changes in timing/debounce.
I suspect previously it could register `pendingValidation` state in between, and thus registering the change, and now it doesn't. Removing `distinctUntilChanged` fixes the problem.
As described in https://linear.app/sourcegraph/issue/QA-488
1. Switch acc from free to pro (or from pro to free on the same account)
2. Pro label …
=> Update subscription type when switching acc without endpoint change

vscode/.gitignore
Probably shouldn't have removed from the PR here: https://github.com/sourcegraph/cody/pull/7430
Ensures this doesn't stick around in git logs
N/A ignore change
=> chore(tutorial): re-add gitignore

vscode/src/configuration.ts
The `cody.autocomplete.enabled` no longer exists. As a result, the override [condition](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/configuration.ts?L60-62) is always false.
- unit testing only
=> CODY-4631: remove compatibility override after experimental release

jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt
This reverts commit a31acd06580fe300a2623d4baf75578fb0da54cd.
I'm reverting this as we get few reports of multiple agent processes being spawned, and this is only recent change in this area of code. 
There is a chance that my fix is solving the underlaying issue:
https://github.com/sourcegraph/cody/pull/7466
But if my fix is proper, then we do no need `WebUIService.getInstance(project).reset()` in both `start` and `stop` methods.
I believe before my PR it was sometimes beneficial because there was race between `stop` and `start` code.
But there is also a chance that it was breaking something is timing was slightly different.
N/A
=> Revert "Fix assertion error from webview (closes #2845) (#7257)"

lib/shared/src/models/model.ts, lib/shared/src/models/modelsService.test.ts, lib/shared/src/models/modelsService.ts
This PR fixes a critical issue where reasoning models could be incorrectly set as the default model for Edit operations, causing the application to break for users.
This commit addresses an issue where reasoning models could be incorrectly set as the default model for Edit operations. The problem occurred because when Edit model is not available, Edit would fallback to the `firstModelUserCanUse` logic which doesn't filter out reasoning models for Edit usage. This could cause Inline Edit to use reasoning model even when they are not assigned for Edit usage.
The issue occurred in the `getDefaultModel` and `getDefaultEditModel` methods in `modelsService.ts`. When a user didn't have a selected model preference for Edit and the server didn't provide a default Edit model, the code would use the …
=> fix(models): prevent reasoning models from being set as default model

lib/shared/src/experimentation/FeatureFlagProvider.ts, vscode/src/chat/chat-view/ChatController.ts
This commit introduces an internal feature flag, `NextAgenticChatInternal`, to control the availability of the new agentic chat experience. This flag is intended for internal use only and will not be exposed to users.
-   Adding the `NextAgenticChatInternal` feature flag to the `FeatureFlag` enum.
-   Updating the `ChatController` to use the new feature flag to enable the experimental agentic chat features.
Simple change. Check if feature flag is correct
=> feat(agentic chat): add internal feature flag

vscode/src/commands/scm/source-control.ts
Closes CODY-5281. This PR depends on https://github.com/sourcegraph/cody/pull/7385.
This commit changes the order in which the `flash` and `flash-lite` models are assigned to `this.model` in `CodySourceControl`.
The `flash` model is now prioritized over the `flash-lite` model. This ensures that the more capable `flash` model is used when available, improving the quality of the generated commit message.
Manually test by comparing the performance and quality for both.
=> Commit message gen: prioritize 'flash' model over 'flash-lite'

vscode/src/autoedits/prompt/default-prompt-strategy.test.ts, vscode/src/autoedits/prompt/default-prompt-strategy.ts, vscode/src/autoedits/prompt/prompt-cache-optimized-v1.test.ts, vscode/src/autoedits/prompt/prompt-cache-optimized-v1.ts, vscode/src/autoedits/prompt/prompt-utils.test.ts, vscode/src/autoedits/prompt/prompt-utils.ts, vscode/src/autoedits/prompt/short-term-diff-prompt-strategy.test.ts, vscode/src/autoedits/prompt/short-term-diff-prompt-strategy.ts
Our prompt strategy usually consists of bulding `PromptStrings` together. When we don't have valid information to prompt we return an empty string. I think this is OK and a good way to build the prompts, but we had some cases where we were unnecessarily padding empty strings with new lines. This fixes that.
Tested with unit tests, see the updated snapshots
=> fix(auto-edit): Remove unnecessary prompt whitespace

vscode/src/autoedits/autoedit-onboarding.ts, vscode/src/completions/inline-completion-item-provider.ts, vscode/src/services/LocalStorageProvider.ts
- PR adds the onboarding setup for the eligible auto-edit users for the beta rollout.
- By default the `cody.suggestions.mode` is set to `autocomplete` for most of the users, this enrolls all the eligible users to `auto-edit` one time, and displays a notification, that they have been switched to `auto-edits`.
- Switching between modes in the debug mode and observe the notification.
- Check the telemetry event for the onboarding notification `cody.autoedit:beta-enrolled`
=> feat(auto-edit): Add beta onboarding for auto-edit

vscode/webviews/chat/cells/toolCell/ToolStatusCell.tsx
CLOSE https://linear.app/sourcegraph/issue/CODY-5441/bug-fix-view-goes-blank-when-display-terminal-output
Memorize the terminal lines to resolve an error
Cause: The useMemo dependency array only includes output.content, but the function is using convertToTerminalLines(output.content). If convertToTerminalLines is not stable (i.e., it creates a new reference each time), this could cause issues.
The key changes are:
1. Moved the useMemo for terminal lines outside of the conditional rendering
2. Added proper dependency on output?.outputType as well as output?.content
3. Added null/undefined checks with optional chaining
This should resolve the React error by ensuring the useMemo hook has all the dependencies it needs and is used consistently.
Verified with Alex that the fixed worked. To test …
=> fix(vscode): Extract terminal lines outside of conditional render in ToolStatusCell

vscode/test/e2e/chat-keyboard-shortcuts.test.ts, vscode/webviews/chat/cells/messageCell/human/editor/toolbar/ModeSelectorButton.test.tsx, vscode/webviews/chat/cells/messageCell/human/editor/toolbar/ModeSelectorButton.tsx, vscode/webviews/chat/cells/messageCell/human/editor/toolbar/ModeSelectorField.stories.tsx, vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx
FIX https://linear.app/sourcegraph/issue/QA-545
This commit fixes an issue where users could use the keyboard shortcut (⌘. or Ctrl+.) 
to cycle through and select chat modes (intents) that should be disabled for them based 
on their permission level.
Added e2e test for dotcom users.
=> fix(chat): prevent keyboard shortcut from selecting disabled chat modes

vscode/src/autoedits/analytics-logger/analytics-logger.test.ts, vscode/src/autoedits/analytics-logger/analytics-logger.ts, vscode/src/autoedits/analytics-logger/types.ts, vscode/src/autoedits/autoedits-provider.test.ts, vscode/src/autoedits/renderer/inline-manager.ts, vscode/src/autoedits/renderer/manager.ts
Notable changes in this PR:
1. We now mark auto-edits as accepted when the document changes match the suggestion. I think this is logically correct for our telemetry - if a user pastes some code in that matches our suggestion we can say that our suggestion was accepted and pat ourselves on the back
2. We handle a nasty bug where VS Code makes an insertion for native completions _before_ calling the command we provide `cody.supersuggest.accept`. This ordering means that, due to how we try to intercept cursor changes as a way to reject suggestions, we would incorrectly reject an accepted completion. See the flow below:
Before:
1. Suggest native completion
2. User accepts it
3. VS Code inserts the text, and calls `onDidChangeTextDocument` and `onDidChangeTextEditorSelection` due to the …
=> feat(auto-edit): Handle accept events correctly when document changes match the active request

vscode/src/autoedits/autoedit-onboarding.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/completions/inline-completion-item-provider.ts
PR marks the user as auto-edit enrolled if they are already using auto-edits. This prevents switching them to `auto-edits` if user switched to `autocomplete`.
- Start the debug mode with `auto-edits` enabled and switch to `autocomplete`, this should prevent automatically enrolling user to `auto-edit` feature.
=> fix(auto-edit): Do not swtich user to if already enrolled to beta

vscode/src/autoedits/autoedit-onboarding.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/completions/inline-completion-item-provider.ts
PR marks the user as auto-edit enrolled if they are already using auto-edits. This prevents switching them to `auto-edits` if user switched to `autocomplete`.
- Start the debug mode with `auto-edits` enabled and switch to `autocomplete`, this should prevent automatically enrolling user to `auto-edit` feature.
(cherry picked from commit 4ab242769d419a72f5948887a8b77e9962395831)
=> [Backport M80] fix(auto-edit): Do not swtich user to if already enrolled to beta (#7487)

vscode/webviews/chat/cells/toolCell/ToolStatusCell.tsx
Close https://linear.app/sourcegraph/issue/CODY-5444/bug-search-results-and-file-tool-results-are-not-clickable
The Issue: In the original implementation, if the vscodeAPI prop was undefined during initial component render (because the VSCode API wasn't fully initialized yet), the onFileLinkClicked function would be created with a reference to that undefined value. Even if the API became available later, the callback would still reference the initial undefined value due to how closures work.
The Fix: By calling getVSCodeAPI() at the time the link is clicked (rather than capturing the value during render), the code now gets the most current API reference at the exact moment it's needed. This guarantees that even if the API wasn't available during the component's first render, the link …
=> fix(vscode): Ensure file link clicks work in ToolStatusCell

vscode/webviews/chat/cells/messageCell/human/HumanMessageCell.tsx
CLOSE https://linear.app/sourcegraph/issue/CODY-5451/update-ghost-text-for-follow-up-message-in-chat
The commit updates the placeholder text in the chat input field to provide clearer guidance to the user on how to add context to their questions.
Manually verified the placeholder text in the chat input field.
=> fix(vscode): Improve placeholder text in chat input (#7490)

lib/shared/src/context/openctx/context.ts, vscode/src/chat/chat-view/tools/search.ts
This commit enhances error handling in the codebase search tool and OpenCtx context retrieval.
For the codebase search tool, it adds a try-catch block to handle potential errors during the validation of input, retrieval of corpus items, and context retrieval. This prevents the chat view from crashing and provides more informative error messages to the user.
For OpenCtx, it adds a dependent abort controller to handle abort signals from the parent operation. It also adds error handling to prevent errors from OpenCtx providers from propagating up the chain. This ensures that the chat functionality remains robust even if some OpenCtx providers fail. Additionally, it logs errors when matching regex patterns for OpenCtx providers.
The title of the search result is changed to the query to …
=> fix(chat): update openctx error handling

vscode/webviews/chat/cells/toolCell/BaseCell.tsx, vscode/webviews/chat/cells/toolCell/FileCell.tsx
Remove the expanded content for the files since the user can click on the filename to see the content in the editor.
CI
=> chore(chat): Remove the expanded content for the files

vscode/src/chat/chat-view/handlers/AgenticHandler.ts, vscode/src/chat/chat-view/tools/diagnostic.ts, vscode/src/chat/chat-view/tools/edit.ts, vscode/webviews/chat/cells/toolCell/DiffCell.tsx, vscode/webviews/chat/cells/toolCell/TerminalOutputCell.tsx
This commit improves the robustness of agentic chat by enhancing error handling during tool execution and file creation/insertion.
- **AgenticHandler:**
- Adds a catch block to `executeTools` to handle errors during tool execution, preventing the chat from crashing.
- Uses `Promise.allSettled` to execute tools concurrently, allowing the process to continue even if some tools fail.
- Filters out rejected promises and null/undefined results from `Promise.allSettled` to ensure only successful tool results are processed.
- Adds a catch block to `executeSingleTool` to handle errors during individual tool invocations.
- Throws an error if a tool returns null to signal failure.
- **Edit Tool:**
- Removes `await vscode.window.showTextDocument(doc)` after creating or inserting into a file. This …
=> fix(agentic-chat): Improve error handling and tool execution robustness

vscode/src/tree-sitter/parse-tree-cache.ts
CLOSE CODY-5459
The Swift grammar is currently crashing the extension host in VSCode 1.98 and later. This commit temporarily disables the Swift grammar to prevent crashes.
This is a temporary measure, and the Swift grammar will be re-enabled once the compatibility issue is resolved.
- Verify that the extension host does not crash when opening Swift files and Cody still can give you answers regarding the file passed as context.
=> fix(chat): Temporarily disable Swift tree-sitter parsing due to VSCode 1.98+ compatibility issue

jetbrains/src/main/kotlin/com/sourcegraph/cody/ui/web/WebUIProxy.kt
CLOSE https://linear.app/sourcegraph/issue/CODY-4704/backspace-and-enter-keys-not-working-in-rider-cody-window-macos
Special global handler for `Backspace`, `Delete`, `Enter`, and `Shift+Enter` which are not working properly in the CEF instance in Rider and potentially in other IntelliJ IDEs flavors. Even, when there are  no shortcuts defined for these keys in the current keymap, press key events still aren't forwarded to the CEF instance, but looks like they are swallowed by other dispatchers (`DefaultKeyboardFocusManager.keyEventDispatcher`) in the pipeline:
The implementation un-consume a key event (via reflection), already consumed by other dispatchers, which allow a key event to be later handled by Cef component (webview).
Detecting the event source using `JBCefOsrComponent` type, …
=> [JetBrains] Custom global key handler supporting Enter/Delete/Backspace and Enter+Shift in all IntelliJ IDEs flavors in the uniform way

jetbrains/src/main/resources/META-INF/plugin-json.xml, jetbrains/src/main/resources/META-INF/plugin.xml
close https://github.com/sourcegraph/jetbrains/issues/3197
This PR makes the `com.intellij.modules.json` module an optional dependency. This is necessary if you use a remote WSL. JetBrains client can only use trimmed module (`com.intellij.json.frontend`). The full version is not available on client-side which leads to an error. More info: https://intellij-support.jetbrains.com/hc/en-us/community/posts/21479962703890-JSON-plugin-dependency-cannot-be-resolved
1. Run IJ instance on WSL
2. Install Cody extension (use 'Plugins Client' settings page then click gear icon and select 'Install plugin from Disk')
3. After restarting Cody should load without any errors
=> Make com.intellij.modules.json an optional dependency

vscode/webviews/chat/cells/toolCell/FileCell.story.tsx, vscode/webviews/chat/cells/toolCell/FileCell.tsx
This commit updates the FileCell component in the chat interface to display the file path instead of just the title. It uses the `displayPath` function from `@sourcegraph/cody-shared` to format the URI for better readability. This change improves the user experience by providing more context about the selected file.
Also fixed storybook for FileCell
- Ask Cody in agent mode about something that would view a file content
- Confirm File tool / File Cell is displaying the path of the file
Storybook fix
=> fix(chat): Display file path in chat file cell

jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentClient.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/CodySecureStore.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/config/migration/AccountsMigration.kt, jetbrains/src/main/kotlin/com/sourcegraph/config/ConfigUtil.kt
This PR partially mitigates the issue where users faces multiple prompt passwords if they change the endpoints in different IDEs.
To fully solve that issue it would need to be done on the JetBrains level, as I described there: https://platform.jetbrains.com/t/group-keyring-access-for-all-ides-from-jetbrains-familly/1002
With my changes only password to Cody secret store is stored in a keyring using `PasswordSafe`, and all secrets are stored in a custom java [KeyStore](https://docs.oracle.com/javase/8/docs/api/java/security/KeyStore.html). That means password need to be typed only once per different IntelliJ executable (no matter between how many endpoints user switches).
**Backward compatibility test**
1. Open your keychain settings and search for `IntelliJ Platform Sourcegraph`, and then …
=> Store all cody keyring secrets in a single entry

vscode/src/prompts/prompt-hydration.ts
When current selection is not available, use the whole file as context while hydrating prompt template for `cody://current-selection`
Execute a prompt with current selection on cody web where there is nothing selected. It should hydrate correctly and mention the current file.
=> Use current file as fallback for current selection prompt hydration

vscode/src/autoedits/analytics-logger/types.ts, vscode/src/autoedits/autoedits-provider.test.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/smart-throttle.ts, vscode/src/autoedits/test-helpers.ts
- Implements smart-throttle for the auto-edit provider. See a doc string comment in the implementation explaining how it works. The smart-throttle service now fully controls abort logic, and we do not use cancellation tokens provided by VS Code.
- Requests in the new code to rewrite areas are made instantly, without delay.
- The throttle interval is set to 50ms in this PR. Happy to adjust, but it performed OK locally during the manual testing. We can adjust the value with a backport during the dogfooding phase if we see that the load on the model grows significantly.
- Closes [CODY-5466: Implement smart-throttle](https://linear.app/sourcegraph/issue/CODY-5466/implement-smart-throttle)
CI + new tests + manual testing with the auto-edit debug panel
=> feat(auto-edit): implement smart-throttle

agent/src/autoedit.test.ts, lib/shared/src/configuration.ts, vscode/package.json, vscode/src/configuration.ts, vscode/src/jsonrpc/agent-protocol.ts, vscode/src/services/StatusBar.ts
Change the identifier from experimental to beta. Also added backward compatibility for the setting.
Start in debug mode and ensure `auto-edit` works and have "beta" in the setting
=> feat(auto-edit): Change the identifier from experimental to beta

vscode/src/chat/chat-view/ChatController.ts
Closes: [CODY-5473](https://linear.app/sourcegraph/issue/CODY-5486/when-you-click-the-file-name-it-opens-a-new-panel)
This commit modifies the `openFileLink` case in the `ChatController` to open files in the active column when the chat view is in the sidebar. Previously, files were always opened in the `Beside` column.
The change introduces a check to determine if the webview is in the sidebar. If it is, the `viewColumn` option for the `vscode.commands.executeCommand('vscode.open')` command is set to `vscode.ViewColumn.Active`. Otherwise, it defaults to `vscode.ViewColumn.Beside`.
This improves the user experience by ensuring that files opened from the chat view in the sidebar are opened in the current editor group, rather than creating a new one.
1. Ask Cody a question in sidebar view …
=> feat(chat): Open file in active column when in sidebar view

vscode/src/prompt-builder/sanitize.test.ts, vscode/src/prompt-builder/sanitize.ts
FIX: https://linear.app/sourcegraph/issue/CODY-5482
This commit addresses a scenario where the assistant's last message contains a `tool_call` but the subsequent human message does not have a corresponding `tool_result`. In such cases, the `tool_call` is removed from the assistant's message to prevent issues with the prompt builder.
The changes involve:
- Modifying the `sanitizedChatMessages` function to identify and remove dangling `tool_call` parts from the last assistant message if a subsequent human message lacks a `tool_result`.
- Creating a copy of the messages array to avoid mutating the original.
- Using `isDefined` to filter out undefined values after mapping.
1. Ask Cody a question in agent mode until it runs into error, or stop the chat after a tool was used.
2. Then ask a …
=> fix(agent mode): remove dangling tool_call from assistant messages

vscode/webviews/chat/cells/toolCell/DiffCell.tsx
CLOSE https://linear.app/sourcegraph/issue/CODY-5472
We were seeing the numbers of diff were off by 1, but the root cause is because those lines were counted toward modified lines instead of add / remove. This PR adds the modified line numbers for display.
After
Display total number of modified lines
Before
Only added & removed line numbers are displayed
=> feat(agent mode): Display modified lines count in DiffCell 

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Constants.kt, agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ExtensionConfiguration.kt, vscode/src/chat/chat-view/handlers/AgenticHandler.test.ts, vscode/src/chat/chat-view/handlers/AgenticHandler.ts, vscode/src/chat/chat-view/tools/file.ts, vscode/src/chat/chat-view/tools/shell.ts, vscode/webviews/chat/cells/toolCell/DiffCell.tsx, vscode/webviews/chat/cells/toolCell/FileCell.tsx, vscode/webviews/chat/cells/toolCell/TerminalOutputCell.tsx
FIX https://linear.app/sourcegraph/issue/CODY-5494
This commit modifies the `AgenticHandler` to include the initial context provided by the user in the conversation loop.
The initial context is computed using `this.computeContext` and passed to the `runConversationLoop` function. This ensures that the agent has access to the user's initial input and any mentioned context items throughout the conversation.
Additionally, the context is reset after each turn to prevent it from accumulating and potentially influencing subsequent turns in unintended ways. A debug log was added to catch errors when executing tools.
This is the same implementation we are using for regular chat in ChatHandler.
1. Ask Cody a question in agent mode and at mention an image
2. The agent should be able to answer you …
=> fix(agent mode): Include initial context in conversation loop

vscode/webviews/chat/cells/messageCell/human/editor/toolbar/ModeSelectorButton.tsx
This commit updates the `ModeSelectorButton` component to hide the agentic mode option when the edit functionality is not enabled. This ensures that users do not see the agentic mode option if they cannot use it.
This includes Web client
Agent mode should be hidden for clients that dont support edit
=> fix(modes): Hide agentic mode when edit is not enabled

agent/src/cli/command-models.ts
This PR fixes issue with `cody model list` command, which was failing because it didn't send `X-Requested-With` header.
- Just run `cody model list` and see if it fails
=> Fix cody agent model listing command

lib/prompt-editor/src/PromptEditor.test.tsx, lib/prompt-editor/src/v2/lexical-interop.test.ts, lib/shared/src/lexicalEditor/editorState.test.ts, lib/shared/src/lexicalEditor/editorState.ts, lib/shared/src/lexicalEditor/fixtures.ts, lib/shared/src/lexicalEditor/nodes.ts, vscode/webviews/components/promptList/PromptList.tsx
closes: https://linear.app/sourcegraph/issue/CODY-5393/bug-fix-send-the-file-path-to-the-model-for-at-mentions
This PR updates the get text from editor state logic to include the full file display path and not just the file basename. 
The text is sent to the LLM as the human message text.
unit tests added. 
mention a file and debug & test if the full file display path is included in the prompt.
=> Pass full filepath in prompt to the LLM. 

jetbrains/build.gradle.kts, jetbrains/src/integrationTest/kotlin/com/sourcegraph/cody/edit/DocumentCodeTest.kt, jetbrains/src/integrationTest/kotlin/com/sourcegraph/cody/util/BaseIntegrationTextFixture.kt, jetbrains/src/integrationTest/kotlin/com/sourcegraph/cody/util/EditCodeFixture.kt, jetbrains/src/integrationTest/resources/recordings/documentCode_2994921345/recording.har.yaml, jetbrains/src/integrationTest/resources/recordings/integration-test_2927926756/recording.har.yaml, jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt
We had a major issue in our integration tests. `setUp` and `tearDown` methods are called before and after EACH case. That means we initialized (and shutdown-ed) the agent not once per the class but multiple times. And the recordings were recorded multiple times overriding the previous version. We were lucky it worked for document code test class.
This PR is a prerequisite for integration tests for autocomplete.
Additionally, this PR provides a mechanism to specify the recording name that will help us later with autocomplete and probably other test classes. 
It will likely speed up tests. Let's see once CI passes.
- green ci
=> [JetBrains] Run agent once per test class

.github/workflows/release-vscode-stable.yml
Previously release notes were not being generated because of a missing anthropic key, this PR moves the env var to the right step in the workflow
tested release-notes.ts working locally with the key
=> chore(release): fix release notes step

vscode/src/chat/chat-view/handlers/AgenticHandler.ts, vscode/src/chat/chat-view/tools/diagnostic.ts, vscode/src/chat/chat-view/tools/edit.ts, vscode/src/chat/chat-view/tools/file.ts, vscode/src/chat/chat-view/tools/schema.ts, vscode/src/chat/chat-view/tools/search.ts, vscode/src/chat/chat-view/tools/shell.ts, vscode/src/chat/chat-view/utils/diff.ts, vscode/src/prompt-builder/index.ts, vscode/src/prompt-builder/sanitize.test.ts, vscode/src/prompt-builder/sanitize.ts, vscode/webviews/chat/cells/toolCell/BaseCell.tsx, vscode/webviews/chat/cells/toolCell/DiffCell.tsx, vscode/webviews/chat/cells/toolCell/FileCell.tsx, vscode/webviews/chat/cells/toolCell/OutputStatusCell.tsx, vscode/webviews/chat/cells/toolCell/SearchResultsCell.tsx, vscode/webviews/chat/cells/toolCell/TerminalOutputCell.tsx, vscode/webviews/chat/cells/toolCell/ToolStatusCell.tsx
This commit modifies the `PromptBuilder` class to exclude context items of type 'tool-state' when building context messages. These items are now handled as part of the chat messages.
The change filters the `this.contextItems` array to exclude items where `item.type === 'tool-state'` before processing them for inclusion in the prompt. This ensures that tool state information is not duplicated or misinterpreted within the prompt context.
Also fix UI bug where files are showing up with FileX icon
1. Ask Cody in agent mode that requires opening a file
2. before this change, the file icon will show up with an X
3. After: show up with code file icon
After
=> fix(Agent Mode): Exclude tool-state context items from prompt

lib/shared/src/common/path.test.ts, lib/shared/src/common/path.ts
The `basename` function was not handling empty paths correctly, leading to unexpected behavior. This commit adds a check for an empty path and returns an empty string in that case, ensuring consistent and correct behavior.
Tests updated. Green CI.
=> fix(path): handle empty path in basename function

vscode/webviews/components/CodeBlockPlaceholder.tsx, vscode/webviews/components/GuardrailsApplicator.tsx, vscode/webviews/components/GuardrailsStatus.tsx
- Update capitalization of 'Guardrails' to be consistent throughout the UI text
- Applied to status messages, tooltips, and documentation comments
- Verify all UI text now uses 'Guardrails' with proper capitalization
- Confirm changes in GuardrailsStatus.tsx, GuardrailsApplicator.tsx, and CodeBlockPlaceholder.tsx
=> Consistent capitalization of 'Guardrails' in UI text

lib/shared/src/sourcegraph-api/clientConfig.ts, vscode/src/edit/edit-guardrails.ts, vscode/src/edit/edit-manager.ts, vscode/src/edit/provider.ts, vscode/src/edit/smart-apply-manager.ts, vscode/src/main.ts, vscode/src/non-stop/FixupController.ts, vscode/src/non-stop/FixupDocumentEditObserver.ts, vscode/src/non-stop/FixupTask.ts, vscode/src/non-stop/decorations/compute-decorations.ts
Adds basic Guardrails integration to Edits (Ask Cody to Edit, Document Code, etc.) When Guardrails is off, this is a no-op; when it is in permissive mode, it will notify the user of attribution matches asynchronously; when it is in enforced mode, it turns off streaming edits and will cancel edits that have attribution matches.
Fixes CODY-5084.
In VSCode and JetBrains:
1. Connect to dotcom, which does not use Guardrails. Check that edits (option-k) have a streaming style of presentation for additions; check that document code (option-d) works.
2. Connect to s2, which uses Guardrails in permissive mode. Check that edits and document code work (in streaming mode, where applicable, like dotcom.)
3. In addition, cut and paste 10+ lines from …
=> feat/guardrails: Perform Guardrails checks for edits.

lib/shared/src/guardrails/client.ts, vscode/webviews/components/RichCodeBlock.tsx
When Guardrails is in "enforced" mode, we want to prevent the user from using code until an attribution check is complete. Hide the action buttons until it is OK to show the code.
For Guardrails "permissive" mode, or no Guardrails, `showCode` is always `true` and we will show the action buttons as soon as the code is complete.
This also bumps the timeout for Guardrails attribution requests. These requests can easily take 20s+ for long code blocks.
Fixes CODY-5552, CODY-5551
Tested manually:
1. Set up an instance with `"attribution.enabled": true, "attribution.mode": "enforced"` and connect to it.
2. Generate more than 10 lines of code.
3. Check that the action buttons do not appear while "Checking Guardrails"
=> fix/guardrails: In enforced mode, hide smart apply, etc. actions until attribution complete

lib/shared/src/sourcegraph-api/completions/client.ts, vscode/src/completions/nodeClient.ts
This commit addresses an issue where completion requests might not have associated events that is causing unexpected error that stops chat requests. These changes ensure that the completion service gracefully handles scenarios where no usage data is available for a completion request, preventing potential errors and improving the robustness of the system.
The error occurs in the sendEvents method of the SourcegraphCompletionsClient class when it tries to process events but there are no events to process.
Implemented Fixes:
1. In nodeClient.ts:
- Added a check to ensure we only call sendEvents when there are actually events to process
- Added better error logging when no events are detected
- Improved the error handling in the request.on('close') handler to provide more detailed …
=> fix(completion): handle completion requests with no events

vscode/src/chat/chat-view/handlers/AgenticHandler.ts, vscode/src/chat/chat-view/tools/file.ts
This commit improves context handling in the agentic chat feature and enhances file content processing within the file tool.
- The AgenticChatPrompter now directly manages context items, removing the need to reset them after each turn. It also streamlines the process of adding context and history items to the prompt.
- The file tool now appends "<<EOF>>" to the end of file content to ensure the LLM knows the end of the file.
- Updated the transformItems function to add the EOF marker to the file content.
1. At mention a file and ask Cody in agent mode about it
2. Cody should be able to answer the question without using tool to fetch the file
it would try to find the file to answer the question
=> fix(agent mode): initial context not included as context

vscode/webviews/chat/Transcript.test.tsx, vscode/webviews/chat/cells/contextCell/ContextCell.tsx
Follows up on https://github.com/sourcegraph/cody/pull/7502 which add the LoadingDots at Transcript level, where the LoadingDots will show up at the end of the transcript when there is an assistant message in progress.
This commit refactors the `ContextCell` component to remove the `LoadingDots` component and simplify the display of context items.
The `LoadingDots` component was previously used to indicate that the context was loading. However, it was only displayed when `isContextLoading` was true and `isAgenticChat` was false. This logic was removed, and the context items are now always displayed within the `AccordionContent`.
This change simplifies the component and improves the user experience by providing a consistent display of context items, regardless of the loading state or chat …
=> refactor(chat): Remove loading dots from context display

web/lib/components/CodyWebChat.tsx, web/package.json
Before this change, a new Guardrails client was created on each render. Requests were keyed by the Guardrails client, resulting in lots of excess attribution requests. This memoizes the Guardrails client.
CodyWebPanel was missing the `vscodeAPI` message handler for routing attribution requests back to the Guardrails client. This adds that handler.
This also bumps the Cody Web package version in preparation for updating Cody Web in Sourcegraph 6.2.
Part of CODY-5547.
Have a local Sourcegraph instance that works, then:
```
pnpm i && pnpm -C lib/shared build && pnpm build && pnpm -C build
cd web
pnpm link --global
cd ~/sourcegraph
sed -i '' 's/"@sourcegraph\/cody-web": ".*",/"@sourcegraph\/cody-web": "0.32.4",/g' \
client/web-sveltekit/package.json
sed -i '' 's/pnpm install/# pnpm install/g' …
```
=> fix/web: De-dup Guardrails attribution requests and route results back to the page

lib/shared/src/chat/transcript/index.ts, lib/shared/src/chat/transcript/lightweight-history.ts, lib/shared/src/common/path.ts, lib/shared/src/misc/rpc/webviewAPI.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/chat-view/ChatHistoryManager.test.ts, vscode/src/chat/chat-view/ChatHistoryManager.ts, vscode/webviews/AppWrapperForTest.tsx, vscode/webviews/tabs/HistoryTab.story.tsx, vscode/webviews/tabs/HistoryTab.test.tsx, vscode/webviews/tabs/HistoryTab.tsx
This commit introduces a lightweight chat history to improve performance when displaying the chat history in the UI.
Key changes:
- **Lightweight Chat History:** Created a `LightweightChatTranscript` and `LightweightChatHistory` interface to represent a simplified version of the chat history, containing only essential data like ID, title, and timestamp.
- **ChatHistoryManager Updates:**
- Added a `getLightweightHistory` method to `ChatHistoryManager` to retrieve the lightweight chat history.
- Updated the `userHistory` observable in `ChatController` to use `chatHistory.lightweightChanges` for improved performance.
- **UI Updates:**
- Updated the `HistoryTab` component to use the `LightweightChatTranscript` type.
- Modified the `HistoryTab` component to display chat titles or the first …
=> feat(webview): Improve webview performance with lightweight history

vscode/webviews/chat/ChatMessageContent/ChatMessageContent.tsx, vscode/webviews/chat/ChatMessageContent/EditButtons.tsx, vscode/webviews/components/GuardrailsApplicator.tsx, vscode/webviews/components/GuardrailsStatus.tsx, vscode/webviews/components/RichCodeBlock.tsx
Also move the ... overflow menu to be the last menu item on the left.
Tested manually: Ask Cody to generate a 10 line shell script, and verify that the button is labelled "Execute."
Check that the Copy and Execute icons are aligned, both in cases where there are filenames/Guardrails, and where there is no metadata.
=> fix/chat: Label the button that runs shell commands "Execute" instead of "Execute in Terminal"

.github/workflows/scip-typescript.yml
The `lsif upload` command in the SCIP TypeScript workflow has been replaced with `code-intel upload`. This change aligns with the updated command structure in `@sourcegraph/src`. The environment variables and other configurations remain the same. This ensures that SCIP data is correctly uploaded to Sourcegraph Cloud, S2, and Demo instances.
[scip-typescript / scip-typescript (pull_request)](https://github.com/sourcegraph/cody/actions/runs/14120690080/job/39560246951?pr=7593) job to be green. it's been failing for a month
=> fix(ci): Update SCIP upload command in GitHub Actions

lib/shared/src/experimentation/FeatureFlagProvider.ts, lib/shared/src/models/model.test.ts, lib/shared/src/models/model.ts, lib/shared/src/models/modelsService.ts, lib/shared/src/models/sync.test.ts, lib/shared/src/models/sync.ts, vscode/src/completions/providers/shared/helpers.ts
New feature flag `enhanced-context-window` to increase the limits.
Update the limits (controlled by the flag) based the values in [this table](https://docs.google.com/spreadsheets/d/166KyI-B3SxClFF8CXmGYWMUrGdVBoFaCrWtveLUkP4I/edit?gid=0#gid=0).
Server-side PR: https://github.com/sourcegraph/sourcegraph/pull/4321
1. Test all the test cases listed [here](https://docs.google.com/spreadsheets/d/166KyI-B3SxClFF8CXmGYWMUrGdVBoFaCrWtveLUkP4I/edit?gid=194443342#gid=194443342)
Add tests to `model.test.ts` and `sync.test.ts`
2. Test the feature flag and context window changes e2e locally (see server side PR for more details)
- `sg start`
- `sg start cody-gateway`
- check console logs
- Loom: https://www.loom.com/share/00c66bd7e24f4b9788e5a5ec51cce05d
=> feat(models) Set new context limits (CODY-5022)

vscode/src/tree-sitter/grammars.test.ts, vscode/src/tree-sitter/grammars.ts, vscode/src/tree-sitter/parse-tree-cache.ts
This commit disables the Swift grammar in the tree-sitter implementation due to compatibility issues with VS Code versions 1.98 and later. The Swift grammar was causing the extension host to crash.
Previous pull request https://github.com/sourcegraph/cody/pull/7520 disabled the parser language loading
when going through parseDocument but you could also call directly `parse` and `updateParseTreeOnEdit`
Check that Cody no longer crashes with VSCode 1.98+
=> fix(chat): Completely disable Swift tree-sitter parsing due to VS Code 1.98+ crash

.dockerignore, .github/workflows/agent-release.yml, Dockerfile, cli/Dockerfile
[Slack context](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1742314663276049)
[Linear ticket](https://linear.app/sourcegraph/issue/REL-806/release-cody-cli-as-docker-image-for-version-5517)
~~This is just so that we have a reference here for now. We're unblocking
a customer while we integrate a CI  pipeline that will publish this
whenever an agent release goes out. That means coping the _built_ files
into this container, rather than using npm. We'll also need to give the
GHA the creds to publish this to Dockerhub.~~
This handles creation of a docker container, pushed to docker hub, which comes pre-installed with the cody npm package, built from source. Previously a single image was published for a customer under the `ccsourcegraph` account, but this PR makes the process production …
=> feat: Add Dockerfile that installs cody from source

vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/chat-view/handlers/registry.ts, vscode/webviews/chat/Transcript.test.tsx, vscode/webviews/chat/Transcript.tsx
CLOSE https://linear.app/sourcegraph/issue/CODY-5582/when-agent-mode-is-selected-it-doesnt-always-run-in-this-mode
This commit fixes an issue where the manually selected intent was not being correctly passed to the agent retrieval and submission functions. This resulted in incorrect agent selection and behavior, especially for the 'agentic' intent.
The following changes were made:
- In `Transcript.tsx`, removed the `intentFromSubmit` parameter from the `onUserAction` callback and related functions (`onEditSubmit`, `onFollowupSubmit`, `onHumanMessageSubmit`). The manually selected intent is now directly used.
- In `Transcript.tsx`, set manuallySelectedIntent to 'search' when editAndSubmitSearch is called
- In `registry.ts`, updated the `getAgent` function to use the …
=> fix(agent mode): select mode at start up

lib/shared/src/models/sync.ts
The `syncModels` function was incorrectly checking for the presence of '5-sonnet' in the model ID. This commit updates the check to look for 'sonnet' instead, which is the correct identifier for the Sonnet model regardless of their version number.
This is a temporary solution until we make agentic chat available to all models
https://linear.app/sourcegraph/issue/CODY-5598
1. Open cody and connect to demo
2. Confirm Agentic Chat is showing up in model drop down
=> fix(agentic chat): Update Sonnet model ID check in syncModels

vscode/webviews/tabs/TabsBar.tsx
This commit moves the "Open in Editor" button in the TabsBar to a secondary position, next to the "New Chat" button.
The "New Chat" button is now always visible as the primary action. The "Open in Editor" button is displayed conditionally based on the `showOpenInEditor` prop. This change improves the user experience by prioritizing the "New Chat" action while still providing easy access to the "Open in Editor" functionality.
Fix https://linear.app/sourcegraph/issue/CODY-5587/new-editor-and-new-chat-should-both-show-in-nav-bar
=> feat(tabs): Move "Open in Editor" button to secondary position

lib/shared/src/models/sync.ts, lib/shared/src/models/tags.ts, vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx, vscode/webviews/components/modelSelectField/ModelSelectField.story.tsx, vscode/webviews/components/modelSelectField/ModelSelectField.tsx
CLOSE https://linear.app/sourcegraph/issue/CODY-5449/better-ui-for-pinning-the-model-when-agentic-mode-is-selected#comment-115188f6
In agent mode
- enable the model dropdown button
- when user opens the menu, all other models are disabled. a call out is shown at the drop of the dropdown: "Only Claude 3.7 Sonnet is currently available in Agent Mode"
Loom: https://www.loom.com/share/5dc7f3e75c4f48cab44e5351a58fa2ee
=> fix(agentic-chat): Improve the UI for pinning the model when Agentic mode is selected (CODY-5449)

agent/src/cli/command-bench/AutocompleteMatcher.ts, agent/src/cli/command-bench/testParse.test.ts, agent/src/cli/command-bench/testParse.ts, package-lock.json, package.json, pnpm-lock.yaml, vscode/src/completions/text-processing/parse-completion.ts, vscode/src/tree-sitter/query-sdk.ts
Update tree sitter to version [v0.24.5](https://github.com/tree-sitter/tree-sitter/releases/tag/v0.24.5)
This is last version before breaking changes which would require some bigger code changes and probably more testing.
Notably this version contains this PR:
[When loading languages via WASM, gracefully handle memory errors and leaks in external scanners #3181
](https://github.com/tree-sitter/tree-sitter/pull/3181)
That should help mitigate a lot of problems we had in past with tree-sitter, and also - hopefully - help with tree-sitter memory usage.
Full QA, with different programming languages.
=> Update tree-sitter to v0.24.5

vscode/src/autoedits/autoedit-onboarding.ts
Not 100% sure if this would be an issue or not (as we're directly modifying the VS Code workspace settings, unsure if that's propagated to Agent)... but to be on the safe side we should skip auto-enrollment when not running in VS Code
1. Run auto-edits in JetBrains but do not set `suggestionsMode`
2. Check that this setting is not automatically set
=> fix(autoedit): Skip automatically enrollment when running in other clients

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/CodyAgentServer.kt, agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ModelTag.kt, agent/src/agent.ts, jetbrains/src/main/kotlin/com/sourcegraph/cody/CodyToolWindowFactory.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/debugging/AgentHeapDumpAction.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/debugging/OpenWebviewDevToolsAction.kt, jetbrains/src/main/resources/META-INF/plugin.xml, vscode/package.json, vscode/src/jsonrpc/agent-protocol.ts, vscode/src/main.ts, vscode/src/services/utils/heap-dump.ts
This PR adds Heap Dump action for both VSC and JetBrains.
It can be used for debugging memory leaks and general memory performance.
**Interesting fact:**
Doing a heap dump takes few seconds in VSC but few minutes in JetBrains.
We definitely should explain why that happens (and hopefully fix it).
1. Open JetBrains IDE
2. Click `Shift shift` and type "cody heap"
3. Hit enter to confirm running "Cody: Agent Heap Dump" action
4. Select location where you want to save a dump
After few minutes IDE should display notification about dump being ready.
The same can be done with VSC. To find the action hit `Ctrl+Shift+P`.
=> Add head dump command to Cody debug options

vscode/webviews/components/CodeBlockPlaceholder.module.css, vscode/webviews/components/CodeBlockPlaceholder.story.tsx, vscode/webviews/components/CodeBlockPlaceholder.tsx, vscode/webviews/components/GuardrailsApplicator.tsx, vscode/webviews/components/RichCodeBlock.tsx
...not sure why pr-auditor/pre-merge does not think the following is a test plan:
1. Connect to an instance with `"attribution.enabled": true, "attribution.mode": "enforced"`
2. Prompt Cody to generate 10+ lines of code which matches code indexed by sourcegraph.com, in this example "generate hello world in INTERCAL"
3. Check that the shimmer effect appears on the lines as the code is being generated and checked, but stops when the attribution matches (or the API fails with a timeout.)
Subtle in a screenshot, but note how each line appears the same tone. The shimmering has stopped:
=> fix/chat: Stop the Guardrails shimmer effect when checks are done

jetbrains/src/main/kotlin/com/sourcegraph/cody/autoedit/AutoeditLineStatusMarkerPopupPanel.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/autoedit/AutoeditManager.kt
Fixing integration tests broke real feature 😅 
```
hint.putUserData(LightweightHint.SHOWN_AT_DEBUG, true)
```
This cannot be used in real life.
- green ci
- manually tested auto edit
=> [JetBrains][auto-edit] Fix popup presentation

jetbrains/build.gradle.kts
This reverts commit ba7b0deb5633bb66633341018d6aa393a2d9b92c.
Reason: looks like it fails during release publishing.
N/A
=> Revert "[JetBrains] Update plugins  (#7626)"

jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyEnableAutocompleteAction.kt
This PR add refreshing status icon to `CodyEnableAutocompleteAction`
1. Try to enable/disable autocomplete in status bar button and see if icon is changing.
=> Refreshing icon after enabling autocomplete

lib/shared/src/experimentation/FeatureFlagProvider.ts, lib/shared/src/models/sync.test.ts
Add a forceRefresh param to evaluateFeatureFlag. This can be useful for new feature flags since we might toggle the value frequently and skip caching.
CI
=> chore(chat): Improve the feature flag evaluation process

.github/workflows/ci.yml
I mistakenly skipped this step when I re-added the gcloud auth
Closes DINF-909
CI
=> chore(ci): add gcloud auth that was removed

jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt, jetbrains/src/test/kotlin/utils/CodyEditorUtilTest.kt
`VfsUtil.toUri()` interpert the drive letter in the windows path as a scheme in the uri. This leads to a URI object which, when the `toPath()` method is called, causes an error. This prevents the creation of a new code file and spoils all "Save file" functionality. This PR tries to remedy the situation by conditionally adding a "file" prefix to the uri string. Using `withScheme()` does not fix the situation because the scheme is already mistakenly set when the URI is created. 
1. Use chat to generate some code
2. Under code block click on Save file icon
3. Add name for file
4. Click on 'OK'
5. Code file should be created and opened in the editor without errors
=> Crash occurred when user tries to save new code file

vscode/test/integration/single-root/chat.test.ts
This test regularly fails in CI.
Example failures on `main`: 
1. https://github.com/sourcegraph/cody/actions/runs/14302985167/job/40080668100#step:12:127
2. https://github.com/sourcegraph/cody/actions/runs/14273152078/job/40010756130#step:13:109
3. https://github.com/sourcegraph/cody/actions/runs/14273152078/job/40010755491#step:12:126
Integration tests pass
=> chore: Skip flaky integration test

jetbrains/build.gradle.kts, jetbrains/gradle.properties
Update node binaries used by agent to v22.14.0.
It seems to have a bit better memory management/gc, and definitely gives us huge boost when doing heap snapshots for memory profiling (5 sec vs 3 min).
Full QA on possibly all platforms is needed.
=> feat(agent): Update node binaries used by agent to v22.14.0

vscode/webviews/tabs/TabsBar.tsx
CLOSING https://sourcegraph.slack.com/archives/C08DP4R5CG0/p1744059407418759
Put the settings tab behind the internal-only flag `next-agentic-chat-internal`. This flag is already used for MCP servers.
Toggle the feature flag on S2 and check that the setting is not there when the flag value is false.
=> fix(agentic chat): Put the settings tab behind a feature flag

lib/shared/src/experimentation/FeatureFlagProvider.ts, vscode/src/services/utils/codeblock-action-tracker.ts
Add a feature flag to use the instant smart apply model when enabled.
- Override the user in the feature flag and test if we use the new smart apply model for both dotcom and enterprise accounts.
=> feat(smart-apply): Ship instant smart apply model

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Chat_ModelsParams.kt, agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Constants.kt, agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Model.kt, agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ModelTag.kt, agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ModelUsage.kt
Fixes broken test caused by https://github.com/sourcegraph/cody/pull/7367
Green `agent-bindings` test on CI.
=> chore(CI): Fix agent bindings

lib/shared/src/sourcegraph-api/graphql/client.ts, lib/shared/src/sourcegraph-api/siteVersion.ts, vscode/test/integration/single-root/chat.test.ts
Fixes https://github.com/sourcegraph/cody/issues/7673
Rerun a `test-integration (ubuntu)` few times - all reruns should be green.
=> Fix flaky tests caused by too often refresh of siteVersion

.github/workflows/release-jetbrains-experimental.yml, .github/workflows/release-jetbrains-prerelease.yml, .github/workflows/release-jetbrains-stable.yml
This PR should allow us to upload jetbrains publish artefact report in case of publishing failure.
Without it we barely have any visibility to the reasons of the failure.
N/A
=> chore(CI): Upload jetbrains artefact publishing reports

.github/workflows/ci.yml, .github/workflows/release-vscode-experimental.yml, .github/workflows/release-vscode-nightly.yml, .github/workflows/release-vscode-prerelease.yml, .github/workflows/release-vscode-stable.yml
Integration steps need to auth with Data team creds since metrics gets sent during the test. So we auth before the step.
Closes DINF-923
CI
=> fix(vscode): update release workflows to auth before integration tests

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Constants.kt, agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ExtensionConfiguration.kt, jetbrains/src/integrationTest/kotlin/com/sourcegraph/cody/autocomplete/AutocompleteEditTest.kt, lib/shared/src/configuration.ts, vscode/package.json, vscode/src/configuration.ts, vscode/src/jsonrpc/agent-protocol.ts, vscode/src/services/StatusBar.ts
Reflecting that Auto-Edits are a beta feature in the setting value feels redundant and could potentially cause issues from a marketing perspective. Let's remove it.
- ci
=> Change 'auto-edit (Beta)' to 'auto-edit'

pnpm-lock.yaml, vscode/package.json, vscode/src/autoedits/adapters/base.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/services/open-telemetry/OpenTelemetryService.node.ts
Introduces OpenTelemetry's metrics support to cody client. This allows cody client to send real-time metrics (currently every minute) for observability, monitoring. The metrics can be queried with prometheus or GCP's metric explorer. For example:
No additional configuration is required. New metrics will automatically appear in GCP's metric explorer.
In addition, with the version field (attached to the meter), the metrics can be used for release gating before rolling out to all populations.
- manual testing
=> feat(telemetry): introduce opentelemetry metrics to cody #CODY-5585

lib/shared/src/sourcegraph-api/graphql/cache.test.ts, lib/shared/src/sourcegraph-api/graphql/cache.ts, vscode/test/integration/single-root/chat.test.ts
`GraphQLResultCache::get` is used by `getSiteVersion`, and it by turn is user t create an observable.
Code ran in observables cannot throw exceptions.
Signature of the `get` was suggesting it returns `Errors` by value instead of throwing them, but both options were possible.
Error handling which I aeed makes sure errors are always retuned by value.
1. Run `pnpm -C vscode run test:integration` few times locally.
2. You should see no `AbortError` errors.
It was reproducing better on M84 for me, but on main error is still visible in the log although it does not crash the test.
With this PR error is totally gone, and on M84 tests is not crashing anymore.
=> chore(core): Fix unhandled AbortError errors 

jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentClient.kt
This PR changes two things:
1. Add the icon - previously, without it, our notifications looked anonymously and were easy to be omitted. 
2. Expires the notification after first trigger of any action. API does not allow us to handle multiple trigger rn. Let's do not confuse users with blue-available-text actions that do nothing.
- see the image above
=> [JetBrains] Expire 'window/showMessage' notifications after an action trigger

lib/shared/src/models/sync.ts
force EnhancedContextWindow feature flag value to fresh each time instead of using the cache
CI
=> fix(chat): force refresh for EnhancedContextWindow

lib/shared/src/completions/types.ts, vscode/src/autoedits/analytics-logger/analytics-logger.test.ts, vscode/src/autoedits/analytics-logger/analytics-logger.ts, vscode/src/autoedits/analytics-logger/types.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/debug-panel/autoedit-data-sdk.ts, vscode/src/autoedits/debug-panel/debug-panel.ts, vscode/src/autoedits/debug-panel/debug-protocol.ts, vscode/src/autoedits/prompt/prompt-utils.ts, vscode/src/completions/analytics-logger.ts, vscode/webviews/autoedit-debug.tsx, vscode/webviews/autoedit-debug/AutoeditDebugPanel.tsx, vscode/webviews/autoedit-debug/components/AutoeditDetailView.tsx, vscode/webviews/autoedit-debug/components/AutoeditListItem.tsx, vscode/webviews/autoedit-debug/components/FeedbackSection.tsx, vscode/webviews/autoedit-debug/components/side-by-side-diff/SideBySideDiff.tsx, vscode/webviews/autoedit-debug/webview-api.ts
[**Feedback Loop for the model**] Adds the feedback tab in the `auto-edit` debug panel. It adds 2 text fields `Expected Code`, which can be used as a ground truth example for SFT/DPO and `Assertions` which will be used for evaluation in LLM judge.
Adds a submit option which sends the event data to backend telemetry for model training/evaluation.
Observe the telemetry events
```
█ telemetry-v2 recordEvent: cody.autoedit/feedback-submitted: {
"parameters": {
"version": 0,
"metadata": [
{
"key": "recordsPrivateMetadataTranscript",
"value": 1
}
],
"privateMetadata": {
"inlineCompletionItemContext": {
"source": "feedback",
"file_path": "src/autoedits/prompt/base.ts",
"prefix": "import ...        ...userPromptArgs\n",
"suffix": "        // files. This ...}\n}\n",
"code_to_rewrite_prefix": " …
```
=> feat(auto-edit): Add a feedback tab in the autoedit debug panel

vscode/src/autoedits/adapters/model-response/fireworks.ts, vscode/webviews/autoedit-debug/sections/PromptSection.tsx
Add the missing `requestBody` to the model response to surface it in the auto-edit debug panel.
manually check the autoedit debug panel while connected to DotCom
=> fix(autoedit): add request body to the autoedit debug panel

.github/workflows/agent-bindings.yml
This workflow is required, but if you don't change any ts/tsx/js files your PR will be in limbo (as you will see on this PR)
Closes DINF-942
CI
=> fix(ci): skip agent bindings if only kt files changed

vscode/webviews/ChatErrorNotice.story.tsx
added new stories to the error item storybook
run `pnpm -C vscode run storybook` to start storybook
=> add storybook for error item

README.md, lib/shared/src/models/sync.ts, vscode/webviews/ChatErrorNotice.story.tsx, vscode/webviews/chat/ErrorItem.tsx
Update the displayed message for rate limiting
Put this behind the feature flag FallbackToFlash 
- Open Cody
- Send messages to hit the rate limit
- Free user: `Upgrade to Cody Pro`
- Pro user: `Upgrade to Cody Enterprise`
- Enterprise: `Usage limit of premium models reached, switching the model to Gemini Flash` AND `You can continue using Gemini Flash, or other standard models.`
=> feat(chat): Update the displayed message for rate limiting

vscode/src/chat/initialContext.ts, vscode/test/e2e/chat-atFile.test.ts, vscode/test/e2e/initial-context.test.ts, vscode/webviews/chat/cells/messageCell/human/editor/HumanMessageEditor.tsx
Fixes #CODY-5632 by restoring current selection, dynamically updated when selection changes.
- Check that if you have test selected it is reflected in the chat message input as file:range
- If you modify the selection, the input value is also dynamically changed
- @mention current-selection will expand to file:range
- Using a prompt with cody://current-selection will expand to file:range
- Opt + L will add the selected text as file:range
=> change(chat): re-add current selection within initial mention 

vscode/src/chat/chat-view/handlers/registry.ts
This commit renames `DeepCodyAgentID` to `DeepCodyModelRef` to align with the naming convention used for other model references. This change ensures consistency and clarity in the codebase.
Agentic chat works:
Before - agentic context is empty
=> fix(chat): use DeepCodyModelRef instead of id

agent/recordings/customCommandsClient_509552979/recording.har.yaml, agent/recordings/document-code_965949506/recording.har.yaml, agent/recordings/edit_1541920145/recording.har.yaml, agent/recordings/fix_3001320056/recording.har.yaml, agent/src/__snapshots__/custom-commands.test.ts.snap, agent/src/__snapshots__/document-code.test.ts.snap, agent/src/edit.test.ts, vscode/src/chat/chat-view/ChatController.test.ts, vscode/src/non-stop/FixupTask.ts
VSCode's text edit API is apparently forgiving and allows a position at `(N,0)` in an N-lined document, even if the last line does not end in a newline. (Note that lines are zero indexed so `(N,0)` is the N+1th line.)
JetBrains' text model is less forgiving and treats that extent as out of bounds. This causes exceptions when rejecting edits.
We could follow Postel's law and make EditService.performTextEdits more liberal in what it accepts. But since we're integrating this into N editors, I have chosen to make the TypeScript side more rigorous and not extend selections past the end of the document.
Fixes QA-507.
```
pnpm i && pnpm -C lib/shared build && pnpm build
cd jetbrains
SKIP_CODE_SEARCH_BUILD=true ./gradlew :customRunIde -PforceAgentBuild=true
```
Then:
1. Open a project
2. Write …
=> fix/edit: Do not widen selections past the end of the document.

jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/action/CycleCodyAutocompleteActionHandler.kt, jetbrains/src/test/kotlin/com/sourcegraph/cody/autocomplete/CodyAutocompleteManagerTest.kt
This PR is a cleanup to AutocompleteManager.
- autocompletes tested manually
- got it popup verified manually
=> Rename displayAgentAutocomplete to displayInlay & clean up

vscode/webviews/components/UserAvatar.tsx
This PR adds error handling for user avatar URLs.  If the avatar URL is invalid or inaccessible, the component will fall back to displaying the user's initials instead of a broken image.
Still displays avatars from public-facing URLs and now uses the fallback for private or unreachable URLs.
Image from self-hosted GitLab.
Before:
After:
=> handle broken avatar URLs

vscode/src/autoedits/autoedits-provider.ts
`getAndProcessModelResponses` returns an `AsyncGenerator`. As a result, the wait does not happen until calls to `next` function. This causes timing skewed to only function call latencies. The fix is to record latency at the time `next` function is called instead.
ref: CODY-5528
verified by manually trying autoedit in debug environment and verify the metrics in metric explorer.
=> fix(auto-edit): model call latency metric did not reflect actual timing

jetbrains/src/main/kotlin/com/sourcegraph/cody/listeners/CodyFileEditorListener.kt, jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt
Probably fixes https://linear.app/sourcegraph/issue/BUGS-1580/bug-jetbrains-rider-freezes-when-switching-files-and-on-startup
Previously `codyAgent.server.textDocument_didOpen` and `codyAgent.server.textDocument_didFocus` were called on the EDT with the rest of the code for obtaining document content. That is bad, because if for any reason Cody will be stuck or slow it will make whole IntelliJ unstable. Cody calls should always happen on separate background thread.
1. Open a lot of big files
2. Restart IntelliJ
3. There should be no hangs of UI when starting Cody (compared to doing the same with Cody disabled/uninstalled)
=> Don't execute Cody calls on EDT

vscode/src/commands/scm/source-control.ts
Inspired by PR #7748, read the commit template from `git config` if VSCode's SCM integration does not have a commit template already.
Works only with `git`.
Affects the "Generate Commit Message" functionality introduced in PR #4130
CI tests pass.
Usually VSCode's SCM integration loads the commit template, but you might be able to fake it out by unsetting the commit template (`git config --unset commit.template;git config --global --unset commit.template; sudo git config --system --unset commit.template`), launching VSCode, and then setting the commit template(s) again.
If you're able to fake out VSCode's SCM integration, you should still see the commit template being loaded (you might need to set some breakpoints to be sure)
=> fix(vscode): read commit template from git's config

vscode/src/autoedits/hot-streak/index.ts
Previously we would always force the `position` to be at the start of the hot-streak chunk, and then adjust the prefix to be empty to account for it. That has some issues:
1. We incorrectly make inline completions for the first chunk, as the `position` is different than the users actual cursor position. This means sometimes we _think_ we have shown a completion but it was actually hidden by VS Code. We should have shown an edit in this case instead.
2. We need to also adjust other values like `maxPrefixLength` and `maxSuffixLength` when we reduce the prefix. This can get complex and it's easier just to maintain the original values (although we may want this logic in the future.)
closes https://github.com/sourcegraph/cody/pull/7811
Manual testing on real examples and mocked examples in …
=> fix(autoedit): Use correct `position` for hot streak chunks

vscode/src/autoedits/renderer/next-cursor-manager.ts
Fixes an issue where:
1. Next cursor prediction is shown
2. User changes file
3. Cursor prediction state isn't cleared, so the Tab command doesn't work to accept the next suggestion
Manually in cody-chat-eval by triggering a cursor prediciton and changing file
=> fix(autoedit): Ensure next cursor decoration is cleared when file changed

jetbrains/src/main/kotlin/com/sourcegraph/cody/error/CodyPerformanceListener.kt
I just noticed this after a merge.
`?.any { ... } != null` will always evaluate to `true` if `edtStackTrace` is not null.
Bad suggestion by Cody, which replaced `find` with `any`, but keep the orginal condition :) 
Verified manually with debugger.
=> Fix freeze reporter logic

vscode/src/autoedits/debug-panel/autoedit-data-sdk.ts, vscode/webviews/autoedit-debug/AutoeditDebugPanel.tsx, vscode/webviews/autoedit-debug/components/AutoeditDetailView.tsx, vscode/webviews/autoedit-debug/components/AutoeditListItem.tsx, vscode/webviews/autoedit-debug/sections/RenderOutputSection.tsx
Adds render output info to the debug UI
**Render output tab**
**Hot streak info + render output type on main item list**
Manual checking on debug panel
=> feat(autoedit): Add render output / hot streak information to debug panel

vscode/src/autoedits/renderer/manager.ts
Long shot... but noticed this isn't quite correct when we attempt to hide the suggestion.
Related to: https://linear.app/sourcegraph/issue/CODY-5747/floating-window-in-auto-edit-is-unresponsive-and-stuck
For a proper fix we should rework our decoration logic. Right now we create the decorator for every new request (and dispose of the old decorations). Instead we should create the decorator once, and just clear decorations from different editors when needed
Consolidating the decoration logic [here](https://github.com/sourcegraph/cody/pull/7815) and then it should be easy to do this. 
Wasn't able to test this because the issue with stuck decorations is really intermittent.
Did manual testing to check this caused no new regressions
=> fix(autoedit): Use correct decorator when hiding suggestion

lib/shared/src/experimentation/FeatureFlagProvider.ts, vscode/src/autoedits/adapters/fireworks.ts, vscode/src/autoedits/autoedits-config.ts
Update the `auto-edit` config for the hot-streak as per the latency evaluation.
Latency evaluation details can be found in the [slack thread](https://sourcegraph.slack.com/archives/C08GUBSHMKN/p1745943031411789).
CI
=> feat(auto-edit): Update hot-streak config as per the latency analysis

vscode/src/autoedits/analytics-logger/analytics-logger.test.ts, vscode/src/autoedits/hot-streak/get-chunk.test.ts, vscode/src/autoedits/hot-streak/index.test.ts, vscode/src/autoedits/prompt/prompt-utils.test.ts, vscode/src/autoedits/prompt/prompt-utils.ts, vscode/src/autoedits/prompt/test-helper.ts, vscode/src/autoedits/request-manager.test.ts, vscode/src/autoedits/shrink-prediction.test.ts, vscode/src/completions/get-current-doc-context.ts
- The current logic in `ipynb` notebooks was not respecting the token limits. All the prefix and suffix were used from the other cells.
- The PR fixes that by only taking the lines with remaining tokens for notebooks. 
Updated unit tests
=> fix(auto-edit): Respect the prefix suffix token limit for ipynb notebooks

vscode/src/services/open-telemetry/OpenTelemetryService.node.ts
The console printout does not contain useful information on these metrics. They are more useful when being used in conjunction with Prometheus or Grafana for charting.
ref: CODY-5533
- n/a clean-up of metrics in development mode
=> chore(auto-edit): remove printing out otel metrics every 5 seconds to console

vscode/src/commands/context/git-api.test.ts, vscode/src/commands/context/git-api.ts, vscode/src/commands/scm/source-control.ts
Fixes CODY-5227
When generating a commit message, in the case when there are no changes (staged or otherwise) to commit, the result of clicking the Generate Commit Message button was the text, `Error: Failed to get git output.` being placed in the commit message input box.
This PR changes that behavior: when commit message generation fails - for whatever reason - the input box remains unchanged, a message about the error is displayed via `showInformationMessage`, and the error is sent to the "Cody by Sourcegraph" output channel.
Clarified error messages about skipping file because they're too big for the context
Enabled commit message generation about file deletions
CI/CD
=> fix(commit message): No error message in input box when there are no changes to commit

vscode/webviews/tabs/HistoryTab.story.tsx, vscode/webviews/tabs/HistoryTab.tsx
Fixes QA-620
This commit updates the HistoryTab component to improve the layout when there are no chat history items.
Also fixed the Pagination story, where previously we were getting the empty story result instead of a pagination
listing
- Run pnpm storybook and check the pagination storybook
- Start with a profile that has no history and notice that the empty history notice is centered
=> fix(history-tab): improve layout for empty state

vscode/src/autoedits/adapters/fireworks-websocket.ts, vscode/src/autoedits/adapters/utils.ts
Until https://github.com/sourcegraph/sourcegraph/pull/5030, the websocket proxy does not support custom models for fireworks requests since the proxy uses a hard-coded URL to a specific model. This has been changed to client's custom model and URL setting takes precedence.
ref: CODY-5745
- manual testing in conjunction with https://github.com/sourcegraph/sourcegraph/pull/5030
=> chore(auto-edit): allow custom models for websocket requests

vscode/src/chat/agentic/ToolboxManager.test.ts, vscode/src/chat/agentic/ToolboxManager.ts
Close https://linear.app/sourcegraph/issue/CODY-5736 https://linear.app/sourcegraph/issue/CODY-5781
This commit prioritizes the Gemini Flash > Haiku 3.5 models for the DeepCodyAgent.
If the `useDefaultChatModel` feature flag is disabled, the agent will now prefer to use Gemini Flash by default, or Haiku 3.5 if  Gemini Flash is not available. If neither is available, it will fall back to the first model tagged with "speed". This ensures that the agent uses a fast model when possible, improving the user experience.
Added unit test for setting the right model for agentic chat.
1. Connect to S2 and ask Cody a question using agentic chat
2. Verify agentic context is used and work
Example: `why isn't the cody commit message generator using the git template in this codebase?`
=> feat(agentic chat): Use Gemini Flash mode as default

vscode/test/e2e/chat-messages.test.ts, vscode/webviews/chat/ChatMessageContent/EditButtons.tsx, vscode/webviews/chat/cells/messageCell/assistant/AssistantMessageCell.tsx
Fixes CODY-4963 introduce Copy message button to allow copying of message output useful
especially on Cody web.
The copy button at the bottom corner of the AssistantMessageCell and it works both in VSCode and in
Cody web.
Most copilots have such a copy button to get the output which is super useful especially if you want
to past the reply somewhere else for further processing.
- Verify that the copy button is displayed correctly in the assistant message cell.
- Verify that clicking the copy button copies the assistant's message to the clipboard.
- Verify that the copy button is not displayed when the message is loading, has errors (unless aborted), or is a search intent.
=> feat(chat): add copy message button to copy message output

vscode/src/autoedits/analytics-logger/analytics-logger.test.ts, vscode/src/autoedits/analytics-logger/analytics-logger.ts, vscode/src/autoedits/analytics-logger/types.ts, vscode/src/autoedits/autoedit-completion-item.ts, vscode/src/autoedits/autoedits-provider.test.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/hot-streak/index.test.ts, vscode/src/autoedits/hot-streak/index.ts, vscode/src/autoedits/renderer/diff-utils.ts, vscode/src/autoedits/renderer/manager.ts, vscode/src/autoedits/renderer/render-output.ts, vscode/src/autoedits/request-manager.test.ts, vscode/src/autoedits/request-manager.ts, vscode/src/completions/get-current-doc-context.ts
- Renamed `docContext` to `predictionDocContext` and `requestDocContext` to clearly differentiate between them in the code. 
- In `vscode/src/autoedits/renderer/manager.ts`, the `getRenderOutput` function used to rely on `requestDocContext` to prepend the current line prefix to the inline completion insert text. However, if a user added any text after the completion started, and the current line prefix changed, it led to the `insertText` not matching the text already in the document and being hidden by VS Code. This PR fixes the issue by removing the dependency on `docContext` entirely from this function. Instead, it now relies on the always up-to-date recomputed current line prefix and suffix.
- Inlines the `getAndProcessModelResponses` body into `getPrediction` to reduce the number of …
=> fix(auto-edit): use correct doc context version to show inline completions more often

vscode/src/autoedits/autoedits-provider.ts
Since we didn't unregister the next cursor manager, it caused a duplicate registered command runtime error. This error stopped autoedit from working right after switching accounts. This PR fixes it by adding the next cursor manager to the disposables list.
1. Trigger autoedit and verify that it works — suggestions are rendered.
2. Switch account
3. Trigger autoedit and verify that it works — suggestions are rendered.
=> fix(auto-edit): dispose next cursor manager

lib/shared/src/sourcegraph-api/completions/types.ts, vscode/src/autoedits/adapters/cody-gateway.test.ts, vscode/src/autoedits/adapters/cody-gateway.ts, vscode/src/autoedits/adapters/fireworks-websocket.test.ts, vscode/src/autoedits/adapters/fireworks-websocket.ts, vscode/src/autoedits/adapters/fireworks.test.ts, vscode/src/autoedits/adapters/fireworks.ts, vscode/src/autoedits/adapters/sourcegraph-chat.test.ts, vscode/src/autoedits/adapters/sourcegraph-chat.ts, vscode/src/autoedits/adapters/sourcegraph-completions.test.ts, vscode/src/autoedits/adapters/sourcegraph-completions.ts, vscode/src/autoedits/adapters/utils.ts, vscode/src/autoedits/autoedits-config.ts
- Fix the NCP `auto-edit` model configuration as per latency evaluation.
- Backend PR https://github.com/sourcegraph/sourcegraph/pull/5190
- Evaluation PRs:
- https://github.com/sourcegraph/cody-chat-eval/pull/157
- https://github.com/sourcegraph/cody-chat-eval/pull/159
Added unit tests
=> fix(autoedit): Adjust the config for long suggestion model

vscode/src/prompts/manager.ts
Fixes QA-579
Added  "(Draft)" suffix to the label of draft prompts in the prompt selector.
- Add a prompt that is draft
- Use opt + shit + p and notice the title has (Draft) appended
=> feat(prompts): Display draft prompts in prompt selector

vscode/webviews/components/UserMenu.tsx
Fixes QA-307
This commit adds an `ExternalLinkIcon` to the "Upgrade to Pro" link in the UserMenu. This provides a visual cue to the user that clicking the link will open an external website.
- Login with a free account
- Notice that the call to action to upgrade to pro contains also the external link icon
=> fix(usermenu): add external link icon to upgrade to pro link

vscode/src/completions/context/retrievers/recent-user-actions/recent-view-port.test.ts, vscode/src/completions/context/retrievers/recent-user-actions/recent-view-port.ts
- Fix the `view-port` retriever by updating the editor.
- Before the active editor was not getting updated and outdated snippet from most older file was coming in the snippet view retiever.
- Added unit test to check current active editor
=> fix(auto-edit): Fix the view prompt for active editor

vscode/src/autoedits/hot-streak/get-chunk.test.ts, vscode/src/autoedits/hot-streak/get-chunk.ts, vscode/src/autoedits/hot-streak/index.test.ts, vscode/src/autoedits/hot-streak/stable-suggestion.ts
Do not suggest empty line insertions from hot-streak chunks. It was caused by the fact that we did not remove the last empty line from the predicted lines when diffing against the code to rewrite. 
CI + new unit tests
=> fix(auto-edit): do not suggest empty line insertions

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/AutoeditRequestStateForAgentTesting.kt, agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Constants.kt, agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Phase.kt, vscode/src/autoedits/adapters/sourcegraph-completions.ts, vscode/src/autoedits/analytics-logger/analytics-logger.test.ts, vscode/src/autoedits/analytics-logger/analytics-logger.ts, vscode/src/autoedits/analytics-logger/types.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/debug-panel/autoedit-data-sdk.ts, vscode/src/completions/analytics-logger.ts, vscode/webviews/autoedit-debug/AutoeditDebugPanel.tsx
- Introduced new phases (`postProcessed` and `readyToBeRendered`) to better track the lifecycle of autoedit suggestions, along with corresponding state interfaces (`PostProcessedState` and `ReadyToBeRenderedState`). Updated valid state transitions to include these new phases. 
- Fixed the problem where response headers and body were not propagated to the auto-edit debug panel from the Sourcegraph completions adapter.
- Integrated the new analytics logger methods (`markAsLoaded`, `markAsPostProcessed`, and `markAsReadyToBeRendered`) into the `AutoeditsProvider` to align with the updated state management. This ensures we can view model responses for ignored/empty suggestions in the debug panel
- To ensure the correct order, sort hot-streak chunks in the debug panel by timestamp if the line …
=> feat(auto-edit): add `readyToBeRendered` state to the analytics logger

vscode/webviews/components/promptList/ActionItem.tsx
addresses: https://sourcegraph.slack.com/archives/C05AGQYD528/p1746640793043669
This PR removes the duplicate prompt mode icons added due to merge conflicts. As discussed we want to only show Pencil icon for edit mode prompts and nothing otherwise. 
- In prompt picker, Pencil icon should be visible for edit prompts.
=> Remove duplicate mode icon

vscode/src/autoedits/autoedits-config.ts, vscode/src/autoedits/hot-streak/get-chunk.test.ts, vscode/src/autoedits/hot-streak/index.test.ts, vscode/src/autoedits/hot-streak/stable-suggestion.ts
`codeToReplaceData` almost always ends in a new line, except for cases where the last line is at the very end of the document. This is because the range uses `rangeIncludingLineBreak` ([code](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/autoedits/prompt/prompt-utils/code-to-replace.ts?L74-80))
Instead of always trimming the final new line from the prediction, we should do it conditionally based on if the code to replace also has a new line
Manual testing.
Unit tests
=> fix(auto-edit): Only trim hot streak predictions when codeToReplace is missing a final new line

vscode/src/autoedits/autoedits-provider.test.ts, vscode/src/autoedits/autoedits-provider.ts, vscode/src/autoedits/renderer/decorators/base.ts, vscode/src/autoedits/renderer/decorators/inline-diff-decorator.ts, vscode/src/autoedits/renderer/diff-utils.ts, vscode/src/autoedits/renderer/manager.test.ts, vscode/src/autoedits/renderer/manager.ts
closes https://linear.app/sourcegraph/issue/CODY-5799/auto-edits-not-dismissable-in-vim-mode
closes https://linear.app/sourcegraph/issue/CODY-5747/floating-window-in-auto-edit-is-unresponsive-and-stuck
Refactors the decoration logic so we no longer recreate the decorator entirely for each new suggestion. This is much easier to reason with as there can only ever be one instance of a decoration at a time, and we don't need to worry about cases where we might show multiple types of the same decoration
Manual testing on cody-chat-eval examples
=> fix(auto-edit): Handle stuck decorations, refactor decorators

lib/shared/src/experimentation/FeatureFlagProvider.ts, vscode/src/autoedits/hot-streak/__snapshots__/index.test.ts.snap, vscode/src/autoedits/hot-streak/constants.ts, vscode/src/autoedits/hot-streak/get-chunk.test.ts, vscode/src/autoedits/hot-streak/index.test.ts, vscode/src/autoedits/hot-streak/stable-suggestion.test.ts, vscode/src/autoedits/hot-streak/stable-suggestion.ts
Changes to prep hot streak for dogfooding:
1. Updates the hot-streak feature flag so we can enable it in the prerelease and ensure it's only used for people who have the latest stable version installed
2. Adds `SHOULD_USE_STABLE_UNCHANGED_HUNK_THRESHOLD` to help increase the stability of the partial diff
Enable flag, check hot streak shows
Unit tests
=> chore(auto-edit): Prepare hot-streak for dogfooding

vscode/src/services/CharactersLogger.ts
- Enables the Characters Logger support for untitled docs.
- Related [Slack thread](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1746564961790279).
CI + manually test the character logger locally:
- Open a new untitled document
- Insert N characters
- cmd+P to execute a debug command: "Log character logger counters"
- Verify that counters match the number of inserted chars.
=> fix(analytics): enable characters logger for untitled doc

vscode/src/completions/default-client.ts, vscode/src/completions/fast-path-client.ts, vscode/src/completions/providers/shared/fetch-and-process-completions.ts
- While playing with https://github.com/sourcegraph/cody/pull/7871 I noticed that we do not yield the correct stop reason from the default completions client. Sometimes this prevents completions from being emitted to the inline completion items provider. 
CI + manual testing
=> fix(autocomplete): fix stop reason in the default completions client

vscode/src/completions/model-helpers/index.ts, vscode/src/completions/model-helpers/openai-v2.ts, vscode/src/completions/providers/unstable-openai.ts, vscode/src/completions/text-processing/utils.ts
- Use https://sg02.sourcegraphcloud.com/, where the gpt-4.1-mini is currently set as a default completion model. The test account credentials are in the 1Password note "Cody - Test Accounts".
- Thanks @taras-yemets for [a beautiful summary](https://linear.app/sourcegraph/issue/PROD-510/azure-openai-autocomplete-model-gpt-4o-mini-mercedes-leidos#comment-b90872d7) on how to configure the model.
- Manually plan with the model.
=> feat(autocomplete): better autocomplete support for gpt-4.1-mini

lib/shared/src/models/sync.ts
Fixes https://linear.app/sourcegraph/issue/CODY-5800
This PR fixes the bug when we were appending to model list (instead of overwriting it).
It was happening only if feature flags were changing, but that can easily happen in case of lost network connectivity (see testplan).
1. Apply the diff bellow to increase frequency of feature flags refresh
```diff
Wait for Cody to load and then disable network for 15 sec and enable it again :slightly_smiling_face:
--- a/lib/shared/src/experimentation/FeatureFlagProvider.ts
+++ b/lib/shared/src/experimentation/FeatureFlagProvider.ts
@@ -170,7 +170,7 @@ export enum FeatureFlag {
AgenticContextDisabled = 'agentic-context-disabled',
}
-const ONE_HOUR = 60 * 60 * 1000
+const ONE_HOUR = 10 * 1000
```
2. Wait for Cody to load
3. Disable network for 15 sec …
=> Fix issue with duplicated models in the model selection

jetbrains/src/main/kotlin/com/sourcegraph/cody/ui/web/WebUIProxy.kt
Added support for Ctrl+C not working in Rider/Windows, when trying to copy text from Cody tool window.
CLOSE https://linear.app/sourcegraph/issue/CODY-4258/fix-ctrl-c-text-copy-issue-in-cody-for-rider-on-windows
1. Open Rider (Windows)
2. Open Cody chat and ask to generate some code snippet
3. Select part of a code snipper, and `Ctrl+C` to copy it
4. `Ctrl+V` in the editor to check result
=> Added support for Ctrl+C not working in Rider/Windows

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/CodyAgentClient.kt, agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ExtensionConfiguration_DidUpdateParams.kt, agent/src/AgentWorkspaceConfiguration.ts, agent/src/agent.ts, agent/src/vscode-shim.ts, jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentClient.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/config/migration/ClientConfigCleanupMigration.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/initialization/PostStartupActivity.kt, jetbrains/src/main/kotlin/com/sourcegraph/config/ConfigUtil.kt, jetbrains/src/test/kotlin/com/sourcegraph/cody/config/migration/ClientConfigCleanupMigrationTest.kt, vscode/src/jsonrpc/agent-protocol.ts
This PR fixes how client-side configuration variables are handled to prevent them from being written back to `cody_settings.json` and adds a migration to clean up any settings that were already incorrectly stored.
- Modified the agent protocol and client to use a more granular update approach
- Changed the extension configuration update system to pass specific keys and values instead of the entire configuration object
- Updated the `ConfigUtil` with an additional method to handle targeted configuration updates
- Added a migration that runs on plugin startup to clean up the `cody_settings.json` file by:
- Removing temporary client-side configuration that should not be persisted (agent info, hasNativeWebview)
- Removing default configuration values to reduce clutter in the settings file
- …
=> Fix handling of client-side temporary settings in cody_settings.json

lib/shared/src/rules/editing-helpers.ts, lib/shared/src/rules/rules.test.ts, lib/shared/src/rules/rules.ts, vscode/src/completions/analytics-logger.ts, vscode/src/rules/fs-rule-provider.test.ts, vscode/src/rules/fs-rule-provider.ts
This commit prevents the addition of duplicate `.sourcegraph` paths when generating rule search paths. This avoids scenarios where the same `.sourcegraph` directory is added multiple times to the search path which would result in a console error since you are not supposed to have .sourcegraph.sourcegraph paths.
The fix involves checking if the current path already ends with `.sourcegraph` before adding it to the search paths. A new test case is added to ensure that duplicate paths are not generated. 
Additionally, a check is added to ensure that the directory exists before attempting to read it. If the directory does not exist, an empty array is returned without error.
UPDATE:
- Also restricted rules from running in untrusted workspaces
- create a .sourcegraph/test.rule.md within a folder …
=> fix(rules): avoid duplicate .sourcegraph paths in rule search

vscode/webviews/components/mcp/views/AddServerForm.tsx
CLOSE https://linear.app/sourcegraph/issue/CODY-5825/bug-mcp-arguments-dont-allow-spaces
The input field for server arguments was trimming spaces, preventing users from entering arguments that require spaces. This commit removes the `trim()` function from the `onChange` handler, allowing spaces to be included in the arguments.
Details in https://linear.app/sourcegraph/issue/CODY-5825/bug-mcp-arguments-dont-allow-spaces
=> fix(chat): Allow spaces in mcp server arguments

vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/protocol.ts, vscode/webviews/components/mcp/ServerHome.tsx
CLOSE https://linear.app/sourcegraph/issue/CODY-5827/mcp-server-button-doesnt-show-settings
Updated to allow passing arguments to VS Code commands executed from the chat protocol by adding an optional `args` property to the `WebviewMessage` type for the 'command' case.
The `ChatController` is updated to use `message.args` if `message.arg` is not provided, ensuring backward compatibility.
Additionally, the MCP server home component is updated to show the open config button even when there is no servers configured.
The settings button now opens the settings JSON directly to the `cody.mcpServers` key.
Button display on start up view:
Open json setting on click:
https://github.com/user-attachments/assets/faa43676-e135-49d6-b483-c8e2ed017852
=> feat(chat): open mcp settings in json

lib/shared/src/sourcegraph-api/graphql/client.ts, vscode/webviews/components/promptOwnerFilter/PromptOwnerFilter.tsx, vscode/webviews/components/promptSelectField/PromptSelectField.tsx, vscode/webviews/components/promptTagsFilter/PromptTagsFilter.tsx
Enables using latest gql query to sort prompts by relevance on the insider builds as well, given now the backend changes are deployed to S2. 
Also fixes the css issue with prompt filter components which didn't have text truncation. 
- Open prompts picker make sure that the prompts are sorted by relevance. https://linear.app/sourcegraph/issue/CODY-5752/update-prompts-sorting-in-web
=> Enable prompts sort by relevance for insider builds

lib/shared/src/llm-providers/mcp/types.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/chat-view/tools/MCPConnectionManager.ts, vscode/src/chat/chat-view/tools/MCPManager.ts, vscode/src/chat/chat-view/tools/MCPServerManager.ts, vscode/webviews/components/mcp/ServerHome.tsx, vscode/webviews/components/mcp/views/AddServerForm.tsx, vscode/webviews/components/mcp/views/AddServerView.tsx, vscode/webviews/tabs/HistoryTab.tsx
CLOSE https://linear.app/sourcegraph/issue/CODY-5829/remove-mcp-transporttype-from-settings
Improvements to MCP server management and tool state handling:
- Adds a "Reload" button to the MCP Servers view in the webview, allowing users to refresh the server list.
- Refactors MCP connection management for improved reliability and error handling.
- Implements persistent tool disabling across sessions by storing disabled tool states in the configuration.
- Enhances MCP server configuration updates and validation.
The following changes were made:
- Added a "Reload" button with a refresh icon to the `ServerHome` component in the webview.
- Modified `MCPConnectionManager` to handle connection status updates, error reporting, and transport events more robustly.
- Implemented …
=> refactor(chat): MCP server management and tool state

vscode/src/chat/chat-view/ChatController.ts, vscode/src/services/utils/codeblock-action-tracker.ts
-   In `ChatController.ts`, the `handleCopiedCode` function now passes the `message.eventType` directly instead of checking for `'Button'`.
-   In `codeblock-action-tracker.ts`, the logic for determining if a copy event is in progress has been updated to use `eventName.toLowerCase().includes('copy')` for case-insensitive matching.
-   The `handleCopiedCode` function in `codeblock-action-tracker.ts` now uses the `eventType` to determine if the copy event originated from a button click. If `eventType` includes 'button', the event is considered a 'copyButton' event; otherwise, it's a 'keyDown.Copy' event. The `copiedCode` is now retrieved from the `text` parameter if available, falling back to the clipboard if `text` is null or undefined.
Check output channel when …
=> fix(chat): track code paste event

pnpm-lock.yaml, vscode/package.json, vscode/webviews/chat/downloadChatHistory.test.ts, vscode/webviews/chat/downloadChatHistory.ts
For reasons which are close to impossible to debug, JCEF version used in IntelliJ 2025.1 have problems with handling our native file picker implementation:
```
const a = document.createElement('a') // a temporary anchor element
a.href = url
a.download = `cody-chat-history-${timestamp}.json`
a.target = '_blank'
a.click()
```
I replaced it with pollyfil `browser-fs-access` implementation which according to my testing works fine everywhere.
Try to export chat history in:
1. Intellij 2023.3
2. Intellij 2025.1
3. VSC
4. Web
=> Replace native file picker with polyfill implementation

vscode/webviews/chat/cells/messageCell/human/editor/toolbar/Toolbar.tsx
Previously, the entire toolbar would not render if there were fewer than 2 models available. This change ensures the toolbar is always displayed, with only the model selector being conditionally rendered when multiple models are available.
1. Test with a configuration that has only one model available
- Verify the toolbar with submit button and intent selector still appears
2. Test with multiple models available
- Verify the model selector appears alongside other toolbar elements
=> fix(chat): show toolbar even when only one model is available

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/Chat_ModelsResult.kt, agent/src/agent.ts, jetbrains/src/main/kotlin/com/sourcegraph/cody/chat/ui/LlmDropdown.kt, vscode/src/jsonrpc/agent-protocol.ts
This PR brings back functionality to disable models list selection if account is enterprise and `clientConfig?.modelsAPIEnabled` is `false`. This was broken several months ago and no one noticed:
https://github.com/sourcegraph/cody/pull/6182/files#diff-96fcfc91b38ef7dec1c22931edfd74464efb663547e49be8718ecea3171113b8
I recently removed our code for handling it (since it was not working anyway and was overly complicated) and now bringing back simpler version of it.
Hard to test without being able to change server flags, but I changed server response in debugger and verified it works.
=> Add handling for read-only models list in jetbrains edit window

lib/shared/src/models/client.ts, lib/shared/src/models/sync.test.ts, lib/shared/src/models/sync.ts, vscode/src/chat/agentic/ToolboxManager.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/chat-view/handlers/DeepCodyHandler.ts, vscode/src/chat/chat-view/handlers/registry.ts
This commit reverts the  changes made in https://github.com/sourcegraph/cody/pull/7761
- Updates the `isAgenticChatEnabled` method in `ToolboxManager` to check for a feature flag (`FeatureFlag.DeepCody`) and the specific model being used (`DeepCodyModelRef`). This ensures that agentic chat is only enabled when the feature flag is enabled and the selected model is the Deep Cody model.
- Modifies the `syncModels` function to add the Deep Cody model to the list of available models if the `DeepCody` feature flag is enabled and the model is not already present.
- Updates `ChatController` and `registry` to pass the model to `isAgenticChatEnabled` to ensure the agent is only used with the correct model.
- Removes unnecessary check for `toolboxManager.isAgenticChatEnabled()` in `DeepCodyHandler` …
=> revert(chat): enable agentic chat based on feature flag and model

vscode/src/autoedits/autoedits-config.ts
Hot streak logic was disabled in Agent... but this helper was used for the model layer and meant we were using a different model and rewrite window in Agent / other clients
Manual testing needed on the JB side after merge
=> fix(autoedit): Disable hot streak experimental model in agent

jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentClient.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/CodySecureStore.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/config/migration/AccountsMigration.kt, jetbrains/src/main/kotlin/com/sourcegraph/config/ConfigUtil.kt, jetbrains/src/main/resources/CodyBundle.properties, jetbrains/src/test/kotlin/com/sourcegraph/cody/auth/CodySecureStoreTest.kt
This PR partially mitigates the issue where users faces multiple prompt passwords if they change the endpoints in different IDEs.
To fully solve that issue it would need to be done on the JetBrains level, as I described there: https://platform.jetbrains.com/t/group-keyring-access-for-all-ides-from-jetbrains-familly/1002
With my changes only password to Cody secret store is stored in a keyring using `PasswordSafe`, and all secrets are stored in a custom java [KeyStore](https://docs.oracle.com/javase/8/docs/api/java/security/KeyStore.html). That means password need to be typed only once per different IntelliJ executable (no matter between how many endpoints user switches).
This is second attempt to deploy that changes. Compared to previous one I added some safeguards:
1. we notify user if …
=> feat(jetbrains): Improve password management in jetbrains

vscode/webviews/tabs/HistoryTab.tsx
Ccenters the content of the history tab when there are no chat histories available.
Run storybook `pnpm -C vscode run storybook` and visit http://localhost:6007/?path=/story/cody-app--simple
After: loading dots moved to the center
Before: loading dots on the side
=> fix(chat): center empty history tab

jetbrains/src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt
The logic was there but there was a bug.
1. Run the plugin with a runtime without JCEF.
2. Ensure that the related notification appears & that the panel appears in Cody tool window.
=> Fix missing JCEF panel

lib/shared/src/chat/transcript/lightweight-history.ts, vscode/src/chat/chat-view/tools/MCPManager.ts, vscode/webviews/chat/cells/messageCell/human/editor/toolbar/ModeSelectorButton.tsx, vscode/webviews/tabs/HistoryTab.tsx
Enhances the history tab by displaying the chat mode (e.g., "Agentic", "Search") and the model used for each chat on hover.
- Adding `model` and `mode` fields to the `LightweightChatTranscript` interface to store the model and intent of the chat.
- Updating the `toLightweightChatTranscript` function to extract the model and intent from the transcript.
- Modifying the `HistoryTabWithData` component to display the chat mode and model in the history list.
- Updating the `INTENT_MAPPING` to include a fallback to 'chat' to avoid undefined values.
Minor UI update. Everything works as before. Last chat model used will show up on hover when available.
Non-chat mode will have mode title appended to title name.
=> refactor(chat): add more info to show in history tab

jetbrains/build.gradle.kts
Some time ago we decided to hide stable releases by default. That was caused by the fact we were focused on limiting the time from the moment releases to the moment of the JB approval (having QA in between). Presently, we are more careful about stable releases. We can be more confident about stables. We can make it public by default.
- n/a
=> Do not hide stable releases by default

jetbrains/src/main/kotlin/com/sourcegraph/cody/ui/web/WebUIProxy.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/ui/web/WebviewView.kt
Fixes https://linear.app/sourcegraph/issue/CODY-4220/cody-plugin-gets-stuck-in-jetbrains-pycharm-intelli-j
JCEF implementation in IntelliJ is buggy, and depending on IntelliJ version it is buggy in different way:
* IJ 2023.3 - I was not able to reproduce any issues
* IJ 2024.2 - When connecting and disconnecting external displays I'm from time to time able to cause webview hang
* IJ 2025.1 - Moving IntelliJ window between displays causes webview rendering issues - white box is rendered over most of the UI and it does not refresh itself properly
I did quite a bit of debugging and so far I was able to establish that:
1. Looks like problem is caused by JetBrains or JCEF implementation is not handling display configuration changes properly. There are few places where is should be taken into …
=> Refresh Cody window on display configuration change

lib/shared/src/configuration.ts, lib/shared/src/experimentation/FeatureFlagProvider.ts, lib/shared/src/models/client.ts, lib/shared/src/models/sync.test.ts, lib/shared/src/models/sync.ts, vscode/package.json, vscode/src/chat/agentic/ToolboxManager.test.ts, vscode/src/chat/agentic/ToolboxManager.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/chat/chat-view/handlers/registry.ts, vscode/src/configuration.test.ts, vscode/src/configuration.ts, vscode/src/testutils/mocks.ts
Add a new configuration option, `cody.chat.agenticContext`, to enable or disable agentic chat functionality, enabled by default. Also removing Agentic Context from model dropdown.
- Is added to the `RawClientConfiguration` interface in `lib/shared/src/configuration.ts`.
- Is exposed as a configurable option in VS Code settings via `vscode/package.json`.
- Defaults to `true` in `vscode/package.json`, `vscode/src/configuration.ts`, and `vscode/src/testutils/mocks.ts`.
- Can be overridden in VS Code settings.
- Is used to determine whether to enable the Deep Cody agent in `vscode/src/chat/agentic/ToolboxManager.ts`.
- Removes the feature flag check for `DeepCody` and replaces it with the `cody.agentic.context` config.
- Removes the addition of the `DEEP_CODY_MODEL` based on feature flags and …
=> feat(chat): add `cody.chat.agenticContext` configuration option

vscode/test/e2e/chat-messages.test.ts, vscode/webviews/chat/ChatMessageContent/EditButtons.tsx
Fixes https://linear.app/sourcegraph/issue/QA-572/jb-no-tool-tip-is-shown-for-apply-icon-on-mouse-hover
JCEF implementation in JetBrains does not support native tooltips provided by `title`.
If we want to show them we should use dedicated React tooltip component.
1. Do chat action which will provide code change suggestion.
2. Hover mouse over smart apply buttons like `Apply` and veify that tooltip is showing up.
=> Fix smart apply tooltips in jetbrains

vscode/webviews/tabs/HistoryTab.tsx
This PR fixes a bug where "You have no chat history"  message is not shown when user deletes last remaining history while filtering the messages.
1. Log in to Cody using any account type.
2. Have multiple conversations with Cody to create chat history entries.
3. Navigate to the "History" tab in the Cody panel.
4. Use the search box to filter existing history entries.
5. Click on the "Delete All" button to clear all chat history.
6. Observe the content of the history tab after deletion - "You have no chat history" message should appear
=> Show empty chat history message if deleting all messages during filtering

jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/protocol_extensions/ModelUtil.kt
The icons disappeared long time ago (before the repo's merge). This PR brings them back.
1. Edit Code...
2. Ensure that the icons are visible
=> Fix missing LLM icon in Edit Code's dropdown

vscode/webviews/tabs/HistoryTab.tsx
Fixes https://linear.app/sourcegraph/issue/QA-622/jb-specificwindows-specific-cancel-button-doesnt-match-the-theme-of
Various fixes for readability of the History tab.
On first 3 screenshots from VSC you can see old look on the left and new look on the right:
On the next 3 screenshots you can see new look in the IntelliJ across various themes:
1. Open VSC and IntelliJ and change themes
2. Make sure `Export`, `Delete all`, `Delete all chats` and `Cancel` buttons, together with other UI elements looks good and are redable.
=> Fix History tab styling across IDE themes

README.md, vscode/README.md, vscode/package.json
The Cody LLM options in the `README.md` files and `package.json` have been updated to reflect the latest model names. Specifically, "Claude 3.5 Sonnet" has been corrected to "Claude Sonnet 4" in the listed options.
README.md and package.json update. Green CI.
=> chore: update model options from 3.5 Sonnet to Sonnet 4

jetbrains/build.gradle.kts, jetbrains/gradle.properties
`252.18003.27-EAP-SNAPSHOT` has been released. Let's prepare the plugin for `252.*`.
- plugin verifier did not report anything critical (no new errors)
- manually tested chat and autocomplete in the eap version - no issues
=> Update `untilBuild` to `252.*`

agent/src/cli/command-bench/strategy-chat-context.ts, lib/shared/src/experimentation/FeatureFlagProvider.ts, lib/shared/src/sourcegraph-api/graphql/client.ts, lib/shared/src/sourcegraph-api/graphql/queries.ts
CLOSING https://linear.app/sourcegraph/issue/SRCH-1673/cody-evaluatefeatureflags
migrate feature flags evaluation to new batch api on the sg repo https://github.com/sourcegraph/sourcegraph/pull/3513
`lib/shared/src/sourcegraph-api/graphql/client.ts`
- use `EVALUATE_FEATURE_FLAGS_QUERY` (evaluateFeatureFlags in queries.ts) instead of `GET_FEATURE_FLAGS_QUERY` (evaluatedFeatureFlags in queries.ts)
- add server version check for backwards compatibility
Backwards compatibility - Tested against dotcom and test 
for each case tested
=> feat(cody): migrate feature flags evaluation to new batch api

lib/shared/src/sourcegraph-api/completions/parse.test.ts, lib/shared/src/sourcegraph-api/completions/parse.ts, vscode/src/completions/nodeClient.ts, vscode/src/prompt-builder/sanitize.ts
we previously stream the completion to the callback function as text and also as text content which is redundant and would cause confusion to the LLM when both are sent back as part of chat history.
also revert the sanitize refactoring that is causing a bug in chat.
all tests are green. try agent mode to confirm no text is being repeated
=> remove duplicated parsed text as content

agent/src/AgentFixupControls.ts, agent/src/agent.ts, vscode/src/edit/edit-manager.ts, vscode/src/edit/input/edit-input-flow.ts, vscode/src/edit/input/get-input.ts, vscode/src/edit/input/get-items/range-symbols.ts, vscode/src/edit/input/get-items/range.ts, vscode/src/edit/input/get-matching-context.ts, vscode/src/non-stop/FixupController.ts, vscode/src/non-stop/roles.ts
Initial work for https://linear.app/sourcegraph/issue/QA-668/core-method-not-implemented-error-display-when-using-edit-search
Intention of this PR is mostly to prepare codebase for sub-sequent PRs which will unify the way in which VSC and other clients use the edit code. Currently `getInput` method which is at the core of UI logic is not called by clients at all, and instead edit code is hacked a bit in the agent. In the long run that can lead to various issues like this one: https://linear.app/sourcegraph/issue/QA-668/core-method-not-implemented-error-display-when-using-edit-search
One side effect of this PR is that I fixed title of the quickpic, which is updated if user changes selection type (e.g. from range to line).
Requires full edits QA.
=> Split edit code between flow/model and UI (QuickPick)

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/CodyAgentServer.kt, agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/TextDocument_DidRenameParams.kt, agent/src/AgentWorkspaceDocuments.test.ts, agent/src/AgentWorkspaceDocuments.ts, agent/src/agent.ts, jetbrains/src/main/kotlin/com/sourcegraph/cody/listeners/CodyElementRefactoringListenerProvider.kt, jetbrains/src/main/resources/META-INF/plugin.xml, vscode/src/jsonrpc/agent-protocol.ts
Fixes https://github.com/sourcegraph/jetbrains/issues/2360.
Fixes https://linear.app/sourcegraph/issue/QA-695/jb-specific-autocomplete-feature-stops-working-after-renaming-file.
This PR adds missing handling for `onDidRenameFiles` events. 
Note: It refers to JB Client.
**Steps:**
1. Open a file and trigger an autocomplete; verify it appears 
2. Move the file / rename the file
3. Trigger the autocompletion in at the same place (or anywhere in the file)
4. Verify that the suggestion appears
**Setup:**
```
project/
├── src/
│   └── foo.txt
```
**Steps:**
1. Open `foo.txt` in editor
2. Trigger Cody's "Edit Code" action
3. Verify code lenses appear with Accept/Reject buttons
4. Use Shift+F6 (or right click / Rename...) to rename `foo.txt` to `bar.txt`
5. Verify:
- Code lenses remain visible …
=> Fix autocomplete and code lenses issues on file renamed/moved operations

vscode/src/chat/chat-view/ChatController.ts
Eliminate unnecessary billing metadata from the `cody.chat.customTitle:generated` event
CI
=> Remove billing metadata from `customTitle` event

lib/prompt-editor/src/mentions/mentionMenu/useMentionMenuData.test.tsx, lib/prompt-editor/src/mentions/mentionMenu/useMentionMenuData.ts, web/lib/components/CodyWebChat.tsx
This commit modifies the mention menu to display both the file and selection mentions in the chat interface.
Previously, if a file was already present in the initial context, the selection (file with range) from the mention menu would be filtered out due to URI-based deduplication. This change ensures that both the file and selection are displayed as separate options in the mention menu, providing users with more granular control over the context they include in their chat prompts.
- Select a file range within Cody Web
- Check if @ mention displays `Current file` not just `Current selection`
=> feat(chat): Show both file and selection mentions in Cody Web chat

jetbrains/src/main/kotlin/com/sourcegraph/cody/edit/lenses/actions/EditShowDiffAction.kt
Fixes issue reported by Sentry in a diff action:
```
Crashed in non-app: jdk.internal.misc.Unsafe in park
com.sourcegraph.cody.edit.lenses.actions.EditShowDiffAction in _init_$lambda$2$lambda$1$lambda$0 at line 13
com.sourcegraph.cody.edit.lenses.actions.EditShowDiffAction$$Lambda/0x00000001037c8e00 in compute
Called from: com.intellij.openapi.command.WriteCommandAction in lambda$runWriteCommandAction$5
```
We should not have blocking code in a IntelliJ write actions.
N/A
=> Do not use blocking operations in write actions

web/package.json, web/vite.config.ts
Fixes cody web build failing due to `node:process` and updates the package version.
- `cd web`
- `pnpm dev`
- test new chat and other core actions
=> Update Cody Web version and fix build

vscode/webviews/chat/StorageWarningBanner.tsx
Update the storage warning banner message to avoid [confusion](https://discord.com/channels/969688426372825169/969688427232641136/1383142818234630305) about 'storage'.
Text update
---------
(cherry picked from commit dcfe95d3b943863ee662965cd8ebaf19ff08c42d)
=> [Backport M104] fix(chat): Update the storage warning banner message (#8056)

release/README.md, release/release-captain.sh
Creates an interactive script to guide release captains through the complete Cody release process.
Note: This is just an initial PR. I might have more PRs to improve the script later.
./release/release-captain.sh
=> chore: Add CLI workflow for Cody release captains

agent/src/vscode-shim.ts
Before this change, when we were updating the config with a string value, the resulting payload was smth like ""auto-edit"" (not double nesting!). That caused a parsing error in JB client. Eventually, we were saving a double nested string. Weird and incorrect. This PR fixes that.
- Make sure that double nested strings are not saved in the config. E.g. play with auto-edit enrolment.
=> Do not stringify strings in configuration update payload

agent/bindings/kotlin/lib/src/main/kotlin/com/sourcegraph/cody/agent/protocol_generated/ClientCapabilities.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt, lib/shared/src/configuration/clientCapabilities.ts, vscode/src/autoedits/autoedit-onboarding.ts, vscode/src/completions/inline-completion-item-provider.ts
This PR makes auto-edits the default suggestion mode for all clients. 
1. Having an IDE with autocompletion mode turned on (also, note that there is a local flag handled by `markUserAsAutoEditBetaEnrolled`, you may need to manually modify some code to see it working. I do not know how to clear the state of that config.)
2. Run IDE
Expected:
Cody switches to auto-edits automatically. A notification appears with an option to switch back to autocompletion mode.
=> Do enrol to auto-edit for all clients

jetbrains/src/main/kotlin/com/sourcegraph/cody/ui/web/WebUIProxy.kt
I verified that adding a sleep next to `CopyPasteManager.getInstance().setContents` call causes IDE to hang.
We do not control if that call is blocking or not, but we can run it in a background thread.
That will prevent hangs, but in case of slow `setContents` call it may cause delay in clipboard copying operation (text in the clipboard may not be available immediately).
But it is better alternative to hang, and in the majority of cases that operation is instant.
1. Generate some code with Cody chat
2. Click "Copy" button under the snapshot
3. Do it a few times
4. No hands should be observed
=> Do not copy code to clipboard on the EDT thread

vscode/src/services/utils/edit-create-file.test.ts, vscode/src/services/utils/edit-create-file.ts
Fixes CODY-5064 CODY-5830 CODY-6023 
- Have a workspace that follows this path cli -> cli -> hello.ts
- ask any llm to make some changes to hello.ts
- hit smart apply and notice smart apply changes are added to cli/cli/hello.ts instead of cli/hello.ts
=> fix(smart-apply): now applies changes to file that have parents that duplicate workspace name

lib/shared/src/sourcegraph-api/client-name-version.ts
closes: https://linear.app/sourcegraph/issue/CODY-6059/error-with-context-filters-in-cody-setup-for-client
context: https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1750104540995199
> I have a client trying to use Cody context filters, but they are running into the error in the attached image. I was able to recreate the same error when I set up [context filters](https://sourcegraph.com/docs/cody/capabilities/ignore-context#context-filters) in our test instance.
From the client as per the network request and the error message we are sending the client-name=vscode in the query params.
The issue is that the backend API only checks for `X-Sourcegraph-API-Client-Name` header field and not the `client-name` query param, but the error message says that we need to pass query param. [backend …
=> Pass client name version headers with completions request

vscode/src/main.ts
fixes: https://linear.app/sourcegraph/issue/QA-739/core-user-is-unable-to-login-to-cody
The handler was accidentally removed in #8095 (the method name was misleading, indicated that the handlers refer to upgrade logic only). This PR brings back that handler (and gives a proper name to the method).
auth with google/gitlab/github works in JB
=> fix(auth): restore accidentally removed URI handler for authentication callbacks

agent/src/configuration.test.ts
I have accidentally added these comments in https://github.com/sourcegraph/cody/pull/8093. They are redundant.
n/a
=> Remove redundant comments

jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/protocol_extensions/ProtocolTextDocument.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/chat/actions/BaseCommandAction.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/listeners/CodyCaretListener.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/listeners/CodyFileEditorListener.kt, jetbrains/src/main/kotlin/com/sourcegraph/cody/listeners/CodySelectionListener.kt, jetbrains/src/test/kotlin/com/sourcegraph/cody/agent/protocol_extensions/ProtocolTextDocumentTest.kt
Fixes https://linear.app/sourcegraph/issue/CODY-6132/cody-document-code-placement-issue-in-intellij-idea.
This PR extends work done by @mkondratek in https://github.com/sourcegraph/cody/pull/8129
**Test 1**
1. Select a block of code in the editor
2. Right click within the selection (about the middle)
3. Trigger Document Code
4. Created comment should relate to the selected block (not only to the area at the caret).
**Test 2**
1. Double click on a text token
2. Check if selection changes properly in cody chat window
**Test 3**
1. Select few lines of the code
2. Move them to different position using mouse
3. Check if selection changes properly in cody chat window
**Test 4**
1. Select few text tokens using Shift + Arrow
2. Check if selection changes properly in cody chat window
=> Fix selection issues in JetBrains

agent/recordings/autocomplete_2136217965/recording.har.yaml, agent/src/__snapshots__/autocomplete.test.ts.snap, agent/src/enterprise-s2.test.ts, agent/src/vscode-shim.ts, vscode/src/autoedits/autoedit-onboarding.ts
There was a bug in `affectsConfiguration`. We are looking for a key in the section (not the other way). This PR fixes that. It likely fixes some other config propagation / sync issues. In particular, it makes auto-edits available just after the enrolment.
Tested manually. Sadly, auto-edit case needs some code tweaks.
You can checkout my other branch based on this one that provides the necessary functionalities:
[[DO NOT MERGE] Auto-edit enrol testing](https://github.com/sourcegraph/cody/pull/8141#top)
=> Fix auto-edit enrolment issue caused by config propagation bug

agent/package.json, agent/src/cli/command-models.ts
Fixes CODY-6118 This commit initializes the client identification headers for the `cody-cli` tool. It sets the client name and version using `setClientNameVersion` from `@sourcegraph/cody-shared`. This ensures that requests from the CLI are properly identified and versioned, otherwise the command fails.
- run agent models list and notice it giving a reply with available models instead of error
=> fix(agent): Initialize client identification headers for cody-cli

jetbrains/src/main/kotlin/com/sourcegraph/cody/autoedit/AutoeditLineStatusMarkerPopupPanel.kt
Fixes https://linear.app/sourcegraph/issue/QA-754/jb-specific-crash-occurred-while-the-auto-edit-triggered-and-user.
1. Trigger auto-edit
2. Minimise the editor
---
1. Trigger auto-edit
2. Trigger auto-edit via Search Action
=> Fix a crash on auto-edit popup disposal

agent/CHANGELOG.md, agent/package.json
Fixes CODY-6118
- Test that chat models lists command works if package is released
=> chore(agent): bump release version to 5.5.22

vscode/src/chat/initialContext.ts, vscode/test/e2e/common.ts, vscode/test/e2e/helpers.ts, vscode/test/e2e/initial-context.test.ts, vscode/test/e2e/utils/buildCustomCommands.ts
Refs CODY-6072 
This commit adds support for multi-root workspaces in the initial context feature.
See https://www.youtube.com/watch?v=s53bFuT0SoY for a video demo of the enhancement in action.
- Manually tested with a multi-root workspace to verify the initial context switches correctly between workspace folders.
=> feat(chat-mention): Support multi-root workspaces in initial context

lib/shared/src/experimentation/FeatureFlagProvider.ts, vscode/src/chat/chat-view/ChatController.ts, vscode/src/net/DelegatingAgent.ts
Add a new feature flag to allow disabling network requests from Cody, in the rare cases that Cody client causes problems. Both vscode and agent uses the patched `DelegateAgent`, so this flag should apply to both.
Cody does not use `keepAlive`, nor `keepAliveMsecs` (which defaults to 1s), so this flag should be reflected ~1 hour or so after set on server side.
-- manual testing with s2
=> chore: add an option to block network requests to server

vscode/webviews/chat/ChatMessageContent/EditButtons.tsx, vscode/webviews/components/RichCodeBlock.story.tsx, vscode/webviews/components/RichCodeBlock.tsx, vscode/webviews/components/RichMarkdown.tsx
Fixes CODY-6175
The `isShellCommand` prop was originally used to prevent smart apply from being applied to shell commands. However, this distinction is no longer necessary.
- Ask for a change for a .sh file
- See that you can now apply changes instead of getting only the execute button
- Check that smart apply works on these .bash or .sh files.
=> change(smart-apply): allow apply for shell languages not just execute action

vscode/webviews/chat/ChatMessageContent/ChatMessageContent.tsx, vscode/webviews/chat/Transcript.tsx, vscode/webviews/components/RichMarkdown.tsx
This PR is not fixing a memory leak in the DOM highlighter code but significantly reduces amount of re-computation which is done. With mocked LLM response of length of 7528 characters I get:
**Before my changes:**
Execution time: 1 min 25 s ec
Peak memory used: over 2GB
Stable memory after final GC: 833MB 
**After my changes:**
Execution time: **45 sec**
Peak memory used: over 1GB
Stable memory after final GC: 719MB 
Sop while memory usage drop was not significant there is very visible speedup in the execution speed.
Also memory usage swings were subjectively less significant.
I do not have good testing procedure on `main`, but I di testing using my testing PR, with some custom logging:
https://github.com/sourcegraph/cody/pull/8167
=> Improve markdown component caching

jetbrains/build.gradle.kts, jetbrains/settings.gradle.kts
This should fix the problem visible on other builds on the CI:
```
* What went wrong:
Could not determine the dependencies of task ':compileKotlin'.
> Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=17, vendor=JetBrains, implementation=vendor-specific} for LINUX on x86_64.
> No matching toolchain could be found in the locally installed toolchains or the configured toolchain download repositories.
```
Looks like resolver we are using is too old, but I'm not sure why it started to fail just now (I guess it must be some change on the toolchains repositories side).
Green CI
=> Update gradle toolchains resolver

jetbrains/src/main/kotlin/com/sourcegraph/cody/listeners/CodyElementRefactoringListenerProvider.kt
Fix for the NPE in the `CodyElementListenerProvider` reported by Sentry:
```
Cannot invoke "com.intellij.psi.PsiFile.getVirtualFile()" because the return value of "com.intellij.psi.PsiElement.getContainingFile()" is null
com.sourcegraph.cody.listeners.CodyElementListenerProvider in getListener at line 12
In App
com.intellij.refactoring.listeners.impl.RefactoringTransactionImpl in addAffectedElement at line 46
com.intellij.refactoring.listeners.impl.RefactoringTransactionImpl$MyRefactoringElementListener in <init> at line 73
(...)
```
I'm not sure how to replicate the issue but the source of the problem is pretty clear.
=> Fix NPE exception reported by Sentry

README.md
This PR adds a notice to the README letting people know that Cody is now deprecated and transitioned to a private repository.
CI
=> chore: add deprecation notice to README

.github/workflows/ci.yml, vscode/src/utils/plg-es-access.ts
When a failure occurs in the e2e tests, we upload some of the artifacts for access. However, the naming of this artifact isn't unique and when an artifact with the same name exists, it throws an error.
This PR makes the artifact name unique and overwrites it in the event that running the workflow multiple times returns an error
* CI
=> fix: resolve issue with artifacts naming 

jetbrains/src/main/kotlin/com/sourcegraph/cody/error/CodyConsole.kt, lib/shared/src/telemetry-v2/cody-tier.ts, vscode/src/output-channel-logger.ts
Enhanced the JetBrains Cody Console with multi-channel support, filtering capabilities, and improved UI.
- **Multi-channel support**: Console now creates separate tabs for different channels
- **Message filtering**: Added toggle to show only errors and warnings 
- **Custom toolbar**: Added clear and filter actions to each console tab
- **Message storage**: Console now stores messages for filtering and refreshing
- **Better error handling**: Improved message categorisation and display
- **Log level fix**: Upgraded VSCode output channels to use proper log levels
- **Telemetry logging fix**: Added `NotAuthenticated` tier to telemetry; previously serialisation failing when user was not authenticated and `tier` was `undefined`
1. Run `/gradlew :customRunIDE` and wait for Cody to start.
2. Open …
=> Improve Cody Console in JetBrains
